### ISSUE TITLE
All versions of a workflow definition are created when triggered

### ISSUE THREAD

**Issue by jamesdoran** [elsa-workflows/elsa-core#100]
I'm _loving_ this project and how quickly it's progressing. Keep up the awesome work Sipke.

Steps to reproduce:

- Create workflow definition with HttpRequestTrigger
- Publish
- Make a change to it (can just be moving a box)
- Publish again
- Make Http Request
- 2 instances of workflow created

It looks like the problem is in `WorkflowRegistry.ListByStartActivity`:

Is an additional where clause required?
`where workflow.IsPublished`

Sorry, I've not had chance to create a pull request.

**Comment by sfmskywalker** [comment]
Cheers for the encouragement!
I think you're spot-on. Don't worry about no PR, I'm happy with the bug report.

**Comment by sfmskywalker** [comment]
Fixed with #101
