### ISSUE TITLE
Workflow execution and expression evaluation error take 2

### ISSUE THREAD

**Issue by tomy2105** [elsa-workflows/elsa-core#1000]
In #983 expression evaluation exception was allowed to propagate and fault the execution, good work, thanks for that!

However, workflow instance exeuction journal still needs to be improved for this to be usable.

It currently contains limited stack trace with message saying: "An exception was thrown whilst setting 'WriteHttpResponse.Content'. See the inner exception for further details."

And the real Javascript evaluation error is hidden inside message of the inner exception. In my case (read from console log) it says: "TypeError: Cannot read property 'Trnd' of undefined".

![StackTraceResponse](https://user-images.githubusercontent.com/7658839/118508345-66bde900-b72f-11eb-909f-1bda696f72e4.png)

Could you please somehow "reveal" the content of the inner exception message because (in this case) it holds valuable information.

In addition it would be nice if output could be somehow improved so it doesn't get garbled like shown in the picture.

**Comment by sfmskywalker** [comment]
Yeah I noticed and was hoping you’d create a ticket for that ;)

I’ll try and work on this sometime this week. Something came up with higher priority (and will take some time to finish).
