### ISSUE TITLE
Loading Elsa Workflows with JSON

### ISSUE THREAD

**Issue by chandramohank** [elsa-workflows/elsa-core#1001]
https://github.com/elsa-workflows/elsa-core/discussions/506

I had a similar requirement as above where i need to use the json to load the workflows rather than using design. I used above example as reference to explore Elsa, but i am not able to trigger the workflow.

I have added my sample test code 
https://github.com/chandramohank/Elsa.Test

Below is the workflow i have added for testing

```

 {
  "activities": [
    {
      "id": "35470e3a-ebe1-4558-aa02-a556919b1764",
      "type": "Signaled",
      "left": 1230,
      "top": 941,
      "state": {
        "signal": {
          "expression": "RegisterUser",
          "syntax": "Literal"
        },
        "name": "",
        "title": "RegisterUser",
        "description": ""
      },
      "blocking": false,
      "executed": false,
      "faulted": false
    },
    {
      "id": "2c8b6772-9897-41fb-9097-b11f05e09b4d",
      "type": "Test",
      "left": 34,
      "top": 146,
      "state": {
        "name": "Test",
        "title": "",
        "description": ""
      },
      "blocking": false,
      "executed": false,
      "faulted": false
    }
  ],
  "connections": [
    {
      "sourceActivityId": "39ac31d6-68c7-41aa-8d3b-de5cf148982f",
      "destinationActivityId": "2c8b6772-9897-41fb-9097-b11f05e09b4d",
      "outcome": "Done"
    }
  ]
 }

```

below is the invocation logic

```
   [HttpPost]
   public async Task<IActionResult> Post()
   {
         await this.invoker.TriggerSignalAsync("RegisterUser", Variables.Empty);
         return Ok();
   }
```

As I am new to Elsa, please help me to understand what I am missing.

_Originally posted by @chandramohank in https://github.com/elsa-workflows/elsa-core/discussions/506#discussioncomment-751309_

**Comment by sfmskywalker** [comment]
Since Elsa 2.0 is very close to being released and you're just getting started, it might be better for you to try it with Elsa 2. If you run in any difficulties there, it will be easier for me to help out. Elsa 1 has a few issues that are solved with Elsa 2, which is the way forward.

**Comment by sfmskywalker** [comment]
Closing this because this refers to Elsa 1. Elsa 2 should be good, but please reopen this issue or create a new one specific to Elsa 2 if you run into any difficulties. Thanks!
