### ISSUE TITLE
An item with the same key has already been added

### ISSUE THREAD

**Issue by Aoshua** [elsa-workflows/elsa-core#1008]
Every once and a while, while creating workflows (via the designer), I get this error:
```
Failed to materialize workflow definition 98223cae81e44598b87a1c0a32a58bc8 with version 5
      System.ArgumentException: An item with the same key has already been added. Key: e7f34924-f2bf-4512-90b0-df05d8dfe993
```
If I delete that workflow and recreate it... suddenly things are fine again. I think that it may have to do with inserting a new custom activity between two activities (having already published?). Say I have activityA and activityB already, I add a new custom activity, activityC, in between. That new activity has a "technical name" of activityC, which I access now in activityB as `activityC.Output`. Some times this works fine... other times I get the above mentioned error and have to start over.

**Comment by sfmskywalker** [comment]
I've seen this happening too, but I haven't been able to reliably reproduce it as of yet. It's a tricky one.

**Comment by sfmskywalker** [comment]
I haven't seen this happening for some time now. I did see that sometimes the designer ends up adding the same activity (with same ID) when updating its properties, which is a slightly different issue. I will create a separate issue for that.
