### ISSUE TITLE
Multiple outcome in Composite Activity are not respected

### ISSUE THREAD

**Issue by jdevillard** [elsa-workflows/elsa-core#1012]
(_this seems to be a regression because it seems to work two weeks ago. Or something has changed and I've miss something_)

I've a composite activity with multiple outcome available [Done, Nack]. 

![image](https://user-images.githubusercontent.com/3254429/118895037-af2eff80-b905-11eb-8892-7ee0283891f6.png)

The Composite Activity log the outcome before finishing.
```
  branch
                     .When("Done")
                       .Then<WriteLine>(setup: s => { s.Set(x => x.Text, "Branch Done"); })
                     .Finish(setup => {
                         setup.Set(x => x.OutcomeNames, new[] { "Done" });
                         setup.Set(x => x.OutputValue, ctx => ctx.Input);

                     });

                     branch
                     .When("nack")
                     .Then<WriteLine>(setup: s => { s.Set(x => x.Text, "Branch nack"); })
                     .Finish(setup => {
                         setup.Set(x => x.OutcomeNames, new[] { "nack" });
                         setup.Set(x => x.OutputValue, ctx => ctx.Input);

                     });
```

Then I've connected WriteLine to check what branch is executed.

The result is the following :
![image](https://user-images.githubusercontent.com/3254429/118895172-f1f0d780-b905-11eb-9e6c-df2d1651a450.png)

as you can see , the **Branch nack** is written once and then the 2 console writeline are executed **Nack** and **done done done**

Here is a sample to reproduce the issue : 

```
  public class HelloWorld : IWorkflow
    {
        public void Build(IWorkflowBuilder builder) => builder
            .WriteLine("Hello World!")
            .Then<FirstLevel>(a =>
            {
                a
                    .When("nack")
                    .Then<WriteLine>(setup:s => { s.Set(x => x.Text, "nack in WF"); })
                    .Finish(setup =>
                    {
                        setup.Set(x => x.OutcomeNames, new[] { "nack" });
                        setup.Set(x => x.OutputValue, ctx => ctx.Input);
                    });

                a
                .When("done")
                .Then<WriteLine>(setup: s => { s.Set(x => x.Text, "done in WF"); })
                .Finish(setup =>
                {
                    setup.Set(x => x.OutcomeNames, new[] { "done" });
                    setup.Set(x => x.OutputValue, ctx => ctx.Input);
                });
             
            })
            ;
    }
    public class FirstLevel : CompositeActivity
    {
        public override void Build(ICompositeActivityBuilder activity)
        {
            activity
                  .Then<SecondLevel>(a =>
                  {
                      a
                          .When("nack")
                          .Then<WriteLine>(setup: s => { s.Set(x => x.Text, "nack in First Level"); })
                          .Finish(setup =>
                          {
                              setup.Set(x => x.OutcomeNames, new[] { "nack" });
                              setup.Set(x => x.OutputValue, ctx => ctx.Input);
                          });

                      a
                      .When("done")
                      .Then<WriteLine>(setup: s => { s.Set(x => x.Text, "done in First Level"); })
                      .Finish(setup =>
                      {
                          setup.Set(x => x.OutcomeNames, new[] { "done" });
                          setup.Set(x => x.OutputValue, ctx => ctx.Input);
                      });

                  });
        }
    }

    public class SecondLevel : Activity
    {
        protected override IActivityExecutionResult OnExecute()
        {

            return Combine(Output("nack content"), Outcome("nack"));            
        }
    }
```

this will print : 
Hello World!
nack in First Level
nack in WF
done in WF

instead of : 
Hello World!
nack in First Level
nack in WF

**Comment by jdevillard** [comment]
ok, 

so I've come back 20 days ago on the source code, and it seems to not be a regression. 

The fact is the "Done" Outcome is always bind to the next activity.  

If I resume with this schema

![image](https://user-images.githubusercontent.com/3254429/118967341-e257aa00-b96a-11eb-974f-87e83bde670f.png)

if A return Done : 
- B1 is Executed

If A return Nack :
- B2 is executed
- B1 is executed

and with the following schema 

![image](https://user-images.githubusercontent.com/3254429/118967511-18952980-b96b-11eb-8f47-b4c5c9a13211.png)

if A return Ack : 
- B1 is Executed

If A return Nack :
- B2 is executed


I think this behavior is why the IF/THEN work like that (outcome True/False/Done).

as I wrote this text, I had to mention that Activity A is a composite Activity and so maybe this post is related to #1018 ?

**Comment by sfmskywalker** [comment]
Indeed this behavior sounds like I would have expected given the way Composite Activities operated where it would always return **Done** as an outcome, regardless of any additional outcomes provided from the composite activity via the Finish activity.

However, a change was pushed yesterday that changes this behavior such that **Done** is only provided as an outcome if:

1. The composite activity does not provide any outcomes, and:
2. The composite activity is connected to another activity via the **Done** outcome

So in your case it should now work as you would have expected after pulling the latest version.

**Comment by sfmskywalker** [comment]
Closing this issue it's (supposed to be) fixed. Please feel free to reopen if you are still seeing the reported issue.

**Comment by jdevillard** [comment]
yes ! fixed 👍  Thanks.
