### ISSUE TITLE
Workflow execution and expression evaluation error take 3

### ISSUE THREAD

**Issue by tomy2105** [elsa-workflows/elsa-core#1016]
Yes, I am a very annoying guy :(......
In #1000 workflow instace journal shows expression evaluation exception, good work, thanks for that!

If I could plead to take that one step further......

Currently real reason, javascript error message, is hidden inside JSON stack trace, and is still really hard to find.

![StackTraceResponse2](https://user-images.githubusercontent.com/7658839/118960707-db796900-b963-11eb-8e0e-30d3f87f2da0.png)

Could we please make real reason a part of top level message?
In my case I'd like message to be: "Error setting 'WriteHttpResponse.Content' property: Cannot read property 'Trnd' of undefined.". The "Cannot read property 'Trnd' of undefined" is message of inner exception.

This way it would be immediately obvious from journal what went wrong.
Thank you very much :).

**Comment by tomy2105** [comment]
And yes, please change "exception" above JSONised stack trace to "Exception" :).

**Comment by sfmskywalker** [comment]
Please keep being annoying, I'm loving the improvements that come out of it :)

Before we tackle this one, I want to make sure you are still seeing the above after pulling the latest version, since I've been working on this a couple of hours ago - it should fix the issue you are describing.

Please let me know.

**Comment by tomy2105** [comment]
Yes, I see your changes, it is better.

![StackTraceResponse3](https://user-images.githubusercontent.com/7658839/118991221-d4625300-b983-11eb-92e3-cd748d542286.png)

IMHO, following changes would make it even better:
1. Place Message first, then Exception.
2. Make Message contain real Javascript error, like : "Error setting 'WriteHttpResponse.Content' property: Cannot read property 'Bar' of undefined". The "Cannot read property 'Bar' of undefined" is message of inner exception.

So it would look like this:
![StackTraceResponse4](https://user-images.githubusercontent.com/7658839/118992115-a29dbc00-b984-11eb-841b-d0ac99a6ccc7.png)

**Comment by sfmskywalker** [comment]
Would this work?

![image](https://user-images.githubusercontent.com/938393/119019702-bace0500-b99d-11eb-90fd-fc81c0bba1f5.png)

It's not exactly the same as you propose, but close enough and I'd venture to say detailed enough too.

Furthermore, you can click on the exception details which will automatically select the entire contents, making it easy to copy & paste into a text editor for further inspection.

**Comment by tomy2105** [comment]
Yes, close enough :).....

**Comment by sfmskywalker** [comment]
Excellent. Then I think we can close this issue. Thanks again for the suggestions!
