### ISSUE TITLE
Composite Activity and Workflow Instance viewer problem.

### ISSUE THREAD

**Issue by tomy2105** [elsa-workflows/elsa-core#1017]
I wrote composite activity, code is provided below.
Composite activity accepts http endpoint output as input through property (workflow attached [workflow-definition-test-composite.zip](https://github.com/elsa-workflows/elsa-core/files/6515091/workflow-definition-test-composite.zip)).
When I execute it, it works as expected.

However when I open Workflow Instance viewer of the execution I get NullReferenceException on line `return Request.Method == "GET";`. Seems at that point `Request` is `null` (only when viewing instance, when executing all is ok!).

Did I do something wrong? Should composite activity be written differently?

    public class OutcomeNames : Elsa.OutcomeNames
    {
        public const string Pass = "Pass";
        public const string Failed = "Failed";
    }

    [Action(
      Category = "TESTING",
      DisplayName = "Test Composite Activity",
      Description = "Test Composite Activity",
      Outcomes = new[] { OutcomeNames.Pass, OutcomeNames.Failed }
    )]

    public class TestContainer : CompositeActivity
    {
        [ActivityProperty(
            Label = "HTTP Request",
            UIHint = ActivityPropertyUIHints.SingleLine,
            DefaultSyntax = SyntaxNames.JavaScript,
            SupportedSyntaxes = new[] { SyntaxNames.JavaScript }
        )]
        public HttpRequestModel Request
        {
            get => GetState<HttpRequestModel>(() => null);
            set => SetState(value);
        }

        public override void Build(ICompositeActivityBuilder builder)
        {
            builder
                .If(method =>
                {
                    return Request.Method == "GET";
                },
                @if =>
                {
                    @if
                        .When(If.True)
                        .Then<WriteHttpResponse>(resp => resp
                            .WithStatusCode(HttpStatusCode.BadRequest)
                            .WithContent("*** GET IS BAD REQUEST")
                            .WithContentType("text/plain"))
                        .Finish(OutcomeNames.Failed);
                    @if
                        .When(If.False)
                        .Then<WriteHttpResponse>(resp => resp
                            .WithStatusCode(HttpStatusCode.OK)
                            .WithContent("*** POST IS GOOD REQUEST")
                            .WithContentType("text/plain"))
                        .Finish(OutcomeNames.Pass);
                });
        }
    }

**Comment by sfmskywalker** [comment]
As discussed in #1018 , this was by design, although the added value escapes me so I pushed a change.
