### ISSUE TITLE
Distributed Signals

### ISSUE THREAD

**Issue by sfmskywalker** [elsa-workflows/elsa-core#102]
In order to support multi-node environments (web farms, kubernetes, etc), it is important that local caches are evicted across all nodes. Currently, local caches get evicted that monitor `ISignal`. Providing a distributed implementation of `ISignal` will allow a single node to evict a given cache across all nodes. This works the same way it does in Orchard 1.

**Comment by sjd2021** [comment]
@sfmskywalker Is there an option to opt out of cache entirely? We don't use redis or rebus, and we don't want to tbh. But we pull stale workflow blueprints from one server when the other server added it to our db. Any way we can do that now without faking it out and just constantly purging all the cache keys?
