### ISSUE TITLE
Multiple Elsa instances against single database problem

### ISSUE THREAD

**Issue by tomy2105** [elsa-workflows/elsa-core#1020]
Using latest elsa 2 code I used sql server as elsa database using:

                    .UseEntityFrameworkPersistence(
                        ef => ef.UseSqlServer("some connection string") :
                    )

Then I did a test with two instances of elsa pointing against identical database. Test was as follows:

1. Start Elsa instance 1 on port 15265 (let's call it Elsa1)
2. Create and publish simple Elsa1workflow1 (attached [workflow-definition-elsa1-workflow1.zip](https://github.com/elsa-workflows/elsa-core/files/6516240/workflow-definition-elsa1-workflow1.zip)) - only HTTP Endpoint activity (get, post)
3. Execute Elsa1 workflow1 http://localhost:15265/elsa1workflow1 - everything is OK, executed and instance is shown on Elsa1
4. Start Elsa instance 2 on port 25265 (Elsa2) and check Elsa2 tab Workflow instances => everything is fine, instances and workflow definitions displayed OK
5. In Elsa1, modify elsa1workflow1 and publish
6. in Elsa1, execute elsa1workflow1 http://localhost:15265/elsa1workflow1 - everything is OK on Elsa1, executed and instance is shown
7. **However**: In Elsa2, open tab Workflow Instances => Instance id is displayed but workflow is not found '(Workflow definition not found)':

![WorkflowNotFound](https://user-images.githubusercontent.com/7658839/118986917-0c679700-b980-11eb-8c88-33b6e2d02466.jpg)

Moreover there is another problem (the cause is probably the same):
8. In Elsa2 browser, try to execute Elsa1Workflow1 on http://localhost:25265/elsa1workflow1. Workflow was not executed. 

So my first question. Is this setup supported/supposed to work?
And if yes, what is the reason that this errors happen?

**Comment by sfmskywalker** [comment]
One thing you might test is to stop both Elsa nodes and start them again. This time, both nodes should show the correct workflow definitions used by the workflow instances.

**Comment by tomy2105** [comment]
Yes, after both are restarted it does work but I think definitely this needs to be fixed so it works without restart.

**Comment by sfmskywalker** [comment]
Good, thanks for confirming. Yes absolutely, this is a release blocker.

**Comment by sfmskywalker** [comment]
This is fixed and guidance is [documented here](https://elsa-workflows.github.io/elsa-core/docs/next/hosting/hosting-distributed-hosting).
