### ISSUE TITLE
Multiple Elsa instances against single database problem and timer activity

### ISSUE THREAD

**Issue by tomy2105** [elsa-workflows/elsa-core#1021]
This might be caused by same issue described in #1020, but since I'm not sure filing this as a separate report.

Using latest elsa 2 code I used sql server as elsa database, using hangfire and/or quartz also configured to point to a same database.

Scenario is as follows:

1. Start Elsa instance 1 on port 15265 (let's call it Elsa1)   
2. Start Elsa instance 2 on port 25265 (Elsa2)
3. Create and publish simple Elsa2workflow2 (attached) - only HTTPEndpoint -> Timer (50s) -> Writeline  ([workflow-definition-elsa2-workflow2.zip](https://github.com/elsa-workflows/elsa-core/files/6516610/workflow-definition-elsa2-workflow2.zip))                 
4. in Elsa2, execute Elsa2workflow2. Elsa2workflows2 ends in Suspended state
5. Close Elsa2 instance before timer kicks off
6. Now, only Elsa1 is running.
7. Elsa1 **didn't start the suspended** Elsa2workflow2 witch was scheduled to run after 50s timeout:

![WorkfowSuspended](https://user-images.githubusercontent.com/7658839/118994063-4f2c6d80-b986-11eb-8aa5-8f5b87043a73.jpg)

When timer kicked of, in console there was an excpetion saying activity blueprint id wasn't found or something similar (forgot to write it down).

**Comment by sfmskywalker** [comment]
Thanks for the report, this is a great scenario to test again after #102 gets in. Given the exception about the missing blueprint, odds are it's the same issue - when publishing a workflow on node 1 (e.g. Elsa1), only that node will get an updated blueprint in memory, whilst the other nodes are still holding on to the memory-cached blueprints.

**Comment by tomy2105** [comment]
Just a comment on my part, I don't know the internal implementation well enough so maybe I'm on completely wrong track.
In #102 you are talking about distributed implementation of signaling that something should be evicted from cache, which is probably good idea but maybe complex to do.

Maybe the other way to do it to know locally if something is stale in cache and evict/re-fetch it.
For example blueprint version (if you somehow can know which is the last one) could be checked if current blueprint is stale and should be refetched or not. Don't know if this is possible or would be more complex than your solution, so just an idea.

**Comment by sfmskywalker** [comment]
Yes that would be ideal. But that's also where the rub lies: how do you know if something got stale?

**Comment by tomy2105** [comment]
I know, but maybe fetching just last published version of blueprint from db is less work than recreating whole blueprint.
So check version only without cache (or very short lived cache, less than 10s of seconds)
- if version is old
    - evict from cache and recreate whole blueprint

**Comment by sfmskywalker** [comment]
Interesting. Checking to see if there's a newer version (with a _very_ short lived cache) would do the trick too. But what I like with the distributed signals approach is that it is a more general-purpose cache eviction strategy which can be applied to more than just workflow blueprints being cached.

But I will keep all this in mind - thank you.

**Comment by sfmskywalker** [comment]
This is fixed and guidance is [documented here](https://elsa-workflows.github.io/elsa-core/docs/next/hosting/hosting-distributed-hosting).
