### ISSUE TITLE
Elsa 2 Rpc WorkflowDefinitionSerevice - latestOrPublished returns the latest published rather than the latest

### ISSUE THREAD

**Issue by matt4446** [elsa-workflows/elsa-core#1036]
Still on the YesSQL this time: 

A small hiccup on 'latestOrPublished': 
``` csharp 
this.WorkflowDefinition = await this.WorkflowDefinitionService.GetByIdAsync(this.WorkflowInstanceSummary.DefinitionId, VersionOptions.LatestOrPublished);
var workflowDefinition1 = await this.WorkflowDefinitionService.GetByIdAsync(this.WorkflowInstanceSummary.DefinitionId, VersionOptions.Latest);
var workflowDefinition2 = await this.WorkflowDefinitionService.GetByIdAsync(this.WorkflowInstanceSummary.DefinitionId, VersionOptions.Published);
var workflowDefinition3 = await this.WorkflowDefinitionService.GetByIdAsync(this.WorkflowInstanceSummary.DefinitionId);
```

I have a definition with 4 versions where v4 is the latest, and v3 is the latest published. 

- [x] latest - is correct (v4) 
- [x] Published is correct (v3)
- [ ] LatestOrPublished is incorrect (v3) - should be v4? 
- [ ] Default - Should it be the latest published or just latest?

**Comment by sfmskywalker** [comment]
The results are actually correct: `LatestOrPublished` should return the published version if there is one, and if not, return the latest version. But I can see how the name is confusing - a better name would probably be `PublishedOrLatest`.

`Default` should return the published version only. Which means that if there is no published version present, it will return null.

**Comment by matt4446** [comment]
That name will bug me 🤣. I think I've tripped up some other sections of my code as well in that case.  It would be useful to have a summary for these static fields, but I'll remember for now: 

```
public static readonly VersionOptions Latest;
public static readonly VersionOptions Published;
public static readonly VersionOptions LatestOrPublished;
public static readonly VersionOptions Draft;
public static readonly VersionOptions All;
```

**Comment by sfmskywalker** [comment]
Then I won't change the name (for now 😉 ).
Yeah good point, this needs to be documented somewhere. For now I update the XML comments. Better than nothing!
