### ISSUE TITLE
Designer -> HTTP Response -> Content not retaining value

### ISSUE THREAD

**Issue by atorres16** [elsa-workflows/elsa-core#1038]
I type something in "Content", save it, but the value is not retained

(I'm running the "AspnetCore.Monolith" sample from source)

![image](https://user-images.githubusercontent.com/19210281/119517538-51534b00-bd3d-11eb-8e38-f68939b4a448.png)

**Comment by sfmskywalker** [comment]
I just tried the same (`ElsaDashboard.Samples.AspNetCore.Monolith` from source) - I did make sure to run the `build-assets.ps1` file first. 

Do you get the same issue when running it from the Docker image?

```
docker run -t -i -e ELSA__SERVER__BASEURL='http://localhost:13000' -e ASPNETCORE_ENVIRONMENT='Development' -p 13000:80 elsaworkflows/elsa-dashboard-and-server:latest
```

**Comment by atorres16** [comment]
I pulled the latest changes this morning, I'll clone again, thanks

**Comment by atorres16** [comment]
I cloned the project, ran the ps1 script, restored and rebuilt, but I still have the same issue

**Comment by atorres16** [comment]
It's weird, I restarted the debugger and it works fine
