### ISSUE TITLE
Dashboard formatting needs improvement

### ISSUE THREAD

**Issue by MiroslavMikus** [elsa-workflows/elsa-core#1048]
Hey, I'm running
`commit 6889b0cf38f463c4fe2206e4ec123fc2195eddf7` in docker and there was some exception..

![image](https://user-images.githubusercontent.com/29312172/119736629-4d7b1200-be7e-11eb-9d54-2bce4f7a3a05.png)

.. and some more ..
![elsa](https://user-images.githubusercontent.com/29312172/119737220-3983e000-be7f-11eb-9283-f89cf1793c9b.gif)

BTW Congrats on the second release 🎊 👍 😄

**Comment by sfmskywalker** [comment]
Indeed that doesn't look good. Looks like the image is being built with an older commit. Will investigate.

**Comment by sfmskywalker** [comment]
Looks like it was an issue with the docker build pipeline using older layers. I pushed a new build and pulled it from Docker Hub, and now it looks good for me (I did have to do a hard-refresh / CTRL+F5 in the browser):

![image](https://user-images.githubusercontent.com/938393/119890415-1832fa80-bf38-11eb-945f-1c7fff78c0fb.png)
