### ISSUE TITLE
Elsa 2.0 Why is Elsa.DistributedLocking.Redis Nuget is lagging behind at 2.0.0-rc2.73?

### ISSUE THREAD

**Issue by AvtsVivek** [elsa-workflows/elsa-core#1049]
While other [Elsa Nugets](https://www.nuget.org/packages/Elsa) are at 2.0.0.159, why is [Elsa.DistributedLocking.Redis Nuget ](https://www.nuget.org/packages/Elsa.DistributedLocking.Redis/2.0.0-rc2.73 )is lagging behind at rc2.73? Am I missing something here?

**Comment by sfmskywalker** [comment]
Looks like that class library project got lost in the frey - it's no longer there in the solution. I will add it back. Thanks for letting me know!

**Comment by sfmskywalker** [comment]
Pushed. Will deploy to NuGet soon.
