### ISSUE TITLE
The links to source codes in Elsa guides website are incorrect

### ISSUE THREAD

**Issue by AvtsVivek** [elsa-workflows/elsa-core#1051]
The links on this [**A Simple Document Approval Workflow**](https://elsa-workflows.github.io/elsa-core/docs/next/guides/guides-document-approval) page are incorrect. 

The github [guides repo link is here](https://github.com/elsa-workflows/elsa-website/blob/elsa-2.0/docs/guides/guides-document-approval.md).

![image](https://user-images.githubusercontent.com/41255281/119825667-d2b10600-bf14-11eb-9dbe-5b9f51279dca.png)

The corrected links should be as follows, as I tried to figure out.

https://github.com/elsa-workflows/elsa-guides/tree/master/src/ElsaGuides.ContentApproval.Web
https://github.com/elsa-workflows/elsa-guides/blob/master/src/ElsaGuides.ContentApproval.Web/VisualDocumentApprovalWorkflow.json

I tried to push the changes, but I dont have write access. 

![image](https://user-images.githubusercontent.com/41255281/119826331-8914eb00-bf15-11eb-8e11-2277bc346d65.png)

**Comment by sfmskywalker** [comment]
You're right; thanks for reporting! I will fix.

**Comment by sfmskywalker** [comment]
By the way, if you wish to push fixes (which I would highly appreciate of course 😄 ) you need to first fork the project, clone that one, make the changes and then submit a PR.

Let me know if you need help with that!

**Comment by sfmskywalker** [comment]
Fixed in [d49f3ed4dd486273eec821b2fe79d405c6be36a5](https://github.com/elsa-workflows/elsa-website/commit/d49f3ed4dd486273eec821b2fe79d405c6be36a5)
