### ISSUE TITLE
JS Expression setVariable not working if value is an object

### ISSUE THREAD

**Issue by atorres16** [elsa-workflows/elsa-core#1054]
It works ok If the variable is set via the visual Activity in the designer, but if you try to set it via Javascript expression, it fails

1. Works (I do get the JSON object in the response):
    
![image](https://user-images.githubusercontent.com/19210281/119903848-f3765d00-bf0e-11eb-96de-ba31809f64f5.png)

2. Doesn't work (I get null in the response):

![image](https://user-images.githubusercontent.com/19210281/119903966-2b7da000-bf0f-11eb-9e74-44fc5a376c8b.png)

(The value I'm trying to set in the variable is a Json object)

I noticed that, when it comes from JS expression, the value is of type ExpandoObject instead of a dictionary, in this test, I converted it into a dictionary and it worked

(https://github.com/elsa-workflows/elsa-core/blob/master/src/core/Elsa.Abstractions/Models/Variables.cs)
![image](https://user-images.githubusercontent.com/19210281/119904155-7dbec100-bf0f-11eb-87c1-a3b6d2359729.png)

**Comment by atorres16** [comment]
I'm attaching the model, and the two workflows if you want to test some day

[tests.zip](https://github.com/elsa-workflows/elsa-core/files/6557140/tests.zip)

**Comment by sfmskywalker** [comment]
I've recently changed the way variables are persisted. Perhaps you can give it another go?

**Comment by atorres16** [comment]
I tried, but it's throwing an error, I cloned the project and tried again but I get:
![image](https://user-images.githubusercontent.com/19210281/122629416-74de8c80-d082-11eb-871c-257dfd1cb75f.png)

I run the ps1 file twice

**Comment by atorres16** [comment]
It works! thanks!
