### ISSUE TITLE
Parallel Foreach Child Workflow pass variable to Parent Workflow

### ISSUE THREAD

**Issue by deu2019** [elsa-workflows/elsa-core#1056]
I am working with Elsa2.0 to develop a "multi dispatch then join" Approval workflow using  dashboard.
this is what I have designed.
![image](https://user-images.githubusercontent.com/48954978/119951544-a5c12980-bfce-11eb-88a1-052d8b853d95.png)

What I expect：
1."Parallel For Each" receive a post with payload
{
​    "Collection":["a","b","c"]
}
then trigger a child workflow with correlateid "a"、"b"、"c".
2.each "subworkflow“ receive a post with payload "payloadA"、"payloadB"、"payloadC"
3.”Join“ wait all child workflows done then merge ”payloadA“、”payloadB“、”payloadC“ as output.
4."Write Line" print "Join" output to console.

Actually Happens:
1.work as expected.
2、3.when i trigger ”subworkflow“ with correlateId ”a“、”b“、”c“， always the last item，in this case ”c“ trigger the ”Join“ action，the other correlateId just run the child workflow and trigger nothing.
4.unable to print merge data.

So the question is :
1.how to set the "join" node, make it be triggered after all child workflow done?
2.how to pass child workflow node data to parent workflow?

**Comment by deu2019** [comment]
here is the master workflow definition json

**Comment by deu2019** [comment]
{
  "$id": "1",
  "definitionId": "d9f3d78c18f3487fb375c1a8d7764500",
  "versionId": "1bbeb556f6c84a8d9dff4d4ef6a08f40",
  "name": "workflow7",
  "displayName": "workflow7",
  "version": 37,
  "variables": {
    "$id": "2",
    "data": {}
  },
  "customAttributes": {
    "$id": "3",
    "data": {}
  },
  "contextOptions": {
    "$id": "4",
    "contextFidelity": "Activity"
  },
  "isSingleton": false,
  "persistenceBehavior": "ActivityExecuted",
  "deleteCompletedInstances": false,
  "isPublished": false,
  "isLatest": true,
  "activities": [
    {
      "$id": "5",
      "activityId": "fb8ed6d9-f033-4fa1-8d60-6e63727ffeab",
      "type": "HttpEndpoint",
      "name": "node01endpoint",
      "displayName": "HTTP Endpoint",
      "persistWorkflow": true,
      "loadWorkflowContext": true,
      "saveWorkflowContext": true,
      "persistOutput": true,
      "properties": [
        {
          "$id": "6",
          "name": "Path",
          "expressions": {
            "$id": "7",
            "Literal": "/workflow7/node01"
          }
        },
        {
          "$id": "8",
          "name": "Methods",
          "expressions": {
            "$id": "9",
            "Json": "[\"POST\"]"
          }
        },
        {
          "$id": "10",
          "name": "ReadContent",
          "expressions": {
            "$id": "11",
            "Literal": "true"
          }
        },
        {
          "$id": "12",
          "name": "TargetType",
          "expressions": {
            "$id": "13"
          }
        }
      ]
    },
    {
      "$id": "14",
      "activityId": "9110e03c-5178-4a85-9674-8a559412333c",
      "type": "SetVariable",
      "displayName": "Set Variable",
      "persistWorkflow": false,
      "loadWorkflowContext": false,
      "saveWorkflowContext": false,
      "persistOutput": false,
      "properties": [
        {
          "$id": "15",
          "name": "VariableName",
          "expressions": {
            "$id": "16",
            "Literal": "node01"
          }
        },
        {
          "$id": "17",
          "name": "Value",
          "syntax": "JavaScript",
          "expressions": {
            "$id": "18",
            "JavaScript": "node01endpoint.Output.Body;"
          }
        }
      ]
    },
    {
      "$id": "19",
      "activityId": "c26aa301-f0b4-47af-9fd2-a200429f2a3d",
      "type": "WriteHttpResponse",
      "displayName": "HTTP Response",
      "persistWorkflow": false,
      "loadWorkflowContext": false,
      "saveWorkflowContext": false,
      "persistOutput": false,
      "properties": [
        {
          "$id": "20",
          "name": "StatusCode",
          "expressions": {
            "$id": "21"
          }
        },
        {
          "$id": "22",
          "name": "Content",
          "expressions": {
            "$id": "23",
            "Literal": "node01node01node01node01node01node01node01node01node01node01node01node01node01node01node01node01node01node01node01"
          }
        },
        {
          "$id": "24",
          "name": "ContentType",
          "expressions": {
            "$id": "25"
          }
        }
      ]
    },
    {
      "$id": "26",
      "activityId": "b6a51ef8-014c-4bea-902b-7fe29ce736f3",
      "type": "RunWorkflow",
      "name": "subworflow",
      "displayName": "subworkflow",
      "persistWorkflow": true,
      "loadWorkflowContext": true,
      "saveWorkflowContext": true,
      "persistOutput": true,
      "properties": [
        {
          "$id": "27",
          "name": "WorkflowDefinitionId",
          "expressions": {
            "$id": "28",
            "Literal": "9923fdc6dbeb4e16a90c166b39692848"
          }
        },
        {
          "$id": "29",
          "name": "Input",
          "syntax": "JavaScript",
          "expressions": {
            "$id": "30",
            "JavaScript": "input;"
          }
        },
        {
          "$id": "31",
          "name": "Mode",
          "expressions": {
            "$id": "32",
            "Literal": "Blocking"
          }
        },
        {
          "$id": "33",
          "name": "TenantId",
          "expressions": {
            "$id": "34"
          }
        },
        {
          "$id": "35",
          "name": "CorrelationId",
          "syntax": "JavaScript",
          "expressions": {
            "$id": "36",
            "JavaScript": "input;"
          }
        },
        {
          "$id": "37",
          "name": "ContextId",
          "expressions": {
            "$id": "38"
          }
        }
      ]
    },
    {
      "$id": "39",
      "activityId": "7904ec48-9d5d-4b3a-856f-16d112f48025",
      "type": "Join",
      "displayName": "Join",
      "persistWorkflow": true,
      "loadWorkflowContext": true,
      "saveWorkflowContext": true,
      "persistOutput": true,
      "properties": [
        {
          "$id": "40",
          "name": "Mode",
          "expressions": {
            "$id": "41"
          }
        }
      ]
    },
    {
      "$id": "42",
      "activityId": "a28b146e-d971-4fbf-ad1c-20b0eaa692b6",
      "type": "WriteLine",
      "displayName": "Write Line",
      "persistWorkflow": false,
      "loadWorkflowContext": false,
      "saveWorkflowContext": false,
      "persistOutput": false,
      "properties": [
        {
          "$id": "43",
          "name": "Text",
          "syntax": "JavaScript",
          "expressions": {
            "$id": "44",
            "Literal": "joinjoinjoinjoinjoinjoinjoinjoinjoinjoinjoinjoinjoinjoinjoinjoinjoinjoinjoinjoinjoinjoinjoinjoinjoinjoinjoinjoinjoinjoinjoinjoinjoinjoinjoinjoin",
            "JavaScript": "'*****************************************' + 'join wait all ' + JSON.stringify(input);"
          }
        }
      ]
    },
    {
      "$id": "45",
      "activityId": "b1da120c-55be-41be-8047-2d2c4b4322b8",
      "type": "ParallelForEach",
      "displayName": "Parallel For Each",
      "persistWorkflow": false,
      "loadWorkflowContext": false,
      "saveWorkflowContext": false,
      "persistOutput": false,
      "properties": [
        {
          "$id": "46",
          "name": "Items",
          "syntax": "JavaScript",
          "expressions": {
            "$id": "47",
            "JavaScript": "node01.Collection;"
          }
        }
      ]
    }
  ],
  "connections": [
    {
      "$id": "48",
      "sourceActivityId": "fb8ed6d9-f033-4fa1-8d60-6e63727ffeab",
      "targetActivityId": "9110e03c-5178-4a85-9674-8a559412333c",
      "outcome": "Done"
    },
    {
      "$id": "49",
      "sourceActivityId": "7904ec48-9d5d-4b3a-856f-16d112f48025",
      "targetActivityId": "a28b146e-d971-4fbf-ad1c-20b0eaa692b6",
      "outcome": "Done"
    },
    {
      "$id": "50",
      "sourceActivityId": "9110e03c-5178-4a85-9674-8a559412333c",
      "targetActivityId": "c26aa301-f0b4-47af-9fd2-a200429f2a3d",
      "outcome": "Done"
    },
    {
      "$id": "51",
      "sourceActivityId": "b1da120c-55be-41be-8047-2d2c4b4322b8",
      "targetActivityId": "b6a51ef8-014c-4bea-902b-7fe29ce736f3",
      "outcome": "Iterate"
    },
    {
      "$id": "52",
      "sourceActivityId": "c26aa301-f0b4-47af-9fd2-a200429f2a3d",
      "targetActivityId": "b1da120c-55be-41be-8047-2d2c4b4322b8",
      "outcome": "Done"
    },
    {
      "$id": "53",
      "sourceActivityId": "b6a51ef8-014c-4bea-902b-7fe29ce736f3",
      "targetActivityId": "7904ec48-9d5d-4b3a-856f-16d112f48025",
      "outcome": "Done"
    }
  ],
  "id": "1bbeb556f6c84a8d9dff4d4ef6a08f40"
}

**Comment by sfmskywalker** [comment]
This is a similar problem as reported in #1025.

Unfortunately there is a limitation with the workflow engine where it cannot handle parallel scopes. This is a design oversight that I plan on fixing in #1059.
