### ISSUE TITLE
Introduce Multiple & Nested Execution Scopes

### ISSUE THREAD

**Issue by sfmskywalker** [elsa-workflows/elsa-core#1059]
Currently it is not possible for Elsa to handle multiple execution scopes, which makes activities such as **Parallel ForEach** very limited as reported in #1025 and #1056

### Execution Scope

An execution scope would maintain its own set of variables and blocking activities, so that when a blocking activity is triggered, it is resumed in the right scope with access to variables and other state recorded at the time of suspension.

Having execution scopes also simplify the "unwinding" logic that is currently in place for activities such as **If**, **While** and **For** and **ForEach** by having clear boundaries implemented as a scope.

**Comment by Nokecy** [comment]
Need this feature ~~~ @sfmskywalker

**Comment by ddydeveloper** [comment]
Just wondering would it be working solution to have a couple of variables like `numberOfIterations` (set once when ParallelForEach defined) and `finishedIterations` (update it when each iteration completed) inside `ActivityExecutionContext` which we could use to compare and unblock workflow.

```
...
.ParallelForEach(() => {
   // set numberOfIterations
})
.WaitAll(() => {
   // compare numberOfIterations with finishedIterations
})
.Then<Activity>
...
```

**Comment by sfmskywalker** [comment]
Something like that could work. It would be similar to the way the `Join` activity blocks until all inbound connections have executed (when using `JoinMode.WaitAll`. But I don't think it will solve the issue of not being able to block within an iteration branch itself. Technically speaking, one could block (one bookmark per iteration would be created) - but the issue is when you want to resume one of the blocked iterations - there's no context being tracked. 

In Elsa 3, each parallel execution will have its own activity execution context, which can store contextual information such as the current value of the iteration (and other variables scoped to the iteration).

**Comment by maltegoetz** [comment]
@sfmskywalker Is there a reason why this was removed from Elsa 3.0 milestone? This seems pretty important to me.

**Comment by sfmskywalker** [comment]
@maltegoetz I removed all issues from the milestone in order to re-evaluate what should be part of the initial milestone and do some backlog grooming. And you're right, this issue is important and will be added back.

**Comment by sfmskywalker** [comment]
Parallel ForEach is now available in Elsa 3 via https://github.com/elsa-workflows/elsa-core/pull/4306
