### ISSUE TITLE
Elsa 2.0 Mistake and a bug in guide

### ISSUE THREAD

**Issue by AvtsVivek** [elsa-workflows/elsa-core#1061]
I found the following.

1. The Reject spelling is incorrect [here](https://elsa-workflows.github.io/elsa-core/docs/next/guides/guides-document-approval#send-reminder-email-to-josh-the-approver). Its **Rejecte**, there is 'e' after t. 

![image](https://user-images.githubusercontent.com/41255281/120057777-71e41380-c063-11eb-9bd3-10cf5d37668e.png)

2.  Next there are 2 double quotes [here](https://elsa-workflows.github.io/elsa-core/docs/next/guides/guides-document-approval#send-email-to-josh-the-approver). I think this is a minor one.

![image](https://user-images.githubusercontent.com/41255281/120057804-b2439180-c063-11eb-9622-e6494ec81c1d.png)

**Comment by sfmskywalker** [comment]
Indeed. Thanks for pointing those out!
