### ISSUE TITLE
Radio List is not rendering on activity editor 

### ISSUE THREAD

**Issue by sundar91** [elsa-workflows/elsa-core#1062]
I was trying to explore activity property type, but I have noticed that radio list is not rendering on UI.

` [ActivityProperty(
          UIHint = ActivityPropertyUIHints.RadioList,
          Options = new[] { "MongoDb", "YesSql" } )]`

I found out that there no component for radio button list in designer application. 

Also I am looking for Dependent Property where options values are dependent on another property (on change of property we dynamically want to load the options for another field).

**Comment by sfmskywalker** [comment]
Thanks for reporting!

> Also I am looking for Dependent Property where options values are dependent on another property (on change of property we dynamically want to load the options for another field).

Perhaps you can create a separate issue for this? And maybe elaborate a bit on how you would expect the options for the cascading list items would come from? Would you expect some JS event to be triggered so your own JS code can handle this, or an HTTP call, or maybe both?
