### ISSUE TITLE
Calculate no. of years from given date

### ISSUE THREAD

**Issue by adityaazilen** [elsa-workflows/elsa-core#1066]
Need a function which will calculate no. of years from a given date. 

Input parameter : 08/20/1990(mm/dd/yyyy)
Output:31 years

**Comment by tomy2105** [comment]
You can probably achieve this using Javascript expression (all the usual nuances about date parsing and formats included :))....

**Comment by sfmskywalker** [comment]
Indeed. Still, it would be nice to have it as a function out of the box given the fact that we already have a plethora of date/time functions out of the box. It's what I like a lot about Logic Apps - a lot of convenient date/time parsing and modifying functions.

**Comment by sfmskywalker** [comment]
You can now calculate the number of years between now and a date in the past using the `periodFromNow` JS function. Example:

```javascript
const pastInstant = instantFromUtc(1990, 8, 20);
const period = periodFromNow(pastInstant);

return period.Years; // Returns 31
```
