### ISSUE TITLE
Send HTTP Request activity should create a outcome per status code

### ISSUE THREAD

**Issue by ldias91** [elsa-workflows/elsa-core#1069]
I have this:

![image](https://user-images.githubusercontent.com/51196891/120176625-69284480-c1ff-11eb-97ca-d4ab2206b223.png)

but, has only one outcome "done"

![image](https://user-images.githubusercontent.com/51196891/120176703-83622280-c1ff-11eb-95b2-48edadf11a6c.png)

**Comment by ldias91** [comment]
Hi @sfmskywalker, sorry for replying on a closed issue.

but if no supported status code is defined the outcome "done" must be displayed, and if any supported status code is defined the outcome "UnSupportedStatusCode" must be displayed.

thanks

**Comment by sfmskywalker** [comment]
You're right about "UnSupportedStatusCode". Regarding "Done", I'm thinking that this outcome should always be available for scenarios where you do not care about the actual response status.
