### ISSUE TITLE
HTTP Endpoint model problems with Javascript expression 

### ISSUE THREAD

**Issue by tomy2105** [elsa-workflows/elsa-core#1070]
If you use HTTP Endpoint model inside Javascript expression using stringify, for example:
`JSON.stringify(input)` and last activity was HTTP Endpoint you will be greeted by following fault in the workflow instance:

    {
        "InnerException" :
        {
            "InnerException" : null,
            "Message" : "This operation is not supported for a relative URI.",
            "StackTrace" : " at Jint.Runtime.ExceptionHelper.ThrowMeaningfulException(Engine engine, TargetInvocationException exception) at Jint.Runtime.Descriptors.Specialized.PropertyInfoDescriptor.get_CustomValue() at Jint.Native.Object.ObjectInstance.UnwrapJsValue(PropertyDescriptor desc, JsValue thisObject) at Jint.Native.Object.ObjectInstance.Get(JsValue property, JsValue receiver) at Jint.Runtime.Interop.ObjectWrapper.Get(JsValue property, JsValue receiver) at Jint.Native.Json.JsonSerializer.Str(JsValue key, ObjectInstance holder) at Jint.Native.Json.JsonSerializer.SerializeObject(ObjectInstance value) at Jint.Native.Json.JsonSerializer.Str(JsValue key, ObjectInstance holder) at Jint.Native.Json.JsonSerializer.SerializeObject(ObjectInstance value) at Jint.Native.Json.JsonSerializer.Str(JsValue key, ObjectInstance holder) at Jint.Native.Json.JsonSerializer.SerializeObject(ObjectInstance value) at Jint.Native.Json.JsonSerializer.Str(JsValue key, ObjectInstance holder) at Jint.Native.Json.JsonSerializer.Serialize(JsValue value, JsValue replacer, JsValue space) at Jint.Native.Json.JsonInstance.Stringify(JsValue thisObject, JsValue[] arguments) at Jint.Runtime.Interop.ClrFunctionInstance.Call(JsValue thisObject, JsValue[] arguments) at Jint.Runtime.Interpreter.Expressions.JintCallExpression.EvaluateInternal() at Jint.Runtime.Interpreter.Expressions.JintExpression.GetValue() at Jint.Runtime.Interpreter.Statements.JintExpressionStatement.ExecuteInternal() at Jint.Runtime.Interpreter.JintStatementList.Execute() at Jint.Engine.Execute(Script program) at Jint.Engine.Execute(String source, ParserOptions parserOptions) at Jint.Engine.Execute(String source) at Elsa.Scripting.JavaScript.Services.JintJavaScriptEvaluator.ExecuteExpressionAndGetResult(Engine engine, String expression) in D:\Projects\Envox\Mainline\ThirdParty\elsa-core\src\scripting\Elsa.Scripting.JavaScript\Services\JintJavaScriptEvaluator.cs:line 62 at Elsa.Scripting.JavaScript.Services.JintJavaScriptEvaluator.EvaluateAsync(String expression, Type returnType, ActivityExecutionContext context, Action`1 configureEngine, CancellationToken cancellationToken) in D:\Projects\Envox\Mainline\ThirdParty\elsa-core\src\scripting\Elsa.Scripting.JavaScript\Services\JintJavaScriptEvaluator.cs:line 39 at Elsa.Scripting.JavaScript.Services.JavaScriptExpressionHandler.EvaluateAsync(String expression, Type returnType, ActivityExecutionContext context, CancellationToken cancellationToken) in D:\Projects\Envox\Mainline\ThirdParty\elsa-core\src\scripting\Elsa.Scripting.JavaScript\Services\JavaScriptExpressionHandler.cs:line 22 at Elsa.Expressions.ExpressionEvaluator.EvaluateAsync(String expression, String syntax, Type returnType, ActivityExecutionContext context, CancellationToken cancellationToken) in D:\Projects\Envox\Mainline\ThirdParty\elsa-core\src\core\Elsa.Core\Expressions\ExpressionEvaluator.cs:line 43 at Elsa.Services.ExpressionActivityPropertyValueProvider.GetValueAsync(ActivityExecutionContext context, CancellationToken cancellationToken) in D:\Projects\Envox\Mainline\ThirdParty\elsa-core\src\core\Elsa.Core\Services\ExpressionActivityPropertyValueProvider.cs:line 28 at Elsa.Services.ActivityPropertyProviders.SetActivityPropertiesAsync(IActivity activity, ActivityExecutionContext activityExecutionContext, CancellationToken cancellationToken) in D:\Projects\Envox\Mainline\ThirdParty\elsa-core\src\core\Elsa.Abstractions\Services\ActivityPropertyProviders.cs:line 63",
            "Type" : "System.InvalidOperationException"
        }
        ,
        "Message" : "An exception was thrown whilst setting 'WriteHttpResponse.Content'. See the inner exception for further details.",
        "StackTrace" : " at Elsa.Services.ActivityPropertyProviders.SetActivityPropertiesAsync(IActivity activity, ActivityExecutionContext activityExecutionContext, CancellationToken cancellationToken) in D:\Projects\Envox\Mainline\ThirdParty\elsa-core\src\core\Elsa.Abstractions\Services\ActivityPropertyProviders.cs:line 76 at Elsa.Services.ActivityActivator.ActivateActivityAsync(ActivityExecutionContext context, Type type, CancellationToken cancellationToken) in D:\Projects\Envox\Mainline\ThirdParty\elsa-core\src\core\Elsa.Core\Services\ActivityActivator.cs:line 31 at Elsa.ActivityTypeProviders.TypeBasedActivityProvider.<>c__DisplayClass6_0.<b__3>d.MoveNext() in D:\Projects\Envox\Mainline\ThirdParty\elsa-core\src\core\Elsa.Core\ActivityTypeProviders\TypeBasedActivityProvider.cs:line 53 --- End of stack trace from previous location --- at Elsa.Services.WorkflowRunner.TryExecuteActivityAsync(ActivityOperation activityOperation, ActivityExecutionContext activityExecutionContext, RuntimeActivityInstance activity, CancellationToken cancellationToken) in D:\Projects\Envox\Mainline\ThirdParty\elsa-core\src\core\Elsa.Core\Services\WorkflowRunner.cs:line 278",
        "Type" : "Elsa.Exceptions.CannotSetActivityPropertyValueException"
    }

The culprit seems to be `Uri` class inside `HttpRequestModel`. If changed to string everything works as expected.
Can we either change model or have correct converter added so this model works ok with Javascript?

**Comment by sfmskywalker** [comment]
I just tried to reproduce this issue, but when I try with the following workflow, it works:

[workflow-definition-http-demo.zip](https://github.com/elsa-workflows/elsa-core/files/6682173/workflow-definition-http-demo.zip)

Response:

```json
{"Path":{"OriginalString":"/demo","IsAbsoluteUri":false,"UserEscaped":false,"UriSchemeFile":"file","UriSchemeFtp":"ftp","UriSchemeGopher":"gopher","UriSchemeHttp":"http","UriSchemeHttps":"https","UriSchemeMailto":"mailto","UriSchemeNews":"news","UriSchemeNntp":"nntp","UriSchemeNetTcp":"net.tcp","UriSchemeNetPipe":"net.pipe","SchemeDelimiter":"://"},"Method":"GET","QueryString":{},"Headers":{":authority":"localhost:11000",":method":"GET",":path":"/workflows/demo",":scheme":"https","Accept":"text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9","Accept-Encoding":"gzip, deflate, br","Accept-Language":"en-US,en;q=0.9,nl;q=0.8","Cookie":"Default-adminPreferences={%22leftSidebarCompact%22:false%2C%22isCompactExplicit%22:false%2C%22darkMode%22:false},hblid=cYQVBQElPmM60BqS3m39N0NC24brOhjo,olfsk=olfsk39550985764505286","Host":"localhost:11000","User-Agent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.101 Safari/537.36 Edg/91.0.864.48","Upgrade-Insecure-Requests":"1","sec-ch-ua":"\" Not;A Brand\";v=\"99\", \"Microsoft Edge\";v=\"91\", \"Chromium\";v=\"91\"","sec-ch-ua-mobile":"?0","sec-fetch-site":"none","sec-fetch-mode":"navigate","sec-fetch-user":"?1","sec-fetch-dest":"document"},"Body":null}
```

Maybe it was fixed by accident? 😀

**Comment by tomy2105** [comment]
Yeah, it works with 2.1 git code but not with 2.0 NuGet one.
It would be interesting to see what you changed to make it work :).
And maybe path should be string and not Uri because as you see in this case it just contains bunch of useless stuff (absolute uri will always be false, user escaped also, and others are hardcoded constants :))....

**Comment by sfmskywalker** [comment]
Good point. Let's indeed change it to `string`. One can always parse that should they find the need to do so.
