### ISSUE TITLE
HttRequest activity headers features

### ISSUE THREAD

**Issue by dust63** [elsa-workflows/elsa-core#1078]
In the dashboard workflow edition allow user to add headers on http request activity. 
In some rest apis we need to send a header to pass the access token.

Example:

x-api-token: "010254545450454"

**Comment by sfmskywalker** [comment]
Just pushed an update that allows you to do this using a JSON format like so:

```json
{
   "x-api-token": "010254545450454"
}
```

**Comment by dust63** [comment]
Thank you. I think it should be interesting to add a Key Value pair display in the dashboard

![image](https://user-images.githubusercontent.com/13755387/121128887-67c4d080-c82c-11eb-986b-29e27e7ddb92.png)

**Comment by sfmskywalker** [comment]
Agreed, much more user friendly. Same goes for the Variables tab on the Workflow settings window.
