### ISSUE TITLE
context.GetVariable not working with Mongodb UseMongoDbPersistence

### ISSUE THREAD

**Issue by ricksearcy** [elsa-workflows/elsa-core#1088]
I have tested this issue with multiple workflow examples, but for reproduction I will stick with one of yours. 

In the code below if I use .UseEntityFrameworkPersistence(ef => ef.UseSqlite()) everything runs as expected. 

If I try to use the mongo persistence everything initially runs, and the collections are created in the DB, but anything that tries to access a saved variable using context.GetVariable after the initial http request will get a null reference. My gut tells me it's probably a serialization issue with mongo, but I have not gone thru the source code. 
.UseMongoDbPersistence(opts =>
                    {
                        opts.ConnectionString = myserverconn;
                        opts.DatabaseName = dbName;
                    })
This line will always fail: .WithSubject(context => $"{context.GetVariable<dynamic>("Document")!.Author.Name} is waiting for your review!")

Is there something I'm missing when using mongo as the persistence provider?

 public void Build(IWorkflowBuilder builder)
        {
            builder
                .WithDisplayName("Document Approval Workflow")
                .HttpEndpoint(activity => activity
                    .WithPath("/v1/documents")
                    .WithMethod(HttpMethod.Post.Method)
                    .WithReadContent())
                .SetVariable("Document", context => context.GetInput<HttpRequestModel>()!.Body)
                .SendEmail(activity => activity
                    .WithSender("workflow@acme.com")
                    .WithRecipient("josh@acme.com")
                    .WithSubject(context => $"Document received from {context.GetVariable<dynamic>("Document")!.Author.Name}")
                    .WithBody(context =>
                    {
                        var document = context.GetVariable<dynamic>("Document")!;
                        var author = document!.Author;
                        return $"Document from {author.Name} received for review.<br><a href=\"{context.GenerateSignalUrl("Approve")}\">Approve</a> or <a href=\"{context.GenerateSignalUrl("Reject")}\">Reject</a>";
                    }))
                .WriteHttpResponse(
                    HttpStatusCode.OK,
                    "<h1>Request for Approval Sent</h1><p>Your document has been received and will be reviewed shortly.</p>",
                    "text/html")
                .Then<Fork>(activity => activity.WithBranches("Approve", "Reject", "Remind"), fork =>
                {
                    fork
                        .When("Approve")
                        .SignalReceived("Approve")
                        .SendEmail(activity => activity
                            .WithSender("workflow@acme.com")
                            .WithRecipient(context => context.GetVariable<dynamic>("Document")!.Author.Email)
                            .WithSubject(context => $"Document {context.GetVariable<dynamic>("Document")!.Id} Approved!")
                            .WithBody(context => $"Great job {context.GetVariable<dynamic>("Document")!.Author.Name}, that document is perfect."))
                        .ThenNamed("Join");

                    fork
                        .When("Reject")
                        .SignalReceived("Reject")
                        .SendEmail(activity => activity
                            .WithSender("workflow@acme.com")
                            .WithRecipient(context => context.GetVariable<dynamic>("Document")!.Author.Email)
                            .WithSubject(context => $"Document {context.GetVariable<dynamic>("Document")!.Id} Rejected")
                            .WithBody(context => $"Nice try {context.GetVariable<dynamic>("Document")!.Author.Name}, but that document needs work."))
                        .ThenNamed("Join");

                    fork
                        .When("Remind")
                        .Timer(Duration.FromSeconds(10)).WithName("Reminder")
                        .SendEmail(activity => activity
                                .WithSender("workflow@acme.com")
                                .WithRecipient("josh@acme.com")
                                .WithSubject(context => $"{context.GetVariable<dynamic>("Document")!.Author.Name} is waiting for your review!")
                                .WithBody(context =>
                                    $"Don't forget to review document {context.GetVariable<dynamic>("Document")!.Id}.<br><a href=\"{context.GenerateSignalUrl("Approve")}\">Approve</a> or <a href=\"{context.GenerateSignalUrl("Reject")}\">Reject</a>"))
                            .ThenNamed("Reminder");
                })
                .Add<Join>(join => join.WithMode(Join.JoinMode.WaitAny)).WithName("Join")
                .WriteHttpResponse(HttpStatusCode.OK, "Thanks for the hard work!", "text/html");
        }

**Comment by serenabenny** [comment]
The exception message.
```
An unhandled exception occurred while processing the request.
InvalidCastException: Invalid cast from 'System.Int64' to 'Elsa.Activities.Signaling.SignalScope'.
System.Convert.DefaultToType(IConvertible value, Type targetType, IFormatProvider provider)

InvalidCastException: Invalid cast from 'System.Int64' to 'Elsa.Activities.Signaling.SignalScope'.
System.Convert.DefaultToType(IConvertible value, Type targetType, IFormatProvider provider)
long.System.IConvertible.ToType(Type type, IFormatProvider provider)
Elsa.ObjectConverter.ConvertTo(object value, Type targetType)
Elsa.JObjectExtensions.GetState(IDictionary<string, object> state, string key, Type targetType)
Elsa.Services.Models.ActivityExecutionContext.GetState(string propertyName, Type targetType)
Elsa.Services.ActivityActivator.ApplyStoredValues(ActivityExecutionContext context, IActivity activity)
Elsa.Services.ActivityActivator.ActivateActivityAsync(ActivityExecutionContext context, Type type, CancellationToken cancellationToken)
Elsa.ActivityTypeProviders.TypeBasedActivityProvider+<>c__DisplayClass6_0+<<CreateActivityTypeAsync>b__0>d.MoveNext()
System.Threading.Tasks.ValueTask<TResult>.get_Result()
Elsa.Services.WorkflowRunner.CanExecuteAsync(WorkflowExecutionContext workflowExecutionContext, IActivityBlueprint activityBlueprint, object input, bool resuming, CancellationToken cancellationToken)
System.Runtime.CompilerServices.ConfiguredValueTaskAwaitable<TResult>+ConfiguredValueTaskAwaiter.GetResult()
Elsa.Services.WorkflowRunner.ResumeWorkflowAsync(WorkflowExecutionContext workflowExecutionContext, IActivityBlueprint activityBlueprint, object input, CancellationToken cancellationToken)
Elsa.Services.WorkflowRunner.RunWorkflowAsync(IWorkflowBlueprint workflowBlueprint, WorkflowInstance workflowInstance, string activityId, object input, CancellationToken cancellationToken)
Elsa.Services.WorkflowResumer.ResumeWorkflowAsync(WorkflowInstance workflowInstance, string activityId, object input, CancellationToken cancellationToken)
Elsa.Services.WorkflowInstanceExecutor.ExecuteAsync(WorkflowInstance workflowInstance, string activityId, object input, CancellationToken cancellationToken)
Elsa.Decorators.LockingWorkflowInstanceExecutor.ExecuteAsync(string workflowInstanceId, string activityId, object input, CancellationToken cancellationToken)
Elsa.Decorators.LockingWorkflowInstanceExecutor.ExecuteAsync(string workflowInstanceId, string activityId, object input, CancellationToken cancellationToken)
Elsa.Decorators.LockingWorkflowInstanceExecutor.ExecuteAsync(string workflowInstanceId, string activityId, object input, CancellationToken cancellationToken)
Elsa.Services.WorkflowLaunchpad.ExecutePendingWorkflowsAsync(IEnumerable<PendingWorkflow> pendingWorkflows, object input, CancellationToken cancellationToken)
Elsa.Services.WorkflowLaunchpad.CollectAndExecuteWorkflowsAsync(CollectWorkflowsContext context, object input, CancellationToken cancellationToken)
Elsa.Activities.Signaling.Services.Signaler.TriggerSignalAsync(string signal, object input, string workflowInstanceId, string correlationId, CancellationToken cancellationToken)
Elsa.Activities.Signaling.Services.Signaler.TriggerSignalTokenAsync(string token, object input, CancellationToken cancellationToken)
Open.Linq.AsyncExtensions.Extensions.ToList<TSource>(Task<IEnumerable<TSource>> source)
Elsa.Activities.Http.Endpoints.Signals.TriggerEndpoint.Handle(string token)
Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor+TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, object controller, object[] arguments)
System.Threading.Tasks.ValueTask<TResult>.get_Result()
Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Logged|12_1(ControllerActionInvoker invoker)
Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, object state, bool isCompleted)
Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(ref State next, ref Scope scope, ref object state, ref bool isCompleted)
Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, object state, bool isCompleted)
Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|24_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, object state, bool isCompleted)
Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(ref State next, ref Scope scope, ref object state, ref bool isCompleted)
Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, object state, bool isCompleted)
Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
Elsa.Activities.Http.Middleware.HttpEndpointMiddleware.InvokeAsync(HttpContext httpContext, IWorkflowLaunchpad workflowLaunchpad, IWorkflowInstanceStore workflowInstanceStore, IWorkflowRegistry workflowRegistry, IWorkflowBlueprintReflector workflowBlueprintReflector, IEnumerable<IHttpRequestBodyParser> contentParsers)
Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
```
