### ISSUE TITLE
Dashboard don't show any activities

### ISSUE THREAD

**Issue by dust63** [elsa-workflows/elsa-core#1092]
When I want to add an activity, I can't find any activity when I click on Start.

![image](https://user-images.githubusercontent.com/13755387/121050404-d5cfb000-c7b8-11eb-9764-9cf4e6dcb292.png)

**Comment by dust63** [comment]
Hi, I solved the issue by replace in _Host.cshtml
```
@{
    var serverUrl = $"{Request.Scheme}://{Request.Host}";
}

  <elsa-studio-root server-url="@serverUrl" ...
```

by


```
@{
    ViewData["Title"] = "Home page";
    var serverUrl = Configuration["Elsa:Server:BaseUrl"];

 <elsa-studio-root server-url="@serverUrl" ...
}
```

**Comment by sfmskywalker** [comment]
Awesome. Thanks for following up.
