### ISSUE TITLE
Faulty Sample - No workflow definition

### ISSUE THREAD

**Issue by dust63** [elsa-workflows/elsa-core#1094]
I'm looking for an example to manage faulted activity result.
I tried to go to this [sample](https://github.com/elsa-workflows/elsa-core/tree/master/src/samples/aspnet/Elsa.Samples.FaultyWorkflows) but I can't see the workflow definition.

**Comment by sfmskywalker** [comment]
Ha. That sample somehow got removed from the solution. I'll get it restored.

**Comment by sfmskywalker** [comment]
It's back.
