### ISSUE TITLE
File Activities

### ISSUE THREAD

**Issue by dust63** [elsa-workflows/elsa-core#1095]
I writing File activities. For now I wrote:

FileMoved -> Moved a file on local filesystem
FileCopy ->Copy a file on local filesystem
FileDelete -> Delete a file on local filesystem

Liquid Filter:
"combine_path" -> Combine file name and path
"get_filename" -> Get file name from a path
"get_path" -> get path of directory on a file path

Are you interested by this set of activities/filter ? Do you want a PR for this ?

**Comment by tomy2105** [comment]
Would definitely be nice to have, IMHO...

**Comment by sfmskywalker** [comment]
Sure, sounds great!

**Comment by dust63** [comment]
What is the procedure to make a pull request ?

**Comment by sfmskywalker** [comment]
1. Fork the project.
2. Clone your fork.
3. Make changes and push them.
4. Repeat step 3 as many times as you want.
5. Create a PR from GitHub.

Hope this helps, but let me know if you have more questions.

**Comment by sfmskywalker** [comment]
This is done. Thanks for contributing!

**Comment by BenSeymourODB** [comment]
Hi, @sfmskywalker - is there a branch where the specific activities that @dust63 mentioned are implemented? Having `MoveFile` and `CopyFile` activities available would be useful (though my team has figured out how to implement these actions as workflows using a combination of `ReadFile`, `OutFile`, and `DeleteFile`).

Additionally, we noticed that the `SupportedSyntaxes` attribute is missing from `DeleteFile.Path`. If there is not already an issue / PR for this, we'd be happy to contribute.

**Comment by sfmskywalker** [comment]
Hi @BenSeymourODB , it looks like these activities weren't created. If you want I'd be happy to accept another PR though 😁
