### ISSUE TITLE
Ability to extend designer

### ISSUE THREAD

**Issue by tomy2105** [elsa-workflows/elsa-core#1097]
First of all thanks for the good work, keep it up :)

I would like to see ability to define my own input properties and maybe even whole activities in designer without having to build whole designer.

My list would be extension points for:
- property type implementation
- whole activity dialog implementation (needed when you have activity where there is a relation between input properties, for example hide some of them based on the value of another one, etc....)
- ability to hook up to certain events, like activity dialog shown, workflow rendered, etc, .... (don't know if stencil gives something like this out of the box)

**Comment by sfmskywalker** [comment]
- [x] property type implementation
- [ ] whole activity dialog implementation (needed when you have activity where there is a relation between input properties, for example hide some of them based on the value of another one, etc....)
- [x] ability to hook up to certain events, like activity dialog shown, workflow rendered, etc, .... (don't know if stencil gives something like this out of the box)

**Comment by tomy2105** [comment]
Good work on progressing this......
Could you please provide either a few hints here or a documentation page, where to start with what has been implemented...
Ideally an example:
- how to hook up to certain events (and which events are available)
- how to write your own property implementation and how to register it with "core UI"

**Comment by sfmskywalker** [comment]
Yes, I will work on documentation (at some point). A few quick pointers for now:

Available events (using event bus):

* `'workflow-instance-bulk-actions-loading'`
* `'http-client-created'`
* '`http-client-config-created`'
* '`workflow-imported`'
* '`workflow-retracted`'
* '`workflow-published`'
* '`activity-descriptor-displaying`'
* '`activity-design-displaying`'
* '`workflow-model-changed`'
* '`activity-picked`'
* '`show-activity-picker`'

To observe any of these events, the easiest way is to define a plugin. Example:

```javascript
<script>
    // Custom plugin that intercepts outgoing HTTP requests and their responses.
    function CustomHttpMiddlewarePlugin(elsaStudio) {
        const eventBus = elsaStudio.eventBus;

        eventBus.on('http-client-created', e => {
            // Register a sample middleware.
            e.service.register({
                onRequest(request) {
                    console.log('onRequest');
                    return request;
                },
            });
        });
    }

    // Get a handle to the elsa-studio-root element.
    const elsaStudioRoot = document.querySelector('elsa-studio-root');
    
    (async () => {
        // Wait until the component is available.
        await customElements.whenDefined('elsa-studio-root');

        // Install plugins.
        await elsaStudioRoot.addPlugin(CustomHttpMiddlewarePlugin);
    })();
</script>
```

Similarly, to create a new property type, start by creating a plugin:

```javascript
// Custom driver:
function CustomPropertyFieldDriver(elsaStudio){
    this.display = (activity, property) => {
        const prop = elsaStudio.getOrCreateProperty(activity, property.name);
        return `<input type="text" className="disabled:elsa-opacity-50 disabled:elsa-cursor-not-allowed focus:elsa-ring-blue-500 focus:elsa-border-blue-500 elsa-block elsa-w-full elsa-min-w-0 elsa-rounded-md sm:elsa-text-sm elsa-border-gray-300"`;
    };
}

// Custom plugin to register driver:
function CustomPropertyFieldPlugin(elsaStudio) {
    const {propertyDisplayManager} = elsaStudio;

    // Register custom driver.
    propertyDisplayManager.addDriver('my-custom-property-type', CustomPropertyFieldDriver);
}

// Register plugin:
(async () => {
    await customElements.whenDefined('elsa-studio-root');
    await elsaStudioRoot.addPlugin(CustomPropertyFieldPlugin);
})();
```

The hardest part will be implementing the custom input control to handle change events etc. When doing this as a stencil component, Angular or React component, it might be easy. Doing it using vanilla JS should work too though, just a bit more plumbing maybe. Not sure, I haven't actually gone through the motions myself yet.

**Comment by kleiner2012** [comment]
Hello, I have tried all the available events.
Maybe I am missing something but the events below trigger only at first workflow that is being edited. Any additional workflow that is being edited after the first one does not trigger the events.

- 'workflow-imported'
- 'workflow-retracted'
- 'workflow-published'
- 'activity-picked'
- 'show-activity-picker'

The code is similar to your example with custom http middleware.

           `const eventBus = elsaStudio.eventBus;

            eventBus.on('workflow-imported', e => {
                console.log('workflow-imported');
            });
            eventBus.on('workflow-retracted', e => {
                console.log('workflow-retracted');
            });
            eventBus.on('workflow-published', e => {
                console.log('workflow-published');
            });
            eventBus.on('activity-picked', e => {
                console.log('activity-picked');
            });
            eventBus.on('show-activity-picker', e => {
                console.log('show-activity-picker');
            });`

Also, how could one trigger 'workflow-model-changed'?

**Comment by sfmskywalker** [comment]
@kleiner2012  I think you discovered an issue, because I get the same result: the events are fired only once. I will look into it.

**Comment by sfmskywalker** [comment]
I pushed a fix so that the event handlers are invoked normally. The issue was that some components were a little bit too eager in their cleanup of their event handlers; they cleaned up ALL handlers for some of the events 😅

The Workflow Model Changed event is fired as a regular DOM event which you can handle like this:

```javascript
elsaStudioRoot.addEventListener('workflow-changed', e => {
    console.log('workflow model changed!!!');
})
```

But perhaps it's a good idea to publish it via the event bus as well so that you can conveniently implement a plugin that handles this event.

**Comment by sfmskywalker** [comment]
I pushed an update that also published the `workflow-model-changed` event via the event bus.

**Comment by sfmskywalker** [comment]
Done in 46d96a70808a51af99dea48649502e93ffc1aee4

**Comment by Nokecy** [comment]
> * [x]  whole activity dialog implementation (needed when you have activity where there is a relation between input properties, for example hide some of them based on the value of another one, etc....)

How to achieve this

**Comment by jdevillard** [comment]
> > * [x]   whole activity dialog implementation (needed when you have activity where there is a relation between input properties, for example hide some of them based on the value of another one, etc....)
> 
> How to achieve this

agree, could be awesome to have a sample that demonstrate something like cascading dropdown or something like this.

**Comment by sfmskywalker** [comment]
Here's a [small sample](https://github.com/elsa-workflows/elsa-core/blob/master/src/designer/elsa-workflows-studio/src/index.html#L96-L146) that creates a plugin that replaces the `Properties` tab with a custom one.

**Comment by sfmskywalker** [comment]
I agree, that would be even more useful. I'll add it to my list of things to blog about and/or create a guide for. Thanks for the tip 😄
