### ISSUE TITLE
[HELP] Sample using workflow context concept

### ISSUE THREAD

**Issue by dust63** [elsa-workflows/elsa-core#1102]
I'm looking for example to understood how to use workflow context.
Do you have also for correlation Id ?

**Comment by sfmskywalker** [comment]
Will create guides for both of these.

**Comment by sfmskywalker** [comment]
Here you go: https://elsa-workflows.github.io/elsa-core/docs/next/guides/guides-workflow-contexts

**Comment by dust63** [comment]
Thank for your effort. Nice work. Is it possible to have also a demo with fluent methods ?

**Comment by sfmskywalker** [comment]
Most certainly, here you go: https://github.com/elsa-workflows/elsa-core/blob/master/src/samples/aspnet/Elsa.Samples.ContextualWorkflowHttp/Workflows/DocumentApprovalWorkflow.cs

**Comment by wakuflair** [comment]
Hi @sfmskywalker 
Is the fluent builder available in Elsa 3?
