### ISSUE TITLE
Designer mouse doubleclick, enter and cancel 

### ISSUE THREAD

**Issue by tomy2105** [elsa-workflows/elsa-core#1114]
Splitting #1100....

It would nice if designer would: 
- [ ] Open activity dialog with **double click**
- [ ] Cancel changes and close activity dialog if **ESC** was pressed on keyboard
- [ ] Save activity if enter or **CTRL+Enter** was pressed on keyboard (optional)

**Comment by sfmskywalker** [comment]
> save activity if enter (or ctrl+enter) was pressed on keyboard

Doesn't this already work? Except of course if you are trying to do this in a text area or script editor control.

**Comment by tomy2105** [comment]
Actually, as I've just tested, Enter saves **if and only if** you are inside single line text input property.
Which is kind of confusing.
Since enter is used in multi-line text inputs I would opt for ctrl+enter saving regardless of focus if possible (focus might be on drop down, check box, whatever.....).

**Comment by sfmskywalker** [comment]
CTRL+Enter might be good to implement 👍🏻
