### ISSUE TITLE
Three workflow instances are always created for each running workflow. 

### ISSUE THREAD

**Issue by ricksearcy** [elsa-workflows/elsa-core#1121]
No matter the workflow details I always see this behavior. 3 workflow instances created for one workflow kicked off. I have also tried setting a unique correlation Id, which then all 3 instances show the same correlation Id.  If I have a workflow that includes an http response I see the first 2 workflows as faulted then the 3rd as finished. I'm not understanding this behavior and it makes the workflow instance data not very useful from a client perspective. 

public void Build(IWorkflowBuilder builder)
        {
            var serializer = builder.ServiceProvider.GetRequiredService<IContentSerializer>();
            builder
                .WithDisplayName("Approval Workflow")
                .HttpEndpoint(activity => activity
                    .WithPath("/v1/approvals")
                    .WithMethod(HttpMethod.Post.Method)
                    .WithTargetType<ApprovalRequest>()
                    .WithReadContent());
        }
        
        
<img width="484" alt="screen" src="https://user-images.githubusercontent.com/6527752/121698194-9e942400-ca82-11eb-9613-5cb20b9c5652.png">

**Comment by sfmskywalker** [comment]
That does not happen for me. Could you provide exact steps to reproduce? Maybe a complete sample project I can just run?

**Comment by ricksearcy** [comment]
Sure I thru together a skeleton of how I am trying to use it. Server and Dashboard in one project and Workflows in another. The sample workflow does nothing other than create the http endpoint and accept the request. 

https://github.com/ricksearcy/Elsa
Open the Elsa.Workflow.sln
Run the Elsa.Server project which will run the server and dashboard and use the ApprovalWokflow in the Elsa.Workflow project.
POST https://localhost:44391/v1/Approvals
Go to the Workflow Instances in the dashboard and there are always 3 instances for a single HTTP activity request.

**Comment by mohdali** [comment]
@ricksearcy in your Startup class can you comment out lines 36 and 40 and check?

Seems to me you HTTP activities are added twice and workflows are loaded both from the assembly and from the specific class.

**Comment by ricksearcy** [comment]
@mohdali @SipkeSchoorstraRTL I had to comment out lines 36, 38, 40. 
//.AddHttpActivities()
//.AddHttpActivities(elsaSection.GetSection("Server").Bind)
//.AddWorkflowsFrom<Startup>()
This still feels like a bug to me unless I am missing something.

**Comment by mohdali** [comment]
@ricksearcy 

Oh I see, you also had `elsa.AddHttpActivities(elsaSection.GetSection("Server").Bind)` in line 33.

You should only register HttpActivities once. In your code you had it registered 3 times which caused the three times of activation.
