### ISSUE TITLE
Urgent :( help needed with activities created with IActivityTypeProvider and CompositeActivity

### ISSUE THREAD

**Issue by tomy2105** [elsa-workflows/elsa-core#1122]
Hi, sorry to trouble with such long problem but @sfmskywalker I need help because I'm stuck.
I need "simple" activity with variable number of params so I'm creating activity using IActivityTypeProvider and placiing parameter values inside Dictionary.
For simplicity and ease of use reasons I need to wrap this activity (and some for loop logic and timers) inside another CompositeActivity which would also need variable number of parameters (same as simple one).

To cut the story short I wrote all of this (sample doing same is below). 
"Simple" activity when executed behaves as expected and outputs `{"SomeId":"simple"}` on console.

However CompositeActivity when executed doesn't behave as I would expect and outputs `{"Flags":"ElsaDashboard.Samples.AspNetCore.Monolith.MyDictionary"}` on console, I would expect the output to be "similar" to simple one `{"SomeId":"composite"}`

Above, "simple" and "composite" were values I placed inside activity property in designer, one for each activity.

Please help me, what did I do wrong?
Complete listing is below, I put all inside Startup.cs for ease of pasting here.
Elsa is 2.0 from NuGet repo......

    public interface IActivityWithRealType
    {
        public string RealType { get; set; }
    }

    public interface ISetFlag : IActivity
    {
        public IDictionary<string, string> Flags { get; set; }
    }

    public class SetFlag : Activity, ISetFlag, IActivityWithRealType
    {
        // must be done because FlagActivityTypeProvider sets name to something other than simple class name
        public string RealType { get; set; }
        public override string Type => string.IsNullOrWhiteSpace(RealType) ? GetType().Name : RealType;

        public IDictionary<string, string> Flags { get; set; } = new Dictionary<string, string>();

        protected override async ValueTask<IActivityExecutionResult> OnExecuteAsync(ActivityExecutionContext context)
        {
            System.Console.Out.WriteLine(JsonConvert.SerializeObject(Flags));
            return Done();
        }
    }

    public class SetFlagContainer : CompositeActivity, ISetFlag, IActivityWithRealType
    {
        // must be done because FlagActivityTypeProvider sets name to something other than simple class name
        public string RealType { get; set; }
        public override string Type => string.IsNullOrWhiteSpace(RealType) ? GetType().Name : RealType;

        public IDictionary<string, string> Flags
        {
            get => GetState(() => new Dictionary<string, string>());
            set => SetState(value);
        }

        public override void Build(ICompositeActivityBuilder builder)
        {
            builder
                .Then<SetFlag>(typeof(SetFlag).FullName, set => set
                    .Set(flag => flag.Flags, Flags)
                );
        }
    }

    public class FlagActivityTypeProvider : IActivityTypeProvider
    {
        private static string INTERNAL_ID_NAME = "SomeId";
        private readonly ElsaOptions _elsaOptions;

        public async ValueTask<IEnumerable<ActivityType>> GetActivityTypesAsync(CancellationToken cancellationToken = default)
        {
            var types = new List<ActivityType>();

            types.AddRange(CreateSetFlagActivityTypes());

            return types.ToArray();
        }

        private IList<ActivityType> CreateSetFlagActivityTypes()
        {
            return new List<ActivityType>{
                CreateSetFlagActivityType(typeof(SetFlag), "Set Flags simple", "Set flags, without error complication."),
                CreateSetFlagActivityType(typeof(SetFlagContainer), "Set Flags", "Set flags.")
            };
        }

        private ActivityType CreateSetFlagActivityType(Type activityType, string displayName, string description)
        {
            List<ActivityPropertyDescriptor> properties = new List<ActivityPropertyDescriptor>();
            properties.Add(
                new ActivityPropertyDescriptor(
                    INTERNAL_ID_NAME, //property name
                    typeof(string), // property type
                    ActivityPropertyUIHints.SingleLine, // property UI hint
                    "My Id", // property label
                    "My Nice Id", // property description,
                    null, // possible property values
                    null, // cathegory
                    null, // default value
                    SyntaxNames.JavaScript, // default syntax
                    new[] { SyntaxNames.Literal, SyntaxNames.JavaScript } // allowed syntaxes
                )
            );

            var descriptor = new ActivityDescriptor
            {
                Type = activityType.FullName,
                Category = "Test",
                DisplayName = displayName,
                Description = description,
                Traits = ActivityTraits.Action,
                Outcomes = new[] { OutcomeNames.Done },
                Properties = properties.ToArray()
            };

            return new ActivityType
            {
                TypeName = descriptor.Type,
                Type = activityType,
                Description = descriptor.Description,
                DisplayName = descriptor.DisplayName,
                Describe = () => descriptor,
                ActivateAsync = async context =>
                {
                    return await ActivateActivityAsync(context, activityType, descriptor.Type);
                },
                CanExecuteAsync = async context =>
                {
                    var instance = await ActivateActivityAsync(context, activityType, descriptor.Type);
                    return await instance.CanExecuteAsync(context);
                },
                ExecuteAsync = async context =>
                {
                    var instance = await ActivateActivityAsync(context, activityType, descriptor.Type);
                    return await instance.ExecuteAsync(context);
                },
                ResumeAsync = async context =>
                {
                    var instance = await ActivateActivityAsync(context, activityType, descriptor.Type);
                    return await instance.ResumeAsync(context);
                }
            };
        }

        private async Task<IActivity> ActivateActivityAsync(ActivityExecutionContext context, Type type, string realType, params string[] parameters)
        {
            var activity = (IActivity)ActivatorUtilities.GetServiceOrCreateInstance(context.ServiceProvider, type);
            ((IActivityWithRealType)activity).RealType = realType;
            activity.Data = context.GetData();
            activity.Id = context.ActivityId;

            await SetActivityPropertiesAsync((ISetFlag)activity, context);

            return activity;
        }

        private async ValueTask SetActivityPropertiesAsync(ISetFlag activity, ActivityExecutionContext activityExecutionContext)
        {
            var providers = activityExecutionContext.WorkflowExecutionContext.WorkflowBlueprint.ActivityPropertyProviders.GetProviders(activity.Id);

            if (providers == null)
                return;

            foreach (var provider in providers)
            {
                try
                {
                    var value = await provider.Value.GetValueAsync(activityExecutionContext, activityExecutionContext.CancellationToken);
                    activity.Flags.Add(provider.Key, value?.ToString());
                }
                catch (Exception e)
                {
                    throw new CannotSetActivityPropertyValueException($@"An exception was thrown whilst setting '{activity?.GetType().Name}.{provider.Key}'. See the inner exception for further details.", e);
                }
            }
        }
    }

    public class Startup
    {
        public Startup(IConfiguration configuration)
        {
            Configuration = configuration;
        }

        public IConfiguration Configuration { get; }

        // This method gets called by the runtime. Use this method to add services to the container.
        public void ConfigureServices(IServiceCollection services)
        {
            services.AddRazorPages();
            
            // Elsa Server.
            var elsaSection = Configuration.GetSection("Elsa");
            
            services
                .AddElsa(options => options
                        .UseEntityFrameworkPersistence(ef => ef.UseSqlite())
                        .AddConsoleActivities()
                        .AddHttpActivities(elsaSection.GetSection("Server").Bind)
                        .AddJavaScriptActivities()
                        .AddActivitiesFrom<Startup>()
                        .RemoveActivity<SetFlag>()  // must be removed because it is added and configured by FlagActivityTypeProvider 
                        .RemoveActivity<SetFlagContainer>()  // must be removed because it is added and configured by FlagActivityTypeProvider 
                );

            services
                .AddScoped<IActivityTypeProvider, FlagActivityTypeProvider>()
                .AddElsaApiEndpoints();

            // Allow arbitrary client browser apps to access the API.
            // In a production environment, make sure to allow only origins you trust.
            services.AddCors(cors => cors.AddDefaultPolicy(policy => policy.AllowAnyHeader().AllowAnyMethod().AllowAnyOrigin().WithExposedHeaders("Content-Disposition")));
        }

        // This method gets called by the runtime. Use this method to configure the HTTP request pipeline.
        public void Configure(IApplicationBuilder app, IWebHostEnvironment env)
        {
            if (env.IsDevelopment())
            {
                app.UseDeveloperExceptionPage();
            }
            else
            {
                app.UseExceptionHandler("/Error");
                // The default HSTS value is 30 days. You may want to change this for production scenarios, see https://aka.ms/aspnetcore-hsts.
                app.UseHsts();
            }

            app.UseCors();
            app.UseStaticFiles();
            app.UseHttpActivities();
            app.UseRouting();
            app.UseAuthorization();
            app.UseEndpoints(endpoints =>
            {
                // Elsa Server uses ASP.NET Core Controllers.
                endpoints.MapControllers();
                
                endpoints.MapFallbackToPage("/_Host");
            });
        }
    }

**Comment by sfmskywalker** [comment]
It might be a while before I can look into this, but if you could share a (simple) project that I can try, then that would save me some time.

**Comment by tomy2105** [comment]
Just paste all I put in my initial post into Startup.cs (you might need to add some using directives) of ElsaDashboard.Samples.AspNetCore.Monolith and you are there.

**Comment by tomy2105** [comment]
Just paste all I put in my initial post into Startup.cs (you might need to add some using directives) of ElsaDashboard.Samples.AspNetCore.Monolith and you are there.

**Comment by tomy2105** [comment]
OK, I made it work :) but had to do one ugly thing with casting interface to implementation class in order to be able so, I will open new task for that.
In addition CompositeDerived activities and their properties implemented through GetData/SetData and not directly behave a little differently than ordinary activities with direct property implementation. Will open separate task for that too since it either needs to be clearly documented or behaviour changed so it doesn't surprise anyone at it did me :).

The full listing which works now is below, changes are in Build method of composite activity and in SetActivityPropertiesAsync of IActivityTypeProvider derived class.

    public interface IActivityWithRealType
    {
        public string RealType { get; set; }
    }

    public interface ISetFlag : IActivity
    {
        public IDictionary<string, string> Flags { get; set; }
    }

    public class SetFlag : Activity, ISetFlag, IActivityWithRealType
    {
        // must be done because FlagActivityTypeProvider sets name to something other than simple class name
        public string RealType { get; set; }
        public override string Type => string.IsNullOrWhiteSpace(RealType) ? GetType().Name : RealType;

        public IDictionary<string, string> Flags { get; set; } = new Dictionary<string, string>();

        protected override async ValueTask<IActivityExecutionResult> OnExecuteAsync(ActivityExecutionContext context)
        {
            System.Console.Out.WriteLine("SetFlag::OnExecuteAsync" + JsonConvert.SerializeObject(Flags));
            return Done();
        }
    }

    public class SetFlagContainer : CompositeActivity, ISetFlag, IActivityWithRealType
    {
        // must be done because FlagActivityTypeProvider sets name to something other than simple class name
        public string RealType { get; set; }
        public override string Type {
            get
            {
                return string.IsNullOrWhiteSpace(RealType) ? GetType().Name : RealType;
            }
        }

        public IDictionary<string, string> Flags
        {
            get => GetState(() => new Dictionary<string, string>());
            set => SetState(value);
        }

        public override void Build(ICompositeActivityBuilder builder)
        {
            builder
                .ThenTypeNamed(typeof(SetFlag).FullName, setup =>
                {
                    var trueSetup = (SetupActivity<IActivity>)setup;
                    trueSetup.ValueProviders[FlagActivityTypeProvider.INTERNAL_ID_NAME] = context =>
                    {
                        return new ValueTask<object?>(Flags[FlagActivityTypeProvider.INTERNAL_ID_NAME]);
                    };
                }, null);
        }
    }


    public class FlagActivityTypeProvider : IActivityTypeProvider
    {
        public static string INTERNAL_ID_NAME = "SomeId";

        public async ValueTask<IEnumerable<ActivityType>> GetActivityTypesAsync(CancellationToken cancellationToken = default)
        {
            var types = new List<ActivityType>();

            types.AddRange(CreateSetFlagActivityTypes());

            return types.ToArray();
        }

        private IList<ActivityType> CreateSetFlagActivityTypes()
        {
            return new List<ActivityType>{
                CreateSetFlagActivityType(typeof(SetFlag), "Set Flags simple", "Set flags, without error complication."),
                CreateSetFlagActivityType(typeof(SetFlagContainer), "Set Flags", "Set flags.")
            };
        }

        private ActivityType CreateSetFlagActivityType(Type activityType, string displayName, string description)
        {
            List<ActivityPropertyDescriptor> properties = new List<ActivityPropertyDescriptor>();
            properties.Add(
                new ActivityPropertyDescriptor(
                    INTERNAL_ID_NAME, //property name
                    typeof(string), // property type
                    ActivityPropertyUIHints.SingleLine, // property UI hint
                    "My Id", // property label
                    "My Nice Id", // property description,
                    null, // possible property values
                    null, // cathegory
                    null, // default value
                    SyntaxNames.JavaScript, // default syntax
                    new[] { SyntaxNames.Literal, SyntaxNames.JavaScript } // allowed syntaxes
                )
            );

            var descriptor = new ActivityDescriptor
            {
                Type = activityType.FullName,
                Category = "Test",
                DisplayName = displayName,
                Description = description,
                Traits = ActivityTraits.Action,
                Outcomes = new[] { OutcomeNames.Done },
                Properties = properties.ToArray()
            };

            return new ActivityType
            {
                TypeName = descriptor.Type,
                Type = activityType,
                Description = descriptor.Description,
                DisplayName = descriptor.DisplayName,
                Describe = () => descriptor,
                ActivateAsync = async context =>
                {
                    return await ActivateActivityAsync(context, activityType, descriptor.Type);
                },
                CanExecuteAsync = async context =>
                {
                    var instance = await ActivateActivityAsync(context, activityType, descriptor.Type);
                    return await instance.CanExecuteAsync(context);
                },
                ExecuteAsync = async context =>
                {
                    var instance = await ActivateActivityAsync(context, activityType, descriptor.Type);
                    return await instance.ExecuteAsync(context);
                },
                ResumeAsync = async context =>
                {
                    var instance = await ActivateActivityAsync(context, activityType, descriptor.Type);
                    return await instance.ResumeAsync(context);
                }
            };
        }

        private async Task<IActivity> ActivateActivityAsync(ActivityExecutionContext context, Type type, string realType, params string[] parameters)
        {
            var activity = (IActivity)ActivatorUtilities.CreateInstance(context.ServiceProvider, type);
            ((IActivityWithRealType)activity).RealType = realType;
            activity.Data = context.GetData();
            activity.Id = context.ActivityId;

            await SetActivityPropertiesAsync((ISetFlag)activity, context);

            return activity;
        }

        private async ValueTask SetActivityPropertiesAsync(ISetFlag activity, ActivityExecutionContext activityExecutionContext)
        {
            var providers = activityExecutionContext.WorkflowExecutionContext.WorkflowBlueprint.ActivityPropertyProviders.GetProviders(activity.Id);

            if (providers == null)
                return;

            var flags = activity.Flags;
            foreach (var provider in providers)
            {
                try
                {
                    var value = await provider.Value.GetValueAsync(activityExecutionContext, activityExecutionContext.CancellationToken);
                    flags[provider.Key] = value?.ToString();
                }
                catch (Exception e)
                {
                    throw new CannotSetActivityPropertyValueException($@"An exception was thrown whilst setting '{activity?.GetType().Name}.{provider.Key}'. See the inner exception for further details.", e);
                }
            }
            activity.Flags = flags;
        }
    }

    public class Startup
    {
        public Startup(IConfiguration configuration)
        {
            Configuration = configuration;
        }

        public IConfiguration Configuration { get; }

        // This method gets called by the runtime. Use this method to add services to the container.
        public void ConfigureServices(IServiceCollection services)
        {
            services.AddRazorPages();
            
            // Elsa Server.
            var elsaSection = Configuration.GetSection("Elsa");
            
            services
                .AddElsa(options => options
                        .UseEntityFrameworkPersistence(ef => ef.UseSqlite())
                        .AddConsoleActivities()
                        .AddHttpActivities(elsaSection.GetSection("Server").Bind)
                        .AddJavaScriptActivities()
                );

            services
                .AddScoped<IActivityTypeProvider, FlagActivityTypeProvider>()
                .AddElsaApiEndpoints();

            // Allow arbitrary client browser apps to access the API.
            // In a production environment, make sure to allow only origins you trust.
            services.AddCors(cors => cors.AddDefaultPolicy(policy => policy.AllowAnyHeader().AllowAnyMethod().AllowAnyOrigin().WithExposedHeaders("Content-Disposition")));
        }

        // This method gets called by the runtime. Use this method to configure the HTTP request pipeline.
        public void Configure(IApplicationBuilder app, IWebHostEnvironment env)
        {
            if (env.IsDevelopment())
            {
                app.UseDeveloperExceptionPage();
            }
            else
            {
                app.UseExceptionHandler("/Error");
                // The default HSTS value is 30 days. You may want to change this for production scenarios, see https://aka.ms/aspnetcore-hsts.
                app.UseHsts();
            }

            app.UseCors();
            app.UseStaticFiles();
            app.UseHttpActivities();
            app.UseRouting();
            app.UseAuthorization();
            app.UseEndpoints(endpoints =>
            {
                // Elsa Server uses ASP.NET Core Controllers.
                endpoints.MapControllers();
                
                endpoints.MapFallbackToPage("/_Host");
            });
        }
    }

**Comment by sfmskywalker** [comment]
It looks like you got a good handle on this now. Can we close this one, since you created actionable items elsewhere already?

**Comment by tomy2105** [comment]
Yes, closing this one and will work on the items that were created based on this.
