### ISSUE TITLE
File persistence providers

### ISSUE THREAD

**Issue by sfmskywalker** [elsa-workflows/elsa-core#113]
It would be useful to have a file-based workflow definition provider so that one can include workflow definition JSON files with their application and execute these.

**Comment by anktsrkr** [comment]
Hi @sfmskywalker I would like to start on this. Making sure no one else is working on this item.

**Comment by sfmskywalker** [comment]
Awesome, please do!

**Comment by anktsrkr** [comment]
Hi @sfmskywalker  Could you please elaborate in detail? I am thinking about something like this - 

```
public static class BuilderExtension
    {
        public static async Task FromJson(this IWorkflowBuilder builder,string jsonWorkflow)
        { 
            var serializer = builder.ServiceProvider.GetRequiredService<IWorkflowSerializer>();
            var workflowDefiniton = serializer.Deserialize<WorkflowDefinitionVersion>(jsonWorkflow, JsonTokenFormatter.FormatName);

            //Register it
            var workflowDefinitionStore = builder.ServiceProvider.GetRequiredService<IWorkflowDefinitionStore>();
            await workflowDefinitionStore.AddAsync(workflowDefiniton);

            //Run it
            var invoker = builder.ServiceProvider.GetRequiredService<IWorkflowHost>();
            await invoker.RunWorkflowDefinitionAsync(workflowDefiniton.DefinitionId);

        }
        public static async Task FromEmbeddedResource(IWorkflowBuilder builder, Assembly assembly, string resourceName)
        {
            var jsonWorkflow = await ReadEmbeddedResourceAsync(assembly, resourceName);
            await FromJson(builder, jsonWorkflow);
        }
         
        private static async ValueTask<string> ReadEmbeddedResourceAsync(Assembly assembly, string resourceName)
        {
            using var reader = new StreamReader(assembly.GetManifestResourceStream(resourceName));
            return await reader.ReadToEndAsync();
        }
    }
```

**Comment by anktsrkr** [comment]
Any feedback @sfmskywalker

**Comment by sfmskywalker** [comment]
I was thinking more along the lines of having actual file-based implementations of `IWorkflowDefinitionStore`, like so:

```csharp
public class FileSystemWorkflowDefinitionStore : IWorkflowDefinitionStore
{
....
}
```

But I really like the idea of also having an embedded resource workflow definition provider, like so:

```csharp
public class EmbeddedResourceWorkflowDefinitionStore : IWorkflowDefinitionStore
{
....
}
```

Which made me realize that I might even want to be able to fetch workflow definitions from different sources within a given application. So maybe we should refactor the workflow definition store such that it accepts a list of providers: 


```csharp
interface IWorkflowDefinitionStoreProvider 
{
   Task<IEnumerable<WorkflowDefinition>> ListAsync(CancellationToken cancellationToken = default);
}
```

You would then have a bunch of these provider implementations, like:

* FileSystemWorkflowDefinitionProvider
* EmbeddedWorkflowDefinitionProvider
* AzureBlobWorkflowDefinitionProvider
* SqlWorkflowDefinitionProvider
* CosmosWorkflowDefinitionProvider
* MongoWorkflowDefinitionProvider

Then the `WorkflowDefinitionStore` itself would simply do a select many on all of these providers.

Thoughts?

**Comment by sfmskywalker** [comment]
This is now implemented using Storage.NET.
