### ISSUE TITLE
Http Endpoint faulted flow returns 200 with no response content to caller

### ISSUE THREAD

**Issue by vlad-crisan** [elsa-workflows/elsa-core#1130]
I have defined a workflow that is started by exposing an endpoint through "Http Endpoint" activity, with method POST.
Following that, if the workflow faults at any point, the caller receives response 200, and no content body (header Content-Length: 0)
 
Navigating to Workflow Instances shows the proper details, exception message, stack trace, status "Faulted", etc.

I would have expected the caller to receive all of these details, instead of getting a 200.
Is there some additional configuration that can be done to acchieve this behavior? Or should the default be like I described it - get the exception details in the response?

I'm using version 2.0.0.159 of the library.
The way I forced an exception to happen in the flow:
- custom activity that explicitly throws an exception
- input property to an activity set to javascript and defining a faulty expression

both of these result in the same behavior - 200 and no response content

I'm working at the moment on an application that intends to proxy to another service that runs the elsa workflows (and exposes them by having an HTTP Endpoint step at the start of each flow),  so it's important to have the ability to get information about the faulty behavior.

Thanks in advance for any feedback!

**Comment by sfmskywalker** [comment]
Makes sense to at the very least respond with an appropriate status code, i.e. 500 when the workflow faults.

For production, it would be unsafe to send back a full stack trace, but we should make this configurable in some way.
