### ISSUE TITLE
Elsa Page in Asp.Net Core application 

### ISSUE THREAD

**Issue by AvtsVivek** [elsa-workflows/elsa-core#1132]
I created an Asp.Net Core MVC application and integrated Elsa into it based on the [exercise given here](https://elsa-workflows.github.io/elsa-core/docs/next/quickstarts/quickstarts-aspnetcore-server-dashboard-and-api-endpoints). 
I pushed the working [solution here](https://github.com/AvtsVivek/ElsaBugReports/tree/main/src/P20703DashboardWithServer).
This has [HomeController](https://github.com/AvtsVivek/ElsaBugReports/blob/main/src/P20703DashboardWithServer/P20703DashboardWithServer/Controllers/HomeController.cs) with [Index view](https://github.com/AvtsVivek/ElsaBugReports/tree/main/src/P20703DashboardWithServer/P20703DashboardWithServer/Views/Home) in it.

So when I run the app and browse to http://localhost:26284/home/index, I see the home page as expected.

![image](https://user-images.githubusercontent.com/41255281/122040672-b7d80000-cdf5-11eb-9ac3-e3c8c808e260.png)

Now I click Home button and I am shown the elsa home page. Everything works fine. The workflow definition and instance pages also work fine as expected(see images below). 
But the problem is I don't want elsa page as the home page(http://localhost:26284.). What do I have to do if I want the following elsa page to be shown at say the URL http://localhost:26284/elsa/workflows and not at http://localhost:26284. 

I tried fiddling the [startup file](https://github.com/AvtsVivek/ElsaBugReports/blob/b59d85c829803f8d1216cdbf27ac83606574f1c5/src/P20703DashboardWithServer/P20703DashboardWithServer/Startup.cs#L58). I tried changing 

endpoints.MapFallbackToPage("/_Host");     
 //endpoints.MapFallbackToPage("/ElsaWorkflows/{**segment}", "/_Host");

Also tried tweaking the base url and base path in the [appsettings.json](https://github.com/AvtsVivek/ElsaBugReports/blob/main/src/P20703DashboardWithServer/P20703DashboardWithServer/appsettings.json) file, they did not work.

What am I missing?

![image](https://user-images.githubusercontent.com/41255281/122040891-fcfc3200-cdf5-11eb-87c2-985c2e14b089.png)
![image](https://user-images.githubusercontent.com/41255281/122043841-6df11900-cdf9-11eb-9ff8-4020c81ba624.png)
![image](https://user-images.githubusercontent.com/41255281/122043948-8d884180-cdf9-11eb-97cd-bd13b2d4661c.png)

**Comment by weirdyang** [comment]
change the `@page` for `_Host.cshtml`



```
@page "/elsa/workflows"
@{
    var serverUrl = $"{Request.Scheme}://{Request.Host}";
}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Elsa Workflows</title>
    <link rel="icon" type="image/png" sizes="32x32" href="/_content/Elsa.Designer.Components.Web/elsa-workflows-studio/assets/images/favicon-32x32.png">
    <link rel="icon" type="image/png" sizes="16x16" href="/_content/Elsa.Designer.Components.Web/elsa-workflows-studio/assets/images/favicon-16x16.png">
    <link rel="stylesheet" href="/_content/Elsa.Designer.Components.Web/elsa-workflows-studio/assets/fonts/inter/inter.css">
    <link rel="stylesheet" href="/_content/Elsa.Designer.Components.Web/elsa-workflows-studio/assets/styles/tailwind.css">
    <script src="/_content/Elsa.Designer.Components.Web/monaco-editor/min/vs/loader.js"></script>
    <script type="module" src="/_content/Elsa.Designer.Components.Web/elsa-workflows-studio/elsa-workflows-studio.esm.js"></script>
</head>
<body class="h-screen" style="background-size: 30px 30px; background-image: url(/_content/Elsa.Designer.Components.Web/elsa-workflows-studio/assets/images/tile.png); background-color: #FBFBFB;">
    <elsa-studio-root server-url="@serverUrl" monaco-lib-path="_content/Elsa.Designer.Components.Web/monaco-editor/min"></elsa-studio-root>
</body>
</html>
```

update startup.cs `Configure`

```
        public void Configure(IApplicationBuilder app)
        {
            if (Environment.IsDevelopment())
            {
                app.UseDeveloperExceptionPage();
            }

            app
                .UseStaticFiles() // For Dashboard.
                .UseHttpActivities()
                .UseRouting()
                .UseEndpoints(endpoints =>
                {
                    // Elsa API Endpoints are implemented as regular ASP.NET Core API controllers.
                    endpoints.MapControllers();
                    endpoints.MapControllerRoute(
                        name: "default",
                        pattern: "{controller=Home}/{action=Index}/{id?}");

                    endpoints.MapControllerRoute(
                        name: "home",
                        pattern: "",
                        defaults: new { controller = "Demo", action = "Index" }
                     );
                    // For Dashboard.
                    // add this line
                    endpoints.MapRazorPages();
                });
        }
```

**Comment by AvtsVivek** [comment]
Hi
Thank You. Its working.

For others, the summary.

1. Changed the change the `@page`  in the  `_Host.cshtml`  file from `/` to `/elsa/workflows`
2. In the configure method of Startup class, add `endpoints.MapRazorPages();` and completely remove `endpoints.MapFallbackToPage("/_Host");`

But I have one more query.

What if I want the workflow instances and workflow definition pages urls be 

    http://localhost:26284/elsa/Workflows/workflow-definitions 

instead of 

    http://localhost:26284/workflow-definitions

Can that also be configured? This routing seems difficult for me to understand.

**Comment by weirdyang** [comment]
I'm not sure to be honest, looking at the studio code, it seems to be set in the tsx;

https://github.com/elsa-workflows/elsa-core/blob/2ec915dabed9ffd03e9c9101e95a04f2438c1ed7/src/designer/elsa-workflows-studio/src/components/dashboard/pages/elsa-studio-root/elsa-studio-root.tsx

**Comment by AvtsVivek** [comment]
Ok, I will close this issue for now. Its a minor issue.

Again Thank You very much. Deeply appreciated your time.

**Comment by llimos** [comment]
Adding this for people who find this later: You can add a `base-path` attribute to `<elsa-studio-root>`

```<elsa-studio-root base-path="/elsa/workflows"```
