### ISSUE TITLE
Variables not getting persisted when set using workflow instance

### ISSUE THREAD

**Issue by a-khanna** [elsa-workflows/elsa-core#1133]
Hi,
I'm using Elsa with SQL server.
I have created a workflow which is triggered by a signal and contains a lot of UserTasks at various steps.
I have a controller through which I provide endpoints for controlling a particular workflow instance. For example, invoking a workflow, resuming a suspended workflow etc.

In the invoke flow method, I tried setting a variable:
```
[HttpPost("invoke-flow")]
public async Task<IActionResult> InvokeFlow([FromQuery]string keyword, [FromBody]dynamic input)
{
    var startedWorkflows = await _signaler.TriggerSignalAsync(keyword);
    if (!startedWorkflows.Any())
        return BadRequest("No workflows found for the given keyword");

    var instanceId = startedWorkflows.ElementAt(0).WorkflowInstanceId;
    var workflowInstance = await _workflowInstanceStore.FindByIdAsync(instanceId);

    workflowInstance.Variables.Set("input", input);
    // returns instance id
```
But when the workflow gets suspended, this variable does not get persisted in the `data` in `WorkflowInstances` table.
For this reason when I try to resume this suspended instance, the variable count is 0.
```
[HttpPost("resume-instance")]
public async Task<IActionResult> ResumeInstance(UserInput userInput)
{
    var workflowInstance = await _workflowInstanceStore.FindByIdAsync(userInput.InstanceId);
    // variables count is 0 in the below
    var input = workflowInstance.Variables.Get("input");
```

**Comment by sfmskywalker** [comment]
Hi @a-khanna ,

Make sure to persist changes made to the workflow instance, which you can do using the `SaveAsync` method. Try the following:

```csharp
// Set a variable.
workflowInstance.Variables.Set("input", input);

// Persist changed workflow.
await _workflowInstanceStore.SaveAsync(workflowInstance);
```

**Comment by a-khanna** [comment]
As a workaround I was going to pass `input` to `_signaler.TriggerSignalAsync(keyword, input)` so that it gets persisted as the Signal's output, but manually persisting the instance solved it.
Thanks!

**Comment by a-khanna** [comment]
@sfmskywalker btw, could you suggest if it's possible to access/modify `WorkflowExecutionContext` in this setup?
Is there any advantage as compared to Variables in the context of saving and accessing objects?

**Comment by sfmskywalker** [comment]
If you want access to the `WorkflowExecutionContext`, you will need to implement a notification handler for events published by the workflow runner. For example, if you need access to it right before an activity begins execution, you need to handle the `ActivityExecuting` event. Similarly, there are events for `ActivityExecuted`, `ExecutingWorkflow` and much more. For a full list, checkout the [Events directory](https://github.com/elsa-workflows/elsa-core/tree/master/src/core/Elsa.Abstractions/Events).

To answer your second part of your question, it depends on what you are trying to do and for which reason.
