### ISSUE TITLE
Designer allows connecting one activity outcome with multiple activities

### ISSUE THREAD

**Issue by tomy2105** [elsa-workflows/elsa-core#1138]
Shift + Click on + of the same outcome and it connects to multple activities.
![MultipleOutputs](https://user-images.githubusercontent.com/7658839/122366825-3189fe00-cf5c-11eb-89ed-deaa4741cbf4.png)

I think when you shitf + click on an outcome that is already connected it should either do nothing or delete existing connection and make a new one, but not multiply them.

Or I got something wrong and there is some hidden fork ability without fork activity :)?

**Comment by sfmskywalker** [comment]
You found a hidden feature ;)

It's a supported scenario, except for doing this in combination with the `Join` activity to clear any blocking activities higher up the inbound trajectory. But that's something we should fix.

**Comment by sfmskywalker** [comment]
Sure, we can update the designer code to allow only one outgoing connection. But I'm not sure yet we want to disallow it. If it is a problem though, we can always expose it as a setting on the component and let the developer decide.

**Comment by tomy2105** [comment]
I would definitely like to be able to disable it (as I can disable Fork/Join activities).

I you like to keep it then the approach of having a configuration paramter which enables/disables it sounds like a good way to go :).
