### ISSUE TITLE
.AddElsa extension method not available

### ISSUE THREAD

**Issue by giannik** [elsa-workflows/elsa-core#114]
Following the guides  to create a host application
https://elsa-workflows.github.io/elsa-core/docs/guides-dashboard 

it seems that this method 

 .AddElsa(elsa => elsa.AddEntityFrameworkStores(options => options.UseSqlite(Configuration.GetConnectionString("Sqlite"))))

is not available from the nuget packages.

**Comment by sfmskywalker** [comment]
Thanks for letting me know. I'll update the guide and mention that one should add only the following packages:

* Elsa
* Elsa.Dashboard
* Elsa.Persistence.EntityFrameworkCore

Please let me know if this fixes the issue for you?

**Comment by sfmskywalker** [comment]
I updated the guide.

**Comment by giannik** [comment]
Still getting the following ambiguous invocation message : 

![image](https://user-images.githubusercontent.com/1516981/67764358-7a710400-fa52-11e9-8cb4-93ff983aa19b.png)

**Comment by sfmskywalker** [comment]
Ah, I see. Fixing.

**Comment by sfmskywalker** [comment]
I updated the guides repository with working examples.

Please let me know if you find any other issues. Thanks!

**Comment by giannik** [comment]
thank you, sipke,

**Comment by sfmskywalker** [comment]
Is this still a issue or can we close it?
