### ISSUE TITLE
Extension method to add Azure distributed locking has incorrect name

### ISSUE THREAD

**Issue by mdrjob** [elsa-workflows/elsa-core#1142]
The method to add Azure distributed locking to Elsa has name [UseSqlServerLockProvider](https://github.com/elsa-workflows/elsa-core/blob/master/src/locking/Elsa.DistributedLocking.AzureBlob/DistributedLockingOptionsExtensions.cs#L10).

That is the same name as used in the [Sql Server distributed locking](https://github.com/elsa-workflows/elsa-core/blob/master/src/locking/Elsa.DistributedLocking.SqlServer/DistributedLockingOptionsExtensions.cs#L7), so it could be a copypaste mistake.

**Comment by sfmskywalker** [comment]
Thanks for the PR! Please sign the CLA so I can accept it.
