### ISSUE TITLE
Difference between CompositeActivity properties and Activity properties

### ISSUE THREAD

**Issue by tomy2105** [elsa-workflows/elsa-core#1145]
Related to #1122.
Imagine two classes, one implementing Activity and other CompositeActivity having one property which is Dictionary.

    public class SetFlag : Activity
    {
        public IDictionary<string, string> Flags { get; set; } = new Dictionary<string, string>();

        // rest of implementation is irelevant
    }

    public class SetFlagContainer : CompositeActivity, ISetFlag, IActivityWithRealType
    {
        public IDictionary<string, string> Flags
        {
            get => GetState(() => new Dictionary<string, string>());
            set => SetState(value);
        }

        // rest of implementation is irelevant
    }

Looking from the outside their properties look identical and should, if possible, behave identically, but they do not :(.

With `SetFlag` you can do `activity.Flags.Add("FlagName", "Flag Value")` and it will work.
However with `SetFlagContainer` you cannot do `activity.Flags.Add("FlagName", "Flag Value")` and it won't work because add will be executed on the temporary object returned by get state default value callback. So it will actually be lost, because GetState returns temporary object which is never stored into Data, and SetState is never invoked.
The workaround is to do add on temporary dictionary and then do `activity.Flags=temporary`. Then it will invoke SetState and everything will work.

I believe this should be fixed by GetState implementation which should instead of returning temporary (obtained using default callback) actually do a SetState with this temporay if not found and then proceed as if found.

Something along lines (not tested or compiled):

        public static T GetState<T>(this JObject? state, string key, Func<T> defaultValue)
        {
            var item = state?.GetValue(key, StringComparison.OrdinalIgnoreCase);

            if (item == null || item.Type == JTokenType.Null)
            {
                   SetState(key, defaultValue())
                   item = state?.GetValue(key, StringComparison.OrdinalIgnoreCase);
            }

            return item.ToObject<T>(CreateSerializer())!;
        }

**Comment by sfmskywalker** [comment]
Looks good to me. Would you mind submitting a PR with this?
