### ISSUE TITLE
Filter workflow-instances by correlationId

### ISSUE THREAD

**Issue by ricksearcy** [elsa-workflows/elsa-core#1151]
As a service I would like to be able to query the workflow-instances endpoint by correlationId to get workflow instances that have been related to entities in another system by their Id.

This does not appear to be supported.
https://localhost:44391/v1/workflow-instances?correlationId=7cf0839b-03f6-4d12-bfc0-c82f65997c7b
does not work.

**Comment by sfmskywalker** [comment]
Fixed in 11de05173e050a62ae16fa4f16b3b6d36c67907d
