### ISSUE TITLE
Error installing Elsa Workflow Designer NPM

### ISSUE THREAD

**Issue by Gavin0912** [elsa-workflows/elsa-core#1158]
When I embed the
![image](https://user-images.githubusercontent.com/20514838/122751521-70a0b200-d2c2-11eb-8322-732106966902.png)
 designer in the form of the NPM package as a set of HTML Web components, there was a js problem

**Comment by sfmskywalker** [comment]
Any chance you can share your setup that I can try on my machine?

**Comment by josephdangerstewart** [comment]
I've also encountered these errors trying to build the designer (`yarn && yarn build`) locally after pulling from master I'm running node 12.8.3 on Windows 10. I was able to build successfully after changing all of the `eventBus.off(EventTypes.EventName, this.doThing)` calls to `eventBus.off(EventTypes.EventName)`

**Comment by chenmj383606** [comment]
> 您有机会分享我可以在我的计算机上尝试的设置吗？

This problem occurs when you download the package through npm. I don’t have this problem through the cdn link.
![image](https://user-images.githubusercontent.com/20514838/123723941-0b4e5180-d8be-11eb-893f-3b534a421b43.png)

**Comment by josephdangerstewart** [comment]
@chenmj383606, do you see that error output when you install the package? From your screenshot, that looks like output from running `yarn build`, which I don't *think* you should be seeing at all if you're installing it via npm.

**Comment by Gavin0912** [comment]
@josephdangerstewart Yes, I installed it through NPM, and there was an error problem when building

**Comment by sfmskywalker** [comment]
I just got the same error, but it happened after I updated the `js-event-bus` package to the latest version. After updating all packages I accommodated for breaking changes introduced by some of them (including `js-event-bus`) and pushed the changes.

I'm also in the process of automating publishing `master` to the NPM registry. When done, you should be able to update `@elsa-workflows/elsa-workflows-studio` to the latest version.

Although it's still a mystery to me why you would be getting compilation errors when using NPM packages - they have already been built.
