### ISSUE TITLE
2.0 to 2.1 code backward compatibility related to IActivityTypeProvider

### ISSUE THREAD

**Issue by tomy2105** [elsa-workflows/elsa-core#1165]
Started (for some pull requests) compiling code under latest 2.1 code and was greeted with some surprises :)

ActivityDescriptor has now InputProperties and OutputProperties and there is no Properties at the moment.
I would suggest adding "back" Properties to be an alias to InputProperties with obsolete mark.

        [Obsolete("Use InputProperties instead.")]
        public ActivityInputDescriptor[] Properties 
        { 
            get => InputProperties;
            set => InputProperties = value;
        }

Same goes with ActivityPropertyDescriptor which is gone and replaced by ActivityInputDescriptor.
Moreover ActivityInputDescriptor has one more argument in constructor (order) which is not last, so should be accounted for:

    [Obsolete("Use ActivityInputDescriptor instead.")]
    public class ActivityPropertyDescriptor : ActivityInputDescriptor
    {
        public ActivityPropertyDescriptor() : base()
        {
        }

        public ActivityPropertyDescriptor(
            string name,
            Type type,
            string uiHint,
            string label,
            string? hint = default,
            object? options = default,
            string? category = default,
            object? defaultValue = default,
            string? defaultSyntax = "Literal",
            IEnumerable<string>? supportedSyntaxes = default,
            bool? isDisabled = default)
            : base (
                name,
                type,
                uiHint,
                label,
                hint,
                options,
                category,
                0,
                defaultValue,
                defaultSyntax,
                supportedSyntaxes,
                isDisabled
            )
        {
        }
    }

ActivityType's methods CanExecuteAsync, ExecuteAsync and ResumeAsync now take two parameters. Don't know how to deal with this in backward compatible manner :(.

**Comment by sfmskywalker** [comment]
> Started (for some pull requests) compiling code under latest 2.1 code and was greeted with some surprises :)

It probably didn't give you Happy Christmas feelings 😅 

> ActivityType's methods CanExecuteAsync, ExecuteAsync and ResumeAsync now take two parameters. Don't know how to deal with this in backward compatible manner :(.

Maybe let's not worry about this one - it's a compile-time error and likely not used by too many devs since it's an advanced feature. Those devs who do use it must be highly-skilled anyway. Tell me I'm wrong ;)

I agree with adding back the removed / renamed properties as you proposed, marking them as obsolete 👍🏻 .
