### ISSUE TITLE
Unknown discriminator value 'FinishOutput'

### ISSUE THREAD

**Issue by Juandavi1** [elsa-workflows/elsa-core#1177]
Hi guys,

I have the following message when I want to go to the workflow instances

`[15:57:10 ERR] flow-engine 06/25/2021 20:57:10 500 Internal Server Error System.FormatException: An error occurred while deserializing the Output property of class Elsa.Models.WorkflowInstance: Unknown discriminator value 'FinishOutput'. ---> MongoDB.Bson.BsonSerializationException: Unknown discriminator value 'FinishOutput'.`
dependency
`<PackageReference Include="Elsa.Persistence.MongoDb" Version="2.0.0.159"/>
`
should i update some other dependency?

Thanks, awesome project !!

**Comment by sfmskywalker** [comment]
I can't seem to reproduce this issue with the latest builds of Elsa 2.1. We did do some fixes with MongoDB serialization, so I'm going to assume we fixed it and close this issue. Please reopen if you can repro the issue with Elsa 2.1 (preview).

Thanks!
