### ISSUE TITLE
Swagger UI for Elsa Server Sample not working

### ISSUE THREAD

**Issue by AvtsVivek** [elsa-workflows/elsa-core#1178]
I ran [this sample](https://github.com/elsa-workflows/elsa-core/tree/master/src/samples/server/Elsa.Samples.Server.Host), I get the following error message for the url https://localhost:11000/swagger/index.html

Am I missing something?

![image](https://user-images.githubusercontent.com/41255281/123507681-541cc500-d688-11eb-86fc-48cef2c0a195.png)

![image](https://user-images.githubusercontent.com/41255281/123507655-30f21580-d688-11eb-9602-65aeb097fc34.png)

**Comment by sfmskywalker** [comment]
I get the same, it's caused by a recent change. Will fix. Thanks for reporting!
