### ISSUE TITLE
Document for each of the Activity

### ISSUE THREAD

**Issue by khanhtranchi** [elsa-workflows/elsa-core#1180]
This is a great workflow framework, but the lack of the document for each of the activity make it hard to use. I appreciate a detail document about the parameter of activity, how it works and interact with other activates along with the examples.

**Comment by tomy2105** [comment]
I believe this is a duplicate of #1113 . @khanhtranchi you can close this one and add any points you have to the #1133.

**Comment by sfmskywalker** [comment]
Thanks for the kind words @khanhtranchi. As pointed out by @tomy2105 , please feel free to add your comments to #1113 which has the same subject (document activities).
