### ISSUE TITLE
ActivityPropertyUIHints.Json is not supported by UI

### ISSUE THREAD

**Issue by PietroLubini** [elsa-workflows/elsa-core#1185]
Activity properties that are declared as "UIHint = ActivityPropertyUIHints.Json" 
1) could not be configured in UI
2) has Literal syntax only that makes them unevaluable:
LiteralHandler
Task.FromResult(expression.Parse(returnType)

It seems that the following fix could work

 [ActivityProperty(
        Hint = "Additional headers to send along with the request.",
        UIHint = ActivityPropertyUIHints.**MultiLine**,
        **DefaultSyntax = SyntaxNames.Json**,
        **SupportedSyntaxes = new[] { SyntaxNames.Json }**)]
    public HttpRequestHeaders RequestHeaders { get; set; } = new();

**Comment by sfmskywalker** [comment]
Indeed, thanks for reminding me to implement that one 😄

**Comment by sfmskywalker** [comment]
Fixed with c3a73d1c17ac0ed36f8aadc9594adb5e9ca65b26
