### ISSUE TITLE
Variables in workflow instances 

### ISSUE THREAD

**Issue by DvpDevelop** [elsa-workflows/elsa-core#1189]
I guys, 

we have a workflow with a switch activity that evaluates an existing variable in the execution context.

It works fine, but when I try to view the workflow instance the variables don't exist and no show the execution graph :'( 

server
`
Failed to evaluate expression formOptions == 0 using syntax JavaScript <s:Elsa.Expressions.ExpressionEvaluator> 
ReferenceError: formOptions is not defined
`

client 
`TypeError: Cannot read property '$values' of null
    at kB.onActivityDesignDisplaying`

and when i enable Save Workflow Context in the designer it throws de following exception 

`500 Internal Server Error System.FormatException: An error occurred while deserializing the Fault property of class Elsa.Models.WorkflowInstance: An error occurred while deserializing the Exception property of class Elsa.Models.WorkflowFault: An error occurred while deserializing the Type property of class Elsa.Models.SimpleException: Specified method is not supported.`

Could you guide us? 

Thanks !!

**Comment by sfmskywalker** [comment]
Let me guess: you’re using MongoDB as the persistence provider?

If so, then the second part of your issue has been fixed and will be released with 2.1 (which is already available from MyGet as preview packages).

Regarding your first issue with the Switch activity, I will have a look into that this week. If I can reproduce I will fix, which too will be part of 2.1.

**Comment by sfmskywalker** [comment]
It all looks good on `master` and the 2.1 preview packages, so I will close this issue as fixed. Should you still encounter these issues after upgrading, please reopen. Thanks!

**Comment by DvpDevelop** [comment]
When you say 2.1 is the same 2.0.0.1? I have version 2.0.0.159 in the dependencies. I can't find version 2.1 :( 

thanks for answering

**Comment by dwevedivaibhav** [comment]
Hi @sfmskywalker ,

I am unable to load workflow instances menu (Elsa UI) in elsa 2.8.2 when activity failed while executing workflow. I am using mongo db
please find the below error which i got in code

An unhandled exception was thrown by the application.", "exception": "System.FormatException: An error occurred while deserializing the Fault property of class Elsa.Models.WorkflowInstance: An error occurred while deserializing the Exception property of class Elsa.Models.WorkflowFault: An error occurred while deserializing the Type property of class Elsa.Models.SimpleException: Specified method is not supported.\r\n ---> System.FormatException: An error occurred while deserializing the Exception property of class Elsa.Models.WorkflowFault: An error occurred while deserializing the Type property of class Elsa.Models.SimpleException: Specified method is not supported.

Please advice how we can fix this issue.

Thanks
