### ISSUE TITLE
When using YesSQL provider, publishing workflow from dashboard yields an error: SqlException: Incorrect syntax near 'WorkflowDefinitionIndex'.

### ISSUE THREAD

**Issue by sfmskywalker** [elsa-workflows/elsa-core#119]

**Comment by giannik** [comment]
Thanks. That fixes it. Now I am getting this error : 
![image](https://user-images.githubusercontent.com/1516981/68088532-d8de1e00-fe68-11e9-9fa9-fe6bc1b5ce1d.png)

**Comment by sfmskywalker** [comment]
Reopening issue

**Comment by sfmskywalker** [comment]
I believe this issue has been fixed. Can you confirm?

**Comment by sfmskywalker** [comment]
I'm closing this as I believe this has now been fixed. If not, please re-open. Thanks!
