### ISSUE TITLE
HTTP Controller problem when database is not available.

### ISSUE THREAD

**Issue by tomy2105** [elsa-workflows/elsa-core#1192]
I have Elsa 2.0 configured to use Postgres database.

In addition in code I have one simple endpoint controller:

    [ApiController]
    [Route("test")]
    public class TestController : Controller
    {
        [HttpGet]
        public async Task<IActionResult> Handle(CancellationToken cancellationToken)
        {
            return NoContent();
        }
    }

When Postgres is available everything is ok and /test returns 204 (NoContent)

However if I turn Postgres off even the simple endpoint which doesn't have anything to do with Postgres stops working and returns 500.
I think it is because Elsa middleware somewhere along the path looks for workflow endpoints in database and it fails.

**Is there a way to have non-Elsa, non-Database endpoint controllers work even in case when Database is down?**

**Comment by sfmskywalker** [comment]
> I think it is because Elsa middleware somewhere along the path looks for workflow endpoints in database and it fails.

Indeed. To prevent invoking this middleware from executing for ALL requests, you can configure the middleware to handle only requests to a certain path. For example, the `Elsa.Samples.Server.Host` sample Elsa Server project configures this middleware to handle requests only at `/workflows`.

You can configure this during the call to `AddHttpActivities()`. Example:

```csharp
services.AddElsa(elsa => elsa.AddHttpActivities(options => options.BasePath = "/workflows");
```

When you have a workflow starting with **HTT Endpoint** configured with path `"/my-workflow"`, it will only respond to requests made to `"/workflows/my-workflow"`.

**Comment by tomy2105** [comment]
Thanks, that worked!
