### ISSUE TITLE
Signal From Another Application

### ISSUE THREAD

**Issue by CansuGoren** [elsa-workflows/elsa-core#1200]
After register documents and information control, If everything is ok, I want to resume my workflow and I thought that I could do that using send signal.
How can I send a signal from another application( like running with angular js frontend), is it possible?
Thank you in advance.

**Comment by sfmskywalker** [comment]
Certainly. There are 2 API endpoints you can invoke to send a signal from your front-end app:

- v1/signals/{signalName}/execute
- v1/signals/{signalName}/dispatch

The difference between execute and dispatch is that the former will execute the workflow before returning an HTTP response, while the latter will schedule the workflow for execution on a background queue and return an HTTP response immediately.

To send additional workflow input, workflow instance ID and/or correlation ID, take a look at the source code to see what JSON model to post with:

https://github.com/elsa-workflows/elsa-core/tree/master/src/server/Elsa.Server.Api/Endpoints/Signals
