### ISSUE TITLE
Dashboard: Display problem with Context-Menu in Workflow-Overview

### ISSUE THREAD

**Issue by Andale-online** [elsa-workflows/elsa-core#122]
Hey there...

Just some cosmetics:

![image](https://user-images.githubusercontent.com/57248720/68114428-42f0d480-fef6-11e9-8a50-1bc80077a18a.png)

Maybe create the list with a minimum height to solve this in a quick manner? I can't select the hidden context-menu parts.

System: FF 70.0.1 on Windows 10

**Comment by sfmskywalker** [comment]
That sounds like a good quick fix.
