### ISSUE TITLE
Don#t use colon in appsettings

### ISSUE THREAD

**Issue by jwillmer** [elsa-workflows/elsa-core#1223]
Kubernetes does not support colons (`:`) in environment variables and I also have a problem in docker-compose.

Current appsettings.json
```
...
  "Elsa": {
    "Features": {
      "Persistence:EntityFrameworkCore:Sqlite": {
        "Enabled": true,
        "ConnectionStringName": "Sqlite"
      },
      "Console": true,
...
```

If I like to override `Console` in appsettings via env variable I can do it one of two ways:
```
-e Elsa__Features__Console="false"
-e Elsa:Features:Console="false"
```

But if I like to override `Persistence:EntityFrameworkCore:Sqlite` I have a problem because docker-compose treats `:` and `__` as delimiters. I haven't found any escape for it yet. For Kubernetes it is even worse since it does not allow `:` at all in the environment settings as described in this issue: [Environment variables containing colon not allowed](https://github.com/kubernetes/kubernetes/issues/53201)

**Comment by Axeleron007** [comment]
I suggest to remove colons from (an example) "Persistence:EntityFrameworkCore:Sqlite" and just name it as "PersistenceEntityFrameworkCoreSqlite". If everyone is happy it will be a quick and cheap fix.

**Comment by jwillmer** [comment]
doesn't help. there are more options with colons!

**Comment by sfmskywalker** [comment]
@jwillmer Maybe I misunderstood, but @Axeleron007 said he will remove all colons from all options. That should help, right?
