### ISSUE TITLE
Feature Request: XMLContentFormatter + POCO loader

### ISSUE THREAD

**Issue by Andale-online** [elsa-workflows/elsa-core#123]
Hey dude...

I need XML as ContentFormatting - there is no such feature, isnt it?

Even more it should be able to cast the requests in a type safe manner (e.g. against a poco dll)

I did this before for Web Api - think i can do this and commit it. I rly rly rly need that.... Do you wanna have this?

Greetings

**Comment by sfmskywalker** [comment]
We don’t have it yet, but I have a sneaky suspicion you will send a PR with that feature 😉

Perhaps you could describe it in a little bit more detail / provide a use case?

For example, are you posting an XML payload to a workflow, and you want that XML to be deserialized into a POCO?

If so, we need to come up with a way for a user to specify what type of poco it should be. And maybe by default it would be deserialized to a JObject, so that you could easily access its members from Liquid and JavaScript expressions.

**Comment by Andale-online** [comment]
Err.. For sure... I will do so.

But first: I cloned the JsonContentFormatter to:

`namespace Elsa.Activities.Http.Formatters
{
    public class XMLContentFormatter : IContentFormatter
    {
        public int Priority => 2;
        public IEnumerable<string> SupportedContentTypes => new[] { "application/xml", "text/xml" };

        public Task<object> ParseAsync(byte[] content, string contentType)
        {
            string rootNodeName = "";
            using (XmlReader xmlReader = XmlReader.Create(new MemoryStream(content)))
            {
                if (xmlReader.MoveToContent() == XmlNodeType.Element)
                    rootNodeName = xmlReader.Name;
            }

            if(rootNodeName != "")
            {
               
                
            }

            return null;


        }
    }
}
`

But my formatter doesnt get loaded to 

        public ReceiveHttpRequest(
            IHttpContextAccessor httpContextAccessor,
            IEnumerable<IContentFormatter> contentFormatters)

Any idea?

**Comment by Andale-online** [comment]
Too early in the mornin... Forget the question... Think i found it

**Comment by Andale-online** [comment]
.AddSingleton<IContentFormatter, XMLContentFormatter>()

**Comment by sfmskywalker** [comment]
Good morning 😉

**Comment by Andale-online** [comment]
Mornin.... :-D

So... In theory i got the receiver formatter working :-D Got some dll loading issue, but that will be solved after another coffee...

**Comment by Andale-online** [comment]
So... Request Formatter is working with autoloader. Means the incoming model type is loaded by reflection search. There has to be an option to override this for the step. The override should disable all reflection, so type safe routes are gaining back the performance. This way you can have type safe and also the JObject option - i doubt this is something you should do. 

Big question - i made a branch... how do i commit, so you can have a look ^^ :-D

**Comment by sfmskywalker** [comment]
That sounds wonderful. Please create a fork of this repo so you can commit to that and I’ll gladly have a look! I am about to travel to Germany however so it might take a while before I get another chance to look at things.

**Comment by Andale-online** [comment]
Switched from contentformatter to httprequesthandler for the XML. Will be in the next PR

**Comment by Andale-online** [comment]
Need pull request #161 to straighten this all. Can you review / test it?

**Comment by Andale-online** [comment]
Closing this issue due new features of framework. Pocoloader is in activities.reflection
