### ISSUE TITLE
Undefined in Switch activity  

### ISSUE THREAD

**Issue by Juandavi1** [elsa-workflows/elsa-core#1239]
Hi guys, 
I have an issue when i go to the workflow-instances. The switch activity it works fine but when rendering execution it show undefined. Im working with 2.1.0-preview.421 version

definition:
<img width="750" alt="Captura de Pantalla 2021-07-10 a la(s) 8 19 29 p  m" src="https://user-images.githubusercontent.com/18731612/125180147-3a1ccf80-e1bc-11eb-819f-60cd31da2173.png">

instance: 
<img width="574" alt="Captura de Pantalla 2021-07-10 a la(s) 8 15 31 p  m" src="https://user-images.githubusercontent.com/18731612/125180106-c24ea500-e1bb-11eb-87b0-0bcdabddbd3c.png">

thanks so much

**Comment by sfmskywalker** [comment]
Hi Juan,

I tried to reproduce this issue, but it seems to be working fine for me:

![image](https://user-images.githubusercontent.com/938393/125281275-52a0fd00-e316-11eb-928c-5ee315609eef.png)

If you can send me a project with the issue, I can look into it for you.

**Comment by DvpDevelop** [comment]
A question, are you evaluating the switch with some context variable or with the output of http endpoint?

**Comment by Juandavi1** [comment]
A question, are you evaluating the switch with some context variable or with the output of http endpoint?

**Comment by sfmskywalker** [comment]
Not really actually. The `Switch` activity simply evaluates each case's Expression property. You can of course use any context you like within each case expression, such as output of the **HTTP Endpoint** activity.

For example, the following **Switch** activity has two cases where it checks against a query string value of the HTTP Endpoint output:

![image](https://user-images.githubusercontent.com/938393/125288474-7c5e2200-e31e-11eb-9d27-aff32cde24bc.png)

**Comment by Juandavi1** [comment]
hi, could you try evaluating the condition with a context variable? thanks

**Comment by sfmskywalker** [comment]
I tried and with success. Are you running into an issue?

**Comment by Juandavi1** [comment]
now I'm doing it through variables but I'm going to test it with an input. Thanks a lot
