### ISSUE TITLE
How to define a dictionary property in a custom activity?

### ISSUE THREAD

**Issue by VahidShir** [elsa-workflows/elsa-core#1241]
I already know how to [define simple property](https://elsa-workflows.github.io/elsa-core/docs/next/extensibility/extensibility-custom-activities#properties) types such as `string` in custom activities. It works fine and it is shown in designer and also exposed in HTTP endpoint JSON response as well, but I want a dictionary type, enabling us to fill it in activity designer.

Here's what I tried:
```
[Activity(
    DisplayName = "Custom Activity",
    Description = "It's a customized activity",
    Category = "Custom",
    Outcomes = new[] { OutcomeNames.Done }
)]
public class SampleActivity : Activity
{
    [ActivityProperty(Hint = "Variables associated to this activity")]
    public Dictionary<string, string> Variables { get; set; }

    protected override IActivityExecutionResult OnExecute(ActivityExecutionContext context)
    {
        Console.WriteLine("Variables: " + string.Join(", ", Variables.Keys));

        return Done();
    }
}
```
![image](https://user-images.githubusercontent.com/8729558/125185666-5b70d080-e23b-11eb-9ab8-8d025e5b4a80.png)

But this property isn't working as expected and I'm not able to insert anything into it.

- And also please tell me how to define a property in a custom activity without exposing it in designer, only exposing it in HTTP endpoints JSON results (setting it programmatically in activity).
Thanks.

**Comment by jdevillard** [comment]
Hello, 

have you take a look at the UIHint and SupportedSyntaxes  of the ActivityInput Decorator ? 

for example, 
```
        [ActivityInput(
            UIHint = ActivityInputUIHints.MultiLine,
            DefaultSyntax = SyntaxNames.Json,
            SupportedSyntaxes = new[] { SyntaxNames.JavaScript, SyntaxNames.Liquid, SyntaxNames.Json }
```

and try to write your json dictionnary in the Text Form (in JSON mode or Javascript mode)
```
{
"key1":"value1",
"key2":"value2":
}
```
