### ISSUE TITLE
Create simplified version of HTTP Endpoint

### ISSUE THREAD

**Issue by tomy2105** [elsa-workflows/elsa-core#1247]
Elsa 2.0 from NuGet....
Inspired by your answer to https://github.com/elsa-workflows/elsa-core/discussions/1212 and based on the `WebhookActivityTypeProvider` I tried adding my simple HTTP Endpoint based activity using code below.

Activity is visible in designer, however calling its URL/path does not trigger workflow.
Similar as #1237 I don't see `ActivateActivityAsync` ever invoked.

Can you advise what I am missing?
Do I need my bookmark provider (your answer in https://github.com/elsa-workflows/elsa-core/discussions/1212 seems to indicate it is not required but I might have misunderstood it :()?

Thanks in advance.

    public class EndpointActivityProvider : IActivityTypeProvider
    {
        private readonly IActivityActivator _activityActivator;

        public EndpointActivityProvider(
            IActivityActivator activityActivator)
        {
            _activityActivator = activityActivator;
        }

        public async ValueTask<IEnumerable<ActivityType>> GetActivityTypesAsync(CancellationToken cancellationToken = default)
        {
            var activityTypes = new List<ActivityType>();
            var activity = CreateEndpointActivityType();
            activityTypes.Add(activity);

            return activityTypes;
        }

        private ActivityType CreateEndpointActivityType()
        {
            var descriptor = new ActivityDescriptor
            {
                Type = "TestTypeName",
                DisplayName = "TestDisplayName",
                Category = "HTTP",
                Outcomes = new[] { OutcomeNames.Done },
                Traits = ActivityTraits.Trigger,
                Properties = new[]
                {
                    new ActivityPropertyDescriptor(
                        nameof(HttpEndpoint.Path),
                        typeof(string),
                        ActivityPropertyUIHints.SingleLine,
                        "Path",
                        "Specify Path",
                        null,
                        null,
                        "",
                        SyntaxNames.Literal,
                        new[] { SyntaxNames.Literal, SyntaxNames.JavaScript, SyntaxNames.Liquid })
                }
            };

            async ValueTask<IActivity> ActivateActivityAsync(ActivityExecutionContext context)
            {
                var activity = await _activityActivator.ActivateActivityAsync<HttpEndpoint>(context);

                activity.Methods = new HashSet<string>(new[] { "GET" });
                activity.ReadContent = false;
                activity.TargetType = null;
                return activity;
            }

            return new ActivityType
            {
                TypeName = descriptor.Type,
                Type = typeof(HttpEndpoint),
                Description = descriptor.Description,
                DisplayName = descriptor.DisplayName,
                ActivateAsync = ActivateActivityAsync,
                Describe = () => descriptor
            };
        }
    }

**Comment by sfmskywalker** [comment]
> Do I need my bookmark provider (your answer in #1212 seems to indicate it is not required but I might have misunderstood it :()?

Indeed, in this case you should provide a custom bookmark provider. The `HttpEndpointMiddleware` is wired to find all bookmarks that are associated with the activity type name `HttpEndpoint`.

However, you're providing an activity with type name `TestTypeName`. Writing a custom bookmark provider allows you to create bookmarks that will be found by the HTTP Endpoint Middleware component.

Here's an example:

```csharp

// The custom provider must still yield HttpEndpointBookmark bookmark objects - this is what the middleware expects.
public class EndpointBookmarkProvider : BookmarkProvider<HttpEndpointBookmark>
{
    // Tell the bookmark finder that we support "TestTypeName" activities.
    public override bool SupportsActivity(BookmarkProviderContext context) => context.ActivityType.TypeName == "TestTypeName";

    public override async ValueTask<IEnumerable<BookmarkResult>> GetBookmarksAsync(BookmarkProviderContext context, CancellationToken cancellationToken)
    {
        // We need to create an HttpEndpointBookmark with a Path to match against.
        var path = ToLower(await context.ReadActivityPropertyAsync<HttpEndpoint, PathString>(x => x.Path, cancellationToken))!;

        // As well as a list of supported HTTP methods. These need to normalized into lowercase representations.
        var methods = new [] { "get" };
        
        return new[] { Result(new(path, methods, nameof(HttpEndpoint)) };
    }

    private static string ToLower(string s) => s.ToLowerInvariant();
}
```

When you register the above with `AddBookmarkProvider<EndpointBookmarkProvider>()`, it should work.
