### ISSUE TITLE
Default value for input property and output property storage per each input/output

### ISSUE THREAD

**Issue by tomy2105** [elsa-workflows/elsa-core#1254]
In Elsa 2.1 one can choose whether input/output value is persisted or not, default value is set for whole Elsa using  `services.AddElsa(elsa => elsa.UseDefaultWorkflowStorageProvider<TransientWorkflowStorageProvider>());`

Would it be possible that for custom activities and their properties you can specify initial value of storage flag (default, instance, transient, blob) as part of **each** activity property definition (ActivityInput/ActivityOutput attribute)? And same for properties created by IActivityProvider?

Moreover, would it be possible to add another flag which would indicate whether this control is even displayed in UI (so end workflow developer cannot change it :))?

**Comment by sfmskywalker** [comment]
Yes, all possible. And probably not too hard to do either :))
