### ISSUE TITLE
Error when trying to import workflow

### ISSUE THREAD

**Issue by Alexplose** [elsa-workflows/elsa-core#1256]
Can we get a more detailed error message when importing badly formatted json :
Uncaught (in promise) TypeError: Cannot read property 'outcomes' of undefined

I'm trying to convert Elsa 1.5 json output to 2.0.

https://github.com/elsa-workflows/elsa-core/blob/40b53b24a61fe236877af5764b32d3e1368d2d7e/src/designer/elsa-workflows-studio/src/components/screens/workflow-definition-editor/elsa-workflow-definition-editor-screen/elsa-workflow-definition-editor-screen.tsx#L279

**Comment by sfmskywalker** [comment]
Sure. What more details would you expect, exactly?

**Comment by Alexplose** [comment]
The activity type name.
An error message like this : 
The activity named 'Signaled' was not found, possible activity names are [SignalReceived,Fork,Join,.....]

**Comment by sfmskywalker** [comment]
Ah, so the underlying reason for the error was that the JSON is referencing an activity that wasn't registered / doesn't exist.

We can (and will) definitely handle this. As a first step, we can just state the the referenced activity doesn't exist. As an upgrade, we could try the fuzzy search later. I've never done anything with that, so I'm not sure how hard or easy that is to do, but perhaps using some library like [FuzzySharp](https://github.com/JakeBayer/FuzzySharp) might make that straightforward.
