### ISSUE TITLE
Instance Viewer Activity Map JS Error

### ISSUE THREAD

**Issue by matt4446** [elsa-workflows/elsa-core#1257]
> Version: 2.1.0-preview.432 

Anything I need to change on my custom activities? It's breaking the instance viewer ;) 

![image](https://user-images.githubusercontent.com/1550939/125475797-579604b1-c451-474f-8c78-04ebfea351eb.png)

**Comment by sfmskywalker** [comment]
These sort of exceptions are expected actually. When loading the workflow instance model for viewing, the server tries to evaluate the property value providers for display. That doesn’t work when using context that is not there, but doesn’t pose any issues. The exceptions are all handled.
________________________________
Van: Matthew Green ***@***.***>
Verzonden: Tuesday, July 13, 2021 5:07:26 PM
Aan: elsa-workflows/elsa-core ***@***.***>
CC: Subscribed ***@***.***>
Onderwerp: [elsa-workflows/elsa-core] Instance Viewer Activity Map JS Error (#1257)


Version: 2.1.0-preview.432

Anything I need to change on my custom activities? It's breaking the instance viewer ;)

[image]<https://emea01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fuser-images.githubusercontent.com%2F1550939%2F125475797-579604b1-c451-474f-8c78-04ebfea351eb.png&data=04%7C01%7C%7Cf5d2e2a0d11a4efefecd08d9460fed6a%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637617856478876884%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=BsoWEWrdXBtP8IsRSNr1CinNk4%2FOz7LxDAomM38%2B6Vo%3D&reserved=0>

**Comment by matt4446** [comment]
it doesn't appear to be caught in this instance (JS) 
![image](https://user-images.githubusercontent.com/1550939/125495694-330cd6a6-788f-4fd8-a06b-5716a39879f0.png)

The workflow instance viewer isn't rendering anymore:  
![image](https://user-images.githubusercontent.com/1550939/125496074-282e0364-ed5a-4c04-a6e8-ddc89d019ed1.png)
Fairly sure it was working in 2.1.0-preview.362 for the same instances.

**Comment by sfmskywalker** [comment]
Sorry, I completely misread your initial post. Teaches me well to try and look at my smartphone without glasses ;)

This looks like a different issue altogether. Any chance you have some repro steps for me to try?

**Comment by matt4446** [comment]
No problem :) 
I can but not in the next couple of days. Hopefully, I can create something on the weekend

**Comment by Alexplose** [comment]
I'm having the same issue here after updating from 2.0.0.159 to 2.1.0.443

![image](https://user-images.githubusercontent.com/18287013/125911780-993b25f0-89ce-4092-997a-c8341893ffed.png)

![image](https://user-images.githubusercontent.com/18287013/125912024-483c5e6f-cd9e-49c0-9e89-5153d5c90ce6.png)

![image](https://user-images.githubusercontent.com/18287013/125912055-eec42268-9395-4e7b-b532-99e8d166e60d.png)


The activity type is a simple Join, can't display workflow instance anymore.
The instance was started with previous version, I deleted and restarted and the instance created with new version has the same problem.

**Comment by matt4446** [comment]
Just upgraded to 2.1 (2.1.1.467 from a preview version 2.1.1.x) and the old workflows history can be viewed again. 

Just replaced the old workflows as they (more expectantly as per announcement ) stopped working - but in the designer.  
New workflows are happy with the designer and history. 

@Alexplose have you tried the version above?

**Comment by Alexplose** [comment]
I've upgraded, and now can't display workflow definitions anymore, and workflow instances still doesn't work.

Is there anything to do to get workflow definitions displaying again ?
Do I need to recreate all the workflows again ?

**Comment by matt4446** [comment]
Odd some of my broken ones in the designer yesterday seem to be working fine today (designer and viewer). Maybe I didn't need to recreate a particular workflow after all.  
I have that error too (but not after deployed 🥳) but I'm not paying much attention to it (at the moment). I had a feeling it was Monaco but I have that set up already, which I don't want to fiddle around with right now.   
... Curiously ignoring it has paid off and I cant seem to find that error anymore on localhost or staging 

All seems to be well again
