### ISSUE TITLE
On the issue of designer css style pollution

### ISSUE THREAD

**Issue by mayaoxiansheng** [elsa-workflows/elsa-core#1265]
vue----main.js

import {
  defineCustomElements as elsa
} from "@elsa-workflows/elsa-workflows-studio/loader";
import '@elsa-workflows/elsa-workflows-studio/dist/elsa-workflows-studio/assets/styles/tailwind.css'

Style will conflict with antdesign.

**Comment by sfmskywalker** [comment]
Conflict in what way?

**Comment by mayaoxiansheng** [comment]
> Conflict in what way?

Some styles cover each other. Both antdesignvue and tailwind.css are introduced globally.
Lead to partial style coverage. For example, input border color change。

**Comment by sfmskywalker** [comment]
Are these styles coming from 2.0 or 2.1 packages? Since 2.1, the tailwind css classes are prefixed with `elsa-` to avoid clashes with other framework styles. But perhaps there are some custom non-tailwind classes in use that are conflicting. If so, please feel free to submit a PR with different class names.

**Comment by mayaoxiansheng** [comment]
> Are these styles coming from 2.0 or 2.1 packages? Since 2.1, the tailwind css classes are prefixed with `elsa-` to avoid clashes with other framework styles. But perhaps there are some custom non-tailwind classes in use that are conflicting. If so, please feel free to submit a PR with different class names.
From 2.1.
Is it possible to achieve style isolation?
Like the scoped in the vue component, it only acts on the current page.

**Comment by mayaoxiansheng** [comment]
> Are these styles coming from 2.0 or 2.1 packages? Since 2.1, the tailwind css classes are prefixed with `elsa-` to avoid clashes with other framework styles. But perhaps there are some custom non-tailwind classes in use that are conflicting. If so, please feel free to submit a PR with different class names.

From 2.1.
Is it possible to achieve style isolation?
Like the scoped in the vue component, it only acts on the current page.

**Comment by sfmskywalker** [comment]
Stencil supports shadow dom components, which might be the solution. But I’ve never gotten quite the hang of it. Perhaps this is one thing to revisit.

**Comment by mayaoxiansheng** [comment]
> Stencil supports shadow dom components, which might be the solution. But I’ve never gotten quite the hang of it. Perhaps this is one thing to revisit.


Thank you！I will try to learn  Stencil.Try to solve it.
In addition. The conflict with it is Ant Design of Vue.The URL is "https://antdv.com/docs/vue/introduce-cn/".
The class name starts with "ant-". Hope this information helps solve this problem.
