### ISSUE TITLE
ContextId is not stored in the database

### ISSUE THREAD

**Issue by Rafael94** [elsa-workflows/elsa-core#1271]
Hi,

i just noticed that the `ContextId` is not stored in the database. However, it is present during runtime. The `ContextType` is stored in the database. I tried the `CorrelationId` and it is also stored.

I need the `ContextId` for the specification `WorkflowInstanceContextIdMatchSpecification`, so I can check if an instance for a specific object has already been created.

Version: 2.1.0.443
DB Provider: EntityFramework (MSSQL)

```
var workflow = await workflowRegistry.FindAsync(x => x.Name == "xxx");
var workflowRunner = GetRequiredService<IStartsWorkflow>();
await workflowRunner.StartWorkflowAsync(workflow, contextId: id.ToString());
```
Workflow Definition:
```
builder
 .WithContextType<MyObject>()
...
```

**Comment by Rafael94** [comment]
@sfmskywalker 
I have found the mistake. 

The mistake is in `WorkflowContextRefresher.SaveAsync`. The function returns `NULL` and this is then used as `ContextId`.

I would suggest a change. 

Instead of `new()`, `context.ContextId` should be returned.

**Comment by sfmskywalker** [comment]
Yes, great catch. Will push a fix.
