### ISSUE TITLE
Rebus connection count optimization

### ISSUE THREAD

**Issue by tomy2105** [elsa-workflows/elsa-core#1272]
It seems Elsa is creating/using 7 Rebus "busses" one for each of:
- Elsa.Dispatch.TriggerWorkflowsRequest
- Elsa.Dispatch.ExecuteWorkflowDefinitionRequest
- Elsa.Dispatch.ExecuteWorkflowInstanceRequest
- Elsa.Caching.Rebus.Messages.TriggerCacheSignal
- Elsa.Events.WorkflowDefinitionPublished
- Elsa.Events.WorkflowDefinitionRetracted
- Elsa.Events.WorkflowDefinitionDeleted

And, at least when using Postgres backend for Rebus, each bus uses, at least, one worker/connection.
Which when having more Elsa instances quickly blows out of proportions (7 * number of instances at least)

It might be beneficial to cut down number of busses used and instead use single one with additional parameter(s) or similar.

**Comment by sfmskywalker** [comment]
Do you have any suggestions how to use one bus for different message types, or at least have different queues for each type all the while using a single bus? I never really quite understood rebus, until I thought I did and concluded one needs a bus per queue for consuming that queue. I’d be very pleased if I were wrong.

**Comment by tomy2105** [comment]
I don't have much experience with Rebus either so would have to go deeper :).
One way without going into Rebus internals would be probably be to have a single message with additional parameter.
So instead of:
- Elsa.Events.WorkflowDefinitionPublished
- Elsa.Events.WorkflowDefinitionRetracted
- Elsa.Events.WorkflowDefinitionDeleted
have only:
- Elsa.Events.WorkflowDefinitionChanged
with a parameter saying whether it was published, retracted or deleted.....

This would also, as a "side-effect", diminish number of MediatR listener types, reducing number of classes that MediatR creates when publishing events :).....

**Comment by sfmskywalker** [comment]
Looks like it's not possible to use a single bus to read from multiple queues given [this reply](https://github.com/rebus-org/Rebus/issues/791#issuecomment-482223128) from @mookid8000.

Your suggestion to merge the various event messages into a single one would indeed drop the number of buses we have to use, but at the same time it seems not very elegant. Before we go down this route, it would be good to investigate some more.

**Comment by sfmskywalker** [comment]
[As it turns out](https://github.com/rebus-org/Rebus/issues/791#issuecomment-886051352), we can use a single queue for different event types. Using a message type per queue makes sense for high-volume messages, but for the various event types we have, a single queue is more than enough.

Which means the actionable for this issue is:

- Update Elsa to allow configuration of multiple message types per queue.

**Comment by sfmskywalker** [comment]
Fixed in b1380616618ebddefc835b919ad722fdfd03fb88
