### ISSUE TITLE
Feature request: Code-Editor for JS with Syntax-Highlight

### ISSUE THREAD

**Issue by Andale-online** [elsa-workflows/elsa-core#130]
Nothing to comment... There should be a lot suitable projects for this...

**Comment by sfmskywalker** [comment]
Definitely a great improvement to make. A great code editor / syntax highligher library is [Code Mirror](https://codemirror.net/). We can then use it for JavaScript, Liquid, and other syntaxes in the future (VBScript / C# anyone?)

**Comment by okachirski** [comment]
I like Monaco (it's used in VS Code and I've only good things to say while using it in web-based projects requiring script editing UI). You can use it for a variety of languages. 

[https://github.com/microsoft/monaco-editor](https://github.com/microsoft/monaco-editor)

**Comment by mostwired** [comment]
I like Monaco (it's used in VS Code and I've good things to say while using it in web-based projects requiring script editing UI). It can be used for a variety of languages.

[https://github.com/microsoft/monaco-editor](https://github.com/microsoft/monaco-editor)

**Comment by sfmskywalker** [comment]
Monaco looks great. Thanks for the tip!

**Comment by sfmskywalker** [comment]
Monaco is implemented. Example:

![designer-demo-4](https://user-images.githubusercontent.com/938393/110208891-f7538f80-7e89-11eb-90e7-cebfdb9da196.gif)
