### ISSUE TITLE
Elsa dashboard>instances>journal formatting is bad

### ISSUE THREAD

**Issue by MiroslavMikus** [elsa-workflows/elsa-core#1305]
Hey, I'm sorry to report a new issue again. :sweat_smile:

I'm running the latest docker image:
Repository: elsaworkflows/elsa-dashboard-and-server 
Image ID: f0dd3b6a4db1

![image](https://user-images.githubusercontent.com/29312172/126785452-5bb9c521-0346-40ab-ae0a-738855776d74.png)

I have a CRON timer for each minute. It is rendered like this in all instances.

**Comment by sfmskywalker** [comment]
I'm glad you did. Thanks! 😄

**Comment by MiroslavMikus** [comment]
@sfmskywalker you are the best! :heart_eyes:
