### ISSUE TITLE
Version Management

### ISSUE THREAD

**Issue by sfmskywalker** [elsa-workflows/elsa-core#1311]
Workflow definitions are versioned, which means that every time a new change is published, a new version is created.

User should be able to view past versions, roll back to them (into a new version) and permanently delete versions.

**Comment by tomy2105** [comment]
Another very useful (but tricky to implement) feature would be the ability to compare between versions.

**Comment by sfmskywalker** [comment]
@tomy2105  I love that. Could be done as a (big) improvement down the line.
