### ISSUE TITLE
TypeError: Cannot read property 'bind' of undefined

### ISSUE THREAD

**Issue by Juandavi1** [elsa-workflows/elsa-core#1313]
Hello,

Everything had been working fine but now I can't add new activities to a flow. On the server there are no exceptions, only on the front.

![Captura de pantalla de 2021-07-26 17-38-20](https://user-images.githubusercontent.com/18731612/127068062-81823d2c-af17-4507-b8ac-d8b7a1b3b5b0.png)

This happens with all activities.

We are working with version 2.2.0-preview.518

Thanks for the collaboration that you can give us.

**Comment by sfmskywalker** [comment]
Can you try and clear your browser cache?

**Comment by Juandavi1** [comment]
Hi, 

I've been trying and it was solved by removing the function that registers a plugin. https://github.com/elsa-workflows/elsa-core/discussions/1299

**Comment by sfmskywalker** [comment]
Great. Let me know if you need any further help.
