### ISSUE TITLE
New Feature: Activity Reflection-based Method Calls

### ISSUE THREAD

**Issue by Andale-online** [elsa-workflows/elsa-core#132]
Got it working already:

![image](https://user-images.githubusercontent.com/57248720/68209089-efa08400-ffd2-11e9-81a0-75bedb5426ae.png)

![image](https://user-images.githubusercontent.com/57248720/68209130-03e48100-ffd3-11e9-9268-ad041ae7e6a5.png)

![image](https://user-images.githubusercontent.com/57248720/68209261-41490e80-ffd3-11e9-8728-6ce36df17ed5.png)

Gonna put it in the PR...

Comments are wanted!

**Comment by Andale-online** [comment]
Sorry, step back. Gotta code the "non-static" class path - then it's done. :-D

**Comment by sfmskywalker** [comment]
Very cool. Maybe one thing to consider would be to change the "Input Variable Name" to be a workflow expression that provides the object to execute the method on? Then the user can specify not only a workflow variable, but also other activity's output.

**Comment by Andale-online** [comment]
Didn't know how :-D This was the most convenient way for me. This is upped to my fork in branch #123 
Maybe you can change it after merging?
Additionally i added an ObjectSplitter. It takes an object from variable and parses different properties of the object to Outcomes

**Comment by sfmskywalker** [comment]
Interesting stuff. Sure, send me a PR with your changes and we'll get it merged in.

**Comment by sfmskywalker** [comment]
@Andale-online I believe we can close this, yes?

**Comment by Andale-online** [comment]
Yup... Think so
