### ISSUE TITLE
Copy and paste activities

### ISSUE THREAD

**Issue by jwillmer** [elsa-workflows/elsa-core#1323]
As a user I like to copy and paste activities. I like to easily duplicate a activity node by copy&paste. I also like to copy a node in one workflow and past it to another.

- Use the user device clipboard to store a text representation of the node when executing the copy command.
- select a node by clicking on it (highlighting)
- copy and past should support CTRL+C and CTRL+V

**Comment by tomy2105** [comment]
Isn't this a duplicate of #792 also mentioned in #1100 epic?
Although I like the fact that this same functionality already has three tasks (there was also #393), which means it is definitely something needed :) :).

**Comment by jwillmer** [comment]
@tomy2105 sorry, didn't noticed the existing issue. we will close both as soon as it is implemented :)

**Comment by tomy2105** [comment]
No one will be happier than me when this happens @jwillmer.
And if @Axeleron007 has a will to tackle some of the other tasks enumerated in #1100, it will be Christmas coming in August :).

**Comment by sfmskywalker** [comment]
This feature has now been implemented, but has a problem that will be fixed via #1430
