### ISSUE TITLE
Expressions: Config access exposes vulnerability when working with user supplied expressions

### ISSUE THREAD

**Issue by josephdangerstewart** [elsa-workflows/elsa-core#1327]
Hello again 👋

**Project context**

We're building a user-facing workflow feature into our product and using Elsa as the execution engine. Thus, any workflow definitions and any expressions contained therein are user supplied and untrusted. The operations that the workflow engine can take on behalf of the user is strictly contained to just the actions they have permission to take in their group (we use a relatively straightforward group-based permission model).

**Vulnerability**

Because workflow definitions are user supplied and untrusted, the fact that [expressions can reference](https://elsa-workflows.github.io/elsa-core/docs/expressions/expressions-liquid#configuration) [.Net configuration](https://elsa-workflows.github.io/elsa-core/docs/expressions/expressions-javascript#getconfig) poses a security risk for us since .Net configuration tends to contain secrets (connection strings, auth headers, etc).

I've been able to disable config access in both javascript and liquid expressions but this was a surprising default to me. Exposing carte-blanche to .Net configuration by default seems dangerous. Although it could be that our use case for Elsa isn't aligning completely with what Elsa was designed for.

**Proposed Action Steps**

I have three ideas for how to improve this (ordered by preference)

1. My ideal solution is that this would be an opt-in feature. I'm sure there is a use case for this, although I wonder if it's ubiquitous enough to warrant the security risk in a context like this. Although I realize that would be a breaking change.
2. It would be nice if there were a convenient way to reliably disable this behavior (e.g. via [ElsaOptionsBuilder](https://github.com/elsa-workflows/elsa-core/blob/2ec915dabed9ffd03e9c9101e95a04f2438c1ed7/src/core/Elsa.Core/ElsaOptionsBuilder.cs#L18) - `elsa.DisableConfigurationAccess()` for instance).
3. At minimum, it would be nice to see better documentation on how to workaround it. My solution for JavaScript was relatively straightforward, following the [documentation here](https://elsa-workflows.github.io/elsa-core/docs/extensibility/extensibility-javascript), I was able to override the `getConfig` function to throw an `InvalidOperationException`. Disabling config access in Liquid took some digging. In order to know what type to override in the `MemberAccessStrategy`, I had to look at [the source code](https://github.com/elsa-workflows/elsa-core/blob/master/src/scripting/Elsa.Scripting.Liquid/Handlers/ConfigureLiquidEngine.cs#L61). Looking at source code isn't the end of the world, although it would be nice to have an officially recognized way to disable this behavior.

With my current familiarity with the project, I'd be willing to tackle any one of these approaches (although that first idea might be best saved for Elsa 3).

**Comment by sfmskywalker** [comment]
Makes perfect sense.

Option 1 would be best. By default. CLR access would be disabled, and all dangerous JS functions could be enabled by the developer on a case-by-case basis. For this we would introduce some form of `JavaScriptOptions` and `LiquidOptions` class to neatly scope the various settings.

If you want to provide a PR then that would be absolutely welcome. As far as I know, there's only one customer currently relying on the configuration access from their workflows. In any case, we'll announce the breaking change for whichever release this will be part of.

**Comment by josephdangerstewart** [comment]
> If you want to provide a PR then that would be absolutely welcome.

I'd be happy to!
