### ISSUE TITLE
Find BlockingActivityRemoved but not find BlockingActivityCreacted

### ISSUE THREAD

**Issue by Nokecy** [elsa-workflows/elsa-core#1330]

**Comment by sfmskywalker** [comment]
We can add that event. But out of curiosity, what do you need it for?

**Comment by Nokecy** [comment]
I want to create a WorkItem when the BlockingActivityCreacted event is triggered, and remove the WorkItem when BlockingActivityRemoved is triggered https://github.com/elsa-workflows/elsa-core/discussions/1329

**Comment by sfmskywalker** [comment]
That makes sense. Thanks for sending a PR!
