### ISSUE TITLE
[bug]: ReceiveMassTransitMessage does not work anymore

### ISSUE THREAD

**Issue by ckeller81** [elsa-workflows/elsa-core#1332]
The ReceiveMassTransitMessage activity does not work anymore. The MassTransit bus message is normally consumed, but the workflow itself is either silent (got this on the test-project) or displays the message 'Workflow <workflowid> cannot begin from an idle state (perhaps it needs a specific input)'.

I already got a fix for this, preparing the PR.

**Comment by sfmskywalker** [comment]
This was fixed with 42bcb03b80e26e22cad060ba72533bf044ceaf0ev. Thank you!
