### ISSUE TITLE
ActivityInputUIHints (MultiLine) doesn't save the value anyway.

### ISSUE THREAD

**Issue by Alhammoud** [elsa-workflows/elsa-core#1335]
when I used ActivityInputUIHints (MultiLine) element in attribute of inputs activity and then clicked on save button ,it didn't save the value anyway.

![image](https://user-images.githubusercontent.com/45689826/127654312-c741f2a6-addb-455e-a2e4-53e3b72eaf1d.png)

**Comment by sfmskywalker** [comment]
Sounds like this might be the same issue as #1343

**Comment by MiroslavMikus** [comment]
Hey Sipke :)
in issue #1343 is the value is clearly stored, just not visible or editable. @Alhammoud could you check if is the correct value in DB?

Thanks :)

**Comment by Alhammoud** [comment]
Yes, that's right  just not visible or editable. It was seved in DB.
Thanks 👍

**Comment by sfmskywalker** [comment]
What package version are you using? I just tried and I could not reproduce:

![Animation](https://user-images.githubusercontent.com/938393/128607831-7b6acd74-ee57-4c10-9848-8d607827dc01.gif)

**Comment by sfmskywalker** [comment]
I believe this has been fixed since I can not reproduce with latest package versions.
