### ISSUE TITLE
Elsa designer tree rendering error

### ISSUE THREAD

**Issue by GreenShadeZhang** [elsa-workflows/elsa-core#1339]
When I use the NPM package version number 2.1.14, I render Elsa designer tree separately, and an error occurs. The error prompt is typeerror: activitymodel.outcomes is not Iterable. Therefore, I think this is a bug. Please confirm that I render Elsa designer tree separately.

**Comment by sfmskywalker** [comment]
Hard to say what might be the cause of this issue. Can you provide a repro that I can try for myself?

**Comment by GreenShadeZhang** [comment]
Sorry, I found that it seems that my problem caused the rendering exception. I will close this problem later.
