### ISSUE TITLE
UI Dashboard does not show activity's Content field

### ISSUE THREAD

**Issue by MiroslavMikus** [elsa-workflows/elsa-core#1343]
Hey, I'm too lazy to explain so please check this:

![Elsa-Bug-20210802](https://user-images.githubusercontent.com/29312172/127873928-a322ef5e-c55b-45eb-a165-cef9088cffd5.gif)

I'm running this commit (6889b0cf38f463c4fe2206e4ec123fc2195eddf7) in docker.

**Comment by sfmskywalker** [comment]
A picture says more than a thousand words. An animated gif says it all 😄 
Does this happen consistently, or only sometimes?

**Comment by MiroslavMikus** [comment]
This issue is consistent -_- that gif was from the second run...

**Comment by sfmskywalker** [comment]
Perfect, then it’s fixable ;)

**Comment by sfmskywalker** [comment]
Wait, it looks like you're using an older version of the packages. Can you upgrade to the latest version and test again? I just tried and I could not reproduce:

![Animation](https://user-images.githubusercontent.com/938393/128607831-7b6acd74-ee57-4c10-9848-8d607827dc01.gif)

**Comment by MiroslavMikus** [comment]
Hey, I see at the first look :see_no_evil: , your gif has 4 tabs and mine only 3...

It looks like I was not able to set up the latest version correctly.

Maybe we could go through the docker setup together (commit 0222c20d7de71df4d76b2e008da0d6349d48dc1f in master):
## 1. I do always start at docker/README.md
``` ps
$ docker build -t elsadashboardwithserver:local -f ./docker/Dockerfile-with-npm .
$ docker run -t -i -e Elsa__Server__BaseAddress='http://localhost:6868' -e ASPNETCORE_ENVIRONMENT='Development' -p 6868:80 elsadashboard:latest
```
Ehm, I'm not sure, but it looks like we build **Dockerfile-with-npm** (btw which does not exist anymore), tag it with **elsadashboardwithserver:local**, and then start **elsadashboard:latest**. 

I would propose to update this file to:
``` ps
$ docker build -t elsadashboardwithserver:local -f ./docker/Dockerfile-elsa-dashboard-and-server.
$ docker run -t -i -e Elsa__Server__BaseAddress='http://localhost:6868' -e ASPNETCORE_ENVIRONMENT='Development' -p 6868:80 elsadashboardwithserver:local
```
If it makes sense for you as well.
## 2. docker/docker-compose.yml
This file points as well to the missing **Dockerfile-with-npm**

> Side note: Maybe it would be better to support only one default was to run the application in docker. Either docker run or docker-compose. If someone does not want to have smtp4dev running just enter ` docker compose up -d elsa-dashboard`. I personally would go for the **compose** way.

I would be more than happy if I could try to fix this in a new PR!

Now, it looks like you are using another test setup. Could you reveal your test flow/setup? 


Many thanks and sorry for the late response -_^

**Comment by sfmskywalker** [comment]
Good catch, we definitely need to update the README + docker-compose 😄 Thanks for reporting.

**Comment by sfmskywalker** [comment]
Done via d1b0465b0d76443c6e9192d4f9d09ff609e0f8a5

**Comment by MiroslavMikus** [comment]
Perfect, many thanks :)
