### ISSUE TITLE
Workflow faulted with An error occurred while attempting to establish an SSL or TLS connection

### ISSUE THREAD

**Issue by kekoke** [elsa-workflows/elsa-core#1345]
I created a document approval workflow by referring to the [document approval guide ](https://elsa-workflows.github.io/elsa-core/docs/next/guides/guides-document-approval )

When I use Postman created a request, I get the below error message. How can I fix it?
![image](https://user-images.githubusercontent.com/17831817/127951540-646cc803-77f2-45c2-8e54-69a9fbcb7d1f.png)

![image](https://user-images.githubusercontent.com/17831817/127950515-5a91bd58-31c9-4fb1-8f17-b0ac36c79915.png)

**Smtp configuration**
![image](https://user-images.githubusercontent.com/17831817/127951766-68635115-cded-455b-9998-091ed7adb6f5.png)

**Error message**
 `{
    "errorMessage": "Workflow faulted at 2021-08-03T03:12:50Z with error: An error occurred while attempting to establish an SSL or TLS connection.\r\n\r\nThis usually means that the SSL certificate presented by the server is not trusted by the system for one or more of\r\nthe following reasons:\r\n\r\n1. The server is using a self-signed certificate which cannot be verified.\r\n2. The local system is missing a Root or Intermediate certificate needed to verify the server's certificate.\r\n3. A Certificate Authority CRL server for one or more of the certificates in the chain is temporarily unavailable.\r\n4. The certificate presented by the server is expired or invalid.\r\n5. The set of SSL/TLS protocols supported by the client and server do not match.\r\n\r\nSee https://github.com/jstedfast/MailKit/blob/master/FAQ.md#SslHandshakeException for possible solutions.\r\n",
    "workflow": {
        "name": null,
        "version": 1,
        "instanceId": "01bab0010ca84b44aefef0fd105285c5"
    }
}`

Thank you for your help!

**Comment by sfmskywalker** [comment]
Hi @kekoke , it looks like your SMTP server requires SSL, which means you should configure the SMTP client to use the same.
Try the following appsettings section for SMTP:

```json
"Elsa": {
   "Smtp": {
      "Host": "zmt.???????.com",
      "Port": 25,
      "SecureSocketOptions": "StartTls" // OR try any of these: "None", "SslOnConnect" or "StartTlsWhenAvailable"
   }
}
```

See also [this SO post](https://stackoverflow.com/questions/55287641/im-getting-a-mailkit-security-sslhandshakeexception-when-trying-to-connect-to) for more information (Elsa uses the MailKit library for sending emails via SMTP).

**Comment by kekoke** [comment]
Hi @sfmskywalker , the following appsettings is work for me. Thank you so much -^-^. 

`"Elsa": {
   "Smtp": {
      "Host": "zmt.???????.com",
      "Port": 25,
      "SecureSocketOptions": "None" 
   }
}`
