### ISSUE TITLE
Re-run failed activity

### ISSUE THREAD

**Issue by Rafael94** [elsa-workflows/elsa-core#1348]
Hi,

I would like to manually re-run a failed activity and thus continue the workflow.

Example:

I have a workflow with multiple activities. For example, one activity could be to create a folder. This activity fails due to missing permissions. After the permissions are adjusted, I would like to re-run this activity and continue the workflow with it.

Does this option already exist?

**Comment by sfmskywalker** [comment]
Yes, take a look at the [Retry API endpoint](https://github.com/elsa-workflows/elsa-core/blob/master/src/server/Elsa.Server.Api/Endpoints/WorkflowInstances/Retry.cs).

It uses the `IWorkflowReviver` service to simply retry a given workflow instance.

**Comment by Rafael94** [comment]
Thank you. Just tested and it worked. 

But I just noticed that in `WorkflowExecutionLogRecord` the error message is not saved.  The error message would make sense to me because I am displaying the activities to the user.

Then it would say `CreateFolder`" twice even though it is only one activity. I would like to show the user that it failed the first time.

Is the error message stored in the activity or would it be a feature request?

**Comment by sfmskywalker** [comment]
@Rafael94 Awesome. There are some missing pieces it seems when it comes to logging workflow errors on both the workflow level and the activity execution log level. The error message should be stored in the workflow execution log for the activity as well as on the workflow instance itself.

**Comment by Rafael94** [comment]
I have found the mistake. `Exception` is saved, but not `Fault(Error)`

https://github.com/elsa-workflows/elsa-core/issues/1349#issuecomment-894969026
