### ISSUE TITLE
Save activity status in WorkflowExecutionLogRecord

### ISSUE THREAD

**Issue by Rafael94** [elsa-workflows/elsa-core#1349]
Hi,

Would it be possible to store the status of an activity in WorkflowExecutionLogRecord? I would like to filter out activities that are responsible for stopping a workflow. For example `UserTask`.

I would like to show the user a list of completed activities and activities that are blocking the workflow (suspend).

I have a worklfow with a fork because the `UserTask` take place in parallel. The join at the end waits for all `UserTask`. But in my list they are shown as running, although the workflow is currently blocked by them. I could search in Data for `{"Outcomes": [ "Done"]}`, I just don't find that quite as nice.

I could imagine the following statuses.
- Done
- Failed
- Suspend

With `Failed` you could also save the error message.

**Comment by sfmskywalker** [comment]
I think you might be able to use the `EventName` field for this if we make a change such that instead of recording "Executed" when an activity suspends the workflow, it is recorded as "Suspended".

* Done equals Executed
* Failed equals Faulted
* Suspend would then equal Suspended

**Comment by Rafael94** [comment]
That would also be a possibility. With Failed the error should still be stored.

**Comment by sfmskywalker** [comment]
I see. I'm not sure it's a good idea to keep the workflow running when an activity faults. But what might be a good idea is to have a "compensating" mode where each activity on the workflow gets a chance to roll back (or send a notification) upon a fault condition.

**Comment by Rafael94** [comment]
My problem is that on `return Fault("Error")` the error `"Error"` is not saved.

For example:

There is an activity to create a backup. If it fails, I `return Fault("Server unavailable")` to send an email notification afterwards. But the error `"Server not available"` is not saved.

But if I call `throw new Exception("Server not reachable")`, the error is saved, but I can't send a notification (next activity) anymore.

In the best case both activities can be executed again.  The only difference is that on `return Fault` the workflow continues.

It would be even better if it happens automatically. An attribute could be used to control that it should be retried after X hours.

**Comment by sfmskywalker** [comment]
The current best practice for Elsa 2 is to have your activity return an "Error" or "Fault" etc. outcome. Then from the workflow designer you can choose how to handle this outcome, e.g. by sending a notification and then trying the activity again (by connecting back into it).

Would this work for your scenario?
