### ISSUE TITLE
Should connections be hooked up with case-insensitivity?

### ISSUE THREAD

**Issue by jamesdoran** [elsa-workflows/elsa-core#135]
This might be by design, but just asking the question. When `OutcomeResult.ScheduleNextActivities` looks for the next connection based on the previous endpoint's outcome, it's done so case-sensitively. Do you think it's worth making this case-insensitive, especially for user tasks? Change implemented below if you think this is a good idea.

```
private void ScheduleNextActivities(WorkflowExecutionContext workflowContext, SourceEndpoint endpoint)
{
    var completedActivity = workflowContext.CurrentActivity;
    var connections = workflowContext.Workflow.Connections.Where(x => x.Source.Activity == completedActivity && 
                                                                        (x.Source.Outcome ?? OutcomeNames.Done).Equals(endpoint.Outcome, StringComparison.OrdinalIgnoreCase));
    var activities = connections.Select(x => x.Target.Activity);
    
    workflowContext.ScheduleActivities(activities);
}
```

**Comment by sfmskywalker** [comment]
I see no reason the comparison needs to be case-sensitive, so I agree with your change.
