### ISSUE TITLE
UI Designer - activity context menu placement is off while using a different site template

### ISSUE THREAD

**Issue by matt4446** [elsa-workflows/elsa-core#1358]
The bug that has been present since the new designer came in (it's not that annoying really, but sometimes out of view on larger workflows): 

![image](https://user-images.githubusercontent.com/1550939/128482228-8a318320-69f5-4be9-8a06-e518d21792be.png)

The offset is the width of the sidebar and the height header plus or minus some padding in the main content area. 

Delete the sidebar and:
![image](https://user-images.githubusercontent.com/1550939/128482522-e523f3d5-1db9-44b8-be2e-2a8eeda6350b.png)
etc... 

As of 2.2 the structure of the app now looks like (since 2.2) and prior to that it didn't have the elsa-studio-root element with everything just as below (in shorthand):
```
<elsa-studio-root flex-row>
   <div.sidebar screen-height>
   </div.sidebar> 
   <div.main screen-height flex-grow flex-col>
      <div.header />
      <div.content> 
            <div.titlesAndDoodads /> 
         ... designer components/viewer etc 
             <elsa-workflow-definition-editor-screen workflow-definition-id="@WorkflowDefinitionId" monaco-lib-path="/_content/Elsa.Designer.Components.Web/monaco-editor/min" />

      </div.content>
   </div.main>
</elsa-studio-root> 
```

**Comment by sfmskywalker** [comment]
@matt4446 Should be good now. If not, let us know. /cc @simona-taran
