### ISSUE TITLE
New feature: Add "else" case to switch

### ISSUE THREAD

**Issue by Andale-online** [elsa-workflows/elsa-core#136]
I upped it in my fork.

There's now an option with value "!unknown!" which is used for all values the switch could not match from expression to cases. Maybe we should use an other value or option to set this, because !unknown! looks ugly, but i didnt want to block the keyword "else".
Any ideas?

**Comment by sfmskywalker** [comment]
Sounds like a good addition. Can you please create a PR from your fork? That will make it easier for me to look at your changes and to comment on specific code. Thanks!

**Comment by Andale-online** [comment]
PR opened

**Comment by sfmskywalker** [comment]
Great! I'm thinking we might use the word `"default"` - it's used in C# and in JavaScript, so makes sense? 🤷‍♂

**Comment by Andale-online** [comment]
Switched to "default".
