### ISSUE TITLE
Dashboard editor intelisense & more

### ISSUE THREAD

**Issue by MiroslavMikus** [elsa-workflows/elsa-core#1368]
Hey, I have in some issue seen a request for some kind of intelligence for the javascript syntax. I can't find that issue anymore, maybe it's already closed -_- 

Anyways I would like to add to the *missing* issue:
Do you like [Monaco](https://github.com/Microsoft/monaco-editor)? It would be really amazing to see it in the dashboard 😄

**Comment by sfmskywalker** [comment]
Perhaps I misunderstood entirely, but we already use Monaco Editor with intellisense for JavaScript in the workflow designer:

![](https://miro.medium.com/max/700/1*cE8nFKCRE25NDfEe5CGCgA.gif)

Or were you referring to something else?

**Comment by MiroslavMikus** [comment]
🙈  ou, I did somehow miss this. It's exactly what I'm talking about! I guess that issue, that I was talking about is already implemented and closed 😄 

I'm closing this issue, and many thanks @sfmskywalker 🙏

**Comment by sfmskywalker** [comment]
It might be related to the other issue where your docker image is not the latest one.
