### ISSUE TITLE
Retry a failed activity / workflow

### ISSUE THREAD

**Issue by robpop78** [elsa-workflows/elsa-core#1385]
I'm keen on using elsa in a commercial context, but in order to justify replacing our existing workflow software, we need the ability to re-run failed activities / workflows. Are you planning to add this functionality?
Thanks

**Comment by Rafael94** [comment]
The function already exists. I asked the same thing last week. :)

#1348

**Comment by sfmskywalker** [comment]
@robpop78 Closing this as duplicate, but please feel free to continue in the issue referenced by @Rafael94 . Thank you.

**Comment by robpop78** [comment]
Excellent! Thank you
