### ISSUE TITLE
The call is ambiguous and matches multiple workflows.

### ISSUE THREAD

**Issue by rairafaqatali** [elsa-workflows/elsa-core#1392]
Hi,
I have created a simple workflow by using the designer, when I try to publish more than once and then try to execute it throws "the call is ambiguous and matches multiple workflows" Here are concreate steps:

1. I have added Elsa package 2.2.1, I have tried with 2.2.0 but got no luck
2. The Workflow JSON is
{
  "$id": "1",
  "definitionId": "3533ba793d36447eb5d5748d34f4eb5a",
  "versionId": "3abae36de6984e8dbe94762c542e57fa",
  "version": 4,
  "variables": {
    "$id": "2",
    "data": {}
  },
  "customAttributes": {
    "$id": "3",
    "data": {}
  },
  "isSingleton": false,
  "persistenceBehavior": "WorkflowBurst",
  "deleteCompletedInstances": false,
  "isPublished": true,
  "isLatest": true,
  "activities": [
    {
      "$id": "4",
      "activityId": "0d817b13-78e5-46f3-b9d3-ad6735420e4e",
      "type": "HttpEndpoint",
      "displayName": "HTTP Endpoint",
      "persistWorkflow": false,
      "loadWorkflowContext": false,
      "saveWorkflowContext": false,
      "properties": [
        {
          "$id": "5",
          "name": "Path",
          "expressions": {
            "$id": "6",
            "Literal": "/read"
          }
        },
        {
          "$id": "7",
          "name": "Methods",
          "expressions": {
            "$id": "8",
            "Json": "[\"POST\"]"
          }
        },
        {
          "$id": "9",
          "name": "ReadContent",
          "expressions": {
            "$id": "10",
            "Literal": "true"
          }
        },
        {
          "$id": "11",
          "name": "TargetType",
          "expressions": {
            "$id": "12"
          }
        }
      ],
      "propertyStorageProviders": {}
    },
    {
      "$id": "13",
      "activityId": "13dc393b-d599-4080-b251-78d5fbcf3791",
      "type": "WriteHttpResponse",
      "displayName": "HTTP Response",
      "persistWorkflow": false,
      "loadWorkflowContext": false,
      "saveWorkflowContext": false,
      "properties": [
        {
          "$id": "14",
          "name": "Content",
          "syntax": "JavaScript",
          "expressions": {
            "$id": "15",
            "JavaScript": "input.body;"
          }
        },
        {
          "$id": "16",
          "name": "ContentType",
          "expressions": {
            "$id": "17",
            "Literal": "application/json"
          }
        },
        {
          "$id": "18",
          "name": "StatusCode",
          "expressions": {
            "$id": "19"
          }
        },
        {
          "$id": "20",
          "name": "CharSet",
          "expressions": {
            "$id": "21"
          }
        },
        {
          "$id": "22",
          "name": "ResponseHeaders",
          "expressions": {
            "$id": "23"
          }
        }
      ],
      "propertyStorageProviders": {}
    }
  ],
  "connections": [
    {
      "$id": "24",
      "sourceActivityId": "0d817b13-78e5-46f3-b9d3-ad6735420e4e",
      "targetActivityId": "13dc393b-d599-4080-b251-78d5fbcf3791",
      "outcome": "Done"
    }
  ],
  "id": "3abae36de6984e8dbe94762c542e57fa"
}

kindly help me,
Thanks

**Comment by sfmskywalker** [comment]
Hi @rairafaqatali , this issue has been fixed as of version 2.3.0-preview.23 (and higher; it's published on MyGet, which may show only newer versions due to a retention policy).

When you update your packages to this prerelease and to make sure the issue goes away for you, please update the `WorkflowDefinitions` database table or collection by making sure there are no workflow definitions with the same ID with `IsPublished = true` - there can only be one workflow definition that is published (within a versioned set of a given workflow definition ID).

See #1293 for more information.
