### ISSUE TITLE
Custom Http End Point Activity not Triggering

### ISSUE THREAD

**Issue by rairafaqatali** [elsa-workflows/elsa-core#1393]
Hi,
I have written a custom activity endpoint. here is the code:
`using System;
using System.Collections.Generic;
using Elsa;
using Elsa.Activities.Http;
using Elsa.Activities.Http.Models;
using Elsa.Activities.Http.Providers.DefaultValues;
using Elsa.Activities.Http.Services;
using Elsa.ActivityResults;
using Elsa.Attributes;
using Elsa.Design;
using Elsa.Expressions;
using Elsa.Services;
using Elsa.Services.Models;
using Microsoft.AspNetCore.Http;

namespace Workflow.Activities
{
    [Trigger(
        Category = "Extended",
         DisplayName = "Receive HTTP Request",
        Description = "Receive an incoming HTTP request.",
        Outcomes = new[] { OutcomeNames.Done }
    )]
    public class ExtendedHttpEndPoint : HttpEndpoint
    {
        /// <summary>
        /// The path that triggers this activity. 
        /// </summary>
        [ActivityInput(Hint = "The relative path that triggers this activity.", SupportedSyntaxes = new[] { SyntaxNames.JavaScript, SyntaxNames.Liquid })]
        public PathString Path { get; set; }

        /// <summary>
        /// The HTTP methods that triggers this activity.
        /// </summary>
        [ActivityInput(
            UIHint = ActivityInputUIHints.CheckList,
            Hint = "The HTTP methods that trigger this activity.",
            Options = new[] { "GET", "POST", "PUT", "DELETE", "PATCH", "OPTIONS", "HEAD" },
            DefaultValueProvider = typeof(HttpEndpointDefaultMethodsProvider),
            DefaultSyntax = SyntaxNames.Json,
            SupportedSyntaxes = new[] { SyntaxNames.Json, SyntaxNames.JavaScript, SyntaxNames.Liquid })]

        public HashSet<string> Methods { get; set; } = new HashSet<string> { "GET" };

        /// <summary>
        /// A value indicating whether the HTTP request content body should be read and stored as part of the HTTP request model.
        /// The stored format depends on the content-type header.
        /// </summary>
        [ActivityInput(
            Hint = "A value indicating whether the HTTP request content body should be read and stored as part of the HTTP request model. The stored format depends on the content-type header.",
            SupportedSyntaxes = new[] { SyntaxNames.Literal, SyntaxNames.JavaScript, SyntaxNames.Liquid })]
        public bool ReadContent { get; set; }

        /// <summary>
        /// The <see cref="Type"/> to parse the received request content into if <seealso cref="ReadContent"/> is set to true.
        /// If not set, the content will be parse into a default type, depending on the parser associated with the received content-type header.
        /// </summary>
        [ActivityInput(Category = PropertyCategories.Advanced)]
        public Type? TargetType { get; set; }

        [ActivityInput(
            Hint = "Check to allow authenticated requests only",
            SupportedSyntaxes = new[] { SyntaxNames.Literal, SyntaxNames.JavaScript, SyntaxNames.Liquid },
            Category = "Security"
        )]
        public bool Authorize { get; set; }

        [ActivityInput(
            Hint = "Provide a policy to evaluate. If the policy fails, the request is forbidden.",
            SupportedSyntaxes = new[] { SyntaxNames.Literal, SyntaxNames.JavaScript, SyntaxNames.Liquid },
            Category = "Security"
        )]
        public string? Policy { get; set; }

        [ActivityOutput(Hint = "The received HTTP request.")]
        public HttpRequestModel? Output { get; set; }

        protected override IActivityExecutionResult OnExecute(ActivityExecutionContext context) => context.WorkflowExecutionContext.IsFirstPass ? ExecuteInternal(context) : Suspend();
        protected override IActivityExecutionResult OnResume(ActivityExecutionContext context) => ExecuteInternal(context);

        private IActivityExecutionResult ExecuteInternal(ActivityExecutionContext context)
        {
            Output = context.GetInput<HttpRequestModel>();
            return Done();
        }
    }
}
`
I have created the bookmark like below code:
`using Elsa.Activities.Http.Bookmarks;
using Elsa.Services;
using Microsoft.AspNetCore.Http;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;
using Workflow.Activities;

namespace Workflow.Bookmarks
{
    public class ExtendedHttpEndPointBookmarkProvider : BookmarkProvider<HttpEndpointBookmark>
    {
        public override bool SupportsActivity(BookmarkProviderContext context) => context.ActivityType.TypeName == nameof(ExtendedHttpEndPoint);
        public override async ValueTask<IEnumerable<BookmarkResult>> GetBookmarksAsync(BookmarkProviderContext context, CancellationToken cancellationToken)
        {
            var path = await context.ReadActivityPropertyAsync<ExtendedHttpEndPoint, PathString>(x => x.Path, cancellationToken);
            var methods = (await context.ReadActivityPropertyAsync<ExtendedHttpEndPoint, HashSet<string>>(x => x.Methods, cancellationToken))?.Select(ToLower) ?? Enumerable.Empty<string>();

            BookmarkResult CreateBookmark(string method) => Result(new(path, method), nameof(ExtendedHttpEndPoint));
            return methods.Select(CreateBookmark);
        }

        private static string ToLower(string s) => s.ToLowerInvariant();
    }
}
`
in my startup.cs file, I have registered the bookmark and activity like below:
`
using Elsa.Persistence.EntityFramework.Core.Extensions;
using Elsa.Persistence.EntityFramework.SqlServer;
using Microsoft.AspNetCore.Builder;
using Microsoft.AspNetCore.Hosting;
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.Hosting;
using Elsa;
using Workflow.Activities;
using Workflow.Bookmarks;

namespace Workflow
{
    public class Startup
    {
        public Startup(IConfiguration configuration)
        {
            Configuration = configuration;
        }

        public IConfiguration Configuration { get; }
        public void ConfigureServices(IServiceCollection services)
        {
            var elsaSection = Configuration.GetSection("Elsa");
            services
                .AddElsa(elsa => elsa
                    .UseEntityFrameworkPersistence(ef => ef.UseSqlServer(Configuration.GetSection("ConnectionStrings:SqlServerConnectionString").Value), true)
                    .AddConsoleActivities()
                    .AddHttpActivities(elsaSection.GetSection("Server").Bind)
                    .AddQuartzTemporalActivities()
                    .AddJavaScriptActivities()
                    .AddJavaScriptActivities()
                    .AddActivity<ExtendedHttpEndPoint>()
                );

            services.AddElsaApiEndpoints();
            services.AddControllers();
            services.AddRazorPages();
            services.AddBookmarkProvider<ExtendedHttpEndPointBookmarkProvider>();
        }
        public void Configure(IApplicationBuilder app, IWebHostEnvironment env)
        {
            if (env.IsDevelopment())
            {
                app.UseDeveloperExceptionPage();
            }
            app.UseHttpActivities();
            app.UseStaticFiles();
            app.UseRouting();

            app.UseAuthorization();

            app.UseEndpoints(endpoints =>
            {
                endpoints.MapControllers();
                endpoints.MapFallbackToPage("/_Host");
            });
        }
    }
}

`

The custom activity is visible in designer, I have created the workflow below is it's json:
{
  "$id": "1",
  "definitionId": "a5dc1a352ee849a5b8ed47bf3f919827",
  "versionId": "b8b4a1263b42452a97b461180dc09f79",
  "version": 1,
  "variables": {
    "$id": "2",
    "data": {}
  },
  "customAttributes": {
    "$id": "3",
    "data": {}
  },
  "isSingleton": false,
  "persistenceBehavior": "WorkflowBurst",
  "deleteCompletedInstances": false,
  "isPublished": true,
  "isLatest": true,
  "activities": [
    {
      "$id": "4",
      "activityId": "61ea7d09-8ad1-42e6-a27c-a376e479ea70",
      "type": "ExtendedHttpEndPoint",
      "displayName": "Receive HTTP Request",
      "persistWorkflow": false,
      "loadWorkflowContext": false,
      "saveWorkflowContext": false,
      "properties": [
        {
          "$id": "5",
          "name": "Path",
          "expressions": {
            "$id": "6",
            "Literal": "/feed"
          }
        },
        {
          "$id": "7",
          "name": "Methods",
          "expressions": {
            "$id": "8",
            "Json": "[\"POST\"]"
          }
        },
        {
          "$id": "9",
          "name": "ReadContent",
          "expressions": {
            "$id": "10",
            "Literal": "true"
          }
        },
        {
          "$id": "11",
          "name": "TargetType",
          "expressions": {
            "$id": "12"
          }
        },
        {
          "$id": "13",
          "name": "Authorize",
          "expressions": {
            "$id": "14"
          }
        },
        {
          "$id": "15",
          "name": "Policy",
          "expressions": {
            "$id": "16"
          }
        }
      ],
      "propertyStorageProviders": {}
    },
    {
      "$id": "17",
      "activityId": "66784483-ea96-44c6-84c1-7d12aaaf50d7",
      "type": "WriteHttpResponse",
      "displayName": "HTTP Response",
      "persistWorkflow": false,
      "loadWorkflowContext": false,
      "saveWorkflowContext": false,
      "properties": [
        {
          "$id": "18",
          "name": "Content",
          "expressions": {
            "$id": "19",
            "Literal": "test"
          }
        },
        {
          "$id": "20",
          "name": "ContentType",
          "expressions": {
            "$id": "21"
          }
        },
        {
          "$id": "22",
          "name": "StatusCode",
          "expressions": {
            "$id": "23"
          }
        },
        {
          "$id": "24",
          "name": "CharSet",
          "expressions": {
            "$id": "25"
          }
        },
        {
          "$id": "26",
          "name": "ResponseHeaders",
          "expressions": {
            "$id": "27"
          }
        }
      ],
      "propertyStorageProviders": {}
    }
  ],
  "connections": [
    {
      "$id": "28",
      "sourceActivityId": "61ea7d09-8ad1-42e6-a27c-a376e479ea70",
      "targetActivityId": "66784483-ea96-44c6-84c1-7d12aaaf50d7",
      "outcome": "Done"
    }
  ],
  "id": "b8b4a1263b42452a97b461180dc09f79"
}

When I try to hit this workflow from the postman, I got 400 Bad Request error: here is my postman request:
URL: http://localhost:7492/feed
MethodType: Post
Body: in json format
{
"test":"hello"
}

Kindly let me know what I'm missing
Thanks

**Comment by sfmskywalker** [comment]
Can you please do something about the code snippets? It's a bit hard to read as it is right now. In any case, you may want to try out @tomy2105 's sample here: https://github.com/elsa-workflows/elsa-core/discussions/1249#discussioncomment-1153591

**Comment by rairafaqatali** [comment]
@sfmskywalker  Thanks, issue fixed
