### ISSUE TITLE
Question: Does Elsa support multi-tenancy ?

### ISSUE THREAD

**Issue by iyhammad** [elsa-workflows/elsa-core#140]
I would like to ask, does Elsa support multi-tenancy ? If yes, what's the best way to do this ?

**Comment by sfmskywalker** [comment]
For sure, but Elsa itself does not provide anything to that end. Instead, it would be up to your application hosting the workflow runtime to provide a multi-tenant workflow definition and workflow instance store.

For example, if you were to use Orchard Core Framework to build a multi-tenant solution, Elsa would automatically be multi-tenant de to the fact that the service container itself would be tenant-specific.

If you would use ABP framework, the principle would probably be similar.

And of course you could implement your own multi-tenant data store.

Hope this helps.

**Comment by iyhammad** [comment]
Thank You. I'm planning to start using it in few days.

**Comment by Andale-online** [comment]
Hey... Found a simple way: if you e.g. use mongodb you could change connection strings to the representative bucket for the tenant... Just an idea. You just need some logic on the dashboard side to look up the right basket.
