### ISSUE TITLE
Copying an editor's value causes a copy of an activity instead

### ISSUE THREAD

**Issue by matt4446** [elsa-workflows/elsa-core#1411]
in preview 61:

![image](https://user-images.githubusercontent.com/1550939/130244400-78d16d0f-d5e0-46af-8759-fe01c241be68.png)
> you can see the notification in the top right

If i copy "get-access" it will give me the value : `{}`

**Comment by matt4446** [comment]
Pasting in an editor works but i have a feeling its trying to do more: 

![image](https://user-images.githubusercontent.com/1550939/130245326-33a4324b-5c8c-49e2-8612-c6936a6d7952.png)

**Comment by sfmskywalker** [comment]
This issue has been partially fixed. The real fix will be done via #1430.
