### ISSUE TITLE
Error when trying to put activity output as an next activity input

### ISSUE THREAD

**Issue by szubartm** [elsa-workflows/elsa-core#1419]
Hi,
I ran into issue, when I try to put activity output as an activity input in next activity. Getting this error => :
![elsaError](https://user-images.githubusercontent.com/34095065/130430867-9e447eeb-8aff-46ad-a4d9-20c805a6819b.PNG)

And there is no error showed in viewer, just workflow is not reaching next activity =>
![elsaWorkflowError](https://user-images.githubusercontent.com/34095065/130431469-d8c3fc9f-73a6-4ed3-b3cb-5da3ca128e8a.PNG)

I found similar error here: [https://github.com/elsa-workflows/elsa-core/issues/1381](url), but workflows are slightly different;

I'm using JS syntax like this:
![checpriceError](https://user-images.githubusercontent.com/34095065/130432088-f9da8ad7-0bab-40d1-ba1c-0a9b824eb62a.png)

Error occurs even if as input I try to pass int or string with JavaScript syntax.

Is it a bug, or am I just doing something wrong?

My source code =>
[ElsaQuickstarts-Server-DashboardAndServer.zip](https://github.com/elsa-workflows/elsa-core/files/7031034/ElsaQuickstarts-Server-DashboardAndServer.zip)

**Comment by rairafaqatali** [comment]
@szubartm 
try activities.GetDocument.Document()

Read Activity Output (Elsa 2.1) from [https://elsa-workflows.github.io/elsa-core/docs/expressions/expressions-javascript](url)

**Comment by szubartm** [comment]
Hi @rairafaqatali  

Syntax looks like you said:
![checpriceError](https://user-images.githubusercontent.com/34095065/130440991-1db16cdc-92f7-439e-948e-09a31962998a.png)

But it is still not working =>

![elsa2](https://user-images.githubusercontent.com/34095065/130441237-805ad541-5cad-469b-af6d-072d8eb59147.PNG)

**Comment by sfmskywalker** [comment]
@szubartm Make sure that there is an activity named `GetDocument`. Note: you are expected to provide a `Name` value that you reference, not to be confused with the **activity type name**.

For example, if you have an activity on your workflow of type `GetDocument`, and you want to access its output, you need to give this activity a name. For example, `GetDocument1`. Then your JS expression becomes:

```javascript
activities.GetDocument1.Document()
```

**Comment by szubartm** [comment]
@sfmskywalker Thank you a lot! It is working now. I'm closing the topic 👍

**Comment by sfmskywalker** [comment]
Great! I will work on improving the error message to make it clearer next time it happens when an activity is being referenced that doesn't exist.
