### ISSUE TITLE
Create Dockerfile for Dashboard

### ISSUE THREAD

**Issue by sfmskywalker** [elsa-workflows/elsa-core#142]
The Dockerfile should build an image that launches Elsa Dashboard.
Then a docker-compose file should run this image + mongodb.

**Comment by Andale-online** [comment]
If you have the compose files I'll make you some helm chart if you like.
One thing: please don't include mongodb or tag one without mongodb. My DevOps will go nuts with mixed systems. (Scalability)

**Comment by sfmskywalker** [comment]
That would be great! Noted about the mixing of services. Perhaps what I’ll do is provide a couple of compose files containing various “recipes”. E.g. one without any persistence, another with EF Core and another with MongoDB. Main purpose of these docket compose files are for people to have a quick start to see how things might work for them. I reckon most folks will maintain their own compose files.
