### ISSUE TITLE
How to schedule a job from designer?

### ISSUE THREAD

**Issue by rairafaqatali** [elsa-workflows/elsa-core#1424]
@sfmskywalker 
I need to schedule a job that will run at a specific time/cron. I have not found any option. I tried by following but got no luck.
I have created a workflow in which cron is included, when I run this workflow, it's not executed on a cron expression. Here is my workflow
{
  "$id": "1",
  "definitionId": "16578058d03b4f748cba4036460f4a72",
  "versionId": "4f8e4debe8fa4a44b07b63079e633222",
  "name": "Google Trends Full Load Workflow",
  "displayName": "Google Trends Full Load Workflow",
  "description": "Google Trends Full Load Workflow",
  "version": 1,
  "variables": {
    "$id": "2",
    "data": {}
  },
  "customAttributes": {
    "$id": "3",
    "data": {}
  },
  "isSingleton": false,
  "persistenceBehavior": "Suspended",
  "deleteCompletedInstances": false,
  "isPublished": true,
  "isLatest": true,
  "activities": [
    {
      "$id": "4",
      "activityId": "435a3c04-53af-407a-ba2c-3e3c30f2d7c9",
      "type": "ExtendedHttpEndPoint",
      "name": "ExtendedHttpEndpoint",
      "displayName": "Receive HTTP Request",
      "persistWorkflow": false,
      "loadWorkflowContext": false,
      "saveWorkflowContext": false,
      "properties": [
        {
          "$id": "5",
          "name": "Path",
          "expressions": {
            "$id": "6",
            "Literal": "/hello"
          }
        },
        {
          "$id": "7",
          "name": "Methods",
          "expressions": {
            "$id": "8",
            "Json": "[\"GET\"]"
          }
        },
        {
          "$id": "9",
          "name": "ReadContent",
          "expressions": {
            "$id": "10",
            "Literal": "true"
          }
        },
        {
          "$id": "11",
          "name": "TargetType",
          "expressions": {
            "$id": "12"
          }
        }
      ],
      "propertyStorageProviders": {}
    },
    {
      "$id": "13",
      "activityId": "8236a462-2bc5-4670-9970-a5c7d8572fbb",
      "type": "Cron",
      "displayName": "Cron",
      "persistWorkflow": false,
      "loadWorkflowContext": false,
      "saveWorkflowContext": false,
      "properties": [
        {
          "$id": "14",
          "name": "CronExpression",
          "expressions": {
            "$id": "15",
            "Literal": "0 * * ? * *"
          }
        }
      ],
      "propertyStorageProviders": {}
    },
    {
      "$id": "16",
      "activityId": "83b340ab-ce07-4140-8906-76be6eddf6d2",
      "type": "WriteLine",
      "displayName": "Write Line",
      "persistWorkflow": false,
      "loadWorkflowContext": false,
      "saveWorkflowContext": false,
      "properties": [
        {
          "$id": "17",
          "name": "Text",
          "expressions": {
            "$id": "18",
            "Literal": "Hello World"
          }
        }
      ],
      "propertyStorageProviders": {}
    },
    {
      "$id": "19",
      "activityId": "651ddd06-8e54-4ff1-8dfe-ae4bdfc86850",
      "type": "WriteHttpResponse",
      "displayName": "HTTP Response",
      "persistWorkflow": false,
      "loadWorkflowContext": false,
      "saveWorkflowContext": false,
      "properties": [
        {
          "$id": "20",
          "name": "Content",
          "expressions": {
            "$id": "21",
            "Literal": "test"
          }
        },
        {
          "$id": "22",
          "name": "ContentType",
          "expressions": {
            "$id": "23"
          }
        },
        {
          "$id": "24",
          "name": "StatusCode",
          "expressions": {
            "$id": "25"
          }
        },
        {
          "$id": "26",
          "name": "CharSet",
          "expressions": {
            "$id": "27"
          }
        },
        {
          "$id": "28",
          "name": "ResponseHeaders",
          "expressions": {
            "$id": "29"
          }
        }
      ],
      "propertyStorageProviders": {}
    }
  ],
  "connections": [
    {
      "$id": "30",
      "sourceActivityId": "435a3c04-53af-407a-ba2c-3e3c30f2d7c9",
      "targetActivityId": "8236a462-2bc5-4670-9970-a5c7d8572fbb",
      "outcome": "Done"
    },
    {
      "$id": "31",
      "sourceActivityId": "8236a462-2bc5-4670-9970-a5c7d8572fbb",
      "targetActivityId": "83b340ab-ce07-4140-8906-76be6eddf6d2",
      "outcome": "Done"
    },
    {
      "$id": "32",
      "sourceActivityId": "83b340ab-ce07-4140-8906-76be6eddf6d2",
      "targetActivityId": "651ddd06-8e54-4ff1-8dfe-ae4bdfc86850",
      "outcome": "Done"
    }
  ],
  "id": "4f8e4debe8fa4a44b07b63079e633222"
}

Kindly let me know, How can I schedule workflow using designer?
Thanks

**Comment by sfmskywalker** [comment]
I just tried but the cron works fine for me.

However I had to do two things:

1. Replace your extended HTTP endpoint activity with a regular HTTP endpoint activity, since I do not have your custom activity on my machine. This however should not affect my test in any meaningful way.
2. Remove the HTTP Response activity because that will fail when executed from a background task. 

Due to the way the CRON activity is implemented, it resumes the workflow from a background task. At that time, there will be no HTTP context available, which means you cannot write a response back at that time.

If you really need to be able to wait for a CRON schedule before completing the HTTP request, you could consider implementing a custom activity from where you compute the desired delay using a CRON expression, then use `Task.Wait`. 

In any case, the CRON works as expected so I will close this issue. Feel free to reopen if you can send me a (clean) project demonstrating the issue with the latest Elsa 2.3 prerelease packages.
