### ISSUE TITLE
Oracle - ElsaContext EF: modelBuilder.Model.MaxIdentifierLength does not shorten the identifier

### ISSUE THREAD

**Issue by megamanhxh** [elsa-workflows/elsa-core#1426]
#  Origin Issue
By using Oracle 11g database, the limitation is known that it cannot support any identifier that has more than 30 characters. In EntityFrameworkCore, by using Oracle.EntityFrameworkCore, you can fulfill this requirement by following: 
https://docs.oracle.com/en/database/oracle/oracle-data-access-components/19.3/odpnt/EFCoreAPI.html#GUID-22C75E2E-4A17-46CB-82EE-6AE2303F9EEA

The issue happened because one of the issues of IdentityContexts requires to be extended and setup the following in order to be able to use it for Oracle 11g database.

```csharp
.AddConfigurationStore<IdentityConfigurationDbContext>(options =>
{
    options.ConfigureDbContext = builder => builder.UseOracle(
        connectionString,
        sql =>
        {
            sql.MigrationsAssembly(migrationsAssembly);
            sql.UseOracleSQLCompatibility("11");
        }
    );
})
```

And EntityFrameworkCore will adjust your variables if you mentioned in the `DbContext` class in the override function `OnModelCreating`.

```csharp
protected override void OnModelCreating(ModelBuilder builder)
{
    builder.Model.SetMaxIdentifierLength(30);
    ...
}
```

When start to create the migration, it will create in the ModelSnapshot two hints that indicate the changes:

### Hint 1
```csharp
protected override void BuildModel(ModelBuilder modelBuilder)
{
  ...
  modelBuilder
    .HasAnnotation("Relational:MaxIdentifierLength", 30)
  ...
}
```

### Hint 2
```csharp
protected override void BuildModel(ModelBuilder modelBuilder)
{
  ...
  // For example, it will trim the end of the identifier and add "~" with number if duplication occur.
  b.HasIndex("SubjectId", "SessionId", "Type")
      .HasDatabaseName("IX_PersistedGrants_SubjectId~1");
  ...
}
```

# The Actual Problem
For some reason, this does not works on `ElsaContext` context. I have tried to extend it and implement the exact previous steps in order to adjust the `MaxIdentifier` for it, but only "Hint 1" shows up, "Hint 2" is still not changing, and it will trigger either of those two errors:
- ORA-00972: identifier is too long
- ORA-02000: missing ALWAYS keyword (If you did not do the `sql.UseOracleSQLCompatibility("11")`

```csharp
public class WorkflowElsaContext : ElsaContext
{
    public WorkflowElsaContext(DbContextOptions<WorkflowElsaContext> options) : base(options)
    {
    }

    public override string Schema => "";

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Model.SetMaxIdentifierLength(30);
        base.OnModelCreating(modelBuilder);
    }
}
```

Assuming that I did this in `Startup.cs`:
```csharp
services.AddElsa(elsa => elsa
    .UseEntityFrameworkPersistence<WorkflowElsaContext>(ef =>
        ef.UseOracle(connectionString, sql =>
        {
            sql.MigrationsAssembly(migrationsAssembly);
            sql.UseOracleSQLCompatibility("11");
        })
    )
```

However, the results for the migration itself is a bit weird and confusing:
### Hint 1
**It does work!**
```csharp
[DbContext(typeof(WorkflowElsaContext))]
partial class WorkflowElsaContextModelSnapshot : ModelSnapshot
{
    protected override void BuildModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
        modelBuilder
            .HasAnnotation("Relational:MaxIdentifierLength", 30)
        ...
    }
    ...
}
```

### Hint 2
**It does not work!**
```csharp
protected override void BuildModel(ModelBuilder modelBuilder)
{
  ...
  b.HasIndex("ActivityType", "TenantId", "Hash")
      .HasDatabaseName("IX_Bookmark_ActivityType_TenantId_Hash");
  ...
}
```

I might be missing something, in the context itself, but not really sure tho. Any hint?

**Comment by megamanhxh** [comment]
As a workaround, I have to change the `DatabaseName` for each index to make it work on oracle by trimming and unique the identifiers in the function `OnModelCreating`:

```csharp
protected override void OnModelCreating(ModelBuilder modelBuilder)
{
    modelBuilder.Model.SetMaxIdentifierLength(30);
    base.OnModelCreating(modelBuilder);

    modelBuilder.Entity<Bookmark>(b =>
    {
        b.HasIndex("ActivityType", "TenantId", "Hash")
            .HasDatabaseName("IX_Bookmark_ActivityType_Tena~");
        b.HasIndex("Hash", "CorrelationId", "TenantId")
            .HasDatabaseName("IX_Bookmark_Hash_CorrelationI~");
    });
    
    modelBuilder.Entity<WorkflowDefinition>(b =>
    {
        b.HasIndex("IsPublished")
            .HasDatabaseName("IX_WorkflowDefinition_IsPubli~");
        b.HasIndex("DefinitionId", "Version")
            .HasDatabaseName("IX_WorkflowDefinition_Definit~");
    });
    
    modelBuilder.Entity<WorkflowExecutionLogRecord>(b =>
    {
        b.HasIndex("ActivityId")
            .HasDatabaseName("IX_WorkflowExecutionLogRecor~1");
    
        b.HasIndex("ActivityType")
            .HasDatabaseName("IX_WorkflowExecutionLogRecor~2");
    
        b.HasIndex("TenantId")
            .HasDatabaseName("IX_WorkflowExecutionLogRecor~3");
    
        b.HasIndex("Timestamp")
            .HasDatabaseName("IX_WorkflowExecutionLogRecor~4");
    
        b.HasIndex("WorkflowInstanceId")
            .HasDatabaseName("IX_WorkflowExecutionLogRecor~5");
    });
    
    modelBuilder.Entity<WorkflowInstance>(b =>
    {
        b.HasIndex("ContextType")
            .HasDatabaseName("IX_WorkflowInstance_ContextTy~");
    
        b.HasIndex("CorrelationId")
            .HasDatabaseName("IX_WorkflowInstance_Correlati~");
        
        b.HasIndex("DefinitionId")
            .HasDatabaseName("IX_WorkflowInstance_Definitio~");
        
        b.HasIndex("LastExecutedAt")
            .HasDatabaseName("IX_WorkflowInstance_LastExecu~");
        
        b.HasIndex("WorkflowStatus")
            .HasDatabaseName("IX_WorkflowInstance_WorkflowS~");
    
        b.HasIndex("WorkflowStatus", "DefinitionId")
            .HasDatabaseName("IX_WorkflowInstance_Workflow~1");
    
        b.HasIndex("WorkflowStatus", "DefinitionId", "Version")
            .HasDatabaseName("IX_WorkflowInstance_Workflow~2");
    });
}
```

So unfortunate that I had to go manually for this process, it seems something related to index annotator for the entities that sets the identifiers forcefully manual (I could be wrong though).

If no solution for this, please close this issue, the workaround is doing the job in meantime.

**Comment by sfmskywalker** [comment]
I have no idea why it would work fine on your own DB context but not when inheriting from ElsaContext. Could be a bug in EF Core. As a test, what happens when you use two of your own DB contexts? For example:

```csharp
public class MyDbContext1 : DbContext
{
}

public class MyDbContext2 : MyDbContext1
{
}
```

Do you see the same behavior then?

In any case, perhaps your DB context doesn't need to be derived from ElsaContext at all, but instead use it separately?
I do this in a customer application who has its own DB Context. I simply inject `DbContext<ElsaContext>` when I need access to the Elsa DB context, and `DbContext<CustomerDbContext>` when I need the customer one.
