### ISSUE TITLE
Workflow Server - GraphQL Endpoint

### ISSUE THREAD

**Issue by sfmskywalker** [elsa-workflows/elsa-core#143]
The Workflow Server should expose a GraphQL that exposes the following queries and mutations:

**Queries**
- workflows
- workflow instances
- activities

**Mutations**
- createWorkflow
- updateWorkflow
- triggerEvent
- runWorkflow
- abortWorkflow

**Comment by Andale-online** [comment]
Hey... Now I get what GraphQL is for :-D thanks :+1

**Comment by sfmskywalker** [comment]
Good to hear :)

**Comment by sfmskywalker** [comment]
Merged 60bfb4e7b2a9a71cb97c1421c736a601f7e896ad
