### ISSUE TITLE
Bug in TimersHostedService

### ISSUE THREAD

**Issue by salarvand** [elsa-workflows/elsa-core#144]
when run ExcuteAsync method in the TimerHostService calss throw error!

`Processing of the LINQ expression 'AsQueryable<BlockingActivity>(NavigationTreeExpression
    Value: EntityReferenceWorkflowInstanceDocument
    Expression: (Unhandled parameter: w).BlockingActivities)' by 'NavigationExpandingExpressionVisitor' failed. This may indicate either a bug or a limitation in EF Core. See https://go.microsoft.com/fwlink/?linkid=2101433 for more detailed information.`

**Comment by sfmskywalker** [comment]
Looks like an issue with the EF Core persistence provider. Will check.

**Comment by sfmskywalker** [comment]
I think with the upgraded EF Core version it now no longer allows local queries by default, this to prevent inefficient queries.

Since I was already planning on revisiting the EF provider to allow more efficient querying, I might as well do it now and fix this problem while I'm at it.
