### ISSUE TITLE
How to use HttpEndpoint to get incoming parameters

### ISSUE THREAD

**Issue by landonzeng** [elsa-workflows/elsa-core#1446]
How to use HttpEndpoint to get incoming parameters, and call other APIs with SendHttpRequest, and then output the data returned by the API interface as WriteHttpResponse to its Json.

I intend to deploy Elsa workflow separately, with users customizing the workflow through Elsa Dashboard and the workflow using Http to call the business service API, which decouples the related business and also allows users to change the workflow at any time, but now I'm having the above problem because I really don't see the relevant example

**Comment by Rathna314** [comment]
Were you able to find any solution. Elsa website has nothing but 404's and zero documentation.
