### ISSUE TITLE
The rest of workflow runs twice after child workflow finishes

### ISSUE THREAD

**Issue by VahidShir** [elsa-workflows/elsa-core#1455]
Trying on latest source code from MyGet(**2.3.0-preview.90**).
Latest NuGet version (**2.2.1**) doesn't have this issue.
Parent workflow:
1. Console WriteLine activity:
  "Parent workflow started."
2. RunWorkflow:
 Mode: Blocking
3. Console WriteLine activity:
 "Parent workflow finished."

Child workflow:
1. Console WriteLine activity:
  "Child workflow finished."
2. Finish activity

[parent.zip](https://github.com/elsa-workflows/elsa-core/files/7082629/parent.zip)
[child.zip](https://github.com/elsa-workflows/elsa-core/files/7082631/child.zip)

Expected console output:
```
Parent workflow started.
Child workflow finished.
Parent workflow finished.
```
Current console output:
```
Parent workflow started.
Child workflow finished.
Parent workflow finished.
Parent workflow finished.
```
Note: This issue also happens on latest NuGet version **2.2.1** if using a custom RunWorkflow activity.

**Comment by sfmskywalker** [comment]
Thanks for the great repro 🙌🏻
