### ISSUE TITLE
SmtpClient is not thread safe

### ISSUE THREAD

**Issue by petedavis** [elsa-workflows/elsa-core#147]
If a heap of workflows trigger an email at the same time, the same instance of the SMTP client is used, which results in an `InvalidOperationException`

Perhaps a task to migrate to MailKit?

Otherwise maybe the SMTP client instance needs to be created when the activity is executed?

![image](https://user-images.githubusercontent.com/164331/68830506-c92dc780-06fb-11ea-957f-efdbb055ec63.png)

**Comment by sfmskywalker** [comment]
I looked into the issue of SmtpClient not being thread-safe, and found this SO post: https://softwareengineering.stackexchange.com/questions/336291/is-smtp-client-created-in-singleton-scope-or-request-scope

The answer states that for a truly scalable solution, it's best to implement a pool system of smtp clients. 

A simpler alternative is to just create a new instance when the activity is executed, as you suggested.

I'm not familiar with MailKit, but it looks like a very rich and robust emailing library. Do you have experience with it? And more importantly, is its SMTP client thread-safe?

**Comment by petedavis** [comment]
No I havent looked into MailKit yet. I really only have awareness because Orchard Core stopped using SmtpClient and used mailkit. And i think there is guidance from Microsoft to use that instead.

https://github.com/OrchardCMS/OrchardCore/pull/3458

**Comment by sfmskywalker** [comment]
I see. Then all the more reason to switch 👍
