### ISSUE TITLE
Cannot configure a singleton workflow triggered by HttpEndpoint

### ISSUE THREAD

**Issue by andreapier** [elsa-workflows/elsa-core#1473]
I am trying to create and endpoint that cannot be invoked concurrently so I checked the `Singleton` checkbox in workflow properties.
However this does not seem to work. I can invoke the endpoint concurrently.
So I tried to create a Singleton Cron workflow, and this seems to work as expected.
I looked through the code but didn't quite understand how the singleton feature works.

There seem to be 2 way to determine if a singleton workflow can be run:
- acquiring a lock => This works for `Cron` activity, but not for `HttpEndpoint`
- checking if an instance has state `Running` or `Suspended` (I am using EF persistence) => This seems to no work as expected: I can never find an instance that has state `Running`. It either has state `Idle` or `Finished`

Also, I couldn't find where the instance state gets updated to `Running` in the DB.

Can you please clarify if this is a bug or an intended feature?
I understand that an http call might not be the perfect use case for singletons, but it could help a lot to implement queue-like systems.
Let me know if you need more info, thanks

**Comment by sfmskywalker** [comment]
I just tried a singleton HTTP workflow, and it behaved as expected. Here's what I did:

1. Create & published a new [singleton HTTP workflow](https://github.com/elsa-workflows/elsa-core/files/7128120/singleton-http-workflow-demo.zip)
2. Invoked the workflow once (successfully)
3. Invoked the workflow again. This time I received a 404.

What version are you using? If older than 2.2 then perhaps there's a bug.
