### ISSUE TITLE
Hosting Elsa on Multiple Nodes: Executing workflows not working #azureservicebus

### ISSUE THREAD

**Issue by progala2** [elsa-workflows/elsa-core#1478]
Hi,

I have problems with the distributed execution of workflows in Elsa 2.2.1.
I configured everything as it is described in the [documentation](https://elsa-workflows.github.io/elsa-core/docs/hosting/hosting-distributed-hosting), here is my configuration:
```charp
.UseServiceBus(s =>
{
    s.Configurer
        .Transport(t =>
            t.UseAzureServiceBus(
                Configuration.GetConnectionString("ElsaServiceBus"), "ElsaQueue"));
})
.ConfigureDistributedLockProvider(l => { l.UseSqlServerLockProvider(Configuration.GetConnectionString("ElsaServerDb")); })
.UseRebusCacheSignal()
.AddQuartzTemporalActivities(configureQuartz: quartz => quartz.UsePersistentStore(store =>
{
    store.UseJsonSerializer();
    store.UseSqlServer(Configuration.GetConnectionString("ElsaServerDb"));
    store.UseClustering();
}))
```

The issue is that when I execute some workflow by api it sends an event to the "execute-workflow-definition-request-default" queue  and **it never reads from this queue to actually execute it.**

I found that probably there is incoherency between the ```QueuingWorkflowDispatcher``` and the ```CreateSubscriptions``` in the queue naming, but maybe there is something more, because I managed to replace the ```QueuingWorkflowDispatcher``` with my own implementation but still nothing happens after sending an event to the queue with the "execute-workflow-default" name.

Is something missing in my configuration or is there some bug?

We would like to use Elsa in our company but without distributed nodes, we cannot do it :(

**Comment by sfmskywalker** [comment]
Could be a bug with the queue names being registered. Will have to investigate.

**Comment by tomy2105** [comment]
When using Postgres and SQL Server I needed to configure two things for Service Bus: Transport and Subscriptions .
Don't know if that is the case for Azure but maybe you are missing subscription config for Azure (or is that hidden inside UseAzureServiceBus :)?).

In any case in Elsa 2.0 it works for me with both Postgres and SQL Server so it is either something introduced later or specific to using Azure provider.

Here is my snippet for service bus:

                    .UseServiceBus(context => {
                        context.Configurer.Transport(
                            t => t.UsePostgreSql(rebusPostgresServerConn, "ElsaRebusTransport", context.QueueName)
                        );
                        context.Configurer.Subscriptions(
                            s.StoreInPostgres(rebusPostgresServerConn, "ElsaRebusSubscriptions") 
                        );
                    })

**Comment by progala2** [comment]
@tomy2105 Thanks! I'll check it 👍

**Comment by progala2** [comment]
@tomy2105 There is nothing to be done with the subscription part with Azure Service Bus, so it's not the issue, but thanks for helping!

**Comment by progala2** [comment]
```
.UseServiceBus(s =>
{
    s.Configurer
        .Transport(t =>
            t.UseSqlServer(
                new SqlServerTransportOptions(elsaSqlDbConnectionString), "ElsaQueue"))
        .Subscriptions(s => s.StoreInSqlServer(elsaSqlDbConnectionString, "ElsaQueueSubscriptions"));
})
```
I configured the sql provider and now it shows an error during initialization that "there is no dbo.execute-workflow table". I created one, by copying the dbo.ElsaQueue but after that I get an error that:
```
: 'Cannot get destination for message of type Elsa.Services.ExecuteWorkflowDefinitionRequest because it has not been mapped! 
```

If it worked in 2.0 that means something has been broken in the meantime; I use the 2.2.1 version.

**Comment by sfmskywalker** [comment]
@progala2 Any chance you can share a (stripped down) version of your project that reproduces this issue?

**Comment by progala2** [comment]
[OptimusPrime.zip](https://github.com/elsa-workflows/elsa-core/files/7135308/OptimusPrime.zip)

We use the ScoringWorkflowController to run the workflow, you can use it by swagger by putting the ScoringWorkflow in the name field

**Comment by sfmskywalker** [comment]
Thanks for the repro! I see now what the issue is. You were right with your initial assessment: there was a mismatch between the configured queues and the queues actually use to send a message to.

To fix this, you need to use the queue name provided as part of the `s` argument in your lambda, like so:

```csharp
.UseServiceBus(s =>
                    {
                        s.Configurer
                            .Transport(t =>
                                t.UseAzureServiceBus(
                                    Configuration.GetConnectionString("ElsaServiceBus"), s.QueueName));
                    })
```

Notice the last argument of the last line (`s.QueueName`).

This lambda is invoked for each endpoint (registered queue name) used by Elsa.

As an alternative to the above code, you might consider using the following helper:

```csharp
.UseAzureServiceBus(Configuration.GetConnectionString("ElsaServiceBus"))
```

It does the same thing, and still allows you to further configure the transport by one of its overloads.

**Comment by progala2** [comment]
Thank you for your response!
I'll check it and let you know the results.

So it means it is not possible to name the queue by my own name, right? It is not a big issue but something good to know.

PS I think it would be good to include it on the documentation page?
Is this repo for that: [website-repo](https://github.com/elsa-workflows/elsa-website/tree/master/website)?
I'll make a PR after the "fix" confirmation :)

**Comment by progala2** [comment]
The fix confirmed.
Thanks for your help!

**Comment by sfmskywalker** [comment]
Thanks for confirming!

> PS I think it would be good to include it on the documentation page?

Definitely.

> Is this repo for that: website-repo?

That's the one!

> I'll make a PR after the "fix" confirmation :)

That would be fantastic, thank you :)
