### ISSUE TITLE
Stop workflow execution from dashoard

### ISSUE THREAD

**Issue by sfmskywalker** [elsa-workflows/elsa-core#1495]
We should be able to cancel workflow instances from the dashboard.

**Comment by Nokecy** [comment]
How to cancel a process programmatically ？ @sfmskywalker

**Comment by sfmskywalker** [comment]
I think it will be something like this:

1. Acquire a lock on `$"workflow-instance:{workflowInstanceId}"`.
2. Get the workflow instance from `IWorkflowInstanceStore`.
3. Set the status to `Cancelled`.
4. Save the changes.
5. Release the lock.

The locking mechanism is necessary to avoid situations where the workflow instance is currently being executed (and therefore is in memory) after which it gets persisted back to the database, overriding the previous cancellation action.

**Comment by sfmskywalker** [comment]
@Nokecy You can now cancel workflow instances from the dashboard.

To do it programmatically, inject the new `IWorkflowInstanceCanceller` service and invoke its `CancelAsync` method, which takes a workflow instance ID as its first argument.

Example:

```csharp
_workflowInstanceCanceller.CancelAsync(workflowInstanceId);
```

**Comment by Nokecy** [comment]
Thanks, i will try @sfmskywalker

**Comment by hm-ch** [comment]
Hi @sfmskywalker 

How can I get this Fix via nuget package.

Thanks.

**Comment by sfmskywalker** [comment]
Hi @hm-ch ,

You can get this from the MyGet feed. Details how to do that can be found [here](https://elsa-workflows.github.io/elsa-core/docs/next/installation/installing-feeds).
