### ISSUE TITLE
HTTP Endpoints Swagger

### ISSUE THREAD

**Issue by sfmskywalker** [elsa-workflows/elsa-core#1499]
Currently Swashbuckle only looks at controller actions when building an Open API specification. We should look into the possibility of telling Swashbuckle to also look at HTTP Endpoint activities declared on workflow blueprints. This would provide a complete view of all of the exposed API endpoints when generating the specification.

**Comment by emmanuelmathot** [comment]
I really would like to see HTTP activities exposed automatically to OpenAPI and thus swagger. Why isn't there the case already? Are the dynamic controllers hidden?

**Comment by sfmskywalker** [comment]
I would love to see it too. The reason it doesn't just work is because the HTTP Endpoint activity doesn't integrate with ASP.NET routing. It's currently implemented as a simple piece of middleware.
