### ISSUE TITLE
Service Bus activities

### ISSUE THREAD

**Issue by sfmskywalker** [elsa-workflows/elsa-core#15]
We need a set of activities that can send/publish messages to a service bus and receive messages from a service bus. Ideally, the service bus support is abstracted away so that we can implement providers for Azure Service Bus, RabbitMQ and others. I don't want to use MassTransit for this, because that relies on strongly-typed message classes. Instead, this feature should allow the user to send arbitrary payloads with message names, and be able to consume those message from the same or other workflows.

**Comment by Andale-online** [comment]
I'd Like to help on that...

**Comment by sfmskywalker** [comment]
Please do. Let me know if you need anything from me. Thanks!

**Comment by Andale-online** [comment]
I like this API:

https://github.com/rebus-org/Rebus

I used it with RabbitMQ before and it's very easy and straight-forward.

Seen it before?

**Comment by sfmskywalker** [comment]
Nice. I haven't used it before, but I did see it when I did some preliminary research on this topic. 

Do you think it can be used without having to specify strongly-typed C# classes? I.e. could we have a generic SendMessage and ReceiveMessage activity, and specify a message name + JSON payload?

**Comment by Andale-online** [comment]
Err... The Messagebus doesnt care about types (normally). You just take an object and put it on the bus. The bus doesnt care if it is an complex object or an json string. It will serialize it to the bus as is.

**Comment by sfmskywalker** [comment]
Then it sounds perfect.

**Comment by Andale-online** [comment]
Will be on my roadmap in the next 48h. Need the feature. Will create simple solution someone else may extend...

**Comment by sfmskywalker** [comment]
Awesome!

**Comment by Andale-online** [comment]
Dropping message implemented

**Comment by Nongzhsh** [comment]
https://github.com/dotnetcore/CAP 

I think it's good.

**Comment by sfmskywalker** [comment]
Done
