### ISSUE TITLE
Multiple Activity Incomes (Improved Join)

### ISSUE THREAD

**Issue by FlorianZick** [elsa-workflows/elsa-core#1502]
Hey,
is it possible to create a "JOIN" activity, which doesn't just wait for all.
Instead, it should have customizeable Income branchs (like the outcomes branches in the Fork activity). This activity should wait for all and can then identify, which input comes from which incomes branch.

In addition it would be great to have a Fork activity, which can give each branch a different input.

Are these two things possible? And if not, are they planed?

Greetings,

Florian

**Comment by sfmskywalker** [comment]
Hi Florian,

This new Join activity that you described, can you tell a little bit more about why it would be useful for it to have a specific set of income branches? Perhaps a concrete use case might help make me understand.

In any case, activities in Elsa do not have any notion of inbound ports, only outbound ports. However, as I'm designing a new architecture for Elsa 3, it would be interesting to understand how inbound ports might be useful.

Regarding your question about the Fork activity where you can provide a different input per branch, that would be possible to implement as a new activity today. It would probably look similar to the Switch activity where you'd have a list of branches and next to each branch an expression editor to specify the output for each (which would be provided as input into the first connected activity to each branch).

This is not planned, but feel free to create an issue for it. And if you create a PR I'd happily accept it 😃
