### ISSUE TITLE
Swagger not working with Elsa 2.2.1 for Custom Controllers

### ISSUE THREAD

**Issue by rairafaqatali** [elsa-workflows/elsa-core#1503]
Hi @sfmskywalker 
I have created Elsa project and it working fine, I added swagger to this project and it throws the error:
SwaggerGeneratorException: Conflicting method/path combination "GET v1/workflow-definitions" for actions - Elsa.Server.Api.Endpoints.WorkflowDefinitions.GetMany.Handle

Can you let me know how it will be fixed?

**Comment by progala2** [comment]
Probably because Elsa has its own implementation of swagger.
an example of startup file, it works in our solution.
```       
public void ConfigureServices(IServiceCollection services)
{    

            services.AddControllers();
 services
                .AddElsaApiEndpoints()
                .AddElsaSwagger();
}
public void Configure(IApplicationBuilder app, IWebHostEnvironment env)
        {
         app.UseHttpsRedirection();

            app.UseRouting();
            app.UseCors();
            app.UseAuthorization();

            app.UseElsaFeatures();
            app.UseEndpoints(endpoints =>
            {
                endpoints.MapControllers();
            });

            if (env.IsDevelopment())
            {
                app.UseDeveloperExceptionPage();
                app.UseSwagger();
                app.UseSwaggerUI(c => c.SwaggerEndpoint("/swagger/v1/swagger.json", "name"));
            }
        }
                ```

**Comment by rairafaqatali** [comment]
@progala2 yes, with these options, swagger shows the detail of Elsa endpoints.
But, it will not shows the detail of the controllers that I have added to this project.

So, the issue is, I need to show both Elsa & custom controllers in swagger UI.

**Comment by progala2** [comment]
I have my own controller, it looks like that:
```
 [Route("v1/[controller]/[action]")]
    [ApiController]
    public class ScoringWorkflowController : Controller
    {
        public ScoringWorkflowController()
        {
        }

        [HttpPost]
        public async Task<IActionResult> Execute(CancellationToken cancellationToken)
        {
            return Ok();
        }
        ```
        
        It is displayed in the swagger.

**Comment by rairafaqatali** [comment]
Thanks, @progala2 
Decorating custom controllers with 
[ApiController]
working

**Comment by mgochmuradov** [comment]
Or if you don't want to (or can't) edit controllers, you can do

```cs
	services.AddElsaApiEndpoints();

	// Add the following code
	services.AddApiVersioning(
		options =>
		{
			options.UseApiBehavior = false;
		});
```
