### ISSUE TITLE
Newtonsoft json  self referencing loop detected

### ISSUE THREAD

**Issue by 1002527441** [elsa-workflows/elsa-core#1509]
Hi Team

When I StartworkflowAsync with the object of IStartsWorkflow, I met the Newtonsoft json  self referencing loop detected in source code. could you help me to verify it.

with the following code, it could be reference.

var workflowInput = new WorkflowInput(dto);

var workflowResult = await _startsWorkflow.StartWorkflowAsync(workflowBlueprint, null, workflowInput);

return (int) workflowResult.WorkflowInstance.WorkflowStatus;

regards
Henry

**Comment by 1002527441** [comment]
with latest version Elsa 2.2.1

**Comment by 1002527441** [comment]
I am using MongDB, Error information happend in ObjectSerializer:IBsonSerializer<object>, in JsonSerializerSettings,  

        _serializerSettings = new JsonSerializerSettings
            {
                NullValueHandling = NullValueHandling.Ignore,
                TypeNameAssemblyFormatHandling = TypeNameAssemblyFormatHandling.Simple,
                TypeNameHandling = TypeNameHandling.Auto,
                ReferenceLoopHandling = ReferenceLoopHandling.Ignore,      //Added by henry
            }.ConfigureForNodaTime(DateTimeZoneProviders.Tzdb);

**Comment by sfmskywalker** [comment]
In most cases that I have seen, input DTOs aren't too complex. But if you have a DTO with reference loops and this setting works for you, it should be fine to add. Do you want to submit a PR?

**Comment by 1002527441** [comment]
@sfmskywalker thanks for your confirmation. I will try to submit a PR this weekend.
