### ISSUE TITLE
Feature request: Add ability to hold object in Outcomes

### ISSUE THREAD

**Issue by Andale-online** [elsa-workflows/elsa-core#151]
Hey dude...

I'm struggling around the "dont use variables" problem in the xml-package.

currently writing to the workflow looks like 

`            byte[] content = await request.ReadContentAsBytesAsync();

            string rootNodeTypeName = TypeName;
            if (string.IsNullOrEmpty(rootNodeTypeName))
                rootNodeTypeName = TypeSafeXMLExtensions.GetRootTypeName(ref content);

            if (rootNodeTypeName != "")
            {
                Type rootType = TypeSafeXMLExtensions.GetType(rootNodeTypeName, AssemlbyName);
                XmlSerializer xmlSerializer = new XmlSerializer(rootType);
                model.Body = xmlSerializer.Deserialize(new MemoryStream(content));
                workflowContext.CurrentScope.LastResult = Output.SetVariable("Content", model);
                Output.SetVariable("Result", model.Body);
            }

            return Done();`

and receiving the value looks like:
`
string bodyText;
            var inputObject = workflowContext.CurrentScope.LastResult;

            Type rootType = inputObject.GetType();
            XmlSerializer xmlSerializer = new XmlSerializer(rootType);
            using (MemoryStream stream = new MemoryStream())
            {
                xmlSerializer.Serialize(stream, inputObject);
                bodyText = System.Text.Encoding.Default.GetString(stream.ToArray());
            }`

To be honest - its pain i.t.a

restclient gave me for a workflow that just should write back the request xml:
System.Func`3[Jint.Native.JsValue,Jint.Native.JsValue[],Jint.Native.JsValue]

Why does everything has to be serialized internally. You can do so for the js-interpreter - but why dont keep the original. 

So my idea:

We got Outcomes... As i am used to it (from DTS, SSIS, KEttle etc.) the Outcomes hold values. 

So instead of returning:

            return Done();

we could return:

            return Done(myObjectForThisOutcomeLane);

Would prevent objects from de/serializing and even outcomes with strings, number values or even no value etc. would work.

The Result-thingy is good, but it should remain the "base result" of the workflow...

Whatchathinking

**Comment by Andale-online** [comment]
Of course... I would do this...

**Comment by Andale-online** [comment]
A Done<T> would be cool... That way the object type would be displayable in dashboard

**Comment by sfmskywalker** [comment]
Just to make sure I understand.

Are you proposing to keep the variable read in the `RecieveHttpRequest` in-memory when passing it to the outcome?

If so, then what should happen when the next activity to which execution transitions halts the workflow, and needs the variable when it is resumed? Would the object not be lost when the workflow is to be suspended and persisted?

As for the ability to pass data alongside an `OutcomeResult`, that is quite an interesting idea that I will give some more thought 👍 

> Why does everything has to be serialized internally. You can do so for the js-interpreter - but why dont keep the original.

The reason things need to be serialized is to support long-running workflows where a workflow instance becomes suspended and serialized. If we didn't serialize values, objects will get lost.
The Outcome + value idea is nice, but these values too would have to be serialized and then deserialized.

I'm not sure I see the problem with serialization/deserialization. If you know the type of object being serialized, you generally also know that type when deserializing, so you could stream its JSON representation (or JToken in this case) right back into its original type.

No doubt I'm missing some important point, so please do help me see.

**Comment by Andale-online** [comment]
This will be obsolete with milestone 2.0 - so closing

**Comment by sfmskywalker** [comment]
@Andale-online `feature/elsa-2.0` now contains this feature. Activities can return an outcome and specify an output value, which is then automatically made available to all immediately connected activities. 

I also optimized the activity's state to use the `Variables` object instead of `JObject`, so that values only get serialized when the workflow as a whole is being serialized for persistence. 

This opened the door for adding support to basically connect C# statements within a workflow, without having to use script syntax (which is still useful when creating workflows using the visual designer).
