### ISSUE TITLE
UseEntityFrameworkPersistence not available

### ISSUE THREAD

**Issue by rairafaqatali** [elsa-workflows/elsa-core#1510]
Hi @sfmskywalker I updated below packages
  ```
<PackageReference Include="Elsa" Version="2.3.0-preview.124" />
  <PackageReference Include="Elsa.Activities.Http" Version="2.3.0-preview.124" />
  <PackageReference Include="Elsa.Activities.Temporal.Quartz" Version="2.3.0-preview.124" />
  <PackageReference Include="Elsa.Server.Api" Version="2.3.0-preview.124" />
```
from 
```
 <PackageReference Include="Elsa" Version="2.3.0-preview.87" />
  <PackageReference Include="Elsa.Activities.Http" Version="2.3.0-preview.87" />
  <PackageReference Include="Elsa.Activities.Temporal.Quartz" Version="2.3.0-preview.87" />
  <PackageReference Include="Elsa.Server.Api" Version="2.3.0-preview.87" />
```

**and got the error "Reference to type 'ElsaOptionsBuilder' claims it is defined in 'Elsa.Core', but I couldn't be found**

Can you  kindly guide me on what I'm missing here
Thanks

**Comment by sfmskywalker** [comment]
Nothing seems off from the snippets you sent, but based on the error message you either have a cached build output that's in play or another project that references a different Elsa package version.

**Comment by rairafaqatali** [comment]
@sfmskywalker I have removed the cached but still same error. Here are the references that I'm using in my project
![image](https://user-images.githubusercontent.com/52976818/133045395-1e6d4963-ffb6-4166-b6d4-00b5fe26dc45.png)

**Comment by rairafaqatali** [comment]
@sfmskywalker I'm getting this issue now
![image](https://user-images.githubusercontent.com/52976818/133049778-eb089027-09cf-4a02-bdef-b7a01572e192.png)
I have cleared cache, changed browser, removed obj/bin folders but same error

**Comment by sfmskywalker** [comment]
Hi @rairafaqatali , good to see you resolved the issue.
For the other issue, please create a separate one. When you do, please also provide steps to reproduce since the JS error you're displaying does not occur when I start a new Elsa project. If you want you can also attach a zipped version of your (stripped down) project in order for me to reproduce the problem on my machine. Thank you.
