### ISSUE TITLE
Hosting Elsa Dashboard in IIS

### ISSUE THREAD

**Issue by Marsland** [elsa-workflows/elsa-core#1525]
Hi!

We are working with Elsa and would like to be able to host Elsa under IIS along with our other .NET Core APIs. I can't seem to work out how to deploy Elsa as a published .NET Core application to IIS. The paths to the resources the _Host.cshtml page links to end up lacking the name of the application in IIS under the main Url (e.g. https://our-dev.co.com/ElsaDashboard.

The links for the resources on the page end up with 404s and are  https://our-dev.co.com/_content  instead of  https://our-dev.co.com/ElsaDashboard/_content. We moved the wwwroot files out to the main folder after seeing similar errors when the _content folder is inside of the wwwroot folder.

We are probably missing something very basic here but can't just dedicate an entire IIS instance to Elsa alone. Is there a simple way to set this up so it works correctly?

Thanks in advance,
David Marsland

**Comment by sfmskywalker** [comment]
Hi David,

It sounds like this might be a similar issue as https://github.com/elsa-workflows/elsa-core/issues/1395.

There is a `base-path` attribute on the `elsa-studio-root` element you might try to set:

```html
<elsa-studio-root server-url=" https://our-dev.co.com/ElsaServer" base-path="/ElsaDashboard" monaco-lib-path="build/assets/js/monaco-editor/min" culture="en-US">
<elsa-studio-dashboard></elsa-studio-dashboard>
</elsa-studio-root server-url>
```

I'm not sure if this is already part of 2.2.x, but it is definitely available today with the 2.3.x prerelease packages available from MyGet.

Furthermore, it is important to configure the dashboard ASPNET server project to rewrite requests using the base path.

See @matt446's comment as well: https://github.com/elsa-workflows/elsa-core/issues/1395#issuecomment-904129203

I've never went through the entire IIS sub directory setup myself, but I will try and see what I find.

**Comment by Marsland** [comment]
It's very similar. I'm on 2.2.1 freshly installed from NuGet, changing the base-path in that case had no effect. The page shows 404s for the items being referenced in the <head> and the monaco-editor. 
![image](https://user-images.githubusercontent.com/4764115/133145241-8aedc422-12ee-422e-bd87-c9ca57a7d963.png)

I did previously trying hand editing the links to prepend the site name, which sort of worked as far as loading the landing page but the navigation failed due to the missing 'ElsaDashboard'.

When you mention " it is important to configure the dashboard ASPNET server project to rewrite requests using the base path" I'm not sure what you mean. This is deployed as an application to IIS so normally a web site/ react app will handle that for you but I  might be missing your meaning here.

I'll go get 2.3 and try this again. I'll keep you posted as to what happens.

BTW< kudos to you on this project, it's just what we were looking for and we are eager to get this operational on a pilot project.

**Comment by sfmskywalker** [comment]
When I follow the steps [outlined here](https://github.com/elsa-workflows/elsa-core/issues/1395#issuecomment-918514613), the dashboard is loaded correctly from a sub directory of IIS.

**Comment by Marsland** [comment]
I'll give it go, looks like that should work. The @basepath path is similar to the hack I tried the other day.

Just a super job on your part and keep it up :) :) :)

**Comment by sfmskywalker** [comment]
> When you mention " it is important to configure the dashboard ASPNET server project to rewrite requests using the base path" I'm not sure what you mean. This is deployed as an application to IIS so normally a web site/ react app will handle that for you but I might be missing your meaning here.

As it turns out, you are correct and this is not necessary at all 😄 

> BTW< kudos to you on this project, it's just what we were looking for and we are eager to get this operational on a pilot project.

Hearing that makes my day. Thanks! 😄

**Comment by Marsland** [comment]
I'm close. I followed the suggested steps on the other issue but now getting a 500 error which is probably the server?

Category: Microsoft.AspNetCore.Server.IIS.Core.IISHttpServer
EventId: 2
SpanId: 0a4f736601c8d34d
TraceId: e335ead9e15aee46a8b690f539f15288
ParentId: 0000000000000000
RequestId: 80000125-0001-af00-b63f-84710c7967bb
RequestPath: /ElsaDashboard

Connection ID "12610078962542969124", Request ID "80000125-0001-af00-b63f-84710c7967bb": An unhandled exception was thrown by the application.

Exception: 
System.NullReferenceException: Object reference not set to an instance of an object.
   at AspNetCore.Pages__Host.<>c__DisplayClass8_0.<<ExecuteAsync>b__1>d.MoveNext() in C:\Projects\ElsaQuickstarts.Server.Dashboard\Pages\_Host.cshtml:line 21
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Razor.Runtime.TagHelpers.TagHelperExecutionContext.SetOutputContentAsync()
   at AspNetCore.Pages__Host.ExecuteAsync() in C:\Projects\ElsaQuickstarts.Server.Dashboard\Pages\_Host.cshtml:line 5
   at Microsoft.AspNetCore.Mvc.Razor.RazorView.RenderPageCoreAsync(IRazorPage page, ViewContext context)
   at Microsoft.AspNetCore.Mvc.Razor.RazorView.RenderPageAsync(IRazorPage page, ViewContext context, Boolean invokeViewStarts)
   at Microsoft.AspNetCore.Mvc.Razor.RazorView.RenderAsync(ViewContext context)
   at Microsoft.AspNetCore.Mvc.ViewFeatures.ViewExecutor.ExecuteAsync(ViewContext viewContext, String contentType, Nullable`1 statusCode)
   at Microsoft.AspNetCore.Mvc.ViewFeatures.ViewExecutor.ExecuteAsync(ViewContext viewContext, String contentType, Nullable`1 statusCode)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResultFilterAsync>g__Awaited|29_0[TFilter,TFilterAsync](ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResultExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.ResultNext[TFilter,TFilterAsync](State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeResultFilters()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|24_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeFilterPipelineAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Builder.Extensions.UsePathBaseMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Server.IIS.Core.IISHttpContextOfT`1.ProcessRequestAsync()

**Comment by Marsland** [comment]
I was able to sort this out by replacing my server project with a simpler one and hardcoding (for now) the base address, but this IS working and I AM tickled. :)

**Comment by Marsland** [comment]
Next wrinkle: the auto-generated signal_url in our test email for an approval doesn't have our Server base path so we get:

https://apis-dev.ica.com/signals/trigger/

instead of https://apis-dev.ica.com/ELSA_1/signals/trigger/   (ELSA_1 in this case being our server)

From this:
Hello, please approve your submitted document here: <br><a href="{{ "Approve-IPN-WF1" | signal_url }}">Approve</a> <br> You can also ject the preposed document here: <a href="{{ "Reject-IPN-WF1" | signal_url }}">Reject</a>

Thanks in advance for your super support!

Dave

**Comment by sfmskywalker** [comment]
That's odd. if your `BaseUrl` setting is configured as `https://apis-dev.ica.com/ELSA_1` then it should use that as the base path. Unless you're on a less than current version, since this was actually an issue that was resolved relatively recently (maybe couple of weeks or more). 

If you are seeing this on 2.3 preview then I will try to reproduce.

**Comment by Marsland** [comment]
ELSA_1 is a server-only project based on the documentation/tutorial, so I apparently am not familiar with where or how the BaseUrl setting is configured, and I'm 99% certain that particular demo project is on 2.2.1, so if you can point me at documentation for how to set the BaseUrl (Startup.cs? appsettings? web.config?) I can probably sort this out. I can also port the server project over to a 2.3 preview based version if that's necessary.

We are making good progress and I hope to be able to start wiring this up with our web app front ends on a sample 'real-world' app so I'm pleased with how well it's going. The other Senior Developers have commented on how well-thought out this is as far as design and implementation. Usually by this time we would have hit some sort of snag or complexity.

If I get some spare time in the schedule I'll see if I can contribute something useful, other than pointing out typos in the documentation lol.

**Comment by Marsland** [comment]
Found the BaseUrl in the appsettings.json

**Comment by Marsland** [comment]
It was set to the following:
 "Elsa": {
    "Http": {
      "BaseUrl": "https://apis-dev.ica.com/ELSA_1"
    },
    "Server": {
      "BaseUrl": "https://apis-dev.ica.com/ELSA_1"
    },
  "Smtp": {
    "Host": "localhost",
    "Port": "25",
    "DefaultSender": "noreply@us.com"
  }

This looks to be correct so I think I'm back to being puzzled again.

D

**Comment by sfmskywalker** [comment]
I am pleased to hear things are going well and that the seniors like it 😊 

Yes, the `BaseUrl` setting in appsettings is the one to use. Althought, since the base URL is environment-dependent, it might be a better idea to set it as an environment variable from the application in IIS (`ELSA__SERVER__BASEURL=https://apis-dev.ica.com/ELSA_1`).

**Comment by sfmskywalker** [comment]
Your appsettings.json are correct, so then it must be the fact that you're using 2.2 which must still have this bug. If you upgrade to 2.3 preview and are still not having any luck, let me know and I will dig into it.

**Comment by Marsland** [comment]
Currently we have a separate appsettings per environment but the approach you suggest is valid too. I'll update this project to 2.3 and give it another go.

**Comment by sfmskywalker** [comment]
Separate appsettings per environment works perfectly well too of course.

**Comment by Marsland** [comment]
I recreated the sample server project with the 2.3.171 preview and it's still not adding the '/ELSA_1' BaseUrl to the actual embedded email link. We are trying a couple of things to see if we can give you a reproduceable test case.

**Comment by Marsland** [comment]
Note that the actual signal url is created at the right endpoint, it's just the embedded signal_url link in the email doesn't include it. You can edit the URL manually and the endpoint is valid.

**Comment by Marsland** [comment]
Here are two workflows. The 'workaround' version we manually modify the provided signalUrl. The other one is the one that doesn't work. We are running in an IIS Application using the appSettings.json settings provided above
[workflow_Workaround.zip](https://github.com/elsa-workflows/elsa-core/files/7187673/workflow_Workaround.zip)
.

**Comment by sfmskywalker** [comment]
I can indeed reproduce the issue. Looking into it.

**Comment by sfmskywalker** [comment]
The issue was because of the way `Uri` works when being constructed, which follows strict rules:

- The base path needs to end with a slash.
- The relative path must not start with a slash.

Any other combination will cause the virtual directory portion of the base path to be lost.

I pushed a change that will take care of this automatically. Once the new packages are built and you update your project, things should start to work better.

**Comment by Marsland** [comment]
Standing by for the new build. Thanks as always!

**Comment by akghasemi** [comment]
I had the same problem ,I used this approach and it works for me in IIS: 

@inject IConfiguration _configuration;
@using System.Web 
@{
    ViewData["Title"] = "Workflow Dashboard";
    //var serverUrl = _configuration["Elsa:Server:BaseUrl"];
    string serverUrl = $"<elsa-studio-root server-url=\"{Context.Request.Scheme}://{Context.Request.Host}{Context.Request.PathBase}\"   monaco-lib-path=\"{Context.Request.Scheme}://{Context.Request.Host}{Context.Request.PathBase}/_content/Elsa.Designer.Components.Web/monaco-editor/min\" >" +
        "<elsa-studio-dashboard></elsa-studio-dashboard>" +
        "</elsa-studio-root>";


}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Elsa Dashboard</title>
    <link rel="icon" type="image/png" sizes="32x32" href="~/_content/Elsa.Designer.Components.Web/elsa-workflows-studio/assets/images/favicon-32x32.png">
    <link rel="icon" type="image/png" sizes="16x16" href="~/_content/Elsa.Designer.Components.Web/elsa-workflows-studio/assets/images/favicon-16x16.png">
    <link rel="stylesheet" href="~/_content/Elsa.Designer.Components.Web/elsa-workflows-studio/assets/fonts/inter/inter.css">
    <link rel="stylesheet" href="~/_content/Elsa.Designer.Components.Web/elsa-workflows-studio/elsa-workflows-studio.css">
    <script src="~/_content/Elsa.Designer.Components.Web/monaco-editor/min/vs/loader.js"></script>
    <script type="module" src="~/_content/Elsa.Designer.Components.Web/elsa-workflows-studio/elsa-workflows-studio.esm.js"></script>
</head>
<body BBBaboo="@true" test="@Context.Request.Host" test2="@Context.Request.PathBase" test3="@Context.Request.Path" >
    @*<elsa-studio-root server-url=@Url.Content("~") monaco-lib-path=@Url.Content("~/_content/Elsa.Designer.Components.Web/monaco-editor/min") >
        <elsa-studio-dashboard></elsa-studio-dashboard>
    </elsa-studio-root>*@
    @Html.Raw(serverUrl)
</body>
</html>
