### ISSUE TITLE
Elsa Dashboard not work with Pascal case json

### ISSUE THREAD

**Issue by rairafaqatali** [elsa-workflows/elsa-core#1528]
### Discussed in https://github.com/elsa-workflows/elsa-core/discussions/1526

<div type='discussions-op-text'>

<sup>Originally posted by **rairafaqatali** September 14, 2021</sup>
@sfmskywalker I have integrated Elsa in our existing project that was using Pascal Case for JSON responses. 
I got below error
![image](https://user-images.githubusercontent.com/52976818/133219285-083d250f-b5c6-45be-a449-2d73904731e4.png)

When I change JSON from Pascal to Camel it worked fine

Can you kindly let me know what change I need to do to support the pascal case for Elsa?</div>

**Comment by sfmskywalker** [comment]
My response copied from the discussion:

The JSON serializer settings that the Ela Server API uses come from the [IEndpointContentSerializerSettingsProvider](https://github.com/elsa-workflows/elsa-core/blob/master/src/server/Elsa.Server.Api/Services/IEndpointContentSerializerSettingsProvider.cs) service.

There are two things you could do:

1. Replace the service implementation in the service collection with your own (there's a `Replace<TService, TImplementation>` extension method you could use for that.
2. Submit a PR that updates the [EndpointContentSerializerSettingsProvider](https://github.com/elsa-workflows/elsa-core/blob/master/src/server/Elsa.Server.Api/Services/EndpointContentSerializerSettingsProvider.cs) implementation that takes an options object that provides the serializer configuration.
