### ISSUE TITLE
DbUpdateException in PostgresException: 23505: duplicate key value violates unique constraint "PK_WorkflowExecutionLogRecords"

### ISSUE THREAD

**Issue by JoschaMetze** [elsa-workflows/elsa-core#1529]
Running on latest master, slightly modified Elsa.Samples.Persistence.EntityFramework sample to start the workflow multiple times with multiple tasks.
I assume this is related to pooled entity framework resources that both try to save the same workflow log.
To reproduce:

Use the following code as a replacement for the Program.cs in the sample (and of course the postgres connection string) and start. Might take multiple executions, but occurs pretty reliable.

```using System;
using System.Threading.Tasks;
using Elsa.Persistence;
using Elsa.Persistence.EntityFramework.Core.Extensions;
using Elsa.Persistence.Specifications.WorkflowInstances;
using Elsa.Services;
using Microsoft.Extensions.DependencyInjection;
using Elsa.Persistence.EntityFramework.SqlServer;
using Elsa.Persistence.EntityFramework.PostgreSql;
using System.Collections.Generic;

namespace Elsa.Samples.Persistence.EntityFramework
{
    class Program
    {
        private static async Task Main()
        {
            // Create a service container with Elsa services.
            var services = new ServiceCollection()
                .AddElsa(options => options
                    // Configure Elsa to use the Entity Framework Core persistence provider using one of the three available providers 
                    .UseEntityFrameworkPersistence(ef =>
                    {
                        //ef.UseSqlite();
                        
                        ef.UsePostgreSql("Server=127.0.0.1;Port=5433;Database=elsa;User Id=postgres;Password=mysecretpassword;");

                        //ef.UseMySql("Server=localhost;Port=3306;Database=elsa;User=root;Password=password;");

                        //ef.UseSqlServer("Server=localhost;Database=Elsa;Integrated Security=true");
                    })
                    .AddConsoleActivities()
                    .AddWorkflow<HelloWorld>())
                .AddAutoMapperProfiles<Program>()
                .BuildServiceProvider();
            
            // Run startup actions (not needed when registering Elsa with a Host).
            var startupRunner = services.GetRequiredService<IStartupRunner>();
            await startupRunner.StartupAsync();

            // Get a workflow runner.
            var workflowRunner = services.GetRequiredService<IBuildsAndStartsWorkflow>();
            var tasks = new List<Task>();
            // Run the workflow.
            for (int i = 0; i < 100; i++)
            {
               tasks.Add(Task.Run(async () =>
                {
                    var runWorkflowResult = await workflowRunner.BuildAndStartWorkflowAsync<HelloWorld>();
                }));
            }
            await Task.WhenAll(tasks.ToArray());  
            //var workflowInstance = runWorkflowResult.WorkflowInstance!;

            // Get a reference to the workflow instance store.
            var store = services.GetRequiredService<IWorkflowInstanceStore>();

            // Count the number of workflow instances of HelloWorld.
            var count = await store.CountAsync(new WorkflowDefinitionIdSpecification(nameof(HelloWorld)));

            Console.WriteLine(count);
            
            //var loadedWorkflowInstance = await store.FindByIdAsync(workflowInstance.Id);
            //Console.WriteLine(loadedWorkflowInstance);
        }
    }
}

**Comment by JoschaMetze** [comment]
Might be related to #1331

**Comment by masdono** [comment]
Hi all, we have same error. We use Elsa 2.2.1 and YesSql persistence. Upgrading to 2.3 preview still produce more errors in our environment though.

**Comment by sfmskywalker** [comment]
I found out the issue, which is an ordinary race condition that happens within `WorkflowExecutionLog`.

It goes like this:

1. We have many tasks (100 in the example)
2. Each task does two things:
    1. Add a log entry to an in-memory collection.
    2. Save the in-memory collection into the database.

It is between the last two steps that the race condition occurs: multiple tasks might store the same set of records from the in-memory collection.

![image](https://user-images.githubusercontent.com/938393/133682733-a885b23c-4ef0-40a1-b499-22e6e5dbbe41.png)

I will need to somehow synchronize access. The interesting part is that the records are collected in one place of the system, and from another place the records get flushed into the DB. 

I will sleep on it :)

**Comment by sfmskywalker** [comment]
I just realized it’s even simpler. The problem is that the WorkfleExecutionLog service acts kind of like a singleton, because it’s a scoped service.

This means that if you created a child service scope within each task, the problem goes away.

But since the workflow runner already creates a child scope for each workflow execution, we might consider exposing the workflow execution log from the workflow context only. The downside is that I have to remove the workflow execution log service, which might break some folks’ code. But I doubt it’d be a big issue. Worst case they’d have to implement the service themselves if they need it outside the context of a workflow execution context.
