### ISSUE TITLE
Getting JSON Array from getVariable causes Object serialized to Array. JObject instance expected.

### ISSUE THREAD

**Issue by gerardlardizabal** [elsa-workflows/elsa-core#1536]
I'm storing a JSON Array object from an Http Request

![image](https://user-images.githubusercontent.com/20595488/133573814-3ea68942-8464-4c15-a492-dd2c3bab6798.png)

When i try to get or use the Json Array Variable from getVariable it throws the following error

![image](https://user-images.githubusercontent.com/20595488/133573672-908acb40-0bed-47a5-a5d7-a70f6f93a8b5.png)

Heres how i try to use the Json Array object

![image](https://user-images.githubusercontent.com/20595488/133574073-b2149922-3fe8-4e65-822c-2823e4619adc.png)

**Comment by sfmskywalker** [comment]
I'm unsure about your first step where you store the JSON object. I see a partial screenshot that shows a JSON string. Is the value stored as an actual string? What activity are you using here specifically?

The easiest way for me to look into this is if you could share a simple JSON workflow that demonstrates the issue. You probably could do it without using custom DTOs. If not, then a simple project setup that demonstrates the issue works too. Alternatively, a simple set of steps to reproduce the issue would help too.
