### ISSUE TITLE
Detected Package downgrade when I try to publish them to server. 

### ISSUE THREAD

**Issue by 1002527441** [elsa-workflows/elsa-core#1537]
Hi Team,
      I added reference project "Elsa.Core" and other activities component to my project, anyone met this kind of similar situation?
      I checked all errors, it all comes from Elsa.Core->Scrutor3.3.0, I don't know why and How to solve it.
regards
Henry

Error : Detected package downgrade: System.IO.FileSystem.Primitives from 4.3.0 to 4.0.1. Reference the package directly from the project to select a different version. 
 Elsa.Activities.Console -> Elsa.Core -> Scrutor 3.3.0 -> Microsoft.Extensions.DependencyModel 2.1.0 -> Microsoft.DotNet.PlatformAbstractions 2.1.0 -> System.IO.FileSystem 4.0.1 -> runtime.win.System.IO.FileSystem 4.3.0 -> System.IO.FileSystem.Primitives (>= 4.3.0) 
 
 Elsa.Activities.Console -> Elsa.Core -> Scrutor 3.3.0 -> Microsoft.Extensions.DependencyModel 2.1.0 -> Microsoft.DotNet.PlatformAbstractions 2.1.0 -> System.IO.FileSystem 4.0.1 -> System.IO.FileSystem.Primitives (>= 4.0.1)	TJExpense.Web

**Comment by sfmskywalker** [comment]
Hi Henry,

It think I might have messed up by omitting to update certain packages. I have bettered myself since and pushed a couple of updates. If you try and get the latest version from MyGet (ignore the 2.3.0-preview1 from NuGet - it's NOT the latest version anymore) then it should work better.

If not, let me know.

**Comment by 1002527441** [comment]
Hi  sfmskywalker, 
     thank you very much, the problem is fixed after I updated with  latest version from MyGet.


regards
Henry

**Comment by mohdali** [comment]
@sfmskywalker I stumbled upon the same issue when trying to publish a project in .NET 6 using win-x64 runtime.

Scrutor 4.x has explicit target for .NET 6 which helps avoid this issue. Would it be possible to bump Scrutor version up?
