### ISSUE TITLE
Designer Performance Issues - 12.5 secs to publish workflow | 30s to add a if/else activity

### ISSUE THREAD

**Issue by matt4446** [elsa-workflows/elsa-core#1543]
This might be something I need to run against an un-minified version as it's hard to grasp what is up to.

When I press the publish button it's very busy for 10 seconds: 
![image](https://user-images.githubusercontent.com/1550939/133637484-924f93ec-286f-4f33-97ac-cd7269a2c5fe.png)

Whereas the publish call takes 91-139ms after the rendering.

Similarly, if I add in an `if/else` activity to the middle of my workflow then there are two slow fairly similar repeated sections: 
 
![image](https://user-images.githubusercontent.com/1550939/133638531-a76fce35-796d-4972-8259-340fba5bc38c.png) 

This is the choose editor, dialog, enter details etc part:
![image](https://user-images.githubusercontent.com/1550939/133639681-4767599c-4554-4e6d-9b8b-fba914254a4d.png)

From 13.3~ is when the save button is pressed and it begins its animation frame  (taking a while to close and render)

**Comment by sfmskywalker** [comment]
Does it happen always, with any workflow, or just this one? Also, does it happen immediately when you enter the designer, or after a while?

**Comment by matt4446** [comment]
certainly worse for the longer ones. I'm not using the dashboard in this instance 

Loading that workflow the page has navigated to it at 3500 ms
![image](https://user-images.githubusercontent.com/1550939/133641036-c95e56cb-46ef-4004-8b0a-97289494b925.png)

**Comment by sfmskywalker** [comment]
So this is just the designer, embedded in your own application? I have not seen this type of behavior before. When did you first notice this issue, and also: against which version?

**Comment by matt4446** [comment]
Correct. It's thrown into a blazor server-side application so they might be arguing with each other. Slow is relative ;) 
I think I've become acclimatized to it only working in this scenario. When I switched to the dashboard version last week to create that context property lifecycle test it felt faster. 

New-workflow is pretty immediate 
It's probably been a bit slow since the c3 moved in. But I did not have the longer workflows going back then. 

This one for comparison takes ~2 seconds: 
![image](https://user-images.githubusercontent.com/1550939/133644961-0438f509-b7fe-4e1c-9e62-ae45bc03ca05.png)
![image](https://user-images.githubusercontent.com/1550939/133645051-5f14ed3d-22f8-4c85-8f52-1a9389310843.png)

let me go check on the dashboard version (same packages) with the same exported workflow

**Comment by matt4446** [comment]
same workflow but less rendering time (all out the box activities in this one) 

![image](https://user-images.githubusercontent.com/1550939/133646804-7acf596a-b459-4344-8363-a3d3f96ce927.png)

Adding a if/else in the dashboard version takes less time than the blazor version, but still a chunk of time 
![image](https://user-images.githubusercontent.com/1550939/133647623-d3e7a871-b083-4dbd-9aeb-34fbf9fd41ca.png)

**Comment by matt4446** [comment]
5x slower from one site to another, but why 😂 (both localhost, same machine, same workfow)

**Comment by matt4446** [comment]
I can then make it 2-5x times quicker by removing the sidebar (sidebar and nav). I'll have a play with flex to see if that might be causing it 

Publish: 
Same site (without sidebar and header) 
![image](https://user-images.githubusercontent.com/1550939/133650688-86386608-f3e2-4180-a0ad-da7c53ce0095.png)

Same site (with sidebar and header) 
![image](https://user-images.githubusercontent.com/1550939/133650827-240fe3d3-cb99-436b-b101-458cb8693011.png)

**Comment by sfmskywalker** [comment]
Such an odd problem. And you're saying the perf issue is not just with publishing, but anything you do, like opening activity editor modals and such?

**Comment by matt4446** [comment]
Correct, but nearly anything. Opening an activity is fast (including the start of adding a new one), closing it is not. The activity viewer is similarly sluggish in my scenario (I wonder if its related to that switch activity display bug). The problems include dragging the designer around to altering the activities in any way. Dragging the designer around is a bit sluggish too (it peaks its CPU resources going by the section in the performance recording) until I take away the sidebar. Both Applications are similarly high on resources for that dragging though ;). It could be some poorly written Flex I have above the designer that is causing layout to recalculate. I shall continue to dig once I finish some other work

**Comment by matt4446** [comment]
This seems to have fixed itself after upgrading to tailwindcss 3 in my solution. Curious. Well, it's about 3 or 4 seconds to add an activity on a complex one instead of the 30 odd seconds. Much, much better. 

> https://tailwindcss.com/docs/upgrade-guide
It's worth giving that a shot if you have your own tailwincss in your projects but have not upgraded it yet.

**Comment by sfmskywalker** [comment]
Good to know! Elsa 3 designer already uses tailwindcss 3, but sounds like it'd be worthwhile to upgrade the Elsa 2 designer as well 👍🏻
