### ISSUE TITLE
Get previous Activity Output with javascript syntax not work

### ISSUE THREAD

**Issue by NewHeight** [elsa-workflows/elsa-core#1546]
### Hi, 

- I try to create the user registration workflow with the latest elsa version, SignalReceived -> CreateUser -> SendEmail

![image](https://user-images.githubusercontent.com/8469179/133712680-bdc6a6fe-1db9-470e-8bda-df9f133f9c1f.png)

- CreatUser Activity's name was assigned CreateUser1

![image](https://user-images.githubusercontent.com/8469179/133712822-95fea2e4-bbfa-49a0-8747-da68131d67a3.png)

- In the SendEmail activity, I want to get email address from CreateUser activity with javascript expression  [`${activities.CreateUser1.UserInfo().Email}`] , but the javascript expression  throw an exception 

![image](https://user-images.githubusercontent.com/8469179/133712101-c1b4a872-b921-4e22-88db-4dbbb84b47d2.png)

![image](https://user-images.githubusercontent.com/8469179/133712017-f00dc5bb-b4ad-42ee-ac4e-4ebb8fde811c.png)

The CreateUser Activity code is following:
![image](https://user-images.githubusercontent.com/8469179/133713565-b3df17cd-ceff-4c15-bd82-b04f10fa8900.png)
And the workflow json file is following:
[user-registration.zip](https://github.com/elsa-workflows/elsa-core/files/7182105/user-registration.zip)

Did I do something wrong? Thanks.

**Comment by swuecho** [comment]
https://elsa-workflows.github.io/elsa-core/docs/expressions/expressions-javascript#activity-output-elsa-21

> For example, if you have an activity named MyActivity, you can access its output as follows: activities.MyActivity.Output().

**Comment by NewHeight** [comment]
@swuecho 

> Expression [`${activities.CreateUser1.Output().Email}`]  still get an error, 

![image](https://user-images.githubusercontent.com/8469179/133750525-63c58d89-8ffd-4e6e-b9d4-f3bd4b7750fe.png)

**Comment by NewHeight** [comment]
@swuecho , in CreateUser Activity, I defined an property named UserInfo decorated with attribute [ActivityOutput], so to access the output infos like Email, the javascript expression should be "activities.CreateUser1.UserInfo().Email" , was it right？

**Comment by sfmskywalker** [comment]
@NewHeight that's right. For some reason, the UserInfo property returns null. It's hard to see why this might be without actually running your workflow (including the custom activities).

If you can send a zip file including your project or a simplified version thereof that reproduces the issue, I can take a look.

**Comment by NewHeight** [comment]
@sfmskywalker , Hi , the following is the project zip file, the workflow json file is in it, it's a blazor server project, please have a look , Thanks.
[UserRegistration.zip](https://github.com/elsa-workflows/elsa-core/files/7189055/UserRegistration.zip)
