### ISSUE TITLE
Workflow JSON import doesn't select the specified persistence behavior

### ISSUE THREAD

**Issue by valsov** [elsa-workflows/elsa-core#1548]
When I export a workflow with a persistence behavior set to ```Activity executed```, and I import the JSON into Elsa (version 2.2.1), the persistence behavior is set to default ```Suspended``` instead of ```Activity executed```.

### First workflow to export:
![image](https://user-images.githubusercontent.com/17987048/133764516-4473785b-a2bc-48b7-a3f9-fc2d43744329.png)

### Exported JSON sample content:
```json
{
  "persistenceBehavior": "ActivityExecuted"
}
```
### Second workflow (imported from JSON):
![image](https://user-images.githubusercontent.com/17987048/133764980-0d65e45e-b8a3-4317-ac07-9ea260b499fa.png)

**Comment by sfmskywalker** [comment]
Nice catch. Thanks for reporting.
