### ISSUE TITLE
Editor intellisense disappears - given a particular context

### ISSUE THREAD

**Issue by matt4446** [elsa-workflows/elsa-core#1553]
I'm trying to create a fluent based activity for writing emails. 
- `addHeading("helloWorld").addParagraph("loremIpsum")` kind of thing

The setup is similar to the JavaScript Activity so that it evaluates the JS when the activity executes., which works fine. 

Using the notification hander to dd the TS to describe the object kind of works:
``` csharp
            output.AppendLine("declare function addHeading(heading:string): any;");
            output.AppendLine("declare function addBr(): any;");
            output.AppendLine("declare function addText(text:string): any;");
```

This is a good start: 
![image](https://user-images.githubusercontent.com/1550939/133986117-ae8d5fd5-7dce-49ba-a286-7a90ed490b11.png)

however, I've tried constricting it to the specific editor ... 
``` csharp
        public Task Handle(RenderingTypeScriptDefinitions notification, CancellationToken cancellationToken)
        {
            var output = notification.Output;
            var context = notification.Context;

            if (context != nameof(FluentEmailActivity))
            {
                return Task.CompletedTask;
            }
       .... 
```
The IntelliSense disappears. It does get past the `if` phase once but then it then comes back a few times more with a context value of null which then removes the IntelliSense it seems. Any ideas?

**Comment by sfmskywalker** [comment]
No idea, but I like what you're doing 😄 

Let me know if you figure it out. Otherwise I can take a look as well a little later.

**Comment by matt4446** [comment]
I'm sure i will at some point. I've hidden it away with `getEmail() : FluentEmail` as its much more tidy (and decorated). I have a feeling its something to do with multiple editors where they are sharing the intellisense, but that's just a guess. The context (`notification.Context`) is null so that is my first clue to go looking for it somewhen

**Comment by sfmskywalker** [comment]
@matt4446 I added some changes so that your code (with small modifications) will have the intended effect:

```csharp
public Task Handle(RenderingTypeScriptDefinitions notification, CancellationToken cancellationToken)
        {
            var output = notification.Output;
            var context = notification.Context;

            if (context.ActivityTypeName != nameof(FluentEmailActivity))
            {
                return Task.CompletedTask;
            }
```

**Comment by matt4446** [comment]
Fantastic. I'll give it a try somewhen when im back around workflows :)
