### ISSUE TITLE
WorkflowInstanceCanceller Cancel WorkflowInstance   `WorkflowCancelled` event should be posted

### ISSUE THREAD

**Issue by Nokecy** [elsa-workflows/elsa-core#1560]
https://github.com/elsa-workflows/elsa-core/blob/fbd8fe1b7953550a4e03a6fb725ea947cdf18b70/src/core/Elsa.Core/Services/Workflows/WorkflowInstanceCanceller.cs#L38

**Comment by sfmskywalker** [comment]
Good catch! Thanks for reporting 👍🏻
