### ISSUE TITLE
'Run Java Script' should be 'Run Javascript or Run JS'

### ISSUE THREAD

**Issue by swuecho** [elsa-workflows/elsa-core#1569]
https://github.com/elsa-workflows/elsa-core/blob/30ec4b20b5c5dd512f4c2e5f56355c9e6463ea23/src/scripting/Elsa.Scripting.JavaScript/Activities/RunJavaScript/RunJavaScript.cs#L23 add display name ?

![image](https://user-images.githubusercontent.com/666683/134607068-16be22bd-e7a6-4d21-a59d-770b8c4750ed.png)

**Comment by sfmskywalker** [comment]
Makes sense 👍🏻
