### ISSUE TITLE
Test workflow url path

### ISSUE THREAD

**Issue by jwillmer** [elsa-workflows/elsa-core#1575]
Workflows with an HTTP endpoint that are created as part of a test workflow execution (in the test menu) should use the path `.../test-workflows/WORKFLOW_NAME`. This allows us to have a static url for workflow tests. Currently we use the corelationID of a workflow to trigger when testing the workflow and we constantly need to update the url in our external client.

**Comment by sfmskywalker** [comment]
@jwillmer I believe this issue was resolved. Can you confirm?
