### ISSUE TITLE
misunderstanding system behaviour when starting workflows

### ISSUE THREAD

**Issue by misaqsaadat** [elsa-workflows/elsa-core#1584]
Hi

I think in method "FindStartableWorkflowAsync" there is different behavior of variables. more specifically I am talking about CorrelationId and tenantId.
both of them are nullable  strings and both have default value.
when I am using it as a consumer, I expect there should be same behavior with them when I don't supply them in method call.
but this is not what happen.
if I dont supply them, correlationId get a new GUID value. but tenantId will not change.
the problem is both correlationId and tenantId are using for locks. so when me as consumer don't supply it, system goes to some sort of deadlock. this happened to me. and I solve it after reading Elsa code and understand behavior.

this is obviously not a bug. but developers may take mistakes using the code.

locking with tenantId is in "CollectStartableWorkflowInternalAsync" method.

It might be a system "feature". but if it is not, it is better to some change.
1- add definition for method input varialbes.
or
2- remove default value from input variables.
or
3- set GUID as default value for tenantId.

sorry for my poor english

**Comment by sfmskywalker** [comment]
I see. I agree, in retrospect it doesn't seem to make much sense to generate a correlation ID when starting a new workflow. If the user wants to provide a correlation ID for the new workflow instance, then that's fine and they should provide a value. If not, the correlation ID will be generated when a workflow instance is created (which happens in a later stage).

I'll see if I can remove the auto-initialization of the `correlationId` parameter.

PS. Your English is fine ;)
