### ISSUE TITLE
Cannot establish connection - source does not exist

### ISSUE THREAD

**Issue by ziedunited92** [elsa-workflows/elsa-core#1589]
I use elsa workflow in my project .After designing my workflow, i save it and when i want to see it again i get this screen and this error on the console .
![Capturewf](https://user-images.githubusercontent.com/50137270/135238715-175d23fc-468f-4a86-91f0-0db9678d1a15.PNG)
I also added a checkbox named first step when i check it and save when i need to see it later i find it's not checked 
![Capturech](https://user-images.githubusercontent.com/50137270/135239476-785a687f-d3f7-47ed-b76d-f65d0855f763.PNG)

**Comment by ziedunited92** [comment]
@sfmskywalker can you help me please

**Comment by sfmskywalker** [comment]
Hi @ziedunited92 , I don't know why you're getting this error. What you could try is see if you get this error with a clean Elsa 1 setup (no custom code). Then apply your custom code (in as small a number of steps as possible) until you run into this issue again.

Additionally, or perhaps alternatively, clone the full repo and checkout the 1.4.x branch, build the client assets for the designer and set breakpoints. This will also make it easier to set breakpoints from the un-optimized code using the F12 developer tools.

In case you're just getting started with Elsa, I highly recommend to get started with Elsa 2 instead. Elsa 2 is under active development, while Elsa 1 is not.

**Comment by ziedunited92** [comment]
Thank you for your response but how can i use elsa designer 2 with angular? and please don't forget my additional question about the first step checkbox

**Comment by sfmskywalker** [comment]
You would use Elsa 2's designer the same way you wrap the Elsa 1 designer component.

Regarding the checkbox, this may not be an issue when you migrate to Elsa 2. Assuming you'll be creating custom activities using C#, you can simply declare a Boolean activity input property, and a functioning checkbox will be generated in the UI automatically.

**Comment by sfmskywalker** [comment]
I'm closing this issue because it's both related to Elsa 1, but please feel free to continue the discussion. Thanks for using Elsa!

**Comment by ziedunited92** [comment]
@sfmskywalker  I didn't create a custom activity i just used the fork activity and added a checkbox to it .But i will try it in Elsa 2.
I really thank you for having the time to answer me.
