### ISSUE TITLE
The request was canceled due to the configured HttpClient.Timeout of 100 seconds elapsing in 2.3.0

### ISSUE THREAD

**Issue by rairafaqatali** [elsa-workflows/elsa-core#1595]
### Discussed in https://github.com/elsa-workflows/elsa-core/discussions/1586

<div type='discussions-op-text'>

<sup>Originally posted by **rairafaqatali** September 28, 2021</sup>
Hi @sfmskywalker 
I have tried to set timeout with below way, but none of them worked. :
 `.AddHttpActivities(elsaSection.GetSection("Server").Bind, configureHttpClient: httpClientBuilder => httpClientBuilder.SetHandlerLifetime(TimeSpan.FromHours(10)))`

` .AddHttpActivities(elsaSection.GetSection("Server").Bind, configureHttpClient: httpClientBuilder => httpClientBuilder.ConfigureHttpClient(x => x.Timeout = TimeSpan.FromDays(1)))`

When I use send HTTP request activity, it throws **The request was canceled due to the configured HttpClient.Timeout of 100 seconds elapsing.**
Can you let me know what I'm missing?
 Is this issue resolved or still pending?

Kindly let me know.

Thanks</div>

**Comment by sfmskywalker** [comment]
Hi @rairafaqatali , please find my response in the discussion.
