### ISSUE TITLE
Unable to evaluate custom type Liquid Expressions

### ISSUE THREAD

**Issue by jayachandra21** [elsa-workflows/elsa-core#1599]
Hi @sfmskywalker,

Using Elsa 2.3, I have created two custom activities let say **Activity1**, **Activity2**. 

From **Activity1**, I have to pass the object data into **Actvity2**. 
So in the Activity1 my code is as follow:

```
List<Employee> lstdata = new List<Employee>();
 Employee objEmp = new Employee();
                objEmp.Id = 1;
                objEmp.Name = "John";
                objEmp.Salary = 20000;
                objEmp.Contactnumber = "123";
                lstdata .Add(objEmp);//Alm data is object data.
context.SetVariable("AlmData",  lstdata);
```
**In Activity2,**
Created a property as follow:
```
        public IList<Employee> DataList { get; set; } = new List<Employee>();
        protected override async ValueTask<IActivityExecutionResult> OnExecuteAsync(ActivityExecutionContext context)
        {
            string _outcome = OutcomeNames.Done;
            try
            {
                var data = DataList;
                if (data != null)
                {
                    Console.WriteLine("Data Records Count:" + data.Count);
                }
            }
            catch (Exception)
            {
                _outcome = "Error Occured";
            }
            return Outcomes(_outcome);
        }
```

In Workflow designer, In the Activity2 property configured as below
![image](https://user-images.githubusercontent.com/67507118/135856230-b9e14d35-f909-43e4-bd41-7cb31cca8ef3.png)

Though context variable has a values, but in the Activity2, property always returns "0" records.
Please guide me the right approach. 

 I have attached attached the project along with workflow below:

[LiquidExpression_CustomTypes.zip](https://github.com/elsa-workflows/elsa-core/files/7278174/LiquidExpression_CustomTypes.zip)

**Comment by sfmskywalker** [comment]
Hi @jayachandra21 ,

Thanks for the repro.

A couple of notes:

1. When using Liquid, keep in mind that it will simply try to render its contents into a string. In your example, it will render the .NET type name of the variable's value, which itself cannot be parsed into a list of `Employee`s.
2. You could, theoretically, render the `AlmData` as a JSON string (e.g. `{{ Variable.AlmData | json | raw }}`) and implement a `TypeConverter` for your list of emplyees that deserializes the JSON back into a strongly typed model.

But the easiest solution would be to just use the JavaScript syntax. JavaScript retains the original object, so no serialization/deserialization would be necessary.
