### ISSUE TITLE
Bug or Feature? - Two workflows with same url path crash both flows

### ISSUE THREAD

**Issue by Andale-online** [elsa-workflows/elsa-core#160]
SImple thing...

Create two workflows with ReiceiveHttpRequest and WriteHttpResponse...

Give both of them the same route url...

Both are unusable... Is this a bug or a feature :-D I mean - it ends up with "Response already started" which IMHO has no usable information for the workflow designer. Maybe need to test for duplicate routes or are duplicate routes wanted???

Greetings!

**Comment by sfmskywalker** [comment]
What should happen is that the first selected workflow should execute fine, and the other one should indeed fail if it also tries to send an HTTP response.

I think duplicate paths should be allowed regardless. Maybe one workflow will write a response, while another will kick off some timer or publish a message.

What does sound like a bug is that neither workflows will work if they start with the same URL. I'll look into that.

Thanks for reporting!

**Comment by sfmskywalker** [comment]
I just tried the scenario, and it does work as expected: 1 workflow succeeds, while the other one fails.

Let me know if you have a repro.

**Comment by Andale-online** [comment]
Err... Same result now. Don't know what i changed. Lets close this until someone else runs into something similiar. Sounds very specific to an "undocumented usage" ;-)

**Comment by sfmskywalker** [comment]
Fair enough 👍🏻
