### ISSUE TITLE
Docker image issue

### ISSUE THREAD

**Issue by Codewizard** [elsa-workflows/elsa-core#1606]
I am trying to test out ELSA workflows via the docker container as outlined in https://elsa-workflows.github.io/elsa-core/docs/next/quickstarts/quickstarts-elsa-and-docker

The container runs fine, but when I try to click the first tab, I get this..

![image](https://user-images.githubusercontent.com/8772196/136275106-598afa9d-0a07-43e0-bb5d-205650c31091.png)

When I click workflow registry the page comes up, but when I click "Create Workflow" I get this...

![image](https://user-images.githubusercontent.com/8772196/136275182-c06c2f43-7c68-44fb-8787-439b47a1b08e.png)

Do they just have a broken copy of the docker image or do I have something misconfigured? This is in the latest version of chrome BTW.

**Comment by Dibya90** [comment]
1. After Run docker run -t -i -e ELSA__SERVER__BASEURL='http://localhost:13000' -e ASPNETCORE_ENVIRONMENT='Development' -p 13000:80 elsaworkflows/elsa-dashboard-and-server:latest 
2. Webhook Definition is not showing.
3. I tried docker run -t -i -e ELSA__SERVER__BASEADDRESS='https://my-elsa-server.com' -p 13000:80 elsaworkflows/elsa-dashboard-and-server:latest   It's showing Webhook Definition but it's not working

Could you please share any proper docker cmd to get working all like Workflow Definition, Webhook Definition etc...

**Comment by Energiz0r** [comment]
@Dibya90 I guess you mean Workflow definitions :)

I tried your docker run command in my environment and it works great.
As I stated above I **have** to use **PowerShell** for it to work. cmd.exe doesn't work for me at all.

Have you tried using PowerShell?

**Comment by Dibya90** [comment]
Hi @Energiz0r 
Yeah, I tried using PowerShell, It's working fine with Workflow Definitions, Workflow Instances and Workflow Registry But Webhook Definitions is not showing.
![Capture](https://user-images.githubusercontent.com/93663745/140278411-a5aaa4ec-6a6e-4369-81d6-2c0cee7d4629.PNG)

I need docker run command which works for all including Webhook Definitions.

**Comment by sfmskywalker** [comment]
The Webhooks feature is an optional module that can be enabled. The current Docker build doesn't enable this, but if you create a feature request then we can add an option in the form of an ENV variable you would pass in when running the docker command to start the image to enable this feature.
