### ISSUE TITLE
WatchDirectory Activity not working

### ISSUE THREAD

**Issue by noxe** [elsa-workflows/elsa-core#1654]
Hi,

as discussed on Discord - it seems that the WatchDirectory Activity only works when defining an workflow in code.

But i cannot get it working for an workflow designed at runtime via Designer - the workflow is never executed / started?

**Comment by noxe** [comment]
cool thanks - seems like the builds are failing currently https://ci.appveyor.com/project/sfmskywalker/elsa/history

**Comment by noxe** [comment]
@sfmskywalker - thanks for the fix - i see it fires now after i create and publish an workflow at runtime in the designer.

but it does not start a new worfkow instance - should it? or i am missing something? Watch Directory is my start activity?

![image](https://user-images.githubusercontent.com/158478/143423857-dfbe5ab3-d2da-48ab-8233-47ae2b5ad87b.png)

**Comment by sfmskywalker** [comment]
It should be able to create new workflow instances when used as a starting activity. I will check to see why that's not happening.

**Comment by noxe** [comment]
thx - i only see that it does query the database on the Bookmark table - where activitytype is WatchDirectory - but i dont see any bookmark record in the database

**Comment by sfmskywalker** [comment]
Right, that makes sense. For starting activities, they are stored as triggers in memory, not in the database. Only for suspended workflows will these be stored as bookmarks in the database.

**Comment by noxe** [comment]
ok - so is this an bug currently?

**Comment by sfmskywalker** [comment]
Well, if it doesn't start new workflow instances when used as a starting activity, then that would be a bug.

However, I just tried but it works fine for me:
![directory-watcher](https://user-images.githubusercontent.com/938393/143436247-2c9da052-7043-406d-a875-257afc6f260c.gif)

**Comment by noxe** [comment]
hmm interessting - i am on latest preview from today :( will try once again after launch

**Comment by noxe** [comment]
i ust debugged the TriggerFinder - i see that the "WatchDirectory" is in the trigger stores - but it seems that the store has another Hash then the scoped hash - dont know what is going on here?

**Comment by noxe** [comment]
damn - just found the bug @sfmskywalker - i used *.* as pattern - which does not work then - because the FileSystemWatcher does change this to * - and so the bookmark is not found - because bookmark is stored as *.* - while the pattern * is used query the store:


        private void StartWorkflow(FileSystemWatcher watcher, FileSystemEventArgs e)
        {
            var changeTypes = e.ChangeType;
            var notifyFilter = watcher.NotifyFilter;
            var path = watcher.Path;
            var pattern = watcher.Filter;

            var model = _mapper.Map<FileSystemEvent>(e);
            var bookmark = new FileSystemEventBookmark(path, pattern, changeTypes, notifyFilter);

**Comment by noxe** [comment]
github seems to have problems with the patter - i used * . * in the workflow - but filewatcher does an *

**Comment by noxe** [comment]
maybe as workaround - add an if (pattern == "* . *") patter = *; in the StartWorkflow method?

**Comment by noxe** [comment]
i still hava a problem with this - when i change the pattern to * - i see the workflow instance is created - but the workflow is never executed - until i restart the server. the workflow instance is in Idle state - i use hangfire dispatcher - maybe related to this?

**Comment by noxe** [comment]
ok - seems like some kind of race condition - i see ObjectDisposedExceptrions happening - and so further processing stops - in the StartWorkflow method - there is an async method - shoudnt there be an await?

     _workflowLaunchpad.UseService(s => s.CollectAndDispatchWorkflowsAsync(launchContext, new WorkflowInput(model)));

from what i see code runs across this and disposes the current scope ? @sfmskywalker

**Comment by noxe** [comment]
This need to be changed to 

  _workflowLaunchpad.UseServiceAsync(async s => await s.CollectAndDispatchWorkflowsAsync(launchContext, new WorkflowInput(model)));

then everything works fine :)

**Comment by noxe** [comment]
created an PR for this - please take a look if this is the correct approach
