### ISSUE TITLE
RabbitMQ Activity

### ISSUE THREAD

**Issue by jwillmer** [elsa-workflows/elsa-core#1660]
New activity based on rebus:

As a user I like to set rabbit credentials in the activity, select an exchange I like to listen to and define headers (filters). I like to use the rabbit activity as a trigger to start my workflow.

![image](https://user-images.githubusercontent.com/1503577/138074592-56b535dc-871f-4584-9fb1-91d4ce07c468.png)

**Comment by constantine-v** [comment]
I suggest we have all 3 options (configuration in activity, in workflow settings, in application settings) and let user to choose which one to use. That way we could make UX a bit friendlier, allowing to specify connection string once per workflow or application, but also cover scenarios where single workflow needs to target multiple RabbitMQ hosts (thus, each activity should be able to provide it's own connection string).

![image](https://user-images.githubusercontent.com/77638996/141683677-89c19a91-6de7-449f-8bba-e13500d060ce.png)

**Comment by jwillmer** [comment]
@constantine-v sounds good but remember the task is about a first version. implementation speed is key.
