### ISSUE TITLE
Can't run Elsa Workflows Dashboard

### ISSUE THREAD

**Issue by zsanhong** [elsa-workflows/elsa-core#167]
I follow the instruction to Building & Running Elsa Workflows Dashboard
1、Clone the repository.
2、Run NPM install on all folders containing packages.json (or run node npm-install.js - a script in the root that recursively installs the Node packages)
3、Execute gulp build from the directory src\dashboard\Elsa.Dashboard\Theme\argon-dashboard
4、Open a shell and navigate to src/samples/Sample19 and run dotnet run.
Navigate to https://localhost:8632/elsa/home
every thing is ok,but I get nothing.

`>SET EF_CONNECTIONSTRING=Data Source=c:\data\elsa-dashboard.db;Cache=Shared

D:\newUseCode\elsa-core-develop\src\samples\Sample19>dotnet ef database update --context ElsaContext
Executing DbCommand [Parameters=[], CommandType='Text', CommandTimeout='30']
PRAGMA journal_mode = 'wal';
Executing DbCommand [Parameters=[], CommandType='Text', CommandTimeout='30']
CREATE TABLE "__EFMigrationsHistory" (
    "MigrationId" TEXT NOT NULL CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY,
    "ProductVersion" TEXT NOT NULL
);
Executing DbCommand [Parameters=[], CommandType='Text', CommandTimeout='30']
SELECT COUNT(*) FROM "sqlite_master" WHERE "name" = '__EFMigrationsHistory' AND "type" = 'table';
Executing DbCommand [Parameters=[], CommandType='Text', CommandTimeout='30']
SELECT "MigrationId", "ProductVersion"
FROM "__EFMigrationsHistory"
ORDER BY "MigrationId";
Applying migration '20191116105145_InitialCreate'.
Executing DbCommand [Parameters=[], CommandType='Text', CommandTimeout='30']
CREATE TABLE "WorkflowDefinitionVersions" (
    "Id" INTEGER NOT NULL CONSTRAINT "PK_WorkflowDefinitionVersions" PRIMARY KEY,
    "VersionId" TEXT NULL,
    "DefinitionId" TEXT NULL,
    "Version" INTEGER NOT NULL,
    "Name" TEXT NULL,
    "Description" TEXT NULL,
    "Variables" TEXT NULL,
    "IsSingleton" INTEGER NOT NULL,
    "IsDisabled" INTEGER NOT NULL,
    "IsPublished" INTEGER NOT NULL,
    "IsLatest" INTEGER NOT NULL
);
Executing DbCommand [Parameters=[], CommandType='Text', CommandTimeout='30']
CREATE TABLE "WorkflowInstances" (
    "Id" INTEGER NOT NULL CONSTRAINT "PK_WorkflowInstances" PRIMARY KEY,
    "InstanceId" TEXT NULL,
    "DefinitionId" TEXT NULL,
    "Version" INTEGER NOT NULL,
    "Status" TEXT NOT NULL,
    "CorrelationId" TEXT NULL,
    "CreatedAt" TEXT NOT NULL,
    "StartedAt" TEXT NULL,
    "FinishedAt" TEXT NULL,
    "FaultedAt" TEXT NULL,
    "AbortedAt" TEXT NULL,
    "Scopes" TEXT NULL,
    "Input" TEXT NULL,
    "ExecutionLog" TEXT NULL,
    "Fault" TEXT NULL
);
Executing DbCommand [Parameters=[], CommandType='Text', CommandTimeout='30']
CREATE TABLE "ActivityDefinitions" (
    "Id" INTEGER NOT NULL CONSTRAINT "PK_ActivityDefinitions" PRIMARY KEY,
    "ActivityId" TEXT NULL,
    "WorkflowDefinitionVersionId" INTEGER NULL,
    "Type" TEXT NULL,
    "Left" INTEGER NOT NULL,
    "Top" INTEGER NOT NULL,
    "State" TEXT NULL,
    CONSTRAINT "FK_ActivityDefinitions_WorkflowDefinitionVersions_WorkflowDefinitionVersionId" FOREIGN KEY ("WorkflowDefinitionVersionId") REFERENCES "WorkflowDefinitionVersions" ("Id") ON DELETE RESTRICT
);
Executing DbCommand [Parameters=[], CommandType='Text', CommandTimeout='30']
CREATE TABLE "ConnectionDefinitions" (
    "Id" INTEGER NOT NULL CONSTRAINT "PK_ConnectionDefinitions" PRIMARY KEY AUTOINCREMENT,
    "WorkflowDefinitionVersionId" INTEGER NULL,
    "SourceActivityId" TEXT NULL,
    "DestinationActivityId" TEXT NULL,
    "Outcome" TEXT NULL,
    CONSTRAINT "FK_ConnectionDefinitions_WorkflowDefinitionVersions_WorkflowDefinitionVersionId" FOREIGN KEY ("WorkflowDefinitionVersionId") REFERENCES "WorkflowDefinitionVersions" ("Id") ON DELETE RESTRICT
);
Executing DbCommand [Parameters=[], CommandType='Text', CommandTimeout='30']
CREATE TABLE "ActivityInstances" (
    "Id" INTEGER NOT NULL CONSTRAINT "PK_ActivityInstances" PRIMARY KEY AUTOINCREMENT,
    "ActivityId" TEXT NULL,
    "WorkflowInstanceId" INTEGER NULL,
    "Type" TEXT NULL,
    "State" TEXT NULL,
    "Output" TEXT NULL,
    CONSTRAINT "FK_ActivityInstances_WorkflowInstances_WorkflowInstanceId" FOREIGN KEY ("WorkflowInstanceId") REFERENCES "WorkflowInstances" ("Id") ON DELETE RESTRICT
);
Executing DbCommand [Parameters=[], CommandType='Text', CommandTimeout='30']
CREATE TABLE "BlockingActivities" (
    "Id" INTEGER NOT NULL CONSTRAINT "PK_BlockingActivities" PRIMARY KEY AUTOINCREMENT,
    "WorkflowInstanceId" INTEGER NULL,
    "ActivityId" TEXT NULL,
    "ActivityType" TEXT NULL,
    CONSTRAINT "FK_BlockingActivities_WorkflowInstances_WorkflowInstanceId" FOREIGN KEY ("WorkflowInstanceId") REFERENCES "WorkflowInstances" ("Id") ON DELETE RESTRICT
);
Executing DbCommand [Parameters=[], CommandType='Text', CommandTimeout='30']
CREATE INDEX "IX_ActivityDefinitions_WorkflowDefinitionVersionId" ON "ActivityDefinitions" ("WorkflowDefinitionVersionId");
Executing DbCommand [Parameters=[], CommandType='Text', CommandTimeout='30']
CREATE INDEX "IX_ActivityInstances_WorkflowInstanceId" ON "ActivityInstances" ("WorkflowInstanceId");
Executing DbCommand [Parameters=[], CommandType='Text', CommandTimeout='30']
CREATE INDEX "IX_BlockingActivities_WorkflowInstanceId" ON "BlockingActivities" ("WorkflowInstanceId");
Executing DbCommand [Parameters=[], CommandType='Text', CommandTimeout='30']
CREATE INDEX "IX_ConnectionDefinitions_WorkflowDefinitionVersionId" ON "ConnectionDefinitions" ("WorkflowDefinitionVersionId");
Executing DbCommand [Parameters=[], CommandType='Text', CommandTimeout='30']
INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20191116105145_InitialCreate', '3.0.0');
Done.`

`dotnet run
info: Microsoft.AspNetCore.DataProtection.KeyManagement.XmlKeyManager[0]
      User profile is available. Using 'C:\Users\zsh\AppData\Local\ASP.NET\DataProtection-Keys' as key repository and Windows DPAPI to encrypt keys at rest.
info: Microsoft.EntityFrameworkCore.Infrastructure[10403]
      Entity Framework Core 3.0.0 initialized 'ElsaContext' using provider 'Microsoft.EntityFrameworkCore.Sqlite' with options: MaxPoolSize=128
info: Microsoft.EntityFrameworkCore.Database.Command[20100]
      Executing DbCommand [Parameters=[], CommandType='Text', CommandTimeout='30']
      SELECT "w"."Id", "w"."DefinitionId", "w"."Description", "w"."IsDisabled", "w"."IsLatest", "w"."IsPublished", "w"."IsSingleton", "w"."Name", "w"."Variables", "w"."Version", "w"."VersionId", "a"."Id", "a"."ActivityId", "a"."Left", "a"."State", "a"."Top", "a"."Type", "a"."WorkflowDefinitionVersionId", "c"."Id", "c"."DestinationActivityId", "c"."Outcome", "c"."SourceActivityId", "c"."WorkflowDefinitionVersionId"
      FROM "WorkflowDefinitionVersions" AS "w"
      LEFT JOIN "ActivityDefinitions" AS "a" ON "w"."Id" = "a"."WorkflowDefinitionVersionId"
      LEFT JOIN "ConnectionDefinitions" AS "c" ON "w"."Id" = "c"."WorkflowDefinitionVersionId"
      ORDER BY "w"."Version" DESC, "w"."Id", "a"."Id", "c"."Id"
info: Microsoft.EntityFrameworkCore.Infrastructure[10403]
      Entity Framework Core 3.0.0 initialized 'ElsaContext' using provider 'Microsoft.EntityFrameworkCore.Sqlite' with options: MaxPoolSize=128
info: Microsoft.EntityFrameworkCore.Database.Command[20100]
      Executing DbCommand [Parameters=[@__activityType_0='?' (Size = 10)], CommandType='Text', CommandTimeout='30']
      SELECT "w"."Id", "w"."AbortedAt", "w"."CorrelationId", "w"."CreatedAt", "w"."DefinitionId", "w"."ExecutionLog", "w"."Fault", "w"."FaultedAt", "w"."FinishedAt", "w"."Input", "w"."InstanceId", "w"."Scopes", "w"."StartedAt", "w"."Status", "w"."Version", "a"."Id", "a"."ActivityId", "a"."Output", "a"."State", "a"."Type", "a"."WorkflowInstanceId", "b"."Id", "b"."ActivityId", "b"."ActivityType", "b"."WorkflowInstanceId"
      FROM "WorkflowInstances" AS "w"
      LEFT JOIN "ActivityInstances" AS "a" ON "w"."Id" = "a"."WorkflowInstanceId"
      LEFT JOIN "BlockingActivities" AS "b" ON "w"."Id" = "b"."WorkflowInstanceId"
      WHERE ("w"."Status" = 'Executing') AND EXISTS (
          SELECT 1
          FROM "BlockingActivities" AS "b0"
          WHERE (("w"."Id" = "b0"."WorkflowInstanceId") AND "b0"."WorkflowInstanceId" IS NOT NULL) AND ((("b0"."ActivityType" = @__activityType_0) AND ("b0"."ActivityType" IS NOT NULL AND @__activityType_0 IS NOT NULL)) OR ("b0"."ActivityType" IS NULL AND @__activityType_0 IS NULL)))
      ORDER BY "w"."CreatedAt" DESC, "w"."Id", "a"."Id", "b"."Id"
info: Microsoft.EntityFrameworkCore.Database.Command[20100]
      Executing DbCommand [Parameters=[@__activityType_0='?' (Size = 9)], CommandType='Text', CommandTimeout='30']
      SELECT "w"."Id", "w"."AbortedAt", "w"."CorrelationId", "w"."CreatedAt", "w"."DefinitionId", "w"."ExecutionLog", "w"."Fault", "w"."FaultedAt", "w"."FinishedAt", "w"."Input", "w"."InstanceId", "w"."Scopes", "w"."StartedAt", "w"."Status", "w"."Version", "a"."Id", "a"."ActivityId", "a"."Output", "a"."State", "a"."Type", "a"."WorkflowInstanceId", "b"."Id", "b"."ActivityId", "b"."ActivityType", "b"."WorkflowInstanceId"
      FROM "WorkflowInstances" AS "w"
      LEFT JOIN "ActivityInstances" AS "a" ON "w"."Id" = "a"."WorkflowInstanceId"
      LEFT JOIN "BlockingActivities" AS "b" ON "w"."Id" = "b"."WorkflowInstanceId"
      WHERE ("w"."Status" = 'Executing') AND EXISTS (
          SELECT 1
          FROM "BlockingActivities" AS "b0"
          WHERE (("w"."Id" = "b0"."WorkflowInstanceId") AND "b0"."WorkflowInstanceId" IS NOT NULL) AND ((("b0"."ActivityType" = @__activityType_0) AND ("b0"."ActivityType" IS NOT NULL AND @__activityType_0 IS NOT NULL)) OR ("b0"."ActivityType" IS NULL AND @__activityType_0 IS NULL)))
      ORDER BY "w"."CreatedAt" DESC, "w"."Id", "a"."Id", "b"."Id"
info: Microsoft.EntityFrameworkCore.Database.Command[20100]
      Executing DbCommand [Parameters=[@__activityType_0='?' (Size = 12)], CommandType='Text', CommandTimeout='30']
      SELECT "w"."Id", "w"."AbortedAt", "w"."CorrelationId", "w"."CreatedAt", "w"."DefinitionId", "w"."ExecutionLog", "w"."Fault", "w"."FaultedAt", "w"."FinishedAt", "w"."Input", "w"."InstanceId", "w"."Scopes", "w"."StartedAt", "w"."Status", "w"."Version", "a"."Id", "a"."ActivityId", "a"."Output", "a"."State", "a"."Type", "a"."WorkflowInstanceId", "b"."Id", "b"."ActivityId", "b"."ActivityType", "b"."WorkflowInstanceId"
      FROM "WorkflowInstances" AS "w"
      LEFT JOIN "ActivityInstances" AS "a" ON "w"."Id" = "a"."WorkflowInstanceId"
      LEFT JOIN "BlockingActivities" AS "b" ON "w"."Id" = "b"."WorkflowInstanceId"
      WHERE ("w"."Status" = 'Executing') AND EXISTS (
          SELECT 1
          FROM "BlockingActivities" AS "b0"
          WHERE (("w"."Id" = "b0"."WorkflowInstanceId") AND "b0"."WorkflowInstanceId" IS NOT NULL) AND ((("b0"."ActivityType" = @__activityType_0) AND ("b0"."ActivityType" IS NOT NULL AND @__activityType_0 IS NOT NULL)) OR ("b0"."ActivityType" IS NULL AND @__activityType_0 IS NULL)))
      ORDER BY "w"."CreatedAt" DESC, "w"."Id", "a"."Id", "b"."Id"
info: Microsoft.Hosting.Lifetime[0]
      Now listening on: http://localhost:8236
info: Microsoft.Hosting.Lifetime[0]
      Application started. Press Ctrl+C to shut down.
info: Microsoft.Hosting.Lifetime[0]
      Hosting environment: Development
info: Microsoft.Hosting.Lifetime[0]
      Content root path: D:\newUseCode\elsa-core-develop\src\samples\Sample19`

**Comment by sfmskywalker** [comment]
A few of observations:

1. I can't seem to find `npm-install.js` in the `develop` branch. Can you point me to it?
2. You do `SET EF_CONNECTIONSTRING=Data Source=c:\data\elsa-dashboard.db;Cache=Shared`, however `Sample19` uses the following connection string: `Data Source=c:\data\elsa.sample19.db;Cache=Shared`. Notice that they both point to a different DB file.

**Comment by zsanhong** [comment]
I also change the 
 "ConnectionStrings": {
        "Sqlite": "Data Source=c:\\data\\elsa-dashboard.db;Cache=Shared"
    } in appsettings.json, and I run the "npm install" in "D:\newUseCode\elsa-core-develop\src\dashboard\Elsa.Dashboard\Theme\argon-dashboard" fold,after that ,I run the "gulp build" cmd, there is no wrong msg.

**Comment by zsanhong** [comment]
It works,the address is  https://localhost:8236/elsa/home, not https://localhost:8632/elsa/home
thanks
