### ISSUE TITLE
Intellisense broken in 2.4 previews

### ISSUE THREAD

**Issue by noxe** [elsa-workflows/elsa-core#1670]
Hi,

as discussed on Discord - currently Intellisense is broken. You ca repro it with the https://github.com/elsa-workflows/elsa-guides/tree/master/src/ElsaDemos.DocumentManagement sample. I spent some hours in debugging this - and it seems it is caused by this commit here https://github.com/elsa-workflows/elsa-core/commit/743bfa0643c94a3562b976066fde040c2ba43087

seems like the ConfigureJavaScriptEngine now processes all named activities - meaning also those which are not related to the Http Activities - so it generates wrong? typescript code as it appends <T> to our custom activity types / classes and their proeprties. i think this class should only process Http activities?

**Comment by sfmskywalker** [comment]
@noxe Can you please remind me what the issue was again? I.e. what are you seeing that is different from what was expected?

**Comment by noxe** [comment]
i think this should help :)

https://www.screencast.com/t/2FMBZEeH3ju3

**Comment by sfmskywalker** [comment]
Ah, perfect 🙏🏻

**Comment by sfmskywalker** [comment]
Looks like intellisense has been restored (checking against master).

**Comment by noxe** [comment]
@sfmskywalker - did you test with the DocumentManagement repo - i really wonder why did would work now?

**Comment by sfmskywalker** [comment]
I haven't tried with that, just with the master branch. Many changes came in since, including a fix related to intellisense form another contributor.

**Comment by noxe** [comment]
yes i have seen that other fix - but this issue here is that the http things completly break the logic :) - but i can of course also test it once more the DocumentManagement repo later :)

**Comment by sfmskywalker** [comment]
Ah. I haven't tried anything with HTTP activities. I will give that a proper look :)

**Comment by noxe** [comment]
thx :)

**Comment by sfmskywalker** [comment]
I see now. That commit broke it good ;) Will fix.

**Comment by noxe** [comment]
cool :)

**Comment by sfmskywalker** [comment]
Looks good now, but please let me know if you're still seeing this issue.

**Comment by noxe** [comment]
perfect thank you 👌
