### ISSUE TITLE
RunScript Activity

### ISSUE THREAD

**Issue by sfmskywalker** [elsa-workflows/elsa-core#177]

**Comment by Andale-online** [comment]
What kinda script? C#?

**Comment by sfmskywalker** [comment]
This would depend on the available expression providers, but maybe we should separate "expression" from "scripts" and have a seprate `IScriptEvaluator`. There would be `JavaScriptEvaluator`, `PythonEvaluator`, `CSharpEvaluator`, `VBScriptEvaluator` etc.

**Comment by Andale-online** [comment]
i even dont like the expression expression for script :-D (got the joke, do you, do you?)

**Comment by randomchance** [comment]
I think PowerShell support would be a given, since it's so tightly coupled with dotnet. Also, it brings with it a huge ecosystem of tooling for system administration.

**Comment by sfmskywalker** [comment]
Elsa 2 has a RunJavaScript activity. More languages could be added as needed.
