### ISSUE TITLE
Allow turning off Jint's AllowClr function

### ISSUE THREAD

**Issue by jamesdoran** [elsa-workflows/elsa-core#179]
Would be great to have the ability to turn this off. 
Am I right in thinking this feature opens up some potential security issues?

**Comment by sfmskywalker** [comment]
Sure, we can expose this as a setting to the application host. It can certainly open up security issues, depending on who's using the application in what context.

**Comment by jamesdoran** [comment]
Can now be configured as follows:

```
new ServiceCollection()
    .AddElsa()
    .WithJavaScriptOptions(o => o.Configure(x => x.AllowClr = true))
```
