### ISSUE TITLE
Add lastExpressionResult() javascript function

### ISSUE THREAD

**Issue by jamesdoran** [elsa-workflows/elsa-core#180]
When activities are transitioning based on an expression, it's difficult to debug what's happened. In the case of the switch activity, there's a "default" case providing a catch-all. 

I'd like to be able to have access to the evaluated expression result for logging/debugging.

PR to follow/discuss

**Comment by sfmskywalker** [comment]
@jamesdoran I think I can close this, but please do reopen if there's still something there. Thanks!
