### ISSUE TITLE
Feature: Hangfire/Background process Integration

### ISSUE THREAD

**Issue by jruckert** [elsa-workflows/elsa-core#198]
It would be great if we could send workflow to a background job (especially for long running jobs). At the moment, i'm not aware of anyway that we could logically do this in the code.

**Comment by sfmskywalker** [comment]
Just trying to understand the use cases;

Do you mean to invoke a given workflow from a Hangfire job? Or maybe to kick off a background job from a workflow?

Or something else?

We have background tasks today that trigger workflows based in timers and incoming MassTransit messages.

What other scenarios do you have in mind that involve Hangfire?

**Comment by Diaskhan** [comment]
1.There is case that processes must lauch evere hour for example !
2.Or in workflow download some file and wait 30 minutes! After 30 minutes execute next activity !

**Comment by sfmskywalker** [comment]
Sure, but isn’t that the whole purpose of the Timer and Cron activities? These allow you to setup a workflow that execute every hour, and then for example download a file, then wait for 30 minutes, and then execute the next task.

I’m not sure what Hangfire would add regarding this. What Hangfire might add instead is a background task runner different from .NET Core’s background task type in that it would automatically support distributed locking (making sure that only one node in a web farm scenario executes). But then it might be overkill to use Hangfire just for that. Even more when we support multiple distributed lock providers like Workflow Core does.

**Comment by Diaskhan** [comment]
Could add demo or example using cron activities or timer ? 
I guesse author of issue didnt know this features!

**Comment by sfmskywalker** [comment]
Yes, great idea 👍🏻

**Comment by Diaskhan** [comment]
Sorry but am to dont know this features! 
Just exploring ure engine !

**Comment by sfmskywalker** [comment]
No worries, I meant: "Great idea, I will add an example" 😃

**Comment by sfmskywalker** [comment]
Elsa 2 now has a Hangfire provider for the Timer activities
