### ISSUE TITLE
Using YesSql data stores throws exception after first run

### ISSUE THREAD

**Issue by jamesdoran** [elsa-workflows/elsa-core#205]
When using YesSqlStores, it works on first run - tables are created. Subsequent runs cause following exception when Elsa tries to create the index tables again.

```
System.InvalidOperationException
  HResult=0x80131509
  Message=This SqlTransaction has completed; it is no longer usable.
  Source=Microsoft.Data.SqlClient
  StackTrace:
   at Microsoft.Data.SqlClient.SqlTransaction.ZombieCheck()
   at Microsoft.Data.SqlClient.SqlTransaction.Commit()
   at Elsa.Persistence.YesSql.StartupTasks.InitializeStoreTask.CreateTables()
   at Elsa.Persistence.YesSql.StartupTasks.InitializeStoreTask.ExecuteAsync(CancellationToken cancellationToken)
   at Elsa.Runtime.StartupRunner.<StartupAsync>d__2.MoveNext()
   ...
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.Run(IHost host)
   at StandaloneElsaDash.Program.Main(String[] args) in C:\Data\repos\StandaloneElsaDash\StandaloneElsaDash\Program.cs:line 16
```
Here's the setup from `Startup.ConfigureServices`:
```
var connectionString = "Data Source =.; Initial Catalog = Workflows; Integrated Security = True; MultipleActiveResultSets=True";

services.AddElsa(elsa => elsa.AddYesSqlStores(
            options => options
                        .UseSqlServer(connectionString, IsolationLevel.ReadUncommitted)
                        .UseDefaultIdGenerator()
                        .SetTablePrefix("Workflows_")
        ))
        .AddElsaDashboard();
```
What do you think about creating a SchemaVersion document to manage this so they only get created the first time or if further changes are required?

I'll push a new branch that just catches this exception for now.

**Comment by sfmskywalker** [comment]
Yes, I presume that's what Orchard Core does as well, in some form or another. Catching the exception is fine for now. Thanks!

**Comment by sfmskywalker** [comment]
Let me know if you want to implement the SchemaVersion document solution. Otherwise I'll pick it up eventually.

**Comment by petedavis** [comment]
Yeah in Orchard Core it is all handled by the Migration classes, and system maintains what has been run. 

eg: https://github.com/OrchardCMS/OrchardCore/blob/dev/src/OrchardCore.Modules/OrchardCore.Users/Migrations.cs

**Comment by jamesdoran** [comment]
I'll give it a crack. Hopefully over the weekend.
