### ISSUE TITLE
Enhancement:: Dynamic Activity resolving

### ISSUE THREAD

**Issue by Andale-online** [elsa-workflows/elsa-core#208]
No, this won't be another discussion about assemblies.

My goal would be to prevent the manual registration of activities (e.gUseHttpActivities)  . I mean: For every new activity I have to add it in MVC / asp. They all are added by their own extension methods. Wouldn't it be nice if these extension methods would be scannable and executable? So by default there's no more UseHttpActivities or equal in code - except you need to set up things manually.

**Comment by sfmskywalker** [comment]
For sure. You could already do this using e.g. [Scrutor](https://github.com/khellang/Scrutor).  Elsa.Dashboard uses this to automatically register available activities.

If we are going to do this for activities, we need to think about those activities that require certain dependencies. For example, the `SendEmail` activity requires the `ISmtpService`. If we were to allow the user automatically discover & register all `IActivity` implementations, it would not be obvious that they'd also need to register `ISmtpService`.

A solution might be to register default implementations that do nothing, and expose extension methods e.g. `ConfigureEmailActivities` that allows the user to configure the default `SmtpService` and configure it.

Thoughts?

**Comment by Andale-online** [comment]
Yes... Exactly what i thought of

**Comment by sfmskywalker** [comment]
Elsa 2 now has an `AddActivitiesFrom` extension method that registers all `IActivity` implementations from the specified set of assemblies
