### ISSUE TITLE
Remove MassTransit activity dependency on MassTransit.RabbitMQ

### ISSUE THREAD

**Issue by petedavis** [elsa-workflows/elsa-core#210]
Just thinking that the activities in the MassTransit module should be able to work on Azure service bus (or any transport that MassTransit supports), so the responsibility for creating a bus and wiring the consumers should not be part of the activity project.

This could be part of another project that can setup a bus and consumers for RabbitMQ or AzureSB etc for you.

However if you want to setup the bus and start it yourself, I have previously made some changes to make it simpler to connect workflow consumers into a bus that the application startup was responsible for setting up. This is used in the shopping cart sample. These "should" be using common abstractions in the MassTransit project and not be dependent on any particular transport.

**Comment by sfmskywalker** [comment]
100% agree.
