### ISSUE TITLE
Switch view  shows up correctly in designer| registry, but in the instance viewer the cases are disconnected.

### ISSUE THREAD

**Issue by RainerAtSpirit** [elsa-workflows/elsa-core#2407]
I've followed the steps outlined in https://github.com/elsa-workflows/elsa-core/issues/1447 by importing and executing the example switch.
From what I can see, the instance comes with the wrong casing over the wire. 

![image](https://user-images.githubusercontent.com/581644/138721317-16adb718-d518-40e9-8088-b116fa4c72f7.png)

Therefore the `switch-plugins` fails 

![image](https://user-images.githubusercontent.com/581644/138721469-f5db8647-5491-4be5-bb09-19d128d25ede.png)

This looks like a mismatch between a server and client model to me. So I didn't want to solve it in the `switch-plugin.tsx`.

**Comment by sfmskywalker** [comment]
Must be a mismatch between designer code in master branch and older 2.3.0 server release. When I try using master code (both server & client), it works fine on both workflow viewer as well as blueprint viewer.

**Comment by RainerAtSpirit** [comment]
Ok. I'll check back after the next server release.
Here's the temporary client-side fix we're using in the meantime (`switch-plugin.tsx`).

```typescript
      for(const c of cases){
        var fixCaseIssueWithName: string = c.name || (c as any).Name;
        outcomesHash[fixCaseIssueWithName] = true;
      }
````
