### ISSUE TITLE
Icons activities in instances 

### ISSUE THREAD

**Issue by Juandavi1** [elsa-workflows/elsa-core#2410]
Hello, 

I don't get the icon in the upper right of the activity 😢 
but if I click it, the info appears

![image](https://user-images.githubusercontent.com/18731612/138746924-1a18e29c-3589-46bb-a1f6-aa21727e6f13.png)

there are no errors in the console 😞 

![image](https://user-images.githubusercontent.com/18731612/138747227-f9b9739a-d902-4542-92b4-6ed4c80926d8.png)

our versions 

![image](https://user-images.githubusercontent.com/18731612/138747718-d3f1d5c9-9b16-4f91-9b6c-685b5035949d.png)

![image](https://user-images.githubusercontent.com/18731612/138748550-4ba34b2d-d04c-4d15-a2f6-bb76ee192746.png)

thanks 🙇‍♂️

**Comment by sfmskywalker** [comment]
Can you try to update the packages to the latest prerelease version (2.4.0-preview.349), clear your browser's cache and try again? 

If you're still not seeing the upper-right icon, please let me know.

**Comment by Juandavi1** [comment]
Hello, thanks for answering.

I did the update but now the designer does not load :( I have already tried on several computers

![image](https://user-images.githubusercontent.com/18731612/139873597-8f922d8e-b541-476b-bce4-6801f444a0f8.png)

![image](https://user-images.githubusercontent.com/18731612/139873669-e2c54443-0bd4-4933-b17d-3a36587511f5.png)

thanks

**Comment by Juandavi1** [comment]
I tried but dont works :( 
We are working with 2.4 version

**Comment by sfmskywalker** [comment]
That's odd. Any chance you can share with me a repro?
