### ISSUE TITLE
Oracle persistence problem in ELSA Version 2.3

### ISSUE THREAD

**Issue by akghasemi** [elsa-workflows/elsa-core#2416]
Hi,
in ELSA version 2.3 Oracle persistence ef core provider some columns changed to NVARCHAR(2000) from NCLOB which causes problem in columns which supposed to be big.at the same time these columns in SQL server are nvarchar(max) and in postgres are 'text', the only equivalent data type to these datatypes are NCLOB.
which also described here in this link:

[https://docs.microsoft.com/en-us/sql/relational-databases/replication/non-sql/data-type-mapping-for-oracle-publishers?view=sql-server-ver15](url)

otherwise if for example columns that keeps the workflow definition  extends from 2000 characters then the Oracle will return Error.
I am trying to upgrade Elsa in my project and now I hit this error because my workflow definition is too big,
is there a reason that this behavior changed in version 2.3?
I can provide a fast fix for this, if it is accepted as a bug

**Comment by sfmskywalker** [comment]
I'm not sure why it was changed to NVARCHAR(2000) from NCLOB, but if you can provide a fix for this then I will happily accept it. Thanks!

**Comment by akghasemi** [comment]
> I'm not sure why it was changed to NVARCHAR(2000) from NCLOB, but if you can provide a fix for this then I will happily accept it. Thanks!

Ok,I am trying to fix that but I am getting this error 
No coercion operator is defined between types 'System.String' and 'Elsa.Services.Models.WorkflowOutputReference
do you have any idea about this?
