### ISSUE TITLE
Intelisense proposes invalid properties

### ISSUE THREAD

**Issue by jwillmer** [elsa-workflows/elsa-core#2417]
I get the `activities` path displayed on all levels. Same with some other paths that should only be proposed on specific levels. I guess it is all the same problem so fixing `activities` should solve the others as well.

![image](https://user-images.githubusercontent.com/1503577/139071039-4be63550-3130-46fb-8164-2118dc8817c0.png)

**Comment by constantine-v** [comment]
Most likely this is a configuration issue, can be easily reproduced on [Monaco Editor Playground](https://microsoft.github.io/monaco-editor/playground.html):
![autocomplete](https://user-images.githubusercontent.com/77638996/139920716-1f956aea-29d8-4901-ac3f-f3a14c0ae66f.gif)
