### ISSUE TITLE
Elsa 2.3.0 Created the Dashboard project according to the documentation and ran it with the error

### ISSUE THREAD

**Issue by landonzeng** [elsa-workflows/elsa-core#2420]
I created the dashboard and Service project according to the documentation and ran it with the error: Unable to load the file or assembly 'Microsoft.EntityFrameworkCore. adb9793829ddae60'.
When I add "Microsoft.EntityFrameworkCore.Relational" to the project and run it again, it reports this error: "A schema "Elsa" has been set for an object of type "RenameTableOperation" with the name of "WorkflowInstances". MySQL does not support the EF Core concept of schemas. Any schema property of any "MigrationOperation" must be null. This behavior can be changed by setting the `SchemaBehavior` option in the `UseMySql` call.”

**Comment by sfmskywalker** [comment]
I just followed every step of [this quickstart](https://elsa-workflows.github.io/elsa-core/docs/next/quickstarts/quickstarts-aspnetcore-server-dashboard-and-api-endpoints) and did not get any error.

Make sure you are using .NET 5 SDK (`dotnet new web -n "ElsaQuickstarts.Server.DashboardAndServer" -f net5.0`) and you should be fine.

If not, please feel free to zip your solution and attach it to this issue so I can check it out.

**Comment by landonzeng** [comment]
> I just followed every step of [this quickstart](https://elsa-workflows.github.io/elsa-core/docs/next/quickstarts/quickstarts-aspnetcore-server-dashboard-and-api-endpoints) and did not get any errors.
> 
> Make sure you are using .NET 5 SDK (`dotnet new web -n "ElsaQuickstarts.Server.DashboardAndServer" -f net5.0`) and you should be fine.
> 
> If not, please feel free to zip your solution and attach it to this issue so I can check it out.

When I switch to a mysql database, I get the above error, but not if I use sqlite, nor YesSql.

**Comment by sfmskywalker** [comment]
Are you using the 2.3 packages from NuGet or latest builds from MyGet (2.4.x)? Odds are this issue with usage of schema has been fixed since.

**Comment by landonzeng** [comment]
> Are you using the 2.3 packages from NuGet or latest builds from MyGet (2.4.x)? Odds are this issue with usage of schema has been fixed since.

I'm using NuGet's 2.3 package

**Comment by landonzeng** [comment]
After upgrading to 2.3.0 the webhook definitions page also disappeared, is this cancelled? Although the previous version of webhook definitions did not implement the function

**Comment by sfmskywalker** [comment]
> I'm using NuGet 2.3 package

Can you try with 2.4.x from MyGet to see if the issue still exists?

**Comment by sfmskywalker** [comment]
> After upgrading to 2.3.0 the webhook definitions page also disappeared, is this cancelled? Although the previous version of webhook definitions did not implement the function

Let's open a separate question (discussion)? Then we can keep this issue focused on the original issue you opened 😄 
Thanks!
