### ISSUE TITLE
HTTP activity issue

### ISSUE THREAD

**Issue by jwillmer** [elsa-workflows/elsa-core#2427]
I receive a JSON payload in my HTTP activity and also set the JSON schema. When accessing the data in a JS activity I need to transform the data from raw. Using just the body does not give me a valid JS object. My workflow fails as soon as I try to access the `body`with `Cannot convert undefined or null to object`

```
// not working
//const body = activities.webhook.Output().Body;

// working
const raw = activities.webhook.Output().RawBody;
const body = JSON.parse(raw);
```

**Comment by sfmskywalker** [comment]
Thanks for that! I just tried this scenario with latest code, and it works nicely now (both methods).
