### ISSUE TITLE
How to modify the style and content of the project

### ISSUE THREAD

**Issue by landonzeng** [elsa-workflows/elsa-core#2434]
How to modify the style and content of the project, I checked the source code and did not find a page style file that can be modified

**Comment by sfmskywalker** [comment]
Indeed, the dashboard app wasn't designed with theme-ability in mind. However, you can still just include a custom CSS and target specific and/or generic HTML elements to modify their appearance such as fonts, colors etc.

If you need to target specific HTML elements for which no ID or specific CSS class is provided, then please feel free to submit a PR that adds this.
