### ISSUE TITLE
Elsa 2.3  Workflow Context Type Input Value Not Saved

### ISSUE THREAD

**Issue by baraanaser** [elsa-workflows/elsa-core#2435]
Hi,
I try to add the type of workflow context in the input field but it does not save , when i return to the settings again it's empty.

https://prnt.sc/1y1eddm
https://prnt.sc/1y1eknr

Thanks

**Comment by sfmskywalker** [comment]
1. Make sure the provided typename actually exists.
2. If so, it might be a bug in 2.3 in which case it should be fixed in 2.4 preview (available from MyGet).

If not, please feel free to send me a repro (it works for me, so an example demonstrating the issue would help).
