### ISSUE TITLE
How to unit test Activities?

### ISSUE THREAD

**Issue by wakuflair** [elsa-workflows/elsa-core#244]
I dont' want to use workflow stuff, just test an activity.

I searched the repo, but no test code founded.

**Comment by sfmskywalker** [comment]
You should be able to instantiate your activity and then call its `ExecuteAsync` method, but I do realize it might be less than straightforward to instantiate the `WorkflowExecutionContext`. Writing tests is on my list of things to do, so I will make sure to include proper unit tests for the activities that come with Elsa out of the box.

**Comment by PeterLaComb-Availity** [comment]
I have been thinking about tests for Elsa a lot lately, and I think the value provided by covering the Core of Elsa with test is significant, I will likely put up a PR against this issue in the next few weeks.

Is there a preference for test framework? NUnit, XUnit, Other?

**Comment by sfmskywalker** [comment]
100% agree about the value of having tests covering the core. I do recommend doing so for Elsa 2 however, as Elsa 1 is currently in maintenance mode. Not to say that tests are useless for projects under maintenance of course.

**Comment by PeterLaComb-Availity** [comment]
Understood. I'll focus on the 2.0 branch. Perhaps we can back-port some of the result if there is value.

**Comment by sfmskywalker** [comment]
Much appreciated!
