### ISSUE TITLE
Workflow stuck in suspended state if timer elapsed when server is down

### ISSUE THREAD

**Issue by OvyDev** [elsa-workflows/elsa-core#2443]
I ran a workflow containing timer activity. When timer activity was hit, it scheduled resumption at certain time "x". The server was not running at that time "x" and now this workflow instance stuck in suspended state. Is there any way we can resume it?

**Comment by sfmskywalker** [comment]
Do you have a sample workflow that I can use to reproduce this behavior?

**Comment by OvyDev** [comment]
My workflow is just a custom activity followed by timer. 
I failed to reproduce it, I guess it must be something else.

 Thanks for the response.
