### ISSUE TITLE
Should it be possible to work with array methods on a globally defined variable?

### ISSUE THREAD

**Issue by RainerAtSpirit** [elsa-workflows/elsa-core#2447]
### Discussed in https://github.com/elsa-workflows/elsa-core/discussions/2446

<div type='discussions-op-text'>

<sup>Originally posted by **RainerAtSpirit** November  3, 2021</sup>
Here's a simple console use case:

```javascript
let TestArray = [{test: 123}]
TestArray.push({"test": 123})
TestArray = [...TestArray, {"test2": 234}]
TestArray = TestArray.concat([{"test3": 456}])
JSON.stringify(TestArray) // '[{"test":123},{"test":123},{"test2":234},{"test3":456}]'
```

When trying to do the same in a workflow, the `TestArray` variable won't get updated. 

![image](https://user-images.githubusercontent.com/581644/140048698-4aa2fc4c-f3f1-42b1-b537-d659aeadbf74.png)

**Definition:**

![image](https://user-images.githubusercontent.com/581644/140048780-4890d100-29e1-49cc-b96e-50efc910e8ff.png)

![image](https://user-images.githubusercontent.com/581644/140048808-7e223a1a-1a6e-4d88-98f3-61532e5fd1e0.png)

**DefinitionExport:**

[array-push-issue.zip](https://github.com/elsa-workflows/elsa-core/files/7467068/array-push-issue.zip)

</div>

**Comment by RainerAtSpirit** [comment]
I'd think that advocating using `setVariable` and `getVariable` is a straightforward solution. It just requires updating the documentation.

**Comment by sfmskywalker** [comment]
Yeah. But if we want to keep the ability to access workflow variables "directly", then it should work intuitively. Otherwise, I'd rather remove the feature to avoid confusion. But I'm not sure we should remove it yet. Maybe someone can convince me :)

**Comment by tomy2105** [comment]
First, what worries me is the "backward compatibility" breaking. Accessing variable values directly worked ok so far and if you remove this capability you are breaking backward compatibility.
Setting them to some value obviously didn't work at all so you are free to choose another path for setting without fear of breaking anything.

And one question more here. We are talking ONLY about workflow variables (ones "defined" in variables part of workflow) and not about accessing activity output/output properties (which suffered from new way of doing in Elsa 2.1 :))?

**Comment by sfmskywalker** [comment]
We won't break anything here because you will still be able to use variables in te same way :)

However, we will simply stop advertising it and instead document usage of `setVariable` and `getVariable`.

> We are talking ONLY about workflow variables (ones "defined" in variables portion of designer) and not about accessing activity output/output properties

Exactly.

> (which suffered from new way of doing in Elsa 2.1 :))

Sorry :)

> Or you are talking about all variables introduced with SetVariable activity?
It's the same - whether you define variables via the workflow variables settings panel or via the SetVariable activity, both methods will have the effect of adding/setting a workflow variable in the workflow instance (in its `Variables` field).
