### ISSUE TITLE
approve-reject and get data dynamically via postman

### ISSUE THREAD

**Issue by fthmlymz** [elsa-workflows/elsa-core#2449]
Hello there,

I have created a workflow as below in elsa designer. I'm posting json through this workflow postman. Then I send json again for "**Approve**".

But I cannot read the information I sent for approval and send it via e-mail. can you show me how to do this?

[activities.SignalReceived.Output().toMail]
[activities.SignalReceived.Output().toList.newUser]

Scheme
[https://easyupload.io/dact9i](url)

Create document
[https://localhost:2001/v1/documents](url)

     {
       "Id": "100",
       "Author": {
         "Name": "John",
         "Email": "john@gmail.com",
         "BusinessCode": "42",
         "FirstApprove": "firstapprove@hotmail.com"
       }
       "Body": "sample document."
     }

[https://localhost:2001/v1/signals/Approve/execute](url)

     {
       "workflowInstanceId": "f2da47fb8dab492f88d06e93a74a106a",
       "correlationId": "e3d00ec536e14dab96045810c58ac955",
       "input": "",
       "toMail": "mail@hotmail.com",
       "toList": [ {"newUser": "deneme@gmail.com"}]
     }

![error](https://user-images.githubusercontent.com/87203103/140301998-562891b2-9445-4fea-8958-01681d2b0d06.PNG)

**Comment by fthmlymz** [comment]
https://ufile.io/93wtccft


You can download the file from this address.
I did as you said, but I want to send a syntax and get the element in the array I sent.

**Comment by OvyDev** [comment]
you can send object in input when triggering Signal, for example:
```
{
    "workflowInstanceId": "f2da47fb8dab492f88d06e93a74a106a",
    "correlationId": "e3d00ec536e14dab96045810c58ac955",
    "input": 
    { 
        "mailTo": ["mail@hotmail.com"],
        "body": "This was sent in Signal" 
    }      
}
```
note that `mailTo` is an array of string. 
You can then set `Send Email` properties using `input.mailTo` and `input.body`.
