### ISSUE TITLE
Remove System.Data.SqlClient from Elsa.DistributedLocking.SqlServer

### ISSUE THREAD

**Issue by matt-psaltis** [elsa-workflows/elsa-core#2457]
The underlying DistributedLock.SqlServer uses Microsoft.Data.SqlClient as defined here: https://github.com/madelson/DistributedLock/blob/master/DistributedLock.SqlServer/DistributedLock.SqlServer.csproj#L44

Can we remove the package reference to System.Data.SqlClient? This causes issues when trying to add Elsa to an asp.net project which already uses Microsoft.Data.SqlClient

**Comment by sfmskywalker** [comment]
Looks like we can do that.

**Comment by sfmskywalker** [comment]
Closed with d4e5fd15bcd9246c10ec28d745782fbdb36d32f4
