### ISSUE TITLE
Switch to tenant database for tenant workflows

### ISSUE THREAD

**Issue by nchancp** [elsa-workflows/elsa-core#2462]
We are trying to integrate elsa workflow to abp.io project in a multitenant set up. It works perfectly for host workflows. But for tenants, it uses the host database instead of the tenant database. Is there any way to configure to use tenant database when logged in as a tenant user? We tried configuring context factory, but it is not getting invoked.

**Comment by sfmskywalker** [comment]
I don't have any experience with ABP, so I'm not sure what you need to do. But if you happen to know what aspects of Elsa you would need to configured differently, please let me know.

**Comment by nchancp** [comment]
Can you please help with the elsa configuration to implement this?
Following is the configuration we have now. We have created ElsaWorkflowContext extending from ElsaContext. 
<img width="597" alt="image" src="https://user-images.githubusercontent.com/72537775/142977901-4f7c7b37-773e-46b8-a97c-24a7dddf668e.png">
We tried to modify to use a factory instead  in order to switch connection string at runtime. But the factory is not getting invoked.
<img width="550" alt="image" src="https://user-images.githubusercontent.com/72537775/142983116-21e38f82-9d10-46e7-8164-c5e9dad2e757.png">
Is there any other configuration we have to implement to make this working?

**Comment by sfmskywalker** [comment]
I don't think you can replace the `IDbContextFactory` service within that lambda, because it is invoked like this:

```csharp
elsa.Services.AddDbContextFactory<TElsaContext>(configure, serviceLifetime); // The `configure` variable is your lambda.
```

Which means that your lambda is trying to replace a service that is not yet registered with the service container.

What you could try is to create your own version of `UseNonPooledEntityFrameworkPersistence` so that you control what factory gets registered. Example:

```csharp
public static ElsaOptionsBuilder UseNonPooledEntityFrameworkPersistence(ElsaOptionsBuilder elsa)
{
    elsa.Services.AddDbContextFactory<ElsaWorkflowContext, ElsaWorkflowContextFactory>(configure, ServiceLifetime.Singleton);

    elsa.Services
        .AddSingleton<IElsaContextFactory, ElsaContextFactory<ElsaWorkflowContext>>()
        .AddScoped<EntityFrameworkWorkflowDefinitionStore>()
        .AddScoped<EntityFrameworkWorkflowInstanceStore>()
        .AddScoped<EntityFrameworkWorkflowExecutionLogRecordStore>()
        .AddScoped<EntityFrameworkBookmarkStore>();

    return elsa
        .UseWorkflowDefinitionStore(sp => sp.GetRequiredService<EntityFrameworkWorkflowDefinitionStore>())
        .UseWorkflowInstanceStore(sp => sp.GetRequiredService<EntityFrameworkWorkflowInstanceStore>())
        .UseWorkflowExecutionLogStore(sp => sp.GetRequiredService<EntityFrameworkWorkflowExecutionLogRecordStore>())
        .UseWorkflowTriggerStore(sp => sp.GetRequiredService<EntityFrameworkBookmarkStore>());
}
```

**Comment by nchancp** [comment]
Hi, it worked and the "ElsaWorkflowContextFactory" is getting invoked now except when the WorkflowRegistry methods are invoked. 
workflowDefinitionStore.FindManyAsync gives me the workflows stored in the tenant database now. But workflowRegistry.FindManyAsync retrieves the workflows in the host database. Is it possible to configure workflowregistry to retrieve data from the tenant database?

**Comment by sfmskywalker** [comment]
I'm afraid the workflow registry service is not tenant-aware. What you might try however is create a custom implementation of `IWorkflowRegistry` that knows about the current tenant context. You then load in only the workflow definitions for that tenant.

**Comment by nchancp** [comment]
I have created a custom implementation of workflow registry and it is reading from the tenant database now. I also had to modify  "ExecuteWorkflowDefinitionRequestConsumer" to set the tenant id from the message to abp context and use workflowLaunchpad.CollectAndExecuteWorkflowsAsync directly to trigger the signal instead of using Signaler. Thank you so much for the support. Will multitenancy be implemented in Elsa soon?

**Comment by sfmskywalker** [comment]
Glad to hear you got it to work, very nice.

Multitenancy is still on the backlog, so it's hard to say when it will be completed. Priorities are mostly driven by customers who need a certain set of features. I know of one partner who needs multitenancy in the near future, so with luck we will not wait for too long.
