### ISSUE TITLE
net6 update get error

### ISSUE THREAD

**Issue by yutao815** [elsa-workflows/elsa-core#2464]
I update to net6,then get a error.
System.MissingMethodException: Method not found: 'System.Type Microsoft.EntityFrameworkCore.Metadata.ITypeBase.get_ClrType()'.
Maybe need to update efcore to 6,thanks.

**Comment by slwcsf** [comment]
一样的问题

**Comment by maelmahdy86** [comment]
Same issue here, any support ?

**Comment by sfmskywalker** [comment]
Related issue: #2501

**Comment by sfmskywalker** [comment]
Fixed with 4933a2e81e1c88546f482bf9a82388f0060ac69d
