### ISSUE TITLE
NU1608 Warning with net6

### ISSUE THREAD

**Issue by noxe** [elsa-workflows/elsa-core#2470]
Hi - when building with net6 - you get a build warning about Rebus.ServiceProvider 6.4.1 - since it has an dependency < 6.0.0

warning NU1608: Erkannte Paketversion außerhalb der Abhängigkeitseinschränkung: "Rebus.ServiceProvider 6.4.1" erfordert Microsoft.Extensions.DependencyInjection.Abstractions (>= 2.0.0 && < 6.0.0), aber es wurde Version Microsoft.Extensions.DependencyInjection.Abstractions 6.0.0 aufgelöst.

**Comment by noxe** [comment]
Seems to be related to this https://github.com/rebus-org/Rebus.ServiceProvider/commit/2b74f192efff4eed174d2ebdae1dd7ba19681acf

**Comment by taurisjoe** [comment]
Hi guys,  
Just a heads up this warning is back in .NET 7:

```
warning NU1608: Detected package version outside of dependency constraint: Rebus.ServiceProvider 7.0.0 requires Microsoft.Extensions.Hosting.Abstractions (>= 3.0.0 && < 7.0.0) but version Microsoft.Extensions.Hosting.Abstractions 7.0.0 was resolved.
```
