### ISSUE TITLE
Custom tabs and v2.3.x

### ISSUE THREAD

**Issue by MichaelPetrinolis** [elsa-workflows/elsa-core#2477]
Thanx for this great project!

in v2.3.x the event 'activity-editor-displaying' was replaced by 'activity-editor-appearing'. 

The new event arguments do not contain the tabs property, so the CustomActivityEditorPlugin example in index.html does not work.

Is there a way to provide a custom view for an activity in 2.3.0 ?

BR

**Comment by sfmskywalker** [comment]
Great catch. I added a new `activity-editor.rendering` event and update the `CustomActivityEditorPlugin ` plugin to demonstrate its usage.

There's no option to provide a custom view for an activity icon 2.3, but we can certainly add it to 2.4. Feel free to open a separate issue for that.

**Comment by MichaelPetrinolis** [comment]
Thank you Sipke! Great work!
