### ISSUE TITLE
how can SendhttpRequest Advanced's authorization get input.Headers.Authorization again?

### ISSUE THREAD

**Issue by landonzeng** [elsa-workflows/elsa-core#2478]
After upgrading the project to 2.3.0, how can SendhttpRequest Advanced's authorization get input.Headers.Authorization again?
In version 2.2.0 it was possible to get the authentication information in the request context, but not anymore

**Comment by landonzeng** [comment]
After upgrading the project to 2.3.0, all SendhttpRequest requests are unsuccessful and return a blank html page.

**Comment by landonzeng** [comment]
Has anyone encountered this problem?

**Comment by sfmskywalker** [comment]
Can you send me a repro? When I setup a workflow server with the same activities, I get the expected `<h1>Hello !</h1>` response.

**Comment by landonzeng** [comment]
This is my json file
`{
  "$id": "1",
  "definitionId": "a39994efd26b48659afcd24a9e1d23d1",
  "versionId": "f6cf3397afc84f3b922ad8334900961f",
  "version": 1,
  "variables": {
    "$id": "2",
    "data": {}
  },
  "customAttributes": {
    "$id": "3",
    "data": {}
  },
  "isSingleton": false,
  "persistenceBehavior": "WorkflowBurst",
  "deleteCompletedInstances": false,
  "isPublished": true,
  "isLatest": true,
  "activities": [
    {
      "$id": "4",
      "activityId": "3f616203-596b-40f0-8072-4140bc2becb1",
      "type": "HttpEndpoint",
      "displayName": "HTTP Endpoint",
      "persistWorkflow": false,
      "loadWorkflowContext": false,
      "saveWorkflowContext": false,
      "properties": [
        {
          "$id": "5",
          "name": "Path",
          "expressions": {
            "$id": "6",
            "Literal": "/test"
          }
        },
        {
          "$id": "7",
          "name": "Methods",
          "expressions": {
            "$id": "8",
            "Json": "[\"GET\"]"
          }
        },
        {
          "$id": "9",
          "name": "ReadContent",
          "expressions": {
            "$id": "10",
            "Literal": "true"
          }
        },
        {
          "$id": "11",
          "name": "TargetType",
          "expressions": {
            "$id": "12"
          }
        },
        {
          "$id": "13",
          "name": "Schema",
          "syntax": "Literal",
          "expressions": {
            "$id": "14",
            "Literal": ""
          }
        },
        {
          "$id": "15",
          "name": "Authorize",
          "expressions": {
            "$id": "16"
          }
        },
        {
          "$id": "17",
          "name": "Policy",
          "expressions": {
            "$id": "18"
          }
        }
      ],
      "propertyStorageProviders": {}
    },
    {
      "$id": "19",
      "activityId": "53092434-6ed5-4725-b370-a625536ac4db",
      "type": "WriteHttpResponse",
      "displayName": "HTTP Response",
      "persistWorkflow": false,
      "loadWorkflowContext": false,
      "saveWorkflowContext": false,
      "properties": [
        {
          "$id": "20",
          "name": "Content",
          "expressions": {
            "$id": "21",
            "Literal": "<h1>hello!</h1>"
          }
        },
        {
          "$id": "22",
          "name": "ContentType",
          "expressions": {
            "$id": "23"
          }
        },
        {
          "$id": "24",
          "name": "StatusCode",
          "expressions": {
            "$id": "25"
          }
        },
        {
          "$id": "26",
          "name": "CharSet",
          "expressions": {
            "$id": "27"
          }
        },
        {
          "$id": "28",
          "name": "ResponseHeaders",
          "expressions": {
            "$id": "29"
          }
        }
      ],
      "propertyStorageProviders": {}
    }
  ],
  "connections": [
    {
      "$id": "30",
      "sourceActivityId": "3f616203-596b-40f0-8072-4140bc2becb1",
      "targetActivityId": "53092434-6ed5-4725-b370-a625536ac4db",
      "outcome": "Done"
    }
  ],
  "id": "f6cf3397afc84f3b922ad8334900961f"
}`

**Comment by sfmskywalker** [comment]
Thanks. I just tested it with the latest code (from master using the `Elsa.Samples.Server.Host` project), and it works fine when I try your workflow:

![image](https://user-images.githubusercontent.com/938393/143234793-02082fa2-a745-45b0-acaa-08af4d77282d.png)

**Comment by landonzeng** [comment]
Ok, I'll try again, thank you very much for your answer
