### ISSUE TITLE
I am using *SendHttpRequest* activity (named as activity1) to call an API that returns json data. here is the expression I am using to view the json data returned.

### ISSUE THREAD

**Issue by absolutesolutions** [elsa-workflows/elsa-core#2479]
I am using *SendHttpRequest* activity (named as activity1) to call an API that returns json data. here is the expression I am using to view the json data returned. 
```{{Activities.activity1.ResponseContent | json}}``` 
It returns following json data
```
{
  "hodId": 0,
  "id": 1,
  "code": "BR001",
  "desc": "Information Technology"
}
```
but if I try to access **desc** attributes with following expression ```{{Activities.activity1.ResponseContent.desc}}``` it returns *empty* string.

What am I missing?

_Originally posted by @absolutesolutions in https://github.com/elsa-workflows/elsa-core/discussions/2466_

**Comment by sfmskywalker** [comment]
See: https://github.com/elsa-workflows/elsa-core/discussions/2466#discussioncomment-1684426
