### ISSUE TITLE
Elsa 1 (v1.5.5.1943) |  Method not found: Microsoft.EntityFrameworkCore.MutableAnnotatableExtensions.SetOrRemoveAnnotation exception on DotNet 6

### ISSUE THREAD

**Issue by DoomerDGR8** [elsa-workflows/elsa-core#2480]
I have started to get this exception. ~~I cannot blame .Net 6 as it was working a few days ago and I have a week-old deployment on staging server with .Net 6 release verion still working~~. It is definitely .Net 6

However, I had a few packages update and now on dev, I'm getting this response from my API that fails to start at all:

```
{
    "Message": "An exception was thrown while activating Elsa.Activities.Http.RequestHandlers.Handlers.TriggerRequestHandler -> Elsa.Services.WorkflowInvoker -> Elsa.Persistence.EntityFrameworkCore.Services.EntityFrameworkCoreWorkflowInstanceStore -> λ:Elsa.Persistence.EntityFrameworkCore.DbContexts.ElsaContext -> Microsoft.EntityFrameworkCore.Internal.ScopedDbContextLease`1[[Elsa.Persistence.EntityFrameworkCore.DbContexts.SqlServerContext, Elsa.Persistence.EntityFrameworkCore, Version=1.5.5.1943, Culture=neutral, PublicKeyToken=null]].",
    "Errors": null,
    "IsSuccess": false
}
```

**Comment by DoomerDGR8** [comment]
```
An exception was thrown while activating Elsa.Activities.Http.RequestHandlers.Handlers.TriggerRequestHandler 
    -> Elsa.Services.WorkflowInvoker 
    -> Elsa.Persistence.EntityFrameworkCore.Services.EntityFrameworkCoreWorkflowInstanceStore 
    -> λ:Elsa.Persistence.EntityFrameworkCore.DbContexts.ElsaContext 
    -> Microsoft.EntityFrameworkCore.Internal.ScopedDbContextLease`1[[Elsa.Persistence.EntityFrameworkCore.DbContexts.SqlServerContext, Elsa.Persistence.EntityFrameworkCore, Version=1.5.5.1943, Culture=neutral, PublicKeyToken=null]].
```

**Comment by DoomerDGR8** [comment]
It seems that the class [Microsoft.EntityFrameworkCore.MutableAnnotatableExtensions](https://github.com/dotnet/efcore/blob/main/src/EFCore/Extensions/MutableAnnotatableExtensions.cs) is obsolete and is replaced by [IMutableAnnotatable](https://github.com/dotnet/efcore/blob/main/src/EFCore/Metadata/IMutableAnnotatable.cs). I'm still now certain when this change occurred and why I was able to use Elsa v1 in DotNet 6 Previews.

**Comment by DoomerDGR8** [comment]
It seems that the class [Microsoft.EntityFrameworkCore.MutableAnnotatableExtensions](https://github.com/dotnet/efcore/blob/main/src/EFCore/Extensions/MutableAnnotatableExtensions.cs) is obsolete and is replaced by [IMutableAnnotatable](https://github.com/dotnet/efcore/blob/main/src/EFCore/Metadata/IMutableAnnotatable.cs). I'm still now certain when this change occurred and why I was able to use Elsa v1 in DonNet 6 Previews

**Comment by sfmskywalker** [comment]
Looks like the Elsa 1 projects need to be updated to target .NET 6. If you want to submit a PR I'll merge it in.

**Comment by DoomerDGR8** [comment]
I tried to upgrade but it wasn't straight forward. I'll update here when I can.
