### ISSUE TITLE
Token decoding failing when ELSA hosted on multiple server

### ISSUE THREAD

**Issue by shreedhar-ww** [elsa-workflows/elsa-core#2490]
If I am hosting  Multiple instances of the ELSA server in that case token decryption is failing.

We observed this behaviour when the user click on approve/reject link from the SMTP portal and ELSA server configure with multiple nodes.

I believe there is some issue with decoding.

Looks like below code in ElsaServiceCollectionExtensions.cs causing an issue.

  services.AddDataProtection();

**Comment by sfmskywalker** [comment]
Indeed. When hosting on multiple nodes in a cluster, you need to configure data protection to use shared storage and some other details.

[This blogpost](https://medium.com/swlh/how-to-distribute-data-protection-keys-with-an-asp-net-core-web-app-8b2b5d52851b) explains some options you might consider.
