### ISSUE TITLE
Can I add Custom Properties To Work flow Definition To Be Set Using The Designer?

### ISSUE THREAD

**Issue by hassanelsherbiny** [elsa-workflows/elsa-core#2491]
I want to add Some Custom Properties To Workflow Definition which i can set it's values throw the designer
for example i want to add checkbox to flag this workflow for specific criteria to be used later which execution 
Like This
![image](https://user-images.githubusercontent.com/20015837/142383199-16a50341-00ce-4faa-afea-3b8d6ce0118d.png)

**Comment by sfmskywalker** [comment]
There's a new feature coming with Elsa 2.4 that allows you to define custom properties for workflow definitions. It's not documented yet however.
