### ISSUE TITLE
Prefilter Workflow Instance List

### ISSUE THREAD

**Issue by noxe** [elsa-workflows/elsa-core#2499]
Hi,

as discussed on discord - i would like to prefilter the workflow instance list based on an workflow definition id or an correlation id. It seems there are properties in the component - but they are not exposed as attributes - and settings via javasript also does not work. from what i see there is no code in the componentwillload that take into account these values?

**Comment by sfmskywalker** [comment]
I just tried the following code with the current version from master:

```html
<elsa-studio-root server-url="https://localhost:11000" monaco-lib-path="build/assets/js/monaco-editor/min" culture="en-US">
   <elsa-workflow-instance-viewer-screen id="workflowInstanceViewer"></elsa-workflow-instance-viewer-screen>
</elsa-studio-root>

<script>
  const workflowInstanceViewer = document.getElementById('workflowInstanceViewer');
  workflowInstanceViewer.workflowInstanceId = 'b7a01fc39ddd4bb19395f01612ca9af8';
</script>
```

Which works.
However, trying to set the property directly on the element doesn't work as you mentioned so we need to expose it as an attribute.

**Comment by noxe** [comment]
Hi - ok - bit i think i was refering to the elsa-workflow-instance-list-screen - not the elsa-workflow-instance-viewer-screen

**Comment by sfmskywalker** [comment]
You're right, my mistake. I'll look into the list screen :D

**Comment by noxe** [comment]
thx you - cannot get it work even with the script in the list-screen 😎

**Comment by sfmskywalker** [comment]
Yeah makes sense:

> from what i see there is no code in the componentwillload that take into account these values?

That was the issue. I just pushed an update that fixes this 😎

**Comment by noxe** [comment]
you rock as always - thank you 😎👍👍

**Comment by noxe** [comment]
wouldnt that raise a small performance hit now - i think all 4 calls handle* - will now raise 4 loads of the instances?

**Comment by noxe** [comment]
it work fine now - thx again - but sql profiler shows 5 queries now when opening the instance list - maybe this could be improved?

**Comment by sfmskywalker** [comment]
That’s not good. Yes, we should fix that.

**Comment by sfmskywalker** [comment]
Should be good now. Thanks for the great catch 😎

**Comment by noxe** [comment]
thank you 🙏 😎
