### ISSUE TITLE
LiternalExpression "\r\n" evaluates null result

### ISSUE THREAD

**Issue by wakuflair** [elsa-workflows/elsa-core#250]
Hi

I have a `WorkflowExpression<string>` property set to `new LiteralExpression<string>("\r\n")`, however its evaluated value always be null, while I expected it returns "\r\n".

I examined the source, it because the `LiternalEvaluator` has this check:

https://github.com/elsa-workflows/elsa-core/blob/8fdc93952b1c83d5bfdab7a4b5467b64a611ce04/src/core/Elsa.Core/Expressions/LiteralEvaluator.cs#L22

Mabe just using `IsNullOrEmpty` is better?

**Comment by sfmskywalker** [comment]
I don’t see why not. Let’s get this in.

**Comment by wakuflair** [comment]
I raised a PR to resolve this.
