### ISSUE TITLE
.NET 6

### ISSUE THREAD

**Issue by sfmskywalker** [elsa-workflows/elsa-core#2501]
We need to update all projects to target .NET 6.0.

**Comment by mohdali** [comment]
Please target that for 2.5. We have similar plans to move from .NET Core 3.1 to .NET 6 but we want to still use Elsa 2.4 when it is released with .NET Core 3.1.

**Comment by maelmahdy86** [comment]
@sfmskywalker any idea when .NET 6 will be supported ?
I'm totally stuck in an enterprise project due to this exception #2505

**Comment by sfmskywalker** [comment]
Can’t say unfortunately due to various conflicting priorities, but if this is blocking then I’d be happy to accept a PR that targets .NET 6 and release it as 2.3.something. Make sure that it still also targets 3.1 and 5.0.

**Comment by YaoaY** [comment]
stuck here too, can we migrate to .net 6 in the early preview builds of 2.5? 😢

**Comment by sfmskywalker** [comment]
I'm a little bit strapped for time, but if you want to submit a PR I'd happily accept it.

**Comment by puschie286** [comment]
if someone is looking for a .NET 6 version of Elsa

https://github.com/puschie286/elsa-core/tree/dot-net-6

note: its not fully tested, just first version to get it running under net6
note2: because some dependencies are not compatible with 5.0 and 6.0, this version is 6.0 only

**Comment by DoomerDGR8** [comment]
@puschie286 Possible you can bump Elsa v1.5 to .Net 6 as well. I have tried a few times but am not able to get a running testable output. I'm too stuck in an enterprise application that was using Elsa v1.5 and I cannot go to .Net six as the application is Web API + Blazor Server side and there are actual benifits I'm missing by staying on .Net 5. Until .Net 6 Preview 7, Elsa was working. Then something changes in EF Core 6, and I started getting missing methods as interfaces have changed. I have an issue opened #2480

**Comment by sfmskywalker** [comment]
Closed with 4933a2e81e1c88546f482bf9a82388f0060ac69d

**Comment by maelmahdy86** [comment]
I've upgraded to 2.4.0.1 but still getting same exception

![image](https://user-images.githubusercontent.com/76489448/147643486-b5ffce50-cdef-44b1-99d9-a82434eb714d.png)

**Comment by OlegLukash** [comment]
> I've upgraded to 2.4.0.1 but still getting same exception
> 
> ![image](https://user-images.githubusercontent.com/76489448/147643486-b5ffce50-cdef-44b1-99d9-a82434eb714d.png)

Also still have this issue

**Comment by sfmskywalker** [comment]
.NET 6 support will come with `2.4.1` and is not part of `2.4.0`. Can you try with the 2.4.1-preview packages available from MyGet?

**Comment by OlegLukash** [comment]
> .NET 6 support will come with `2.4.1` and is not part of `2.4.0`. Can you try with the `2.4.1-preview` packages available from MyGet?

Sorry, can not find them here: https://www.myget.org/feed/elsa-2/package/nuget/Elsa

**Comment by sfmskywalker** [comment]
My bad, I forgot to bump the version number in the build pipeline. Should be there now.

**Comment by OlegLukash** [comment]
Thanks for quick reply. I have updated ELSA packages to 2.4.1-preview.10, but have an issue: when run the Dashboard, js and css files are not loaded. Discovered that 2.4.1-preview.10 version does not contain them. Have I missed something?
![image](https://user-images.githubusercontent.com/25796029/148090287-1d134c98-b715-4895-8949-df9dfc41f829.png)

**Comment by sfmskywalker** [comment]
You're right - for some reason that particular build does not have the necessary client assets. After triggering a new build, somehow the issue got resolved.
