### ISSUE TITLE
Allow users to toggle between different UI/UX experiences

### ISSUE THREAD

**Issue by omid-tansaz** [elsa-workflows/elsa-core#2507]
Changing Designer UI/UX may impact a lots of users. Reduce adoption frustration by allowing users to toggle between new and existing UI/UX features.

Example use case:
When enabling horizontal ordering of activities, we don't want to remove the vertical editor (many users may still be used to that).

Allow configuring global designer settings under designer expandable side panel where general and test tabs are located.
- [X] Allow API's to control the options in the widget.
- [X] Save information in browser store.
- [X] Integrated this with designer boottrap in Elsa Core so the settings can be controlled by configuration. Please consider the settings must be set at application level (for All users), and as individual user level.

Check proposal (example from Azure DevOps preview feature toggles).

![Screenshot 2021-11-22 at 11 11 09](https://user-images.githubusercontent.com/28906715/142842946-3deffd85-c8c3-428d-b8b6-c3f811d47fa6.png)

![Screenshot 2021-11-22 at 11 01 44](https://user-images.githubusercontent.com/28906715/142842641-de90e55f-e41e-46cd-b2bb-b73a5c9eb264.png)

**Comment by sfmskywalker** [comment]
Looks good. I like that this allows the implementer to control (default) settings from configuration (or probably as component attributes on the `<elsa-studio-root>` element that can then be overridden on a per-workflow-definition basis.

We could do this by exposing a property on the root component that accepts a list of strings, where each string represents a feature name. When a feature is present in this list, the feature is enabled by default.

We should probably also allow the implementer to control what features can be toggled from the UI (if any at all).
Perhaps a secondary root component attribute would suffice.

Example:

```html
<elsa-studio-root id="elsaStudioRoot" features="workflow-layout-horizontal, workflow-testing" feature-toggle-ui="workflow-layout-horizontal"></elsa-studio-root>
```

The above configuration would enable two features, but only one of them can be overridden by the user through the UI for a given workflow.

Furthermore, it is conceivable that some features might have additional options to configure.
In that case, simply listing a feature may not be enough and requires additional configuration through a JSON object. The JSON structure might look like this:

```javascript
export const default = {
   features: [
      workflowLayout: {
         enabled: true, // whether this feature is enabled by default.
         ui: true, // whether this feature can be enabled through UI.
         orientation: "top-bottom|bottom-top|left-right|right-left" // An enum that takes one of the sample values to control orientation.
      }
   ]
}
```

The above JSON could be applied to the root component either through JavaScript or by specifying a path to a JSON file:

```javascript
import * as config from './designer.config.js';
const elsaStudioRoot = document.getElementById('elsaStudioRoot');
elsaStudioRoot.configure(config);
```

Or:

```html
<elsa-studio-root config="/designer.config.js"></elsa-studio-root>
```
