### ISSUE TITLE
An item with the same key has already been added error

### ISSUE THREAD

**Issue by tomy2105** [elsa-workflows/elsa-core#2519]
Elsa 2.0 from nuget.
Has this been solved in more recent versions?
Is there a workaround?

System.ArgumentException:
 An item with the same key has already been added. Key: 
d79283b2-5f6f-42bc-8463-2418f559fb65
   at System.Collections.Generic.Dictionary`2.TryInsert(TKey key, TValue
 value, InsertionBehavior behavior)
   at System.Collections.Generic.Dictionary`2.Add(TKey key, TValue 
value)
   at System.Linq.Enumerable.ToDictionary[TSource,TKey](IEnumerable`1 
source, Func`2 keySelector, IEqualityComparer`1 comparer)
   at System.Linq.Enumerable.ToDictionary[TSource,TKey](IEnumerable`1 
source, Func`2 keySelector)
   at 
Elsa.Services.WorkflowBlueprintMaterializer.CreateWorkflowBlueprintAsync(WorkflowDefinition
 workflowDefinition, CancellationToken cancellationToken)
   at 
Elsa.WorkflowProviders.DatabaseWorkflowProvider.TryMaterializeBlueprintAsync(WorkflowDefinition
 workflowDefinition, CancellationToken cancellationToken)

**Comment by sfmskywalker** [comment]
I believe that to be the case. Do you have steps to reproduce to try against the master branch?

**Comment by tomy2105** [comment]
Unfortunately not.
The workflow has been created using designer but unfortunately not by me, and the person who did it doesn't exactly remember what he did.
He did a larger workflow (50+ activities) and did not test it until the end where he saw it doesn't work :(.
Then I exported it, saw the duplicate entry in json export, removed the duplicate, imported it back and all was well.

So unfortunately the only info I have is that it is designer issue, when adding new activity _sometimes_ a duplicate entry in JSON representation seems to be created.
