### ISSUE TITLE
WatchDirectory does not work with pattern *.*

### ISSUE THREAD

**Issue by noxe** [elsa-workflows/elsa-core#2527]
Hi,

i am creating a new issue - so we dont get lost. as described here - https://github.com/elsa-workflows/elsa-core/issues/1654 - when using * . * as pattern - the workflow does not start. the reason is that the filewatcher normalizes the pattern from * . * to * - so in memory the tigger based on the activity is * . * - but the filesystem event does an bookmark query based on the pattern * - so it does not find any trigger. any suggestion how to fix this?

**Comment by sfmskywalker** [comment]
One solution could be simply instruct the user to use `*`, not `*.*`. Alternatively, we could update the bookmark handler to replace any `*.*` input with just `*`.

**Comment by noxe** [comment]
yes - but this is very error prone - and will cause many support calls i guess. the bookmark handler is a good idea i guess :)

**Comment by sfmskywalker** [comment]
> will cause many support calls

Well, obviously I'm not gonna give away my phone number ;)
