### ISSUE TITLE
System.InvalidOperationException: "Sequence contains no elements"

### ISSUE THREAD

**Issue by noxe** [elsa-workflows/elsa-core#2529]
Hi @sfmskywalker - the latest commit https://github.com/elsa-workflows/elsa-core/commit/b6a7a38b21b00d89b57303dfd224ea2c0f68d7d1 introduced an exception here:

foreach (var type in
                         from activityDefinition in httpEndpointActivities
                         select activityDefinition.Properties.First(x => x.Name == nameof(HttpEndpoint.TargetType)).Expressions.Values.First()

Expressions Count is 0 here - so First will throw - i think this should be an FirstOrDefault() ? I will create an PR for this!

![image](https://user-images.githubusercontent.com/158478/143618707-e78082b8-5780-4562-9a3d-03bbdfd243d0.png)

**Comment by sfmskywalker** [comment]
Cheers @noxe !
