### ISSUE TITLE
Npgsql.TypeMapping.NpgsqlTypeMapping error

### ISSUE THREAD

**Issue by Dymasik** [elsa-workflows/elsa-core#2544]
I tried to use elsa (v.2.3) with PostgreSQL persistence storage (EF Core) as a net5.0 (as well as netcore3.1) and I always receive this error on application starting: 
Unhandled exception. System.TypeLoadException: Could not load type 'Npgsql.TypeMapping.NpgsqlTypeMapping' from assembly 'Npgsql, Version=6.0.0.0, Culture=neutral, PublicKeyToken=5d8b90d52f46fda7'

Please advice ASAP.

**Comment by sfmskywalker** [comment]
Looks like your using a version of NPGQL targeting .NET 6. Try using a lower version compatible with .NET 5. At least until Elsa targets .NET 6z

**Comment by Dymasik** [comment]
![image](https://user-images.githubusercontent.com/33788514/143961105-d457c832-fc03-4bec-949c-b927bd56febb.png)
I use .net5 version of NPGQL

**Comment by sfmskywalker** [comment]
I can’t tell from your screenshot, but looking at the error message, I see that you’re using Ngpsql 6.0.0. Which presumably targets .NET 6. I’m not sure, but you might look into that and see if that’s the case or not. The PostgreSQL package referenced by Elsa is 5.0.10 I believe.

**Comment by lirajw** [comment]
someone found how do fix that bug?

**Comment by sfmskywalker** [comment]
I’m not convinced there’s a bug. The error message shows that Npgsql 6.0 is referenced, which targets .NET 6. Elsa however only targets 5.0. Which means the solution is to downgrade the Npgsql package reference to a lower version that targets .NET 5 or .NET Standard.

**Comment by mohdali** [comment]
Seems to me that `Hangfire.PostgreSql`  version 1.9.x is adding the dependency to Npgsql 6.0.0. Maybe try lowering the version to 1.8.x which refers 5.0.7+

**Comment by sfmskywalker** [comment]
@mohdali nice catch 👍🏻

**Comment by israelabah** [comment]
Thanks @mohdali

**Comment by thiagocoppi** [comment]
Using version npgsql 5.0.x solved this issue
