### ISSUE TITLE
Inconsistency between state object handling in Fluid Definition builder and Dashboard project

### ISSUE THREAD

**Issue by CleverAtBen** [elsa-workflows/elsa-core#255]
When persisting a Fluid Workflow to SQL (using some code based on [Sample 22](https://github.com/elsa-workflows/elsa-core/blob/develop/src/samples/Sample22/Program.cs)) - when I load them up in the Dashboard all Variables and branch values are missing from the UI - from what I have been able to gather it seems to be a CamelCase serialization thing.

All state properties on the Definition Save are capitalized, If I try and create the workflow directly in the dashboard it's lower case.

If I manually amend the case in the persisted definition then the definition loads as expected.

Ideally making State object case insensitive would be the best solution all round.

**Comment by sfmskywalker** [comment]
Fixed with 2.0
