### ISSUE TITLE
HttpEndpointTypeDefinitionRenderer - System.InvalidOperationException

### ISSUE THREAD

**Issue by noxe** [elsa-workflows/elsa-core#2558]
Hi @sfmskywalker ,

similar to https://github.com/elsa-workflows/elsa-core/issues/2529 there is another Exception now - it is because of HttpEndpointTypeDefinitionRenderer. 

Here are 2 First() statements -

        var targetTypeSchema = activityDefinition.Properties.First(x => x.Name == nameof(HttpEndpoint.Schema)).Expressions.Values.First();

This renderer is now called for each activity - also my custom one - so they do not contain 1) an property with the Name Schema - and if so - Expressions.Values should also changed to FirstOrDefault.

Can you advise the best way to fix this - i think this should only handle HTTPEndpoint activities i guess?

**Comment by noxe** [comment]
The RenderActivityPropertyAsync method also has 2 .Values.First()

Currently it seems this happens randomly - the RenderJavaScriptTypeDefinitions does an _activityTypeDefinitionRenderers.First(x => x.GetCanRenderType(type));

since both - the HttpEndpointTypeDefinitionRenderer and the DefaultActivityTypeDefinitionRenderer return True for the GetCanRenderType ?

**Comment by noxe** [comment]
I see you commited a change - thanks for this - but shouldnt that at least call the base method?

 if (activityType.Type != typeof(HttpEndpoint))
                return;

since both HttpEndpointTypeDefinitionRenderer and DefaultActivityTypeDefinitionRenderer  are active - and only one of them is called - return does not render anything then? or am i wrong here?

**Comment by sfmskywalker** [comment]
You're right, great catch!

**Comment by sfmskywalker** [comment]
Just pushed. Thanks again for paying attention ;)

**Comment by noxe** [comment]
cool - thanks man!

**Comment by noxe** [comment]
dont see the commit yet - should it be online?

**Comment by sfmskywalker** [comment]
Forgot to push. It should be online now.

**Comment by noxe** [comment]
thx!!

**Comment by sfmskywalker** [comment]
I'm probably gonna push another update - one that takes advantage of the `GetCanRenderType` method. Which is intended to be used as a filter anyway.

**Comment by noxe** [comment]
cool - thx - if you are at it - can you also change the First() calls to FirstOrDefault() - i was just going to change that localy

**Comment by sfmskywalker** [comment]
Checking

**Comment by sfmskywalker** [comment]
Done

**Comment by noxe** [comment]
❤

**Comment by noxe** [comment]
there are 2 more below :)

   var targetTypeName = activityDefinition.Properties.First(x => x.Name == nameof(HttpEndpoint.TargetType)).Expressions.Values.First();
            var targetTypeSchema = activityDefinition.Properties.First(x => x.Name == nameof(HttpEndpoint.Schema)).Expressions.Values.First();

**Comment by sfmskywalker** [comment]
I added you as a code contributor. Please fix it :)

**Comment by noxe** [comment]
yes sir :)

**Comment by noxe** [comment]
done - so closing this! thanks for the help man!
