### ISSUE TITLE
Issue with character set UTF-8 when using HttpClient.PostAsJsonAsync<T>(path, obj)

### ISSUE THREAD

**Issue by sniperwolfpk5** [elsa-workflows/elsa-core#256]
Hello @sfmskywalker,

I have faced issue when using `HttpClient.PostAsJsonAsync<T>(path, obj)` from client application (Asp.net MVC 5). It appends UTF-8 charachter set after `application/json;`. Due to this null object is return. I have spend full day to find this issue.  Some APIs have no issue with utf-8 encoding. Unfortunately Elas don't like it :( . To tackle this issue I use below format instead of using  `HttpClient.PostAsJsonAsync<T>(path, obj)`
 ```
var data = new StringContent( new JavaScriptSerializer().Serialize(obj));
 data.Headers.ContentType = MediaTypeHeaderValue.Parse("application/json");
 var result = await Client.PostAsync(path, data);
```
IDK whether it is a bug or normal flow.

Regards,

**Comment by sfmskywalker** [comment]
Elsa uses Newtonsoft JSON.NET to parse incoming JSON content. Perhaps it doesn’t like the null character created by PostAsJsonAsync. To be investigated. Thanks for letting me know.

**Comment by IntranetFactory** [comment]
From my experience Newtonsoft JSON.NET is bloated and very opinionated. 

Using it frequently generates bizarre JSON and causes version problems. 

We use for years Simple.Json (https://github.com/facebook-csharp-sdk/simple-json/blob/master/src/SimpleJson/SimpleJson.cs) - just a single file which provides JsonObject and JsonArray classes, and handles serialization absolutely transparent.

**Comment by sniperwolfpk5** [comment]
@sfmskywalker, @IntranetFactory  I think I didn't explain my question well enough. Issue is when using Elsa's Set Variable activity. I debug set variable code. I can see the  Json string in context's body. But `JavaScriptExpressionEvaluator ` is failed to parse it as Json object rather it returns plain string. The problem is not with `JavaScriptExpressionEvaluator `.

**Comment by sniperwolfpk5** [comment]
Change Uri in above  post

**Comment by sfmskywalker** [comment]
This issue has been fixed by properly parsing incoming content types.
