### ISSUE TITLE
Issue create Fork with designer

### ISSUE THREAD

**Issue by yopichy** [elsa-workflows/elsa-core#2565]
When creating fork with designer, connection is not generate by branch e.g. (Approve,Reject,Remind)
![Screenshot 2021-12-08 172732](https://user-images.githubusercontent.com/2038089/145192817-8f7abd38-0ce9-4aea-93c8-a5820a61a885.png)
![Screenshot 2021-12-08 172801](https://user-images.githubusercontent.com/2038089/145192830-6dbbe518-73e4-4006-85db-6525f4758b06.png)

This is from documentation https://elsa-workflows.github.io/elsa-core/docs/next/guides/guides-document-approval#create-workflow
![image](https://user-images.githubusercontent.com/2038089/145192946-ad056f78-d929-46a0-8f5b-400eaa906be6.png)

**Comment by yopichy** [comment]
@sfmskywalker this is bug?

**Comment by sfmskywalker** [comment]
I tried to reproduce with latest code from master branch [as well as the docker image](https://elsa-workflows.github.io/elsa-core/docs/next/quickstarts/quickstarts-elsa-and-docker), but it works for me.

What version are you using?

**Comment by yopichy** [comment]
@sfmskywalker i'm only use elsa-dashboard 
![image](https://user-images.githubusercontent.com/2038089/146759660-18602f10-2e2d-45fd-8794-98d111f198f0.png)

and use another server for API
docker run -t -i -e ELSA__SERVER__BASEADDRESS=https://localhost:5100 -p 14000:80 elsaworkflows/elsa-dashboard:latest

**Comment by sfmskywalker** [comment]
Maybe that's the problem: the docker image you use might be hosting a workflow designer that is incompatible with your workflow server.

If you open your F12 Developer Tools window on the designer, maybe you see some errors there that might offer a hint.

**Comment by yopichy** [comment]
error UnsupportedApiVersion @sfmskywalker 
![image](https://user-images.githubusercontent.com/2038089/146780039-060b26a9-3a4a-4377-9076-4272a3a38b83.png)

This is my API Server
![image](https://user-images.githubusercontent.com/2038089/146780159-e412e1df-7c33-40d8-a580-8add35dfb3f7.png)

**Comment by yopichy** [comment]
I found the problem, from elsa designer using method POST while in swagger use GET @sfmskywalker

**Comment by sfmskywalker** [comment]
Ah. So that probably changed between 2.3 and current version. Current version requires POST:

![image](https://user-images.githubusercontent.com/938393/146783430-0ed07894-a3a4-4ca1-862a-93c6a1a583d9.png)

**Comment by yopichy** [comment]
> Ah. So that probably changed between 2.3 and current version. Current version requires POST:
> 
> ![image](https://user-images.githubusercontent.com/938393/146783430-0ed07894-a3a4-4ca1-862a-93c6a1a583d9.png)

I'm already use elsa v2.3
![image](https://user-images.githubusercontent.com/2038089/146784079-57d1cbf1-77b5-4cbb-b864-a904aad1eeea.png)

**Comment by sfmskywalker** [comment]
Right. Let me be more specific: it was changed between 2.3 **and current version** - by which I mean, the version that exists in the `master` branch and in the form of the 2.4 preview packages available from MyGet.

**Comment by yopichy** [comment]
Ah i get it, so must upgrade v2.3 to current master branch v2.4-preview, thanks @sfmskywalker i'll try it

**Comment by sfmskywalker** [comment]
Exactly 👍🏻

**Comment by yopichy** [comment]
![image](https://user-images.githubusercontent.com/2038089/146790932-3cee862d-22ea-4537-a188-609a32f39046.png)

do you know what error this is?
I'm already added package source
![image](https://user-images.githubusercontent.com/2038089/146791254-79e32488-9f38-4b92-bb11-9ecbff753b93.png)

**Comment by mohdali** [comment]
@yopichy add Jint myGet https://www.myget.org/F/jint/api/v3/index.json

**Comment by yopichy** [comment]
Thanks @mohdali it's works!

**Comment by yopichy** [comment]
Problem solved after Upgrade to version 2.4.0-preview.465
![image](https://user-images.githubusercontent.com/2038089/146792542-fb6b5a25-2492-4cab-8190-9c277d93e3ba.png)
