### ISSUE TITLE
High latency of http endpoint

### ISSUE THREAD

**Issue by omid-tansaz** [elsa-workflows/elsa-core#2569]
What is the expected performance benchmark for http endpint activity?
We see some performances go over 170 ms, that seems odd and quite long for an end-point to just read content and start the workflow.

![Screenshot 2021-12-09 at 12 47 54](https://user-images.githubusercontent.com/28906715/145394796-b12abbd4-48bd-4023-bd7b-635dbf58a95a.png)

**Comment by sfmskywalker** [comment]
There appears to be an issue with the logic that calculates the delta between two activity execution events. See #2568
