### ISSUE TITLE
Postgresql persistence through YesSql through exception

### ISSUE THREAD

**Issue by SherifRefaat** [elsa-workflows/elsa-core#257]

**Comment by SherifRefaat** [comment]
The exception keeps coming and going. But right now, it doesn't show up anymore!
I am sorry.
But the exceptions is about 

- `Session: Can not access a disposed object`
- `(0x80004005): 42883: operator does not exist: character varying = integer`

**Comment by sfmskywalker** [comment]
Just being curious: have you been able to discover the root cause of the issue you were seeing

**Comment by SherifRefaat** [comment]
@sfmskywalker it disappeared on its own while i was typing this issue. That is why i was not able to provide the stack trace. I am experimenting with Elsa right now, if i encounter them again, i will reopen the case. Side note: it seemed to me like a Heisenberg bug or a race condition.

**Comment by sfmskywalker** [comment]
Thanks for the response, I appreciate it. Please do reopen this issue if you run into it again. And of course hopefully with steps to reproduce, but also if it happens on occasion.
