### ISSUE TITLE
Allow listing of historical versions of process definitions with option to replace the draft with a historical version

### ISSUE THREAD

**Issue by omid-tansaz** [elsa-workflows/elsa-core#2572]
It is very useful to view and revert a historical version. As all historical versions are already available in the database.

**Suggestion**
- Allow designers to see previous workflow definition versions
- Allow deleting of a historical version 
     => e.g. very useful if there ia historical version with hardcoded credentials.
- Allow opening a selected historical version 
    => its handy to allow getting some information from previous versions, it should be clear that user has opened a historical version
- Allow reverting a selected historical version 
   => Create new historical version from current draft, make the reverted version as current draft.

**UI/UX Suggestions**
- Please think a long and provide some suggestions as well.
- Add a tab to proces definition in side panel where these functionalities are added.
- Show the user that a historical version (not the active draft/published version) is open, e.g. by changing the bottom-down actions: Revert, Delete, Export, Import, (remove publish). Also show the version information next to the action button.

**Comment by tomy2105** [comment]
This request seems to be the same (albeit a bit more verbose in wording) as #1311.

**Comment by sfmskywalker** [comment]
The history panel could look something like this:

![image](https://user-images.githubusercontent.com/938393/152342507-0078f316-70d9-4434-a874-4098ccadb332.png)

Then once the user selected a version to view in the designer, the **Publish** button would change to e.g. **Save as Draft**. Clicking that button would then create a new version that is a copy of the selected version, after which the button changes to **Publish**.

**Comment by mohdali** [comment]
Wouldn't it be better to have the version history outside the designer? From the workflow list have an option to view history and then load the designer for that specific version.

Something like Git history.

Designer also needs to keep clear visual cues if this is the latest versio or older version to avoid confusion.

**Comment by tomy2105** [comment]
I kind of like this approach inside designer :), but that is personal preference I guess. 
It is "future proof" in sense that if workflow diffing is ever implemented, it could be here, you click on version of history and it displays visual diff on the left :).....

**Comment by tomy2105** [comment]
And one thing more....
Since versions take space in storage, there should be delete button next to view button that would purge some version from history/database......

**Comment by sfmskywalker** [comment]
Thanks for the great input guys. So how about this:

- The Workflow Definitions overview screen receives an extra context menu item: "History". This takes the user to another screen that lists all versions of the selected workflow definition. From here, they can view, rollback and delete versions.
- From the workflow designer, the user can find a list of versions as well as shown [here](https://github.com/elsa-workflows/elsa-core/issues/2572#issuecomment-1028940430). From here they can do the same things: view, rollback and delete.
- When the user selects an older version from the designer, the Publish button changes its text to e.g. _Save as New Version_. The workflow properties panel will of reflect the current version being edited (in addition to showing the latest version as well as the published version).
- When the user wants to delete a version, they need to be made aware that this will also delete any associated workflow instances. And if there ore non-completed instances (Idle, Suspended and Running) then this needs to be included in the alert message as well.

**Comment by sfmskywalker** [comment]
Sub tasks:

**APIs**

- [ ] Rollback Version (which creates a new version of he specified version)
- [ ] Delete Version (will delete associated workflow instances too)
- [ ] Count Workflow Instances (return the number of workflow instances, grouped by status: Idle, Running, Completed, Cancelled and Faulted)

**Dashboard**

- [ ] Context menu item to workflow definition rows in the Workflow Definitions screen
- [ ] Workflow Definition Versions list screen
- [ ] History tab on Workflow Designer screen
- [ ] Confirmation dialog to display when clicking Delete. The dialog should display the number of workflow instances for each non-zero status that will be deleted also.

**Comment by tomy2105** [comment]
Sounds like a good plan :)

**Comment by sfmskywalker** [comment]
I implemented parts of what was described above, which means we still need a separate screen displaying all versions of a given workflow definition. We can add this later.
