### ISSUE TITLE
TypedHttpResponseContentReader

### ISSUE THREAD

**Issue by FransVanEk** [elsa-workflows/elsa-core#2573]
The interface IHttpResponseContentReader has a strong dependency on the SendHttpRequest limiting the re-use of the contentreader implementations. 

Only the TypedHttpResponseContentReader uses this to fetch the ContentType, Could it be changed to Type so it makes it more reuseable..?

 ``json
public interface IHttpResponseContentReader
    {
        string Name { get; }
        int Priority { get; }
        bool GetSupportsContentType(string contentType);
        Task<object> ReadAsync(SendHttpRequest activity, HttpResponseMessage response, CancellationToken cancellationToken);
    }
```

**Comment by sfmskywalker** [comment]
@FransVanEk Can you take a look at #2608 and let me know if this change would work for your case?

**Comment by sfmskywalker** [comment]
I'll mark this as completed, but feel free to reopen if needed!

**Comment by FransVanEk** [comment]
@sfmskywalker , yes this will work for me. thanks
