### ISSUE TITLE
Issue with ELSA packages from MyGet Feeds

### ISSUE THREAD

**Issue by harshad-azilen** [elsa-workflows/elsa-core#2586]
Hi @sfmskywalker ,

In our project we are referring 2.4.0-preview.413 for ELSA.  Till yesterday application able to resolve packages and from today suddenly our application is not working and showing build error with **"Elsa 2.4.0-preview.413 was not found"**. 

We are using feeds from this URL

- Elsa Preview Feed "https://www.myget.org/F/elsa-2/api/v3/index.json"
- Jint Preview Feed "https://www.myget.org/F/jint/api/v3/index.json"

You can find below csproj file content for ELSA packages.

- "Elsa" Version=**"2.4.0-preview.413"**
- "Elsa.Activities.ControlFlow" Version="1.5.5.1943"
- "Elsa.Activities.Http" Version=**"2.4.0-preview.413"**
- "Elsa.Activities.Temporal.Hangfire" Version=**"2.4.0-preview.413"**
- "Elsa.Activities.Temporal.Quartz" Version=**"2.4.0-preview.413"**
- "Elsa.Activities.Timers" Version="1.5.5.1943"
- "Elsa.Core" Version=**"2.4.0-preview.413"**
- "Elsa.Designer.Components.Web" Version=**"2.4.0-preview.413"**
- "Elsa.Persistence.MongoDb" Version=**"2.4.0-preview.413"**
- "Elsa.Server.Api" Version=**"2.4.0-preview.413"**
- **"Jint" Version="1482256692.0.0"**

Kindly let me know which **stable package we need to refer** in application so Workflow with Persistence provider can work.

Reference issue:- https://github.com/elsa-workflows/elsa-core/issues/2552

**Comment by sfmskywalker** [comment]
The Elsa & Jint packages are subject to a retention policy configured at MyGet, which means that newer paclages will push out older packages.

To circumvent that, you could create a copy of the packages you're referencing. For example, in Azure DevOps there's an option to [create a feed from upstream feeds](https://docs.microsoft.com/en-us/azure/devops/artifacts/concepts/upstream-sources?view=azure-devops).

Elsa 2.4 will be released next week to NuGet as a stable release.
With regards to Jint, I will see what we need to do there.

**Comment by harshad-azilen** [comment]
> The Elsa & Jint packages are subject to a retention policy configured at MyGet, which means that newer paclages will push out older packages.
> 
> To circumvent that, you could create a copy of the packages you're referencing. For example, in Azure DevOps there's an option to [create a feed from upstream feeds](https://docs.microsoft.com/en-us/azure/devops/artifacts/concepts/upstream-sources?view=azure-devops).
> 
> Elsa 2.4 will be released next week to NuGet as a stable release. With regards to Jint, I will see what we need to do there.

Hi @sfmskywalker , thanks for your quick reply.

Let me wait till next week for stable release of Elsa 2.4 in Nuget. With this hope along with Elsa 2.4, Jint packages will be available easily :-)

**Comment by harshad-azilen** [comment]
Hi @sfmskywalker ,

To continue on development part we have used version 2.4.0-preview.448. We are facing some strange issue here. See below snap for visualization.

We have project say **Employee** and it has repository implementation using Mongo as persistence. 

If we use ELSA with In-Memory storage and when we try to get data from **Mongo collection in our repository** then we dont have any issue with serialization/de-serialization.

If we use ELSA with Mongo persistence and when we try to get data from **Mongo collection in our repository** then we are facing issue with serialization/de-serialization.

Its something strange. Is it like ELSA mongo override our repository implementation? or any other gap?

![image](https://user-images.githubusercontent.com/95464910/146180717-0b3985fd-1489-46ab-a727-febd216e4cfb.png)

**Comment by sfmskywalker** [comment]
@harshad-azilen 

It's better to open a separate issue, since this seems to be unrelated to the issue with the MyGet feed, unless I'm mistaken?
