### ISSUE TITLE
Elsa workflow missing option to hide custom activities on  elsa-activity-picker-modal

### ISSUE THREAD

**Issue by israelovg** [elsa-workflows/elsa-core#2590]
Hi
Elsa 2.3
type Elsa.Metadata.TypedActivityTypeDescriber , function DescribeAsync

function return:
 return new ActivityDescriptor
            {
                Type = typeName.Pascalize(),
                DisplayName = displayName,
                Description = description,
                Category = category,
                Traits = traits,
                InputProperties = inputProperties.ToArray(),
                OutputProperties = outputProperties.ToArray(),
                Outcomes = outcomes,
            };

There are missing row (that were  on previous version)

IsBrowsable = activityType.GetCustomAttribute<BrowsableAttribute>()?.Browsable ?? true,

**Comment by sfmskywalker** [comment]
The `IsBrowsable` property lives on the `ActivityType` class and is used by the designer to determine what activities to display on the picker.

Do you see a problem with `IsBrowsable` not being present on the `ActivityDescriptor`?

**Comment by israelovg** [comment]
Yes , 
If I add Browsable(false) to my activity , isBrowsable is always returns true  , in activities api
To resolve it , I overrided   Elsa.Metadata.TypedActivityTypeDescriber as I mentioned above

**Comment by sfmskywalker** [comment]
I understand. To be clear, this is solved in 2.4. You can try if you want with the 2.4 preview packages available from MyGet.

**Comment by israelovg** [comment]
Thank you
