### ISSUE TITLE
WriteWorkflowExecutionLog does not use any Content Serializers

### ISSUE THREAD

**Issue by noxe** [elsa-workflows/elsa-core#2591]
Hi @sfmskywalker - the WriteWorkflowExecutionLog does currently simply JToken.FromObject - and so it does not use any defined default and custom converters. Any chance to change that?

**Comment by sfmskywalker** [comment]
For sure. we can inject a `JsonSerializer` , which itself can be configured from Startup:

```csharp
services.AddElsa(elsa => elsa.ConfigureJsonSerializer((sp, serializer) => serializer.Converters.Add(...)));
```

Let me know if that helps or if we need to do something else.

**Comment by noxe** [comment]
Can i ask what is the difference between injecting the JsonSerializer - in comparison to other places where you inject the IContentSerializer ?

**Comment by noxe** [comment]
works perfect now btw - thanks :)

**Comment by sfmskywalker** [comment]
> Can i ask what is the difference between injecting the JsonSerializer - in comparison to other places where you inject the IContentSerializer ?

Sure. There's functionally no difference between the two. Unfortunately I don't currently recall why I introduced an additional way to get a JSON serializer. It's very possible that simply thought it would be cool to directly inject preconfigured Jsonserializer. Serves me right for not having documented this 😉
