### ISSUE TITLE
ForEach Activity - Activity Output storage

### ISSUE THREAD

**Issue by noxe** [elsa-workflows/elsa-core#2592]
Hi @sfmskywalker - i noticed an strange issue with an ForEach Activity - dont know if this is a general problem. To reproduce - i used the monolith sample. I created a new Workflow - with an http endpoint to start the WF - and it contains an foreach:

![image](https://user-images.githubusercontent.com/158478/146169423-fad56197-14c9-4197-bae9-f6f3dd25ae42.png)

in the iterate i simply do an write line.

now when the activity is executed - you see in the workflowexecutionlog - the following content:

![image](https://user-images.githubusercontent.com/158478/146169652-df81ece1-3872-4663-a3a2-f58d430d2e5a.png)

You see the the Output was written to the ExecutionLog.

Now change the Foreach Activity - and change the Storage from the Activity Output to Transient - SAVE - then again change the Storage back to Default - SAVE again - and execute the workflow again.

Now you see - even if the storage is on Default - it does not store the Output? Dont know if this is related to ForEach - or an general problem?

![image](https://user-images.githubusercontent.com/158478/146170013-52c80ce2-83c8-478f-89bb-c975fa48ed7d.png)

**Comment by sfmskywalker** [comment]
What a nice catch 😄 

I will push a quick fix - the story of workflow storage providers and workflow execution logging needs work (there's a TODO comment to indicate that).

**Comment by noxe** [comment]
great - thank you - will test it asap :)
