### ISSUE TITLE
Slow worflow definitions and instances 

### ISSUE THREAD

**Issue by Juandavi1** [elsa-workflows/elsa-core#2593]
Hi, 

when we enter the definition of a flow, the endpoint of v1/activities is consulted but it takes a long time to respond. Adding the times of the assets makes everything too slow.

![image](https://user-images.githubusercontent.com/18731612/146215792-282c73f0-ff8e-49ac-910f-f033ceac68d8.png)

we are working with version 2.3

do you know how we can improve performance?

thank you

**Comment by sfmskywalker** [comment]
Hi @Juandavi1 

It's hard to say what makes it so slow, but given that it is also slow to download static assets would lead me to believe something's not right with the network connection. Also make sure that your F12 Developer tools isn't emulating slow connectivity:

![image](https://user-images.githubusercontent.com/938393/146765553-6b57ec50-2443-48a3-b66a-b9f7bc4fd4b7.png)

If you can tell a bit more about your infrastructure, then that might help.

**Comment by Juandavi1** [comment]
hello, 

it seems that the assets are loading fast but the activites endpoint is still taking a long time. 

currently we have the project running in a container inside kubernetes but in terms of resources it has no cpu or memory limitation. 

we are currently running version 2.4.1 


![image](https://user-images.githubusercontent.com/18731612/147829412-47ded5c0-673f-4dda-bbde-1a86ca1fc8aa.png)

![image](https://user-images.githubusercontent.com/18731612/147829430-85bc231c-eacc-4498-87db-6fce420b7755.png)

I did a small load test to that endpoint and these were the results 

![image](https://user-images.githubusercontent.com/18731612/147829865-1029fbb7-ff1a-4931-893f-eee0cbf30aee.png)

**Comment by Juandavi1** [comment]
Hello,
the problem was that the option providers were called multiple times and made a request that took a couple of seconds. We added a cache and now times are much better.

question, is this number of invocations normal?

thank youu

**Comment by sfmskywalker** [comment]
Good question. Will need to be investigated 👍🏻
