### ISSUE TITLE
Workflow keeps running over and over again. foreach issue?

### ISSUE THREAD

**Issue by FransVanEk** [elsa-workflows/elsa-core#2594]
I created a test for the foreach loop activity. The behavior I observe is that the iteration goes on forever. Except when on the done of the foreach activity a finish activity is added. 

In the sample provided, I post a JSON to /multiple endpoint. in the console you can see that the workflow is executed correctly but it start over and over again.

{
    "myArray": [
        {
            "myitem": 1
        },
        {
            "myitem": 2,
            "demo": 3
        }
    ]
}

[testingloop.JSON.TXT](https://github.com/elsa-workflows/elsa-core/files/7721721/testingloop.JSON.TXT)

**Comment by sfmskywalker** [comment]
I see, you are connecting the Write Line activity in the Iterate branch back to the For Each activity - which you don't have to do (and as it turns out, **should not** do ;) )

The engine will already re-schedule the ForEach activity after the last activity of the Iterate branch completes.
Connecting to the ForEach activity explicitly will cause it to be scheduled twice & forever.

**Comment by mohdali** [comment]
> I see, you are connecting the Write Line activity in the Iterate branch back to the For Each activity - which you don't have to do (and as it turns out, **should not** do ;) )
> 
> The engine will already re-schedule the ForEach activity after the last activity of the Iterate branch completes. Connecting to the ForEach activity explicitly will cause it to be scheduled twice & forever.

@sfmskywalker Can we consider a future enhancement to represent loops like they are done in flow charts (last activity connecting back to the iterator).

Visually it makes more sense. Also, not looping back might cause mistakes in workflow design.

In Elsa 1 what we used to do is manually arrange the foreach to have the iterative part on the side and the done part aligned with the rest of the flow, however, in Elsa 2 designer, everything is branching so it becomes hard to trace loops.

**Comment by sfmskywalker** [comment]
Sure, we can make it mandatory in Elsa 3 to "close the loop" visually.
