### ISSUE TITLE
Exception on importing an Workflow

### ISSUE THREAD

**Issue by noxe** [elsa-workflows/elsa-core#2595]
Hi @sfmskywalker - we get an exception when importing an workflow definition

![image](https://user-images.githubusercontent.com/158478/146243294-de371659-9cc1-453d-8e05-dc0d69af9d9a.png)

Console:

![image](https://user-images.githubusercontent.com/158478/146242718-5c03809f-2251-4c8c-b654-8ec1aa9ed526.png)

I also see that in various *.js files the /workflow-definitions url is hardcoded - which might not be correct as we show the designer (without the dashboard) on an different url?

**Comment by sfmskywalker** [comment]
Can you share the workflow JSON you're trying to import? When I try to import a valid JSON workflow, I don;t get any errors.

> I also see that in various *.js files the /workflow-definitions url is hardcoded - which might not be correct as we show the designer (without the dashboard) on an different url?

Indeed, that's an issue. It needs to be prepended with a base URL. Will push a fix 👍🏻

**Comment by noxe** [comment]
i also dont get an exception when trying with monolith - but i think it depenend how the designer is embedded i guess? we use in winforms an webview2 component - and show the designer page at a custom url:

@page "/workflowdesigner/{workflowdefinitionid}"

so is it possible that in such cases the history property is not available? i see other places where you put an if before the history ?

**Comment by sfmskywalker** [comment]
Oh, I see. You're embedding the designer screen component directly. Then yes, you will want this path to be configurable and not hard-coded.

Feel free to open a PR where this component is configurable through component properties.

**Comment by sfmskywalker** [comment]
And also handling the case where `history` may indeed be null.

**Comment by noxe** [comment]
ok - perfect - i take a look on this! 👌
