### ISSUE TITLE
When using autofac (such as ABP vnext framework), there is no data selection for Activity

### ISSUE THREAD

**Issue by wangliqiang1026** [elsa-workflows/elsa-core#260]
autofac: 5.1.2
elsa: 1.2.2.28
elsa.dashboard: 1.2.2.28
Elsa.Persistence.EntityFrameworkCore: 1.2.2.28

use as below:
var config = context.Services.GetConfiguration();
            context.Services
                .AddElsa(elsa =>
                {
                    elsa.AddEntityFrameworkStores<MySqlContext>(x => x.UseMySql(config.GetConnectionString("Default")));
                })

            .AddEmailActivities()
            .AddHttpActivities()
            .AddTimerActivities()

            .AddNotificationHandlers(typeof(LiquidConfigurationHandler))
            .AddElsaDashboard();

elsa/home can be opened，but New Workflow->Add Activity->Available Activities optional empty
image: [https://ftp.bmp.ovh/imgs/2020/03/d85e9689dfabd2de.png](url)

**Comment by sfmskywalker** [comment]
Could you perhaps produce a small Console application demonstrating the issue? It will help me troubleshoot the issue.

**Comment by wangliqiang1026** [comment]
> 您可能会产生一个演示该问题的小型控制台应用程序吗？这将帮助我解决该问题。

try the following solutions. solved the problem

var activityList = AppDomain.CurrentDomain.GetAssemblies().SelectMany(a => a.GetTypes().Where(t => t.GetInterfaces().Contains(typeof(IActivity)))).ToArray();

context.Services.AddElsaDashboard(options =>
            {
                options.Configure(options =>
                {
                    options.ActivityDefinitions
                     .Discover(t => t
                     .FromAssembliesOf(activityList));
                });
            });

**Comment by zrkcode** [comment]
@wangliqiang1026 Why prompt me not to register

![image](https://user-images.githubusercontent.com/20158277/77739260-2a6f8b00-704c-11ea-832f-ec1f3a112ecb.png)
![image](https://user-images.githubusercontent.com/20158277/77739310-3eb38800-704c-11ea-9feb-8beda540fd0f.png)

**Comment by zrkcode** [comment]
I  can only inject according to the prompts when I use AddElsaDashboard()
![image](https://user-images.githubusercontent.com/20158277/77784999-721b0480-7096-11ea-9355-256a985b8f5b.png)

**Comment by sfmskywalker** [comment]
@zrkcode That's odd - you definitely should nt have to explicitly register your controllers. Any chance you can provide a sample project that reproduces this problem for me to look at?

**Comment by sfmskywalker** [comment]
@zrkcode Thanks for providing the repro. I looked into it. Although I don't completely understand why, it appears that when using Autofac (perhaps only in combination with ABP, I don't know), registering the controllers as services will work - you figured this out yourself already of course, but turns out there's a method on `IMvcBuilder` that does this for you.

The following will work:

```csharp
context.Services
    .AddMvc(options => options.EnableEndpointRouting = false)
    .AddControllersAsServices();
```

Reference: https://autofaccn.readthedocs.io/en/latest/integration/aspnetcore.html#controllers-as-services

**Comment by zrkcode** [comment]
@sfmskywalker Thanks for your answer.Actually，I got more errors with ABP when I didn't use Autofac，you can try it.
In addition, i can't use api of abp when i use ElsaDashboard successfully,I got the following errors:
![image](https://user-images.githubusercontent.com/20158277/77864390-d5559400-725a-11ea-89af-8ef15a72a7da.png)

I'm trying to combine ABP with elsa-core, and if you want to know more, I'll keep reporting.

**Comment by wangliqiang1026** [comment]
> @ wangliqiang1026大佬，为啥我在abp vnext模板的web层添加elsa提示我'Elsa.Dashboard.Areas.Elsa.Controllers.HomeController'尚未注册
> 
> 为什么提示我不要注册
> 
> ![图片](https://user-images.githubusercontent.com/20158277/77739260-2a6f8b00-704c-11ea-832f-ec1f3a112ecb.png)
> ![图片](https://user-images.githubusercontent.com/20158277/77739310-3eb38800-704c-11ea-9feb-8beda540fd0f.png)

the dynamic proxy interface used by abp vnext may be inconsistent with the MvcController that esla needs to register

**Comment by sfmskywalker** [comment]
Please do, Elsa need to work with ABP.

Looking at the stacktrace, it appears the NotifierFilter of the Dashboard application is causing the exception by casting something to a controller while it’s something else (FormDataApServiceProxy).

I’m not familiar with ABP, but perhaps if you’d have a look at the NotifierFilter you probably see what the issue is there.

**Comment by zrkcode** [comment]
you are right,i get error in NotifierFilter,i can skip 'Castle.Proxies' , Although, this is not a good solution
![image](https://user-images.githubusercontent.com/20158277/77921791-cca0a480-72d2-11ea-881a-d87fb638442e.png)

**Comment by sfmskywalker** [comment]
Indeed. Note however that you can already host a workflow server without UI if you want. Just don't do `AddElsaDashboard`. If you do need to use the dashboard, you can do so from a separate ASP.NET Core application and just do `AddElsaDashboard` without also doing `AddElsa`. Just make sure to connect to the same database.

With Elsa 2.0 the story will be better.

**Comment by sfmskywalker** [comment]
If you do want to use the dashboard together with ABP, we could abstract away access to TempData to a service. You could then have an ABP implementation that casts `obj` to `FormDataAppServiceProxy`, and a default MVC implementation that casts `obj` to `Controller`.

**Comment by zrkcode** [comment]
Thanks，I hope to see 2.0 .

**Comment by wjkhappy14** [comment]
Erwartungsvoll gespannt

**Comment by buzzlu** [comment]
I have got elsa-core working well with ABP Vnext module.
Here is my log:

### Part A : ConfigureServices 
   public override void ConfigureServices(ServiceConfigurationContext context)
        {
         ..........
            **// key point 1 : convert controller & viewcomponent as service. It's success key for workflow designer component**
            context.Services.AddMvc(options => options.EnableEndpointRouting = false).AddControllersAsServices().AddViewComponentsAsServices();
            context.Services.AddElsa(x => x.AddEntityFrameworkStores<PostgreSqlContext>(x => x.UseNpgsql(configuration.GetConnectionString("ElsaCore"))));
            **// key point 2: enable ElsaDashboard**
            context.Services.AddElsaDashboard();
        ...........
        }

### Part B :OnApplicationInitialization
public override void OnApplicationInitialization(ApplicationInitializationContext context)
        {
          .............................
            **// key point 3:  Enable static file**
            app.UseStaticFiles();
            **// key point 4:  enable contrllers in ElsaDashboard**
            app.UseEndpoints(endpoints => endpoints.MapControllers());
            app.UseWelcomePage();
            app.UseMvcWithDefaultRouteAndArea();
            // Register necessary ASP.NET Core middleware that triggers workflows containing HTTP activities. 
            app.UseHttpActivities();
           .............................
}

![image](https://user-images.githubusercontent.com/23555993/82524454-8c86d100-9b61-11ea-837f-1bdbb778e8bd.png)
![image](https://user-images.githubusercontent.com/23555993/82524499-b3450780-9b61-11ea-9310-b292cef46b9b.png)

**Comment by pest1999** [comment]
> 
> 
> I have got elsa-core working well with ABP Vnext module.
> Here is my log:
> ### Part A : ConfigureServices
> 
> public override void ConfigureServices(ServiceConfigurationContext context)
> {
> ..........
> **// key point 1 : convert controller & viewcomponent as service. It's success key for workflow designer component**
> context.Services.AddMvc(options => options.EnableEndpointRouting = false).AddControllersAsServices().AddViewComponentsAsServices();
> context.Services.AddElsa(x => x.AddEntityFrameworkStores(x => x.UseNpgsql(configuration.GetConnectionString("ElsaCore"))));
> **// key point 2: enable ElsaDashboard**
> context.Services.AddElsaDashboard();
> ...........
> }
> ### Part B :OnApplicationInitialization
> 
> public override void OnApplicationInitialization(ApplicationInitializationContext context)
> {
> .............................
> **// key point 3: Enable static file**
> app.UseStaticFiles();
> **// key point 4: enable contrllers in ElsaDashboard**
> app.UseEndpoints(endpoints => endpoints.MapControllers());
> app.UseWelcomePage();
> app.UseMvcWithDefaultRouteAndArea();
> // Register necessary ASP.NET Core middleware that triggers workflows containing HTTP activities.
> app.UseHttpActivities();
> .............................
> }
> 
> ![image](https://user-images.githubusercontent.com/23555993/82524454-8c86d100-9b61-11ea-837f-1bdbb778e8bd.png)
> ![image](https://user-images.githubusercontent.com/23555993/82524499-b3450780-9b61-11ea-9310-b292cef46b9b.png)
> ![image](https://user-images.githubusercontent.com/23555993/82524743-4b42f100-9b62-11ea-8124-5e0e84af03ba.png)
> ![image](https://user-images.githubusercontent.com/23555993/82524837-7dece980-9b62-11ea-8764-c67f77132f52.png)


I tried your way，but An error occurred
When I import a json file，the program is shutdown. I don't know what happened。
I used vnext and github.com/zrkcode/Elsa-Workflow-Issue ,the error is same. But github.com/elsa-workflows/elsa-samples has no error.

**Comment by buzzlu** [comment]
Could you check the log file of abp Vnext module?

We are implementing the ABP micro-service solution and integrated Elsa-Core successfully.  
And we have completed the integration test with Elsa-Core.  Our project will goes live on Dec. 2020.

Actually, Elsa-core is a really nice project except the issue for enable Elsa-workflow-designer with Vue.

**Comment by pest1999** [comment]
I get the same problem , How to solve it ?
Where I can override the method OnActionExecuted ？
The method Elsa.Dashboard.ActionFilters.NotifierFilter.OnActionExecuted is from nuget ,How to override  it ?
-------
> you are right,i get error in NotifierFilter,i can skip 'Castle.Proxies' , Although, this is not a good solution
> 
> ![image](https://user-images.githubusercontent.com/20158277/77921791-cca0a480-72d2-11ea-881a-d87fb638442e.png)
> 
> I'm looking forward to seeing Workflow Server without UI

**Comment by pest1999** [comment]
I think I get some mistake .
In debug mode I can't import files , but in production environment when I can import files ，no error has occurred.

Another question， do you have the same problem that zrkcode can't use api of abp when he use ElsaDashboard successfully


---- 
> Could you check the log file of abp Vnext module?
> 
> We are implementing the ABP micro-service solution and integrated Elsa-Core successfully.
> And we have completed the integration test with Elsa-Core. Our project will goes live on Dec. 2020.
> 
> Actually, Elsa-core is a really nice project except the issue for enable Elsa-workflow-designer with Vue.

**Comment by sfmskywalker** [comment]
This is no longer an issue with Elsa 2.0, which fetches activities from Elsa Server.
