### ISSUE TITLE
Unable to embed the designer in my own ASP.NET Core application

### ISSUE THREAD

**Issue by nmadrane** [elsa-workflows/elsa-core#2602]
Hi,

I tried to use the following tag :

`<elsa-workflow-definition-editor-screen server-url="@serverUrl" workflow-definition-id="41e37bc4a3bd4a0883d71dd004119256" monaco-lib-path="_content/Elsa.Designer.Components.Web/monaco-editor/min" />`

The designer appears and everything seems to work, except the Activity Picker  : the popup is empty.

It seems that I need to include others web components.

Could you please tell me which ones ? I couldn't find any documentation about this. My entry point was :

https://elsa-workflows.github.io/elsa-core/docs/next/installation/installing-elsa-designer

Thanks

**Comment by sfmskywalker** [comment]
When using 2.3 and greater, make sure to embed your component within the `<elsa-studio-root>` component. Example:

```html
<elsa-studio-root server-url="@serverUrl" monaco-lib-path="_content/Elsa.Designer.Components.Web/monaco-editor/min">
    <elsa-workflow-definition-editor-screen workflow-definition-id="41e37bc4a3bd4a0883d71dd004119256" />
</elsa-studio-root>
```
