### ISSUE TITLE
Activity Input property is null but designer shows a selected value when options are provided

### ISSUE THREAD

**Issue by mohdali** [elsa-workflows/elsa-core#2604]
When defining a property as an `ActivityInput` and providing it with options, the designer will show the options as a select box with the first option already selected.

However, the property remains null unless the selection is changed to a different value.

As a workaround, the property can be assigned a default value or the options may include a blank choice.

However, from user point of view it is misleading.

Example:

```cs
[ActivityInput(UIHint = ActivityInputUIHints.Dropdown, 
   Hint = "Select the Order By",
   Options = new[] { "ASC", "DESC" },
   SupportedSyntaxes = new[] { SyntaxNames.Literal, SyntaxNames.JavaScript, SyntaxNames.Liquid })]
public string OrderBy { get; set; }
```

It appears in the designer like this, which gives the impression that "ASC" is already selected. It will also not assign the value "ASC" unless the user changes to "DESC" then back to "ASC".
![image](https://user-images.githubusercontent.com/4145465/146679935-0898a770-bb72-4acb-a39c-5f92b4b0e7f8.png)

**Comment by mohdali** [comment]
hi @sfmskywalker, any plan for this bug? Earlier it was targeted for 2.5.

I have noticed something similar in Cron activity where the default syntax provided in the activity is not captured as an input unless it is changed to something else.

**Comment by sfmskywalker** [comment]
Hi, unfortunately I had to remove it to not delay 2.5 too much. I'm afraid I won't be able to get it in 2.6 either (which was originally slated as 2.5.1 for the end of last month). But let me assign it to the 2.7 milestone. And of course, if someone is able to work on this before 2.6 is released, it will be included as well :)

**Comment by sfmskywalker** [comment]
Yeah probably something like that. I remember this issue was solved for some other control in the past [like this](https://github.com/elsa-workflows/elsa-core/commit/29b382eced12571300278935a46e81c7dcf9f3a0#diff-3e16fd621b926f0d4ecd26d91097b6a0f01939cecdd11b08b8de01e23f263701).

**Comment by mohdali** [comment]
> Yeah probably something like that. I remember this issue was solved for some other control in the past [like this](https://github.com/elsa-workflows/elsa-core/commit/29b382eced12571300278935a46e81c7dcf9f3a0#diff-3e16fd621b926f0d4ecd26d91097b6a0f01939cecdd11b08b8de01e23f263701).

I will give it a try. Hopefully can get it done quickly.

**Comment by mohdali** [comment]
@sfmskywalker I made a quick fix and tested with Join Activity. Please check if my coding is proper for null checking etc. as I'm still a beginner when it comes to TypeScript.

**Comment by sfmskywalker** [comment]
Looks good to me 👍🏻
