### ISSUE TITLE
Update HTTP Activity with support for accepting Correlation ID as a header

### ISSUE THREAD

**Issue by sfmskywalker** [elsa-workflows/elsa-core#262]
See also: #261

**Comment by flew2bits** [comment]
Would this have to happen in TriggerRequestHandler? If so, it doesn't look like it would be too terribly difficult to implement.

However, what's the behavior in the case that `X-Correlation-Id` isn't a header? Do you include all matching workflow instances, or just those without a correlation id?

**Comment by sfmskywalker** [comment]
@flew2bits 

> Would this have to happen in TriggerRequestHandler? If so, it doesn't look like it would be too terribly difficult to implement.
Indeed, this would have to happen there. I also don't suspect this would be too hard to do.

> However, what's the behavior in the case that X-Correlation-Id isn't a header? Do you include all matching workflow instances, or just those without a correlation id?
Good question, I hadn't thought of that. I think it might make sense to include just those without a correlation ID.

**Comment by sfmskywalker** [comment]
Fixed in Elsa 2
