### ISSUE TITLE
Error when running docker compose

### ISSUE THREAD

**Issue by Woland2k** [elsa-workflows/elsa-core#2623]
Hi,

I get error when opening localhost:6868 after building and running docker image. Get it when using docker-compose and docker to start it. 

The error happens when the following file url is requested: https://localhost:15265/v1/features

![image](https://user-images.githubusercontent.com/1566470/147140655-9e71e335-3752-4f48-85c1-91eca5d9578f.png)

**Comment by Woland2k** [comment]
What happened here? Is it fixed or will be fixed in 2.4? Is it available already?

**Comment by sfmskywalker** [comment]
As you can see in the associated commit, the problem was with the docker-compose.yml file where it passes an incorrect environment variable.
