### ISSUE TITLE
Credential Management

### ISSUE THREAD

**Issue by jwillmer** [elsa-workflows/elsa-core#2626]
We need a central place to store credentials that can be used by the activities in order to not redefine them on every activity or worklfow.

In other apps there is a defined list of credential types (with different fields). Should our activities provide a blueprint for the credential type they need or should they pick from a defined list we add into the core? @sfmskywalker 

![image](https://user-images.githubusercontent.com/1503577/147254118-902a35b1-a18d-4745-9f9e-dfef4302e399.png)

**Comment by mohdali** [comment]
Yes, this is a great idea.

We have a use case for sending http requests where we need yo store different credentials for different Uris. We inject those to the Credentials cache.

**Comment by sfmskywalker** [comment]
How about this:

- We have a central store for **credentials** implemented from a new module called e.g. `Elsa.Secrets`.
- The credentials are exposed via a store called `ISecretStore`.
- There can be different implementations of `ISecretStore`, e.g. **Azure Keyvault** and others. Out of the box, we might provide a simple EF Core implementation.
- A secret has the following fields: **Name**, **Type** and *Data* where Data is a JSON blob.
- The module exposes an abstraction called `ISecretType` that other libraries implement. For example, `AmqpSecretType : ISecretType`.
- The `AmqpSecretType` would expose its credential data as public properties (e.g. `ConnectionString` and/or individual components of the connection string like `Hostname`, `Port`, `User`, `Password` and `TransportType`. 
- We expose an API endpoint that lists these implementations, similar to the way Activity Types are exposed to the workflow designer's activity picker.
- When creating a new secret, the user selects what type of secret they want to create (e.g. `AMQP`).
- Depending on the selected type, the dashboard dynamically displays the field inputs, similar to the way the Activity Editor dynamically builds a form based on the activity input properties associated with the activity type.

**Comment by BenSeymourODB** [comment]
Looks like this is being addressed under #2897.
