### ISSUE TITLE
Workflow Name in Instance list dropdown

### ISSUE THREAD

**Issue by mohdali** [elsa-workflows/elsa-core#2628]
Instance list drop down shows the V1 workflow name. However, workflow definition list and registry always show the latest version name.

If the workflow is renamed or didn't have a name in V1, it is hard to find it in the drop down list.

![image](https://user-images.githubusercontent.com/4145465/147266191-1436445b-4272-45b7-9ae9-c2adb72ca4fa.png)

![image](https://user-images.githubusercontent.com/4145465/147266217-bf5275e6-416d-48f9-a7c8-fe557e44136f.png)

**Comment by mohdali** [comment]
@sfmskywalker can this be fixed for 2.4 release?

**Comment by sfmskywalker** [comment]
I'm wondering what the desired name would be to be displayed in the Workflow dropdown list, if not the name of the latest version? If we display all versions of a given workflow definition, then the dropdown could become quite big.

**Comment by mohdali** [comment]
I think latest version is fine, that will be consistent with other displays. Currently it shows first version.
