### ISSUE TITLE
Can not click workflow menu like workflow instances. Version 2.3

### ISSUE THREAD

**Issue by rangga98** [elsa-workflows/elsa-core#2631]
sorry sir, when i try to click workflow instance or another, it throw an error like this, i don't know what to do, can you tell me what is it?. oh ya, i run elsa with this command:
docker run -t -i -e ELSA__SERVER__BASEURL='http://localhost:5000' -p 14000:80 elsaworkflows/elsa-dashboard-and-server:latest
![Screenshot_2](https://user-images.githubusercontent.com/69419754/147382095-27a8778a-4c1f-42f2-8472-21a3540b9ceb.jpg)

**Comment by sfmskywalker** [comment]
When running the `elsa-dashboard-and-server` image, make sure to use the same port for both the container as well as the server base url.

In other words, try this:

```
docker run -t -i -e ELSA__SERVER__BASEURL='http://localhost:14000' -p 14000:80 elsaworkflows/elsa-dashboard-and-server:latest
```

Furthermore, you may need to ensure you are not using an older, cached image. This happens to me regularly when I try to reproduce an issue with a docker image where I actually have to delete the image first before pulling a new one.

Lastly, make sure that you clear any & all cached static assets for the URL you are opening (CTRL + F5 should do the trick).

**Comment by rangga98** [comment]
i already copy this code
`docker run -t -i -e ELSA__SERVER__BASEURL='http://localhost:14000' -p 14000:80 elsaworkflows/elsa-dashboard-and-server:latest`
and delete all image and then run the application. i follow your tutorial in medium.
in my appsetting.json like this :
![Screenshot_5](https://user-images.githubusercontent.com/69419754/147382630-20a064a5-f1db-4949-9688-442528e2d502.jpg)
and then when i try to run the program , i can click elsa menu, but there is another error sir like this one:
![Screenshot_3](https://user-images.githubusercontent.com/69419754/147382641-877bf38d-1e01-4b46-888f-7814cd5f8391.jpg)
![Screenshot_4](https://user-images.githubusercontent.com/69419754/147382653-fc15fd7e-711f-4134-b3c0-530ef607c4fd.jpg)

**Comment by sfmskywalker** [comment]
I'm a little bit confused. So you are running the docker image as well as the project solution from the sample project?

**Comment by rangga98** [comment]
yes, i just follow your tutorial here, i already follow all the step and want to run the project but there is error,
https://sipkeschoorstra.medium.com/building-workflow-driven-net-applications-with-elsa-2-part-2-ab0ffae91b95

**Comment by rangga98** [comment]
i just want to create like this one, but there is error when i try by myself
![Screenshot_7](https://user-images.githubusercontent.com/69419754/147382833-35206190-4888-4bcf-9844-3bae08efd1f2.jpg)
![Screenshot_8](https://user-images.githubusercontent.com/69419754/147382837-c1a4559b-493c-401c-bace-5a853526a913.jpg)

**Comment by sfmskywalker** [comment]
I see.

You are running the DocumentManagement sample project as a workflow server, but also the Elsa docker image to use its dashboard to connect to said server.

Unfortunately, the docker image is built from latest source code, which means it's newer than the Elsa 2.3 version referenced by the DocumentManagament sample project.

To fix that, you can try updating the referenced Elsa packages to the 2.4-preview.xxx packages available from MyGet.
Then it should work.

I'll also push an update to the DocumentManagement sample project that references 2.4-preview.xxx packages. You can try and pull that sample if you want to try it.

**Comment by rangga98** [comment]
ok sir , let me try it. thank u,

**Comment by rangga98** [comment]
i already pull your code sir. t updates elsa to 2.4 preview-xxx.
![Screenshot_9](https://user-images.githubusercontent.com/69419754/147383192-56e18c6c-56bb-4422-8e23-0d21e95f0496.jpg)
i change the appsettings base url for elsa to port 14000, you said before that both the container as well as the server base url is the same. so i change the port in appsettings to 14000, and run docker file with this code:
`docker run -t -i -e ELSA__SERVER__BASEURL='http://localhost:14000' -p 14000:80 elsaworkflows/elsa-dashboard-and-server:latest`
when i try to run the program and open elsa dashboard, the error is still the same
![Screenshot_11](https://user-images.githubusercontent.com/69419754/147383249-d0ae12a7-6eef-4d11-9cbc-6b2be9793927.jpg)
:
do i miss something sir?

**Comment by sfmskywalker** [comment]
> you said before that both the container as well as the server base url is the same

Indeed, but that is only the case when you run the `elsaworkflows/elsa-dashboard-and-server:latest` image, which provides both the dashboard **and** the workflow server.

But in your case, you want just the `elsaworkflows/elsa-dashboard:latest` image, in which case you do need to provide a different server URL to point to the workflow server (which is the DocumentManagement project).

For example, if you run the DocumentManagement project at `http://localhost:5000`, then the docker command should be:

```
docker run -t -i -e ELSA__SERVER__BASEADDRESS=http://localhost:5000 -p 14000:80 elsaworkflows/elsa-dashboard:latest
```

That will then host the dashboard application on port 14000, while the dashboard itself will connect to your workflow server listening at `http://localhost:5000`.

**Comment by rangga98** [comment]
oke thanks sir, the app run well now
