### ISSUE TITLE
Static content not found

### ISSUE THREAD

**Issue by bamdad-b** [elsa-workflows/elsa-core#2637]
Hi. I'm trying to use ELSA dashboard in my asp.net core web project.
The links in _Host file cannot be found.
![image](https://user-images.githubusercontent.com/33001312/147451430-38d92e55-435c-4c39-a313-92c391628794.png)
I have double checked everything and also followed the suggested workarounds in [issue808](https://github.com/elsa-workflows/elsa-core/issues/808) and other similar issues.
Running the default sample "ElsaDashboard.Samples.AspNetCore.Monolith" also gives me the same result.
Please help me solve the issue, thank you for the interesting framework.

**Comment by mohdali** [comment]
If you are building from source, you need to build the assets.

You can achieve that by executing `.\build-assets.ps1` from solution folder.

**Comment by bamdad-b** [comment]
Yes I am building from the source, executing `.\build-assets.ps1` did the trick. Thank you Mohamed Ali.
Please consider updating documentations. There seem to be no information about this matter as far as I know.

**Comment by sfmskywalker** [comment]
Actually there is: https://github.com/elsa-workflows/elsa-core#building-from-source 😄 
But I understand it's not easily discoverable and it should be added to the documentation website so that it becomes (hopefully) more visible.
