### ISSUE TITLE
MongoCommandException: command aggregate failed: sort executed memory limit of 104857600 bytes, but did not opt in to external sorting.

### ISSUE THREAD

**Issue by viswajwalith-exceego** [elsa-workflows/elsa-core#2639]
We are using the Elsa(1.5.5.1943)  in our application and after having some Workflows configured and executed getting the below exception 
"MongoCommandException: command aggregate failed: sort executed memory limit of 104857600 bytes, but did not opt in to external sorting." Do we have any work around for this? actually we might need to set the allowDiskUse: true while fetching the data. we have any configurations for this?  Please advice. 

![MicrosoftTeams-image](https://user-images.githubusercontent.com/80587814/147542278-27328756-8bf1-46db-a47f-93fd4e6dec9a.png)

**Comment by sfmskywalker** [comment]
Not sure what's causing this, but one thing I do know is that in Elsa 1, workflow execution log entries are stored as part of the WorkflowInstances document collection. Perhaps the execution log became too big (the longer a workflow executes, the more rows will be added).

Perhaps it's something else. In any case, the best thing you could do is migrate to Elsa 2. Or wait for Elsa 3 if you don't want to migrate twice. Depending also on when you need a working solution - Elsa 3 alpha is still ways off - maybe around March.
