### ISSUE TITLE
Missing elsa-workflow-designer.esm.js

### ISSUE THREAD

**Issue by arifkhannz** [elsa-workflows/elsa-core#265]
In Dashboard's _Layout.cshtml, the following link does not resolve:

~/_content/Elsa.Dashboard/assets/js/plugins/elsa-workflows/elsa-workflow-designer/elsa-workflow-designer.esm.js"

Gulp build was run but the above seems to be missing. And cannot create workflows.

Thanks

**Comment by sfmskywalker** [comment]
There was [an issue with the master branch](https://github.com/elsa-workflows/elsa-core/commit/707eed6f6ff356f4ea959e04287760d72bfb3f24) (the develop branch still contains this issue). Which version are you using? Which branch, and which commit?

**Comment by arifkhannz** [comment]
Ok. I used develop branch with commit: 8ec4323.

Thanks
