### ISSUE TITLE
Scripting Client GetTypeScriptDefinitionFileAsync returns 405

### ISSUE THREAD

**Issue by dominicasley** [elsa-workflows/elsa-core#2650]

**Comment by dominicasley** [comment]
Pull request ready to resolve https://github.com/elsa-workflows/elsa-core/pull/2648

**Comment by Jejuni** [comment]
Once this is merged, will the npm package `@elsa-workflows/elsa-workflows-studio` also be updated?

Spent about an hour debugging why I couldn't add HttpEndpoints anymore...

![image](https://user-images.githubusercontent.com/33608497/148251304-5d27915c-0da0-4f26-b745-a95785d91502.png)

**Comment by sfmskywalker** [comment]
Not automatically unfortunately - one has to manually increment the version number in package.json. I'll do that right now.

**Comment by sfmskywalker** [comment]
I pushed an update. Once the GitHub Action thing finishes, version `2.4.0` should appear on NPM.

**Comment by sfmskywalker** [comment]
Fixed in 6d332c19524bebe49f92a30602f0450810375a64
