### ISSUE TITLE
Composite Activities are not visible in ELSA Dashboard in version 2.4.1-preview.11

### ISSUE THREAD

**Issue by OlegLukash** [elsa-workflows/elsa-core#2651]
Hi all! I have updated to 2.4.1-preview.11 from 2.3.0 version. Found a problem that CompositeActivities are not visible anymore in Elsa Dashboard when want to create a new workflow. Has somebody faced this issue? Custom Composite Activities inherit from CompositeActivity class and is registered in DI as was when used 2.3.0 version. PS. Also updated the project to .NET 6.
Simple Activities are visible

**Comment by jdevillard** [comment]
Try to specify [Browsable(True)] in head of your custom composite activity.

**Comment by OlegLukash** [comment]
it works. thanks a million
