### ISSUE TITLE
Adding possibility to hide sensitive properties in dashboard

### ISSUE THREAD

**Issue by mlditga** [elsa-workflows/elsa-core#2659]
Hi,

Would it be possible to add a way to hide some activity properties from dashboard? Activities may use sensitive inputs (token, passwords). It would be great to block them from displaying when viewing workflow instance (activity state and variables).

![elsa](https://user-images.githubusercontent.com/97239426/148567160-bcae6624-11d9-41d0-8a72-939caeba2ea4.PNG)

Thank you!

**Comment by sfmskywalker** [comment]
I just found the issue that would enable this: #1587

Closing this one as a "duplicate" but feel free to continue the discussion in #1587

**Comment by sfmskywalker** [comment]
I was wrong about the issue #1587 also handling this specific issue, since this issue is about activity state, not execution log. But we can implement a similar solution.

**Comment by sfmskywalker** [comment]
See https://github.com/elsa-workflows/elsa-core/tree/master/src/samples/aspnet/Elsa.Samples.MaskPii for an example.
