### ISSUE TITLE
Client error when rendering workflow journal

### ISSUE THREAD

**Issue by tomy2105** [elsa-workflows/elsa-core#2662]
Elsa 2.0 from NuGet, I got following client error and journal is not rendered, could you please help me investigate why....

TypeError: y is undefined
    renderJournalTab https://example.com/_content/Elsa.Designer.Components.Web/elsa-workflows-studio/p-22305dbb.entry.js:1
    renderJournalTab https://example.com/_content/Elsa.Designer.Components.Web/elsa-workflows-studio/p-22305dbb.entry.js:1
    renderPanel https://example.com/_content/Elsa.Designer.Components.Web/elsa-workflows-studio/p-22305dbb.entry.js:1
    render https://example.com/_content/Elsa.Designer.Components.Web/elsa-workflows-studio/p-22305dbb.entry.js:1
    Y https://example.com/_content/Elsa.Designer.Components.Web/elsa-workflows-studio/p-2ef56300.js:1
    X https://example.com/_content/Elsa.Designer.Components.Web/elsa-workflows-studio/p-2ef56300.js:1
    Q https://example.com/_content/Elsa.Designer.Components.Web/elsa-workflows-studio/p-2ef56300.js:1
    promise callback*oe https://example.com/_content/Elsa.Designer.Components.Web/elsa-workflows-studio/p-2ef56300.js:1
    Q https://example.com/_content/Elsa.Designer.Components.Web/elsa-workflows-studio/p-2ef56300.js:1
    K https://example.com/_content/Elsa.Designer.Components.Web/elsa-workflows-studio/p-2ef56300.js:1
    je https://example.com/_content/Elsa.Designer.Components.Web/elsa-workflows-studio/p-2ef56300.js:1
    Se https://example.com/_content/Elsa.Designer.Components.Web/elsa-workflows-studio/p-2ef56300.js:1
    raf https://example.com/_content/Elsa.Designer.Components.Web/elsa-workflows-studio/p-2ef56300.js:1
    ke https://example.com/_content/Elsa.Designer.Components.Web/elsa-workflows-studio/p-2ef56300.js:1
    K https://example.com/_content/Elsa.Designer.Components.Web/elsa-workflows-studio/p-2ef56300.js:1
    o https://example.com/_content/Elsa.Designer.Components.Web/elsa-workflows-studio/p-2ef56300.js:1
    connectedCallback https://example.com/_content/Elsa.Designer.Components.Web/elsa-workflows-studio/p-2ef56300.js:1
    connectedCallback https://example.com/_content/Elsa.Designer.Components.Web/elsa-workflows-studio/p-2ef56300.js:1
    connectedCallback https://example.com/_content/Elsa.Designer.Components.Web/elsa-workflows-studio/p-2ef56300.js:1
    jmp https://example.com/_content/Elsa.Designer.Components.Web/elsa-workflows-studio/p-2ef56300.js:1
    connectedCallback https://example.com/_content/Elsa.Designer.Components.Web/elsa-workflows-studio/p-2ef56300.js:1
    E https://example.com/_content/Elsa.Designer.Components.Web/elsa-workflows-studio/p-2ef56300.js:1
    F https://example.com/_content/Elsa.Designer.Components.Web/elsa-workflows-studio/p-2ef56300.js:1
    Y https://example.com/_content/Elsa.Designer.Components.Web/elsa-workflows-studio/p-2ef56300.js:1
    Y https://example.com/_content/Elsa.Designer.Components.Web/elsa-workflows-studio/p-2ef56300.js:1
    X https://example.com/_content/Elsa.Designer.Components.Web/elsa-workflows-studio/p-2ef56300.js:1
    Q https://example.com/_content/Elsa.Designer.Components.Web/elsa-workflows-studio/p-2ef56300.js:1
    promise callback*oe https://example.com/_content/Elsa.Designer.Components.Web/elsa-workflows-studio/p-2ef56300.js:1
    Q https://example.com/_content/Elsa.Designer.Components.Web/elsa-workflows-studio/p-2ef56300.js:1
    K https://example.com/_content/Elsa.Designer.Components.Web/elsa-workflows-studio/p-2ef56300.js:1
    je https://example.com/_content/Elsa.Designer.Components.Web/elsa-workflows-studio/p-2ef56300.js:1
    Se https://example.com/_content/Elsa.Designer.Components.Web/elsa-workflows-studio/p-2ef56300.js:1
    raf https://example.com/_content/Elsa.Designer.Components.Web/elsa-workflows-studio/p-2ef56300.js:1
    ke https://example.com/_content/Elsa.Designer.Components.Web/elsa-workflows-studio/p-2ef56300.js:1
    K https://example.com/_content/Elsa.Designer.Components.Web/elsa-workflows-studio/p-2ef56300.js:1
    o https://example.com/_content/Elsa.Designer.Components.Web/elsa-workflows-studio/p-2ef56300.js:1
    connectedCallback https://example.com/_content/Elsa.Designer.Components.Web/elsa-workflows-studio/p-2ef56300.js:1
    connectedCallback https://example.com/_content/Elsa.Designer.Components.Web/elsa-workflows-studio/p-2ef56300.js:1
    connectedCallback https://example.com/_content/Elsa.Designer.Components.Web/elsa-workflows-studio/p-2ef56300.js:1
    jmp https://example.com/_content/Elsa.Designer.Components.Web/elsa-workflows-studio/p-2ef56300.js:1
    connectedCallback https://example.com/_content/Elsa.Designer.Components.Web/elsa-workflows-studio/p-2ef56300.js:1
    E https://example.com/_content/Elsa.Designer.Components.Web/elsa-workflows-studio/p-2ef56300.js:1
    F https://example.com/_content/Elsa.Designer.Components.Web/elsa-workflows-studio/p-2ef56300.js:1
    Y https://example.com/_content/Elsa.Designer.Components.Web/elsa-workflows-studio/p-2ef56300.js:1
    Y https://example.com/_content/Elsa.Designer.Components.Web/elsa-workflows-studio/p-2ef56300.js:1
    X https://example.com/_content/Elsa.Designer.Components.Web/elsa-workflows-studio/p-2ef56300.js:1
    Q https://example.com/_content/Elsa.Designer.Components.Web/elsa-workflows-studio/p-2ef56300.js:1
    oe https://example.com/_content/Elsa.Designer.Components.Web/elsa-workflows-studio/p-2ef56300.js:1
    Q https://example.com/_content/Elsa.Designer.Components.Web/elsa-workflows-studio/p-2ef56300.js:1
    K https://example.com/_content/Elsa.Designer.Components.Web/elsa-workflows-studio/p-2ef56300.js:1
    je https://example.com/_content/Elsa.Designer.Components.Web/elsa-workflows-studio/p-2ef56300.js:1
    Se https://example.com/_content/Elsa.Designer.Components.Web/elsa-workflows-studio/p-2ef56300.js:1
    raf https://example.com/_content/Elsa.Designer.Components.Web/elsa-workflows-studio/p-2ef56300.js:1
    ke https://example.com/_content/Elsa.Designer.Components.Web/elsa-workflows-studio/p-2ef56300.js:1
    K https://example.com/_content/Elsa.Designer.Components.Web/elsa-workflows-studio/p-2ef56300.js:1
    o https://example.com/_content/Elsa.Designer.Components.Web/elsa-workflows-studio/p-2ef56300.js:1
 
<elsa-workflow-instance-journal>
p-2ef56300.js:1:11951
    he https://example.com/_content/Elsa.Designer.Components.Web/elsa-workflows-studio/p-2ef56300.js:1
    Y https://example.com/_content/Elsa.Designer.Components.Web/elsa-workflows-studio/p-2ef56300.js:1
    X https://example.com/_content/Elsa.Designer.Components.Web/elsa-workflows-studio/p-2ef56300.js:1
    Q https://example.com/_content/Elsa.Designer.Components.Web/elsa-workflows-studio/p-2ef56300.js:1
    (Async: promise callback)
    oe https://example.com/_content/Elsa.Designer.Components.Web/elsa-workflows-studio/p-2ef56300.js:1
    Q https://example.com/_content/Elsa.Designer.Components.Web/elsa-workflows-studio/p-2ef56300.js:1
    K https://example.com/_content/Elsa.Designer.Components.Web/elsa-workflows-studio/p-2ef56300.js:1
    je https://example.com/_content/Elsa.Designer.Components.Web/elsa-workflows-studio/p-2ef56300.js:1
    Se https://example.com/_content/Elsa.Designer.Components.Web/elsa-workflows-studio/p-2ef56300.js:1
    (Async: FrameRequestCallback)
    raf https://example.com/_content/Elsa.Designer.Components.Web/elsa-workflows-studio/p-2ef56300.js:1
    ke https://example.com/_content/Elsa.Designer.Components.Web/elsa-workflows-studio/p-2ef56300.js:1
    K https://example.com/_content/Elsa.Designer.Components.Web/elsa-workflows-studio/p-2ef56300.js:1
    o https://example.com/_content/Elsa.Designer.Components.Web/elsa-workflows-studio/p-2ef56300.js:1
    connectedCallback https://example.com/_content/Elsa.Designer.Components.Web/elsa-workflows-studio/p-2ef56300.js:1
    connectedCallback https://example.com/_content/Elsa.Designer.Components.Web/elsa-workflows-studio/p-2ef56300.js:1
    connectedCallback https://example.com/_content/Elsa.Designer.Components.Web/elsa-workflows-studio/p-2ef56300.js:1
    jmp https://example.com/_content/Elsa.Designer.Components.Web/elsa-workflows-studio/p-2ef56300.js:1
    connectedCallback https://example.com/_content/Elsa.Designer.Components.Web/elsa-workflows-studio/p-2ef56300.js:1
    E https://example.com/_content/Elsa.Designer.Components.Web/elsa-workflows-studio/p-2ef56300.js:1
    F https://example.com/_content/Elsa.Designer.Components.Web/elsa-workflows-studio/p-2ef56300.js:1
    Y https://example.com/_content/Elsa.Designer.Components.Web/elsa-workflows-studio/p-2ef56300.js:1
    Y https://example.com/_content/Elsa.Designer.Components.Web/elsa-workflows-studio/p-2ef56300.js:1
    X https://example.com/_content/Elsa.Designer.Components.Web/elsa-workflows-studio/p-2ef56300.js:1
    Q https://example.com/_content/Elsa.Designer.Components.Web/elsa-workflows-studio/p-2ef56300.js:1
    (Async: promise callback)
    oe https://example.com/_content/Elsa.Designer.Components.Web/elsa-workflows-studio/p-2ef56300.js:1
    Q https://example.com/_content/Elsa.Designer.Components.Web/elsa-workflows-studio/p-2ef56300.js:1
    K https://example.com/_content/Elsa.Designer.Components.Web/elsa-workflows-studio/p-2ef56300.js:1
    je https://example.com/_content/Elsa.Designer.Components.Web/elsa-workflows-studio/p-2ef56300.js:1
    Se https://example.com/_content/Elsa.Designer.Components.Web/elsa-workflows-studio/p-2ef56300.js:1
    (Async: FrameRequestCallback)
    raf https://example.com/_content/Elsa.Designer.Components.Web/elsa-workflows-studio/p-2ef56300.js:1
    ke https://example.com/_content/Elsa.Designer.Components.Web/elsa-workflows-studio/p-2ef56300.js:1
    K https://example.com/_content/Elsa.Designer.Components.Web/elsa-workflows-studio/p-2ef56300.js:1
    o https://example.com/_content/Elsa.Designer.Components.Web/elsa-workflows-studio/p-2ef56300.js:1
    connectedCallback https://example.com/_content/Elsa.Designer.Components.Web/elsa-workflows-studio/p-2ef56300.js:1
    connectedCallback https://example.com/_content/Elsa.Designer.Components.Web/elsa-workflows-studio/p-2ef56300.js:1
    connectedCallback https://example.com/_content/Elsa.Designer.Components.Web/elsa-workflows-studio/p-2ef56300.js:1
    jmp https://example.com/_content/Elsa.Designer.Components.Web/elsa-workflows-studio/p-2ef56300.js:1
    connectedCallback https://example.com/_content/Elsa.Designer.Components.Web/elsa-workflows-studio/p-2ef56300.js:1
    E https://example.com/_content/Elsa.Designer.Components.Web/elsa-workflows-studio/p-2ef56300.js:1
    F https://example.com/_content/Elsa.Designer.Components.Web/elsa-workflows-studio/p-2ef56300.js:1
    Y https://example.com/_content/Elsa.Designer.Components.Web/elsa-workflows-studio/p-2ef56300.js:1
    Y https://example.com/_content/Elsa.Designer.Components.Web/elsa-workflows-studio/p-2ef56300.js:1
    X https://example.com/_content/Elsa.Designer.Components.Web/elsa-workflows-studio/p-2ef56300.js:1
    Q https://example.com/_content/Elsa.Designer.Components.Web/elsa-workflows-studio/p-2ef56300.js:1
    oe https://example.com/_content/Elsa.Designer.Components.Web/elsa-workflows-studio/p-2ef56300.js:1
    Q https://example.com/_content/Elsa.Designer.Components.Web/elsa-workflows-studio/p-2ef56300.js:1
    K https://example.com/_content/Elsa.Designer.Components.Web/elsa-workflows-studio/p-2ef56300.js:1
    je https://example.com/_content/Elsa.Designer.Components.Web/elsa-workflows-studio/p-2ef56300.js:1
    Se https://example.com/_content/Elsa.Designer.Components.Web/elsa-workflows-studio/p-2ef56300.js:1
    (Async: FrameRequestCallback)
    raf https://example.com/_content/Elsa.Designer.Components.Web/elsa-workflows-studio/p-2ef56300.js:1
    ke https://example.com/_content/Elsa.Designer.Components.Web/elsa-workflows-studio/p-2ef56300.js:1
    K https://example.com/_content/Elsa.Designer.Components.Web/elsa-workflows-studio/p-2ef56300.js:1
    o https://example.com/_content/Elsa.Designer.Components.Web/elsa-workflows-studio/p-2ef56300.js:1

**Comment by sfmskywalker** [comment]
I would if I could, but this is not much to go by. Also, odds are it's fixed already with 2.4. Maybe you can try that?

**Comment by tomy2105** [comment]
Unfortunately due to number of changes from 2.0 to 2.1 I haven't moved from 2.0 yet :(.
