### ISSUE TITLE
Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'filter')

### ISSUE THREAD

**Issue by oacostam** [elsa-workflows/elsa-core#2663]
Using elsa docker image 2.4.0 with Chrome Version 96.0.4664.110 (Official Build) (64-bit) Windows 10
Steps to reproduce.
Run docker image:
docker run -t -i -e ELSA__SERVER__BASEURL='http://localhost:13000' -p 13000:80 elsaworkflows/elsa-dashboard-and-server:latest
Navigate to http://localhost:13000/workflow-registry
Nothing happens, and this error shows on js console:
```
Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'filter')
    at n.loadWorkflowDefinitions (p-20394db3.entry.js:1)
    at async n.componentWillLoad (p-20394db3.entry.js:1)
```

**Comment by yangmingjie** [comment]
I got the same problem, did you fix it?

**Comment by sfmskywalker** [comment]
What docker image was used specifically? There are two versions: one is the dashboard, another is dashboard + server.

**Comment by Z3roCoder** [comment]
I am receiving the following errors when going to "Workflow Registry" and then click "Create Workflow"

```
p-8e94f51c.js:1 TypeError: Cannot read properties of undefined (reading 'find')
    at g.renderTestPanel (p-0542cb54.entry.js:1:28562)
    at g.renderPanel (p-0542cb54.entry.js:1:28475)
    at g.renderCanvas (p-0542cb54.entry.js:1:20546)
    at g.render (p-0542cb54.entry.js:1:18687)
    at Z (p-8e94f51c.js:1:7218)
    at Y (p-8e94f51c.js:1:7049)
    at p-8e94f51c.js:1:6620 <elsa-workflow-definition-editor-screen class=​"hydrated">​</elsa-workflow-definition-editor-screen>​
ye @ p-8e94f51c.js:1
Z @ p-8e94f51c.js:1
Y @ p-8e94f51c.js:1
(anonymous) @ p-8e94f51c.js:1
Promise.then (async)
se @ p-8e94f51c.js:1
X @ p-8e94f51c.js:1
(anonymous) @ p-8e94f51c.js:1
Se @ p-8e94f51c.js:1
Oe @ p-8e94f51c.js:1
requestAnimationFrame (async)
raf @ p-8e94f51c.js:1
(anonymous) @ p-8e94f51c.js:1
Q @ p-8e94f51c.js:1
r @ p-8e94f51c.js:1
(anonymous) @ p-8e94f51c.js:1
await in (anonymous) (async)
(anonymous) @ p-8e94f51c.js:1
(anonymous) @ p-8e94f51c.js:1
jmp @ p-8e94f51c.js:1
connectedCallback @ p-8e94f51c.js:1
W @ p-8e94f51c.js:1
H @ p-8e94f51c.js:1
(anonymous) @ p-8e94f51c.js:1
Z @ p-8e94f51c.js:1
Y @ p-8e94f51c.js:1
(anonymous) @ p-8e94f51c.js:1
se @ p-8e94f51c.js:1
X @ p-8e94f51c.js:1
(anonymous) @ p-8e94f51c.js:1
Se @ p-8e94f51c.js:1
Oe @ p-8e94f51c.js:1
requestAnimationFrame (async)
raf @ p-8e94f51c.js:1
(anonymous) @ p-8e94f51c.js:1
Q @ p-8e94f51c.js:1
r @ p-8e94f51c.js:1
(anonymous) @ p-8e94f51c.js:1
await in (anonymous) (async)
(anonymous) @ p-8e94f51c.js:1
(anonymous) @ p-8e94f51c.js:1
jmp @ p-8e94f51c.js:1
connectedCallback @ p-8e94f51c.js:1
W @ p-8e94f51c.js:1
H @ p-8e94f51c.js:1
(anonymous) @ p-8e94f51c.js:1
Z @ p-8e94f51c.js:1
Y @ p-8e94f51c.js:1
(anonymous) @ p-8e94f51c.js:1
se @ p-8e94f51c.js:1
X @ p-8e94f51c.js:1
(anonymous) @ p-8e94f51c.js:1
Se @ p-8e94f51c.js:1
Oe @ p-8e94f51c.js:1
requestAnimationFrame (async)
raf @ p-8e94f51c.js:1
(anonymous) @ p-8e94f51c.js:1
Q @ p-8e94f51c.js:1
(anonymous) @ p-8e94f51c.js:1
set @ p-8e94f51c.js:1
(anonymous) @ p-08d4b688.entry.js:1
a @ p-08d4b688.entry.js:1
(anonymous) @ p-08d4b688.entry.js:1
notifyListeners @ p-08d4b688.entry.js:1
g @ p-08d4b688.entry.js:1
(anonymous) @ p-08d4b688.entry.js:1
confirmTransitionTo @ p-08d4b688.entry.js:1
push @ p-08d4b688.entry.js:1
handleClick @ p-08d4b688.entry.js:1
p-0542cb54.entry.js:1 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'querySelector')
    at g.componentDidLoad (p-0542cb54.entry.js:1:11801)
    at oe (p-8e94f51c.js:1:8506)
    at te (p-8e94f51c.js:1:8181)
    at n (p-8e94f51c.js:1:7118)
    at Y (p-8e94f51c.js:1:7137)
    at p-8e94f51c.js:1:6620
```

**Comment by Z3roCoder** [comment]
I have been using the Docker Image from your ReadMe.md - elsaworkflows/elsa-dashboard-and-server:latest

**Comment by oacostam** [comment]
Hi @sfmskywalker As stated in my bug report, I was running docker image elsaworkflows/elsa-dashboard-and-server:latest been "latest" version 2.4.0
Kind regards.

**Comment by sfmskywalker** [comment]
You're absolutely right, I overlooked.

I just tried to reproduce, but I am not getting any errors.
In case you have tried the image before in the past, you might try the following:

- Make sure to pull the latest image. I use Docker for Desktop to do this. Latest image is 4 days old.
- Clear your browser cache.

**Comment by Z3roCoder** [comment]
> You're absolutely right, I overlooked.
> 
> I just tried to reproduce, but I am not getting any errors. In case you have tried the image before in the past, you might try the following:
> 
> * Make sure to pull the latest image. I use Docker for Desktop to do this. Latest image is 4 days old.
> * Clear your browser cache.

Neither of these work, sadly.
Older images don't work either. 
I'm using Docker on a Windows 10 Host.
No errors in console but in the Web Designer Application.

Is there any way I can provide you with some more info?

**Comment by sfmskywalker** [comment]
That's really strange. Can you send me the docker image ID you are using? Just to doublecheck that we are testing the exact same image.

**Comment by sfmskywalker** [comment]
Here's what I am using:

![image](https://user-images.githubusercontent.com/938393/148955908-d33b5dda-8642-481c-b235-942c5eb8ce8c.png)

**Comment by Z3roCoder** [comment]
Sure thing.

I am using the following command to run things:
`docker run -t -i -e ELSA__SERVER__BASEURL='http://localhost:13000' -p 13000:80 elsaworkflows/elsa-dashboard-and-server:latest`

Docker Image:
![image](https://user-images.githubusercontent.com/10726046/148957975-c1a1bb8c-43be-487c-ad28-b1649a742cdb.png)

Showcase Video:

https://user-images.githubusercontent.com/10726046/148958402-18ad293d-1cea-4317-9be8-fc8b2408591e.mp4



Logs:

```
{"EventId":60,"LogLevel":"Warning","Category":"Microsoft.AspNetCore.DataProtection.Repositories.FileSystemXmlRepository","Message":"Storing keys in a directory \u0027/root/.aspnet/DataProtection-Keys\u0027 that may not be persisted outside of the container. Protected data will be unavailable when container is destroyed.","State":{"Message":"Storing keys in a directory \u0027/root/.aspnet/DataProtection-Keys\u0027 that may not be persisted outside of the container. Protected data will be unavailable when container is destroyed.","path":"/root/.aspnet/DataProtection-Keys","{OriginalFormat}":"Storing keys in a directory \u0027{path}\u0027 that may not be persisted outside of the container. Protected data will be unavailable when container is destroyed."}}
{"EventId":35,"LogLevel":"Warning","Category":"Microsoft.AspNetCore.DataProtection.KeyManagement.XmlKeyManager","Message":"No XML encryptor configured. Key {827bd4dd-ac2f-47b8-b0cf-74fabc1deab5} may be persisted to storage in unencrypted form.","State":{"Message":"No XML encryptor configured. Key {827bd4dd-ac2f-47b8-b0cf-74fabc1deab5} may be persisted to storage in unencrypted form.","KeyId":"827bd4dd-ac2f-47b8-b0cf-74fabc1deab5","{OriginalFormat}":"No XML encryptor configured. Key {KeyId:B} may be persisted to storage in unencrypted form."}}
{"EventId":30000,"LogLevel":"Warning","Category":"Microsoft.EntityFrameworkCore.Model.Validation","Message":"The entity type \u0027Bookmark\u0027 is configured to use schema \u0027Elsa\u0027, but SQLite does not support schemas. This configuration will be ignored by the SQLite provider.","State":{"Message":"The entity type \u0027Bookmark\u0027 is configured to use schema \u0027Elsa\u0027, but SQLite does not support schemas. This configuration will be ignored by the SQLite provider.","entityType":"Bookmark","schema":"Elsa","{OriginalFormat}":"The entity type \u0027{entityType}\u0027 is configured to use schema \u0027{schema}\u0027, but SQLite does not support schemas. This configuration will be ignored by the SQLite provider."}}
{"EventId":30000,"LogLevel":"Warning","Category":"Microsoft.EntityFrameworkCore.Model.Validation","Message":"The entity type \u0027WorkflowDefinition\u0027 is configured to use schema \u0027Elsa\u0027, but SQLite does not support schemas. This configuration will be ignored by the SQLite provider.","State":{"Message":"The entity type \u0027WorkflowDefinition\u0027 is configured to use schema \u0027Elsa\u0027, but SQLite does not support schemas. This configuration will be ignored by the SQLite provider.","entityType":"WorkflowDefinition","schema":"Elsa","{OriginalFormat}":"The entity type \u0027{entityType}\u0027 is configured to use schema \u0027{schema}\u0027, but SQLite does not support schemas. This configuration will be ignored by the SQLite provider."}}
{"EventId":30000,"LogLevel":"Warning","Category":"Microsoft.EntityFrameworkCore.Model.Validation","Message":"The entity type \u0027WorkflowExecutionLogRecord\u0027 is configured to use schema \u0027Elsa\u0027, but SQLite does not support schemas. This configuration will be ignored by the SQLite provider.","State":{"Message":"The entity type \u0027WorkflowExecutionLogRecord\u0027 is configured to use schema \u0027Elsa\u0027, but SQLite does not support schemas. This configuration will be ignored by the SQLite provider.","entityType":"WorkflowExecutionLogRecord","schema":"Elsa","{OriginalFormat}":"The entity type \u0027{entityType}\u0027 is configured to use schema \u0027{schema}\u0027, but SQLite does not support schemas. This configuration will be ignored by the SQLite provider."}}
{"EventId":30000,"LogLevel":"Warning","Category":"Microsoft.EntityFrameworkCore.Model.Validation","Message":"The entity type \u0027WorkflowInstance\u0027 is configured to use schema \u0027Elsa\u0027, but SQLite does not support schemas. This configuration will be ignored by the SQLite provider.","State":{"Message":"The entity type \u0027WorkflowInstance\u0027 is configured to use schema \u0027Elsa\u0027, but SQLite does not support schemas. This configuration will be ignored by the SQLite provider.","entityType":"WorkflowInstance","schema":"Elsa","{OriginalFormat}":"The entity type \u0027{entityType}\u0027 is configured to use schema \u0027{schema}\u0027, but SQLite does not support schemas. This configuration will be ignored by the SQLite provider."}}
{"EventId":14,"LogLevel":"Information","Category":"Microsoft.Hosting.Lifetime","Message":"Now listening on: http://[::]:80","State":{"Message":"Now listening on: http://[::]:80","address":"http://[::]:80","{OriginalFormat}":"Now listening on: {address}"}}
{"EventId":0,"LogLevel":"Information","Category":"Microsoft.Hosting.Lifetime","Message":"Application started. Press Ctrl\u002BC to shut down.","State":{"Message":"Application started. Press Ctrl\u002BC to shut down.","{OriginalFormat}":"Application started. Press Ctrl\u002BC to shut down."}}
{"EventId":0,"LogLevel":"Information","Category":"Microsoft.Hosting.Lifetime","Message":"Hosting environment: Production","State":{"Message":"Hosting environment: Production","envName":"Production","{OriginalFormat}":"Hosting environment: {envName}"}}
{"EventId":0,"LogLevel":"Information","Category":"Microsoft.Hosting.Lifetime","Message":"Content root path: /app","State":{"Message":"Content root path: /app","contentRoot":"/app","{OriginalFormat}":"Content root path: {contentRoot}"}}
{"EventId":0,"LogLevel":"Information","Category":"Microsoft.Hosting.Lifetime","Message":"Application is shutting down...","State":{"Message":"Application is shutting down...","{OriginalFormat}":"Application is shutting down..."}}

```

**Comment by Z3roCoder** [comment]
```
async loadWorkflowDefinitions() {
        const e = await this.createClient()
          , s = await e.workflowDefinitionsApi.list(0, 50, {
            isLatest: !0
        })
          , t = s.items.filter((e=>!e.isPublished)).map((e=>e.definitionId));
        this.publishedWorkflowDefinitions = await e.workflowDefinitionsApi.getMany(t, {
            isPublished: !0
        }),
        this.workflowDefinitions = s
    }
```

`e.workflowDefinitionsApi.list` seems to return a string instead of an object containing an items property

![image](https://user-images.githubusercontent.com/10726046/148959359-0fa95e2c-8c6d-4b70-9a61-5095efe02bd6.png)


Perhaps this bundle or javascript-file is still cached on your end, which makes it work for you?

**Comment by Z3roCoder** [comment]
Debugging shows that while the code tries to call 

`localhost:13000/v1/workflow-definitions?version=Latest`

It actually calls 

`http://localhost:13000/'http://localhost:13000'/v1/workflow-definitions?version=Latest`

Which in turn results in the main page html.

Calling 

`curl localhost:13000/v1/workflow-definitions?version=Latest` in my cmd shell yiels the correct output of `{"items":[],"totalCount":0}`

![image](https://user-images.githubusercontent.com/10726046/148960660-c52bac47-ef0e-4251-9d1e-f81c0a8f7e9b.png)

**Comment by Z3roCoder** [comment]
After some more debugging I found out that the input is apparently not sanitized.

Using the following command:
`docker run -t -i -e ELSA__SERVER__BASEURL='http://localhost:13000' -p 13000:80 elsaworkflows/elsa-dashboard-and-server:latest`

Will result in the parameter passed into the httpClient be "'localhost:13000'" - Instead of "localhost:13000"; If you run the following command:
`docker run -t -i -e ELSA__SERVER__BASEURL=http://localhost:13000 -p 13000:80 elsaworkflows/elsa-dashboard-and-server:latest` without single quotes, it will work like a charme.

So you should either update the docker command on your ReadMe.md-Page, or somehow sanitize single/double quotes inside the Environment Variable that is read via Configuration["Elsa:Server:BaseAdress"].

**Comment by oacostam** [comment]
Hi @Z3roCoder You're right, after removing the quotes it works fine, thank you so much for your quick support! Probably it will be good to update the README.md file of the project so other users don't use quotes for ELSA__SERVER__BASEURL variable  when using the docker image.
Kind regards.

**Comment by Steven23456** [comment]
I don't know if this is the same issue .. but i've tried all version of the cmd with/without quotes etc.  and all I get is a blank screen .. the endpoint responds to the get and I do get the following html

`<html>
<body>

  | <!DOCTYPE html>
-- | --
  | <html lang="en">
  | <head>
  | 
  | <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
  | <title>Elsa Workflows</title>
  | <link rel="icon" type="image/png" sizes="32x32" href="/_content/Elsa.Designer.Components.Web/elsa-workflows-studio/assets/images/favicon-32x32.png">
  | <link rel="icon" type="image/png" sizes="16x16" href="/_content/Elsa.Designer.Components.Web/elsa-workflows-studio/assets/images/favicon-16x16.png">
  | <link rel="stylesheet" href="/_content/Elsa.Designer.Components.Web/elsa-workflows-studio/assets/fonts/inter/inter.css">
  | <link rel="stylesheet" href="/_content/Elsa.Designer.Components.Web/elsa-workflows-studio/elsa-workflows-studio.css">
  | <script src="/_content/Elsa.Designer.Components.Web/monaco-editor/min/vs/loader.js"></script>
  | <script type="module" src="/_content/Elsa.Designer.Components.Web/elsa-workflows-studio/elsa-workflows-studio.esm.js"></script>
  | </head>
  | <body>
  | <elsa-studio-root server-url="http://localhost:13000" monaco-lib-path="_content/Elsa.Designer.Components.Web/monaco-editor/min">
  | <elsa-studio-dashboard></elsa-studio-dashboard>
  | </elsa-studio-root>
  | <script type="module">
  | // Integration demos.
  |  
  | // Import publicly exposed services and models.
  | import { CredentialManagerPlugin } from "/_content/Elsa.Designer.Components.Web/elsa-workflows-studio/index.esm.js";
  |  
  | // Get a handle to the elsa-studio-root element.
  | const elsaStudioRoot = document.querySelector('elsa-studio-root');
  |  
  | // Configure Elsa during the 'initializing' event.
  | elsaStudioRoot.addEventListener('initializing', e => {
  | const elsa = e.detail;
  | elsa.pluginManager.registerPlugins([
  | CredentialManagerPlugin,
  | ]);
  | });
  |  
  | // Some components publish DOM events that we can handle directly:
  | elsaStudioRoot.addEventListener('workflow-changed', e => {
  | console.log('Workflow model changed! New model: ${e.detail}');
  | })
  | </script>
  | </body>
  | </html>


</body>
</html><!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>Elsa Workflows</title>
    <link rel="icon" type="image/png" sizes="32x32" href="[/_content/Elsa.Designer.Components.Web/elsa-workflows-studio/assets/images/favicon-32x32.png](http://localhost:13000/_content/Elsa.Designer.Components.Web/elsa-workflows-studio/assets/images/favicon-32x32.png)">
    <link rel="icon" type="image/png" sizes="16x16" href="[/_content/Elsa.Designer.Components.Web/elsa-workflows-studio/assets/images/favicon-16x16.png](http://localhost:13000/_content/Elsa.Designer.Components.Web/elsa-workflows-studio/assets/images/favicon-16x16.png)">
    <link rel="stylesheet" href="[/_content/Elsa.Designer.Components.Web/elsa-workflows-studio/assets/fonts/inter/inter.css](http://localhost:13000/_content/Elsa.Designer.Components.Web/elsa-workflows-studio/assets/fonts/inter/inter.css)">
    <link rel="stylesheet" href="[/_content/Elsa.Designer.Components.Web/elsa-workflows-studio/elsa-workflows-studio.css](http://localhost:13000/_content/Elsa.Designer.Components.Web/elsa-workflows-studio/elsa-workflows-studio.css)">
    <script src="[/_content/Elsa.Designer.Components.Web/monaco-editor/min/vs/loader.js](http://localhost:13000/_content/Elsa.Designer.Components.Web/monaco-editor/min/vs/loader.js)"></script>
    <script type="module" src="[/_content/Elsa.Designer.Components.Web/elsa-workflows-studio/elsa-workflows-studio.esm.js](http://localhost:13000/_content/Elsa.Designer.Components.Web/elsa-workflows-studio/elsa-workflows-studio.esm.js)"></script>
</head>
<body>
    <elsa-studio-root server-url="http://localhost:13000" monaco-lib-path="_content/Elsa.Designer.Components.Web/monaco-editor/min">
        <elsa-studio-dashboard></elsa-studio-dashboard>
    </elsa-studio-root>
    <script type="module">
        // Integration demos.

        // Import publicly exposed services and models.
        import { CredentialManagerPlugin } from "/_content/Elsa.Designer.Components.Web/elsa-workflows-studio/index.esm.js";

        // Get a handle to the elsa-studio-root element.
        const elsaStudioRoot = document.querySelector('elsa-studio-root');

        // Configure Elsa during the 'initializing' event.
        elsaStudioRoot.addEventListener('initializing', e => {
            const elsa = e.detail;
            elsa.pluginManager.registerPlugins([
                CredentialManagerPlugin,
            ]);
        });

        // Some components publish DOM events that we can handle directly:
        elsaStudioRoot.addEventListener('workflow-changed', e => {
            console.log('Workflow model changed! New model: ${e.detail}');
        })
    </script>
</body>
</html>`

but the browser page is just blank ... the console shows the following

`p-e37496bc.js:2  Uncaught (in promise) TypeError: r.originalAdapter.call is not a function
    at e (p-e37496bc.js:2:897)
    at async Object.list (p-04c30d61.js:1:4811)
    at async se.componentWillLoad (p-23353c0b.entry.js:1:21264)`

any suggestions? the image is: d5a2ba348204
