### ISSUE TITLE
Browser crash 

### ISSUE THREAD

**Issue by Nevyn1975** [elsa-workflows/elsa-core#2669]
IDE: Visual Studio 2019
.Net: 5.0
Elsa 2.4.0.1
Browser: Chrome 96.0.4664.110

Simple project using Elsa Studio + server, taken from samples [here](https://elsa-workflows.github.io/elsa-core/docs/next/quickstarts/quickstarts-aspnetcore-server-dashboard-and-api-endpoints)

Build is OK but everytime I click on menu item "Worflow Instances" inside studio web page, I get these errors on Chrome console:

![image](https://user-images.githubusercontent.com/65671010/149623307-6c51a2b6-1eb4-4dce-a8de-5d63fb41b2bb.png)

and page is no more working...

Tried to rebuild clean, delete sqlite db.

Using Edge everything seems OK and no errors.

Are there any incompatibility issues with Chrome?

Any hint about this?

Thank you very much!

**Comment by sfmskywalker** [comment]
I just went through the quickstart guide myself step-by-step, and it worked without a hitch.

If you send me your project I can take a look.

**Comment by Torolleys** [comment]
can u fix this problem? I also encountered this problem when I upgraded my project to 2.4.0.1 @Nevyn1975

**Comment by sfmskywalker** [comment]
Sure. If someone sends me a broken project or repro steps then I can fix it ;)

**Comment by Nevyn1975** [comment]
It's quite difficult for me to pass the entire project, but these are the main files regarding Elsa.

The strange things is that at the beginning everything was ok but then I started to receive the errors inside console and I wasn't able to restore the working situation.

@Torolleys I patched by setting Edge as default browser for debug

Program.cs:

`namespace TVP
{
    public class Program
    {
        public static void Main(string[] args)
        {

            CreateHostBuilder(args).Build().Run();
        }

        public static IHostBuilder CreateHostBuilder(string[] args) =>
            Host.CreateDefaultBuilder(args)
                .ConfigureWebHostDefaults(webBuilder =>
                {
                    webBuilder.UseElectron(args);
                    webBuilder.UseStartup<Startup>();
                });
    }
}
`

Startup.cs:

`namespace MyNS
{
    public class Startup
    {
        public Startup(IWebHostEnvironment environment, IConfiguration configuration)
        {
            Environment = environment;
            Configuration = configuration;
        }

        private IWebHostEnvironment Environment { get; }
        private IConfiguration Configuration { get; }

        public void ConfigureServices(IServiceCollection services)
        {
            var elsaSection = Configuration.GetSection("Elsa");

            services
                .AddHttpClient(nameof(SendHttpRequest)).ConfigurePrimaryHttpMessageHandler(_ => new HttpClientHandler
                {
                    ClientCertificateOptions = ClientCertificateOption.Manual,
                    ServerCertificateCustomValidationCallback = (httpRequestMessage, cert, cetChain, policyErrors) => true
                });

            // Elsa services.
            services
                .AddElsa(elsa => elsa
                    .UseEntityFrameworkPersistence(ef => ef.UseSqlite())
                    .AddConsoleActivities()
                    .AddHttpActivities(elsaSection.GetSection("Server").Bind)
                    .AddQuartzTemporalActivities()
                ); ;
            // Elsa API endpoints.
            services.AddElsaApiEndpoints();

            // For Dashboard.
            services.AddRazorPages();
            services.AddCors(cors => cors.AddDefaultPolicy(policy => policy.AllowAnyHeader().AllowAnyMethod().AllowAnyOrigin().WithExposedHeaders("Content-Disposition")));
        }
        
        public void Configure(IApplicationBuilder app)
        {
            if (Environment.IsDevelopment())
            {
                app.UseDeveloperExceptionPage();
            }

            app
                .UseCors()
                .UseStaticFiles() // For Dashboard.
                .UseHttpActivities()
                .UseRouting()
                .UseEndpoints(endpoints =>
                {
                    // Elsa API Endpoints are implemented as regular ASP.NET Core API controllers.
                    endpoints.MapControllers();

                    // For Dashboard.
                    endpoints.MapFallbackToPage("/_Host");
                });

            // Open the Electron-Window here
            Task.Run(async () => await Electron.WindowManager.CreateWindowAsync());
        }
}`

**Comment by sfmskywalker** [comment]
One thing to try is to add this to `Program`:

```csharp
.ConfigureWebHostDefaults(webBuilder => {
   webBuilder.UseStaticWebAssets(); // Add this line
   webBuilder.UseElectron(args);
   webBuilder.UseStartup<Startup>();
```

What I've seen in the past is that, depending on how the project is built & launched, static web assets won't be served without that line.

My current understanding (from memory, so could not be entirely accurate) is that .NET will enable static web assets under the following conditions:

1. When you publish your project.
2. When the project runs in `Development` mode.

When you run the project in e.g. `Production` mode without publishing, the assets fail to be served.

**Comment by Torolleys** [comment]
Thanks to u,I solved my problem

**Comment by Nevyn1975** [comment]
It seems to be OK.
Thank you very much.
