### ISSUE TITLE
Can i import from Elsa to Bpmn and vice versa ?

### ISSUE THREAD

**Issue by tacek** [elsa-workflows/elsa-core#267]
Hi!
I am write about Elsa.
There are 3 questions that interest me.
1) Can i import from Elsa to Bpmn and vice versa?
2) Loading a process from JSON to C#, that is to say - there is a description in json and i need to import it at start app, is there any way to do this through code?
3) Is there a standard solution to start a process by POST request or do i need to write a separate web application to handle POST request?

I would really appreciate your help!
Thank you.

**Comment by sfmskywalker** [comment]
Hi @tacek !

1. Not at the moment. I do intend to investigate the possibilities in this area. Or if anyone else is interested in looking into this they would be more than welcome.
1. Yes, you can write & read JSON files representing workflow definitions. See [Sample09](https://github.com/elsa-workflows/elsa-core/blob/master/src/samples/Sample09/Program.cs) for an example that reads JSON from an embedded resource and then uses that JSON to deserialize & run a workflow.
1. Yes, all you need to do is create your ASP.NET Core application and register some Elsa services, most importantly the HTTP activity services. Please have a look at [this guide](https://elsa-workflows.github.io/elsa-core/docs/guides-hello-world-http). Although that guide shows you how to implement the workflow in C# code, it works the same way when defining the workflow using the dashboard application. For more information on setting up the dashboard, please refer to [this guide](https://elsa-workflows.github.io/elsa-core/docs/guides-dashboard). It demonstrates exactly your question.

**Comment by sfmskywalker** [comment]
Closing this issue, but feel free to reopen if you have follow-up questions!
