### ISSUE TITLE
The properties of my custom activity are always null

### ISSUE THREAD

**Issue by nmadrane** [elsa-workflows/elsa-core#2670]
I have created a custom activity containing a single property :

[ActivityInput(Hint = "This is a sample property")]
public string MyProperty1 { get; set; }

In the designer I can see this property in the GUI, I can put a value and it is correctly persisted.

However when I execute my workflow, the activity can't see the value of MyProperty1, it is always null inside OnExecuteAsync !

Could you please tell me what I am missing here ?

Thanks

**Comment by sfmskywalker** [comment]
I couldn't say, since it works fine when I try. If you send me a sample program that demonstrates the issue I might be able to help.
