### ISSUE TITLE
We have a plugin to intercept requests and set an authorization as in the example : it is not working

### ISSUE THREAD

**Issue by vijayalaxmiveluri** [elsa-workflows/elsa-core#2671]
function CustomHttpMiddlewarePlugin(elsaStudio) {
     // alert("Test");
      const eventBus = elsaStudio.eventBus;

      eventBus.on('http-client-created', e => {
        // Register a sample middleware.
        e.service.register({
          onRequest(request) {
            console.log('onRequest');
            return request;
          },

          onResponse(response) {
            console.log('onResponse');
            return response;
          }
        });
      });
    }

    // Get a handle to the elsa-studio-root element.
    const elsaStudioRoot = document.querySelector('elsa-studio-root');

    // Configure Elsa.
    elsaStudioRoot.addEventListener('initializing', e => {
      const elsa = e.detail;
      elsa.pluginManager.registerPlugins([WebhooksPlugin,CustomHttpMiddlewarePlugin]);
    });

**Comment by sfmskywalker** [comment]
What is not working, specifically? The authorization, or the plugin is not invoking the middleware setup? Or the middleware itself?

**Comment by vijayalaxmiveluri** [comment]
Here is my Code 


  <script>
   
    function AuthorizationMiddlewarePlugin(elsaStudio) {
      const eventBus = elsaStudio.eventBus;

      eventBus.on('http-client-created', e => {
        // Register Axios middleware.
        e.service.register({
          onRequest(request) {
            request.headers = { 'Authorization': Model.AccessToken }
            return request;
          }
        });
      });
    }

    // Get a handle to the elsa-studio-root element.
    const elsaStudioRoot = document.querySelector('elsa-studio-root');

    // Configure Elsa.
    elsaStudioRoot.addEventListener('initializing', e => {
      const elsa = e.detail;
      elsa.pluginManager.registerPlugins([AuthorizationMiddlewarePlugin]);
    });
   
  </script>


Model.AccessToken  is the token that I am adding ..this token is not added to the api call v1/features

**Comment by vijayalaxmiveluri** [comment]
function AuthorizationMiddlewarePlugin(elsaStudio) {
      const eventBus = elsaStudio.eventBus;

      eventBus.on('http-client-created', e => {
        // Register Axios middleware.
        e.service.register({
          onRequest(request) {
            request.headers = { 'Authorization': Model.AccessToken }
            return request;
          }
        });
      });
    }

    // Get a handle to the elsa-studio-root element.
    const elsaStudioRoot = document.querySelector('elsa-studio-root');

    // Configure Elsa.
    elsaStudioRoot.addEventListener('initializing', e => {
      const elsa = e.detail;
      elsa.pluginManager.registerPlugins([AuthorizationMiddlewarePlugin]);
    });

**Comment by sfmskywalker** [comment]
> Here is my Code
> 
> <script> function AuthorizationMiddlewarePlugin(elsaStudio) { const eventBus = elsaStudio.eventBus; eventBus.on('http-client-created', e => { // Register Axios middleware. e.service.register({ onRequest(request) { request.headers = { 'Authorization': Model.AccessToken } return request; } }); }); } // Get a handle to the elsa-studio-root element. const elsaStudioRoot = document.querySelector('elsa-studio-root'); // Configure Elsa. elsaStudioRoot.addEventListener('initializing', e => { const elsa = e.detail; elsa.pluginManager.registerPlugins([AuthorizationMiddlewarePlugin]); }); </script>
> Model.AccessToken is the token that I am adding ..this token is not added to the api call v1/features

Can you please format your code? It's hard to read unformatted.

**Comment by sfmskywalker** [comment]
> .this token is not added to the api call v1/features

I see now. That was [a bug](https://github.com/elsa-workflows/elsa-core/issues/2653) that has been solved recently. What version of Elsa re you using currently?

**Comment by vijayalaxmiveluri** [comment]
we are using version  2.4.

**Comment by sfmskywalker** [comment]
OK. Then the fix will be part of 2.4.1. In the meantime, you can try with the preview packages available on MyGet if you want.

**Comment by vijayalaxmiveluri** [comment]
OK. When will it be released

**Comment by vijayalaxmiveluri** [comment]
In the meantime, you can try with the preview packages available on MyGet if you want....
Can you please share link

**Comment by sfmskywalker** [comment]
That depends on when the issues associated with the 2.4.1 milestone have been fixed. Hard to predict due to other work. Hopefully before the end of this month, but we'll see.
