### ISSUE TITLE
How to trigger Workflow from Docker Dashboard and Server Container

### ISSUE THREAD

**Issue by Z3roCoder** [elsa-workflows/elsa-core#2696]
Hey there!

I've created a container using the following docker command:
docker run -t -i -e ELSA__SERVER__BASEURL='http://localhost:13000' -p 13000:80 elsaworkflows/elsa-dashboard-and-server:latest

I've followed the gif example, created a http endpoint workflow which returns some html. The path is /test

How do I trigger this workflow now to test it out?

Going to localhost:13000/test only brings me to the main page of the designer...

Any help is appreciated.

**Comment by sfmskywalker** [comment]
What happens if you try `/workflows/test`?

**Comment by Z3roCoder** [comment]
This works - Thank you!
