### ISSUE TITLE
Different bus library

### ISSUE THREAD

**Issue by Tobias-08** [elsa-workflows/elsa-core#2698]
Hi,

is the use of Rebus encapsulated in ELSA and is it possible to write a custom plugin in order to swap Rebus for another library (e. g. NServiceBus)? We are using NServiceBus and having another bus like Rebus running in the background unnecessarily increases operational complexity.

Thanks!
Tobias

**Comment by sfmskywalker** [comment]
Hi Tobias,

Unfortunately the Rebus use wasn't abstracted out because, so I figured, it is itself an abstraction already.
But maybe I was wrong to have Elsa Core make such opinionated use of libraries such as Rebus, so maybe it's time to reconsider.

If you want to do a PR then I'd welcome that.

**Comment by Tobias-08** [comment]
Thanks, understood.

Maybe I would be able to contribute a NServiceBus-plugin (if of general interest) if the bus was already abstracted in ELSA. But doing the abstraction on my own exceeds my ELSA knowledge, at least for now (completely new to ELSA).

**Comment by Tobias-08** [comment]
But in my opinion ELSA would hugely benefit from reducing its hard dependencies (in particular those with infrastructure/operational impact ->Rebus) in favour of pluggable dependencies. This would stress the lightweight, library-style nature of ELSA (which is a huge advantage over fat workflow server products) and broaden its use cases.

In this context the question might be if ELSA really needs a bus library (which not everyone might have or like to operate) or if it's sufficient to implement an own shared/distributed persistence or simple messaging in ELSA, maybe based on the existing pluggable ELSA.Persistence.* packages.

**Comment by tomy2105** [comment]
Well Rebus is itself an abstraction layer and has a number of plugins some of which are true messaging busses and some are "simple" database based implementations (see https://github.com/rebus-org?utf8=%E2%9C%93&q=rebus.) 
I've personally used postgres and sqlserver "integration libraries.".

@Tobias-08 Maybe you could provide a plugin for NServiceBus for Rebus?

**Comment by Tobias-08** [comment]
NServiceBus itself is in abstraction layer in this sense. It enables plugging in several so called transports (SQL, RabbitMQ, Azure, ...) and therefore seems to have a quite similar architecture like Rebus.

My first impression is that it might not be so useful to write a NServiceBus-plugin for Rebus (plugging an abstraction layer into another abstraction layer).

As rethinking about Rebus in ELSA seems to be a long term task (if at all), could it be a good starting point to better document in what way ELSA uses Rebus at this moment and what implications this might have?

**Comment by sfmskywalker** [comment]
For Elsa 3, the runtime & management layers will use an abstraction for publishing messages to the service bus, which will make it easy to provide implementations using any library people want, including NServiceBus, Rebus and MassTransit.

For Elsa 2, it depends.
In any case, documenting this is certainly a good idea.

**Comment by Tobias-08** [comment]
Thanks, I appreciate the plans for Elsa 3!

**Comment by sfmskywalker** [comment]
Elsa 3 is out and implemented the plans outlined in this issue, so I will go ahead and close it. Thanks, both, for the great conversation!
