### ISSUE TITLE
Custom Field Types throwing error on <elsa-property-editor>

### ISSUE THREAD

**Issue by Zengage** [elsa-workflows/elsa-core#2703]
This example was working fine in version 2.3.0 https://elsa-workflows.github.io/elsa-core/docs/extensibility/extensibility-designer-plugins#custom-field-types
But since the upgrade to the latest 2.4.2.1 and it is unfortunately not working.
Getting following error:
![image](https://user-images.githubusercontent.com/9194241/151230085-93da0f9f-fe85-4416-9f2e-e6466a6349b6.png)
Can you advise please how to get it fixed?
Thanks a bunch!

**Comment by sfmskywalker** [comment]
There was a breaking change that requires the <elsa-property-editor> control to also receive the activity model. In other words, to fix this error, add this line to your plugin:

```typescript
propertyEditor.activityModel = activity;
```

I pushed an update to the documentation as well.

**Comment by Zengage** [comment]
Great stuff! Thanks, it is working again as expected.
