### ISSUE TITLE
@zrkcode That's odd - you definitely should not have to explicitly register your controllers. Any chance you can provide a sample project that reproduces this problem for me to look at?

### ISSUE THREAD

**Issue by zrkcode** [elsa-workflows/elsa-core#271]
@zrkcode That's odd - you definitely should not have to explicitly register your controllers. Any chance you can provide a sample project that reproduces this problem for me to look at?

_Originally posted by @sfmskywalker in https://github.com/elsa-workflows/elsa-core/issues/260#issuecomment-605267960_

[Demo](https://github.com/zrkcode/Elsa-Workflow-Issue)

I use abp vnext and elsa-core,Did I use it wrong

**Comment by sfmskywalker** [comment]
Hi @zrkcode , let's close this issue here and keep the discussion in #260. Your repro helped me find a fix. Thanks!
