### ISSUE TITLE
Elsa.Client SaveAsync returns error if Variables provided

### ISSUE THREAD

**Issue by dominicasley** [elsa-workflows/elsa-core#2717]
Due to mismatched request and response models in `IWorkflowDefinitionsApi` errors occur when serializing and deserializing the Variables property for the client. 

introduced in https://github.com/elsa-workflows/elsa-core/pull/2680

**Comment by dominicasley** [comment]
resolved in PR #2716

**Comment by sfmskywalker** [comment]
Thanks for the fix!
