### ISSUE TITLE
Trigger workflow from another server

### ISSUE THREAD

**Issue by futureneo86** [elsa-workflows/elsa-core#272]
Hi, I hosted elsa workflow with address http://localhost:1111. And I have a workflow with signal name is RegisterUser

Now I build a new website with .Net core with address http://localhost:2222.

How to trigger workflow with signal RegisterUser from 2222?

Thanks for your support

**Comment by sfmskywalker** [comment]
A very good question.

Currently, the only two ways to trigger a workflow containing a `Signaled` activity are:

1. Using `IWorkflowInvoker` to trigger a specific workflow instance or all workflows (new ones and existing workflow instances blocked on 'Signaled`) programmatically (depending on the parameters you supply to the call), or:
1. Generating a token and performing a HTTP GET or POST request on `http://localhost:1111/workflow/signal?token={token}` (see [SignalUrlFilter](https://github.com/elsa-workflows/elsa-core/blob/develop/src/activities/Elsa.Activities.Http/Liquid/SignalUrlFilter.cs) how to generate the token). This approach triggers a specific workflow *instance*, not all workflows starting with or blocked on `Signaled`.

Depending on your exact requirements, I can imagine you are looking for an endpoint on the workflow server (:1111) that you can invoke from :2222. This endpoint could be HTTP, AMQP or gRPC.

Such and endpoint does not exist yet, but I think it would make sense to provide this endpoint out of the box. You could then simply do an e.g. HTTP POST to some endpoint, specifying the signal name to trigger. For example: HTTP POST http://localhost:1111/workflow/trigger?signal=my_signal_name.

Elsa 2.0 will expose a GraphQL mutation to achieve this, so unless you are willing to wait, I recommend that you create an API controller in your :1111 host that uses `IWorkflowInvoker` to trigger your workflows. The implementation would look something like this (not tested, so treat as pseudo code):

```csharp
[ApiController]
[Route("workflow")]
public class MyWorkflowController : ControllerBase
{
   [HttpPost("trigger")
   public async Task<IActionResult> Post(string signal)
   {
      // Execute all workflows that start with or are blocked on the `Signaled` activity.
      await _workflowInvoker.TriggerSignalAsync(signal);

      return Accepted();
   }
}
```

The above will start all workflows starting with `Signaled` and resumes all workflow instances blocked on `Signaled`, for those `Signaled` activities configured with the specified signal name.

Hope this helps, but let me know if you have more questions about this.

**Comment by jedihoo** [comment]
i have the same question .waiting for Elsa 2.0
