### ISSUE TITLE
In-memory persistence?

### ISSUE THREAD

**Issue by Nevyn19** [elsa-workflows/elsa-core#2726]
Elsa 2.4.0.1

I'm using a simple workflow to test our application with Elsa, with an HTTP endpoint and an HTTP response, nothing else.
I noticed that every time time I call the HTTP endpoint, the memory of the application is growing, and the faster I query the endpoint, the faster the memory grows... I reached >2 GB of memory in a bunch of minutes.

Garbage collection is triggered but memory doesn't decrease and keeps growing.

I'm using SQLITE as persistence framework, but practically I need this only to store created workflows by designer,  I don't need to store anything from the workflow execution, no variables, etc...

How can I reduce the memory consumption?

This is the exported workflow JSON:

{
  "$id": "1",
  "definitionId": "b8da70f43d7e4d428ee81b45e0f005c5",
  "versionId": "1d3536c611b34ea38bb18902d95e4180",
  "version": 1,
  "variables": {
    "$id": "2",
    "data": {}
  },
  "customAttributes": {
    "$id": "3",
    "data": {}
  },
  "isSingleton": false,
  "persistenceBehavior": "WorkflowBurst",
  "deleteCompletedInstances": true,
  "isPublished": true,
  "isLatest": true,
  "activities": [
    {
      "$id": "4",
      "activityId": "915e8a23-ff65-48f6-a17f-da21975d8951",
      "type": "HttpEndpoint",
      "displayName": "HTTP Endpoint",
      "persistWorkflow": false,
      "loadWorkflowContext": false,
      "saveWorkflowContext": false,
      "properties": [
        {
          "$id": "5",
          "name": "Path",
          "expressions": {
            "$id": "6",
            "Literal": "/test"
          }
        },
        {
          "$id": "7",
          "name": "Methods",
          "expressions": {
            "$id": "8",
            "Json": "[\"GET\"]"
          }
        },
        {
          "$id": "9",
          "name": "ReadContent",
          "expressions": {
            "$id": "10"
          }
        },
        {
          "$id": "11",
          "name": "TargetType",
          "expressions": {
            "$id": "12"
          }
        },
        {
          "$id": "13",
          "name": "Schema",
          "syntax": "Literal",
          "expressions": {
            "$id": "14",
            "Literal": ""
          }
        },
        {
          "$id": "15",
          "name": "Authorize",
          "expressions": {
            "$id": "16"
          }
        },
        {
          "$id": "17",
          "name": "Policy",
          "expressions": {
            "$id": "18"
          }
        }
      ],
      "propertyStorageProviders": {}
    },
    {
      "$id": "19",
      "activityId": "44389a30-2355-4748-b500-355682b039f0",
      "type": "WriteHttpResponse",
      "displayName": "HTTP Response",
      "persistWorkflow": false,
      "loadWorkflowContext": false,
      "saveWorkflowContext": false,
      "properties": [
        {
          "$id": "20",
          "name": "Content",
          "expressions": {
            "$id": "21",
            "Literal": "ciao"
          }
        },
        {
          "$id": "22",
          "name": "ContentType",
          "expressions": {
            "$id": "23"
          }
        },
        {
          "$id": "24",
          "name": "StatusCode",
          "expressions": {
            "$id": "25"
          }
        },
        {
          "$id": "26",
          "name": "CharSet",
          "expressions": {
            "$id": "27"
          }
        },
        {
          "$id": "28",
          "name": "ResponseHeaders",
          "expressions": {
            "$id": "29"
          }
        }
      ],
      "propertyStorageProviders": {}
    }
  ],
  "connections": [
    {
      "$id": "30",
      "sourceActivityId": "915e8a23-ff65-48f6-a17f-da21975d8951",
      "targetActivityId": "44389a30-2355-4748-b500-355682b039f0",
      "outcome": "Done"
    }
  ],
  "id": "1d3536c611b34ea38bb18902d95e4180"
}`
  "$id": "1",
  "definitionId": "b8da70f43d7e4d428ee81b45e0f005c5",
  "versionId": "1d3536c611b34ea38bb18902d95e4180",
  "version": 1,
  "variables": {
    "$id": "2",
    "data": {}
  },
  "customAttributes": {
    "$id": "3",
    "data": {}
  },
  "isSingleton": false,
  "persistenceBehavior": "WorkflowBurst",
  "deleteCompletedInstances": true,
  "isPublished": true,
  "isLatest": true,
  "activities": [
    {
      "$id": "4",
      "activityId": "915e8a23-ff65-48f6-a17f-da21975d8951",
      "type": "HttpEndpoint",
      "displayName": "HTTP Endpoint",
      "persistWorkflow": false,
      "loadWorkflowContext": false,
      "saveWorkflowContext": false,
      "properties": [
        {
          "$id": "5",
          "name": "Path",
          "expressions": {
            "$id": "6",
            "Literal": "/test"
          }
        },
        {
          "$id": "7",
          "name": "Methods",
          "expressions": {
            "$id": "8",
            "Json": "[\"GET\"]"
          }
        },
        {
          "$id": "9",
          "name": "ReadContent",
          "expressions": {
            "$id": "10"
          }
        },
        {
          "$id": "11",
          "name": "TargetType",
          "expressions": {
            "$id": "12"
          }
        },
        {
          "$id": "13",
          "name": "Schema",
          "syntax": "Literal",
          "expressions": {
            "$id": "14",
            "Literal": ""
          }
        },
        {
          "$id": "15",
          "name": "Authorize",
          "expressions": {
            "$id": "16"
          }
        },
        {
          "$id": "17",
          "name": "Policy",
          "expressions": {
            "$id": "18"
          }
        }
      ],
      "propertyStorageProviders": {}
    },
    {
      "$id": "19",
      "activityId": "44389a30-2355-4748-b500-355682b039f0",
      "type": "WriteHttpResponse",
      "displayName": "HTTP Response",
      "persistWorkflow": false,
      "loadWorkflowContext": false,
      "saveWorkflowContext": false,
      "properties": [
        {
          "$id": "20",
          "name": "Content",
          "expressions": {
            "$id": "21",
            "Literal": "ciao"
          }
        },
        {
          "$id": "22",
          "name": "ContentType",
          "expressions": {
            "$id": "23"
          }
        },
        {
          "$id": "24",
          "name": "StatusCode",
          "expressions": {
            "$id": "25"
          }
        },
        {
          "$id": "26",
          "name": "CharSet",
          "expressions": {
            "$id": "27"
          }
        },
        {
          "$id": "28",
          "name": "ResponseHeaders",
          "expressions": {
            "$id": "29"
          }
        }
      ],
      "propertyStorageProviders": {}
    }
  ],
  "connections": [
    {
      "$id": "30",
      "sourceActivityId": "915e8a23-ff65-48f6-a17f-da21975d8951",
      "targetActivityId": "44389a30-2355-4748-b500-355682b039f0",
      "outcome": "Done"
    }
  ],
  "id": "1d3536c611b34ea38bb18902d95e4180"
}

I need this not to be a sigleton in order to avoid blocking situation.

Any help would be appreciated.

Thx

**Comment by sfmskywalker** [comment]
> I'm using a simple workflow to test our application with Elsa, with an HTTP endpoint and an HTTP response, nothing else.
I noticed that every time time I call the HTTP endpoint, the memory of the application is growing, and the faster I query the endpoint, the faster the memory grows... I reached >2 GB of memory in a bunch of minutes.

Try as I may, even with a few thousand invocations, memory does not exceed 293MB. So something else must be different. Perhaps you can share your exact steps so I can reproduce?

**Comment by Nevyn1975** [comment]
Ok, thx for testing it.
So, maybe the problem is elsewhere... 
I put this into startup.cs:
`// Configure blob storage for blob storage workflow storage provider.
            string wfPath = $@"{AppDomain.CurrentDomain.BaseDirectory}\WF\";
            services.Configure<BlobStorageWorkflowProviderOptions>(options => options.BlobStorageFactory = () => StorageFactory.Blobs.DirectoryFiles(wfPath));
`

Inside the WF folder I have some simple pre-made workflows, very similar to the one in my first post: no need to save anything, only to load them at startup and keep them in idle, ready to be used.

Could it be this the problem with the memory?

**Comment by sfmskywalker** [comment]
That should not cause such an significant increase in memory usage, since it would write data to disk (and only when you configure activity properties to use this provider in the first place).

What I recommend you to try is to [setup a brand new ASP.NET Core project, configure it with Elsa](https://elsa-workflows.github.io/elsa-core/docs/next/quickstarts/quickstarts-aspnetcore-server-api-endpoints), and do your memory testing on that project.

**Comment by Nevyn1975** [comment]
Is it possible to completly disable persistance? Also for memory.

Thx

**Comment by sfmskywalker** [comment]
Yes, you would basically have to create a custom persistence provider that simply does nothing.

With Elsa 3, this will be simpler thanks to a pipeline processing approach, but for Elsa 2 the easiest way is to create a custom provider.

**Comment by brian-exe** [comment]
Hey @Nevyn19, have you managed to find the problem? 
I am running into some similar issue now
