### ISSUE TITLE
Designer.Components.Web fails when custom ASPNETCORE_ENVIRONMENT is used

### ISSUE THREAD

**Issue by dmitryshepelev** [elsa-workflows/elsa-core#2729]
The static assets are not built when **Elsa.DesignerComponents.Web** is istalled via **Nuget** and a **custom Environment** is used. As a result, dashboard and designer are unusable. Setting one of pre-defined values for **ASPNETCORE_ENVIRONMENT** (Development, Staging, Production) solves this issue, but support of custom env is required.

**Step to reproduce:**

1. Follow the [guide](https://elsa-workflows.github.io/elsa-core/docs/quickstarts/quickstarts-aspnetcore-server-dashboard-and-api-endpoints) to setup project.
2. Set ASPNETCORE_ENVIRONMENT to custom value (for istance to "Local")
3. Run project
4. Get:
<img width="712" alt="Screenshot 2022-02-04 at 3 00 07 PM" src="https://user-images.githubusercontent.com/8254783/152525596-abf165ba-c2de-4453-87f3-4e8a2dac5c7f.png">

**Comment by sfmskywalker** [comment]
Try adding [this line](https://github.com/elsa-workflows/elsa-core/blob/master/src/samples/server/Elsa.Samples.Server.Host/Program.cs#L16) to your Program.cs file and let me know if that makes a difference.

**Comment by ricardopaulob** [comment]
Thanks @sfmskywalker . That works perfect for me.

**Comment by blakepell** [comment]
@sfmskywalker Much thanks (very much appreciated), that line worked for me as well and it was most likely related to the environment variable.
