### ISSUE TITLE
ForEach Activity clears Transient storage

### ISSUE THREAD

**Issue by noxe** [elsa-workflows/elsa-core#2736]
Hi @sfmskywalker - i have a huge issue with foreach activities. i am using ElsaDashboard.Samples.AspNetCore.Monolith - and a custom activity like this:

    [Activity(Outcomes = new[] { OutcomeNames.Done })]
    public class TestActivity : Activity
    {
        [ActivityOutput(DefaultWorkflowStorageProvider = TransientWorkflowStorageProvider.ProviderName)]
        public object Result { get; set; }

        protected override IActivityExecutionResult OnExecute()
        {
            this.Result = "Test Transient Val
[workflow-definition-7525ecbb6cff4e3aa663e2d39012d17d.zip](https://github.com/elsa-workflows/elsa-core/files/8021879/workflow-definition-7525ecbb6cff4e3aa663e2d39012d17d.zip)
ue";

            return Done();
        }
    }

Do see the problem - i created a small workflow which is attached. i also recorded a video to see the process. https://www.screencast.com/t/i5tAXK9nfv

From what i found during debug is - that the WorkflowRunner.RunCoreAsync does this here

 if (!workflowExecutionContext.HasScheduledActivities)
                        await _mediator.Publish(new WorkflowExecutionBurstCompleted(workflowExecutionContext, activityExecutionContext), cancellationToken);

The WorkflowExecutionBurstCompleted triggers the CleanupTransientWorkflowStorage - but it also triggers the RescheduleBranchingActivitiesAndContainers, and so HasScheduledActivities is again true after the _mediator.Publish

But now all Transient storage is cleared for the current workflow?

**Comment by sfmskywalker** [comment]
I pushed a fix that causes the transient storage provider to be cleaned up after the workflow finishes execution, instead of after every burst of execution.

**Comment by noxe** [comment]
holy cow - this was fast!! you rock - thank you - will test it immediately!!
