### ISSUE TITLE
Workflow-Definition variables &  customAttributes serialization issue

### ISSUE THREAD

**Issue by dohoangtung** [elsa-workflows/elsa-core#2740]
Current response from SaveWorkflowDefinition Api

![image](https://user-images.githubusercontent.com/40049759/153374128-9f58ca21-b9c1-47b3-b538-aa2b247d8c9d.png)

Data should be **null** instead of "{}"

**Comment by sfmskywalker** [comment]
Hi @dohoangtung , can you elaborate a little bit on why you think it should be `null` rather than an empty hash?

**Comment by dohoangtung** [comment]
Hi @sfmskywalker ,

This is for the cases when users want to de-serialization json string to <WorkflowDefinition> then they will not need to manually parse the data as Varialbles and CustomAttributes are of type Variable, not string. 
![image](https://user-images.githubusercontent.com/40049759/153990749-7872b630-9ed9-4f5d-89ae-2ba03f2a8df9.png)

**Comment by sfmskywalker** [comment]
But if the users don't want to de-serialize the `CustomAttributes` field, couldn't they just ignore it?
