### ISSUE TITLE
PR #1103 was not merged to release 2.5

### ISSUE THREAD

**Issue by shykln** [elsa-workflows/elsa-core#2747]
Hi, 

https://github.com/elsa-workflows/elsa-core/pull/1103 This PR fixed the issue where Elsa Mysql persistence would throw an error complaining about unsupported concept "Schema" in Mysql.

Somehow this commit was not merged to the latest release 2.5

Please include this commit in the coming 2.5.1 release so as to unblock Mysql users. 

Thank you.

Current workaround should be:

```
using Elsa.Persistence.EntityFramework.Core;
using Elsa.Persistence.EntityFramework.MySql;
using Microsoft.EntityFrameworkCore;
using Pomelo.EntityFrameworkCore.MySql.Infrastructure;

namespace WorkflowServer
{
    public static class ElsaUseMysqlFixer
    {
        public static DbContextOptionsBuilder UseMySqlFixed(this DbContextOptionsBuilder builder, string connectionString) =>
            builder.UseMySql(connectionString, ServerVersion.AutoDetect(connectionString), db => db
                .MigrationsAssembly(typeof(MySqlElsaContextFactory).Assembly.GetName().Name)
                .MigrationsHistoryTable(ElsaContext.MigrationsHistoryTable, ElsaContext.ElsaSchema)
                .SchemaBehavior(MySqlSchemaBehavior.Ignore));
    }
}
```

**Comment by sfmskywalker** [comment]
For some reason I replaced your code with a version that I thought fixed the same issue, but did nothing but cause a regression it seems.

Thanks for catching 👍🏻 

1e469b0fd4d72eff1ac4528ed20212f26bf5ca83
