### ISSUE TITLE
docker run is buggy

### ISSUE THREAD

**Issue by AYGTX** [elsa-workflows/elsa-core#2752]
Was following the tutorial 
https://sipkeschoorstra.medium.com/part-3-of-building-workflow-driven-net-applications-with-elsa-2-ea930acb3fe2

When I try to
`docker run -t -i -e ELSA__SERVER__BASEADDRESS='http://localhost:5000'/ -p 14000:80 elsaworkflows/elsa-dashboard:latest `
elsaworkflows/elsa-dashboard-and-server:latest

and I hit **the http://localhost:14000/workflow-instances** 
this is what I get in the console

```
TypeError: a.find is not a function
    at p-df0b5e26.entry.js:1:23551
    at Array.map (<anonymous>)
    at Xe.render (p-df0b5e26.entry.js:1:23516)
    at Z (p-59b41cfd.js:1:7218)
    at Y (p-59b41cfd.js:1:7049)
    at p-59b41cfd.js:1:6620 
```

in the mean time , I tried to 
`docker run -t -i -e ELSA__SERVER__BASEURL='http://localhost:13000' -e ASPNETCORE_ENVIRONMENT='Development' -p 13000:80 
`
and it worked perfectly

**Comment by AYGTX** [comment]
None of the menu items will function correctly until you made sure to point the component to a running Elsa server.

**Comment by John0x** [comment]
Trying to run ``docker run -t -i -e ELSA__SERVER__BASEURL='http://localhost:13000' -e ASPNETCORE_ENVIRONMENT='Development' -p 13000:80 elsaworkflows/elsa-dashboard-and-server:latest``
Seems to cause a similar problem. Is this known?

**Comment by sfmskywalker** [comment]
Yes, depending on your OS / shell, the quotes aurrounding the paramater values are passed straight into the application, which aren't trimmed. To see if that's the case or not, try this:

```
docker run -t -i -e ELSA__SERVER__BASEURL=http://localhost:13000 -e ASPNETCORE_ENVIRONMENT=Development -p 13000:80 elsaworkflows/elsa-dashboard-and-server:latest
```

Notice the removal of the single quotes.
