### ISSUE TITLE
Elsa.Activities.Mqtt.Services.MqttClientWrapper warn

### ISSUE THREAD

**Issue by mircotamburini** [elsa-workflows/elsa-core#2761]
when i try to execute my workflow:
builder
                .Timer(Duration.FromSeconds(5))
                .MessageReceived("/temperature", _host, _port, _username, _password, _qos)
                .WriteLine(context =>
                {
                    var message = context.GetInput<string>();
                    return $"Received a temperature update saying {message}!";
                });

i had an error everytime i send a payload to /temperature topic:
warn: Elsa.Activities.Mqtt.Services.MqttClientWrapper[0]
Attempted to subscribe to topic /temperature, but no message handler was set.

**Comment by mircotamburini** [comment]
Anyone use Mqtt Activities?

**Comment by mircotamburini** [comment]
i found last version 2.5.0 didnt work for me, i downgrade to 2.4.2.1 now work

**Comment by igortheodoro** [comment]
Hey, I'm looking for examples of how to use elsa workflow with message mainly using rabbitMq. Do you have some examples?

**Comment by mircotamburini** [comment]
> Hey, I'm looking for examples of how to use elsa workflow with message mainly using rabbitMq. Do you have some examples? I need to start a workflow as soon as I get a message but I don't see any content about it.

see there an example using rabbitMq
https://github.com/elsa-workflows/elsa-core/tree/master/src/samples/worker/Elsa.Samples.RabbitMqWorker
