### ISSUE TITLE
Proposal: Scheduler UI for Cron Activity

### ISSUE THREAD

**Issue by mohdali** [elsa-workflows/elsa-core#2765]
As a user, I would like to schedule tasks at set times.

For example, 00:15 am each day to send an email.

Currently Cron activity is available which can be used to schedule such tasks.

However, the user needs to learn Cron syntax which is sometimes confusing even for professionals.

Currently the cron activity has a link to this page https://www.freeformatter.com/cron-expression-generator-quartz.html to use as a generator.

However, it would be great to have a scheduler designer in the studio UI itself.

The UI should be intuitive and to the user intend rather than be driven by Cron syntax.

For example, it could be similar to Windows Task Scheduler UI or similar schedulers.

It can provide below options as a basis:

- Daily
  - Execute once Every day or repeat on hourly basis
- Weekly
  - Select which days of the week or work days
- Monthly
 - Execute on a specific day/days of the month and or for specific months

**Comment by mohdali** [comment]
I started some initial work on this activity to perform basic validation in the dashboard UI in this branch.

https://github.com/elsa-workflows/elsa-core/tree/cron-ui

![image](https://user-images.githubusercontent.com/4145465/156311099-d6e4d4a2-902f-425d-85c5-ce69b30c2fa3.png)
![image](https://user-images.githubusercontent.com/4145465/156311125-1bc9d952-0f94-4199-b394-359db244b3b3.png)
![image](https://user-images.githubusercontent.com/4145465/156311151-7ca31f76-7650-483c-8274-b809deaddbec.png)


Pending items:

- [ ] Adjust validation rules to match supported Quartz Syntax
- [ ] Build UI for user to select the desired period and convert to cron syntax

**Comment by sfmskywalker** [comment]
This is great. Keep going! 😄

**Comment by mohdali** [comment]
Sure will do!

I'm doing it on my spare time and using it to learn more about the web components. So it is taking some time but I will see it through.

**Comment by mohdali** [comment]
@sfmskywalker the tabs design got a little bit complicated so I'm dropping it for now. Created a PR for the basic functionality.

One other idea maybe to show the next time the activity will execute like shown in this plugin https://www.npmjs.com/package/cron-parser

I'm not sure where is the right place to put it though.
