### ISSUE TITLE
Samples Elsa.Samples.RabbitMqWorker didnt work with 2.5.0

### ISSUE THREAD

**Issue by mircotamburini** [elsa-workflows/elsa-core#2769]
I try https://github.com/elsa-workflows/elsa-core/tree/master/src/samples/worker/Elsa.Samples.RabbitMqWorker
but didt work with new 2.5.0...  but i  had to downgrade to 2.4.2.1 and it worked

**Comment by constantine-v** [comment]
This was fixed in #2786, please get latest version and check if it works for you now.
