### ISSUE TITLE
审批按钮如何通过请求后端API触发文档审批例子sample07中的fork

### ISSUE THREAD

**Issue by jedihoo** [elsa-workflows/elsa-core#277]
作者这个文档审批例子sample07例子，Approve和Reject都是通过后端生成出的aboluteUrl实现恢复workflow的。具体是在smtp4dev邮件中产生出两个带token的链接，一个是Approve，一个是Reject。我的问题是，我现在自己写前端，审批按钮如何通过请求后端API触发Fork。
![image](https://user-images.githubusercontent.com/14693616/78198957-d8e85580-74bc-11ea-846f-a34234899051.png)

**Comment by Tim1104** [comment]
你写中文，人家看的懂吗？
