### ISSUE TITLE
Workflow Instances

### ISSUE THREAD

**Issue by noxe** [elsa-workflows/elsa-core#2772]
Hi @sfmskywalker - it seems there is currently an Bug in the Workflow Instances list - it does not find the Workflow definition after publishing an new version - see video!

https://www.screencast.com/t/P5FOwMN9N1Ci

**Comment by noxe** [comment]
@sfmskywalker - any ideas where to look into - i think that should be fixed for the next release?

**Comment by sfmskywalker** [comment]
Not yet, but I know how to find it. You’re right this should be part of the next release.

**Comment by noxe** [comment]
thx man :)

**Comment by sfmskywalker** [comment]
Fixed with d433397f004dc4a4fab106083ffed2626f043c52
