### ISSUE TITLE
BUG: Activity "SendHttpRequest" does not provide content headers

### ISSUE THREAD

**Issue by vargaendre** [elsa-workflows/elsa-core#2776]
Hi,

thank you for developing Elsa, it's a great tool wit a lot of potential.

Elsa version I am using: 2.4.2.1

While I was evaluating Elsa, I ran into an issue. I created a workflow which contained a step where I wanted the **SendHttpRequest** Activity to **HEAD** an image resource and check the _Content-Type_ header.
To my surprise, the _activity.Response()_ did not contain any content related headers, but every other one. Looking at the code, I realized, there is a bug here.

In SendHttpRequest.cs line 140 ([here](https://github.com/elsa-workflows/elsa-core/blob/master/src/activities/Elsa.Activities.Http/Activities/SendHttpRequest/SendHttpRequest.cs#L140)) the `ResponseModel.Headers` is set to `HttpResponseMessage.Headers`. The issue is that `HttpResponseMessage `has a `Content `property which also has a Response property holding the content related headers like _Content-Type_. So the correct solution would be to merge these two collections.

I actually created a fix for this locally, which works fine. I am happy to create a PR for this, just give me a green light and some guidelines.

I also found another bug, related to this: a few lines above ([here](https://github.com/elsa-workflows/elsa-core/blob/master/src/activities/Elsa.Activities.Http/Activities/SendHttpRequest/SendHttpRequest.cs#L133)) the `hasContent` boolean is always true, because it checks the `Content `property of the `HttpResponseMessage `which is never null. Instead it could probably check `HttpResponseMessage.Content.Headers.ContentLength != null!` I believe. It is not a big issue, it does not result in an exception, just found while debugging the above error.

Let me know if I can proceed with a PR.

**Comment by vargaendre** [comment]
I managed to fix the above (not quite sure how, probably by installing webpack and webpack-cli locally and globally), but now I have another problem.
I cannot start any workflow, the endpoint returns just the dashboard header. I tested with other Elsa projects and those work.

How do you develop Elsa? What is the local dev environment? What OS are you using?

**Comment by vargaendre** [comment]
I managed to figure it out: in the appsettings.json there is a basePath setting of `/workflow`. This could be better documented though.

**Comment by sfmskywalker** [comment]
> @sfmskywalker How do you develop Elsa? What is the local dev environment? What OS are you using?

I use JetBrains Rider for the IDE. When developing the designer, I open the [elsa-workflows-studio](https://github.com/elsa-workflows/elsa-core/tree/master/src/designer/elsa-workflows-studio) folder with Rider and use the `npm run start` to start a local dev server for just the designer. For the server, I open the Elsa.sln in another Rider instance and run the [Elsa.Samples.Server.Host](https://github.com/elsa-workflows/elsa-core/tree/master/src/samples/server/Elsa.Samples.Server.Host) project (which I configured to listen on port 11000, to which the designer connects).

Should you be able to join one of the weekly [Elsa Community Meetings](https://github.com/elsa-workflows/elsa-core/issues/2862) on Tuesday 19:00 UTC then I'd be happy to show you.

**Comment by sfmskywalker** [comment]
> I managed to figure it out: in the appsettings.json there is a basePath setting of `/workflow`. This could be better documented though.

Duly noted 👍🏻
