### ISSUE TITLE
Getting issue at consumer end of "Elsa.Samples.RabbitMqWorker "

### ISSUE THREAD

**Issue by VartikaSharma14** [elsa-workflows/elsa-core#2779]
In sample code of RabbitMqWorker "Elsa.Samples.RabbitMqWorker "
Having issue at cosumer end workflow to print "Message" send by Producer.

In attached screenshot, consumer do not print back. 
![image](https://user-images.githubusercontent.com/99406269/155557178-2b67f95c-e548-490a-b7c2-6593858161d6.png)

Kindly look into the issue ASAP.

**Comment by constantine-v** [comment]
This issue was fixed in #2786, @VartikaSharma14 could you please get latest version and check if it works for you?
