### ISSUE TITLE
(SOS) Issue while sending message with RabbitMq activity 

### ISSUE THREAD

**Issue by VartikaSharma14** [elsa-workflows/elsa-core#2788]
Hello need help! 
I have just created one simple workflow using Rabbitmq activities.
Attached workflow json file. When I execute that it's giving exception(Refer screenshot). 

Am I doing anything wrong?

**Kindly assist. I am kind of stuck up.**
![unknown](https://user-images.githubusercontent.com/99406269/155941312-3322cdcb-9ed2-432d-b5ce-7c6d8f556bf8.png)

[workflow-definition-3437bd077966429a8c5a427cff8b0293.txt](https://github.com/elsa-workflows/elsa-core/files/8151355/workflow-definition-3437bd077966429a8c5a427cff8b0293.txt)

I am using latest version of ELSA.

**Comment by constantine-v** [comment]
Could you please check your local RabbitMQ configuration and see if exchange named 'messages' exists in your default virtual host ('/') and user 'guest' has access to it?

**Comment by VartikaSharma14** [comment]
Yes, it works. 
Thank you for your assistance and Sorry for the inconvenience.
