### ISSUE TITLE
Multiple instances of the front-end singleton `HttpClient` created

### ISSUE THREAD

**Issue by jcqvisser** [elsa-workflows/elsa-core#2790]
When retrieving the `HttpClient` singleton via `ElsaStudioRoot`s `initializing` function, a different instance is provided from the one used internally.

This causes problems when registering an Axios interceptor to add auth headers to requests made by the `ElsaClient`.

This is addressed in https://github.com/elsa-workflows/elsa-core/pull/2789

**Comment by sfmskywalker** [comment]
Fixed with 8c7d4c8b498dbac14a23b933152578f79b328584
