### ISSUE TITLE
Designer Request: Copy and Paste Steps

### ISSUE THREAD

**Issue by nickbeau** [elsa-workflows/elsa-core#2804]
We're using the Elsa Designer (in Blazor) to create some quite detailed and complex workflows, using our own activity library and database.

Would it be possible to have a copy and paste feature in the designer to allow activities and their parameters to be copied and pasted in a workflow?

This would be awesome where we have many parallel branches!

Thanks!

**Comment by sfmskywalker** [comment]
We tried to implement this for the Elsa 2 designer, but the experience wasn't great so we removed it again. We might try again, but my current focus is the [Elsa 3 designer](https://github.com/elsa-workflows/elsa-core/issues/2647).

The Elsa 3 designer is completely different and comes with multi-select & copy & paste out of the box.

There's no concrete timeline, but we are planning to backport the Elsa 3 designer to Elsa 2 which should boost your productivity significantly.

Here's a quick screen capture:

![elsa-3-designer-copy-paste-demo](https://user-images.githubusercontent.com/938393/156749013-a33ace38-246a-46c2-b6b4-5809aec47bf1.gif)

(There's no context menu implemented yet, so you can't see me pressing CTRL+C & CTRL+V of course, but you do see the sudden appearance of the pasted activities)

**Comment by nickbeau** [comment]
@sfmskywalker That looks amazing and yes, we're building some pretty large workflows using the designer now, so that would be fantastic!
