### ISSUE TITLE
Issue with Elsa.Activities.RPA.Web

### ISSUE THREAD

**Issue by nickbeau** [elsa-workflows/elsa-core#2805]
When running Elsa as part of a Server Application, I'm getting a conflict where Elsa.Activities.RPA.Web requires Microsoft.CodeAnalysis.CSharp.Scripting Version 4.0.1 and my application is using version 4.1

Would it be possible to amend Elsa.Activities.RPA.Web to use Version 4.1?

Happy to create and test a PR if that's easier?

**Comment by sfmskywalker** [comment]
Thanks for the PR!
