### ISSUE TITLE
`server-url` not working

### ISSUE THREAD

**Issue by mattbrailsford** [elsa-workflows/elsa-core#2808]
I'm trying to embed ELSA into an existing project and so am using the web components for the UI. For some reason though, I don't see the `server-url` attribute actually working.

I've embedded the web component like so (I've done some hacking to move the API endpoint to an alternative path)

    <elsa-workflow-definitions-list-screen server-url="https://localhost:44394/umbraco/backoffice/elsa/server"></elsa-workflow-definitions-list-screen>

But when the page is rendered, I just see 404's 

    GET https://localhost:44394/umbraco/v1/workflow-definitions?version=Latest&page=0&pageSize=15 404

The page being rendered is on the path `/umbraco` and so it appears like the request is just ignoring `server-url` and is just using the current path as a base instead.

**Comment by mattbrailsford** [comment]
Hmm, I'm wondering if this might be because I'm rendering the web component in an AngularJS v1 app. Maybe there is a bit of a conflict? 🤔

**Comment by mattbrailsford** [comment]
Hmm, it appears I seem to need to wrap the screen component in an `elsa-studio-root` component to get it to work

    <elsa-studio-root server-url="https://localhost:44394/umbraco/backoffice/elsa/server" base-path="/umbraco#/workflows/workflows" culture="en-US">
            <elsa-workflow-definition-editor-screen id="wf"></elsa-workflow-definition-editor-screen>
     </elsa-studio-root>

Not entirely sure why, as this isn't required based on all examples I've seen 🤔

**Comment by sfmskywalker** [comment]
I remember making `elsa-studio-root` a requirement at some point to optimize some aspects. Looking at the documentation, most quickstarts and guides seem up-to-date, with the exception of [Installing Elsa Designer](https://elsa-workflows.github.io/elsa-core/docs/next/installation/installing-elsa-designer).

If you find additional examples where the screen components aren't wrapped with `elsa-studio-root` then you can list them here and I will get them updated.

**Comment by mattbrailsford** [comment]
@sfmskywalker I think it was the `Installing Elsa Designer` that I was following so that's likely where my confusion came from. 👍

**Comment by sfmskywalker** [comment]
Makes sense. I just updated that page. For some reason the `publish` command of the documentation website is failing, so it might take some time for the update to be published 😅
