### ISSUE TITLE
CompositeActivity starting with HttpEndpoint not working as workflow trigger

### ISSUE THREAD

**Issue by ivantodorov91** [elsa-workflows/elsa-core#2811]
I am trying to create composite activity starting with HttpEndpoint that can be used as workflow trigger. I also tried adding new http bookmark provider that is picking properties from the activity and the trigger was registered but it doesn't work properly. The first call does nothing and expects the same with correlation id.

What is the best practice to achive composite activity that can be used as HttpEndpoint trigger?

```c#
        public override void Build(ICompositeActivityBuilder builder)
        {
            builder.StartWith<HttpEndpoint>(nameof(HttpEndpoint), x => x.WithPath((c) => _initPath).WithMethod("GET"))
                .WriteHttpResponse(c => c.WithResponseHeaders(x => new HttpResponseHeaders
                {
                    { "X-Correlation-Id", $"{x.CorrelationId}" },
                    { "X-Elsa-Next", $"/payments/authorize" }
                }))
                .HttpEndpoint(x => x.WithPath(c => $"/payments/authorize").WithMethod("GET"))
                .WriteHttpResponse(x => x.WithContent("success"));
        }
```

using Elsa 2.5.0

**Comment by sfmskywalker** [comment]
This scenario is currently not supported with Elsa 2, but we have an issue for it here: #738

Elsa 3 will have this capability right out of the box.
