### ISSUE TITLE
Azure Service Bus Trigger : Race Condition when restarting worker

### ISSUE THREAD

**Issue by jdevillard** [elsa-workflows/elsa-core#2812]
When working on a workflow and publishing a new version , sometime the Azure Service Trigger is not working anymore.
Listener seems to no working.

After adding some log in the WorkerManager.cs, it seems that the ICollection<Worker> _workers is not locked when receving TriggerIndexingFinished/TriggersDeleted events and so sometime the worker collection doesn't create the worker (or remove it just after adding...).

This avoid the Azure Service Bus trigger to work.

![image](https://user-images.githubusercontent.com/3254429/157129283-8012eb53-12e0-4224-a80e-e0a668b1760f.png)

**Comment by jdevillard** [comment]
Hello @sfmskywalker , 

quick question before proposing a PR on this issue, 
- can you confirm that Mediator is configure with default strategy? ie: loop through the notification handlers and awaits each one
- is there any reason why you lock on Create and not on Remove ? 

Lock on Create using Semaphore

https://github.com/elsa-workflows/elsa-core/blob/2733a642f258187fb0717182d3ebd2e0d608eea8/src/activities/Elsa.Activities.AzureServiceBus/Services/WorkerManager.cs#L36-L52

No Lock on Remove
https://github.com/elsa-workflows/elsa-core/blob/2733a642f258187fb0717182d3ebd2e0d608eea8/src/activities/Elsa.Activities.AzureServiceBus/Services/WorkerManager.cs#L75-L90


I ask about Mediator to validate that lock on remove is enough to solve the issue. If so, I could propose the PR.

**Comment by sfmskywalker** [comment]
Hi @jdevillard - Great catch. We definitely want to lock on remove as well. Mediatr isn't configured with a specific strategy, so I suppose it is using the default one. I'll happily accept your PR!

**Comment by jdevillard** [comment]
Thanks, 

i'll do this today. I've also see a issue on the CreateAndAddWorkerAsync that throw exception.

https://github.com/elsa-workflows/elsa-core/blob/2733a642f258187fb0717182d3ebd2e0d608eea8/src/activities/Elsa.Activities.AzureServiceBus/Services/WorkerManager.cs#L98-L110


The fact is in case of Creation of a worker for a bookmark (ie: listening to a subscription with an activity in the middle of the Workflow), the filter is a combination of Tag, TopicName & SubscriptionName or Tag is the WorkflowInstanceId in case of Bookmark so different for each instance and the Service Bus Hander already contains a listener for the couple (Topic, Subscription).

Can I propose in the same PR ? or would you like another issue+PR?

**Comment by sfmskywalker** [comment]
You're absolutely right - another great catch! Yes, please feel free to do this in the same PR 👍🏻  Thanks!

**Comment by sfmskywalker** [comment]
I pushed a change set that manages workers more appropriately such that there is only one worker per queue/topic and subscription combination.

To make sure multiple workflows using the same queue/topic/subscription can use the same worker instance, each worker has a collection of tags that can be used.

As long as a worker has at least one such tag, it remains active. As soon as a worker contains more more tags, is removed, since not having any tags means no workflow definitions nor workflow instances exist anymore that are listening for the queue/topic/subscription.
