### ISSUE TITLE
Example to use publish masstransit message from designer

### ISSUE THREAD

**Issue by VartikaSharma14** [elsa-workflows/elsa-core#2823]
Hello

Much help it will be if you can provide me any example to use publish/subscribe/send MassTransit message through designer.
What is the content of the message should be like. 

Using 2.5 elsa version.
Thank you.

**Comment by sfmskywalker** [comment]
Hi @VartikaSharma14 

I just pushed an updated example that prepares the system to allow you to instantiate your message types via JavaScript. [Here's the key change](https://github.com/elsa-workflows/elsa-core/blob/master/src/samples/aspnet/Elsa.Samples.MassTransitRabbitMq/Startup.cs#L54) (but not the only one, so please be sure to checkout the full example).

With these changes, you can configure the **Publish MassTransit Message** like this:

![image](https://user-images.githubusercontent.com/938393/158177258-ebd9fd1e-de20-4d2c-baa2-276e9d090368.png)

Notice that you can instantiate your message type using JS and then configure its properties as necessary. Finally, make sure to return that message object from the expression.
