### ISSUE TITLE
It is hoped that the front end can realize the pop-up personnel selector

### ISSUE THREAD

**Issue by mylidong** [elsa-workflows/elsa-core#2839]

**Comment by sfmskywalker** [comment]
Hi @mylidong, can you elaborate a little bit about your use case scenario? The "personnel selector" sounds application-specific and you should be able to implement a custom control from your own application.

One way to do that is through [plugins written in JavaScript](https://elsa-workflows.github.io/elsa-core/docs/next/extensibility/extensibility-designer-plugins#custom-field-types).
Or even better: create your own Stencil component library to write the necessary plugins and controls (much easier to use JSX than to manually manipulate DOM elements)
