### ISSUE TITLE
AddLocalization with options

### ISSUE THREAD

**Issue by gsig91** [elsa-workflows/elsa-core#2850]
Greetings,

We are using your awesome workflows library and thank you for your efforts.

We have an issue regarding Localization.

We have our Resources files in a "Resources" folder located in Class librabry project, lets name it ```Common```

We have installed Elsa-workflows in our ```API``` project.

```

│   Common
└───Resources
│   API with elsa
```

We cannot get transalted strings even thow we add 
```
services.AddLocalization(options => options.ResourcesPath = "Resources");
```
In our API Startup.

Is there a predefined way to get these translations that we are missing?

Is it mandatory to add ```services.AddLocalization(options => options.ResourcesPath = "Resources");``` after initializing our workflows ```services.AddElsa(...``` ?

**Comment by sfmskywalker** [comment]
Elsa doesn't do anything with localization from the context of ASP.NET. Can you get the translated strings when you remove Elsa from your API project (just as a test)?
