### ISSUE TITLE
Dynamic ActivityProperty value 

### ISSUE THREAD

**Issue by ethermine** [elsa-workflows/elsa-core#286]
Hi , I wonder if it's possible to dynamic fill an activity propery SelectOption from value stored in database.
An exemple would be to have a Selection property fill with user list from my database , the end user could select one/multiple users.

Can I achived it by creating a new ActivityPropertyOptionsAttribute or do you have some hint on how to do that ?

Thanks for your support !

**Comment by sfmskywalker** [comment]
That's not currently possible, but definitely a good feature to add. Unfortunately I didn't make this part extensible, but I will do so for Elsa 2. In Elsa 2, the designer will get its data from a GraphQL.

If you really need this feature, I would accept a PR that introduces a new attribute similar to `ActivityPropertyOptionsAttribute`, for example `ActivityPropertyOptionsDataSourceAttribute`, which would take a `Type` argument that implements some interface, e.g. `IActivityPropertyOptionsDataSource`. The code that handles this attribute would then simply resolve an instance of this type and invoke e.g. `IActivityPropertyOptionsDataSource.GetOptionAsync`.

Your implementation of `IActivityPropertyOptionsDataSource` can then fetch data from anywhere.

It's a bit of an ad-hoc addition, and normally I would consider making this part extensible, but Like I said, this part will change completely with Elsa 2, so I don't think it's worth too much effort.

**Comment by ethermine** [comment]
Hi ! 
 Thanks for your answer , I'll look into this , but as you said if Elsa 2 will be a big change I can certainly wait for GraphQl endpoint.

Just to be sure , if i'll try to make said property , does the designer run the GetOptionAsync at the runtime ? Because it seems the designer only get the attributes on startup.

I tried something very ugly using the WriteHttpResponse activity for an exemple and using a SelectOptions property.
In the static method provide I query a DbContext and return a SelectItem collection. But it seems to load the select list only at the startup , if I add more datas to the table , I will not see them into the designer afterward.
I'm not sure if I'm really clear in my explanations ..

Again big thanks for your help and for the work you put into the dev ;)

**Comment by ethermine** [comment]
I played a little with the source code and found the DiscoverActivities() static method , I just had to call that in the controller to refresh the activity definition when openning the designer view , and well it works fine for me.

So , again thanks for helping me ;)

**Comment by sfmskywalker** [comment]
Glad to hear you got it working :)

Regarding your question about SelectOptions, you are correct: it will only be loaded when the activities are being rendered server-side. So in your case, you would probably be better of by creating a client-side `plugin` that provides a new `field-driver` that renders a `select` element and fetches options from the server using XHR whenever the element is to be rendered. If you look at the source code of the Elsa designer (v1), you will see examples of how to create a custom field driver by looking for boolean-field-driver text-field-driver, etc.

Server-side, you will have to expose an API controller that the client-side field driver can invoke. You will also have to annotate the property on your activity with the new field type, exactly how it's done for any other property type.

**Comment by ethermine** [comment]
Agreed this will be a better version of what I've been doing ! 
I'll take a look to the source code , but as you said with the v2 it will be a big change, so not worth too much effort , but I love that I can extend it ;) 

Thanks for the hints and great answer :)

**Comment by sfmskywalker** [comment]
My pleasure!
