### ISSUE TITLE
CustomTenantAccessor causes Http Endpoint 404

### ISSUE THREAD

**Issue by ricksearcy** [elsa-workflows/elsa-core#2861]
We have implemented an ITenantAccessor for our use case of needing to have multi tenant workflows. We used the sample below. We use a reverse proxy for all our requests to apply JWT as well as any custom headers like in the example. All requests contain an "x-tenant" header. Everything works great when using the designer and or endpoints for managing workflows. They all get created correctly with the TenantId applied and are filtered in the views correctly. However a basic designer created HelloWorld http activity workflow then fails with a 404 response. 

\elsa-core-master\src\samples\aspnet\Elsa.Samples.CustomTenantIdSource

Steps to reproduce:
1. Use the example above to create a designer workflow that gets the TenantId applied from sending in the "x-tenant" header.
2. Add an http endpoint activity GET /HelloWorld
3. Add an http response activity "HelloWorld"
4. Call the workflow GET /HelloWorld or if you were using a "BasePath": "/workflows" then /workflows/HelloWorld with the "x-tenant" header included. 
5. A 404 is returned. 
6. Remove the CustomTenanatAccessor from middleware registration.
7. Repeat workflow creation and all works as expected. 

From what I can tell, all the built in endpoints call the public Task<string> GetTenantIdAsync(CancellationToken cancellationToken = default) implementation whenever a request is made so they all work as expected. But when an http activity endpoint is called the GetTenantIdAsync method is never called so the request fails.

**Comment by sfmskywalker** [comment]
Closed via #2992

**Comment by tomy2105** [comment]
@ricksearcy please let me know if it works for you now with my fix (it works for my use case, hope I got yours too).

**Comment by ricksearcy** [comment]
@tomy2105 @sfmskywalker this seemed to have fixed the issue, but then as we started implementing signals we noticed the same or similar behavior. Creating workflows with signals and a custom tenant accessor does not work. I know the original issue was around an Http endpoint. Should I open a new issue or re-open this one?

**Comment by tomy2105** [comment]
@ricksearcy  I think new one would be more appropriate...
