### ISSUE TITLE
Weekly Community Meeting

### ISSUE THREAD

**Issue by sfmskywalker** [elsa-workflows/elsa-core#2862]
Tomorrow Tuesday, March 22 (tomorrow), we'll be having our first-ever weekly community meeting!

There is no pre-determined agenda, but as a general structure we will be discussing status, do a bit of triage, maybe some small demos, talk about what's new, and pretty much anything else that comes up 😄 

These meetings will take place **every Tuesday** from **7pm to 8pm UTC** on [Discord in the voice channel](https://discord.com/channels/@me/875361723450789898/955397500251037706).

Everyone is welcome to attend!

**Note:** These meetings will be recorded for the benefit of the community to replay at a later time 🎥

**Comment by tomy2105** [comment]
Very nice work @sfmskywalker, sorry I wasn't able to attend (a bit too late in the day for me).
One comment, on the recording, I was able to hear you but not the others when they commented/asked questions.
Maybe its only me, then ignore this, otherwise there might be some additional button that needs to be "pressed" to record their audio too :).....

**Comment by jdevillard** [comment]
> Very nice work @sfmskywalker, sorry I wasn't able to attend (a bit too late in the day for me). One comment, on the recording, I was able to hear you but not the others when they commented/asked questions. Maybe its only me, then ignore this, otherwise there might be some additional button that needs to be "pressed" to record their audio too :).....

It's not you, @sfmskywalker has observe this point when publishing the recording. Should be resolved for next meeting.

**Comment by sfmskywalker** [comment]
@tomy2105 Thanks!

Maybe we can try one hour earlier so that more people have an opportunity to join of they want?

**Comment by tomy2105** [comment]
@sfmskywalker an earlier time would definitely be better for me.
From yesterday **8pm to 9pm UTC** means **10 - 11 pm CEST** which is kind of late for me :(.
But if this is best for others, I'll live with watching it afterwards :), I can always spam discussion and issues with comments :)...

**Comment by mohdali** [comment]
One or two hours earlier would help here as well, current timing is 11-12pm my time (GMT+3)

**Comment by sfmskywalker** [comment]
Alright, let's try 19:00 UTC.
