### ISSUE TITLE
Steering Committee Elections 2022

### ISSUE THREAD

**Issue by sfmskywalker** [elsa-workflows/elsa-core#2863]
With Elsa becoming quite an important project, I figured it becomes important to have proper OS governance in place. Therefore, I'm inviting everyone from the community to volunteer as a candidate to become a steering committee member.

Here are the rules for participation:

1. The candidate needs to have contributed to the project at least once in the form of a PR.
2. The committee will have a maximum of 5 members.
3. One member will be elected the Benevolent Dictator.

If you're interested in volunteering, please announce your candidacy on Discord in the [#steering-committee-election](https://discord.gg/wAQ5FkFBDH) channel and provide the following details:

- Your name
- Your location
- A small intro about who you are and perhaps a little bit about what you use Elsa for.

Then, in about two weeks, we'll stop accepting submissions for candidates and prepare the voting process 😄

**Comment by sfmskywalker** [comment]
### STEERING COMMITEE ELECTION - VOTING POLL OPENED 🎉 

The voting poll for the Elsa Workflows Steering Committee Election 2022 has now officially been opened!

- Everyone gets 5 votes to distribute amongst our 9 wonderful candidates.
- Voting is anonymous!
- The top 5 candidates with the most votes will become steering committee members for the period of May 2022 until May 2023, after which new elections will be held.
- The poll closes on 2022-04-30
- A new poll for the role of Benevolent Dictator will be held afterwards.

Please cast your vote here: https://pollunit.com/en/polls/elsa-workflows-steering-committee-election-2022

Good luck everyone! 🤩

**Comment by tomy2105** [comment]
Just a notice to everyone...
Confirmation mail from poolunit ended up in junk folder on my company email (and I guess votes are invalid without clicking on the link within) so make sure you monitor your junk folders :).....

**Comment by sfmskywalker** [comment]
Here are the final results from PollUnit:

![image](https://user-images.githubusercontent.com/938393/167827231-661d1638-39d6-4f5f-affd-db01cca1b28e.png)

Which means that we have a new steering committee with the following 5 members from May 2022 until May 2023 (we'll have re-elections then):

- Amanda Seiken - @Amanda-SVT
- Cristina Mudura - @cristinamudura
- Frans van Ek - FransVanEk
- Jérémie Devillard - @jdevillard
- Sipke Schoorstra - @sfmskywalker

Congratulations everyone!
