### ISSUE TITLE
Elsa tables are not created when registered along with another database

### ISSUE THREAD

**Issue by asmakhalid7** [elsa-workflows/elsa-core#2864]
I have created a Blazor Server App that uses an applicationDBContext derived from IdentityDbContext for user management. I have integrated Elsa workflow designer with it. I have registered both databases in startup using the following commands. Both databases are created but tables are not created in Elsa database.

services.AddElsa(elsa => elsa
                    .UseEntityFrameworkPersistence<ElsaContext>(ef => ef.UseSqlServer("Data Source=LAPTOP-JCGB13US;Initial 
                                      Catalog=Elsa;Integrated Security=True;MultipleActiveResultSets=True;App=EntityFramework"),true)
                    .AddConsoleActivities()
                    .AddHttpActivities(elsaSection.GetSection("Server").Bind)
                    .AddQuartzTemporalActivities()
                );

services.AddDbContext<ApplicationDBContext>(options =>
    options.UseSqlServer(
        Configuration.GetConnectionString("DefaultConnection")));

**Comment by asmakhalid7** [comment]
@sfmskywalker yes it works in another project where I am not using the other DBContext.

**Comment by sfmskywalker** [comment]
That’s odd. I have another application that also uses it’s own DbContext with no issue. Can you describe steps reproduce or send a sample that I can look at?

**Comment by asmakhalid7** [comment]
My issue has been resolved now. The calls to UseSqlServer were ambiguous between Elsa.Persistence.EntityFramework.SqlServer and Microsoft.EntityFramework.SqlServer. To resolve this issue, we have created a separate class to configure ApplicationDBContext while Elsa is configured in Startup. I hope this ambiguity can be removed in future version. Thank you!

**Comment by yonahochieng** [comment]
> My issue has been resolved now. The calls to UseSqlServer were ambiguous between Elsa.Persistence.EntityFramework.SqlServer and Microsoft.EntityFramework.SqlServer. To resolve this issue, we have created a separate class to configure ApplicationDBContext while Elsa is configured in Startup. I hope this ambiguity can be removed in future version. Thank you!

Thanks ... This saved me after busting my head for 2 hrs
