### ISSUE TITLE
Composite Activity monitoring show wrong timing and occurence

### ISSUE THREAD

**Issue by jdevillard** [elsa-workflows/elsa-core#2871]
I use CompositeActivity and see that monitoring is not showing the good information about the timing of the activity and the nuber of occurence.

To demonstrate the issue, here are some code and reflexion.

Let's go with a quick sample of Composite activity. The aims of this activity is to simulate some delay.
```csharp
public class CompositeDelay : CompositeActivity
    {
        public override void Build(ICompositeActivityBuilder builder)
        {
            builder
                .WriteLine("Starting Composite Activity")
                .Then<Inline>(setup:setup => setup.Set(x=>x.Function,async (c)=> {
                    await System.Threading.Tasks.Task.Delay(4 * 1000);
                    return Done();
                    }
                ))
                .WriteLine("End of the composite activity");
        }
    }
```

if we integrate this activity in a sample workflow : 
![image](https://user-images.githubusercontent.com/3254429/159809083-f031f8a3-b730-401f-81ff-4311a60a49aa.png)

after testing the workflow , we get the following information on the Instance Viewer : 
![image](https://user-images.githubusercontent.com/3254429/159809183-0815cf97-6f83-4498-8f3c-119f3dd4e19d.png)
_The subactivities are not shown on the Designer but we can see them in the Journal Panel_

if we take a look at the WorkflowExecutionLogRecords Table, we can see some information : 
![image](https://user-images.githubusercontent.com/3254429/159809351-f71e11e7-62b5-4402-9f53-40a5e8079e0b.png)

Indeed the activity `CompositeDelay` seems to execute twice and for each the executing time is few ms.
We can see that the subactivity `Inline` has an expected duration of 4 sec but these information are not used in the tracking.

After digging a little bit :  
- The Activity Stats are retrieve using the ActivityStats API which do the following work : 
  - order each activity by id and  time desc
  - get the difference between Executed and Executing (the row before) to get the execution duration
  - count the number of Executed/Executing for an activity id to get the occurrence measurement.

- An CompositeActivityBuilder is used to create the subactivity when creating the Blueprint of the CompositeActivity : 
  - Here the Builder seems to create a **Pre-Activity** with an _Enter_ outcome and a **Post-Activity** with the expected outcome of the Composite Activity. These two activity have the same AcitvityId/Name so that is why the occurrence are multiply by 2 for each use of this activity. Also, these two activity doesn't execute the implementation of the Composite Activity so the duration is just few ms.

**The expected is to get the time of the Composite activity as the sum of all the activity inside OR to get event start/end at the right place that allow the api to get the good information.**

I've done another test : 
- encapsulate the CompositeActivity alone in a new Worklow and use the activity Run Workflow with blocking property.

![image](https://user-images.githubusercontent.com/3254429/159812268-e841d049-182b-4343-9a4c-2c87d6e7f380.png)

Regarding the sample, the delay is executed two times, and this is accurate on the global stats in the instance viewer : 
![image](https://user-images.githubusercontent.com/3254429/159812381-6b92a293-1e29-40f5-a299-dcb1a3a7a7f0.png)

If we take a look at the stat for the RunWorkflow activity : 
![image](https://user-images.githubusercontent.com/3254429/159812450-d53970e0-a911-45ae-8f12-34603efb3c8d.png)

everything is good. 

I don't have check, but regarding the last elements, I think it would be good to encapsulate the composite activity builder in the same way has it is done with the RunWorkflow.

Pros: stats are accurate
Cons: we loose the info about the timing of the child activities of the Composite.
![image](https://user-images.githubusercontent.com/3254429/159813444-82ea938b-271c-432a-964e-3d4a081bdab8.png)

Do you think it could be the good way to make the composite activity : 
- create the blueprint as if it was some sort of child workflow
- execute this blueprint in the ExecuteAsync()

maybe there is some issue with scope, or dynamic property or anything else.

that's all for now ! 😄  thanks for reading 📖 !

**Comment by sfmskywalker** [comment]
@jdevillard Can we close this?

**Comment by jdevillard** [comment]
yep !
