### ISSUE TITLE
Auto-generate activity name in designer

### ISSUE THREAD

**Issue by sfmskywalker** [elsa-workflows/elsa-core#2874]
When adding a new activity to the designer, the activity should receive an auto-generated name.

This name should be generated based on the activity type name and the number of instances that currently exist while also taking into account that an activity with this name might already exists, and should therefore increase the sequence number.

For example, if the user adds a new `MessageReceived` activity to the designer, the activity should automatically get a name of `MessageReceived1`.

If the user adds another `MessageReceived` activity, it should get a name of `MessageReceived2`, etc.

But if the user now deletes the first activity (MessageReceived1) and then adds another MessageReceived, that one should not be named `MessageReceived2` since an activity with that name already exists. Instead, the algorithm should try the next number: 3.

The algorithm should be like this:

1. Take the type activity name -> `typeName`
2. Count the number of activities of this type currently in the workflow -> `count`
3. Construct a string: `${typeName}${count + 1}` -> `name`
4. Check if there is already an activity with that name.
5. If an activity with the constructed name already exists, increment `count` and go back to step 3.
6. Apply the constructed name to the name of the activity being added.

**Note**

Take into account that the user can copy & paste activities - which means that each pasted activity's name should be updated, as well as the connections (edges) between them.

*Depends on #2875*

**Comment by tomy2105** [comment]
May I suggest one small change, add a separator between sequence number and activity name, like underscore, or minus or something.
I think it would increase readability like: `MessageReceived_1`, `MessageReceived_2`.

**Comment by sfmskywalker** [comment]
Sure. How about we make this naming strategy configurable? Should be easy to do and caters to each individual's preference.

**Comment by tomy2105** [comment]
Make it configurable would be very nice addition, yes.

**Comment by sfmskywalker** [comment]
Closed via #3035
