### ISSUE TITLE
Azure Service Bus example

### ISSUE THREAD

**Issue by dgouissem** [elsa-workflows/elsa-core#2877]
Hello,
First of all tons of thanks for the project, i would like to integrate azure bus messaging, could you please provide me an example how to configure it in the workflow activity, in order to send or receive messages between the workflow activity and a topic?

thank you in advance.

**Comment by jdevillard** [comment]
Hello @dgouissem , 

you will found an example with the `Elsa.Samples.AzureServiceBusWorker` [project] (https://github.com/elsa-workflows/elsa-core/tree/master/src/samples/worker/Elsa.Samples.AzureServiceBusWorker)

This sample contains 3 workflows : 
- `ProducerWorkflow` : that send message to a queue named `greetings`
- `ConsumerWorkflow` : that listen to the `greetings` queue
- `SendAndReceiveWorkflow` : that send to a topic and listen a subscription of this topic.

The idea is the following : 

fill the Azure Service Bus Connection String in the appsettings.json
```
 "ConnectionStrings": {
        "AzureServiceBus": ""
    }
```

In startup.cs, add the Azure Service Bus Extensions with the `.AddAzureServiceBusActivities(o => o.ConnectionString = hostContext.Configuration.GetConnectionString("AzureServiceBus"))`

Then use :
- SendTopicMessage : to send a message bus to a topic
- TopicMessageReceived : to receive a message from a topic/subscription
![image](https://user-images.githubusercontent.com/3254429/160098779-eca9e522-3f55-43f0-a35c-86f48b8db8e7.png)

The Service Bus Worker of Elsa take care of creating topic/subscription if not existing.

**Comment by dgouissem** [comment]
Thank you so much.
