### ISSUE TITLE
Complete HttpEndpoint Activity

### ISSUE THREAD

**Issue by sfmskywalker** [elsa-workflows/elsa-core#2895]
The HttpEndpoint activity has yet to receive the following features:

- Read & parse inbound request body.
- Read inbound request headers.
- Read inbound request query string.

**Comment by sergeivalko** [comment]
@sfmskywalker 
Is it actual? 
as i can see HttpEndpoint already have these funcianalities
https://github.com/elsa-workflows/elsa-core/blob/8f3adadd8c71c350241023f22d23eb3f1738b9ed/src/activities/Elsa.Activities.Http/Middleware/HttpEndpointMiddleware.cs#L126

**Comment by sfmskywalker** [comment]
@sergeivalko Yes, Elsa 2 already has these capabilities, but we need to port these over to Elsa 3.
