### ISSUE TITLE
Elsa Dashboard not loading

### ISSUE THREAD

**Issue by badjuice** [elsa-workflows/elsa-core#2903]
The dashboard does not load at times. The only solution I found (and it worked) was to clean my browser cache. Not sure if the behavior is because of the browser or because of Elsa itself.

There are also cases where it does load but the top links (Workflow Definitions, Workflow Instances, Workflow Registry) do not load. For this I do not have a solution. 

![image](https://user-images.githubusercontent.com/25462821/160902903-fbe61c4b-21da-42e1-9e05-b0d465e8e68d.png)

**Comment by BadJuice** [comment]
The screenshot I uploaded is the network tab on dev tools after I clicked the Workflow Definitions link. It just hangs in there.
