### ISSUE TITLE
Monaco JS Code Complete to exclude DOM related stuff

### ISSUE THREAD

**Issue by tomy2105** [elsa-workflows/elsa-core#2907]
Just built Elsa 2.6 from code and saw Monaco code complete contains a bunch of stuff that is not usable in Elsa JS Expressions, like: `CSSAnimation` or `DOMException`.

![MonacoCodeComplete](https://user-images.githubusercontent.com/7658839/161085945-e57a165e-f824-41ca-a30e-8be818a37173.png)

I think Monaco code complete should look at `lib.es5.d.ts` and `lib.es6.d.ts` and similar but not at `lib.dom.d.ts` and similar.
Is this possible?

P.S. I think something like what is described in https://github.com/microsoft/monaco-editor/issues/1001 needs to be done but not sure... :)

**Comment by mohdali** [comment]
@tomy2105 seems the suggested solution is to set ` noLib: true` in monaco settings and then add the desired auto completion using `addExtraLib()`.

`addExtraLib` is already being used currently to add the required completions for workflow contexts, variables, etc. However, I'm not sure if there are additional functions supported by JInt that are not included in that typings file. If so, they will also be required to be included.

@sfmskywalker can you please advise on this? does the typings file generated by `v1/scripting/javascript/type-definitions/' contain all the desired types? if so then `noLib:true` could suffice to resolve this issue.

**Comment by sfmskywalker** [comment]
`v1/scripting/javascript/type-definitions` only includes .NET types, not types typically used in JS/TS. I think we need to include both (if possible):

- lib.es6.ts
- v1/scripting/javascript/type-definitions

**Comment by mohdali** [comment]
@sfmskywalker seems that updating the code as below fixes the issue, I no longer get CSS or DOM related stuff.

The content seems irrelevant because it is just reading from the file instead.

I tried with es6 but that file has reference to Dom related declarations.

```ts
 monaco.languages.typescript.javascriptDefaults.setExtraLibs([{
      filePath: "lib.es5.d.ts"
    }, {
      content: libSource,
      filePath: libUri
    }]);
```
