### ISSUE TITLE
Parallel sub-workflow

### ISSUE THREAD

**Issue by iatsuta** [elsa-workflows/elsa-core#2908]
Hello, I need to start many "sub-workflows" (each of them has a pending event from the user) and wait for them to complete.
I thought I could use ParallelForeach, but unfortunately it immediately releases the thread of execution, and the wait construct ".Add<Join>(...WaitAll)" seems to work correctly only for the Fork activity.
The second problem with ParallelForeach is that it uses the same iterator between parallel threads, and it is impossible to somehow operate on the "Input" value beyond the first activity.
```
public class TestParallelForEachWorkflow : IWorkflow
{
    public void Build(IWorkflowBuilder builder)
    {
        builder
            .ParallelForEach(Enumerable.Range(0, 10).ToHashSet(),

                iterate => iterate
                    .SetVariable("localIndex", ctx => ctx.Input)
                    .WriteLine(ctx => $"Start {ctx.GetVariable("localIndex")}")
                    .SignalReceived("abc") // run sub-wf and wait
                    .WriteLine(ctx => $"End {ctx.GetVariable("localIndex")}") // incorrect index, always 9
                    //.ThenNamed("Wait")
                )
            //.Add<Join>(join => join.Set(x => x.Mode, ParallelJoin.JoinMode.WaitAll)).WithName("Wait") // Wait only first sub-wf
            .WriteLine(ctx => "All iterations executed");
    }
}
```

Essentially I need something like:
https://github.com/elsa-workflows/elsa-core/blob/master/test/integration/Elsa.Core.IntegrationTests/Workflows/ParallelForEachWorkflow.cs
Only with a synchronous wait for the completion of the work of subprocesses.
Unfortunately, the test that checks this case is commented out:
https://github.com/elsa-workflows/elsa-core/blob/master/test/integration/Elsa.Core.IntegrationTests/Workflows/ParallelForEachWorkflowTests.cs

**Comment by sfmskywalker** [comment]
Parallel ForEach is now part of Elsa 3 via https://github.com/elsa-workflows/elsa-core/pull/4306
