### ISSUE TITLE
HTTP Endpoint not working  

### ISSUE THREAD

**Issue by Shivam-kalra** [elsa-workflows/elsa-core#2929]
I tried creating a web app in .Net standard 6.0 and  added a simple workflow for HTTP Endpoint request & response. 
but the server url returning ERR_CONNECTION_REFUSED with the URL(https://localhost:5001/data).
------------------------------------------------------------------------------------
program.cs file 
using System.Configuration;
using Elsa;
using Elsa.Persistence.EntityFramework.Core.Extensions;
using Elsa.Persistence.EntityFramework.Sqlite;
using Microsoft.AspNetCore.Builder;
using Microsoft.AspNetCore.Hosting;

using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.Hosting;

var builder = WebApplication.CreateBuilder(args);
var elsaSection = builder.Configuration.GetSection("Elsa");

// Elsa services.
builder.Services
    .AddElsa(elsa => elsa
        .UseEntityFrameworkPersistence(ef => ef.UseSqlite())
        .AddConsoleActivities()
        .AddHttpActivities(elsaSection.GetSection("Server").Bind)
        .AddQuartzTemporalActivities()
        .AddWorkflowsFrom<Startup>()
    );

// Elsa API endpoints.
builder.Services.AddElsaApiEndpoints();
builder.Services.AddCors(cors => cors.AddDefaultPolicy(policy => policy
    .AllowAnyHeader()
    .AllowAnyMethod()
    .AllowAnyOrigin()
    .WithExposedHeaders("Content-Disposition"))
);
// For Dashboard.
builder.Services.AddRazorPages();
var app = builder.Build();
if (app.Environment.IsDevelopment())
{
    app.UseDeveloperExceptionPage();
}

app
    .UseStaticFiles() 
    .UseCors()
    .UseHttpActivities()
    .UseRouting()
    .UseEndpoints(endpoints =>
    {

        endpoints.MapControllers();

        // For Dashboard.
        endpoints.MapFallbackToPage("/_Host");
    });

app.Run();

-------------------------------------------------------------------------------------------
Exported workflow 

{
  "$id": "1",
  "definitionId": "77bbdbc2d83e402082292c26a054cdce",
  "versionId": "2f40a957f6474d9f9a6291116407bda3",
  "name": "data",
  "displayName": "data",
  "version": 1,
  "variables": {
    "$id": "2",
    "data": {}
  },
  "customAttributes": {
    "$id": "3",
    "data": {}
  },
  "isSingleton": false,
  "persistenceBehavior": "WorkflowBurst",
  "deleteCompletedInstances": false,
  "isPublished": true,
  "isLatest": true,
  "activities": [
    {
      "$id": "4",
      "activityId": "e7685474-cbb7-44af-b15c-72d68897f537",
      "type": "HttpEndpoint",
      "displayName": "HTTP Endpoint",
      "persistWorkflow": false,
      "loadWorkflowContext": false,
      "saveWorkflowContext": false,
      "properties": [
        {
          "$id": "5",
          "name": "Path",
          "expressions": {
            "$id": "6",
            "Literal": "/data"
          }
        },
        {
          "$id": "7",
          "name": "Methods",
          "expressions": {
            "$id": "8",
            "Json": "[\"GET\"]"
          }
        },
        {
          "$id": "9",
          "name": "ReadContent",
          "expressions": {
            "$id": "10"
          }
        },
        {
          "$id": "11",
          "name": "TargetType",
          "expressions": {
            "$id": "12"
          }
        },
        {
          "$id": "13",
          "name": "Schema",
          "syntax": "Literal",
          "expressions": {
            "$id": "14",
            "Literal": ""
          }
        },
        {
          "$id": "15",
          "name": "Authorize",
          "expressions": {
            "$id": "16"
          }
        },
        {
          "$id": "17",
          "name": "Policy",
          "expressions": {
            "$id": "18"
          }
        }
      ],
      "propertyStorageProviders": {}
    },
    {
      "$id": "19",
      "activityId": "e447ad59-8482-43ed-958d-2f044b6ac672",
      "type": "WriteHttpResponse",
      "displayName": "HTTP Response",
      "persistWorkflow": false,
      "loadWorkflowContext": false,
      "saveWorkflowContext": false,
      "properties": [
        {
          "$id": "20",
          "name": "Content",
          "expressions": {
            "$id": "21"
          }
        },
        {
          "$id": "22",
          "name": "ContentType",
          "expressions": {
            "$id": "23"
          }
        },
        {
          "$id": "24",
          "name": "StatusCode",
          "expressions": {
            "$id": "25",
            "Literal": "OK"
          }
        },
        {
          "$id": "26",
          "name": "CharSet",
          "expressions": {
            "$id": "27",
            "Literal": "utf-8"
          }
        },
        {
          "$id": "28",
          "name": "ResponseHeaders",
          "expressions": {
            "$id": "29",
            "Literal": "data"
          }
        }
      ],
      "propertyStorageProviders": {}
    }
  ],
  "connections": [
    {
      "$id": "30",
      "sourceActivityId": "e7685474-cbb7-44af-b15c-72d68897f537",
      "targetActivityId": "e447ad59-8482-43ed-958d-2f044b6ac672",
      "outcome": "Done"
    }
  ],
  "id": "2f40a957f6474d9f9a6291116407bda3"
}

Thanks in advance

**Comment by sfmskywalker** [comment]
You would get that error if you're trying to access a server that's not actually running (on that port) or if it's listening on HTTP instead of HTTPS (or vice versa).

Are you sure your ASP.NET Core application is listening at https://localhost:5001? For example, what if you try and request a custom API controller or Razor page etc.?

Another thing to try is to run your application on a different port. Sometimes port 5000 and 5001 are somehow "taken" by a previous app and somehow messed up something in the system (just guessing here based on personal observations).

If all else fails, please attach a (simplified) version of your project that reproduces the issue.

**Comment by Shivam-kalra** [comment]
Hi @sfmskywalker,

I tried using http , https and different port no. but issue still persist. 
I have attached the source code, Can you please check and let me know the issue.

Repository : https://github.com/Shivam-kalra/ElsaQuickstarts.Server.DashboardAndServer
Thanks in Advance 

Regards, 
Shivam Kalra

**Comment by sfmskywalker** [comment]
Hi @Shivam-kalra 

I just tried your repo and started the project. The project launches successfully at https://localhost:7095/ - which means that when you want to invoke an HTTP endpoint, you need to use the same port.

For example: `https://localhost:7095/start`

![image](https://user-images.githubusercontent.com/938393/163470904-c3c22115-720b-40d9-a465-a14357f16c02.png)

**Comment by ArmyOfNinjas** [comment]
hi @sfmskywalker , from your last comment, why is it starting at port 7095? Shouldn't it be 5001 (baseUrl) in appsettings?

**Comment by sfmskywalker** [comment]
It depends on what launch profile you use to start the app. The repo share by the OP has the following set of profiles: https://github.com/Shivam-kalra/ElsaQuickstarts.Server.DashboardAndServer/blob/master/Properties/launchSettings.json

Ultimately, it doesn’t matter which port you use to host the application, just as long as you use the same port number when making HTTP requests to the HTTP Endpoint driven workflows.

**Comment by Kikkomann** [comment]
Why do you instruct people to [set the baseUrl](https://elsa-workflows.github.io/elsa-core/docs/next/quickstarts/quickstarts-aspnetcore-server-api-endpoints#appsettingsjson) in `appsettings.json`, when it is overwritten by the launch profile?

As a novice in .net, it confused me a lot, that it didn't do anything.

**Comment by davalillo** [comment]
"I don't understand why, according to the documentation on the page [https://elsa-workflows.github.io/elsa-core/docs/quickstarts/quickstarts-aspnetcore-server-dashboard-and-api-endpoints](https://elsa-workflows.github.io/elsa-core/docs/quickstarts/quickstarts-aspnetcore-server-dashboard-and-api-endpoints), it mentions that one needs to modify `Appsettings.json`. It seems pointless to modify it if the contents of `launchSettings.json` take precedence."

**Comment by sfmskywalker** [comment]
I see your point. The issue is that I assumed no presence of `launchSettings.json` because I never use it myself and always rely on Rider's project profiles to provide ENV variables, especially for secret values. I also assumed that this use of appsettings.json is obvious, but I agree that the wording could have been made clearer to prevent any confusion.

Thanks for calling this out, I'll keep it in mind for future documentation updates.
