### ISSUE TITLE
Trigger workflow from another workflow?

### ISSUE THREAD

**Issue by RingoKam** [elsa-workflows/elsa-core#293]
Is there a way to trigger a workflow from another workflow? Example:
1. Trigger inner workflow, halt workflow until inner workflow is done. 
2. Inner workflow is complete, based on completed workflow state, proceed with workflow. 

If this feature cannot be done with the current code, any pointers on how to implement one? 

My first thought would be a combination of ReceiveHttpRequest/WriteHttpResponse/Timer
1. Trigger the inner workflow via HTTP
2. SetVariable on inner workflow instanceID
3. Set Timer to query status of workflow, resume workflow on completion of inner workflow.

Any help is appreciated 🙏🙏

**Comment by sfmskywalker** [comment]
There most certainly is a way to do this. I will keep this issue open as a reminder to write a complete guide about it :+1:

You could do it like you suggested, with the HTTP activities and the workflow you described. Another way is to us the `TriggerSignal`, `TriggerWorkflow` & `Signaled` activities.

You could then do something like this:

1. Trigger the inner workflow with either `TriggerSignal` or `TriggerWorkflow`. You can pass along an Input object containing the outer workflow instance's **correlation ID**.
1. Block outer workflow using `Signaled` activity using a signal name of e.g. `"continue"`.
1. `SetVariable` on inner workflow to store the outer workflow instance's correlation ID.
1. When inner workflow is done, have it execute the `TriggerSignal` activity using the same signal name (e.g. `"continue"` and the correlation ID of the outer workflow).
1. Outer workflow continues.

This should work, but let me know if you run into troubles or have further questions.

**Comment by sfmskywalker** [comment]
This is implemented with 2.0. Documentation [here](https://elsa-workflows.github.io/elsa-core/docs/next/guides/guides-parent-child-workflows).
