### ISSUE TITLE
Updating to 2.6.0 breaks my code - Invalid object name 'Elsa.Triggers'.

### ISSUE THREAD

**Issue by semhlana** [elsa-workflows/elsa-core#2930]
I am running ELSA on dotnet 6. When updating to the latest version (2.6.0) I get the following error message
![image](https://user-images.githubusercontent.com/87702900/162697250-5dcd6ea2-d41c-48bd-9a5a-4e7f95377fb4.png)

What could be causing this issue?

**Comment by sfmskywalker** [comment]
It looks like migrations didn't run - "Triggers" is a new table that was added at some point.
