### ISSUE TITLE
Failed to load JS and CSS related to Elsa dashboard

### ISSUE THREAD

**Issue by BeiMeng** [elsa-workflows/elsa-core#294]
Failed to load JS and CSS related to Elsa dashboard，Sample19 can reproduce this bug，thank you

**Comment by sfmskywalker** [comment]
I cannot reproduce this issue. Did you build the Dashboard assets? I.e.

```bash
cd src\dashboard\Elsa.Dashboard\Theme\argon-dashboard
npm install
gulp build
```

**Comment by BeiMeng** [comment]
thank you，that is ok
