### ISSUE TITLE
Unable to find the Outcomes state of SQL Server activities in the workflow designer

### ISSUE THREAD

**Issue by jayachandra21** [elsa-workflows/elsa-core#2947]
Hello,

I am trying to design a workflow to get the data from the sql server database using the "**_SQL Server activities_**".
In this case, I have observed that, sql server activities outcomes are not displaying for the "execute SQL Query" and "Execute SQL Command" activities in designer.

![image](https://user-images.githubusercontent.com/67507118/163826026-d572b6a3-1649-404a-ab0d-bbaac208677d.png)

**Comment by sfmskywalker** [comment]
Hi @jayachandra21 

This has been fixed with 1bbb67bdd88d38722f3ecf3eb7c6f8354309615f.
