### ISSUE TITLE
IConnection Interface does not support order property nor the database json 'data'

### ISSUE THREAD

**Issue by uppercuut** [elsa-workflows/elsa-core#2957]
Quick Exmaple :

![image](https://user-images.githubusercontent.com/28313687/164407529-98bb51dd-0af2-456d-8a2b-71e937fc735e.png)

**Comment by sfmskywalker** [comment]
Hi @uppercuut , can you elaborate a little bit on what you mean with "json data" please? Do you see the "order" property there and you expected it to find it on `IConnection`? And perhaps you could explain a little bit more why this is an issue? For example, are you talking about the fact that connections in the designer "jump around" as new connections are created & deleted?
