### ISSUE TITLE
AutoMapperMappingException

### ISSUE THREAD

**Issue by wjkhappy14** [elsa-workflows/elsa-core#296]
An unhandled exception occurred while processing the request.
AutoMapperMappingException: Missing type map configuration or unsupported mapping.

Mapping types:
WorkflowDefinitionVersion -> WorkflowDefinitionVersionEntity
Elsa.Models.WorkflowDefinitionVersion -> Elsa.Persistence.EntityFrameworkCore.Entities.WorkflowDefinitionVersionEntity

**Comment by sfmskywalker** [comment]
Which branch / commit / package version is this?

**Comment by wjkhappy14** [comment]
everything is OK now！ thks so much

**Comment by chris1411** [comment]
I'm having automapper issues as well. If I try to use Elsa, it seems like it removes or breaks my existing mapper configurations. I'm using the latest preview nuget package. Any ideas?

**Comment by sfmskywalker** [comment]
That's disappointing :(
Could you provide me with exact repro steps? Ideally a sample console application I can troubleshoot?

**Comment by chris1411** [comment]
Thanks for the quick response. I was able to fix it by moving services.AddAutoMapper up before the services.AddElsa
