### ISSUE TITLE
Elsa Dashboard Blank

### ISSUE THREAD

**Issue by rangga98** [elsa-workflows/elsa-core#2968]
Hello Sir, I download Document Management code via github. first time, i build the solution and run. When i run the solution, there is an error like this:
![image](https://user-images.githubusercontent.com/69419754/165471221-559548e1-fb6e-49c2-b2f3-340d0c479664.png).
Then i try to update the package and run again , then success to run. 
i need elsa dashboard, then i run docker with this following command :
`docker run -t -i -e ELSA__SERVER__BASEADDRESS=http://localhost:5000 -p 14000:80 elsaworkflows/elsa-dashboard:latest`.
when i open elsa dashboard, there is nothing to show, all blank like this image:
![image](https://user-images.githubusercontent.com/69419754/165471710-94e60ba2-3fa3-412f-a0e5-9effd77ffa97.png)
What is wrong sir?

**Comment by sfmskywalker** [comment]
Hi @rangga98 

Make sure that when you specify `ELSA__SERVER__BASEADDRESS=http://localhost:5000`, the DocumentManagement.Web project is actually listening at that URL (http, not https and port 5000).

One other thing you could try is start the application on a different port number (I found that sometimes ports 5000 and 5001 are somehow unavailable - maybe because we as .NET developers use this port in many other local projects and the system gets confused, who knows 😄 ).

When I try and run the web app on `https://localhost:8040` and run the Docker image with the following command:

```
docker run -t -i -e ELSA__SERVER__BASEADDRESS=https://localhost:8040 -p 14000:80 elsaworkflows/elsa-dashboard:latest
```

Then it worked for me.

**Comment by rangga98** [comment]
Hi @sfmskywalker 

Thank u for your reply. But the problem is still the same, nothing shown in elsa, just blank page. I already set the project to listen at http://localhost:5000 and run the docker with this command (with the same url as the project) :
`docker run -t -i -e ELSA__SERVER__BASEADDRESS=http://localhost:5000 -p 14000:80 elsaworkflows/elsa-dashboard:latest`.
![image](https://user-images.githubusercontent.com/69419754/165654000-1fa4c047-c5a7-461a-8d50-2ed371fc17a2.png)


I also try with other port like you and listen to https://localhost:8040. and run the docker with this command:
`docker run -t -i -e ELSA__SERVER__BASEADDRESS=https://localhost:8040 -p 14000:80 elsaworkflows/elsa-dashboard:latest`. But the result is also blank page on elsa.

**Comment by sfmskywalker** [comment]
I think there is some confusion here.

The appsettings.json setting `Elsa:Server:BaseUrl` does not control the port number your application is hosted on - it is used only for scenarios where a public URL must be generated.

To control at which URL to host your application, you can use `launchSettings.json` and `ASPNETCORE_URLS`.

**Comment by rangga98** [comment]
@sfmskywalker 

![image](https://user-images.githubusercontent.com/69419754/165686697-07d92255-ec75-43c2-852b-423200c0f41f.png)
I already set `applicationUrl` in `launchSettings.json`  to `https://localhost:8040`. 
![image](https://user-images.githubusercontent.com/69419754/165687020-6d4868d7-5e3c-4d94-af30-1017c5fba7c2.png)
Like the image above, in `appsettings.json`, what is the setting for `Elsa:Server:BaseUrl`?. I set to `http://localhost:5000`. Is it right?.

And i run docker with this command:
`docker run -t -i -e ELSA__SERVER__BASEADDRESS=https://localhost:8040 -p 14000:80 elsaworkflows/elsa-dashboard:latest`

Is there something wrong with my configuration?

**Comment by sfmskywalker** [comment]
I'm not sure you can use the same port 8040 for both http and https at the same time, but just as long as your web app is successfully launched at https://localhost:8040, then your docker command seems fine.

What you might try is make sure Docker isn't caching an older image by deleting it (this happened more than once to me in the past, even though I specified the `latest` tag).

Also check your browser's console for any errors that might offer a hint.

**Comment by rangga98** [comment]
Oke Sir well noted, the web app and elsa run well now. Thank you for your support.

**Comment by Kikkomann** [comment]
> I think there is some confusion here.
> 
> The appsettings.json setting `Elsa:Server:BaseUrl` does not control the port number your application is hosted on - it is used only for scenarios where a public URL must be generated.
> 
> To control at which URL to host your application, you can use `launchSettings.json` and `ASPNETCORE_URLS`.

It would be nice, if you would put that in the [documentation](https://elsa-workflows.github.io/elsa-core/docs/next/quickstarts/quickstarts-aspnetcore-server-api-endpoints#appsettingsjson). I spent quite some time wondering why it didn't change to port 5001.
