### ISSUE TITLE
Workflow designer - User task actions not visible as outcome

### ISSUE THREAD

**Issue by mathieu-charrier** [elsa-workflows/elsa-core#298]
I have just started to play with Elsa workflow, apologies in advance if my question is not relevant.

I am using version 1.2.2.29, when I create a workflow inside the dashboard / designer and add a user task, my understanding is that each value of the separated by comma list of the property "Actions" should be available as an outcome of my user task.
No matter the values I use , only the "Done" outcome is available.

thanks

![Annotation 2020-04-22 190613](https://user-images.githubusercontent.com/64157130/80011679-7dfaba80-84cc-11ea-9448-6da78d459da2.png)
![Annotation 2020-04-22 190643](https://user-images.githubusercontent.com/64157130/80011697-83f09b80-84cc-11ea-9a3b-13e2d62c76bf.png)

**Comment by sfmskywalker** [comment]
That looks like a bug. You're right, the comma-separated list of user actions should show up as outcomes on the activity.

**Comment by sfmskywalker** [comment]
Fixed with 2.0
