### ISSUE TITLE
Activity Entity

### ISSUE THREAD

**Issue by mircotamburini** [elsa-workflows/elsa-core#2987]
I would  trigger EntityFramework ContextChanges Added, Update, Delete
Everything seams fine but in stateless context its interesting passing OLD e NEW values in Updated state.
In my case i need to evaluate  entity's properties between OLD and NEW to trigger next action.

There's some way? I can modify it or better create new activity?

**Comment by sfmskywalker** [comment]
Are you referring to the `EntityChanged` activity in `Elsa.Activities.Entity`, or something else?

**Comment by mircotamburini** [comment]
Yeah i mean exactly EntityChanged.
I made some change to improve Updated event.... if you want i can share with Pull request
