### ISSUE TITLE
How to integrate Elsa designer into Vue, how to display customized activities in Elsa designer?

### ISSUE THREAD

**Issue by BeiMeng** [elsa-workflows/elsa-core#299]
How to integrate Elsa designer into Vue, how to display customized activities in Elsa designer? Can you give an example，thank you

**Comment by sfmskywalker** [comment]
Regarding integration with Vue, please see [this issue](https://github.com/elsa-workflows/elsa-designer/issues/18).

Regarding displaying customized activities, that's currently quite limited. You can introduce new field type editors (in addition to the existing ones like boolean, list, select and text), but you can't currently take over displaying the activity on the designer for example.

You can of course define new activity types and configure its properties you want to be shown up in the activity editor. To achieve that, you need to create a plugin and register it with the `pluginStore`, which is a singleton service. See the types in the `plugins` folder for examples.

Version 2 of the designer will allow for more flexibility when it comes to rendering activities.
