### ISSUE TITLE
Add Execution Log view

### ISSUE THREAD

**Issue by sfmskywalker** [elsa-workflows/elsa-core#3]
Currently when viewing a workflow instance via the dashboard, the workflow shows which activities have executed, are blocking and have faulted. In addition, we need a separate view (tabbed?) that shows a complete log of the workflow's execution (essentially rendering its `ExecutionLog` to a list of strings).

**Comment by siskender** [comment]
Is it possible to add custom messages to this log? Also when there is an exception is the stack trace also stored (and visible in the dashboard)?

**Comment by sfmskywalker** [comment]
Yes, you can add more entries to the execution log (available on the workflow execution context). I'm not sure about the stack trace, but I believe so. If not, we should update the error handler to include it.
