### ISSUE TITLE
Implement Activity Outputs

### ISSUE THREAD

**Issue by sfmskywalker** [elsa-workflows/elsa-core#30]
Currently, activity drivers can set the `LastResult` variable on the workflow, but we need each activity to maintain its output (if any) so that other activities can read these outputs (using workflow expressions). This requires each activity to be addressable from a workflow expression. This could be done by referencing an activity's ID value, and/or by allowing a user to provide an alias for a given activity and use that.

**Comment by sfmskywalker** [comment]
See [Sample13](https://github.com/elsa-workflows/elsa-core/tree/develop/samples/Sample13)

**Comment by hassanelsherbiny** [comment]
> See [Sample13](https://github.com/elsa-workflows/elsa-core/tree/develop/samples/Sample13)

Like Is Broken

**Comment by sfmskywalker** [comment]
I fixed the link. Thanks for letting me know.
