### ISSUE TITLE
Configuring MongoDB assumes too much about consuming app's settings

### ISSUE THREAD

**Issue by dflor003** [elsa-workflows/elsa-core#302]
I just started working with this library and tried to integrate it into a project with the `Elsa.Persistence.MongoDB` package. Turns out the package wants you to place your Mongo connection string under a `ConnectionStrings` key in your `appsettings.json` and it also expects you to pass the database separate from the connection string.

This seems like quite a few assumptions on the configuration of the apps consuming this package. My connection string is not under a `ConnectionStrings` property and up until this point the database was being read from the connection string and therefore was not being passed separately.

Is there a way to make this configuration a bit more flexible? Perhaps passing the connection string and database name to the module instead of having it assume where it comes from?

An example of that could be:

```cs
services
  .AddElsa({
    elsa =>
      // Pass custom Func<IServiceProvider, string> for each thing needed by Elsa
      elsa.AddMongoDbStores(
        // Provider for connection string
        provider => provider.GetRequiredService<MongoSettings>().ConnectionString,
        // Provider for DB name
        provider => provider.GetRequiredService<MongoSettings>().DatabaseName,
      )
  });
```

**Comment by sfmskywalker** [comment]
You're absolutely right, this method is too opiniated. I changed this in Elsa 2, where it accepts two strings: the connection string and the name of the database, and then it's up to the caller to provide these values.

For V1, if the current implementation is blocking, I would accept a PR that provides an overloaded version.

**Comment by dflor003** [comment]
I was able to work around it by looking at the code of `. AddMongoDbStores` and implementing my own extension method that did something similar but provided an `IMongoDatabase` that I had registered with DI elsewhere.

Unfortunately, I had to switch over to [Workflow-Core](https://workflow-core.readthedocs.io/en/latest/) due to lack of multi-node support in Elsa 1. I may revisit when Elsa 2 is out.
