### ISSUE TITLE
Ability to hide output properties

### ISSUE THREAD

**Issue by tomy2105** [elsa-workflows/elsa-core#3022]
Activity input properties can be hidden by setting IsBrowseable to false.

I would definitely like to have ability to do that with activity output properties.

Use case, I inherit from HTTP Endpoint activity for some custom endpoint processing and would like not to expose its Output property but have my own which would be computed in some way based on output of HTTP Endpoint.

**Comment by sfmskywalker** [comment]
Makes sense. Any chance I can interest you in doing a PR? :)

**Comment by tomy2105** [comment]
Fixed in #3249 .
