### ISSUE TITLE
plus is not defined

### ISSUE THREAD

**Issue by yb12306** [elsa-workflows/elsa-core#3025]
An error occurred while I was using StartAt Activity：

Elsa.Exceptions.CannotSetActivityPropertyValueException, Elsa.Abstractions
An exception was thrown whilst setting 'StartAt.Instant'. See the inner exception for further details.
Elsa.Exceptions.ExpressionEvaluationException, Elsa.Core
Failed to evaluate expression
Jint.Runtime.JavaScriptException, Jint
plus is not defined

**Comment by sfmskywalker** [comment]
What JS expression are you using?
