### ISSUE TITLE
Writing file bytes with Out File activity from JavaScript

### ISSUE THREAD

**Issue by GotBinGo** [elsa-workflows/elsa-core#3027]
Hi,
I think it's currently not possible set the file content byte[] from JavasScript in Out File activity.
Reading with with Read File and writing the resulting bytes work fine.
Creating or modifying the byte array does not seem possible from JavaScript.

**Comment by TrinTragula** [comment]
I'm facing the same issue

**Comment by GotBinGo** [comment]
I've found there is a special case for byte[] [here](https://github.com/elsa-workflows/elsa-core/blob/ebaeabb934d97ed8077d0660fc3ff58247a23f7a/src/scripting/Elsa.Scripting.JavaScript/Services/EnumerableResultConverter.cs)
I'm wondering why we need to handle those differently.
