### ISSUE TITLE
WorkflowExecutionLog is not cleaned by retention module

### ISSUE THREAD

**Issue by mlditga** [elsa-workflows/elsa-core#3038]
Hello,

We are currently trying the retention module with elsa 2.6 and we noticed that the WorkflowExecutionLog collection is not cleaned as well as the WorkflowInstances collection. After a clean it is left with entries with WorkflowInstanceId that does not exist anymore. Would it be possible to add deletion of these too?

Thanks!

**Comment by sfmskywalker** [comment]
Hi @mlditga , which DB provider are you using? I checked out the code, and noticed that the EF Core provider of the `IWorkflowInstanceStore` takes care of deleting related records such as execution log records and bookmarks, but this wasn't done for MongoDB, YesSQL and others.

So perhaps it is better if we update thee providers to have the same behavior as that of EF Core.
That way, it doesn't matter what code is trying to delete a workflow instance - it will always delete related records.

**Comment by mlditga** [comment]
Indeed, we use MongoDB. That would be great. Thank you!
