### ISSUE TITLE
ExecuteSqlQuery Activity DataSet Output not readable in JavaScript using PostgreSQL

### ISSUE THREAD

**Issue by GotBinGo** [elsa-workflows/elsa-core#3042]
The `ExecuteSqlQuery` Activity Output is not readable from JavaScript.
I can see that the query is executed in the DB and the DataSet contains the correct query result.

The activity output looks like this.
`
{"Database":"PostgreSql","Query":"SELECT * FROM \"Schema\".\"Table\" WHERE \"Key\"='key';","ConnectionString":"Server=localhost;Port=5432;Database=db;User Id=user;Password=pass;","_Lifecycle":{"executing":true,"executed":true}}
`
The query result Output variable does not even exist.

The `ExecuteSqlCommand` activity has no problem, updates work great, it's only queries I can't use.

**Comment by GotBinGo** [comment]
Could it be that I'm trying to read the variable wrong?
I see that you can only save the Output to transient store.
Why is it that we can't persist the query output any other way?

**Comment by sfmskywalker** [comment]
Hi @GotBinGo 

The short story is that the ExecuteSqlQuery activity returns a non-de-serializable `DataSet` - which effectively breaks your workflow instance.

The long story is explained in this video: https://youtu.be/uPsuk3QvKdE?t=412
