### ISSUE TITLE
The value 'history' is not valid.

### ISSUE THREAD

**Issue by shijo-kg** [elsa-workflows/elsa-core#3050]
I am creating an Elsa Workflow Dashboard front end in Angular and backend .net core Api. Application build and run without any error, when I am clicking on Create Workflow getting a script error attached.

![image](https://user-images.githubusercontent.com/71206266/169489455-f1db674a-4184-4a16-bd32-c138353190ac.png)

**Comment by tomy2105** [comment]
Which version of Elsa are you running?
History was only recently added to server API so you need to compile from source (don't know if prerelease of 2.8 is available on MyGet).....

**Comment by shijo-kg** [comment]
2.7

**Comment by shijo-kg** [comment]
Working with Ver 2.7 source. Thanks.
