### ISSUE TITLE
Designer is not rendering in vuejs 

### ISSUE THREAD

**Issue by DevAhmedAlayyat** [elsa-workflows/elsa-core#3052]
Hi Eng./ Spike Schoorstra

First i would like to thank you for your efforts in that awesome package.

I searched a lot about how to render designer with vuejs without any good result, so i hope you or any of others who could do it right to help me.

Thanks a lot.

**Comment by jdevillard** [comment]
Hello, 

what version of vuejs do you use? I've tester with vuejs 3 starter.

First install the dashboard :
```
npm install @elsa-workflows/elsa-workflows-studio@2.7.0
npm install monaco-editor@0.33.0
```

copy monaco editor in src/assets/

Then here is the simplify files I've used : 

`Index.html`
```
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <link rel="icon" href="/favicon.ico" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Vite App</title>
    <link rel="stylesheet" href="/src/assets/fonts/inter/inter.css" />
    <link rel="stylesheet" href="/src/assets/elsa-workflows-studio.css" />
    <script src="/src/assets/monaco-editor/min/vs/loader.js"></script>
    
  </head>
  <body>
    <div id="app"></div>
    <script type="module" src="/src/main.ts"></script>
  </body>
</html>
```

in `main.ts` , add the following line (if you load as a pure Web Component, you have to specify extensions and start with ./ or ../ as explain [here](https://github.com/rollup/plugins/tree/master/packages/dynamic-import-vars#limitations)

```
import { defineCustomElements as elsaCustomElements } from '../node_modules/@elsa-workflows/elsa-workflows-studio/loader/index.js';

elsaCustomElements();
```

Then in `App.vue`, I've replace the template with :

```
<elsa-studio-root server-url="https://localhost:11000/" 
                          monaco-lib-path="src/assets/monaco-editor/min">
            <elsa-studio-dashboard></elsa-studio-dashboard>
  </elsa-studio-root>
```

take care of monaco-lib-path (don't start with /).
Change the server-url if needed.
