### ISSUE TITLE
Worfklow instances UI does not load on version 2.7

### ISSUE THREAD

**Issue by vargaendre** [elsa-workflows/elsa-core#3054]
Hi,

After upgrading to version 2.7 (from 2.4) I noticed that the /workflow-instances page would not load.
Only the header is visible and I get errors in console.

```
p-8e94f51c.js:1 TypeError: Cannot read properties of undefined (reading 'find')
    at p-2da90401.entry.js:1:23629
    at Array.map (<anonymous>)
    at Xe.render (p-2da90401.entry.js:1:23594)
    at Z (p-8e94f51c.js:1:7218)
    at Y (p-8e94f51c.js:1:7049)
    at p-8e94f51c.js:1:6620 <elsa-workflow-instance-list-screen class=​"hydrated">​</elsa-workflow-instance-list-screen>​
````

Could you please help me finding the solution for this?

**Comment by vargaendre** [comment]
Hi @sfmskywalker ,
Thank you! Indeed it was the different Elsa versions. My bad!

**Comment by sfmskywalker** [comment]
No worries, glad to hear that fixes it 😄
