### ISSUE TITLE
docker-compose error, can't find specified framework 'Microsoft.AspNetCore.App' version '3.1.0'

### ISSUE THREAD

**Issue by RingoKam** [elsa-workflows/elsa-core#307]
Hi,  I try ran `docker-compose up` from source root, but ran into issue. 
```
elsa-dashboard_1  | It was not possible to find any compatible framework version
elsa-dashboard_1  | The specified framework 'Microsoft.AspNetCore.App', version '3.1.0' was not found.
elsa-dashboard_1  |   - The following frameworks were found:
elsa-dashboard_1  |       3.0.3 at [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
```
any idea how to fix? Trying to experiment with the source code. 

Sorry not that good with docker 🙏

**Comment by sfmskywalker** [comment]
No worries, I'll get it fixed.

**Comment by sfmskywalker** [comment]
The Dockerfile was using SDK 3.0, whilst the Elsa projects target  SDK 3.1, which explains the error. I pushed an updated Dockerfile just now.
