### ISSUE TITLE
Workflow Journal

### ISSUE THREAD

**Issue by sfmskywalker** [elsa-workflows/elsa-core#3078]
As an improvement compared to Elsa 2, I want to explore the possibility of displaying execution log records filtered by activity.
In Elsa 3, parent activities are responsible for scheduling child activities, so it might make sense to be able to look at the execution trail of such an activity.

For example, when looking at a `ForEach` activity, one might be interested in looking at each iteration's execution path, perhaps grouped by iteration number.

The journal should also be able to show an unfiltered flat-list of all execution log records.

- [ ] API endpoints to query execution log records
- [ ] UI panel to display execution log for a given activity

Blocked by #3082

**Comment by sfmskywalker** [comment]
Sample journal (first iteration, we can improve later):

![image](https://user-images.githubusercontent.com/938393/175963515-45f8ad76-9efb-46ee-86bd-48765477a17d.png)

**Comment by tomy2105** [comment]
Nice one....
If you can also indent/color different level differently/make a tree/somethinng so it is better understood which one are children of which would be prefect.
