### ISSUE TITLE
Input type password css is not included in the release css

### ISSUE THREAD

**Issue by javiercoll** [elsa-workflows/elsa-core#3079]
Hi all,

I added @elsa-workflows/elsa-workflows-studio 2.7.0 to my project. I was implementing a password field, but I noticed that there are not styles for type password (as there are for input type text, for example)

Digging around, I noticed that in the node_modules\@elsa-workflows\elsa-workflows-studio\dist\elsa-workflows-studio\elsa-workflows-studio.css the rules for type password are not in place, but in the source code in src/designer/elsa-workflows-studio/src/globals/tailwind.css are:

![image](https://user-images.githubusercontent.com/1391793/170667408-9e7580f1-d01a-4d95-a769-68ce969308f8.png)

Thanks!

**Comment by sfmskywalker** [comment]
Hi @javiercoll 

I think that rule is being optimized away since it's not being used by any of the components.
Do you want to try a PR where the style is kept, by adding a hidden HTML element in the index.html file?

**Comment by javiercoll** [comment]
Hi @sfmskywalker ,

Although it's not being used by any component, as you know there is a way to add a password field using a plugin (as specified here: https://elsa-workflows.github.io/elsa-core/docs/next/extensibility/extensibility-designer-plugins#custom-plugins)

By adding that CSS rule, the password will actually fit the look and feel of any other text input without tweaking your own css.

I'll try to raise the PR 👍
