### ISSUE TITLE
Cancel running workflows

### ISSUE THREAD

**Issue by sfmskywalker** [elsa-workflows/elsa-core#3093]
### Discussed in https://github.com/elsa-workflows/elsa-core/discussions/3053

<div type='discussions-op-text'>

<sup>Originally posted by **gor8808** May 22, 2022</sup>
I have this workflow 

While(true) 
  |(iterate)|
Writeline()

When I cancel this workflow (after execution) using this endpoint -- ​/v1​/workflow-instances​/{id}​/cancel it still keeps executing(printing to console)

Can you specify what means canceling the instance and in which cases it cancels the instance? 
BTW I can't find any docs regarding canceling endpoint
</div>

See also: #3163, #4177

**Comment by payoff** [comment]
Will the same endpoint be used or do you plan to create a new one?

**Comment by johnwc** [comment]
@payoff not sure who you are asking that towards, nor what you are referring to. Why would there be a new cancel endpoint built into Elsa?

@sfmskywalker after using Elsa for some time. We're also finding that a workflow may say faulted in the dashboard, but if we view the node's log; an activity is still logging to console.

**Comment by mathijs-dumon** [comment]
I'd like to see proper support for cancelling workflows in elsa v3 as well

I've had a look around the code, and I think this boils down to supporting it in the IActivityScheduler implementations and the WorkflowExecutionContext?

RunAsync on IWorkflowRunner alraedy takes a cancellation token, it seems like it's passed down reasonably well (at least the WorkflowExecutionContext has it). Only the actual activity schedulers don't consider if the token is cancelled to stop scheduling activities - it would make sense to add a check in there.

I see most activities check the cancellation token on the activity execution context, WriteLine doesn't though ;-)

let me know if there's anything I can do to help, still finding my way around Elsa, but I wouldn't mind contributing on this one

**Comment by mathijs-dumon** [comment]
sorry I was looking at the release candidate version of the code, it looks like the current status on the v3 branch is that cancellation tokens are handled properly - at least when executing workflows directly.

so what remains to be done (if I understand this) is to expose this as an API
is there an architectural view on how to do this?

**Comment by sfmskywalker** [comment]
@raymonddenhaan I think we now support this, am I right?

**Comment by sfmskywalker** [comment]
Confirmed with @raymonddenhaan that this is now part of `main`.
