### ISSUE TITLE
Problems with German Umlaut qith Liquid Syntax

### ISSUE THREAD

**Issue by noxe** [elsa-workflows/elsa-core#3097]
Hi @sfmskywalker ,

we have found an small problem when using liquid syntax and sending mails - when the text contains german "umlauts" (Ä Ü Ö, ä ö ü)

This simple set variable

![image](https://user-images.githubusercontent.com/158478/171208798-b2b906ef-1aa3-49ad-8aed-74e2205a18ec.png)

then sending an mail like this:

![image](https://user-images.githubusercontent.com/158478/171208934-7495e113-6a38-4855-97a3-4835cd01bd09.png)

Results in this Subject - from what i see it is HTML encoded:

![image](https://user-images.githubusercontent.com/158478/171209077-336ee2b6-16a9-435f-a925-166daa6f412d.png)

Any idea how to get rid of this?

Many thx

**Comment by noxe** [comment]
@sfmskywalker - any ideas?

**Comment by noxe** [comment]
oh - that works - thank you for this Info - did not find this filter in the docs when i searched it :)

**Comment by sfmskywalker** [comment]
Good point, it should be added to the Elsa documentation site. Until that is done, you can find the info [here](https://github.com/sebastienros/fluid#html-encoding).

Another good source of available tags and filters can be found [here](https://shopify.github.io/liquid/).

**Comment by noxe** [comment]
nice - thank you!!
