### ISSUE TITLE
Cosmos Persistence

### ISSUE THREAD

**Issue by steve99** [elsa-workflows/elsa-core#311]
Hi, I have configured Elsa using the default SQLite option which is working fine inside my App, but when flipping that over to Cosmos, it is not working.  It is saving a new workflow but only to memory, if I stop that DEBUG instance and start it again their is no persistence.  

I can't find working examples of Cosmos, so can't check if I have missed something.  Below is an entry for both.  No errors and appears to work.

SQL Entry in startup.

        Services
        .AddElsa(elsa => elsa.AddEntityFrameworkStores<SqliteContext>(options => options.UseSqlite(Configuration.GetConnectionString("Sqlite"))))
        
Cosmos Entry in Startup.

        .AddElsa(elsa => elsa
        .AddCosmosDbProvider(url, key, databasename, container
        )

Any pointers please?  I am using the NUGET packages, but if you want me to use full code I can do that.  I think I am right in saying that would be the only way to step through code.

I am getting this output in debug which looks positive.

DocDBTrace Information: 0 : StartRefreshLocationTimerAsync() - Invoking refresh
DocDBTrace Information: 0 : RefreshLocationAsync() refreshing locations
DocDBTrace Information: 0 : Current WriteEndpoints = (https://************-westeurope.documents.azure.com/) ReadEndpoints = (https://*************-westeurope.documents.azure.com/)

Thanks,
Steve.

**Comment by steve99** [comment]
Should point out happy to assist in this if required.

**Comment by sfmskywalker** [comment]
Hi Steve,

Unfortunately I haven't been able to keep up the CosmosDB provider due to time constraints. Any help you can provide would be much appreciated. Please feel free to fork the project, make any changes necessary to fix up the CosmosDB provider, and let me know if I can help with any questions you may have.

**Comment by steve99** [comment]
OK, that is a new one on me, but will give it a go.  What is the last working version of it?  I couldn't even compile the Development one when trying to look into it earlier, as suspect you were in the middle of doing something with AutoMapper, version 2.0

**Comment by sfmskywalker** [comment]
I was indeed, but that works is finished. I'll have a quick look at the compilation error.

**Comment by sfmskywalker** [comment]
I'm not getting any build errors. Can you send me a screenshot with the error you're getting?

**Comment by steve99** [comment]
![image](https://user-images.githubusercontent.com/1472692/82486677-248aa900-9ad5-11ea-8663-0a78a6f2e17d.png)

Imapper is not found, which will be from the main project.  What have you in startup for Automapper related stuff?  

![image](https://user-images.githubusercontent.com/1472692/82486946-88ad6d00-9ad5-11ea-88d6-55c0324b52ff.png)

Can't find MappingProfile.  Nothing called that in the Persistence project, is that coming from the main project also?  In your project I added in the Nuget package for Elsa.Core (1.2.2.29) and you already had the Azure Document DB Nuget.

**Comment by sfmskywalker** [comment]
Just to be sure, what is your current commit hash? It should be f999e8627c5c68056d6dd8fb8019d2e16b52f7e3

Not sure I understand what you mean with having added a NuGet package for Elsa.Core (1.2.2.29), but when working on the full source code, only add project references to other Elsa projects.

**Comment by steve99** [comment]
I have worked it out, well to compile it at least.  I needed Elsa.Abstractions but adding the latest Nuget package didn't work as it didn't have your latest changes.  Taking the project from Github and adding into my solution as source code worked.

You are working with full source code so you always have the correct versions and dependencies.  I wasn't, I was using Nuget packages until I wanted to see why Cosmos wasn't working.  I will do some more on it tomorrow (UK Based), and will see how I get on.  I'm being a little slow on the uptake as this is all new code to me and haven't got my head around it yet.  I will get there.

**Comment by sfmskywalker** [comment]
I see, yeah that makes sense. It's probably easiest if you clone the project and work in the full source solution directly when working on the CosmosDb (DocumentDb) package, especially when opening the Samples.sln solution where you might want to add a "playground" sample console application.

This way it's easier to step through the code as needed.
But up to you of course. 

I totally hear ya about the uptake. I'm here to help when you need me.

Thanks for looking into this!

**Comment by steve99** [comment]
Hey, worked it out.  You have to initialise the two stores in ServiceConfigurationExtensions, otherwise it just uses the in-memory storage by default it never calls the extension library otherwise.

You will see I have added the two singleton lines to the Builder and can actually delete the two methods.  This is now calling Cosmos.

`using System;
using Elsa.Persistence.DocumentDb.Services;
using Elsa.Extensions;
using Elsa.Mapping;
using Elsa.Persistence.DocumentDb.Mapping;
using Microsoft.Extensions.DependencyInjection;

namespace Elsa.Persistence.DocumentDb.Extensions
{
    public static class ServiceConfigurationExtensions
    {
        public static CosmosDbElsaBuilder AddCosmosDbProvider(
            this ElsaBuilder builder,
            string url,
            string authSecret,
            string database,
            string collection,
            DocumentDbStorageOptions options = null)
        {
            if (string.IsNullOrEmpty(url)) throw new ArgumentNullException(nameof(url));
            if (string.IsNullOrEmpty(authSecret)) throw new ArgumentNullException(nameof(authSecret));

            var storage = new DocumentDbStorage(url, authSecret, database, collection, options);

            builder.Services
                .AddSingleton(storage)
                .AddSingleton<IWorkflowInstanceStore, CosmosDbWorkflowInstanceStore>()
                .AddSingleton<IWorkflowDefinitionStore, CosmosDbWorkflowDefinitionStore>()
                .AddMapperProfile<NodaTimeProfile>(ServiceLifetime.Singleton)
                .AddMapperProfile<DocumentProfile>(ServiceLifetime.Singleton);
            
            

            return new CosmosDbElsaBuilder(builder.Services);
        }

        public static CosmosDbElsaBuilder AddWorkflowInstanceStore(this CosmosDbElsaBuilder configuration)
        {
            configuration.Services.AddSingleton<IWorkflowInstanceStore, CosmosDbWorkflowInstanceStore>();
            return configuration;
        }

        public static CosmosDbElsaBuilder AddWorkflowDefinitionStore(this CosmosDbElsaBuilder configuration)
        {
            configuration.Services.AddSingleton<IWorkflowDefinitionStore, CosmosDbWorkflowDefinitionStore>();
            return configuration;
        }
    }
}`

  The larger issue is that partition keys are now required of Cosmos Containers, and whilst you can create them without using the API it is deprecated so no point going down that route.  I have something in mind which will allow this to be scale, the easy answer is hardcode a partition key, but not disimilar to the SQL lite solution, it will crash and burn with a few million instances thrown at it.  I am going to give this more thought and will then update the code and test it out. 

Very happy to put together a sample for the library.  Let me know if you don't like what I am doing here and can adjust accordingly.

Cheers, 
Steve.

**Comment by steve99** [comment]
Knees deep in the code now.  I have chosen to create two separate containers in Cosmos, one for definition documents and the other for instances.  I need to create a partition key for each, as no partition key is a problem longer term and will not scale without.  For instances I decided to use Status, and for the definitions I am actually using a static Int, as the number of definitions in one installation is never going to be a problem, instances on the other hand could be in millions.  The challenge I am now faced with, is that to use status I need to update the IWorkflowInstanceStore to take an optional status value, which sits in the abstraction project and then cascades through the other persistence providers as they all inherit IWorkflowStore.  Thoughts??  I was quite happy changing the Cosmos project, but now stepping on your toes so we need to agree best approach.  

As an example of the last line in the Elsa.Abstractions\persistence\IWorkflowInstanceStore.cs

`        Task DeleteAsync(string id, CancellationToken cancellationToken = default, WorkflowStatus? status = null);`

**Comment by steve99** [comment]
OK, subject to cleanup and more thorough testing, I'm done.  Will discuss when you are available to chat through the Interface change and cascaded changes to each persistence project.

**Comment by sfmskywalker** [comment]
Nice!

About the partition key, you should not use `Status`, because that value will change. See [Choosing a partition key](https://docs.microsoft.com/en-us/azure/cosmos-db/partitioning-overview#choose-partitionkey).

Instead, it should be fine if you simply use the same value as the Workflow Instance ID, which by default is a GUID, which should provide a nice distribution across partitions. CosmosDB itself will take care of the rest. At least, that's what I've been told 😄 

Let me know if there's anything else you'd like to discuss.

**Comment by steve99** [comment]
I hit that today in testing, so the workaround to that is that you delete and recreate the document, which is a pain in the ass, but would work.

The challenge with your solution is that you don't know what that GUID is without scanning every partition which is costly and they are saying they are deprecating cross partition queries.  You can't create a container without a key now in the portal, which is largely why the original code failed.

I did consider using the WorkflowDefinitionId, but that has its challenges also, getting distinct values is costly as it scans the entire container and whilst I would add the ID at creation to a SQL DB that is not a valid pattern for open source software.  Using status, there could easily be an archiving process as finished workflow wouldn't need to be around forever.  Mostly you would be interested in executing, which is going to be smaller and therefore quicker.  Welcome thoughts.

**Comment by steve99** [comment]
OK, that change is also done, but failed miserably when I load tested it with a HTTP receiver.  I need to build in a throttler or think about using the timer for everything and mix it up with a service bus/queue from an architecture point of view.  I will discuss with our Enterprise Architect and see what he thinks.

**Comment by VORUSRIK000** [comment]
I am testing out Cosmos DB persistence and facing the same issue, no instance data is getting stored in configured cosmos DB. I am using Nuget version 1.2.2.29. On explicit call to add the line "services.AddSingleton<IWorkflowInstanceStore, CosmosDbWorkflowInstanceStore> ();", am getting Cross Party query exception, probably because the partition id is not specified as mentioned somewhere above.
Can you let me know if the workaround is to not use nuget but instead use code and make required fixes? If so, did you identify how and where to handle the partition id?

**Comment by andyevans2000** [comment]
Is there a working persistence store for CosmosDB? I have been using EF and SqlServer but it is really struggling with load

**Comment by steve99** [comment]
I do have a working scenario, but it does require core changes, so hasn’t been simply dropped back in as a project update.  Happy to share of course!

Sent from my iPhone

On 10 Sep 2020, at 12:06, Andy <notifications@github.com> wrote:

﻿

Is there a working persistence store for CosmosDB? I have been using EF and SqlServer but it is really struggling with load

**Comment by andyevans2000** [comment]
It would be great if you could share
