### ISSUE TITLE
Reading binary BlobStorage properties fails

### ISSUE THREAD

**Issue by stuartmcgillivray** [elsa-workflows/elsa-core#3115]
When reading binary type data from the BlobStorageWorkflowStorageProvider it's trying to read it as Json.

This seems to be because it doesn't persist the change to the metadata in the blob.

https://github.com/elsa-workflows/elsa-core/blob/0d178386275a750da8d2073a154c2959956cba96/src/core/Elsa.Core/Providers/WorkflowStorage/BlobStorageWorkflowStorageProvider.cs#L35-L54

To do this it will need to call after updating the metadata.

```csharp
await _blobStorage.SetBlobAsync(blob, cancellationToken);
```

**Comment by sfmskywalker** [comment]
Yes let’s close this 👍🏻
