### ISSUE TITLE
Workflow fork with timer facing recurring loop

### ISSUE THREAD

**Issue by rahuljain003** [elsa-workflows/elsa-core#3134]
Hello,

I am trying to simulate your published document approval workflow. This workflow has been taken from below link

https://github.com/elsa-workflows/elsa-guides/blob/master/src/ElsaGuides.ContentApproval.Web/VisualDocumentApprovalWorkflow.json

Issue is that right part of workflow fork activity with timer (Remind) getting resume again and again whereas I have approved the document.
I tried to find the resolution but did not get. 

Note: This workflow working very fine up to 2.6 version, after this version not working. Please let me know what's the mistake i am doing.

**Comment by mohdali** [comment]
There was a change in Join activity behavior. Right now it doesn't clear all blocking activities, so you need to insert a Finish activity in the other branches to complete the workflow.

**Comment by rahuljain003** [comment]
That is great. It's working fine. But how can I get all updated changes. Is any documentation would you provide for better understanding.

**Comment by mohdali** [comment]
> That is great. It's working fine. But how can I get all updated changes. Is any documentation would you provide for better understanding. 

It was mentioned in 2.7 release notes as a fix to eager Join. 

https://github.com/elsa-workflows/elsa-core/releases/tag/2.7.0
