### ISSUE TITLE
Dashboard - Search by Correlation ID

### ISSUE THREAD

**Issue by chris1411** [elsa-workflows/elsa-core#314]
Would it be possible to add search/filtering options to the dashboard? When viewing workflow instances, it would be great if we could search by correlation ID.

**Comment by steve99** [comment]
Hi Chris, If you look at my issue on #312 , you will see the position on the dashboard.  It would be straightforward to add though as that method if already there.

**Comment by sfmskywalker** [comment]
Implemented in the Blazor dashboard in Elsa 2.
