### ISSUE TITLE
Cron missing expression property in designer

### ISSUE THREAD

**Issue by ricksearcy** [elsa-workflows/elsa-core#3141]
When trying to add a cron activity to a new workflow in the designer the cron activity does not show the expression property input. I have added AddQuartzTemporalActivities() to the startup so I don't know what is missing? 

![image](https://user-images.githubusercontent.com/6527752/174633281-ac98bdc7-8160-4af0-b230-c3de6412e513.png)

**Comment by mohdali** [comment]
Which version are you using? Any errors in developer console?

**Comment by aghasemiN** [comment]
I am having the same problem and I am using elas 2.8.2 and I am seeing this error in developer console
![5af3e58f-24d7-41e0-a761-eaf450ec01ce](https://user-images.githubusercontent.com/107998456/193276618-b7be9125-6a2d-4c8c-8203-13b4c6395462.jpg)

**Comment by sfmskywalker** [comment]
@aghasemiN I just tried with a project using Elsa 2.8.2 with no issue. Can you share a minimal ASP.NET Core project + Elsa that demonstrates this issue?
