### ISSUE TITLE
Your documentation is the worst I've ever seen

### ISSUE THREAD

**Issue by Scholar01** [elsa-workflows/elsa-core#3147]
Your documentation is the worst I've ever seen

**Comment by sfmskywalker** [comment]
Thank you @nkosi23 for taking the time to elaborate. Although I very much enjoyed writing the documentation we have so far, it's valuable to understand where it lacks and how it can be done better and perhaps differently. I will take your feedback to heart with future updates.

**Comment by sfmskywalker** [comment]
That would be fantastic. In the meantime, perhaps the [console samples](https://github.com/elsa-workflows/elsa-core/tree/master/src/samples/console) can shed some light on certain use cases. Fair warning: I was lazy and did not provide proper README documentation ;)

Of course, feel free to ask any questions you have here and on the [Elsa Workflows Discord server](https://discord.gg/hhChk5H472).

**Comment by chrisbecke** [comment]
the negativity here is a bit much, but ngl, the docs are pretty bad:
- aspnet core 6 apps don't generate a Startup.cs anymore, so pretty much all the "how to bootstrap a new project" guides just don't work.
- Elsa is at least at 2.8 now, and the docs are ostensibly for version 2.2
- The doc site lacks search. If there are any pages in the docs detailing how to enable features (such as WebHooks) I can't find them.
- Major features, such as how to enable Features, what features exist, are not even acknowledged as a thing by the docs.

My only comment regarding Docker is not enough use of Docker is made: A csproj ApiServer with docker based Dashboard is easy to setup but not mentioned. imo this should almost be the default quickstart.

**Comment by badihi** [comment]
A considerable portion of code lacks any kind of documentation. Not even a descriptive comment in the source code.
For example I wanted to find out about the method `AddCompetingMessageType()`.
I googled it and found nothing. I searched it in GitHub, but no XmlDoc or descriptive comments was available.
Please see the situation from my perspective for a moment and tell me how I'm going to find out what `AddCompetingMessageType()` means at all?! The only way for a person like me is following the rabbit hole deep down into the source code to understand what it is doing.
Each public method in the code must have at least a single line of description, and it is the least you can do about documenting your project.
