### ISSUE TITLE
Use of  IDictionary<string, object> in CommonJavaScriptEngineHandler.cs

### ISSUE THREAD

**Issue by anktsrkr** [elsa-workflows/elsa-core#317]
Hi, 
It seems latest preview of JInt does not support `IDictionary<string, object>`  , While running with latest JInt (**v 3.0.0-beta-1778**), it is getting below error - 

`System.ArgumentException: 'collection is supposed to either have Count or Length property'
`

and this error is coming from CommonJavaScriptEngineHandler.cs while setting the value 

[https://github.com/elsa-workflows/elsa-core/blob/f999e8627c5c68056d6dd8fb8019d2e16b52f7e3/src/scripting/Elsa.Scripting.JavaScript/Handlers/CommonJavaScriptEngineHandler.cs#L35](https://github.com/elsa-workflows/elsa-core/blob/f999e8627c5c68056d6dd8fb8019d2e16b52f7e3/src/scripting/Elsa.Scripting.JavaScript/Handlers/CommonJavaScriptEngineHandler.cs#L35)

[https://github.com/elsa-workflows/elsa-core/blob/f999e8627c5c68056d6dd8fb8019d2e16b52f7e3/src/scripting/Elsa.Scripting.JavaScript/Handlers/CommonJavaScriptEngineHandler.cs#L40](https://github.com/elsa-workflows/elsa-core/blob/f999e8627c5c68056d6dd8fb8019d2e16b52f7e3/src/scripting/Elsa.Scripting.JavaScript/Handlers/CommonJavaScriptEngineHandler.cs#L40)

Is there any specific reason, here we are using `ExpandoObject` and casting into `IDictionary<string, object>`?
If not then, we can simply use - 
` var expando = new Dictionary<string, object>();` 
since it is just a local variable and it will be future proof.

**Comment by sfmskywalker** [comment]
There was a reason I'm using `ExpandoObject`, but I don't recall exactly what it was. Probably the reason is such that JS expressions can use dot-notation when accessing properties on the ExpandoObject. If that's also possible when using a dictionary directly, then that would be fine.

Please feel free to try that out, and if it works, submit a PR.

Thanks!

**Comment by anktsrkr** [comment]
Hi @sfmskywalker, as per Jint documentation any javascript object converts into  expando objects (IDictionary<string, object> and dynamic) and probably that is why ELSA also use  expando objects to support javascript objects.

JInt (**v 3.0.0-beta-1778**) had a issue with that and that's reason ELSA also broke. Current latest **v3.0.0-beta-1828** fixed that issue. 

I am going to close this issue, as I found JInt is in beta release, and they might have some breaking changes in upcoming releases, If needed we can work on this after v3.0 final release of JInt.

Thanks
