### ISSUE TITLE
Passing variables from activity in the designer to the next activity

### ISSUE THREAD

**Issue by steve99** [elsa-workflows/elsa-core#318]
How does this work in practice please?  So lets say I call an HTTP endpoint which returns some content, can I pass that to the next activity with a parameter or set a parameter with a fixed  value or query string to pass to it?

I can see every example you are problematically setting it, which isn't what I want to aim at, I want to have lots of custom activities for my app, but the user to designer the workflow.

**Comment by sfmskywalker** [comment]
Sure So, in your custom activity, invoke the HTTP endpoint you want from the `OnExecuteAsync` method.

Now there are two options to make the response available to the rest of the workflow activities:

1. Invoke `workflowContext.SetLastResult()`, or:
1. Invoke `workflowContext.SetVariable()`.

When using `SetLastResult`, the next activity can use a workflow expression to access this value.
For example, let's say your HTTP endpoint returned a JSON payload representing a customer:

```json
{
   "FullName": "John Doe",
   "Email": "john@doe.com"
}
```

If your next activity were e.g. the `SendEmail` activity, you could provide the following JS expression for the `To` property:

```javascript
lastResult().Email
```

I wanted to provide this example using liquid syntax instead, but just noticed I'm not exposing the `lastResult` via liquid yet.

But if you use the `SetVariable` approach, you can access the object and its properties from liquid as follows:

```liquid
{{ Variables.MyCustomer.Email }} // Assuming your variable is named "MyCustomer".
```

In Elsa 2, `lastResult` is deprecated in favor of returning activity output values directly.

**Comment by steve99** [comment]
Perfect thanks, Makes sense, enough to start coding with it at least.  I don't want to have to redo anything and given our conversation on Timers, am I best to start building against 2?

**Comment by mindfocus** [comment]
so can we keep my activity's sensitive data only pass to next activity not the third or someone global , for safe?

**Comment by sfmskywalker** [comment]
@steve99 Since the elsa-2 branch is under a lot of flux, I'm afraid it would be too frustrating to target it, so probably best to stick with master/develop for now. I'll merge things into elsa-2 from time to time. You're of course welcome to do the same if you want.

**Comment by sfmskywalker** [comment]
@mindfocus Unfortunately, any data stored by any activity is available to any activity within the workflow. There's a separate issue however to have the ability to store secrets / sensitive data separate from the workflow, or at least store it in encrypted form.

**Comment by greight01** [comment]
@sfmskywalker Do you have any example of passing input to the "TriggerSignal" activity from the designer?  I have a JSON object stored in a variable that I would like to pass to another workflow but cannot figure out the syntax to do this from the designer.  If I pass {{ Variables.VariableName }} liquid or variable('VariableName') javascript to the Input the workflow faults with a cast error when trying to cast to the Variables model.

**Comment by steve99** [comment]
@greight01  This got me on the right track in addition to the above.  

https://medium.com/@sipkeschoorstra/building-workflow-driven-net-core-applications-with-elsa-139523aa4c50

**Comment by greight01** [comment]
Thank you for that.  I saw that, but it looks like that is passing to the trigger signal programmatically, so I know it is possible.  I just don't know the syntax from the designer.

**Comment by sfmskywalker** [comment]
@greight01 The following JavaScript expression should work for the `Input` property of the **TriggerSignal** activity:

```
return { 
FirstName: 'John',
LastName: SomeWorkflowVariable,
Phone: output('SomeActivityName')
}
```

**Comment by rparmar2021** [comment]
return { 
FirstName: 'John',
LastName: SomeWorkflowVariable,
Phone: output('SomeActivityName')
} 
Has NOT worked for me;
I have workflow that calls other workflow; 
Passing Data  Output.SetVariable("IncomingFileMetaData", dictionary); in Activity called InteractionActivity;
Therefore 
I tried Javascript approach above but it is failing; Please help; Thx

**Comment by sfmskywalker** [comment]
Can you send a repro I can look at?

**Comment by xitac** [comment]
Proposed solution did not work for me either, but got me in the right direction. 
You need to wrap the value inside another object, like this:
return {
    FirstName: { Value: 'John' },
    LastName: { Value : SomeWorkflowVariable },
    Phone: { Value : output('SomeActivityName') }
}
