### ISSUE TITLE
JavaScript: Static Properties on Types

### ISSUE THREAD

**Issue by Dioltas95** [elsa-workflows/elsa-core#3196]
Hi,

Having issues with registering types for JavaScript, We are trying to use `Encoding.UTF8` in JavaScript. Can access the Methods (See Picture 1) but not the static properties (UTF7, UTF8, ASCII etc) unless an instance is created like new `Encoding().UTF8` (See Picture 2)
### No Static Properties
![Encoding](https://user-images.githubusercontent.com/80762652/178506033-5f5edf30-39fb-480e-bda5-3f4a71ea1588.PNG)
### Have to Create instance to access Static Properties 
![EncodingInstance](https://user-images.githubusercontent.com/80762652/178506036-112b898c-aeeb-4c7b-a60a-5b5501b7354e.PNG)

Just wondering if its this way for a reason / if its is possible to change it to allow static properties to be accessed without an instance being created or if this is a bug.

Tried Messing around a little bit with the code to allow `BindingFlags.Public | BindingFlags.Static` for the `GetProperties` method (see picture below)
![bindingFlags](https://user-images.githubusercontent.com/80762652/178512886-21f2e79a-5c14-440d-b190-38035e7c2e01.PNG)

 It adds the static Properties to the output. But nothing displays in the UI so I assume I am missing something?.

**Comment by sfmskywalker** [comment]
Although you can use the static properties when registering the `Encoding` class, there appears to be a bug with the typescript definitions being generated (used for intellisense) where static properties are declared as instance properties.

Will be fixed for the 2.9 release.

**Comment by sfmskywalker** [comment]
Note that I also added a change that registers `Encoding` by default, so you don't need to do this when using 2.9 (once released or when using the upcoming preview build).
