### ISSUE TITLE
Policies are not working

### ISSUE THREAD

**Issue by bweltin** [elsa-workflows/elsa-core#3200]
I am currently trying to restrict the access via policies to the endpoints published by elsa itself. 
Unfortunately, the endpoints are accessible even though the request violates the setted policy.

Here I have tried using the UI:
![image](https://user-images.githubusercontent.com/59006428/178936360-f7ed6fb7-2f85-4066-95e4-1a44196508d3.png)

The policy is registered this way:
`services.AddAuthorization(auth => auth.AddPolicy("IsAdmin", policy => policy .RequireClaim("is-admin", "true")));`

And this way I tried to create a secured workflow in the application:

```
public class CustomWorkflow : IWorkflow
    {
        public void Build(IWorkflowBuilder builder)
        {
            builder
                .HttpEndpoint(setup => setup
                    .WithPath("/safe-hello")
                    .WithMethod("GET")
                    .WithAuthorize()
                    .WithPolicy("IsAdmin"))
                .WriteHttpResponse(setup => setup.WithStatusCode(HttpStatusCode.OK)
                    .WithContent(context =>
                    {
                        var httpContext = context.GetService<IHttpContextAccessor>().HttpContext!;
                        var user = httpContext.User;
                        return $"Hello {user.Identity!.Name}!";
                    }));
        }

    } 
```

When trying to call the endpoint "/safe-hello" within postman, without any further settings, I get a 200 and the response contains "Hello !" (no name is setted)
![image](https://user-images.githubusercontent.com/59006428/178938202-73549a93-ebb9-439e-a0f4-8bbf1d092f84.png)

My app is configured the following way. The order of the usings should be correct and it should contain everything required.

```
 public void Configure(WebApplication app, IWebHostEnvironment env)
    {
        if (env.IsDevelopment())
        {
            IdentityModelEventSource.ShowPII = true;
            app.UseDeveloperExceptionPage();
        }
        
        app.UseCors(x => x
                .AllowAnyMethod()
                .AllowAnyHeader()
                .SetIsOriginAllowed(origin => true) 
                .AllowCredentials()) 
            .UseHttpLogging()
            .UseRouting()
            .UseAuthentication()
            .UseAuthorization() // including elsa-endpoints (auth-attribute)
            .UseHttpActivities()
            .UseEndpoints(endpoints =>
            {
                endpoints
                    .MapControllers()
                    .RequireAuthorization()
                    ;
            });
    }
```

Maybe you guys are already aware of this problem or someone has already found a workaround for this issue.

**Comment by bweltin** [comment]
The following snippet fixed my issued.  👍 

```
 services
            .AddAuthorization(auth =>
            {
                auth
                    .FallbackPolicy = new AuthorizationPolicyBuilder().RequireAuthenticatedUser().Build();
            });
```

**Comment by sfmskywalker** [comment]
Glad to see you figured it out! 👍🏻

**Comment by bweltin** [comment]
@sfmskywalker The authorization by itself works now. Unfortunately, the policies are not still not working. So the problem could be opened up again.

**Comment by bweltin** [comment]
http.HttpEndpointAuthorizationHandlerFactory =
                            ActivatorUtilities.GetServiceOrCreateInstance<AuthenticationBasedHttpEndpointAuthorizationHandler>;

Was missing
