### ISSUE TITLE
An error occurred when I set the workflow context. The error information is as follows

### ISSUE THREAD

**Issue by JetLe** [elsa-workflows/elsa-core#3207]
[10:14:13 ERR] Serialization and deserialization of 'System.Type' instances are not supported. Path: $.contextOptions.contextType | LineNumber: 0 | BytePositionInLine: 159.
System.NotSupportedException: Serialization and deserialization of 'System.Type' instances are not supported. Path: $.contextOptions.contextType | LineNumber: 0 | BytePositionInLine: 159.
 ---> System.NotSupportedException: Serialization and deserialization of 'System.Type' instances are not supported.

**Comment by sfmskywalker** [comment]
Can you provide some steps to reproduce this issue?

**Comment by JetLe** [comment]
Thank you for your reply！
The problem has been located because I integrated the ABP framework, found serialization exceptions, and I am repairing ABP framework exceptions.
