### ISSUE TITLE
is there any chance to split ExecutionLog to single table?

### ISSUE THREAD

**Issue by jortygu** [elsa-workflows/elsa-core#321]
hi , 
   is there any chance to split ExecutionLog to single table, i have an Scenario that need to gather workflow execution log for statistics.

**Comment by sfmskywalker** [comment]
I wouldn't be opposed to refactor that, although I would suggest to do it as part of Elsa 2. If you need it today, what you can do instead is implement `IWorkflowEventHandler` (or derive from `WorkflowEventHandlerBase` so y don't have to implement every method), and implement the `ActivityExecuted` method, similar to `ActivityLoggingWorkflowEventHandler` - the difference would be that you write log entries to your own table.

**Comment by jortygu** [comment]
thanks,it's work for me!
