### ISSUE TITLE
Console log warnings when changing a property on a custom activity.

### ISSUE THREAD

**Issue by SSCDanexis** [elsa-workflows/elsa-core#3210]
I would like to get rid of the console log warnings that come up after changing a property on a custom activity.

![unknown](https://user-images.githubusercontent.com/92802930/179503320-291d238a-52e6-4cde-9a00-6705a5d0e26c.png)

These always appear when navigating to the "Workflow Instances" section, i first tought it was due to old monitoring entries still present in the db, but even bulk deleting all of them didnt help with the warnings. 

They only thing i can do for now is make a new database and reimport the workflows, which makes me lose all the other monitoring entries of unaffected workflows and is therefore not optimal.

**Comment by mohdali** [comment]
Elsa tries to process all versions of the workflow. So if an older version used this property and it no longer exists in the custom activity you might be getting this warning.

If you want to get rid of that warning then probably you need to Export the workflow an re-import it as Version 1 and delete the old workflow.
