### ISSUE TITLE
Custom HttpRequest

### ISSUE THREAD

**Issue by avataron** [elsa-workflows/elsa-core#3223]
Trying customize HttpRequest.

I've followed directions from:
first: https://github.com/elsa-workflows/elsa-core/issues/1393
then: https://github.com/tomy2105/elsa-core/blob/test/HTTPEndpointExtension/src/samples/dashboard/aspnetcore/ElsaDashboard.Samples.AspNetCore.Monolith/TestReceiveRequest.cs

Following these, I've then implemented my **HttpRequestEx**, but no way it gets reached by an request via postman (it returns NotFound).

After too many tries and errors, I decided to sniff the code, then I found that in HttpEndpointMiddleware.cs, line 81, there is something hardcoded:

```csharp
//my note: hardcoded!
const string activityType = nameof(HttpEndpoint);
```

If I change that to:
```csharp
const string activityType = nameof(HttpEndpointEx);
```

the route now works fine.

So I'm left with two doubts, is it happening because I am still doing something wrong in my code or is it necessary to rewrite the HttpEndpointMiddleware to know my **HttpRequestEx**?

Here is the code for my **HttpRequestEx** just in case:

```csharp

    [Trigger(
    Category = "HTTP",
    DisplayName = "HTTP Endpoint EX",
    Description = "Handle an incoming HTTP request (extended).",
    Outcomes = new[] { OutcomeNames.Done }
    )]
    public class HttpEndpointEx : HttpEndpoint
    {
        private readonly IHttpContextAccessor httpContextAccessor;

        [ActivityInput(
        Hint = "Additional headers to write.",
        UIHint = ActivityInputUIHints.MultiLine,
        DefaultSyntax = SyntaxNames.Json,
        SupportedSyntaxes = new[] { SyntaxNames.JavaScript, SyntaxNames.Liquid, SyntaxNames.Json },
        Category = PropertyCategories.Advanced
        )]
        public HttpResponseHeaders ResponseHeaders { get; set; }



        public HttpEndpointEx(IHttpContextAccessor httpContextAccessor)
        {
            this.httpContextAccessor = httpContextAccessor;
        }

        
        protected override IActivityExecutionResult OnExecute()
        {
            var httpContext = httpContextAccessor.HttpContext ?? new DefaultHttpContext();
            var response = httpContext.Response;

            if (response.HasStarted)
                return Fault("Response has already started");

            var headers = ResponseHeaders;
            if (headers != null)
            {
                foreach (var header in headers)
                    response.Headers[header.Key] = header.Value;
            }

            return base.OnExecute();
        }

        ///// <summary>
        ///// didn't work!
        ///// </summary>
        //public override string Type => nameof(HttpEndpoint);
    }

    /// <summary>
    /// Added this to Startup.cs => services.AddBookmarkProvider<HttpEndpointExBookmarkProvider>();
    /// </summary>
    public class HttpEndpointExBookmarkProvider : BookmarkProvider<HttpEndpointExBookmark, HttpEndpointEx>
    {
        public override bool SupportsActivity(BookmarkProviderContext<HttpEndpointEx> context)
        {
            return context.ActivityType.TypeName == nameof(HttpEndpointEx);
        }

        public override async ValueTask<IEnumerable<BookmarkResult>> GetBookmarksAsync(BookmarkProviderContext<HttpEndpointEx> context, CancellationToken cancellationToken)
        {
            var path = ToLower((await context.ReadActivityPropertyAsync(x => x.Path, cancellationToken))!);
            var methods = (await context.ReadActivityPropertyAsync(x => x.Methods, cancellationToken))?.Select(ToLower) ?? Enumerable.Empty<string>();
            BookmarkResult CreateBookmark(string method) => Result(new(path, method));
            return methods.Select(CreateBookmark);
        }

        private static string ToLower(string s) => s.ToLowerInvariant();
    }

    public record HttpEndpointExBookmark(string Path, string? Method) : IBookmark;

```

*Edit: it seems the problem is related to zero instances saved + HttpEndpointEx as the first activity. 
I've done a late test and when there are instances saved, the middleware is able to retrieve the instances*
:S

**Comment by mohdali** [comment]
In Elsa 1 we ended up writing our own HTTP middleware in order to create a custom HTTP activity. 

However, in Elsa 2, I think the standard activity covers most of the requirements. Can you elaborate the need for customization?

**Comment by tomy2105** [comment]
@mohdali I don't know what was @avataron 's use case. My use case was that I wanted to hide (hardcode, something) some of the properties of the HTTPEndpoint activity to make it simpler for my users (for example, it always accepts only post requests, always reads body, the type of the object it reads from body is fixed, etc.....)

**Comment by avataron** [comment]
> id you register your bookmark provider via a call which

yea, I registered it in startup.cs

**Comment by avataron** [comment]
> @mohdali I don't know what was @avataron 's use case. My use case was that I wanted to hide (hardcode, something) some of the properties of the HTTPEndpoint activity to make it simpler for my users (for example, it always accepts only post requests, always reads body, the type of the object it reads from body is fixed, etc.....)

Plus I want to standardize the request and response headers, because I'm writing adapters in my system, in a way the "end devs" do not need to know how the workflow works. They should just use our conventions, which are coded in a way to send and receive expected values between workflow and our domain entities.

**Comment by cristinamudura** [comment]
@avataron Not sure if this is what you need but.. :

 If you want to customise some things in a specific activity, what you can do basically is to implement a notification handler that listens to INotificationHandler<DescribingActivityType>. Then you can basically verify the type of activity and implement custom logic like hiding properties etc ( that's more on the UI level). 

```csharp
        public Task Handle(DescribingActivityType notification, CancellationToken cancellationToken)
        {
            var activityType = notification.ActivityType;

            if (activityType.Type == typeof(HttpEndpoint))
            {
                var inputProps = notification.ActivityDescriptor.InputProperties;
               // here you can hide properties or add new ones etc
            }
            return Task.CompletedTask;
        }
```

If you want to implement custom logic for specific defined properties ( like settings always some headers ) you can implement the notification handler of activityexecuting (INotificationHandler<ActivityExecuting>)

```csharp
        public Task Handle(ActivityExecuting notification, CancellationToken cancellationToken)
        {
            var activityType = notification.Activity;

            if (activityType is HttpEndpoint)
            {
                var httpEndpoint = activityType as HttpEndpoint;

                httpEndpoint.Output.Headers.Add("My-Header", "value");
            }

            return Task.CompletedTask;
        }
```

**Comment by avataron** [comment]
> ```cs
>  var activityType = notification.Activity;
> 
>             if (activityType is HttpEndpoint)
>             {
>                 var httpEndpoint = activityType as HttpEndpoint;
> 
>                 httpEndpoint.Output.Headers.Add("My-Header", "value");
>             }
> 
>             return Task.CompletedTask;
> ```

@cristinamudura that's exactly what I was looking for! Thanks.

For those who are looking for the complete code, here what I came after @cristinamudura tip:

```csharp
public class StandardPropsHandler : INotificationHandler<ActivityExecuting>
{
    private readonly IHttpContextAccessor httpContextAccessor;

    public StandardPropsHandler(IHttpContextAccessor httpContextAccessor)
    {
        this.httpContextAccessor = httpContextAccessor;
    }

    public Task Handle(ActivityExecuting notification, CancellationToken cancellationToken)
    {
        var activityType = notification.Activity;

        if (activityType is HttpEndpoint)
        {
            var httpContext = httpContextAccessor.HttpContext ?? new DefaultHttpContext();
            //var request = httpContext.Request;
            var response = httpContext.Response;
            response.Headers["My-Header"] = "value";
        }

        return Task.CompletedTask;
    }
}
```

Then register it in Startup.cs:

```csharp
services.AddNotificationHandlers(typeof(StandardPropsHandler));
```

**Comment by mohdali** [comment]
> @avataron Not sure if this is what you need but.. :
> 
>  If you want to customise some things in a specific activity, what you can do basically is to implement a notification handler that listens to INotificationHandler<DescribingActivityType>. Then you can basically verify the type of activity and implement custom logic like hiding properties etc ( that's more on the UI level). 
> 
> ```csharp
>         public Task Handle(DescribingActivityType notification, CancellationToken cancellationToken)
>         {
>             var activityType = notification.ActivityType;
> 
>             if (activityType.Type == typeof(HttpEndpoint))
>             {
>                 var inputProps = notification.ActivityDescriptor.InputProperties;
>                // here you can hide properties or add new ones etc
>             }
>             return Task.CompletedTask;
>         }
> ```
> 
> If you want to implement custom logic for specific defined properties ( like settings always some headers ) you can implement the notification handler of activityexecuting (INotificationHandler<ActivityExecuting>)
> 
> ```csharp
>         public Task Handle(ActivityExecuting notification, CancellationToken cancellationToken)
>         {
>             var activityType = notification.Activity;
> 
>             if (activityType is HttpEndpoint)
>             {
>                 var httpEndpoint = activityType as HttpEndpoint;
> 
>                 httpEndpoint.Output.Headers.Add("My-Header", "value");
>             }
> 
>             return Task.CompletedTask;
>         }
> ```

Thanks @cristinamudura for providing the detailed examples. I think this is avery useful approach and negates the need to build own custom HttpEndpoint.

@tomy2105 I hope this can work for you as well.

**Comment by tomy2105** [comment]
Thanks @mohdali and @cristinamudura.
This definitely shows me another way of doing things but this approach does this for all HttpEndpoint activities.
My usec ase was to have a new actvity similar to HttpEndpoint (with some properties added, some removed) which would exist in addition to default HttpEndpoint activity.
I don't think it can be done with usage of INotificationHandlers only, but please correct me if I'm wrong....

**Comment by mohdali** [comment]
> Thanks @mohdali and @cristinamudura. This definitely shows me another way of doing things but this approach does this for all HttpEndpoint activities. My usec ase was to have a new actvity similar to HttpEndpoint (with some properties added, some removed) which would exist in addition to default HttpEndpoint activity. I don't think it can be done with usage of INotificationHandlers only, but please correct me if I'm wrong....

Would ActivityTypeProvider then fit for your use case? Webhooks for example are simply HttpEndpoints that are customized in certain ways and you can have as many of them as you want. It is all managed by the type provider.

Take a look here:

https://github.com/elsa-workflows/elsa-core/blob/master/src/activities/webhooks/Elsa.Activities.Webhooks/ActivityTypes/WebhookActivityTypeProvider.cs

**Comment by tomy2105** [comment]
Maybe it would but using `ActivityTypeProvider` is by few orders of magnitude more complex than adding new activity (been there, done that for other purposes, would definitely avoid if I can :)).
That is why I liked a lot when I was just able to make new activity based on existing HTTP Endpoint....

**Comment by mohdali** [comment]
> Maybe it would but using `ActivityTypeProvider` is by few orders of magnitude more complex than adding new activity (been there, done that for other purposes, would definitely avoid if I can :)).
> That is why I liked a lot when I was just able to make new activity based on existing HTTP Endpoint....

Yeah could understand ActivityTypeProvider is not straightforward. If you make your own custom activity do you need to modify the middleware as well or it can pick it up via inheritance?

**Comment by tomy2105** [comment]
@mohdali No middleware changes are needed, just inheriting your activity from `HTTPEndpoint` is enough (along with implementing your `BookmarkProvider`.

**Comment by tomy2105** [comment]
@avataron I've just rebased my example at https://github.com/tomy2105/elsa-core/blob/test/HTTPEndpointExtension/src/samples/dashboard/aspnetcore/ElsaDashboard.Samples.AspNetCore.Monolith/TestReceiveRequest.cs to latest Elsa version and it works as far as I can tell.
I needed to change `var path = ToLower(await context.ReadActivityPropertyAsync<HttpEndpoint, PathString>(x => x.Path, cancellationToken))!;` to `var path = ToLower((await context.ReadActivityPropertyAsync(x => x.Path, cancellationToken))!);` but you've already done this so that was not your problem.

The only other difference I can spot in your code are following:

1.  My `BookmarkProvider` doesn't implement `SupportsActivity`, it leaves the default implementation
2. I create bookmark little differently `BookmarkResult CreateBookmark(string method) => Result(new(path, method), nameof(HttpEndpoint));`, I have second parameter to `Result` of value `nameof(HttpEndpoint)` and you don't have second parameter at all.

If you like you could investigate these two differences and let us know if that helped.
