### ISSUE TITLE
Is ELSA 2.2.0 compatible with Windows Server 2012 & IIS 8.5

### ISSUE THREAD

**Issue by chandsalam1108** [elsa-workflows/elsa-core#3227]
We're trying to deploy ELSA 2.2.0 solution on Windows Server 2012 & IIS 8.5 but getting web.config related errors will running the application. 

Please confirm if ELSA 2.2.0 is compatible with Windows Server 2012 & IIS 8.5 and help me with solution to resolve this issue.

Thanks,

Chand

**Comment by mohdali** [comment]
If you mean Windows Server 2012 R2 then I think it is supported. However, I have not tested myself. You might wnd up using .NET Core 3.1 though.

Pleas refer below link https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/iis/?view=aspnetcore-6.0

**Comment by chandsalam1108** [comment]
Hi @mohdali ,

Thanks for the swift response. Yes, it's Windows Server 2012 R2, IIS 8.5 & .Net 6 with elsa 2.8.0. Please confirm if that compatible or I need to install something else.

Thank you!

**Comment by leeveney** [comment]
I depoly ELSA on a server under the same environment with no problem.

**Comment by chandsalam1108** [comment]
> I depoly ELSA on a server under the same environment with no problem.

Can you please help me with IIS 8.5 settings. I'm getting error at web.config while browsing application.

Thanks you!

**Comment by sfmskywalker** [comment]
Are you able to get a basic ASP.NET Core project running? There's nothing special about Elsa that would require anything different compared to a basic ASP.NET application. So if you get that running, you will also be able to get Elsa running.
