### ISSUE TITLE
Example of IActivityTypeProvider based on a single type

### ISSUE THREAD

**Issue by alkampfergit** [elsa-workflows/elsa-core#3228]
Hi,

I've a situation where I have a swagger.json file and I want to create an activity for each API call inside swagger file. I created a based activity that accept paramters and is able to do the call.

I've created a class that implements IActivityTypeProvider and if I return only one class everything seems to work fine, but when I return a second ActivityDefinition based on the same underling class, I got error because elsa is trying to register multiple time the same activity.

I've tried to make the class generic to have a single runtime type for each activity but then I have error like following one and the workflow does not works.

Is there an example that shows how to use a base class to dynamically generates multiple activity definition at runtime? Is this even a supported scenario?

Thanks for any information you can give me.

```
at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
2022-07-27 13:12:22 [ERR] Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware | An unhandled exception has occurred while executing the request.
Elsa.Exceptions.WorkflowException: The activity type 'Activity' has not been registered. Did you forget to register it with ElsaOptions?
   at Elsa.Services.Workflows.ActivityTypeService.GetActivityTypeAsync(String type, CancellationToken cancellationToken)
   at Elsa.Scripting.JavaScript.Handlers.RenderJavaScriptTypeDefinitions.<>c__DisplayClass3_0.<<Handle>b__5>d.MoveNext()
--- End of stack trace from previous location ---
   at Elsa.Scripting.JavaScript.Handlers.RenderJavaScriptTypeDefinitions.Handle(RenderingTypeScriptDefinitions notification, CancellationToken cancellationToken)
   at MediatR.Mediator.PublishCore(IEnumerable`1 allHandlers, INotification notification, CancellationToken cancellationToken)
   at Elsa.Scripting.JavaScript.Providers.DotNetTypeScriptDefinitionProvider.GenerateTypeScriptDefinitionsAsync(StringBuilder builder, ICollection`1 declaredTypes, WorkflowDefinition workflowDefinition, IntellisenseContext context, CancellationToken cancellationToken)
   at Elsa.Scripting.JavaScript.Services.TypeScriptDefinitionService.GenerateTypeScriptDefinitionsAsync(WorkflowDefinition workflowDefinition, IntellisenseContext context, CancellationToken cancellationToken)
   at Elsa.Server.Api.Endpoints.Scripting.JavaScript.TypeDefinitions.Get.Handle(String workflowDefinitionId, IntellisenseContext context, Nullable`1 version, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
```

**Comment by mohdali** [comment]
hi @alkampfergit, the way ActivityTypeProvider works is that it can generate multiple activity definitions based on an existing Activity that is already registered in Elsa. You can customize each activity definition to fit your needs by setting certain values of the activity and you can even hide the base activity and use only the activities generated from the type provider.

For example, if you are trying to implement OpenAPI Clients, your base activity might be SendHTTPRequest and you will customize the request parameters and payload based on the swagger definitions.

I'm actually interested to implement a similar functionally and curious to know how you are processing the swagger files. Do you mind sharing more about your approach? I may be able to help you build the ActivityTypeProvider accordingly.

We have an open issue to implement this as a standard feature and would appreciate your feedback. https://github.com/elsa-workflows/elsa-core/issues/2961

**Comment by alkampfergit** [comment]
Actually my problem was, if I returned only a single activity, everything goes ok, but when I try to return more than one activity based on the same class, I got an internal KeyAlreadyAddedException in a dictionary. It seems that if I register more than one activity with the same TypeName it does not like it.

So I've tried to change the TypeName, but then I had all sort of errors (shown above) and everything stop working, I'm sure that I'm missing something :) but actually I'm trying with a Visual STudio Code generator, that seems to me a more safe approach.

Code is full of Customer Stuff so I cannot share, if I had problem and cannot work with code generator I'll try to create a sample project to reproduce the problem.

Gian Maria.

**Comment by mohdali** [comment]
> Actually my problem was, if I returned only a single activity, everything goes ok, but when I try to return more than one activity based on the same class, I got an internal KeyAlreadyAddedException in a dictionary. It seems that if I register more than one activity with the same TypeName it does not like it.
> 
> So I've tried to change the TypeName, but then I had all sort of errors (shown above) and everything stop working, I'm sure that I'm missing something :) but actually I'm trying with a Visual STudio Code generator, that seems to me a more safe approach.
> 
> Code is full of Customer Stuff so I cannot share, if I had problem and cannot work with code generator I'll try to create a sample project to reproduce the problem.
> 
> Gian Maria.

Thank you for the reply. ActivityTypeProvider can provide multiple activity definitions from the same Activity Type. It is not required to register the activity again. Probably you are trying to add an activity that already exists and therefore getting the error.

Take a look at this example for webhooks. You can have multiple activity definitions from the same activity type.  https://github.com/elsa-workflows/elsa-core/blob/master/src/activities/webhooks/Elsa.Activities.Webhooks/ActivityTypes/WebhookActivityTypeProvider.cs

**Comment by alkampfergit** [comment]
Ok I'll take a look :) thanks.

**Comment by alkampfergit** [comment]
Found My error, in activity activation I used this piece of code I've found on some issue 

```
var activity = (DynamicSendJarvisHttpRequest)ActivatorUtilities.GetServiceOrCreateInstance(context.ServiceProvider, responseType);
```

And this generates all sort of problem, I've changed as for your example to 

```
 var activity = await _activityActivator.ActivateActivityAsync<BaseDynamicSendJarvisHttpRequest>(context);
```

And everything works as a charm.

I'm still evaluating if code generation is a better approach (lots of flexibility) but now I have two distinct strategies to generate actions.

My approach is SUPER SIMPLE, I simply take swagger json definition, parse, then generates the activities. I need this approach because we have some specific API behaviour like bearer tokens, special return types, etc. With this approach I have full intellisense :)

![image](https://user-images.githubusercontent.com/358545/181278600-70d571be-c972-48e0-a11e-fbde3f51f2c6.png)

If you are insterested, feel free to contact me on my private mail alkampfer@nablasoft.com and I'll check what details I can share with you.

**Comment by mohdali** [comment]
This is interesting indeed. Maybe I'm complicating things but I would assume there should be a way for code generation at runtime. But I'm really unable to find a good example how to achieve it.

Back during .NET Framework we used the Add-In model to load service clients that are generated on the fly. It was not straight forward but did the trick.

Parsing the schema should also do the trick I guess and could be the way to go indeed.

Glad to hear it works for you now and happy to help anytime you need any further clarification.

**Comment by alkampfergit** [comment]
You have several options, I'm talking about code generation at compile time, it is really simple and you can simply work with text template where you can simply replace strings and inject in compilation pipeline.

There are various way to obtain this, one is to let NSwag generate a C# client for you, then copy C# code inside your project and let code generator inspect that code and then generate classes.

Or you can simply include json file and let generator work with JSON file. 

Actually I'm using an activity provider, because I've found problem on my code, code generation can give you more flexibility but is indeed an extra layer of complexity :) but I can now choose the technique that suites me most.

Thanks for the help.
