### ISSUE TITLE
Elsa 2#RunWorkflowDefinitionAsync getting object reference null 

### ISSUE THREAD

**Issue by anktsrkr** [elsa-workflows/elsa-core#325]
Hi, 
I was trying to implement **Sample03** of ELSA 1.0 using ELSA 2.0, found that if the workflow definition is not published i.e `IsPublished = true` it is getting object reference null error because it always search for **Published** workflow - 

` var workflow = await workflowRegistry.GetWorkflowAsync(workflowDefinitionId, VersionOptions.Published, cancellationToken);`

I guess instead of  object reference null error  we should put some guard and show valid error message, something like - 
"_**The triggered workflow definition either not registered or not published**_" 

We can also initialize **IsPublished**  to `true` from constructor of **WorkflowDefinitionVersion** but dont think that will be good idea.

**Comment by sfmskywalker** [comment]
Hi Ankit,

Where exactly would you show the error message?

Indeed, I don't think it is a good idea to initialize `IsPublished` to `true` - publishing workflows needs to be a conscious action on the user/developer part.

**Comment by anktsrkr** [comment]
PR #328 merged successfully,
