### ISSUE TITLE
Workflow Instance Status is not getting updated

### ISSUE THREAD

**Issue by santysan143** [elsa-workflows/elsa-core#3267]
Hi,

I created a workflow and also created some custom activities. while running workflow if any activity get any exception then activities get faulted not workflow instance. I need that workflow instance also get faulted. while looking at journal of workflow instance, it is showing activities is running two times once it get failed status and another get executed, design is showing that activity is faulted but not updating workflow instance status.

  
![image](https://user-images.githubusercontent.com/9149159/186337329-8f223776-7bec-42ed-8a6a-223d8291c1d0.png)
![image](https://user-images.githubusercontent.com/9149159/186337538-bacf2350-948b-45c9-8944-066570937802.png)

**Comment by sfmskywalker** [comment]
What version is this?

**Comment by santysan143** [comment]
![image](https://user-images.githubusercontent.com/9149159/186345266-a36f965b-3e76-4c58-9ef7-191f5cd770bb.png)

**Comment by johnwc** [comment]
In your custom activity, are you catching the exception and returning via ` return Fault(<exception>);` ?
