### ISSUE TITLE
How to get query parameters when triggering signals

### ISSUE THREAD

**Issue by iran1024** [elsa-workflows/elsa-core#3282]
Like this, https://*.*:50001/signals/trigger/CfDJ8FVtxAUY3uBEuwyOxYYBIlMxbNFPm4eAc9Nx-BWCQzIs81CjaRvXhd43Jgg0NJYlD96NZoiMGFzpGZuHSyIIszomMMLoU8I0S4ZH4tWbUOLoMlrcIeIggw0qFqbViW98AbFywDB2jmAoJVqVmpoqqFUyOVsF4rXVYyxYo8AGScZvPwx4kJFXBqPD_Zt8pRPbtUfXzZEUjynskIXs-Idwwno?**id=1&type=2**

I want get some params from signal url, or any other method that can pass parameters, Is there any way?

**Comment by iran1024** [comment]
Just in this case. I want to know who visited the signal URL（with params, like username...）
![image](https://user-images.githubusercontent.com/49387318/188068257-93b3656d-1bea-41ab-8c79-683ec69eef4e.png)

**Comment by JetLe** [comment]
you can post url with input object,then it can received,as follows:
{
    "workflowInstanceId": "3ebfab99e4e34c09a1bdbf89d52aeb7e",
    "input":{"creator":"jojo","remark":"test"}
}

**Comment by JetLe** [comment]
> Just in this case. I want to know who visited the signal URL（with params, like username...） ![image](https://user-images.githubusercontent.com/49387318/188068257-93b3656d-1bea-41ab-8c79-683ec69eef4e.png)

you can post url with input object,then it can received,as follows:
{
"workflowInstanceId": "3ebfab99e4e34c09a1bdbf89d52aeb7e",
"input":{"creator":"jojo","remark":"test"}
}
