### ISSUE TITLE
Implementing a fault workflow if a workflow registers a fault

### ISSUE THREAD

**Issue by mptolly-takeda** [elsa-workflows/elsa-core#329]
Is there any way to create a set of steps to send out an email if a workflow encounters a fault so that support could investigate what happened and remedy the situation? 

I would be primarily using this capability with the code-based workflows as it seems challenging to monitor the all the workflow instances for faults that occur.

**Comment by sfmskywalker** [comment]
Hi @mptolly-takeda , there are currently no fault handling options within workflows themselves, however, what we could do is publish an event when a fault occurs. Your application could then handle this event and send an email.

**Comment by craigfowler** [comment]
Dupe of #200 .
