### ISSUE TITLE
Workflow registry Slow 

### ISSUE THREAD

**Issue by Juandavi1** [elsa-workflows/elsa-core#3292]
Hi ! 

Do you know why the workflow registry endpoint is taken a lot of time ?  avg 20 seconds  :( 

<img width="1495" alt="image" src="https://user-images.githubusercontent.com/18731612/188958647-04708328-7bfd-406c-825b-387422eb2144.png">

Causes the workflow instances page load very slow :( 

we are using 2.9.0-preview.394 version 

we just have 10 workflows and a few instances. We are working with MongoDb.  

thanks! 

Awesome project !!

**Comment by Juandavi1** [comment]
I added a stopwatch in the workflow registry controller to take execution time 

<img width="1343" alt="image" src="https://user-images.githubusercontent.com/18731612/189047711-0acd7b98-3379-4b98-a6fe-8b7a83b7c021.png">

these were the times 

<img width="430" alt="image" src="https://user-images.githubusercontent.com/18731612/189047777-4493d11c-884f-4644-a490-070627e1280d.png">

<img width="408" alt="image" src="https://user-images.githubusercontent.com/18731612/189047810-b1f5ad72-9434-45cd-b3cf-2b3051186ca1.png">

also we added `AsParallel`

<img width="1131" alt="image" src="https://user-images.githubusercontent.com/18731612/189047997-696b73ad-73fd-4df4-855b-2dd084391aa7.png">

but the performance doesn't seem to improve     

the performance database metrics are ok. The queries are taken a few milliseconds.

thank you

**Comment by sfmskywalker** [comment]
I haven’t seen that before, but 20 seconds on average is not normal for just 10 workflows. Doing the timer thing is a good start. Perhaps you can clone the elsa-core repo, reference the projects directly, and start adding timer measurements further down until you isolate the code that takes this much time?

**Comment by Juandavi1** [comment]
Hi ! Yes, the first comment has the time taken inside library

**Comment by diegocantero** [comment]
I have this same error, at first it was fast, maybe it needs some additional configuration?

**Comment by Juandavi1** [comment]
Hi ! We are working with 2.9.2 version and it still happens :(

**Comment by sfmskywalker** [comment]
Have you been able to identify what bit causes the slow performance?

**Comment by Juandavi1** [comment]
Hello! not yet :(
