### ISSUE TITLE
Bug in BookmarkFinder

### ISSUE THREAD

**Issue by Alexplose** [elsa-workflows/elsa-core#3293]
Bookmarks are created in database with activity type like `SignalReceived`

But the method Findbookmark uses` GetSimpleAssemblyQualifiedName()`, that return something like : `Elsa.Activities.Signaling.SignalReceived, Elsa.Core.`

So FindBookmark return empty results, because `SignalReceived `doesn't match `Elsa.Activities.Signaling.SignalReceived, Elsa.Core`

https://github.com/elsa-workflows/elsa-core/blob/87c44e183c4d488b8df0ee105651f15f0b270a74/src/core/Elsa.Abstractions/Extensions/BookmarkFinderExtensions.cs#L21

**Comment by Alexplose** [comment]
Could you please revert to the previous version ?

**Comment by sfmskywalker** [comment]
Revert what exactly from which version to what previous version? Are you referring to a commit or entire package versions?

**Comment by Alexplose** [comment]
I had to rollback to v2.4.2, when FindBookmarks was using typeof(T).Name

https://github.com/elsa-workflows/elsa-core/blob/b893006c968484ed8a4540d80fa8b0331142b991/src/core/Elsa.Abstractions/Extensions/BookmarkFinderExtensions.cs#L17


I saw that  typeof(T).Name has been changed to typeof(T).GetSimpleAssemblyQualifiedName() elsewhere, but I don't know the perimeter of this issue.

**Comment by sfmskywalker** [comment]
Got it. Although we can't just undo this change as it would then break users using the new bookmark names, what we might do is look for both names.

This would be a bit of work, but unless deleting database records is an option, we should do it.

**Comment by Alexplose** [comment]
I'm stuck using the version 2.4.2.
Also it's already broken, the bookmarks are created with the simple type(T).Name, but FindBookmark uses GetSimpleAssemblyQualifiedName(), so all created bookmarks since the breaking version, can't be found with the bookmarkfinder.
