### ISSUE TITLE
Issue with rpa and web activities.

### ISSUE THREAD

**Issue by TeoMatosevic** [elsa-workflows/elsa-core#3300]
Hello,

I am new to Elsa and been trying to make a workflow with rpa and web activities.
The problem I encountered is that I do not understand what needs to go in the "Driver Id" field that all of these activities have except "Open Browser". 
As of my understanding (by looking at the source code) "Open Browser" activity generated a Driver Id that is a guid. That same guid should than be put in the "Driver Id" field of the activities that work with that same browser instance. The problem is that I do not understand how to access that variable and how to put it in the "Driver Id" field. The way I see it now the "Driver Id" field only accepts strings as input and not JS or Liquid so I do not understand how to get it to work.
Maybe I got it all wrong but it would be helpful if someone could point me in the right direction.
![Elsa_Issue](https://user-images.githubusercontent.com/93163183/190595638-c207486e-273e-4a69-bfb1-6d1c17e0d782.png)

Thank you all,
I already contacted @sfmskywalker and he told me to create an issue and tag the author.
I looked at commit history and thought the right person to tag would be @lucapisano .

**Comment by lucapisano** [comment]
Hi @TeoMatosevic you're right. I'd need to add the following attributes to the activities classes in order for the designer to allow JS/Liquid expressions.

I'll make the change later today and provide a JSON export of a sample workflow definition that you can import.

**Comment by lucapisano** [comment]
[rpa-activity-demo-definition.zip](https://github.com/elsa-workflows/elsa-core/files/9591707/rpa-activity-demo-definition.zip)
Attached demo Workflow Definition

**Comment by TeoMatosevic** [comment]
Hi, thank you so much for your quick response, when I tried your sample workflow the program threw an exception and it said "DriverId is not a function" so I removed "()" next to DriverId in "Navigate To Url" and "Close Browser" activities and then it worked.

Thank you again.
