### ISSUE TITLE
Elsa Startup Very Slow

### ISSUE THREAD

**Issue by hendxxx** [elsa-workflows/elsa-core#3310]
Iam stuck in ELSA Startup

![image](https://user-images.githubusercontent.com/6839640/192230790-48fef81d-c068-412a-8698-54b3af5c1eb0.png)

After investigation if not include Data, the query run normal
![image](https://user-images.githubusercontent.com/6839640/192230999-c64dad67-c3cc-4239-b1d6-2b0f4e6ad8d5.png)

There is any way to exclude Data for Initial startup ???

**Comment by mohdali** [comment]
Do you have many suspended instances that are trying to resume during startup?  That could be a reason.

**Comment by hendxxx** [comment]
no but, i have big json in Data field. Because i have to include base64 in there for infomation to bypass with ELSA
![image](https://user-images.githubusercontent.com/6839640/192269993-537e4720-9f53-41af-844d-75c5b4f5c195.png)

**Comment by hendxxx** [comment]
in total i have 416014066 byte ~ 400MB 
![image](https://user-images.githubusercontent.com/6839640/192270224-63b66f3a-d8fc-41df-8918-86a78146a3b1.png)

**Comment by hendxxx** [comment]
I think, its not necessary to include Data while in the datatable, it important while get data, i'am right? since exclude Data at the service will run normal.

**Comment by jdevillard** [comment]
I don't have check the necessary of data at startup, but I've propose some improvements #3286 for the retention module that consist in not retrieving data.

Some of the new methods made available could be then use at startup.

**Comment by hendxxx** [comment]
Agree @jdevillard, I have my own database to store the workflow, the same way implemented to improve performance. Exclude DataAproval ([w].[Data] in context of ELSA) from querying to datatable, and its work and fast!

This is important because ELSA support long processing workflow, imagine we have running / suspend 200 approval with attachment each 5 Mb that store in json Data, its same with download 1Gb while startup, it's huge!

**Comment by hendxxx** [comment]
Any updates ??

**Comment by sfmskywalker** [comment]
A fix for the retention module is in the works, I believe there are some final issues that may or may not have been resolved by one or more open PRs. I.e. we're close to a fix it seems.
