### ISSUE TITLE
Return Http Response immediately

### ISSUE THREAD

**Issue by Kvariani** [elsa-workflows/elsa-core#3312]
Hello

I'm trying to build workflow, with HttpEndpoint activity, which will execute long running nested workflow, but i need to return response immediately (in response i need to return ProcessID like some GUID)

I was tried several solution but without success. Can anyone give me some suggestions to solve this issue?

Sample Code:
```    
public class TestWorkflow : IWorkflow
    {
        public void Build(IWorkflowBuilder builder)
        {
            builder.HttpEndpoint(activity => activity
                            .WithPath("/test")
                            .WithMethod(HttpMethod.Post.Method)
                            .WithReadContent())
                   .WriteHttpResponse(x => HttpStatusCode.OK, x => "Some Unique ID", x => "application/json")
                   .RunWorkflow<TestWorkflow2>(RunWorkflow.RunWorkflowMode.FireAndForget);
        }
    }

    public class TestWorkflow2 : IWorkflow
    {
        public void Build(IWorkflowBuilder builder)
        {
            builder.Then<TestActivity>();
        }
    }

    public class TestActivity : Activity
    {
        protected override IActivityExecutionResult OnExecute()
        {
            Thread.Sleep(100000);
            return base.OnExecute();
        }
    }

**Comment by jdevillard** [comment]
Hello, 

I see two issue with in your case : 

1. The WriteResponse is not flush before the end of the middleware execution. The middleware will end (and flush) if the Worklow is `Finished` or `Supsend`
2. The RunWorkflow doesn't really seems to be fire and forget (if so, the Parent Workflow will end quickly and the 1st point will be respected (ie -> Finished -> Flush -> Answer)

a quick workaround could be to add a Timer .
```
                     .WriteHttpResponse(x => HttpStatusCode.OK, x => "Some Unique ID", x => "application/json")
                     .Timer(Duration.FromSeconds(0))
                     .RunWorkflow<TestWorkflow2>(RunWorkflow.RunWorkflowMode.FireAndForget);
```

to force the workflow to suspend and flush the response.

**Comment by tomy2105** [comment]
The problem with Timer workaround is that delay will never be actually 0 but might be "considerable" where definition of "considerable" depends on your use case.

Just to mention here that this issue has been discussed before (and possible workaround and implementation changes discussed) in #1144 and is still open.....
