### ISSUE TITLE
Prevent Instance with cron from finishing

### ISSUE THREAD

**Issue by martin-indexeb** [elsa-workflows/elsa-core#3321]
I'm trying to create a 'Daily Check' workflow in the designer and have it starting with a cron to fire at midnight every day. The workflow itself runs fine, but after the last activity reports 'Done()' it marks the instance as 'Finished' and the cron doesn't fire again.

Can anyone guide me on how to prevent the workflow from finishing so that the cron fires again and repeats the workflow?

Here's a screengrab of the workflow as I currently have it:

![CronWorkflow](https://user-images.githubusercontent.com/54405869/194051185-c17c5812-dafb-4d0a-9ffc-b144bd416f2b.png)

For info, I am running Elsa v2.8.2 and for testing I have a cron of '* * * * *'

**Comment by sfmskywalker** [comment]
Glad to see you figured it out. Thanks for letting us know!
