### ISSUE TITLE
TenantId not passed correctly for DatabaseWorkflowProvider and Workflows.RunWorkflow

### ISSUE THREAD

**Issue by JoschaMetze** [elsa-workflows/elsa-core#3340]
Hi,

two minor issues which are blocking multi-tenancy for us (the rest seems to work great already for multi-tenancy), I can provide a PR for both if helpful, as these are really easy fixes:

1. DatabaseWorkflowProvider:
The FindBy* methods (e.g. FindByNameAsync) already take a tenantId but don't pass them on to the specification (e.g. WorkflowDefinitionNameSpecification) that already take a tenantId as optional parameter as well.
` public override async ValueTask<IWorkflowBlueprint?> FindByNameAsync(string name, VersionOptions versionOptions, string? tenantId = default, CancellationToken cancellationToken = default)
        {
            var workflowDefinition = await _workflowDefinitionStore.FindAsync(new WorkflowDefinitionNameSpecification(name, versionOptions), cancellationToken);
            return workflowDefinition == null ? null : await TryMaterializeBlueprintAsync(workflowDefinition, cancellationToken);
        }`
should become:
` public override async ValueTask<IWorkflowBlueprint?> FindByNameAsync(string name, VersionOptions versionOptions, string? tenantId = default, CancellationToken cancellationToken = default)
        {
            var workflowDefinition = await _workflowDefinitionStore.FindAsync(new WorkflowDefinitionNameSpecification(name, versionOptions, tenantId), cancellationToken);
            return workflowDefinition == null ? null : await TryMaterializeBlueprintAsync(workflowDefinition, cancellationToken);
        }`

2. Workflows.RunWorkflow (the activity)
While starting the workflow with StartWorkflowAsync the TenantId is passed to the activityId instead of the name parameter tenantId (I suppose the interface changed here over time).
`var result = await _startsWorkflow.StartWorkflowAsync(workflowBlueprint!, TenantId, new WorkflowInput(Input), CorrelationId, ContextId, cancellationToken: cancellationToken);`
should become:
`var result = await _startsWorkflow.StartWorkflowAsync(workflowBlueprint!,tenantId: TenantId,input: new WorkflowInput(Input),correlationId:CorrelationId, contextId: ContextId, cancellationToken: cancellationToken);`

Keep up the great working, ELSA powered already million of workflow instances for us, good job.

Cheers
Joscha

**Comment by JoschaMetze** [comment]
Have provided the PR (https://github.com/elsa-workflows/elsa-core/pull/3342)

**Comment by sfmskywalker** [comment]
Closing this because the PR has been merged. Thanks for the contribution @JoschaMetze !
