### ISSUE TITLE
Options Attribute for Multiple-choice Property

### ISSUE THREAD

**Issue by ebekker** [elsa-workflows/elsa-core#335]
Is there currently a way to indicate that an Activity property supports multiple simultaneous values from a list of fixed options?  For example, the `Elsa.Attributes.SelectOptionsAttribute` attribute allows you to specify multiple _exclusive_ options on a string property, but what I'm looking for is the ability to specify multiple choices on a single property.  This is analogous to the `[Flags]` attribute for enums.

I was wondering if this capability already exists today, such as if I decorate a property whose type is `string[]` or `IEnumerable<string>` as opposed to just `string`?

**Comment by sfmskywalker** [comment]
Hi @ebekker , I don't believe this to be the case, but it would be a good feature to support.

**Comment by ebekker** [comment]
I'll explore the current use of `SelectOptionsAttribute` in the code base and see if I can contribute a PR to implement this behavior.

**Comment by craigfowler** [comment]
@sfmskywalker - am I right in thinking that this is now pretty much implemented in v2?  Composite outcomes allow multiple results from the same activity.  Perhaps we can close this with a positive message rather than just letting stale-bot kill it :smile:

**Comment by sfmskywalker** [comment]
Indeed it is! 😃 As of today, we have multiple option support in the form of check box list.

**Comment by ebekker** [comment]
Awesome!
