### ISSUE TITLE
ParallelForEach.Items not work when using variables

### ISSUE THREAD

**Issue by jack2gs** [elsa-workflows/elsa-core#3350]
hey,

 I'm using it like this `ActivityDefinitionProperty.Liquid(nameof(ParallelForEach.Items),"{{ Variables.DataInput }}")`
and the variable is set in this way: ` workflowBlueprint.Variables.Set("DataInput", new List<int> {1,2,3} as ICollection<int>);`.

But Items of ParallelForEach never get set. Is the usage incorrect?

Thanks,
Jack

**Comment by sfmskywalker** [comment]
Indeed, when using Liquid, the evaluated result will be a string value, and not an array of items. Since this is always the case with Liquid, I think we should remove this option for ParallelForEach (and possibly also from For, ForEach and While) and only support the JavaScript syntax.

**Comment by jack2gs** [comment]
@sfmskywalker , thank you very much! JavaScript syntax saved my life! Have a good weekend!
