### ISSUE TITLE
Inconsistent JSON serialisation - Dashboard vs Builder

### ISSUE THREAD

**Issue by johndab** [elsa-workflows/elsa-core#337]
Hi

I use IWorkflow implementation to create workflow definition.

Activity definitions are created and persisted in this way (with EntityFrameworkCore):
```c#
    var builder = scope.ServiceProvider.GetService<IWorkflowBuilder>();
    builder.WithId(Guid.NewGuid().ToString());
    workflow.Build(builder);
    return builder.Build();
```

```c#
    var definitionStore = scope.ServiceProvider.GetRequiredService<IWorkflowDefinitionStore>();
    await definitionStore.AddAsync(definition);
```

Unfortunately `State` of the activity is serialized using PascalCase

```c#
{
    "QuestId": {
        "Syntax": "Liquid",
        "Expression": "{{ Activities.QuestCreated.QuestId }}",
        "Type": "System.String, System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e"
    },
    "QuestState": "Closed",
    "SettlementInfo": null,
    "Name": null
}
```

Which is not deserialized correctly by the dashboard (empty fields)
(`Elsa.Extensions.StateExtensions` uses internal private `Serializer`, so I'm not able to change any configuration there.)

For now I use custom `GetState` and `SetState` methods changing the name of the property.

**Comment by sfmskywalker** [comment]
Fixed with Elsa 2.
