### ISSUE TITLE
Elsa 2.9.1 still reports v2.8 in the dashboard web page.

### ISSUE THREAD

**Issue by Bergam64** [elsa-workflows/elsa-core#3370]
Hello Elsa Team!

This morning, I've upgraded Elsa from 2.8.2 to the latest version (2.9.1), but there's a little oversight in that version (and likely also in 2.9.0):
- The version reported in the dashboard home page is still `2.8` instead of `2.9`.

Suggestion: finding a way to dynamically retrieve this version from the main Elsa assembly running the Elsa server would be much more efficient and would require no manual maintenance in the home page each time a new Elsa version is released. You could then even consider displaying the full version (e.g. `2.9.1`).

**Comment by sfmskywalker** [comment]
That's a great idea 👍🏻

**Comment by Bergam64** [comment]
Hello Sipke,

This might help you:

here's how I extract the _expected_ Elsa version number, like "2.9.0" instead of "2.9.0.0", when I start my Elsa server. The trick is to use the `AssemblyInformationalVersionAttribute` (which contains a value like `"2.9.0+dd9fb865f66d4c6e053077aadab819c6aed1eb1a"` and just take the part before the `+`) instead of the `AssemblyVersionAttribute` or `AssemblyFileVersionAttribute` (which both contain a value like `"2.9.0.0"`).

```csharp
private static string GetElsaVersionAsString()
{
    var elsaAssembly = typeof(Elsa.Builders.IWorkflow).Assembly; // Assembly 'Elsa.Abstractions'.
    var attribute = elsaAssembly.GetCustomAttribute<AssemblyInformationalVersionAttribute>();
    if (attribute is null)
    {
        string message =
            $"Expected {nameof(AssemblyInformationalVersionAttribute)} not found on assembly" +
            $" {elsaAssembly}!";

        throw new InvalidOperationException(message);
    }

    string version = GetVersionWithoutSuffix(attribute.InformationalVersion);

    return version;
}

private static string GetVersionWithoutSuffix(string version)
{
    int position = version.IndexOf('+', StringComparison.Ordinal);
    if (position == -1)
    {
        return version;
    }

    string versionWithoutSuffix = version[..position];

    return versionWithoutSuffix;
}
```

Just my 2 cents...

**Comment by sfmskywalker** [comment]
@Bergam64 That's very helpful thank you for that 👍🏻

**Comment by mohdali** [comment]
@Bergam64 Thanks! This would help in the backend indeed!.

Do you have any suggestions in node? I was thinking to have a pre/post build script to update the version dynamically.

**Comment by sfmskywalker** [comment]
Closed via https://github.com/elsa-workflows/elsa-core/pull/3389
