### ISSUE TITLE
Workflow disappears after deleting an unpublished change

### ISSUE THREAD

**Issue by montoner0** [elsa-workflows/elsa-core#3376]
If you try to make a change to a workflow and then try to undo the change through the version history this will make the whole workflow disappear from the workflow definitions list.

Steps to reproduce:

1. Create and publish any workflow
2. Make a change to it
3. Open the version history and delete the unpublished change (it will be first entry in the list)
4. (optionally) Try to publish the workflow and get 500 error
5. Go to workflow definitions list - the workflow is missing

A quick research has shown that the workflow has lost its `IsLatest` flag in the `WorkflowDefinitions` table.

I think the deletion should check if the remaining versions have the flag and either warn user or silently assign it to the latest by date version. I could try to implement the fix if this way is okay.

**Comment by sfmskywalker** [comment]
Coincidently, I ran into this myself today. Thanks for reporting!

**Comment by sfmskywalker** [comment]
And yes, if you want to give it a go and submit a fix I’d be absolutely grateful 🙏🏻

**Comment by sfmskywalker** [comment]
Fixed via #3378
