### ISSUE TITLE
How to create a workflow by using the database workflow provider?

### ISSUE THREAD

**Issue by uyarbtrlp** [elsa-workflows/elsa-core#3380]
Hello,

We've been supporting the multi-tenancy in our system. We want to provide a base template for the each tenant so that they could change the workflow however they want. As far as I understood we can only edit the workflow which is based on the database workflow provider (Mainly the issue is editing the workflow).

The question: is it possible to create the workflow by using the database workflow provider when the application starts? Are there any API for that like the programmatic workflow provider (by using IWorkflow interface)
If there are, how can I implement it?

**Comment by montoner0** [comment]
You could try to look at the import code since it can create workflows in runtime.
