### ISSUE TITLE
Configuration Variables from Liquid

### ISSUE THREAD

**Issue by taurisjoe** [elsa-workflows/elsa-core#3381]
Hi guys,

I appear to be unable to retrieve configuration variables using Liquid as defined in the documentation.  It's working as expected with javascript so I'm able to workaround this for now.  

This works:
```
getConfig("Section") 
```

This does not work:
```
{{ Configuration.Section }} 
```

Thanks.

**Comment by montoner0** [comment]
You need to explicitly enable access to the configuration from Liquid with `EnableLiquidConfigurationAccess()` on `ElsaOptionsBuilder.Services`.
