### ISSUE TITLE
[Instances] Workflow definition not found

### ISSUE THREAD

**Issue by Juandavi1** [elsa-workflows/elsa-core#3401]
Hi ! Awesome project ! 

We have a few defined workflows and it runs well but the instances doesn't show the workflow name :(

![image](https://user-images.githubusercontent.com/18731612/199408381-be6545b7-e81d-4728-ab3c-4fb7f8145839.png)

We are working with 2.9.0-preview.412 version 

Thank youu !

**Comment by sfmskywalker** [comment]
Can you try the latest 2.9.2-rc2 release from NuGet?

**Comment by Juandavi1** [comment]
Hello! We are trying with version 2.9.2 but it still happens :(

**Comment by sfmskywalker** [comment]
If you reload the page, do you still get this issue?

**Comment by Juandavi1** [comment]
let me check it with the 2.10 version
