### ISSUE TITLE
Confirm the operation record of the process through WorkflowInstanceLogRecords

### ISSUE THREAD

**Issue by djw0306** [elsa-workflows/elsa-core#3406]
In the course of using it, I found a problem. Although this workflow records all the operation records, there is no good way to directly restore the operation process when I use the instance, as shown in the following figure.
![image](https://user-images.githubusercontent.com/48092649/200267569-1bf1a4ea-9801-4a26-9418-08cebd4e5296.png)
I can only look at it one by one on this page, what is recorded in this record, but there is no good way to tell me how to finish the process.
In view of the fact that the corresponding steps of the diagram I have provided are:开始>提交>回退>提交>审核>join>finish.
If there is any good way to directly reflect my corresponding steps, I hope you can help me.

**Comment by longletian** [comment]
我在想是否可以加中间表，把数据写进去
