### ISSUE TITLE
Elsa.Secrets Persistence for EntityFramework Core needs a SqlServer package

### ISSUE THREAD

**Issue by BenSeymourODB** [elsa-workflows/elsa-core#3420]
**UPDATE**: see next comment for the real issue. Below is my initial assessment of the problem I was running into.

The [`Elsa.Secrets.Persistence.EntityFramework.Sqlite`](https://github.com/elsa-workflows/elsa-core/tree/master/src/modules/secrets/Elsa.Secrets.Persistance.EntityFramework.Sqlite) project has migration files, allowing the needed `Elsa.Secrets` table to be created when `autorunMigrations = true`. 

By contrast, the `Elsa.Secrets.Persistence.EntityFramework.Core` project only includes a [create-migrations-initial.cmd](https://github.com/elsa-workflows/elsa-core/blob/master/src/modules/secrets/Elsa.Secrets.Persistence.EntityFramework.Core/create-migrations-initial.cmd) file for running the migration-creation commands. It is unclear if there's a way to use this file from the NuGet package, or if consumers are expected to go to the source to run the migration-creation commands themselves.

The immediate fix appears to be running the commands from the file, then committing the generated migrations so that the `Elsa.Secrets.Persistence.EntityFramework.Core` package can reference them on application startup.

**Comment by BenSeymourODB** [comment]
After reviewing the structure of the [`Elsa.Persistence.EntityFramework`](https://github.com/elsa-workflows/elsa-core/tree/master/src/persistence/Elsa.Persistence.EntityFramework) projects, it's clear now that what's actually missing for my use case is an Elsa.Secrets.Persistence.EntityFramework.SqlServer project.

**Comment by sfmskywalker** [comment]
Indeed. Would you like to submit a PR? :)

**Comment by BenSeymourODB** [comment]
For sure - I think I can see what needs to be done. Right now it's just competing for time with the need to get Secrets working in my team's project. 😅

**Comment by sfmskywalker** [comment]
Completely understood 👍🏻
