### ISSUE TITLE
Update to .NET 7

### ISSUE THREAD

**Issue by vgb1993** [elsa-workflows/elsa-core#3421]
.NET 7 has finally been released! 🙌

It would be nice to update.

Enjoy the conference!

**Comment by mohdali** [comment]
Working on it :)

Few EF core providers are still not compatible with .NET7 (MySQL and Oracle). But I think they are in progress.

**Comment by vgb1993** [comment]
Nice! So many good feaures in this one

Do you have a link to the issues you mentioned? 👀

I guess it wouldn't be possible to update only .NET and leave EF6 meanwhile those EF7 Providers get updated, right?

**Comment by mohdali** [comment]
MySQL provider just merged the update to EF7 yesterday. But it is not yet released.
 https://github.com/PomeloFoundation/Pomelo.EntityFrameworkCore.MySql/pull/1717

Oracle in still not sure. Last update was 6 months back.

With Multi-targeting those providers will remain supporting .NET6 only while others can be upgraded. If you try to use them in .NET7 project you will get dependecy errors.

**Comment by mohdali** [comment]
@vgb1993 I have updated this branch https://github.com/elsa-workflows/elsa-core/tree/net7 to use MySQL 7.0.0-alpha for time being. I also merged latest master branch. Could you give it a try to see if things work well for your use case?

**Comment by vgb1993** [comment]
We are not using MySql but might try to use the branch anyway
