### ISSUE TITLE
Issue using designer got UnsupportedApiVersion

### ISSUE THREAD

**Issue by zinebAme** [elsa-workflows/elsa-core#3424]
Hello,
I use Elsa version 2.9.1.
When I try to add an activity in the designer. its not working.
I got this error in console

"UnsupportedApiVersion"
"The HTTP resource that matches the request URI 'https://localhost:57500/v1/scripting/javascript/type-definitions/f0e03b99cd4d4eaf97908937452edf39' with API version '1' does not support HTTP method 'GET'."

**Comment by bweltin** [comment]
I have had the same issue, when updating to elsa-workflows-studio 2.9.3. It is missing the endpoint (.../v1/version).
That endpoint is already existing in the branch "2.9.x". 

Seems like we need to wait there a little bit, until we can use it.

Another workaround until then could be to build the nuget packages locally and add it from your local nuget feed.

**Comment by zinebAme** [comment]
For the moment, I downgrade to the version 2.2.0 and the designer and dashboard works correctly

**Comment by simfyz** [comment]
@zinebAme are you working on the designer with Angular?
