### ISSUE TITLE
prevent workflow execution in case of an activity fails

### ISSUE THREAD

**Issue by aghasemiN** [elsa-workflows/elsa-core#3425]
hi
I have a workflow in workflow designer with SendEmail activity within 'for loop' activity, the problem that I have when email sending fails I want to break the loop or end the workflow or anything else but I can't get error in 'Done' connection , I use 'Unexpected error' connection and I have added 'Fault' activity or 'Break' activity to it but nothing works, the 'Done' connection also runs anyway,so I don't know how can I prevent workflow to continue if SendEmail fails.
Thanks

**Comment by sfmskywalker** [comment]
The Done outcome is always executed, so you should connect your "success" path to the "Success" outcome of the activity which is only executed if no exception occurred.

But I noticed that the "Success" outcome isn't exposed to the designer, which is a bug. I am pushing a fix for this today and make sure it will be part of the upcoming 2.9.2 release.
