### ISSUE TITLE
Possible bug migrating from 2.8 to 2.9.1

### ISSUE THREAD

**Issue by avataron** [elsa-workflows/elsa-core#3429]
I'm testing my workflow definitions in the new Elsa version 2.9.1.

In a specific workflow I have an Activity that calls a child workflow (the RunWorkflow activity).

In v2.8 this works good, I say, the "master" workflow is set to "Suspended" status when it reaches the child workflow. Good.

But in v2.9.1 the "master" workflow is set to "Finished".

Well, I noticed that the new version introduced break changes (ie: I noticed the State outcome was changed, which broke my definitions). So, is the Workflow with RunWorkflow working different now or is it a bug?

**Comment by sfmskywalker** [comment]
Could be a bug, because when you configure the `Mode` property of the `RunWorkflow` activity with `Blocking`, the parent workflow should not finish until the child workflow finishes.

If you can share steps to reproduce this with the latest version (2.9.2) then we can figure out how to fix it.

**Comment by avataron** [comment]
New day, I tried to add missing dependency from 2.8 to 2.9 (webhook, although it is not being used in these definitions) and now it seems working. :S
The problem is I removed the reference back and now I could not reproduce the problem. I could be missing something.
For now I'll close the ticket,  I'll continue the investigation and if I found the issue again, I tell you here.
