### ISSUE TITLE
How to start/Trigger a workflow using API?

### ISSUE THREAD

**Issue by jayachandra21** [elsa-workflows/elsa-core#344]
Hi,
I have two scenario's to trigger a workflow:
**Scenario 1.** I have designed a workflow using the Elsa Workflow designer. In workflow, I've used the **Signaled** Activity. Now I am trying to trigger a workflow using the below code. However when I execute the below code workflow is not started and no issues found while debugging the code. 
```
// Setup a service collection.
var services = new ServiceCollection()
// Add essential workflow services.
.AddElsa()
 .AddConsoleActivities()
 .BuildServiceProvider();
 var invoker = services.GetService<IWorkflowInvoker>();
await invoker.TriggerSignalAsync("RegisterUser", Variables.Empty);
```
**RegisterUser** user is a name of "Signal" in the Signaled Activity.

**Scenario 2: I** have created a workflow using Elsa workflow designer with an **Write Line** Activity.
Now would like to trigger this workflow upon click on button.
How should I trigger a workflow on button click.

Thank You!

**Comment by ArionWM** [comment]
Response please, we need this anwer (if you want ELSA to be used)

**Comment by sfmskywalker** [comment]
Hey guys, sorry for the late response.

*Scenario 1*
Make sure that the starting activity (the first activity) is of type `Triggered` activity and that its `Signal` is set to `"RegisterUser"`.

*Scenario 2*
Please check out [this article](https://medium.com/@sipkeschoorstra/building-workflow-driven-net-core-applications-with-elsa-139523aa4c50) to see how to trigger a workflow upon user interaction. Look for the section named **Trigger workflow when user submits registration form**

**Comment by ArionWM** [comment]
Thank you, we'll try quickly..
