### ISSUE TITLE
Mysql connection error

### ISSUE THREAD

**Issue by SooRaj-1994** [elsa-workflows/elsa-core#3448]
I received an error similar to this when I tried to design a document approval procedure using your document as a guide.

MySqlConnector.MySqlException: 'You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '"Triggers" WHERE `WorkflowDefinitionId` = 'DocumentApprovalWorkflow'' 

I am using Mysql instead of sqlite. 
![image](https://user-images.githubusercontent.com/74040495/202720300-2a4fe169-88ea-4c73-9278-1613b730350e.png)

I'm hoping you can assist me in finding a solution.

**Comment by jdevillard** [comment]
Which version are you using ?

**Comment by SooRaj-1994** [comment]
I tried it version 8.0.28 and 8.0.31.

**Comment by SooRaj-1994** [comment]
![image](https://user-images.githubusercontent.com/74040495/202834555-92c935f9-dac0-433c-bac6-4209d4c5a066.png)
I'm not sure why this query is running. However, the table name is surrounded by double quotes. When I run this query on workbench, I get the message "Triggers is not valid at this position."

**Comment by akunzai** [comment]
Duplicated with #3430, Fixed in #3446

Try downgrad Elsa version from 2.9.2 to 2.9.1

**Comment by SooRaj-1994** [comment]
When I downgrade Elsa version to 2.9.1 then another error occured.
![image](https://user-images.githubusercontent.com/74040495/203246636-1ab8a15c-5802-4570-933b-63c7644c61df.png)

**Comment by akunzai** [comment]
Try use the elsa-dashboard images that publish before elsa 2.9.2 release
