### ISSUE TITLE
Issues with new x6 designer in Elsa v2

### ISSUE THREAD

**Issue by tomy2105** [elsa-workflows/elsa-core#3454]
Hi @karavajka, @tanelkuhi.
First of all thanks for great work, I definitely like, visually, the new designer :).

A problem I managed to get is ability to get one outcome connected two two activities (something that we weren't able to do in current v2 designer). 

![Double-Link](https://user-images.githubusercontent.com/7658839/203026142-a810d252-952c-4521-8838-cf8c14bea863.png)

Another problems seems to be if you add multiple activities they are placed on top of each other in upper left corner.

And even above some other activities. Which leads me to another comment, it shouldn't be possible to place one activity on top of another (either if placed new, pasted or dragged....)....

Again thanks for great work, hope you can fix those issues, or point me what I did wrong while compiling.

**Comment by tomy2105** [comment]
One more, when I select two activities using mouse and drag them they both move (and appear to stay selected).
But if I drag again only one moves (one I actually dragged). I would expect both to move (because both seem still to be selected using orange rectangle).

**Comment by tomy2105** [comment]
And one more :), the help that is shown when you click on question mark button is no longer valid for x-6 new designer.
Since new designer uses well know idiomes for scrolling etc... I would say just hide this button in new designer.

**Comment by tomy2105** [comment]
And last one is not bug but question about possibility for customization.
Currently outcome name is show if you hover over outcome and in the middle of the connecting line.
Would it be possible to customize where on the connecting line outcome name is shown (beginning, middle, end), or maybe even have outcome names displayed always (as part of activity rectangle next to the blue circle)?

**Comment by jdevillard** [comment]
don't have try the designer, just seeing it during the weekly meeting.

This is awesome. 
If I'm not wrong : 
- when you click on activity it open the panel
- when you click on other activity or something else , it save, close the panel (and open the new one).
-
One thing that could be good IMHO would be to have a something to avoid/revert auto save. 

For example: 

- a general option on the designer to use active/deactivate auto-save
- button(s) on the panel to save/cancel change 
- the ability to revert (ctrl-z?)

**Comment by tomy2105** [comment]
@karavajka, @tanelkuhi  some stuff seems to be fixed with newest PR, so listing here, hope fixes for rest are coming soon.

The inability to click on Add Activity button seems to be fixed.

The auto layout and loading of existing workflow doesn't have problem with having grid on only half of the page....

**Comment by tomy2105** [comment]
With new PR there is something I haven't noticed before (maybe there was but I just didn't notice).

Pressing Auto-layout many times in succession seems to reposition activities again and again making them further apart.

**Comment by tanelkuhi** [comment]
Yes it seems, while I was making things work more like v3, I broke it. There will be a fix for it soon.
