### ISSUE TITLE
Elsa v3 - Write Http Response - Status codes list is not filled in

### ISSUE THREAD

**Issue by cristinamudura** [elsa-workflows/elsa-core#3460]
https://user-images.githubusercontent.com/80831066/203506342-8ad3eb1e-da8a-4298-9aff-f6265f8795bd.mov

**Comment by Invenisso** [comment]
Maybe not directly related to the problem, but how did you run the designer at all? I downloaded the v3 branch, but the Elsa.AllInOne.Web project won't start (FastEndpoints error). I tried to run src\designer\elsa-workflows-designer project but it needs backend service on port 5001. I can't find sources for this backend.
