### ISSUE TITLE
[Question] Display programmatic workflows in the Dashboard

### ISSUE THREAD

**Issue by rusumadalina** [elsa-workflows/elsa-core#348]
Is there any way to configure the dashboard to display also the workflows that are programmatically created? From what I've seen, these workflows are not even stored in the WorkflowDefinitionVersions. It would be very useful to see the running workflows in the dashboard as well as the log part, even if the workflow is created from the code.
If this feature is not supported yet, are there any plans to implement it in the future?

**Comment by sfmskywalker** [comment]
That is currently not supported, but it is definitely something I want to add support for. Even if at first only displaying the workflow instances. Programmatic workflows don't carry information about where to display the activities on the designer, so the designer would need auto-layout to display these workflows. There are existing solutions for this out there, so it can be done.
