### ISSUE TITLE
Elsa.Secrets abstraction

### ISSUE THREAD

**Issue by johnwc** [elsa-workflows/elsa-core#3480]
Adding `Elsa.Secrets` to our WF server project, adds what seems to be unnecessary packages. Can whatever that is requiring `Azure.Identity`, `Microsoft.Identity.Client.Extensions.Msal`, `Elsa.Activities.Sql`, and `Elsa.Scripting.Sql` be abstracted out of the core `Elsa.Secrets` library. Then whoever needs to use it can pull it into their project individually?

```
Updates:

Microsoft.Data.SqlClient.2.1.4 -> Microsoft.Data.SqlClient.3.0.0
Microsoft.Data.SqlClient.SNI.runtime.2.1.1 -> Microsoft.Data.SqlClient.SNI.runtime.3.0.0
Microsoft.Identity.Client.4.21.1 -> Microsoft.Identity.Client.4.22.0
Npgsql.6.0.1 -> Npgsql.6.0.3

Installing:

Azure.Identity.1.3.0
Elsa.Activities.Sql.2.10.0-preview.564
Elsa.Scripting.Sql.2.10.0-preview.564
Elsa.Secrets.2.10.0-preview.564
Microsoft.Identity.Client.Extensions.Msal.2.16.5
```

**Comment by sfmskywalker** [comment]
Indeed, the Secrets package shouldn't have to depend on `Elsa.Activities.Http` and `Elsa.Activities.Sql`.
There should be a new package like e.g. `Elsa.Secrets.Bundle` or whatever that bundles various providers for various other modules (like HTTP and SQL).

**Comment by mohdali** [comment]
I think it is also better to retarget it to `netstandard2.1` once abstraction is done. One less project for multi-targeting :)
