### ISSUE TITLE
The latest 2.10.564 has broken the web UI

### ISSUE THREAD

**Issue by johnwc** [elsa-workflows/elsa-core#3484]
@sfmskywalker The latest 2.10.564 has broken the web UI, only blank white pages now. With 404 on the `elsa-workflows-studio` assets.
<img width="797" alt="image" src="https://user-images.githubusercontent.com/2798441/204152522-3876dadc-edc2-44b9-bc16-63dcc865107f.png">

__Originally posted by @johnwc in https://github.com/elsa-workflows/elsa-core/pull/3446#issuecomment-1328309206__

**Comment by johnwc** [comment]
Tested with 2.10.571 as well

**Comment by johnwc** [comment]
@sfmskywalker Anyway this can get looked at soon? It's holding me up on something I'm trying to get finished.

**Comment by sfmskywalker** [comment]
I'll check this weekend and post here when fixed.

**Comment by sfmskywalker** [comment]
@mohdali has been looking into this issue over the weekend. As it turns out, the build is succeeding even though the NPM build is failing, which causes the NuGet package to be pushed without the complete set of client assets. It looks like he was able to fix this for the net7 branch, so I'll do the same for the master branch.

**Comment by sfmskywalker** [comment]
That did the trick - the latest version on MyGet (Elsa.Designer.Components.Web 2.10.0-preview.590) now contains the necessary assets.

Thanks @mohdali for your investigations!

**Comment by acinep** [comment]
Best I can tell this was broken again in preview 667, and in the 2.10.0 release.  We are pinning to 2.10.0-preview.643 for now just for the Elsa.Designer.Components.Web package.

**Comment by johnwc** [comment]
@sfmskywalker this has occurred again with the 2.10.0 and 2.10.1 releases. 
2.10.0.rc2 is the last version that seems to work.
