### ISSUE TITLE
Credential Manger UI hardcoded path

### ISSUE THREAD

**Issue by johnwc** [elsa-workflows/elsa-core#3485]
Credential manager frontend UI is hardcoding the path for `initializeMonacoWorker(...)`, this is causing a javascript error in the browser.

https://github.com/elsa-workflows/elsa-core/blob/master/src/designer/elsa-workflows-studio/src/modules/credential-manager/elsa-secret-editor-modal/elsa-secret-editor-modal.tsx#L36

**Comment by johnwc** [comment]
This still exists.

**Comment by johnwc** [comment]
@sfmskywalker I think this is resolved via latest release.

**Comment by sfmskywalker** [comment]
Great, thanks @johnwc 👍🏻
