### ISSUE TITLE
.UseSqlServer() ambiguous between Elsa.Persistence.EntityFramework.SqlServer & Microsoft.EntityFrameworkCore Nuget packet

### ISSUE THREAD

**Issue by kelseyyyyyyyyyy** [elsa-workflows/elsa-core#3496]
### How to solve (.UseSqlServer()) ambiguous between Elsa.Persistence.EntityFramework.SqlServer & Microsoft.EntityFrameworkCore Nuget packet in the same project(Program.cs)?

**Background:**
I made a Web form application website by ASP.net core 6.0 EntityFramework with user login information stored in SQLExpress Database. Now i want to add Elsa-core workflow inside my project for handling the "approval" process.

**Issue:**
I followed the following docs to setup but (.UseSqlServer()) ambiguous Errors are appeared.
https://v2.elsaworkflows.io/docs/quickstarts/elsa-dashboard-and-server
- (Microsoft.EntityFrameworkCore is using for my existing database connection)
```
 builder.Services.AddDbContext<ApplicationDbContext>(options =>
  {
      options.UseSqlServer(builder.Configuration.GetConnectionString("DefaultConnection"));
  });
```
![image](https://user-images.githubusercontent.com/119573706/205008922-09029b4a-f2c3-42de-8040-bb81b6fb702d.png)

**Coding**
**Program.cs**
(i deleted the coding for authentication & authorization)
```
  using Elsa.Persistence.EntityFramework.Core.Extensions;
  using Elsa.Persistence.EntityFramework.SqlServer;
  using KelseyWeb.Data;
  using KelseyWeb.Filters;
  using Microsoft.EntityFrameworkCore;
    
  var builder = WebApplication.CreateBuilder(args);
  //workflow engine setting
  var elsaSection = builder.Configuration.GetSection("Elsa");
        // Elsa services.
  builder.Services.AddElsa(elsa => elsa
          .UseEntityFrameworkPersistence(ef => ef.UseSqlServer(builder.Configuration.GetConnectionString("DefaultConnection")))
          .AddConsoleActivities()
          .AddHttpActivities(elsaSection.GetSection("Server").Bind)
          .AddJavaScriptActivities()
      );
  
      // Elsa API endpoints.
  builder.Services.AddElsaApiEndpoints();
  
      // Allow arbitrary client browser apps to access the API.
      // In a production environment, make sure to allow only origins you trust.
  builder.Services.AddCors(cors => cors.AddDefaultPolicy(policy => policy
      .AllowAnyHeader()
      .AllowAnyMethod()
      .AllowAnyOrigin()
      .WithExposedHeaders("Content-Disposition"))
  );
  //end of workflow engine setting
  
  
  builder.Services.AddMvc(options =>
  {
      //options.Filters.Add(new AuthorizeFilter());
      options.Filters.Add(new SessionAuthorizationFilter());
  });
  // Add services to the container.
  builder.Services.AddRazorPages();
  
  builder.Services.AddDbContext<ApplicationDbContext>(options =>
  {
      options.UseSqlServer(builder.Configuration.GetConnectionString("DefaultConnection"));
  });

  //Start from API controller - part 1
  builder.Services.AddControllers();
  builder.Services.AddEndpointsApiExplorer();
  builder.Services.AddSwaggerGen();
  //End from API controller
  
  var app = builder.Build();
  
  if (!app.Environment.IsDevelopment())
  {
      app.UseExceptionHandler("/Error");
      // The default HSTS value is 30 days. You may want to change this for production scenarios, see https://aka.ms/aspnetcore-hsts.
      app.UseHsts();
  }
  
  if (app.Environment.IsDevelopment())
  {
      app.UseSwagger();
      app.UseSwaggerUI();
  }
  
  app.UseHttpsRedirection();
  app.UseStaticFiles();
  
  //for elsa work flow
  app.UseCors();
  app.UseHttpActivities();
  //end of for elsa work flow
  
  app.UseRouting();
    
  //for elsa work flow
  app.UseEndpoints(endpoints =>
  {
      // Elsa API Endpoints are implemented as regular ASP.NET Core API controllers.
      endpoints.MapControllers();
  
      // For Dashboard.
      endpoints.MapFallbackToPage("/_Host");
  });
  //end of for elsa work flow
  
  app.MapRazorPages();
  app.MapDefaultControllerRoute();
  
  //Start from API controller - part 2
  app.MapControllers();
  //End from API controller - part 2
    
  app.UseWelcomePage();
  
  app.Run();
```

**appsettings.json**
```
{
  "Logging": {
    "LogLevel": {
      "Default": "Information",
      "Microsoft.AspNetCore": "Warning"
    }
  },
  "AllowedHosts": "*",

  "ConnectionStrings": {
    "DefaultConnection": "server=.\\SQLExpress; Database=ESEApplicationFormWebApp;uid=kelsey;pwd=12345678;MultipleActiveResultSets=true"
  },
  "Elsa": {
    "Http": {
      "BaseUrl": "http://localhost:7239"
    }
  }
}
```

**launchSettings.json**
```
{
  "profiles": {
    "KelseyWeb": {
      "commandName": "Project",
      "launchBrowser": true,
      "environmentVariables": {
        "ASPNETCORE_ENVIRONMENT": "Development"
      },
      "dotnetRunMessages": true,
      "applicationUrl": "https://localhost:7239"
    }
  },
  "iisSettings": {
    "windowsAuthentication": false,
    "anonymousAuthentication": true,
    "iisExpress": {
      "applicationUrl": "https://localhost:7239",
      "sslPort": 44379
    }
  }
}
```

**NuGet Packet installed list**
(I checked Elsa.Persistence.EntityFramework.SqlServer >= 2.9.2 & Microsoft.EntityFrameworkCore.SqlServer >= 6.0.1 are support in net 6.0)
2.9.2 Elsa
2.9.2 Elsa.Activities.Http
2.9.2 Elsa.Activities.Temporal.Quartz
2.9.2 Elsa.Designer.Components.Web
2.9.2 Elsa.Persistence.EntityFramework.SqlServer
2.9.2 Elsa.Server.Api

6.0.10 Microsoft.AspNetCore.Identity.EntityFrameworkCore
6.0.10 Microsoft.EntityFrameworkCore
6.0.10 Microsoft.EntityFrameworkCore.SqlServer
6.0.10 Microsoft.EntityFrameworkCore.Tools
6.0.10 Microsoft.VisualStudio.Web.CodeGeneration.Design

6.4.0 Swashbuckle.AspNetCore

**Remark**
I also tried to use Microsoft.EntityFrameworkCore only but the following error is always happening when i run the project.
![image](https://user-images.githubusercontent.com/119573706/205016274-8e5ca2b8-f867-43a9-9e19-e31e74defde8.png)

I am new for programming and I learn Asp.net core by myself by watching the doc on Microsoft website and Youtube, thus i think i am lacking knowledge on this case. Many appreciate if anyone can give me a hand. Thanks a lot!!!!

**Comment by johnwc** [comment]
> As a workaround, I believe you can call the extension method as if it's a regular static method. E.g., `MyNamespace.ServiceCollectionExtensions.UseSqlServer(suchAndsuch)`

Correct, when you find two extension methods using the same name and parameters, you have to call them using the static method.

```CSHARP
using ef = Microsoft.EntityFrameworkCore;
...
builder.Services.AddDbContext<ApplicationDbContext>(options =>
  {
      ef.DbContextOptionsBuilder.UseSqlServer(options, builder.Configuration.GetConnectionString("DefaultConnection"));
  });
```

**Comment by kelseyyyyyyyyyy** [comment]
> > As a workaround, I believe you can call the extension method as if it's a regular static method. E.g., `MyNamespace.ServiceCollectionExtensions.UseSqlServer(suchAndsuch)`
> 
> Correct, when you find two extension methods using the same name and parameters, you have to call them using the static method.
> 
> ```cs
> using ef = Microsoft.EntityFrameworkCore;
> ...
> builder.Services.AddDbContext<ApplicationDbContext>(options =>
>   {
>       ef.DbContextOptionsBuilder.UseSqlServer(options, builder.Configuration.GetConnectionString("DefaultConnection"));
>   });
> ```

Thanks @sjd2021 and @johnwc, i tried and the problem is fixed!!! thanks a lot!
