### ISSUE TITLE
The elsa-studio-workflow.css file is not limited to elsa

### ISSUE THREAD

**Issue by sjd2021** [elsa-workflows/elsa-core#3499]
There are global styling that target all img tags, etc. That causes issues when embedding the designer into existing web applications which I believe is intended to be a supported option after reading the documentation. Is this intentional or would changes to target just elsa-studio-root, etc. be acceptable?

**Comment by sfmskywalker** [comment]
If there are CSS styles that target elements outside the scope of elsa-studio-root, then that is unintentional. Please feel free to submit a PR that changes these rules to target img tags inside of elsa-studio-root.

**Comment by Snotax** [comment]
Following selectors are applied to the whole HTML page, instead of just the ELSA Designer. Is this being fixed ? 

[type=number],[type=search],[type=text],[type=time],[type=url],select,textarea{
    --tw-shadow:0 0 #0000;
    -webkit-appearance:none;
    -moz-appearance:none;
    appearance:none;
    background-color:#fff;
    border-color:#6b7280;
    border-radius:0;
    border-width:1px;
    font-size:1rem;
    line-height:1.5rem;
    padding:.5rem .75rem
}
[type=number]:focus,[type=search]:focus,[type=text]:focus,[type=time]:focus,[type=url]:focus,select:focus,textarea:focus{
    --tw-ring-inset:var(--tw-empty,
    /*!*/
    /*!*/
    );
    --tw-ring-offset-width:0px;
    --tw-ring-offset-color:#fff;
    --tw-ring-color:#2563eb;
    --tw-ring-offset-shadow:var(--tw-ring-inset) 0 0 0 var(--tw-ring-offset-width) var(--tw-ring-offset-color);
    --tw-ring-shadow:var(--tw-ring-inset) 0 0 0 calc(1px + var(--tw-ring-offset-width)) var(--tw-ring-color);
    border-color:#2563eb;
    box-shadow:var(--tw-ring-offset-shadow),var(--tw-ring-shadow),var(--tw-shadow);
    outline:2px solid transparent;
    outline-offset:2px
}

**Comment by sfmskywalker** [comment]
Based on the description, it sounds like exactly what we need. Do you want to give it a try?

**Comment by sfmskywalker** [comment]
I noticed your PR. Thank you!

**Comment by Snotax** [comment]
Just for a quick update, with ELSA 2.11.0 we still have the problem that some styles from the elsa-workflow-studio.css escalate to our input fields:

![image](https://user-images.githubusercontent.com/11430940/226909261-f49ee1c9-8160-4626-ada5-f11e33d3587a.png)

**Comment by Snotax** [comment]
@sjd2021  Ok, good to know. Thanks

**Comment by sfmskywalker** [comment]
This should be good now (for Elsa 3 designer).

**Comment by Snotax** [comment]
@sfmskywalker  So this will not get fixed in Elsa 2 ?
