### ISSUE TITLE
Support LTS versions of .Net Core

### ISSUE THREAD

**Issue by Cultti** [elsa-workflows/elsa-core#350]
Hi,

It would be great that in future roadmap LTS versions of .Net Core is supported. At the moment Elsa can't be used with .Net Core 2.1 project even tough it is backed by Microsoft until 2021-08-21.

I've done some preliminary testing and it seems that most of Elsa can be converted to support 2.1 just by downgrading packages. However it seems that Elsa.Persistence.EntityFrameworkCore can't be downgraded that easily.

But for future it would be nice that Elsa supports 3.1 until its end of life (2022-12-03).

**Comment by sfmskywalker** [comment]
Hi @Cultti , we'll have to see what we can do given the limited resources we have, but you make a good point because it is important that this project can be used by others that are on LTS. Thanks for pointing this out.
