### ISSUE TITLE
Container activity support

### ISSUE THREAD

**Issue by EmraanSiddiqui** [elsa-workflows/elsa-core#3508]
Hi,

I was going through foreach activity issues and I found one issue against which you already checked in code:
https://github.com/elsa-workflows/elsa-core/pull/218

https://github.com/elsa-workflows/elsa-core/pull/218/commits/05f9f37f6d792bddfa3f25961789a18aae090b33#diff-210d10f0d521d2260c16bc8356c42f2bd10c87d72116bcc4accc96fe47604da0

But when I today took latest code from github and checking I don't found Activity property in foreach, How I can use container activity.

in latest code:
![image](https://user-images.githubusercontent.com/3264483/205901640-79f1c0df-b301-405e-a976-275b48c65ffd.png)

in merged code in pull request:
![image](https://user-images.githubusercontent.com/3264483/205901744-dc32de31-432d-4203-a0ab-4269000b9149.png)

**Comment by EmraanSiddiqui** [comment]
@sfmskywalker is it deleted due to any reason.

**Comment by johnwc** [comment]
You need to attach your activity that you want looped over your array/list to the `Iterate` outcome in the designer. Each item from the array/list will be set as the input for the attached activity.
