### ISSUE TITLE
Elsa.Designer.Components.Web is missing a javascript file (2.9.2)

### ISSUE THREAD

**Issue by uyarbtrlp** [elsa-workflows/elsa-core#3509]
Hi,

I've just updated all my packages 2.9.1 to 2.9.2 and tried to create some workflows in case there've been any errors. I've seen that there's been missing a javascript file regarding to elsa-workflows-studio. Steps to be reproduced

1. Update the all packages 2.9.1 to 2.9.2
2. Hit the workflow instances tab
3. Cannot navigate to the instances table because of the console error

![image](https://user-images.githubusercontent.com/59877078/206112650-ec03c062-ea88-4cb6-a6f3-5ff5dfef6450.png)
![image](https://user-images.githubusercontent.com/59877078/206114516-0d72b45c-19e4-4967-a634-bb2e26eaabb5.png)

I've examined the Elsa.Designer.Component.Web's nuget package and I've seen that **p-288f4c42.entry.js** has been missing. 
Everything is fine when I downgrade it to 2.9.1. What should I do to resolve this?

Thanks.

**Comment by johnwc** [comment]
This is most likely related to the existing issue #3484
