### ISSUE TITLE
The count of UserTask branches should be based on actions

### ISSUE THREAD

**Issue by realLiangshiwei** [elsa-workflows/elsa-core#351]
Currently it has only one done branch, but there are many user actions.

![image](https://user-images.githubusercontent.com/16813853/89031610-694c7f00-d365-11ea-96ac-8c99019571fb.png)

I think It should be (just like the [example](https://github.com/elsa-workflows/elsa-core/blob/develop/src/samples/Sample12/UserTaskWorkflow.cs) you provided ) :

![image](https://user-images.githubusercontent.com/16813853/89031772-baf50980-d365-11ea-9948-69c3c831a405.png)

`UserTask` class should be:

```csharp
[ActivityDefinition(
    Category = "User Tasks",
    Description = "Triggers when a user action is received.",
    Outcomes = "x => x.state.actions")]
public class UserTask : Activity
{
    [ActivityProperty(
        Type = ActivityPropertyTypes.List,
        Hint = "Enter a comma-separated list of available actions"
    )]
    public string[] Actions
    {
        get => GetState(() => new string[0]);
        set => SetState(value);
    }

    protected override bool OnCanExecute(WorkflowExecutionContext context)
    {
        var userAction = GetUserAction(context);

        return Actions.Contains(userAction, StringComparer.OrdinalIgnoreCase);
    }

    protected override ActivityExecutionResult OnExecute(WorkflowExecutionContext context)
    {
        return Halt(true);
    }

    protected override ActivityExecutionResult OnResume(WorkflowExecutionContext context)
    {
        var userAction = GetUserAction(context);
        return Outcome(userAction);
    }

    private string GetUserAction(WorkflowExecutionContext context) =>
        (string) context.Workflow.Input.GetVariable("UserAction");
}
```

What do you think? If my understanding is not correct, please let me know.
Thanks.

**Comment by denis-ivanov** [comment]
+ I've tried the designer and got the same problem.

**Comment by sfmskywalker** [comment]
This is indeed a limitation with the UserTask activity right now. We plan on revisiting this feature for Elsa 2, but after its release.
