### ISSUE TITLE
Dropdown default value ignored

### ISSUE THREAD

**Issue by JEkedorff** [elsa-workflows/elsa-core#3525]
The default value defined a Custom activity's ActivityInput property is not effectful in editor, nor during actual execution of they flow/activity. Below test relates to UIHint: Dropdown, it may or may not also concern other input types.

**Steps to reproduce**
In a custom activity, define an input as below:
```
[ActivityInput(
    Label = "Severity level",
    UIHint = ActivityInputUIHints.Dropdown,
    Options = new[] { "Option1", "Option2"},
    DefaultValue = "Option2"
)]
public string SeverityLevel { get; set; }
```
Create a flow, and add the custom activity with above ActivityInput.

The same behaviour is found if setting the initial value of the property itself:
```
public string SeverityLevel { get; set; } = "Option2"
```

**Expected Result**
Severity Level should be pre-selected with value "Option2" in editor.
Once flow/activity is ran, the property SeverityLevel should be set to "Option2".

**Actual Result**
Default value in editor dialog is the first value provided in "Options", i.e. Option1 in this example
Once flow/activity is ran, the property SeverityLevel is set to "Option1".
 
**Visual Proof**
![2022-12-09 21_05_26-Elsa default value bug](https://user-images.githubusercontent.com/25667524/206789303-1ab53949-4e05-45cb-a5f5-4ce9e189af97.png)

![2022-12-09 21_05_26-Elsa default value bug 2](https://user-images.githubusercontent.com/25667524/206789201-3830de40-e994-4645-9306-43698c80ffe7.png)

Btw, I love the project! Keep up the great work.

**Comment by mohdali** [comment]
You are right, while resolving another issue with Dropdown, default value was overlooked.

Will try to resolve that.
