### ISSUE TITLE
Missing Continue activity to skip an iteration for For/ForEach

### ISSUE THREAD

**Issue by athulds** [elsa-workflows/elsa-core#3534]
I am currently evaluating the ELSA library and doing some POCs. 
Just noticed that, there is no CONTINUE activity available to skip a particular iteration when we are inside any loop. 

Is there a reason behind this or we will be implementing this capability later in the project ? Or is there a way I can achieve the same behavior without dedicated 'CONTINUE' activity. 

Thanks.

**Comment by tomy2105** [comment]
You probably have some branching logic before that continue. 
So you'd have **If** activity somewhere. Just make sure that it's **Done** isn't connected to anything and you should have the logic you are looking for.
I remember writing my own **If** that doesn't have scopes and **Done**, so maybe you need such thing too for your use case. Don't remember if scope if default **If** would mess up the logic I described above....
