### ISSUE TITLE
Timer Activity -Abnormal triggering of a workflows

### ISSUE THREAD

**Issue by jayachandra21** [elsa-workflows/elsa-core#354]
Hi,
I have designed a workflow and used Timer Activity to trigger a workflow with following configurations:
   **Timeout Expression : 00:01:00**
   **"Timers": {"SweepInterval": "0:00:01:00"}**

I have observed the following strange things:

1. If user keep open the Elsa dashboard portal, then timer functionality is working properly(Deployed the dashboard portal in IIS)
2. If user closed the Elsa dashboard portal ,then timer activity **NOT** scheduling/starting the workflow behind the scene.
3. When user reopen the portal after some time, Timer Activity starts/resume workflow.

**Comment by sfmskywalker** [comment]
That's odd. Are you sure the application host running the Timers Background Service is still running when closing the Elsa Dashboard? Depending on your setup, the background tasks can be run from their own process or from the same process that hosts the dashboard. Although you should obviously be able to close the Dashboard browser window, make sure that if you launch a project from Visual Studio and then close the launched browser, Visual Studio doesn't also shutdown the launched process (this happens for example when running with the debugger attached).

**Comment by jayachandra21** [comment]
@sfmskywalker,

Elsa Dashboard application is hosted in the **IIS(Internet Information server)** in **release mode** .
Also, windows  **Task Scheduler** service is running.
![image](https://user-images.githubusercontent.com/67507118/90341659-f8b28d00-e009-11ea-9620-303cfc9ca2b5.png)

Are you talking about this service or any other service should it run to perform timer activity properly?

**Comment by BedirAMS** [comment]
I am having a similar issue, as well. I have timers set for 1 minute, 10 minutes, 1 hour and 8 hours. The 1 minute and 10 minute timers execute fine. But when I lock my computer and come back the next day, the 1 hour and 8 hour timers have not executed.
Is there a limit for the timers? 
I would like to be able to set timers for multiple days or even weeks and months. Is there a better way to do something like that?
An example of how it might be used would be:
When a new user is added, send a welcome email,
then, after a week send a follow-up email
then, after a month send another follow-up email.

**Comment by sfmskywalker** [comment]
I noticed many issues with the timer activities, so reimplemented them by using a proper scheduling library (Quartz.net) in the Elsa 2.0 branch.

It will replace Elsa 1 in (hopefully) a couple more months.

**Comment by BedirAMS** [comment]
> I noticed many issues with the timer activities, so reimplemented them by using a proper scheduling library (Quartz.net) in the Elsa 2.0 branch.
> 
> It will replace Elsa 1 in (hopefully) a couple more months.

Ok, I think I will just wait for Elsa 2.0.
Do you know if Elsa 2.0 will be compatible with the current dashboard (1.5.x.x)? Because, it seems like the Elsa 2.0 dashboard will be built with Blazor and I do not plan on using Blazor yet.
Thank you for the response and all the hard work you have been doing!

**Comment by sfmskywalker** [comment]
I'm afraid not. The purpose of the Blazor dashboard is for users to use it as-is to manage workflows, and for developers to extend it with their own modules if they want. That being said, I do intend for Elsa to be reusable in all sorts of scenarios, including as a regular MVC application, as an MVC area, as an Orchard Core module, as an ABP module, etc. The designer itself is being written as a clean HTML5 web component. This allows you to use it in regular HTML pages, but I'll also provide bindings for React, Angular, Vue and Blazor as well as an MVC Razor View component.

The order in which these things happen depends largely on personal needs as well as feedback from the community.

**Comment by craigfowler** [comment]
It looks like this issue is either resolved or that at least _there's nothing left to be done about it_.  If you believe I have closed it in error, please re-open.
