### ISSUE TITLE
Instance viewer appears to have stopped working properly in a recent update

### ISSUE THREAD

**Issue by sjd2021** [elsa-workflows/elsa-core#3548]
I can no longer see the activities in the instance history designer. Note that the history does show up accurately in the journal.

![image](https://user-images.githubusercontent.com/84007094/208232414-429bff07-46ea-49a3-88a6-712ce3c77641.png)

I haven't had time to roll back enough and see which version caused the issue, but the instance viewer appears to have stopped working sometime recently. I'm noticing this on 2.9.2. I thought I had a plugin or something else causing the display issue, but I've disabled my plugins and am using the native designer OOTB (with NoCoreActivities + SendEmail activity). I also see the same  display issue on past instances which used to display properly when I was using 2.8.x.

**Comment by sfmskywalker** [comment]
Definitely not expected to not see activities on the designer like this. Have you checked the browser console for any errors?
