### ISSUE TITLE
Custom Http Activity 

### ISSUE THREAD

**Issue by Juandavi1** [elsa-workflows/elsa-core#3549]
Hi ! 

We are trying to add a custom http activity inheriting default http activity to add custom properties but the endpoint doesn't appear in swagger :(  

we are working with 2.9.2 version 

thanks a lot

**Comment by sfmskywalker** [comment]
Hi @Juandavi1 !

It looks like that the HttpEndpoint activity wasn't designed for inheritance, which means things like swagger won't automatically work.

We could probably change this, and I will try to implement it in V3, but for now you would have to implement a custom `IDocumentFilter` (take a look at the existing [HttpEndpointDocumentFilter](https://github.com/elsa-workflows/elsa-core/blob/master/src/activities/Elsa.Activities.Http.OpenApi/HttpEndpointDocumentFilter.cs), or update that filter to support derivatives of `HttpEndpoint` and submit a PR :)
