### ISSUE TITLE
Resume vs Trigger

### ISSUE THREAD

**Issue by gtejeda** [elsa-workflows/elsa-core#355]
Greetings guys,
What's the recommended way to resume a workflow that is designed to be halted several times?

I have the following test workflow:
![image](https://user-images.githubusercontent.com/199282/90300524-cfa6c680-de68-11ea-84df-81a42c38f0cc.png)

When starting the workflow it correctly runs the first 2 activities and halts.
When resuming the workflow I've tried two approaches without luck.

My preferred way would be ResumeAsync, since I get the new Instance presumably with it's new state.
await _invoker.ResumeAsync(request.WorkflowInstance, variables, startId);
Where startId = "First Stop" or "Message 3"

But I get an object not set to an instance of an object here

I can use TriggerAsync, but I always get the first 2 Messages as if starting the workflow from the beginning and I can't really figure out how I would trigger it so that they start from the "correct state".

Any help would be greatly appreciated.
Geo

**Comment by sfmskywalker** [comment]
Hi Geo,

Resuming a given workflow instance should just work. Obviously it doesn't in your case, so this looks like a bug.
Could you maybe create a simple sample project that reproduces the issue and send it over? Instead of using your custom activity, maybe just use the Write Line activity that writes to the console. 
Then I'll take your sample project and figure out what's going on.

**Comment by gtejeda** [comment]
Hi Sipke!!! :)

would it be possible you take a look at the private repo I created last time?
https://github.com/gtejeda/elsa-test-demo

I promise, that I'll make this one more generic and maybe contribute it to the sample repository after I get it working.

**Comment by sfmskywalker** [comment]
I wanted to check out your test demo, but the invite link has expired. If you send me a new one I'll have a look!

**Comment by gtejeda** [comment]
Sipke, sorry for the delay here and thanks for the clarification before (it was one of those weeks).

I'm definitely further away in that I'm able to resume and get no errors, however, I don't seem to be able to continue running from the Signaled activity.

ResumeAsync calls for startActivityIds which is an IEnumerable of String, I've tried passing the id of the activity that was stopped, the Id of the next activity, the names and titles and I don't seem to be able to resume it.

Is there any chance you could again shed some light into it for me?
Thanks again!
Geo

**Comment by sfmskywalker** [comment]
@gtejeda My turn to offer my apology for responding this late. When resuming a blocked workflow instance, make sure to provide the following details:

- [x] The activity type (_Signaled_).
- [x] The ID of that activity.
- [ ] The input payload required by the _Signaled_ activity.

The input payload can be constructed as follows:

```csharp
var input = new Variables();
input.SetVariable("Signal", "Name of your signal");
```
