### ISSUE TITLE
Deadlock Issue

### ISSUE THREAD

**Issue by jayachandra21** [elsa-workflows/elsa-core#356]
Hello,

Workflow is triggered based on the **Timer** Activity configuration and when I am trying to open the Elsa Dashboard portal, I am getting the following error frequently.
![image](https://user-images.githubusercontent.com/67507118/90341271-ed119700-e006-11ea-8353-00a07089e4ad.png)

In system Eventviewer it shows **"Deadlock victim"** 
![image](https://user-images.githubusercontent.com/67507118/90341396-0f57e480-e008-11ea-86bd-00c1639c879c.png)

**Comment by sfmskywalker** [comment]
Fixed in Elsa 2.
