### ISSUE TITLE
Missing summary documentation on activities method

### ISSUE THREAD

**Issue by dust63** [elsa-workflows/elsa-core#3564]
When you use elsa to build a workflow as fluent way, it's little frustrating to don't see any documentation on method, to explain the usage and how to configure them ?

Example of method 

StartWith
ForEach
Then
Build
....

**Comment by sfmskywalker** [comment]
Starting with V3, all activities are documented using XML comments to help constructing workflows through code. Ideally, this will happen for V2 as well.
