### ISSUE TITLE
Don't understood how to use ForEach method

### ISSUE THREAD

**Issue by dust63** [elsa-workflows/elsa-core#3565]
I'm trying to use the ForEach method with IWorkflow builder. Can't find any documentation about it.
How to get collection from previous activity ?

**Comment by montoner0** [comment]
Like with any other activities - from `input`.
```
        public void Build(IWorkflowBuilder builder)
        {
            builder.SetVariable(c => c.GetInput<ICollection<EmailMessage>>())...
        }

```
