### ISSUE TITLE
Elastic Search

### ISSUE THREAD

**Issue by cristinamudura** [elsa-workflows/elsa-core#3579]
In addition to having an EF Core persistence provider for `IWorkflowStateStore` & `IWorkflowExecutionLogStore`, we need additional implementations that stores workflow instances directly in Elasticsearch.

Advantages:

- Ability to store lots of data on cheap storage.
- Ability to search through historical data.
- No need for retention policies (although this is still supported and useful if you want to permanently delete data).

**Comment by sfmskywalker** [comment]
Done via #3600
