### ISSUE TITLE
Questions: How to resume a faulted workflow?

### ISSUE THREAD

**Issue by buzzlu** [elsa-workflows/elsa-core#358]
Suppose a workflow has 3 steps.  The workflow was faulted at step 2  as program bugs. 

How can I resume this workflow from the step 2 after we fix  the program bug? 

Many thanks.

**Comment by sfmskywalker** [comment]
There are currently no programmatic means to resume a faulted workflow instance, but it's something we want to add. As a workaround, you could manipulate the workflow instance manually by updating the Status to Halted and BlockingActivities fields to an array with the activity ID of step 2.

**Comment by buzzlu** [comment]
Got it. 

Many thanks.
