### ISSUE TITLE
Invalid object name 'Elsa.WorkflowInstances'.

### ISSUE THREAD

**Issue by nashiora** [elsa-workflows/elsa-core#3595]
I'm getting the same error as issue [#2930](https://github.com/elsa-workflows/elsa-core/issues/2930) in both .NET 6 and .NET 7, on latest Elsa as well as the RC. I've told it to run migrations at runtime as well as through the dotnet ef tooling according to [this guide](https://elsa-workflows.github.io/elsa-core/docs/next/installation/installing-persistence) in the docs. Both ways result in an empty database. There is an __EFMigrationHistory table, but it's empty.

Could this be environmental? I recently switch from a Windows 10 VM to a Windows Server VM for developing the application I'm having issues with. I otherwise don't know what would be wrong on my end.

For completeness, here's the example program I put together from both a blank .NET 6 and .NET 7 web API project. The appsettings.json file contains the appropriate "Elsa" section as well as a connection string.

```cs
using Elsa;
using Elsa.Activities.Console;
using Elsa.Activities.Temporal;
using Elsa.Builders;
using Elsa.Persistence.EntityFramework.Core;
using Elsa.Persistence.EntityFramework.Core.Extensions;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Design;
using NodaTime;

var builder = WebApplication.CreateBuilder(args);

// Add services to the container.
// Learn more about configuring Swagger/OpenAPI at https://aka.ms/aspnetcore/swashbuckle
builder.Services.AddEndpointsApiExplorer();
builder.Services.AddSwaggerGen();

var elsaSection = builder.Configuration.GetSection("Elsa");

// Elsa services.
builder.Services
    .AddElsa(elsa => elsa
        .UseEntityFrameworkPersistence(ef => ef.UseSqlServer(builder.Configuration.GetConnectionString("Elsa")!), autoRunMigrations: true)
        .AddConsoleActivities()
        .AddHttpActivities(elsaSection.GetSection("Server").Bind)
        .AddQuartzTemporalActivities()
        .AddJavaScriptActivities()
        .AddWorkflowsFrom<Program>()
    );

// Elsa API endpoints.
builder.Services.AddElsaApiEndpoints();

// Allow arbitrary client browser apps to access the API.
// In a production environment, make sure to allow only origins you trust.
builder.Services.AddCors(cors => cors.AddDefaultPolicy(policy => policy
    .AllowAnyHeader()
    .AllowAnyMethod()
    .AllowAnyOrigin()
    .WithExposedHeaders("Content-Disposition"))
);

var app = builder.Build();

// Configure the HTTP request pipeline.
if (app.Environment.IsDevelopment())
{
    app.UseSwagger();
    app.UseSwaggerUI();
}

app
    .UseCors()
    .UseHttpActivities()
    .UseRouting()
    .UseEndpoints(endpoints =>
    {
        // Elsa API Endpoints are implemented as regular ASP.NET Core API controllers.
        endpoints.MapControllers();
    });

app.UseHttpsRedirection();

app.Run();

public class HeartbeatWorkflow : IWorkflow
{
    private readonly IClock _clock;
    public HeartbeatWorkflow(IClock clock) => _clock = clock;

    public void Build(IWorkflowBuilder builder) =>
        builder
            .Timer(Duration.FromSeconds(10))
            .WriteLine(context => $"Heartbeat at {_clock.GetCurrentInstant()}");
}

public class SqlElsaContextFactory : IDesignTimeDbContextFactory<ElsaContext>
{
    public ElsaContext CreateDbContext(string[] args)
    {
        var configuration = new ConfigurationBuilder()
            .SetBasePath(Directory.GetCurrentDirectory())
            .AddCommandLine(args)
            .Build();

        var dbContextBuilder = new DbContextOptionsBuilder();
        var connectionString = configuration.GetConnectionString("Elsa");

        dbContextBuilder.UseSqlServer(connectionString, sql => sql.MigrationsAssembly(typeof(Program).Assembly.FullName));

        return new ElsaContext(dbContextBuilder.Options);
    }
}
```

**Comment by nashiora** [comment]
I was able to work around this for now by created a DbContext in my application which inherits ElsaContext and using it to create my own migrations off of that instead. So this has me wondering if the tooling can even find the correct migrations for the base ElsaContext?

**Comment by tmunihareesh** [comment]
Hi Nashiora,

I am very new this elsa. trying to integrate into my .net web api application. But I want to the EF to create table and schema. Because IIS user will not have DDL permissions. So I wanted to create the scripts with custom schema and run manually before deploying the application.
Do you have any solution for this?
If you have anything and find anything of this sort please update me.
Thanks in advace.

**Comment by bogdandynamic** [comment]
I was stuck with the same problem but ultimately managed to figure it out.
Just remove the `using Microsoft.EntityFrameworkCore;` import and add `using Elsa.Persistence.EntityFramework.SqlServer;`.
Your code (and mine also) was using the `UseSqlServer` extension method from the Microsoft.EntityFrameworkCore assembly and not from Elsa.Persistence.EntityFramework.SqlServer.
After the switch, all worked flawlessly.
Hope it helps.

**Comment by sfmskywalker** [comment]
Thanks for sharing @bogdandynamic ! Indeed, the extension names are the same, which makes it very subtle to identify the issue. For V3, we changed the extension names to avoid confusion.
