### ISSUE TITLE
Workflow visualizer is partially broken in latest version of Chrome (109.0.5414.75) and Edge (109.0.1518.49)

### ISSUE THREAD

**Issue by Bergam64** [elsa-workflows/elsa-core#3621]
Hello Elsa Team!

I'd like to report a strange problem that I've spotted recently in Elsa workflow visualizer, after upgrading Chrome to the latest version (109.0.5414.75): the **first rendering** of the workflow diagram is broken.

When I open a workflow definition or a workflow instance, what is initially displayed is not the workflow as expected, but this:
![image](https://user-images.githubusercontent.com/29800159/212325966-6671a0e1-f439-4420-b2ef-c2de637c2605.png)

After dragging the diagram (to see all of it), it turns out that what is actually rendered is some kind of _mini skeleton_ of the workflow, with only the connections between activities:
![image](https://user-images.githubusercontent.com/29800159/212326053-ee658566-8548-4ffc-80dd-7cba5b0e6bc9.png)

Note: I don't see any error in the JavaScript console:
![image](https://user-images.githubusercontent.com/29800159/212330080-c90912a6-0907-498e-8845-1dffcf3a7502.png)

Oddly enough, if I refresh the page at that point (**F5**), the bug _appears_ to be gone (the rendering is normal).
Here's what it looks like (after zooming out, so you can compare with my second screenshot):
![image](https://user-images.githubusercontent.com/29800159/212326657-ccf901c0-dcde-4643-8da1-16032499b751.png)

The booby-trap is that the next **first** rendering of the same diagram will trigger the same bug again (e.g. by going back to the list of workflow definitions and reopening the same workflow definition).

Initially, I thought the problem was in Elsa as it so happened that I had upgraded from 2.8.2 to 2.9.3 _on the same day_ that I upgraded Chrome to its latest version. So I've tried in Edge and I saw that the problem wasn't present. I might have jumped to conclusions at that point, but then I also noticed that Edge had not yet been upgraded to its own latest version. So I upgraded it and  **the same visual problem also appeared**!

Notes:
- Force-reloading the page (**Ctrl+F5**) doesn't do anything more than **F5**, in either browser.
- Even after downgrading Elsa to 2.8.2, the problem is still present, so it's clearly linked to the latest version of the browsers, and the previous version of them (108.0.*) didn't have the problem.
- Chrome version (with the problem) is **Version 109.0.5414.75 (Official Build) (64-bit)**. I don't remember the precise previous Chrome version.
- Initial Edge version (without the problem) was **Version 108.0.1462.76 (Official build) (64-bit)**.
- Final Edge version (with the problem) is **Version 109.0.1518.49 (Official build) (64-bit)**.

I don't know it the problem lies in the way Elsa draws workflow diagrams (which might somehow use a non-standard HTML/CSS/JavaScript/SVG feature) or if both browsers both have introduced a _regression_ related to that area in their latest version, but you should be aware of this. I won't be the only Elsa user using these versions of Chrome or Edge.

Thanks in advance and keep up the good work !

**Comment by mohdali** [comment]
I have found the issue started occurring with Chromium version 109.0.5401. Latest working version was: 109.0.5399.3

This is a list of changes between the two versions. https://chromium.googlesource.com/chromium/src/+log/109.0.5399.3..109.0.5401.0/?pretty=oneline&n=10000

I'm still not sure the root cause. Probably something related to SVG handling. Need to check further.
