### ISSUE TITLE
Workflow Instances view is not displayed

### ISSUE THREAD

**Issue by cristinamudura** [elsa-workflows/elsa-core#3624]
The workflow instances view in the designer is not shown when using packages. This happens also when running the Elsa.AllInOne.Web for example.

Attached you can find a sample project.

https://user-images.githubusercontent.com/80831066/212359767-c31fb910-d3e6-49dc-b002-0a7692902882.mov

[Elsa3.Samples.zip](https://github.com/elsa-workflows/elsa-core/files/10413021/Elsa3.Samples.zip)

**Comment by sfmskywalker** [comment]
Fixed with latest preview packages - see also the updated sample: 
[Elsa3.Samples-fixed.zip](https://github.com/elsa-workflows/elsa-core/files/10417274/Elsa3.Samples-fixed.zip)
