### ISSUE TITLE
Remove 3rd party dependencies

### ISSUE THREAD

**Issue by miguelhasse** [elsa-workflows/elsa-core#3625]
Is there a plan to remove dependencies on the following libraries?
- AutoMapper
- Humanizer.Core
- MediatR
- NodaTime.Serialization.JsonNet
- Open.Linq.AsyncExtensions
- Rebus
- Scrutor

None of there should be required as they will be forced into solutions where they have no place, for various reasons.

**Comment by sfmskywalker** [comment]
All but `Open.Linq.AsyncExtensions` are gone from V3.
Out of curiosity, could you elaborate a bit on the various reasons?

**Comment by XuJin186** [comment]
In theory, the corresponding interface should be defined in elsa, and then the concrete implementation such as AutoMapping should be used to do it, so that it can be compatible with ABP, and later developers can replace the concrete implementation if they don't like using automapping

**Comment by miguelhasse** [comment]
@sfmskywalker 3rd party libraries shouldn't depend on other 3rd party libraries, except if absolutely necessary, much less depend on contracts defined in 3rd party libraries. Again, there are various reasons for following this best practice. For most, a 3rd party library should never force a solution to use specific 3rd party implementations.
