### ISSUE TITLE
cascade dropdown functionality in elsa workflow

### ISSUE THREAD

**Issue by sairamjallepalli** [elsa-workflows/elsa-core#364]
Hi Team,
I need cascade dropdown functionality in elsa workflow.
i.e. based on parent dropdown value selection child dropdown should be papulate.
can you please help on this.

**Comment by sairamjallepalli** [comment]
Thank you Schoorstra.

We will try to implement that functionality from our end.
is there any similar reference in Dotnet Core.

Thanks in Advance.

**Comment by GustavoArriola** [comment]
@sairamjallepalli Did you manage to do in .net core? I have in the same situation now but sadly, I'm not strong in typescript.

**Comment by sfmskywalker** [comment]
I just wrote [this SO answer](https://stackoverflow.com/questions/72102024/elsa-workflow-how-to-implement-cascade-dropdown/72273275#72273275) about implementing cascading dropdowns.
