### ISSUE TITLE
Workflow designer problem - when update Chrome to 109.0.5414.75 (Build) (a 64 bit)

### ISSUE THREAD

**Issue by mircotamburini** [elsa-workflows/elsa-core#3648]
I update my chrome browser and after that workflow designer show the flow outside screen (at left)

strange behavior if press << the work appear whole on left

![workflow](https://user-images.githubusercontent.com/37830748/214319606-f9a24b12-c59a-414d-8c24-15141fba0c18.png)

**Comment by mohdali** [comment]
Hi,

Thanks for reporting.

Issue identified and fixed here https://github.com/elsa-workflows/elsa-core/pull/3628

**Comment by mircotamburini** [comment]
When a new release?

**Comment by francois-sk-itfaq** [comment]
On chrome  109.0.5414.120, not even possible to use the designer after clicking on the create worklow button.

Screen become empty, Same on Edge up to date.

![image](https://user-images.githubusercontent.com/107416005/214577951-35b7b992-5c02-4336-b1f5-0925fff2336b.png)
