### ISSUE TITLE
Elsa workflow activity not run in the background when the portal dashboard is closed

### ISSUE THREAD

**Issue by emicortez** [elsa-workflows/elsa-core#3656]
Hi, I have recurrence task running with a timer, every 10 minutes. It's running in IIS.

When I open the portal dashboard, the task runs every 10 minutes. But If I close the portal dashboard, the task stops running every 10 minutes. Any suggestions?

**Comment by mohdali** [comment]
Hi, you need to make sure IIS is always running.

Refer this guide

https://docs.hangfire.io/en/latest/deployment-to-production/making-aspnet-app-always-running.html#:~:text=Right%2Dclick%20on%20the%20same,waiting%20for%20the%20initial%20request.

**Comment by emicortez** [comment]
Hi, thanks a lot!
