### ISSUE TITLE
Designer does not work since 2.10.1

### ISSUE THREAD

**Issue by nickbeau** [elsa-workflows/elsa-core#3659]
In 2.10.1, the new designer keeps writing and reading to the server too often and it is impossible to create connections between activities when ```use-x6-graphs``` is set to true

**Repo**
1. Run Elsa Studio with use-x6-graphs set to true
2. Attempt to connect two activities
3. Line starts to be drawn but gets reset as the UI "Saves"

**Comment by Juandavi1** [comment]
Hi ! Same here 👆

**Comment by diegocantero** [comment]
Hi ! Same here :(

**Comment by nickbeau** [comment]
Resolved with #3675
