### ISSUE TITLE
vNext use elsa ,can't import workflow json files.

### ISSUE THREAD

**Issue by pest1999** [elsa-workflows/elsa-core#366]
I tried，I can see the dashboard, I can add Activity, but I can't import any json files as a activity. 
When I import a json file，the program is shutdown. I don't know what happened。
I am sure the files is correct，at elsa-sample project this way can work.
I used vnext and github.com/zrkcode/Elsa-Workflow-Issue ,the error is same. But github.com/elsa-workflows/elsa-samples has no error.

**Comment by sfmskywalker** [comment]
Did you try with a debugger attached? It's hard to say what went wrong without seeing any errors.

**Comment by sfmskywalker** [comment]
No longer an issue with Elsa 2.
