### ISSUE TITLE
parse JSON IS GONE !?

### ISSUE THREAD

**Issue by pepea23** [elsa-workflows/elsa-core#3660]
![image](https://user-images.githubusercontent.com/32633442/216004711-ff17faad-87b4-428f-ad89-f33abacf36f2.png)

latest 2.9 from docker

**Comment by sfmskywalker** [comment]
I believe that you should now select ".NET Type", which will use `ExpandoObject` like what was used by the JSON parser.

**Comment by pepea23** [comment]
> I believe that you should now select ".NET Type", which will use `ExpandoObject` like what was used by the JSON parser.

It work thankkk
