### ISSUE TITLE
v2.10 x6 designer fires save endpoint too much

### ISSUE THREAD

**Issue by sabitertan** [elsa-workflows/elsa-core#3675]
While dragging or trying to connect two activities there are many network calls to save endpoint. That also causing extra render that breaks dragging an action or connection.
![Elsa-x6](https://user-images.githubusercontent.com/449663/216782019-72fed970-bd8e-4bde-a685-4c2242fe3a10.gif)
@karavajka @sfmskywalker

**Comment by nickbeau** [comment]
This is the same issue I mention in #3659

**Comment by diegocantero** [comment]
Hi ! Same here :(

**Comment by sabitertan** [comment]
It is resolved, waiting for a release. :)
