### ISSUE TITLE
How to remove or diabled an activity ? 

### ISSUE THREAD

**Issue by zesmaili** [elsa-workflows/elsa-core#3679]
Hi ,

I want to remove or diabled some activities in the core, 
I found out that I can use the RemoveActivity() command in the startup file, 
but the main problem is command not work for the activities Core like SetVariable

**Comment by tomy2105** [comment]
You can skip automatically adding _core_ activities using `NoCoreActivities` and then add them one by one yourself (the ones you need). 
See https://github.com/elsa-workflows/elsa-core/pull/810 for the `NoCoreActivities` explanation.

**Comment by zesmaili** [comment]
> You can skip automatically adding _core_ activities using `NoCoreActivities` and then add them one by one yourself (the ones you need). See #810 for the `NoCoreActivities` explanation.

Thank you so much
The only problem here is that using the `NoCoreActivities` causes all core activities not to be displayed, while I only want one of them not to be displayed, so I had to use the following code:

```
builder.Services.AddElsa(elsa => elsa
         .NoCoreActivities()
         .AddActivitiesFrom<ElsaOptions>()
         .RemoveActivity(typeof(SetVariable))
     );
	 
```
In this way, instead of the main code, I add all the activities myself and delete the ones I want.

**Comment by sfmskywalker** [comment]
Looks like you found an answer to your question @zesmaili 😄
