### ISSUE TITLE
What are top and left properties in activity definition json?

### ISSUE THREAD

**Issue by smadurange** [elsa-workflows/elsa-core#368]
In an activity definition like the one below, what are the `top` and `left` properties for?

```
"activities": [
    {
      "id": "70dc3b23-b717-47e0-b8ae-61c05b8734e2",
      "type": "HttpRequestEvent",
      "left": 34,
      "top": 0,
      "state": {
        "path": "/documents",
        "method": "POST",
        "readContent": "true"
      },
      "blocking": false,
      "executed": false,
      "faulted": false
    }
]
```

**Comment by sfmskywalker** [comment]
These are properties used by the workflow designer to position them on the canvas. They are irrelevant to workflow execution itself. For Elsa 2, I'm considering moving these properties to a metadata type of dictionary to keep the core domain clear from UI-specific notions.
