### ISSUE TITLE
"npm ci" exited with code 127.

### ISSUE THREAD

**Issue by Sverre-W** [elsa-workflows/elsa-core#3680]
When trying to run the sample on the v3 branch my build fails with:
`  Elsa.Workflows.Designer.csproj(31, 9): [MSB3073] The command "npm ci" exited with code 127.`

I'm not super familiar with NPM and MSBuild, currently I worked around it by executing npm ci manually in the terminal in the Elsa.Workflows.Designer project and removing the npm build command from the csproj file.

Any ideas to what can cause this issue?

**Comment by sfmskywalker** [comment]
First time I heard of this. My first guess would be that the path to npm isn't in your PATH environment variable, but as far as I know, that is done for you when you install npm.

**Comment by Sverre-W** [comment]
Yeah code 127 is 'command not found' it seems msbuild uses /usr/bin/sh to execute the commands while my default is zsh so my environment variables don't get loaded. And thus npm is not on the PATH. 

After making sure that /usr/bin/sh also had the npm on the PATH I could run dotnet build without issues, though if I launch from rider itself I still get an issue.
