### ISSUE TITLE
Executing arbitrary JavaScript functions

### ISSUE THREAD

**Issue by smadurange** [elsa-workflows/elsa-core#369]
I'm new to ELSA and am exploring this as a potential WF engine. Does ELSA support execution of arbitrary JavaScript code? Like an activity type for executing code? Thanks.

**Comment by sfmskywalker** [comment]
It does, however there's no such activity yet. Many activities have workflow-expression properties into which one can enter a JS expression, so the necessary bits are there. What would need to be done to implement an e.g. "RunScript" activity is:

1. Create a new activity called `RunScript` with a property of type `WorkflowExpression`.
1. Maybe even model the activity after the equivalent from Orchard Core, with support to set outcomes from script.
1. Ideally update the workflow designer with a new field type that displays a Code Mirror or VS Code editor.
