### ISSUE TITLE
Can't run the Monolith Sample

### ISSUE THREAD

**Issue by atorres16** [elsa-workflows/elsa-core#3692]
Hi,
I just cloned the project from github, rebuilt the project, all packages restored, ran build-assets.ps1 without errors, tried to debug Monolith sample and I got this

![image](https://user-images.githubusercontent.com/19210281/217871614-b278e8ac-e33b-495e-965d-321b1b354a9d.png)

I'm using VS 2022 on Windows 10

I've been working with previous versions without problems, thank you

**Comment by cernydav** [comment]
The same issue here. It is very unpleasant, seems to be happening on all 2.9 versions. First working I found is 2.8.

![image](https://user-images.githubusercontent.com/3006756/217936146-be6cb1b8-ce62-4890-aa6d-fcaa712f5f90.png)

**Comment by sfmskywalker** [comment]
Should be good now with `2.10.2.2` as soon as it's public on NuGet.

**Comment by akunzai** [comment]
Hi @sfmskywalker,

I tried running the `Elsa.Samples.Server.Host` at tag 2.10.2.2 using the latest elsa-dashboard image (sha-f73d0fd)

```sh
docker run -it --rm -e ELSA__SERVER__BASEADDRESS='https://localhost:11000' -e Logging__Console__FormatterName="" -p 14000:80 elsaworkflows/elsa-dashboard
```

But this problem still exists

![CleanShot 2023-02-13 at 22 42 14](https://user-images.githubusercontent.com/574719/218488488-8ec32b14-6ced-4904-a97a-6892e61ddfb6.png)

**Comment by mubinahmed** [comment]
> The same issue here. It is very unpleasant, seems to be happening on all 2.9 versions. First working I found is 2.8.
> 
> ![image](https://user-images.githubusercontent.com/3006756/217936146-be6cb1b8-ce62-4890-aa6d-fcaa712f5f90.png)

What is the tag for the docker image corresponding to that sha?

**Comment by akunzai** [comment]
Hi @mubinahmed,

It should be the git short SHA commit, see [HERE](https://github.com/docker/metadata-action#typesha) for ref.

- [sha-f73d0fd](https://github.com/elsa-workflows/elsa-core/commit/f73d0fdf21f4856895b6cd55daa9e9c713dfbd23)
- [sha-4f70a57](https://github.com/elsa-workflows/elsa-core/commit/4f70a5742fb21e828d66fdc681ab866f549d05e4)

**Comment by akunzai** [comment]
I found that the latest `elsaworkflows/elsa-dashboard` image ([sha-7aa231c](https://github.com/elsa-workflows/elsa-core/commit/7aa231c09d25365bc243732af82bb3ce1f863a61)) solves the problem!
