### ISSUE TITLE
Issue with 2.10.2 - Numerous elements not present in Elsa.Designer.Components.Web Package

### ISSUE THREAD

**Issue by nickbeau** [elsa-workflows/elsa-core#3695]
The Elsa.Designer.Components.Web Package is missing all css and JS files in the assets folder.

@sfmskywalker

**Comment by sfmskywalker** [comment]
Sorry about that. Until we fix the pipeline, I'll do the subsequent releases manually.
I pushed a new version at 2.10.2.1 that should be good.

**Comment by sabitertan** [comment]
When I use master branch it is all good everything is working fine.
But 2.10.2.1 package causing this problem :
![image](https://user-images.githubusercontent.com/449663/218125886-95730f01-8a0e-42e8-bd81-9a91293bf01b.png)
![image](https://user-images.githubusercontent.com/449663/218126024-f4bbf5e9-d8f2-4a40-a153-71f886d4b73c.png)
![image](https://user-images.githubusercontent.com/449663/218126097-d2d8d1d9-cad2-4853-9c68-a27452cccc67.png)

**Comment by nickbeau** [comment]
@sfmskywalker  I can repro this issue as well.

**Comment by sfmskywalker** [comment]
Although I wasn't able to reproduce the JS errors, I was able to reproduce the styling issues. I'm pushing a new set of packages that should fix at least that (and hopefully also the JS errors you showed).

The new version should be available as soon as NuGet is done indexing them.

**Comment by nickbeau** [comment]
@sfmskywalker  Thanks. I'll test today and close this work item if all is good.

**Comment by nickbeau** [comment]
Fixed. Thanks @sfmskywalker
