### ISSUE TITLE
.netstandard 2.0 ?

### ISSUE THREAD

**Issue by xt1** [elsa-workflows/elsa-core#3697]
We would love to use ELSA workflows, but we have a large chunk of the codebase still living in .net 4.8, so we can't use .netstandard 2.1 - we are locked to .net standard 2.0.  The old full framework will never support .net standard 2.1 - so we are :-( 

Are there any technical reasons for using 2.1 rather than 2.0? i.e. is there some 2.1 feature that ELSA requires?

Could we retarget ELSA to netstandard 2.0 and expect it to work?

**Comment by sfmskywalker** [comment]
Maybe, one would have to try and see what breaks. For Elsa 2, probably the core libraries could target 2.0, but I suspect it might already take advantage of some parts of the 2.1 standard. I don't have a list of what these may be, so it's entirely possible that without too much work it could target .net standard 2.0.

The tricky part will be retargeting the other libraries, like the ones implementing the EF core persistence providers and the ASP.NET project exposing the REST API for the designer. They target  netcoreapp3.1, which I believe implements .net standard 2.1.

For Elsa 3, you need .NET 6 and up. Technically, that too could be implemented with .net standard 2.0, but given my limited time and resources, it made more sense for me to keep it simple. 

Depending on your use cases, another way that Elsa could be used is by hosting it as its own ASP.NET server and integrate it with your app via AMQP messaging and HTTP. The workflow server would then act as a conductor.
Elsa 3
