### ISSUE TITLE
Upgrade workflow process

### ISSUE THREAD

**Issue by Bykiev** [elsa-workflows/elsa-core#37]
I'm new to Elsa, and it's not clear how to update existing workflow process? In Windows WF it is possible to update old workflow process or execute side-by-side different versions. Is any of them supported by Elsa?

**Comment by sfmskywalker** [comment]
@Bykiev Absolutely. When a workflow is executed, a copy is created that is treated as the workflow instance. This means that you can safely edit the workflow definition without affecting any instances. 

Although this method is bullet-proof, it does add a little bit of overhead in terms of memory. For example, each workflow instance will now have all of the defined activities as well as the connections between activities stored. Although this won't be a problem for a few thousand instances, it's probably undesirable when you have millions of instances.

So, I am considering revisiting this model and introduce the notion of a separate `WorkflowDefinition`, `WorkflowVersion` and `WorkflowInstance`. A workflow instance will then simply refer to a workflow version, which contains a complete workflow definition. This would be very similar to Windows WF.

**Comment by Bykiev** [comment]
@sfmskywalker, thank you for detailed explanation!
