### ISSUE TITLE
Missing Signal Activity

### ISSUE THREAD

**Issue by sagargolu** [elsa-workflows/elsa-core#3703]
Hi, I am looking for Signal Activity in v3 version but I don't find it. Would you please let us know if it is renamed or removed in v3 version?

**Comment by sfmskywalker** [comment]
In V3, the Signal has been replaced with the `Event` and `Publish` activities.

- _Event_ replaces _SignalReceived_
- _Publish_ replaces _TriggerSignal_

Documentation to follow.

**Comment by sagargolu** [comment]
Thanks for the quick response
