### ISSUE TITLE
Does Elsa workflow engine support .NET 7?

### ISSUE THREAD

**Issue by sanajmshaji** [elsa-workflows/elsa-core#3705]
I'm considering using Elsa workflow engine for my .NET 7 project. However, I'm not sure if Elsa is compatible with .NET 7. Can someone confirm if Elsa supports .NET 7? If not, are there any plans to add support in the near future?

Thank you in advance for your help!

**Comment by Snotax** [comment]
Yes, I'm using ELSA 2.10.X with .NET 7 :D
