### ISSUE TITLE
WorkFlow Invoking is not working

### ISSUE THREAD

**Issue by sagargolu** [elsa-workflows/elsa-core#3706]
Hi Sipke,

We are trying to invoke workflow activity using HttpEndPoint but it is not working. We are trying with your sample workflow for weatherforecast which have 3 activities called HttpEndPoint, HttpRequest and HttpResponse. But we are trying to access "/wf/weatherforecast-designer".

We are getting blank screen only and also nothing is initiated in "Workflow Instances". In the response we are getting "OK". I have attached both the screenshots. 

![image](https://user-images.githubusercontent.com/79979623/219102610-c0dff2de-bc22-4100-98db-ddfb1d0163a3.png)

![image](https://user-images.githubusercontent.com/79979623/219102701-b3ae1870-75f4-4af3-8330-666cc0b0a2dd.png)

**Comment by sfmskywalker** [comment]
Hi @sagargolu , one thing to check: is the ASP.NET core app configured to use `/wf` as the path prefix for Elsa's HTTP feature? If not, then by default it would be `/workflows`, which means the URL to request would be: `https://localhost:7256/workflows/weatherforecast-designer`.

If that' not the case, please zip your project (and SQLite database file if you're using that) and Ill take a look.

PS. Which version of the packages are you using?

**Comment by sagargolu** [comment]
We are using v3 branch and using "**Elsa.Samples.WorkflowServerAndDesigner**" this sample project. We made the two changes as follows.

1) Elsa.Workflows.Designer.csproj.
![image](https://user-images.githubusercontent.com/79979623/219121968-a742c862-b57e-4e62-9a1b-74bee284bbd5.png)
We changed npm commands. It doesn't launch without it.

2) Changed workflow middleware base path to "/wf"
![image](https://user-images.githubusercontent.com/79979623/219122249-ee900423-6626-405e-8f3f-74684ca1eb83.png)

We tried to debug and found the following root cause:

![image](https://user-images.githubusercontent.com/79979623/219122582-0791659c-9693-44ff-932a-2a615ea77107.png)

PFA the SQLite database.
[elsa.sqlite.db.zip](https://github.com/elsa-workflows/elsa-core/files/10746287/elsa.sqlite.db.zip)

If you still require the full source code, I'll be happy to send. Please me know.

**Comment by sagargolu** [comment]
Hi Sipke,

Would you please help us on above issue?

**Comment by sfmskywalker** [comment]
Quick question: according to the workflow fault, a URL is missing. Just to make sure, did you provide a path in the HTTP Endpoint activity?

**Comment by sagargolu** [comment]
Yes, I have provided path in it as well. let me share you the files that we have changed because sharing complete solution will be quite huge.

1) "src\modules\Elsa.Workflows.Designer" : Elsa.Workflows.Designer.csproj
2) "src\samples\aspnet\Elsa.Samples.WorkflowServerAndDesigner" : Program.cs
[ChangesElsav3.zip](https://github.com/elsa-workflows/elsa-core/files/10783904/ChangesElsav3.zip)

**Comment by sfmskywalker** [comment]
Thanks @sagargolu 

I was able to reproduce the problem, which basically boils down to a change introduced some time ago where the workflow trigger store is configured using a memory provider by default.

When the app stops, the triggers are lost.

To fix that, we need to configure the default workflow runtime to use a persistence provider, such as EF Core.
I pushed an updated sample just now, which adds the following to Program.cs:

```csharp
// Configure the default runtime feature to use EF Core.
elsa.UseWorkflowRuntime(runtime =>
{
    runtime.UseDefaultRuntime(defaultRuntime => defaultRuntime.UseEntityFrameworkCore(ef => ef.UseSqlite()));
});
```

When you start the app, you need to open the workflow in the designer and publish it again so that its triggers are captured and stored in the database.

When you now run the workflow, it should work. However, you'll encounter a workflow fault because of the second activity (HTTP Request), which does not contain a URL value.

Let me know how it goes.

**Comment by sfmskywalker** [comment]
Storing workflow instances is an optional feature that you can enable. For an example, please checkout the Elsa.WorkflowServer.Web project in the Bundles folder: https://github.com/elsa-workflows/elsa-core/blob/v3/src/bundles/Elsa.WorkflowServer.Web/Program.cs

You’ll notice that the workflow runtime feature contains a call to `UseAsyncWorkflowStateExporter`, which is what will capture workflow state and store it as workflow instances.

**Comment by sfmskywalker** [comment]
You're very welcome. Let me know if you run into any other issues or questions with V3.
