### ISSUE TITLE
Cron Expression not parsed correctly

### ISSUE THREAD

**Issue by Rhinostril** [elsa-workflows/elsa-core#3709]
Hi,

I'm having issues with a cron expression that starts a workflow. It is a bit overzealous. 
The Workflow is supposed to run at 01:05 every 1st and 16th of every month. Using the expression formatter linked in the dashboard i've  plugged in "0 5 1 1,16 * ? *"   

Which the dashboard UI correctly parses.
![expression](https://user-images.githubusercontent.com/72130661/219319988-87d7c7d3-a3b3-4c25-8f40-0aa1a960bcbc.PNG)

However when executing the job, it fumbles the expression and runs at that time every day.
![cronfail](https://user-images.githubusercontent.com/72130661/219320174-0afd49df-d43b-40f3-a207-8faac786fa48.PNG)

A quick and dirty solution is to split the one workflow into 3, where:
1. contains the business logic of activities
2. starts the first workflow at 1st of the month
3. starts the first workflow at 16th of the month

or i could probably use the other timer to start a workflow at specific times.
Just wanted to share my issue with the community

**Comment by Rhinostril** [comment]
Edit, Somehow today, even with the service running, there wasnt a false positive interpretation of the cronjob. wierd stuff..

**Comment by mohdali** [comment]
Hi @Rhinostril, I have tested the expression and it gets stored in the workflow definition properly. Could it be that the workflow was not published properly and was using an old version of the expression?

**Comment by Rhinostril** [comment]
> Hi @Rhinostril, I have tested the expression and it gets stored in the workflow definition properly. Could it be that the workflow was not published properly and was using an old version of the expression?

this seems to be what happened after digging a bit deeper
