### ISSUE TITLE
Duplicate Workflow Instance IDs

### ISSUE THREAD

**Issue by jayachandra21** [elsa-workflows/elsa-core#371]
Hi,

Workflow is designed such a way that, it triggers based on the **Timer(00:01:00) activity**.I have observed that some times workflow engine generating the duplicate workflow instance ID's and **Status** shows as "**Executing**". Below screen for reference:

![image](https://user-images.githubusercontent.com/67507118/92367832-9d068b80-f0ff-11ea-95fc-fbfda291600b.png)

**Comment by sfmskywalker** [comment]
Fixed in Elsa 2.
