### ISSUE TITLE
How to handle Change of Type in IActivityTypeProvider

### ISSUE THREAD

**Issue by alkampfergit** [elsa-workflows/elsa-core#3712]
I have a controversial example, 

I have an implementation of IActivityTypeProvider that based on swagger json definition is able to generate a series of activities. It works well but now we need to add versioning to the api. This is not a problem but actually if we change how the IActivityTypeProvider generates type names (to take into account version) all existing workflows will not work because actions are missing.

Apart the obvious solution to scan all workflow definition in the database to manually update the records is this a supported scenario? I'd like to have some way to tell the engine that

If you search for activity UsersV1.Current I will tell you that the activity now has the type Users.Current.

**Comment by sfmskywalker** [comment]
Would it work for you if you generated activity descriptors whose type names include the API version?

For Elsa 3, you can generate multiple versions of the same activity descriptor by using different version numbers.
