### ISSUE TITLE
Problems with Elsa after MediatR 12 release

### ISSUE THREAD

**Issue by oyvindlu** [elsa-workflows/elsa-core#3716]
It seems changes done in MediatR 12 makes AddElsa fail. Is it possible to support MediatR 12 version ?
![image](https://user-images.githubusercontent.com/11014971/219900599-33ea3a0f-5c33-49a0-bd8c-1b8e4c7c93c9.png)

**Comment by Gambitier** [comment]
@oyvindlu @sfmskywalker I think this is fixed in https://github.com/elsa-workflows/elsa-core/issues/3775
