### ISSUE TITLE
npm 2.10.2 @elsa-workflows/elsa-workflows-studio 

### ISSUE THREAD

**Issue by Sverre-W** [elsa-workflows/elsa-core#3725]
It seems like the npm package is not yet updated after the issue that caused #3695. When using @elsa-workflows/elsa-workflows-studio 2.10.2 I experienced a similar result. Downgrading to 2.9.3 worked for me.

**Comment by sfmskywalker** [comment]
Can you try 2.10.3 that was just released from the 2.10.x branch?

**Comment by Sverre-W** [comment]
Seems to work again with 2.10.3
