### ISSUE TITLE
Status multi tenancy

### ISSUE THREAD

**Issue by InFLaMIeS** [elsa-workflows/elsa-core#3727]
Hey, just want to ask what the Status of multitenancy is.
Is there already a good way to go or any example Implementation? 
Just read about orchard core and autofac.

**Comment by sfmskywalker** [comment]
For V2, there is some support at the DB level, but there’s no service container per tenant support like Orchard Core has. You might be able to pull it off when using AutoFac, but I haven’t looked into it as of yet. Multitenancy is one of the major topics we’ll look into post V3 release.

**Comment by sfmskywalker** [comment]
It might still happen, but at the same time, not everyone needs multitenancy, so I'm not sure it makes sense to wait with the V3 release in order to ship it with multitenancy support (unless you're one of the few who need it).
