### ISSUE TITLE
Entity Framework Persistence Exceptions

### ISSUE THREAD

**Issue by andyevans2000** [elsa-workflows/elsa-core#373]
I am using the EF persistence provider and getting a lot of exceptions like this...

IWorkflowEventHandler thrown from Elsa.WorkflowEventHandlers.PersistenceWorkflowEventHandler by DbUpdateConcurrencyException
Microsoft.EntityFrameworkCore.DbUpdateConcurrencyException: Database operation expected to affect 1 row(s) but actually affected 0 row(s). Data may have been modified or deleted since entities were loaded. See http://go.microsoft.com/fwlink/?LinkId=527962 for information on understanding and handling optimistic concurrency exceptions.
   at Microsoft.EntityFrameworkCore.Update.AffectedCountModificationCommandBatch.ThrowAggregateUpdateConcurrencyException(Int32 commandIndex, Int32 expectedRowsAffected, Int32 rowsAffected)
   at Microsoft.EntityFrameworkCore.Update.AffectedCountModificationCommandBatch.ConsumeResultSetWithoutPropagationAsync(Int32 commandIndex, RelationalDataReader reader, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Update.AffectedCountModificationCommandBatch.ConsumeAsync(RelationalDataReader reader, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.ExecuteAsync(IRelationalConnection connection, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.ExecuteAsync(IRelationalConnection connection, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.ExecuteAsync(IEnumerable`1 commandBatches, IRelationalConnection connection, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.ExecuteAsync(IEnumerable`1 commandBatches, IRelationalConnection connection, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChangesAsync(IList`1 entriesToSave, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChangesAsync(DbContext _, Boolean acceptAllChangesOnSuccess, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.SqlServer.Storage.Internal.SqlServerExecutionStrategy.ExecuteAsync[TState,TResult](TState state, Func`4 operation, Func`4 verifySucceeded, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.DbContext.SaveChangesAsync(Boolean acceptAllChangesOnSuccess, CancellationToken cancellationToken)
   at Elsa.Persistence.EntityFrameworkCore.Services.EntityFrameworkCoreWorkflowInstanceStore.SaveAsync(WorkflowInstance instance, CancellationToken cancellationToken)
   at Elsa.WorkflowEventHandlers.PersistenceWorkflowEventHandler.SaveWorkflowAsync(Workflow workflow, CancellationToken cancellationToken)
   at Elsa.WorkflowEventHandlers.PersistenceWorkflowEventHandler.WorkflowInvokedAsync(WorkflowExecutionContext workflowExecutionContext, CancellationToken cancellationToken)
   at Elsa.Services.WorkflowInvoker.<>c__DisplayClass22_0.<<FinalizeWorkflowExecutionAsync>b__1>d.MoveNext()
--- End of stack trace

This happens when multiple workflow instances are being signalled and when a timer sweep is being run. So I can reduce these by having a longer sweep interval.

**Comment by vborza** [comment]
We are getting the same error....Any idea how to solve it? I can even create a PR for the fix if you give me some directions.

**Comment by sfmskywalker** [comment]
Interesting. I bet that a given workflow instance record is loaded twice into memory (one per timer event), and both are updated from different threads, causing the concurrency conflict when attempting to write back to the database - which one should "win"? 

If that is the case, the solution might be to ensure that only one copy of a given workflow instance is loaded at a time, instead of multiple ones as is the case now.

The `feature/elsa-2.0` branch contains a re-architecture of the workflow host by employing a workflow scheduler which adds workflows to execute to a queue, processing them one by one. 

Perhaps this setup can be backported to Elsa 1.

**Comment by spokeDev** [comment]
Started having the same issue once we needed to go from a 12 hour sweep interval to 5 minutes. 

We think the majority of the DbUpdateConcurrencyExceptions have to do with how workflows are saved. Activities and BlockingActivities are always deleted and re-added instead of updated. Until we can move to version 2 here is our temp solution. It is not a 100% fix and concurrency issues will still be a problem but since 99% of our TimerEvent activity executions don't actually change workflow data it seems to work fine. Also considering seperating out the TimerEvent's into their own workflow.

We are testing a solution that involves a custom version of EntityFrameworkCoreWorkflowInstanceStore and hooking it in through dependency injection. Lot's of potential issues going down this path, but right now with how we have our workflows setup this seems to work.

In Startup.cs
`services.AddScoped(typeof(IWorkflowInstanceStore), typeof(CustomEntityFrameworkCoreWorkflowInstanceStore));`

`public class CustomEntityFrameworkCoreWorkflowInstanceStore : IWorkflowInstanceStore
...

public async Task<WorkflowInstance> SaveAsync(
            WorkflowInstance workflowInstance,
            CancellationToken cancellationToken = default)
        {
            var existingWorkflowInstanceEntity = await dbContext
                .WorkflowInstances
                .Include(x => x.Activities)
                .Include(x => x.BlockingActivities)
                .FirstOrDefaultAsync(x => x.InstanceId == workflowInstance.Id, cancellationToken: cancellationToken);

            if (existingWorkflowInstanceEntity == null)
            {
                var entity = Map(workflowInstance);

                await dbContext.WorkflowInstances.AddAsync(entity, cancellationToken);
                await dbContext.SaveChangesAsync(cancellationToken);
                return Map(entity);
            }
            else
            {
                UpdateWorkflow(workflowInstance, existingWorkflowInstanceEntity);

                UpdateWorkflowActivities(workflowInstance, existingWorkflowInstanceEntity);

                AddBlockingActivities(workflowInstance, existingWorkflowInstanceEntity);

                RemoveBlockingActivities(workflowInstance, existingWorkflowInstanceEntity);

                await dbContext.SaveChangesAsync(cancellationToken);
                return Map(existingWorkflowInstanceEntity);
            }
        }

        private static void UpdateWorkflow(WorkflowInstance workflowInstance, WorkflowInstanceEntity 
         existingWorkflowInstanceEntity)
        {
            existingWorkflowInstanceEntity.Fault = workflowInstance.Fault;
            existingWorkflowInstanceEntity.ExecutionLog = workflowInstance.ExecutionLog;
            existingWorkflowInstanceEntity.Input = workflowInstance.Input;
            existingWorkflowInstanceEntity.Scopes = workflowInstance.Scopes;
            existingWorkflowInstanceEntity.AbortedAt = workflowInstance.AbortedAt?.ToDateTimeUtc();
            existingWorkflowInstanceEntity.FaultedAt = workflowInstance.FaultedAt?.ToDateTimeUtc();
            existingWorkflowInstanceEntity.FinishedAt = workflowInstance.FinishedAt?.ToDateTimeUtc();
            existingWorkflowInstanceEntity.StartedAt = workflowInstance.StartedAt?.ToDateTimeUtc();
            existingWorkflowInstanceEntity.CorrelationId = workflowInstance.CorrelationId;
            existingWorkflowInstanceEntity.Status = workflowInstance.Status;
        }

        private static void UpdateWorkflowActivities(WorkflowInstance workflowInstance, WorkflowInstanceEntity 
          existingWorkflowInstanceEntity)
        {
            foreach (var activityInstance in workflowInstance.Activities)
            {
                var existingActivityEntity = existingWorkflowInstanceEntity.Activities
                    .Where(c => c.ActivityId == activityInstance.Value.Id)
                    .SingleOrDefault();

                if (existingActivityEntity != null)
                {
                    existingActivityEntity.State = activityInstance.Value.State;
                    existingActivityEntity.Output = activityInstance.Value.Output;
                }
            }
        }

        private static void AddBlockingActivities(WorkflowInstance workflowInstance, WorkflowInstanceEntity 
       existingWorkflowInstanceEntity)
        {
            foreach (var blockingActivitiesInstance in workflowInstance.BlockingActivities)
            {
                var existingBlockingActivity = existingWorkflowInstanceEntity.BlockingActivities
                    .Where(c => c.ActivityId == blockingActivitiesInstance.ActivityId)
                    .SingleOrDefault();

                if (existingBlockingActivity == null)
                {
                    existingWorkflowInstanceEntity.BlockingActivities.Add(new BlockingActivityEntity() { ActivityId = 
                   blockingActivitiesInstance.ActivityId, ActivityType = blockingActivitiesInstance.ActivityType });
                }
            }
        }

        private void RemoveBlockingActivities(WorkflowInstance workflowInstance, WorkflowInstanceEntity existingWorkflowInstanceEntity)
        {
            foreach (var blockingActivityEntity in existingWorkflowInstanceEntity.BlockingActivities)
            {
                var instanceBlockingActivity = workflowInstance.BlockingActivities
                    .Where(c => c.ActivityId == blockingActivityEntity.ActivityId)
                    .SingleOrDefault();

                if (instanceBlockingActivity == null)
                {
                    dbContext.BlockingActivities.Remove(blockingActivityEntity);
                }
            }
        }
...
`

**Comment by sfmskywalker** [comment]
The EF Core persistence provider has been completely rewritten in Elsa 2, which fixes the above issue.
