### ISSUE TITLE
Kafka MessageReceived activity often crashes (handle is destroyed exception.)

### ISSUE THREAD

**Issue by Aerys-cmd** [elsa-workflows/elsa-core#3737]
MessageReceived activity crashes gaves Error while consuming log in console. 
When i manually reference Elsa.ActivitiesKafka project and debug. I see that it gaves handle is destroyed error.

When everything working on correct order and consumer works. It consumes data from the topic and executes Triggering logic for Workflows but workflow does not trigger.

I am referencing those packages in a .Net 7.0 project

Packages
Elsa@2.10.2.2
Elsa.Activities.Kafka@2.10.2.2

**Comment by Aerys-cmd** [comment]
When i debug it manually. I see that consumer gets disposed somewhere in the application and after that Worker tries to close the consumer. That gaves a ObjectDisposedException

**Comment by Snotax** [comment]
Are you using Mulitenancy ? And if yes, do you have implemented the tenant accessor ?

**Comment by Snotax** [comment]
@Aerys-cmd Are there any headers set on the incoming kafka message ?

**Comment by Aerys-cmd** [comment]
Just allow auto create topics.

**Comment by Aerys-cmd** [comment]
I guess the Worker class causes the problem. I'm not familiar with the design so i could't find the error. Let me know if something that i can do to help.

**Comment by Snotax** [comment]
@Aerys-cmd  The error occurs when unpublishing and publishing (Maybe only publishing) a trigger after ELSA is already running. 
I think it somehow calls Client.Dispose() at least twice. 

Not sure why though I'm still trying to understand the system :D
