### ISSUE TITLE
TriggerRequestHandler: Correlation id filtering not working

### ISSUE THREAD

**Issue by Neuroglia** [elsa-workflows/elsa-core#374]
Hello all,

It seems the TriggerRequestHandler's filtering is not working as expected: even though I'm passing a X-Correlation-Id header, it resumes activities that do not have the specified id.

### **Steps to reproduce:**

**A. Create a new workflow such as the following:**
1. Create a ReceiveHttpRequest activity, listening on, for example, the path '/start'
2. Chain it with a Correlate activity, which sets the correlation id based on a property in lastResult().Body, such as lastResult().Body.orderId
3. Chain it with a new ReceiveHttpRequest activity, listening on, for example, the path '/continue'
4. Chain it with a new SendHttpResponse activity

**B. Execute the workflow:**
1. Post a json such as the following on '/start': { "orderId": "123" }
2. Check that a new workflow instance has started and is attributed the 123 correlation id
3. Post a json such as the following on '/start': { "orderId": "456" }
4. Check that a new workflow instance has started and is attributed the 456 correlation id
5. Request the '/continue' endpoint, passing an X-Correlation-Id header with value '123'

### **Expected result:**
The 123 workflow instance is completed, and the 456 workflow instance is still waiting for a correlated request on path '/continue'

### **Actual result:**

One of the two workflow instances is completed, while the other is faulted, regardless of their correlation ids

I checked the code of the Filter function of the TriggerRequestHandler, and it seems fine. I don't understand why it is not working as expected :(

**Comment by Neuroglia** [comment]
I cloned the repo and it works as expected. It seems the problem lies within the current nuget package, aka version 1.2.2.29. 
Can you please update the nuget package to the last version to fix this?

**Comment by sfmskywalker** [comment]
Thanks for the detailed description, that's very helpful.
The develop branch was just merged to master and tagged with 1.3.0, yielding a new nuget package release.
This should fix this issue, but please reopen if otherwise.
