### ISSUE TITLE
#Bug ServiceBus Sender object disposed in multi-node setup

### ISSUE THREAD

**Issue by Adrian-Grimm** [elsa-workflows/elsa-core#3745]
# Background
We are using Elsa 2.9 in a multi-node setup (Azure AKS, Azure Service-Bus, PostgreSQL)

# Problem
Currently 50% of our workflows failing because of some workflow instance requests are put into the dead-letter-queue of the message bus.

### Here our Log details:

"**ServiceBusSender has already been closed and cannot perform the requested operation**"
[Full Log details](https://github.com/elsa-workflows/elsa-core/files/10853427/Bug-Json-Log.txt)
Further details from Message-Queue:
![image](https://user-images.githubusercontent.com/5657002/221942905-d60f27f3-8f20-4bab-8e82-3df52a541e4a.png)
![image](https://user-images.githubusercontent.com/5657002/221943016-9f0c2ce0-3d89-4d7a-a184-b18769c27203.png)

We figured our such possible causing areas of the exception:
- EventPublisher.cs
- ServiceBusFactory.cs

We don't know what we could change - seems like a Bug in Elsa.
Maybe a unsafe handling of the connection? Or a not fetched timeout exception? 
We would need further details to be able to fix this...

**Comment by sfmskywalker** [comment]
Looks like it may be an issue with the lifetime of the service bus being leaked.
I sort of remember working on this many, many months ago, possibly leading to improvements or even a fix in 2.10. Are you able to upgrade to give it a try, even if in a separate environment?

I'm running too in a multi node environment (Azure App Service with 6 nodes) + Azure Service Bus as the service bus, and haven't seen messages in the dead letter queue for anything but consumers throwing exceptions other than object disposed exceptions.

**Comment by Adrian-Grimm** [comment]
OK, we will test 2.10 and give an update if it solves it or not - will take some time.

**Comment by Adrian-Grimm** [comment]
@sfmskywalker We was able to upgrade to version 2.10.2.2 and retested everything. 
Still the same problem.

We would need further details - but can't dig deeper with given logs ...
Maybe a uncatched Exception which causing this? (Rebus transactions?, ..)
Do you have an idea what we could further test?

**Comment by Adrian-Grimm** [comment]
@sfmskywalker 
i forgot to mention that this only get's visible by setting the "Max Delivery Count" to 1:
![image](https://user-images.githubusercontent.com/5657002/223117990-a74e68fa-83ec-4139-a981-db39859b5c31.png)

If this is not set to "1" (default "100") this is hidden as rebus will retry it - but this causes a not safe single one time execution per activity - which is not acceptable for many use cases which needs to rely on a single not repeated execution.

**Comment by Adrian-Grimm** [comment]
Further test results:

With those Environment variables set:
![image](https://user-images.githubusercontent.com/5657002/223173396-faba084c-21e6-4d63-bcd2-c82f957d45f8.png)
Everything is working without Errors in Dead-Letter-Queue.
But Elsa runs damn slow.

 With this: 
 ![image](https://user-images.githubusercontent.com/5657002/223173739-54d0191e-7ca9-485b-9042-c5cd49f0fe6c.png)
Every 5. ends up in Dead-Letter-Queue.

We would aim for at least "10" for both...
