### ISSUE TITLE
Missing npm-install.js at root of directory

### ISSUE THREAD

**Issue by nm4568** [elsa-workflows/elsa-core#377]
Instructions to build and run Elsa states to do the following after cloning:

Run NPM install on all folders containing packages.json (or run `node npm-install.js` - a script in the root that recursively installs the Node packages)

However, there is no such file, 'npm-install.js' located in the root.

**Comment by sfmskywalker** [comment]
Indeed. The documentation should be updated, because installing packages recursively is no longer necessary.

**Comment by sfmskywalker** [comment]
Updated with https://github.com/elsa-workflows/elsa-core/commit/cd1c151c22c0fc088a4c6f13527a9c1053d1985e
