### ISSUE TITLE
Could not load type 'MediatR.ServiceFactory' from assembly 'MediatR, Version=12.0.0.0

### ISSUE THREAD

**Issue by satishviswanathan** [elsa-workflows/elsa-core#3775]
Dotnet 7
Elsa 2.10.2.2

var services = new ServiceCollection();
services.AddElsa(elsa=> elsa.UseEntityFrameworkPersistence(ef=> ef.UsePostgreSql("connectionString");
services.AddElsaApiEndpoints();
services.Configure<BlobStorageWorkflowProviderOptions>(options => options.BlobStorageFactory = () => StorageFactory.Blobs.DirectoryFiles(Path.Combine(currentAssemblyPath, "Workflows")));

_**Error**_
    Could not load type 'MediatR.ServiceFactory' from assembly 'MediatR, Version=12.0.0.0
Error _**Stack**_

 System.TypeLoadException : Could not load type 'MediatR.ServiceFactory' from assembly 'MediatR, Version=12.0.0.0, Culture=neutral, PublicKeyToken=bb9a41a5e8aaa7e2'.

  Stack Trace: 
    ServiceRegistrar.AddRequiredServices(IServiceCollection services, MediatRServiceConfiguration serviceConfiguration)
    ServiceCollectionExtensions.AddMediatR(IServiceCollection services, IEnumerable`1 assemblies, Action`1 configuration)
    ServiceCollectionExtensions.AddMediatR(IServiceCollection services, IEnumerable`1 handlerAssemblyMarkerTypes, Action`1 configuration)
    ServiceCollectionExtensions.AddMediatR(IServiceCollection services, Action`1 configuration, Type[] handlerAssemblyMarkerTypes)
    ElsaServiceCollectionExtensions.AddWorkflowsCore(ElsaOptionsBuilder elsaOptions)
    ElsaServiceCollectionExtensions.AddElsaCore(IServiceCollection services, Action`1 configure)
    ElsaServiceCollectionExtensions.AddElsa(IServiceCollection services, Action`1 configure)
    WorkFlowServiceCollectionExtension.AddWorkFlowEngine(IServiceCollection services, IConfiguration configuration, Action`1 elsaBuilder) line 45
    WorkFlowServiceCollectionExtensionTests.can_service_collection_add_work_flow_engine() line 16
    RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
    MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)

**Comment by deydinov** [comment]
Waiting for nuget with such fix 👍
