### ISSUE TITLE
Variables.Empty mutable

### ISSUE THREAD

**Issue by gztamas** [elsa-workflows/elsa-core#378]
Hi,

maybe this is just my mind working differently, but I found it somewhat confusing that I can get the empty collection of `Variables` with `Variables.Empty`, and I then I can add `Variable` instances to it, potentially breaking code that expected it to be, well, empty.
Wouldn't it make sense to either return a new `Variables` instance every time, or return an instance an instance of something like `public class ImmutableVariables : Variables`?

**Comment by sfmskywalker** [comment]
You're absolutely right, the `Variables.Empty` instance is intended to be immutable.

**Comment by sfmskywalker** [comment]
`Variables` in Elsa 2 no longer has an `Empty` property, so closing issue.
