### ISSUE TITLE
Ambiguous call when a project references Elsa.Core->Elsa.Scrutor and Scrutor 

### ISSUE THREAD

**Issue by elpht** [elsa-workflows/elsa-core#380]
I have a project where I reference Elsa.Core and Scrutor packages and when I try to use Scrutor's extension methods I get the following error:
 
> Error	CS0121	The call is ambiguous between the following methods or properties: 
'Microsoft.Extensions.DependencyInjection.ServiceCollectionExtensions.TryDecorate<TService, TDecorator>(Microsoft.Extensions.DependencyInjection.IServiceCollection)' and 'Microsoft.Extensions.DependencyInjection.ServiceCollectionExtensions.TryDecorate<TService, TDecorator>(Microsoft.Extensions.DependencyInjection.IServiceCollection)'	

I know it can be overcome by giving an alias to any of the libraries involved. But to me this sounds like a workaround in this case, cause Elsa.Core is referencing a branch of Scrutor, shipped as Elsa.Scrutor but keeping the original namespaces and it could also lead one, without realizing, to make use of Elsa.Scrutor when the intention was using original Scrutor.

So I wonder wheter it would be possible to disambiguate between Elsa.Scrutor and Scrutor.

Thank you for your time and your great job with this open source library.

**Comment by sfmskywalker** [comment]
The correct way is to get rid of the Elsa.Scrutor project - it is a fork of Scrutor that does nothing more than making an internal method public, but this is not strictly necessary. Instead, Elsa should be updated to simply build a service collection itself, have it populated with the services it needs, and use that service collection.

Thanks for reporting!

**Comment by sfmskywalker** [comment]
This has been fixed.
