### ISSUE TITLE
Consider Elsa Workflows Studio in Blazor

### ISSUE THREAD

**Issue by GeorgeS2019** [elsa-workflows/elsa-core#3810]
[elsa-workflows-studio](https://github.com/elsa-workflows/elsa-core/tree/master/src/designer/elsa-workflows-studio)

FYI: [Azure Design Studio](https://github.com/chunliu/AzureDesignStudio)

![msedge_dd0BhaHeDS](https://user-images.githubusercontent.com/49812372/226095073-508f673a-7695-4a70-bceb-9683863bcfa6.gif)

**Comment by GeorgeS2019** [comment]
> I would be really nice if the Activity editor could be replaced to use [custom Blazor components.](https://github.com/elsa-workflows/elsa-core/issues/3232#issuecomment-1416306377)

**Comment by GeorgeS2019** [comment]
[What's the current state of elsa visual designer](https://github.com/elsa-workflows/elsa-core/discussions/1597)

**Comment by GeorgeS2019** [comment]
[Embed workflow designer in my application](https://github.com/elsa-workflows/elsa-core/discussions/3268)

**Comment by GeorgeS2019** [comment]
[Embedding designer and dashboard into 3rd party UI](https://github.com/elsa-workflows/elsa-core/discussions/800)

**Comment by sfmskywalker** [comment]
Yes, we want to redo the entire designer in Blazor and wrap it in a web component. This wasn't possible (or at least practical from what I could see) in the past, but today, I hear, it's very much supported.

**Comment by GeorgeS2019** [comment]
@sfmskywalker 

Do follow .NET8 Blazor United, the best low latency web client, perfect for Elsa Worlflows Studio

**Comment by GeorgeS2019** [comment]
[.NET8 Blazor United by Blazor Creator](https://youtu.be/48G_CEGXZZM)

**Comment by jdevillard** [comment]
Hello, 

Using Blazor could be really nice, but I think that no matter what the language/framework is used, the important thing is it HAS to be interoperable with other technology/framework. Web Component Wrapper is a good thing for this, but interaction with the different part of the designer should also be present (for example, loading/saving/publishing should be handle by external component).

I'm currently working on Web Component Wrapper for Angular (but this should be the same then for React, Vue and others) and I'm currently seeing what is missing for interop.

**Comment by GeorgeS2019** [comment]
> (for example, loading/saving/publishing should be handle by external component)
This is .NET project,  loading/saving/publishing should be handle by external component => can be done as FIRST class citizen with .NET using Blazor.

In terms of Web Technology, 

Currently Vue and Blazor (new kid ), then React, then only Angular.   

Interoperability between Blazor and React and Angular are available at Microsoft website.

**Comment by jspitman** [comment]
Another feature of the evolution of the designer could be looking at something like adaptive cards (https://adaptivecards.io) for use with activity extensibility.  It could be a way for a custom activity developer to include designer activity UI as part of the activity assuming new activities can be added without recompilation of a server.

**Comment by sfmskywalker** [comment]
Thank you for all the tips and leads, that is looking potentially very useful.

**Comment by GeorgeS2019** [comment]
https://github.com/elsa-workflows/elsa-core/discussions/3852

WASM and Blazor

**Comment by sfmskywalker** [comment]
@GeorgeS2019 OK if we close this issue ("consider using Blazor")? We considered and and decided to do it 😄

**Comment by sfmskywalker** [comment]
OK, let's leave it open until we have an MVP with Blazor 👍🏻

**Comment by GeorgeS2019** [comment]
# Elsa.Studio.Host.Wasm => Blazor work!!!!

![msedge_YEZIkQaFYo](https://github.com/elsa-workflows/elsa-core/assets/49812372/fb5759e6-a362-48f2-92e4-82122e97c2f2)
