### ISSUE TITLE
Issue with expression evaluation

### ISSUE THREAD

**Issue by lmartinjr** [elsa-workflows/elsa-core#383]
I'm new to Elsa and find the framework to be very robust. I was easily able to get the engine and workflow designer up and running. I was also able to develop a custom activity with an input parameter defined as follows:

public WorkflowExpression<string> FirstName {
            get => GetState(() => new WorkflowExpression<string>(LiteralEvaluator.SyntaxName, ""));
            set => SetState(value);
        }

In this Activity i am setting an output variable as follows:
Output.SetVariable("ProviderOutput", $"Person:{FirstName}");

I've added this activity to the workflow and set the named instance to ProvOut. I've set the FirstName property with a literal value and it's setting the value appropriately when i step through the custom activity.

I've then added the activity into the workflow again to test passing a value from one activity to another. The second activity is passing the FirstName property as follows (the expression type is Liquid):
{{Activities.ProvOut.ProviderOutput}} 

When i attempt to evaluate this i am getting an object reference error from the LiquidExpression evaluator. Here is a snippet of code from the OnExecuteAsync() method:

var firstName = await expressionEvaluator.EvaluateAsync(
                    FirstName, workflowContext, cancellationToken
                );

My services are configured as follows:

services
                .AddElsa(elsa => elsa.AddEntityFrameworkStores<SqliteContext>(options => options.UseSqlite(Configuration.GetConnectionString("Sqlite"))))
                .AddHttpActivities(options => options.Bind(Configuration.GetSection("Elsa:Http")))
                .AddEmailActivities(options => options.Bind(Configuration.GetSection("Elsa:Smtp")))      
                .AddActivity<MapProvider>()
                .AddTimerActivities(options => options.Bind(Configuration.GetSection("Elsa:Timers")))
                .AddElsaDashboard();

This is the error i am receiving:
"Error while evaluating Liquid expression \"{{Activities.ProvOut.ProviderOutput}}\". Message: Object reference not set to an instance of an object."

And here is the stack trace
"   at Elsa.Expressions.WorkflowExpressionEvaluator.<EvaluateAsync>d__3.MoveNext()\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\n   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()\n   at Elsa.Extensions.WorkflowExpressionEvaluatorExtensions.<EvaluateAsync>d__0`1.MoveNext()\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\n   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()\n   at ElsaCustomActivities.MapProvider.<OnExecuteAsync>d__6.MoveNext() in /Users/larrymartin/Projects/ElsaTest/ElsaCustomActivities/Class1.cs:line 42"

**Comment by lmartinjr** [comment]
This might be the same as issue 341. I’ll download the source and step through.

**Comment by lmartinjr** [comment]
The multiple Name properties on the activity object was the issue and once i modified the JSON to have only one Name property (the uppercase one) the workflow invoker engine properly parsed the object and returned the output parameter. i'll look for the code in the designer that is resulting in multiple name properties being generated.

**Comment by sfmskywalker** [comment]
Nice find. Thank you for looking into this!

**Comment by lmartinjr** [comment]
> Nice find. Thank you for looking into this!

No problem. I'm having a hard time getting my dev environment set up to debug the Elsa.Dashboard project. When i add the project references directly to a web site solution i can't get the activities button to work. Do you have any tips to set up a dev environment properly to debug this?

**Comment by lmartinjr** [comment]
Would love to help with this but i am really struggling here to get a dev environment set up. The error i am getting in the browser console is:

Failed to load module script: The server responded with a non-JavaScript MIME type of "text/html". Strict MIME type checking is enforced for module scripts per HTML spec.
http://localhost:59003/_content/Elsa.Dashboard/assets/js/plugins/elsa-workflows/elsa-workflow-designer/elsa-workflow-designer.esm.js

If i add the nuget package for elsa-dashboard it works fine but then i cant step through the code for elsa-dashboard.

I think i see the problem in the code. i think the model is missing the "Name" property so automapper isn't binding it during persistence. Any tips you can give me to make this work without adding the elsa-dashboard nuget package?

**Comment by sfmskywalker** [comment]
Can you check the F12 Developer Tools and see what the actual HTTP response is when requesting http://localhost:59003/_content/Elsa.Dashboard/assets/js/plugins/elsa-workflows/elsa-workflow-designer/elsa-workflow-designer.esm.js? Possibly you are getting a 404. In which case: make sure to follow these steps to build the client-side assets:

1. Run NPM install on `src\dashboard\Elsa.Dashboard\Theme\argon-dashboard`
1. Execute gulp build from the directory `src\dashboard\Elsa.Dashboard\Theme\argon-dashboard`

Let me know if this works or not.

**Comment by lmartinjr** [comment]
> Can you check the F12 Developer Tools and see what the actual HTTP response is when requesting http://localhost:59003/_content/Elsa.Dashboard/assets/js/plugins/elsa-workflows/elsa-workflow-designer/elsa-workflow-designer.esm.js? Possibly you are getting a 404. In which case: make sure to follow these steps to build the client-side assets:
> 
> 1. Run NPM install on `src\dashboard\Elsa.Dashboard\Theme\argon-dashboard`
> 2. Execute gulp build from the directory `src\dashboard\Elsa.Dashboard\Theme\argon-dashboard`
> 
> Let me know if this works or not.

Thanks! That's exactly what i needed. I now have a dev environment set up and i'm able to step through the code.

**Comment by lmartinjr** [comment]
> Can you check the F12 Developer Tools and see what the actual HTTP response is when requesting http://localhost:59003/_content/Elsa.Dashboard/assets/js/plugins/elsa-workflows/elsa-workflow-designer/elsa-workflow-designer.esm.js? Possibly you are getting a 404. In which case: make sure to follow these steps to build the client-side assets:
> 
> 1. Run NPM install on `src\dashboard\Elsa.Dashboard\Theme\argon-dashboard`
> 2. Execute gulp build from the directory `src\dashboard\Elsa.Dashboard\Theme\argon-dashboard`
> 
> Let me know if this works or not.

Hey there. i have the fix ready. it's a very simple change to Elsa.Abstractions.Models.ActivityDefinition by changing the getters and setters on the Name property to look for the value in state with a lowercased version of name (due to JSON serialization). can i get access to push a remote repo and submit a pull requst?

**Comment by lmartinjr** [comment]
> > Can you check the F12 Developer Tools and see what the actual HTTP response is when requesting http://localhost:59003/_content/Elsa.Dashboard/assets/js/plugins/elsa-workflows/elsa-workflow-designer/elsa-workflow-designer.esm.js? Possibly you are getting a 404. In which case: make sure to follow these steps to build the client-side assets:
> > 
> > 1. Run NPM install on `src\dashboard\Elsa.Dashboard\Theme\argon-dashboard`
> > 2. Execute gulp build from the directory `src\dashboard\Elsa.Dashboard\Theme\argon-dashboard`
> > 
> > Let me know if this works or not.
> 
> Thanks! That's exactly what i needed. I now have a dev environment set up and i'm able to step through the code.

I'm trying to push a remote brach consisting of the code fix. is there anything that i need to do in order to get permissions for this?

**Comment by sfmskywalker** [comment]
They way to do this is by creating a fork of this project and cloning that fork to your local machine (or update your local clone of this repo with the remote URL of the fork you will create), push your changes to your fork, and submit a PR.

[This article](https://opensource.com/article/19/7/create-pull-request-github) explains the steps nicely.

**Comment by lmartinjr** [comment]
> They way to do this is by creating a fork of this project and cloning that fork to your local machine (or update your local clone of this repo with the remote URL of the fork you will create), push your changes to your fork, and submit a PR.
> 
> [This article](https://opensource.com/article/19/7/create-pull-request-github) explains the steps nicely.

Thanks Spike. I've now submitted a PR for review. I was able to confirm the code change worked as expected by creating an activity and assigning a name. I then checked the database (was using EF as persistence) and could confirm after making the change the Name column in the datastore was set. For testing i was using EF and SQLLite.
