### ISSUE TITLE
Using a Kafka activity is causing duplicated WorkFlowTrigger instance

### ISSUE THREAD

**Issue by dao74** [elsa-workflows/elsa-core#3832]
I have added a Kafka activity into a flow and saw that the flow is running twice.

Checking of the Triggers table: the records related to the Kafka activity were duplicated.

After debug I found out the duplication was caused in the _Elsa.Services.Triggers.TriggersForActivityBlueprintAndWorkflowProvider. **GetTriggersForActivityBlueprintAsync_** method.

supportedBookmarkProviders = 
Elsa.Activities.Kafka.Bookmarks.OverrideKafkaBookmarkProvider,
Elsa.Activities.Kafka.Bookmarks.QueueMessageReceivedBookmarkProvider

GetTriggersForBookmarkProvider is returning 2 items WorkflowTrigger with identical values (ActivityType=KafkaMessageReceived)

Please check and advise.

**Comment by sfmskywalker** [comment]
@Snotax Maybe you experienced this as well?

**Comment by sfmskywalker** [comment]
Perfect, thank you!

**Comment by sfmskywalker** [comment]
@dao74 This should be fixed now with the preview build (https://github.com/elsa-workflows/elsa-core/actions/runs/4530401599) with to the PR from @Snotax

**Comment by dao74** [comment]
Seems working, thank you.
