### ISSUE TITLE
System.ObjectDisposedException occured in Elsa.Activities.Kafka module

### ISSUE THREAD

**Issue by dao74** [elsa-workflows/elsa-core#3838]
After multi node tests we faced an issued regarding Kafka - error is below (error is recurring in endless loop):

**First Exception:**
`Error on consuming: System.ObjectDisposedException: handle is destroyed    at Confluent.Kafka.Impl.SafeKafkaHandle.ThrowIfHandleClosed()    at Confluent.Kafka.Impl.SafeKafkaHandle.ConsumerPoll(IntPtr millisecondsTimeout)    at Confluent.Kafka.Consumer`2.Consume(Int32 millisecondsTimeout)    at Confluent.Kafka.Consumer`2.Consume(CancellationToken cancellationToken)    at Elsa.Activities.Kafka.Helpers.Consumer.<>c__DisplayClass0_1`2.<Consume>b__1() in C:\Temp\elsa-core-061ce5e518fbbcbe3db0ab85ba7c7342f948b5f1\src\activities\Elsa.Activities.Kafka\Helpers\Consumer.cs:line 25`

**Consecutive Exceptions:**
`Error on consuming: System.ObjectDisposedException: handle is destroyed
   at Confluent.Kafka.Impl.SafeKafkaHandle.ThrowIfHandleClosed()
   at Confluent.Kafka.Impl.SafeKafkaHandle.Unsubscribe()
   at Elsa.Activities.Kafka.Services.Client.Dispose() in C:\Temp\elsa-core-061ce5e518fbbcbe3db0ab85ba7c7342f948b5f1\src\activities\Elsa.Activities.Kafka\Services\Client.cs:line 70`

BTW, important note:
The error log is not detailed because the stacktrace is not included in the logging statement like below:
`_logger.LogError("Error on consuming");`

**Comment by Snotax** [comment]
@dao74 The endless loop should be fixed in master. But the original problem is still there. I didn't find it yet.
