### ISSUE TITLE
Cannot see SetVariable in Designer

### ISSUE THREAD

**Issue by rfrcarvalho** [elsa-workflows/elsa-core#384]
Hi.

I'm using ASP.NET Zero which is the paid version of ABP so I'm using the source code that was posted in githib for this and almost everything is working except for a small thing.

I integrated Elsa.Dashboard and Elsa.WorkflowDesigner projects in my source code (while I'm waiting for v2.0) to be able to put my authorizations in place and I get the remaining Elsa packages from Nuget. 

I'm registering the Elsa services in my Startup.cs like below:

```
services
     .AddElsa(elsa => elsa.AddEntityFrameworkStores<SqliteContext>(options => options.UseSqlServer(_appConfiguration.GetConnectionString("Default"))))                
     .AddHttpActivities(options => options.Bind(_appConfiguration.GetSection("Elsa:Http")))
     .AddEmailActivities(options => options.Bind(_appConfiguration.GetSection("Elsa:Smtp")))
     .AddTimerActivities(options => options.Bind(_appConfiguration.GetSection("Elsa:Timers")))
     .AddConsoleActivities()
     .AddWorkflowActivities()
     .AddDropboxActivities()
     .AddUserTaskActivities()
     .AddControlFlowActivities()
     .AddReflectionActivities()
                
     .AddElsaDashboard();

```

Everything works fine, except that I don't see the SetVariable activity in my designer but I see all others.

Can someone help me?

**Comment by 463728946** [comment]
every activity can set variable

**Comment by rfrcarvalho** [comment]
The problem is that in the designer, when I select Add Activity, it shows If/Else,..., Request Http, Send Http, ... all of the available activities, except "Set Variable".

**Comment by sfmskywalker** [comment]
Make sure to also do `.AddPrimitiveActivities`.

**Comment by sfmskywalker** [comment]
FYI, this entire story of registering activities with the designer will be improved with Elsa 2, which simply uses an API endpoint from the workflow host to query available activities.

**Comment by rfrcarvalho** [comment]
It says it's private...

![image](https://user-images.githubusercontent.com/4267071/94601801-e9bb2d80-028b-11eb-8705-bf5d00dcf8bd.png)

**Comment by sfmskywalker** [comment]
This should have been fixed. Please feel free to reopen if otherwise.
