### ISSUE TITLE
Reprocess Faulted Instance in V3

### ISSUE THREAD

**Issue by sagargolu** [elsa-workflows/elsa-core#3880]
@sfmskywalker , Do we have way to restart faulted workflow instance from where it's faulted?

**Comment by sfmskywalker** [comment]
For Elsa 2, there should be a Bulk action to retry the selected faulted workflow instances, which will retry the faulted activity.
For Elsa 3, there is currently no such feature implemented yet.

**Comment by sfmskywalker** [comment]
Just created an issue for Elsa 3 here: https://github.com/elsa-workflows/elsa-core/issues/3882
