### ISSUE TITLE
Back button in completed workflow Instance page throw an error if workflow deployed under the IIS Default Web Site  

### ISSUE THREAD

**Issue by jayachandra21** [elsa-workflows/elsa-core#389]
Hi,

I have deployed the Elsa workflow in IIS server under the **"Default Web Site"**  section.
So in this case when I click on the **Back** button in any of Finished workflow instance, getting the following error.

![image](https://user-images.githubusercontent.com/67507118/94734469-f44ff280-0371-11eb-952c-47b6a8d7a0e4.png)

Error while click on Back button:
![image](https://user-images.githubusercontent.com/67507118/94734602-22cdcd80-0372-11eb-9cf5-73c0a5697091.png)

**Comment by sfmskywalker** [comment]
Is the website served directly on the root of the domain, or from a virtual directory?

**Comment by jayachandra21** [comment]
> Is the website served directly on the root of the domain, or from a virtual directory?

1)  Created a "Add Application" under the "Default Web Site" in IIS as below
![image](https://user-images.githubusercontent.com/67507118/94905424-873d7980-04a5-11eb-8a26-56198ee30905.png)
2) Then Run the Elsa Website portal, in this case getting the above issue.

**Comment by sfmskywalker** [comment]
When clicking the Back button, what URL is displayed when you receive the 404?

**Comment by jayachandra21** [comment]
> When clicking the Back button, what URL is displayed when you receive the 404?

following URL is displayed when receive the 404  as,
**https://serverName:80/Elsa/workflow-instance?definitionId=598e0149d4a44e7d9d970630a2a8fd7c&status=Finished**

**Comment by sfmskywalker** [comment]
I see. When adding an application like that, you are creating a virtual directory. Let's say you call this application "ElsaApp" and launch the website, the dashboard URL is: http://localhost/ElsaApp/Elsa/Home
But when generating the Back link, I'm not taking into account any virtual directory, which means it points to http://localhost/Elsa/Home (notice the missing "ElsaApp" at the root).

Doing a quick Google search yielded [this SO](https://stackoverflow.com/questions/15003499/url-action-for-mvc3-application-hosted-in-a-sub-directory) post, where they basically say that if it is deployed correctly, URL generation shouldn't be an issue.

The question then is: how does one properly configure the application under an vdir in IIS such that URL generation (which is what is done when generation the link of the Back button)?

I'm no IIS expert, but perhaps you can pursue this further?
