### ISSUE TITLE
OnCanExecute method is not triggered,Did I miss something？

### ISSUE THREAD

**Issue by 463728946** [elsa-workflows/elsa-core#390]
public class ApproverActivity : Activity
       {

        public AuthorizationExpression AuthorizationExpression
        {
            get => GetState<AuthorizationExpression>();
            set => SetState(value);
        }

        protected override Task<bool> OnCanExecuteAsync(WorkflowExecutionContext context, CancellationToken cancellationToken)
        {
            //when i demo it's working,but using my project is not triggered
        }

        protected override bool OnCanExecute(WorkflowExecutionContext context)
        {
            //when i demo it's working,but using my project is not triggered
        }

        protected override async Task<ActivityExecutionResult> OnExecuteAsync(WorkflowExecutionContext context, CancellationToken cancellationToken)
        {
            //This method is away Ok
        }

        protected override async Task<ActivityExecutionResult> OnResumeAsync(WorkflowExecutionContext context, CancellationToken cancellationToken)
        {
            //when i demo it's working,but using my project is not triggered
        }

    }
`

**Comment by amrlafi** [comment]
I have the same issue. Did you manage to resolve it?

**Comment by sfmskywalker** [comment]
@amrlafi Do you have repro steps that I can try?

**Comment by sfmskywalker** [comment]
I haven't been able to reproduce this in Elsa 2, so closing this out. Feel free to reopen if you are still having issues. Thanks!
