### ISSUE TITLE
Error : 'Unable to cast object of type 'Elsa.Persistence.MongoDb.Serializers.ObjectSerializer' to type 'MongoDB.Bson.Serialization.Serializers.ObjectSerializer'.'

### ISSUE THREAD

**Issue by zesmaili** [elsa-workflows/elsa-core#3912]
Hello
I tried to create an Elsa workflow like the following address:

But instead of using "SQLite" database, I used "Mongo". When loading "Workflow Definitions", I keep getting the following error :

'Unable to cast object of type 'Elsa.Persistence.MongoDb.Serializers.ObjectSerializer' to type 'MongoDB.Bson.Serialization.Serializers.ObjectSerializer'.'

Can you help me find the fault?

Thank you

**Comment by mgochmuradov** [comment]
Hello, I have the same problem using Elsa on MongoDB
@zesmaili  Have you figured out a way to fix (workaround) it?
