### ISSUE TITLE
Unable to server-url binding in elsa-studio-root on Angular 

### ISSUE THREAD

**Issue by uyarbtrlp** [elsa-workflows/elsa-core#3919]
Hello,

I've been using the version 2.10.2 of @elsa-workflows/elsa-workflows-studio, and I want to pass the server-url value to the component rather than giving the static string value. 
Here is the html file
![image](https://user-images.githubusercontent.com/59877078/232539697-02ae0bcc-2208-4d8b-83c6-0c60ede9814d.png)
Here is the ts file
![image](https://user-images.githubusercontent.com/59877078/232539937-c0cc84f5-8ab8-4492-bf17-96127ddea267.png)
When I look into the detail, I see that the serverUrl is undefined.
![image](https://user-images.githubusercontent.com/59877078/232540261-46c745c0-d1d5-4339-b750-41bd7af9707b.png)
When I use the value as static string on html, I see the component without any problems.

What should I do to pass the serverUrl into the component?

**Comment by sfmskywalker** [comment]
Summoning @jdevillard

**Comment by jdevillard** [comment]
Hello ! 

Have you tried this for binding ? [server-url]="hostUrl" instead of using {{}}.

I have a working sample if needed but I'm not on the computer right now

**Comment by uyarbtrlp** [comment]
Hello,

Yes, I have tried. Same result. It seems that I have this problem regardless of using {{}} or []. If you could provide a working solution, I would appreciate it.

Thanks.

**Comment by jdevillard** [comment]
Hello, 

you can take a look at the following repo : 
https://github.com/jdevillard/ElsaWorkflowDashboard-Angular

We have to use the camel case usage to define the component property (don't ask me why, I didn't retrieve documentation on this, I just remember...), so you have to write : 

```
 <div>
    <elsa-studio-root #elsaStudioRoot [serverUrl]="url" monaco-lib-path="assets/monaco">
      <elsa-studio-dashboard></elsa-studio-dashboard>
    </elsa-studio-root>
  </div>
```

The property [serverUrl] is used to bind the server-url property of your custom component. 
In the same time monaco-lib-path should be replace by [monacoLibPath].

and in your controller, you can define your url property : 
```
  url="https://localhost:11000";
```

a second method is to use the AfterInitView base inheritance and use a Ref to the component using the HashTag.
```
 <div>
    <elsa-studio-root #elsaStudioRoot [serverUrl]="url" monaco-lib-path="assets/monaco">
      <elsa-studio-dashboard></elsa-studio-dashboard>
    </elsa-studio-root>
  </div>
```

here I've added the **#elsaStudioRoot** [reference tag](https://angular.io/api/core/TemplateRef).

Then in the controller, I defined a property link to this ref : 
```
 @ViewChild('elsaStudioRoot', { static: true }) elsaStudioRootRef!: ElementRef;
```

Then using the method `ngAfterViewInit()`, we can define the attribute of our component : 

```
  ngAfterViewInit(): void {
    //Try remove the [serverUrl]="url" to use this initialization Method
    this.elsaStudioRootRef.nativeElement.setAttribute('server-url', this.url);
  }
```

The two method are written in the sample repo linked above !

HTH
