### ISSUE TITLE
when muliple outcomes workflow instance keeps status running

### ISSUE THREAD

**Issue by herblinernexxbizz** [elsa-workflows/elsa-core#3925]
When an activity has multiple outcomes and on the outcomes there are continuation activities, after choosing one path in the instance
it keeps status on running (probably because the activities in the other oucomes where not run).

[flow-multiple-paths-workflow-keeps-running.txt](https://github.com/elsa-workflows/elsa-core/files/11262087/flow-multiple-paths-workflow-keeps-running.txt)

**Comment by sfmskywalker** [comment]
Fixed via #3928
