### ISSUE TITLE
The workflow designer doesn't show Input DefaultValue v3

### ISSUE THREAD

**Issue by truthz03** [elsa-workflows/elsa-core#3927]
Hi,

I'm currently try to get v3 working but I have some problems and I don't know if it is a bug or not finished yet.
I have checked out your source code to get all fixes and updates.
The described problem was tested with the commit: https://github.com/elsa-workflows/elsa-core/commit/be7cee71662a97597995f8c09db888a4a804028b

The problem is that I defined Inputs inside my custom activity with default values but these values will not be shown.
I tried it with the "DefaultValue" property, setting the Input property directly and both:
![image](https://user-images.githubusercontent.com/14071920/232792151-1cb5423d-5f9a-46c8-827f-3ec4a2013fd1.png)

What is the preferred way???

At the first look it seems that setting a value to the input property is working because this is how it looks after adding the activity:
![image](https://user-images.githubusercontent.com/14071920/232793520-5b542634-7b85-43b1-bf9a-58a108950116.png)

But after adding a second activity (doesn't matter what) it looks like this:
![image](https://user-images.githubusercontent.com/14071920/232793693-bc5410f3-b397-45ab-8f46-5d5228ef3ded.png)

**Comment by sfmskywalker** [comment]
The preferred way to set a default input value is to do it via the `Input` attribute, because that simplifies transferring it to the designer.

It would appear, however, that this feature isn't fully developed, or at least has a bug that causes the input fields to remain blank.

**Comment by sfmskywalker** [comment]
Fixed as of 7d713d81a3e22bf2428e17ba9bccf497333a7830
