### ISSUE TITLE
When Workflow Faulted, and called through HttpEndpointActivity, status code is OK 200

### ISSUE THREAD

**Issue by j03y-nxxbz** [elsa-workflows/elsa-core#3936]
When calling workflows through HttpEndpoint Activities, and when faulting (try generating an error in JavaScript for example), a 200 OK status code is returned, without any body. 

Sometimes, we have noticed, that when debugging the application locally, and stepping through a custom activity, then suddenly the Elsa .NET exception does appear in the response in Postman. But in any other case when hitting the SEND button in Postman and waiting for an error response will yield an empty 200 response instead,

**Comment by sfmskywalker** [comment]
Fixed via #3937
