### ISSUE TITLE
HttpEndpointMiddleware.cs  Error

### ISSUE THREAD

**Issue by zuohuaijun** [elsa-workflows/elsa-core#3954]
![图片](https://user-images.githubusercontent.com/5865800/234354057-2fdc084e-9977-4313-b69c-f2b2b7d3047e.png)

![图片](https://user-images.githubusercontent.com/5865800/234359874-c5b2f59f-c770-4391-9d74-f3aa176218dc.png)

**Comment by sfmskywalker** [comment]
Can you send a full repro? Perhaps you can send your solution (or a simplified version thereof) so we can investigate? 

One thing I noticed was a reference to Versioning, but I can’t be sure because you did not provide your full Program.cs.
