### ISSUE TITLE
Transition from one activity to the next for various outcomes

### ISSUE THREAD

**Issue by gztamas** [elsa-workflows/elsa-core#396]
In some workflows we want to handle different outcomes of the same activity the same way. For example, we try to do cleanup after some timeout passed, or immediately if the user pressed a button on the screen. It seems that in the designer we cannot drag two outcome bullets of one activity to a single next activity. Well, actually, we can, but afterwards as we keep working with the designer the previous transition disappears and only the latest one remains. Is this by design, a limitiation, or just some unintended behavior?

![image](https://user-images.githubusercontent.com/14156012/95081799-60d44400-071a-11eb-8b33-1e4e00d2b0a5.png)

(In the screenshots the second activity is a join, but that's just because I tried with different activities. I realize the join is not for this and did not intend to use it actually. :) )

**Comment by sfmskywalker** [comment]
That looks like a designer bug; it is a normal use case to connect two outcomes to a single activity like in your example.

**Comment by sfmskywalker** [comment]
No longer an issue as of Elsa 2.
