### ISSUE TITLE
The Elsa.Workflows.Designer v3 preview package contains a buggy designer version

### ISSUE THREAD

**Issue by truthz03** [elsa-workflows/elsa-core#3965]
Today I found the Elsa v3 preview Nuget feed: https://f.feedz.io/elsa-workflows/elsa-3/nuget/index.json
I'm now using this instead of compiling the Elsa source code myself.

I also use the Elsa.Workflows.Designer package which contains:
_content/Elsa.Workflows.Designer/elsa-workflows-designer/elsa-workflows-designer.css
_content/Elsa.Workflows.Designer/monaco-editor/min/vs/loader.js
_content/Elsa.Workflows.Designer/elsa-workflows-designer/elsa-workflows-designer.esm.js

but with version 3.0.0-preview.232 all activities will be very long:
![image](https://user-images.githubusercontent.com/14071920/234793003-3a174453-fb67-49a0-baf8-8765dec4e715.png)

with all versions above 3.0.0-preview.232 the activities length is ok but the settings section at the bottom ist empty now:
![image](https://user-images.githubusercontent.com/14071920/234793854-3dd21ece-a5c1-40f1-8948-8bb888c7944a.png)

**Comment by truthz03** [comment]
Sorry this was my fault. It was a problem with css styling

**Comment by sfmskywalker** [comment]
No worries, good to see you got it working 😄
