### ISSUE TITLE
Port "ConsiderValuesAsOutcomes" functionality from Elsa 2

### ISSUE THREAD

**Issue by sfmskywalker** [elsa-workflows/elsa-core#3973]
In Elsa 2, we have a very convenient feature that simplifies adding support for dynamic outcomes to activities.

For example, let's consider the `SendHttpRequest` activity. Here, the user can provide a list of possible HTTP status codes they want to handle.

In Elsa 3, this list is implemented as a simple property of type `Input<ICollection<string>>`.  There is a designer plugin that takes this list of values that the user entered, and dynamically provides activity outcomes mapped to this list.

Because this is such a common pattern, we can provide it asa reusable feature, where the activity developer no longer has to write a designer plugin to support dynamic outcomes.

Instead, they can simply annotate the input property with some attribute (or an option on the existing InputAttribute like in Elsa 2).
This setting is then passed to the designer, from where it does the rest.

**Comment by Nokecy** [comment]
@sfmskywalker  in elsa3.0  How to implement this feature

**Comment by sfmskywalker** [comment]
Hi @Nokecy ! From the activity class' point of view, it will probably look similar to the way it's done in Elsa 2. But, from the Elsa Studio's perspective, which is done in Blazor, it will of course be different from what was done in Stencil. It's hard for me to explain how to implement in this issue at this moment, because haven't delved into the details yet. But if you're interested in picking this one up, just say the word and it's yours!

**Comment by Nokecy** [comment]
How much do I need to pay and what is the payment plan ? @sfmskywalker

**Comment by Sverre-W** [comment]
It might also be nice to have the option to choose whether these outcomes are ports or are connections in on a flow node.

**Comment by sfmskywalker** [comment]
@Nokecy Do you mean how much you need to pay me to get this prioritized to implement?

@Sverre-W Good idea! 👍🏻

**Comment by sfmskywalker** [comment]
Elsa 3 supports this via the `"dynamic-outcomes"` UI hint. This is currently used by both `RunJavaScript` and `FlowSendHttpRequest` activities.
