### ISSUE TITLE
Mongo persistence Serializer cast issue on .net Core 6 (Elsa dashboard)

### ISSUE THREAD

**Issue by machocr** [elsa-workflows/elsa-core#3975]
I'm getting the following exception when navigating through the dashboard and trying to create a new workflow.

**program.cs**
---------------------
var migrationOptions = new MongoMigrationOptions
{
    MigrationStrategy = new DropMongoMigrationStrategy(),
    BackupStrategy = new CollectionMongoBackupStrategy()
};

builder.Services.AddElsa(options =>
options
    .UseMongoDbPersistence(mongo => mongo.ConnectionString = "mongodb://localhost:27017/WorkflowDB")
    .AddHttpActivities()
    .UseRabbitMq("amqp://guest:guest@localhost:5672")
    .AddHangfireTemporalActivities(hangfire => hangfire.UseMongoStorage("mongodb://localhost:27017/HangfireDB", 
    new MongoStorageOptions { MigrationOptions = migrationOptions, CheckConnection = false }))
).AddElsaApiEndpoints();
---------------------
it works fine if I remove the UseMongoDbPersistence section

**Exception**
InvalidCastException: **Unable to cast object of type 'Elsa.Persistence.MongoDb.Serializers.ObjectSerializer' to type 'MongoDB.Bson.Serialization.Serializers.ObjectSerializer'.**
MongoDB.Bson.Serialization.Serializers.DiscriminatedInterfaceSerializer<TInterface>..ctor(IDiscriminatorConvention discriminatorConvention, IBsonSerializer<TInterface> interfaceSerializer)

**Trace**
TargetInvocationException: Exception has been thrown by the target of an invocation.
System.RuntimeMethodHandle.InvokeMethod(object target, ref Span<object> arguments, Signature sig, bool constructor, bool wrapExceptions)
System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, object[] parameters, CultureInfo culture)
MongoDB.Bson.Serialization.BsonSerializationProviderBase.CreateSerializer(Type serializerType, IBsonSerializerRegistry serializerRegistry)
MongoDB.Bson.Serialization.BsonSerializerRegistry.CreateSerializer(Type type)
System.Collections.Concurrent.ConcurrentDictionary<TKey, TValue>.GetOrAdd(TKey key, Func<TKey, TValue> valueFactory)
MongoDB.Driver.Linq.Linq3Implementation.Serializers.KnownSerializers.KnownSerializersRegistry.GetSerializer(Expression expression, Type type, IBsonSerializer defaultSerializer)
MongoDB.Driver.Linq.Linq3Implementation.Serializers.KnownSerializers.KnownSerializerFinder.VisitMember(MemberExpression node)
System.Linq.Expressions.MemberExpression.Accept(ExpressionVisitor visitor)
MongoDB.Driver.Linq.Linq3Implementation.Serializers.KnownSerializers.KnownSerializerFinder.Visit(Expression node)
System.Linq.Expressions.ExpressionVisitor.VisitBinary(BinaryExpression node)
System.Linq.Expressions.BinaryExpression.Accept(ExpressionVisitor visitor)
....

**Comment by sfmskywalker** [comment]
It looks like this is the same issue as #4000. Since there's a PR associated with that issue, I'll close this one (even though you reported it first - thanks for that!)

**Comment by alkampfergit** [comment]
I can add another info about the issue, I've opened a bug in C# mongodb provider with a repro, the team will investigate the issue and hopefully we can use LINQ3 provider without any problem.

**Comment by sfmskywalker** [comment]
Sweet!
