### ISSUE TITLE
Not able to create an identity application in Elsa 3

### ISSUE THREAD

**Issue by MariusVuscanNx** [elsa-workflows/elsa-core#3987]
I ran into an issue while trying to create an identity application. According to the documentation, you can create an application without providing a token if you run the application locally.

I kept getting 403 Forbidden no matter what I tried. A few things that I tried:
- Call the endpoint without a token
- Call with a token of an admin application
- Call with a token of an admin user
- Call without a token having no application defined (db and settings)

I only managed to do my thing by bypassing the perimisions:
```
Post("/identity/applications");
//Permissions("create:application");
Policies(IdentityPolicyNames.SecurityRoot);
```

**Comment by sfmskywalker** [comment]
Fixed as of e12a57b83ae900be4ec59b53fda9c8dc3633d0ac
