### ISSUE TITLE
v3 mysql support

### ISSUE THREAD

**Issue by woola168** [elsa-workflows/elsa-core#3996]
Is theare any chance 3.0 will support mysql?
Because I just check the preview version of 3.0 , there's no EntityFrameworkCore.MySql
or did I missed something?

And also asking if i can disable auth for 3.0?

**Comment by sfmskywalker** [comment]
We’ll add it before RC. By the way, v3 uses EF core, so even if we don’t provide migrations, you can always generate your own by following the same pattern.

**Comment by sfmskywalker** [comment]
> And also asking if i can disable auth for 3.0?

Yes you can disable it for the API endpoints. If you look at the base class for one of them, you’ll notice there’s a check against a static property that you can set to `false` to disable security.

**Comment by woola168** [comment]
> > And also asking if i can disable auth for 3.0?
> 
> Yes you can disable it for the API endpoints. If you look at the base class for one of them, you’ll notice there’s a check against a static property that you can set to `false` to disable security.

sorry for the mistake , I mean the UseIdentity , not the API endpoints

**Comment by sfmskywalker** [comment]
Sure, the Identity module is entirely optional and offered only for users to get started quickly. But it is recommended you use an identity solution of your choice.

**Comment by Gambitier** [comment]
@sfmskywalker I have created PR for this issue, can you please review https://github.com/elsa-workflows/elsa-core/pull/4047

Also, can you please explain how generate migrations, without using Elsa.EntityFrameworkCore.MySql

> By the way, v3 uses EF core, so even if we don’t provide migrations, you can always generate your own by following the same pattern.

**Comment by sfmskywalker** [comment]
Thanks again for your PR @Gambitier !

> Also, can you please explain how to generate migrations, without using Elsa.EntityFrameworkCore.MySql

Yes, basically just copy one of the `Elsa.EntityFrameworkCore.*` projects, such as `Elsa.EntityFrameworkCore.MySql`. The key is that you need to provide a design time factory for the DB context for which you want to generate migrations.
Once you have that, simply use the CLI from the project directory of the project you just created, e.g.:

```bash
dotnet ef migrations add Initial -c RuntimeElsabContext
```
