### ISSUE TITLE
Exception using BlobStorage - the process blocks no more workflow execution

### ISSUE THREAD

**Issue by alkampfergit** [elsa-workflows/elsa-core#3999]
We enabled file system blob storage because for big workflow storing into mongo database has some problems due to how the query is performed. We enabled the blob storage with this code.

```csharp
            if (!string.IsNullOrWhiteSpace(blobFolder))
            {
                services.Configure<BlobStorageWorkflowProviderOptions>(options =>
                    options.BlobStorageFactory = () => StorageFactory.Blobs.DirectoryFiles(Path.Combine(Environment.ContentRootPath, "Workflows")));

                services.Configure<BlobStorageWorkflowStorageProviderOptions>(options =>
                {
                    options.BlobStorageFactory = () => StorageFactory.Blobs.DirectoryFiles(blobFolder);
                });
            }

...


                if (!String.IsNullOrEmpty(blobFolder))
                {
                    elsa.UseDefaultWorkflowStorageProvider<BlobStorageWorkflowStorageProvider>();
                }

```

It seems to works perfectly unless one customer this morning told us that the production server was blocked no more workflow is executed. We had to restart the process and we found this error in the log.

```
System.AggregateException: 5 unhandled exceptions (Operations that change non-concurrent collections must have exclusive access. A concurrent update was performed on this collection and corrupted its state. The collection's state is no longer correct.) (Operations that change non-concurrent collections must have exclusive access. A concurrent update was performed on this collection and corrupted its state. The collection's state is no longer correct.) (Operations that change non-concurrent collections must have exclusive access. A concurrent update was performed on this collection and corrupted its state. The collection's state is no longer correct.) (Operations that change non-concurrent collections must have exclusive access. A concurrent update was performed on this collection and corrupted its state. The collection's state is no longer correct.) (Operations that change non-concurrent collections must have exclusive access. A concurrent update was performed on this collection and corrupted its state. The collection's state is no longer correct.)
---> System.InvalidOperationException: Operations that change non-concurrent collections must have exclusive access. A concurrent update was performed on this collection and corrupted its state. The collection's state is no longer correct.
at System.Collections.Generic.Dictionary`2.TryInsert(TKey key, TValue value, InsertionBehavior behavior)
at Storage.Net.Blobs.InMemoryBlobStorage.AddVirtualFolderHierarchy(Blob fileBlob)
at Storage.Net.Blobs.InMemoryBlobStorage.Write(String fullPath, Stream sourceStream)
at Storage.Net.Blobs.InMemoryBlobStorage.WriteAsync(String fullPath, Stream sourceStream, Boolean append, CancellationToken cancellationToken)
at Storage.Net.Blobs.BlobStorageExtensions.WriteAsync(IBlobStorage provider, String fullPath, Byte[] data, Boolean append, CancellationToken cancellationToken)
at Elsa.Providers.WorkflowStorage.BlobStorageWorkflowStorageProvider.SaveAsync(WorkflowStorageContext context, String key, Object value, CancellationToken cancellationToken)
```

Two are the things that are not working, first the InMemory implementation of Storage.Net.Blobs.InMemoryBlobStorage seems to be bugged, it try to access a dictionary for multiple thread and then it become  unusable until you restart the process. The second is }}how it is possible that the InMemory instance is used?**

Actually we verified and the folder we configured for blob storage is full of data until the error that happened yesterday night, after restarting the server workflow restarted to be executed and the blob folder contains correct data. So how it is possible that the BlobStorageWorkflowStorageProvider started using the in memory yesterday after 3 days of working without an hiccup?

We are using version 2.9 of elsa (we cannot upgrade to latest version due to problem in mongodb driver). We were not able to reproduce the problem but we disabled blob storage on disk due to the fear of customer being blocked again.

Thanks.

**Comment by sfmskywalker** [comment]
> how it is possible that the InMemory instance is used

That is indeed a good question. What happens if you remove the conditional logic that configures the `BlobStorageFactory` and simply use it *always*?

There's no conditional logic in Elsa that determines what blob storage provider to use, so I think we can rule out any bugs there (at least, this seems quite unlikely to me).

> we cannot upgrade to latest version due to problem in mongodb driver

There will be a release soon that reverts back to the Linq2 provider, perhaps this allows you to upgrade (which would be 2.12.0 (// cc @mohdali )

**Comment by alkampfergit** [comment]
We were totally unable to reproduce ... we had this on our log, happened only one time, never happened again so I really wonder what happened :).

**Comment by sfmskywalker** [comment]
A true mystery. May it never occur again 😄
