### ISSUE TITLE
Elsa 3 - workflow execution stops at the joing activity

### ISSUE THREAD

**Issue by MariusVuscanNx** [elsa-workflows/elsa-core#4013]
If you have a workflow that tries to execute the same sub-workflow twice, in parallel and then join the execution using the join activity (with setting Wait All), then something breaks and the workflow execution gets stuck at the join step. 

We managed to reproduce this only when we have a set output activity in the sub-workflow, so, it has something to do with that. 
[workflows.zip](https://github.com/elsa-workflows/elsa-core/files/11427636/workflows.zip)

**Comment by MariusVuscanNx** [comment]
[workflows2.zip](https://github.com/elsa-workflows/elsa-core/files/11427827/workflows2.zip)
A second example with a workflow that keeps running.

In this case, the sub-workflow returns an output that is not mapped in the main workflow. If you map the variable in the main workflow, the execution is successful.

**Comment by sfmskywalker** [comment]
Can no longer reproduce. Based on your description with the output not being set, I am convinced the issue had to do with the bug preventing the sub workflow from completing when no variable is set to capture the output.

**Comment by sfmskywalker** [comment]
Re-opening - the first workflow still doesn't complete, so this might be something else.

**Comment by sfmskywalker** [comment]
This is now fixed via 2ae438002d006da20cf3ac3b97f1800eee35ce15
