### ISSUE TITLE
Elsa 3: Dashboard fails to display workflow editor when using workflowcontexts

### ISSUE THREAD

**Issue by ploef** [elsa-workflows/elsa-core#4014]
Hi,

When using dashboard and server in same project, the dashboard cannot display the workflow editor anymore after configuring using workflowContext in the program.cs ( elsa.UseWorkflowContexts()).
<img width="1457" alt="Elsa Workflows 3 0 2023-05-09 08-54-53" src="https://user-images.githubusercontent.com/1884192/237017942-d5ddd3ca-6a37-44bd-a833-e77e3b192478.png">

**Comment by sfmskywalker** [comment]
I tried to reproduce this, but it seems to work fine. Perhaps it got fixed by accident in the meantime.
If you an still reproduce this issue, please feel free to reopen this issue and, ideally, attach a sample project that demonstrates this behaviour.
