### ISSUE TITLE
Replace manual mapping logic such as Workflow.ToInstance with AutoMapper

### ISSUE THREAD

**Issue by craigfowler** [elsa-workflows/elsa-core#402]
Elsa has a dependency upon AutoMapper, even in the `Elsa.Core.Abstractions` project (which I believe is the 'root' dependency for all other Elsa projects).  It would be _tidier and more consistent_ to replace logic such as [manual mapping code from Workflow to Workflow Instance](https://github.com/elsa-workflows/elsa-core/blob/develop/src/core/Elsa.Abstractions/Services/Models/Workflow.cs#L58) with AutoMapper.  IE:  Given Elsa thoroughly depends upon AM, it may as well embrace it.  There is probably more of this sort of thing which goes on elsewhere, I've only provided one example I found.

## Further thought
Probably in an ideal world, the library would provide some AutoMapper Profile classes for the mappings which it uses.  Then, the consuming applications could decide to either "just take Elsa out of the box" which means that Elsa manages the creation of a whole mapper configuration, or the consumer could just add those profiles to their own mapper configuration (imagine a consuming app which also uses AutoMapper).

**Comment by sfmskywalker** [comment]
Makes sense. I also like the suggestion of offering mapping profiles, but allowing the hosting application to decide whether they use those, or their own profiles.

A further improvement would be to disable AutoMapper registration. Some commits ago, AutoMapper was registered automatically whenever you register Elsa services. However, this caused [issues](https://github.com/elsa-workflows/elsa-core/issues/290) for folks using the [ABP framework](https://aspnetboilerplate.com/Pages/Documents/AspNet-Core).

I "fixed" that by not registering AutoMapper with DI, but instead abstract it away behind a factory pattern (where the factory would manually instantiate an AutoMapper mapper object). This works nicely, but a more elegant solution might be to let the consuming app control AutoMapper registration.

**Comment by sfmskywalker** [comment]
This has been changed in Elsa 2 (which uses AutoMapper pretty much everywhere it makes sense).
