### ISSUE TITLE
Timer Is not working correct in cluster mode.

### ISSUE THREAD

**Issue by regan32** [elsa-workflows/elsa-core#4021]
i want to use elsa as workflow engine, in distributed, multi-node system. But for now, i have stuck on configuring recurring/cron activities in cluster mode. My test app is here https://github.com/regan32/elsa-core/tree/2.11.1_issues/src/samples/aspnet/Elsa.Samples.DocumentApprovalv2

Both realizations are not working as expected

.AddHangfireTemporalActivities(hangfire => hangfire.UsePostgreSqlStorage("")) cause triggers to work on each node or even more... test output for sample with email for document approval looks like this
![image](https://user-images.githubusercontent.com/3633953/237415128-964a6589-23f8-4f65-a7bf-504f46df6bd7.png)

   .AddQuartzTemporalActivities(configureQuartz: quartz => quartz.UsePersistentStore(store =>
                                {
                                    store.UseJsonSerializer();
                                    store.UsePostgres("");
                                    store.UseClustering();
                                }))

cause only one node to trigger timer event, so after working node termination second node doesn't continue to trigger timer events

This issue can be used as replay for 
_Originally posted by @sfmskywalker in https://github.com/elsa-workflows/elsa-core/issues/1030#issuecomment-1028358963_

**Comment by sfmskywalker** [comment]
Am I right that you're saying that it works as expected with Quartz.NET, but not when using Hangfire?

**Comment by regan32** [comment]
With handfire it works as shown on sceenshot, timer in sample configured to email each 10 seconds, - this is not as expected
With quatrz.net time works fine (i have email each 10 seconds), but timer works always on the same node and if i terminate it, second node doesn't continue to send emails.
