### ISSUE TITLE
Memory leak?

### ISSUE THREAD

**Issue by tomazk8** [elsa-workflows/elsa-core#404]
I am trying out Elsa for the first time. I used the HelloWorldWorkflow example as a base and only added a while loop to it:

```
while (true)
{
    invoker.StartAsync<HelloWorldWorkflow>().Wait();

    if (Console.KeyAvailable)
        break;
}
```

The memory consumption is rising constantly at around 900MB/min.

**Comment by sfmskywalker** [comment]
I just tried it myself and I can confirm that memory consumption is indeed rising constantly. Definitely a memory leak.

**Comment by erolkskn** [comment]
I don't think this is a memory leak issue. I think that memory usage constantly grows because of `WorkflowInstance`s are being appended to ConcurrentQueue in `MemoryWorkflowInstanceStore`. If you dump memory you will see a lot of JObjects and ActivityInstances and WorkflowInstances in the memory.

**Comment by sfmskywalker** [comment]
Doh, of course! I had completely forgotten about the in-memory store (registered by default if no other persistence provider is configured). 

I just tested it by simply not saving workflow instances into the memory store, and then memory consumption remains at a stead 35 megs.

Good thinking @erolkskn ! 😄

**Comment by sherafatian-amirabbas** [comment]
Hi, 

I have still this problem, however the persistence provider is set to use Entityframework and SQL server. 

I noticed the data stored in DB, but memory consumption reaches around 1GB. I'm sending the load test for around 30 seconds. Could you please provide some example solution, link to something you already may have, suggestion, etc. to solve this?

Thanks
