### ISSUE TITLE
2.0.0 branch

### ISSUE THREAD

**Issue by tomy2105** [elsa-workflows/elsa-core#4051]
@sfmskywalker Would it be possible to create a 2.0 branch based on the 2.0 tag?

Explanation....
Yeah, I'm still stuck with 2.0 Elsa for various reasons :(.
I'm switching my source control (finally :)) from SVN to GIT and want to add Elsa source as submodule.
Unfortunately git submodule can add specific branch but cannot seem to add specific tag :(.

So would be grateful for 2.0.0 branch based on current 2.0 tag.
Thank you.

**Comment by sfmskywalker** [comment]
For sure! With the imminent 3.0 RC release, I'll create a 2.x branch and switch merge the v3 branch into main.

**Comment by mohdali** [comment]
@tomy2105 can you check if this branch matches your requirement? https://github.com/elsa-workflows/elsa-core/tree/2.0.0

**Comment by tomy2105** [comment]
@mohdali yes, that one is perfect, thank you very much.
