### ISSUE TITLE
Issues related to activity withdrawal and return

### ISSUE THREAD

**Issue by 15859096137** [elsa-workflows/elsa-core#4058]
I plan to develop a universal workflow, where the function of the activity is approval. For example, after node1 is approved, node2 is followed by node3, and each node has a withdrawal. For example, when node2 is approved (node2 has not yet been approved), node1 can be withdrawn; For returning, I want Node3 to return to Node1. To clarify, each node can return to any node before it at will; So I want to ask if Elsa currently supports such programming? Or how should I implement such logic? Look forward to your reply！

**Comment by sfmskywalker** [comment]
Sure! In Elsa 2, each activity could have a "Withdraw" outcome to which you can connect any activity you like, including previously executed activities.

In Elsa 3, there is the potential for doing this automatically via signaling between activities. For example, you could have each activity schedule the previously executed activity automatically, without connecting them explicitly. There are no examples of this yet, but I'll be looking into this eventually.
