### ISSUE TITLE
The sample project does not display properly

### ISSUE THREAD

**Issue by hyzx86** [elsa-workflows/elsa-core#406]
When I start with `Elsa.Dashboard.Web` , The javascript file is parsed into html content, which looks like it has been replaced by the HTML of the welcome page

![image](https://user-images.githubusercontent.com/15613121/96161421-d8d81080-0f49-11eb-857d-dfc381d67ba9.png)

**Comment by hyzx86** [comment]
But when I comment out `.UseWelcomePage()`, the js resource throws a 404 exception

**Comment by sfmskywalker** [comment]
This is expected. When running the source code version of the dashboard, the client side assets need to be built first using gulp. If you scroll down on the Readme page (home page of this repo), you’ll find a couple of steps to follow.

**Comment by hyzx86** [comment]
got it ,thanks
