### ISSUE TITLE
Get user actions dynamically

### ISSUE THREAD

**Issue by denis-ivanov** [elsa-workflows/elsa-core#407]
Hi!
I need to get user actions dynamically, I have already seen an example [Sample12](https://github.com/elsa-workflows/elsa-core/tree/develop/src/samples/Sample12) and there I can change code like this and get actions:
```csharp
using System;
using System.Linq;
using System.Threading.Tasks;
using Elsa.Activities.Console.Extensions;
using Elsa.Activities.UserTask.Activities;
using Elsa.Extensions;
using Elsa.Models;
using Elsa.Services;
using Elsa.Services.Extensions;
using Microsoft.Extensions.DependencyInjection;

namespace Sample12
{
    /// <summary>
    /// Demonstrates workflow correlation & user tasks.
    /// </summary>
    public static class Program
    {
        public static async Task Main(string[] args)
        {
            var services = BuildServices();
            var registry = services.GetService<IWorkflowRegistry>();
            var workflowDefinition = await registry.GetWorkflowDefinitionAsync<UserTaskWorkflow>();
            var invoker = services.GetRequiredService<IWorkflowInvoker>();

            // Start the workflow.
            var correlationId = Guid.NewGuid().ToString("N");
            var executionContext = await invoker.StartAsync(workflowDefinition, correlationId: correlationId);

            do
            {
                var activity = (UserTask) executionContext.CurrentActivity;
                // Workflow is now halted on the user task activity. Ask user for input:
                Console.WriteLine($"What action will you take? Choose one of: {string.Join(", ", activity.Actions)}");
                var userAction = Console.ReadLine();

                // Resume the workflow with the received stimulus.
                var triggeredExecutionContexts = await invoker.TriggerAsync(nameof(UserTask), new Variables { ["UserAction"] = new Variable(userAction)}, correlationId);
                executionContext = triggeredExecutionContexts.First();

            } while (executionContext.Workflow.IsExecuting());
        }

        private static IServiceProvider BuildServices()
        {
            return new ServiceCollection()
                .AddElsa()
                .AddConsoleActivities()
                .AddWorkflow<UserTaskWorkflow>()
                .BuildServiceProvider();
        }
    }
}
```

But in my application workflow is already started and if try to construct `WorkflowExecutionContext` like this
```csharp
var workflowFactory = services.GetRequiredService<IWorkflowFactory>();
var workflow = workflowFactory.CreateWorkflow(workflowDefinition);
var executionContext = new WorkflowExecutionContext(workflow, services.GetRequiredService<IClock>(), services);
var userTask = (UserTask) executionContext.CurrentActivity;
```

My variable `userTask` is null.

Briefly, I need something like [GetOpenUserActions](https://github.com/danielgerlag/workflow-core/blob/master/src/extensions/WorkflowCore.Users/ServiceExtensions/WorkflowHostExtensions.cs#L27) in WorkflowCore.

**Comment by sfmskywalker** [comment]
You need to first get a reference to the workflow instance. In your code snippet, you are creating a new instance of a workflow, which starts at the beginning.

I'll update the sample to demonstrate getting a list of user actions. Note that Elsa doesn't currently have a concept of "open" user actions (I assume these are actions not already taken), but I like the idea and will see if we can improve upon the UserTask activity in Elsa 2, including useful services around it.

**Comment by sfmskywalker** [comment]
Actually, I was mistaken with my first comment. You don't necessarily need a workflow instance to get the list of configured user actions. You can do it like this instead:

```csharp
var availableActions = workflowDefinition.Activities.Single(x => x.Name == "WaitUser").State["Actions"].ToObject<string[]>();
```

Notice that I'm selecting the UserTask activity by name (which you configure within the workflow definition itself).

See https://github.com/elsa-workflows/elsa-core/commit/07f71a2befd660a181f4ed0b5c18ef3321c7ddd8#diff-7ffc8f67fb3b873afb224d9d041ec59123e2226f1150148b0cbff2f1ffd45b2cR34

**Comment by denis-ivanov** [comment]
@sfmskywalker, thanks for your answer, but still, what if I have multiple `UserTask` in my workflow, how to detect current activity?

**Comment by jortygu** [comment]
@denis-ivanov i think you may need to use activityId to get specific activity,you can pass workflowInstanceId to get workflowDefinition,then  use activityId get specific Activity info.
```
public async Task<IViewComponentResult> InvokeAsync(string instanceId, string activityId)
{
      var activity = await _workflowService.GetActivityAsync(instanceId, activityId);
      var model = new FormApproveModel(activity.Id, activity.Type, activity.Name);
      activity.UserActions.ToList().ForEach(userAction => {
           model.UserActionDict.Add(userAction, _localizer[userAction]);
      });
     ...
}
```

**Comment by sfmskywalker** [comment]
In that case, you would need a workflow instance, which has a list of blocking activities (storing activity type + activity ID). You could query this list to get the `UserTask` activity IDs, and use these IDs to get the `UserTask` activity definitions from the workflow definition in order to get their actions.

**Comment by mserey** [comment]
Hi,
There is an example of how to work with user task in the designer

**Comment by sfmskywalker** [comment]
Not yet, but I [created an issue](#565) for it to keep track of this.

**Comment by uppercuut** [comment]
@sfmskywalker  any luck with the user task example

**Comment by sfmskywalker** [comment]
I'm afraid not as of yet. Shifting priorities and all that.

**Comment by uppercuut** [comment]
For Anyone who ask about this , 
after reading the great documentation `UserTask `is just a `class `the inherits from `activity `. 

it has one more virtual method which called `OnCanExecute` which retruns a bool if true it will go as a normal activity if not it will just terminate the execution . 

its also had `ActivityInput` called action which takes the actions as string[] . 

https://elsa-workflows.github.io/elsa-core/docs/next/guides/guides-blocking-activities

this tutorial is more than enough for the user task example. 

finaly, thanks for this awesome library
