### ISSUE TITLE
Document approval example keep sending reminder

### ISSUE THREAD

**Issue by Ahmedrz89** [elsa-workflows/elsa-core#4081]
Hi
I have been trying to learn elsa workflow and i have checked the document approval example and the reminder activity keep sending email for some reason I though once the join activity gets executes all previous should be stopped am I missing something here can someone helps
Thanks

**Comment by daigs** [comment]
![image](https://github.com/elsa-workflows/elsa-core/assets/25603166/cc642b46-b9ae-488b-a8ba-b6a3722ee4b0)
add .WithEagerJoin(true)
![image](https://github.com/elsa-workflows/elsa-core/assets/25603166/268615ce-b0f9-4700-a7e2-de1355e2bc19)
