### ISSUE TITLE
Remove the direct dependencies on the "https://rsms.me/inter/inter.css" stylesheet

### ISSUE THREAD

**Issue by robverhoef-united** [elsa-workflows/elsa-core#4094]
In Elsa V3 there is a direct dependency on the "https://rsms.me/inter/inter.css" style sheet for the designer to display correctly. This limits the  usage of the designer within an isolated (from Internet access) network. Please add the direct and indirect dependencies of this stylesheet into the Elsa package itself so the designer can be used with networks without internet access as well.

**Comment by sfmskywalker** [comment]
Hello @robverhoef-united,

Thank you for bringing this to our attention. We understand the importance of ensuring that Elsa V3 can operate seamlessly within isolated networks without internet access.

Your request to embed the "https://rsms.me/inter/inter.css" stylesheet directly into the Elsa package is valid, especially for environments with strict network policies. However, I'd like to inform you that we are in the process of transitioning away from the Stencil implementation of the V3 designer. Our focus is shifting towards the [Elsa Studio](https://github.com/elsa-workflows/elsa-studio) project, which we believe will offer a more robust and versatile solution for our users.

We appreciate your feedback and patience as we work towards enhancing the Elsa experience. Please let us know if you have any other concerns or suggestions.

**Comment by sfmskywalker** [comment]
Since we have deprecated the Stencil implementation in favor of the Blazor one, we won't work on this issue. If someone does want to do it, that is fine of course. In that case, please feel free to reopen and submit a PR. Thank you for your participation in the conversation, we will keep this issue in mind going forward.
