### ISSUE TITLE
Elsa 2: Kafka Activity module is preparing consumed message in an asynchronous way

### ISSUE THREAD

**Issue by dao74** [elsa-workflows/elsa-core#4095]
The Elsa.Activities.Kafka.Helpers.Consumer class is using the observer pattern to notificate about received messages from Kafka.
The "notification" process is working asynchronous (fire and forget method) which is causing an issue, if there is a lag in the kafka queue or a bulk processing is intended.

In other words; the consumer is trying to preparing all (outstanding) queue messages in parallel and this can cause in extreme cases the exhausting of all pooled database connections.

To prevent this kind of issues, the process between receiving and preparing should be in an await mode, and the process should stop/retry if preparation of a message will fail. Otherwise, the message which is not processed will be lost.

**Comment by sfmskywalker** [comment]
Do you want to submit a PR to fix this?

**Comment by dao74** [comment]
Sure, with pleasure.
