### ISSUE TITLE
Dashboard designer using wrong workflow version

### ISSUE THREAD

**Issue by MaxBrooks114** [elsa-workflows/elsa-core#4096]
I have a small workflow running and anytime I need to update it, I edit and publish. Despite the correct version showing in the workflow definition, anytime the workflow is triggered it uses the old version. The only way to fix this is to restart the entire solution (which is not a feasible solution).

<img width="1273" alt="image" src="https://github.com/elsa-workflows/elsa-core/assets/45081361/e7db7d1e-bea5-403e-8629-c640862beb8a">

<img width="1273" alt="image" src="https://github.com/elsa-workflows/elsa-core/assets/45081361/6f42999d-dac0-4551-ac6a-ca57cead10ed">

**Comment by sfmskywalker** [comment]
I tried to reproduce this behaviour, but I wasn't able to get the same result.

Here's what I tried:

1. Created a workflow definition (version 1)
2. Ran the workflow, which resulted in a new workflow instance (version 1).
3. Updated the workflow definition (version 2)
4. Ran the workflow, which resulted in a new workflow instance (version 2).

If you have any repro steps you can share with a clean project, I can take a look.

**Comment by MaxBrooks114** [comment]
I am wondering if it has anything to do with the config. We have a web app and and web api in two separate projects. The elsa server is hosted on the api project so we can use the http request activities that hit the api and then we run the dashboard through the web app to design the activities.

**Comment by MaxBrooks114** [comment]
Also try to change it twice in a row actually. The first change works, then the second change doesn't. So in your example,

Created a workflow definition (version 1)
Ran the workflow, which resulted in a new workflow instance (version 1).
Updated the workflow definition (version 2)
Ran the workflow, which resulted in a new workflow instance (version 2).
Updated the workflow definition (version 3)

For me it runs version 2 again.
