### ISSUE TITLE
Potential issues with SendHttpRequest activity

### ISSUE THREAD

**Issue by hankovich** [elsa-workflows/elsa-core#410]
Hi!

While reading Elsa's code, I discovered several places that are not obvious to me and look like potential issues/bugs.
Note that I'm not an actual user, I haven't even compiled the code, so probably my input is not relevant here.

Anyway I think there are some potential problems with SendHttpRequest activity.

1. `GetMethodSupportsBody` returns `true` for "POST", "PUT", "PATCH", but `Method` property also supports "DELETE" method. According to the spec "DELETE" may have a body, so it would be nice to add it to the list of methods that support body.

2. Headers' parsing is inaccurate. I see the issue #375, but I think there is an additional issue:

```csharp
from line in Regex.Split(headersText, "\\n", RegexOptions.Multiline)
let pair = line.Split(':', '=')
select new KeyValuePair<string, string>(pair[0], pair[1]);
```

It will not work if your header has `:` or `=` in it's value.
Example: `Cookie: Key1=Value1` will result in a KeyValuePair of `("Cookie", "Key1")`.
Note that it's not a synthetic example, `=` and `:` may appear in many headers. For example: `Content-Type`, `Location`, `Origin`, `Referer`.

Proposed fix is very trivial. Another `string.Split` overload should be used (i.e. not `line.Split(':', '=')`, but `line.Split(new[] { ':', '=' }, 2)`).

I'm happy to submit a PR that will fix both issues (I can also fix #375 as suggested) if you think them should be fixed.

Please also point if you're interested in my input. I can also report another potential issues/bugs/potential improvements which I have found / will find.

Sviat.

**Comment by sfmskywalker** [comment]
Hi Sviat, nice to see you here!

Thank you for scouring through the source code and identifying potential issues. Who needs a compiler when we have you ;)
I admit that the current implementation is a very naïve one, with the intent being to harden the implementation as it gets used more over time.

However, I agree with your findings, so if you want to provide a PR fixing the issues you discovered then that would be brilliant.

Thanks!

**Comment by hankovich** [comment]
Thanks @sfmskywalker, I am really amazed at how great Elsa looks! Haven't had such pleasure from reading code in a long time. You did a great job!

Could you add a [`hacktoberfest` topic to the repository](https://hacktoberfest.digitalocean.com/hacktoberfest-update) please? This is not critically important for me, but it would be nice if my contribution was also taken into account.

**Comment by sfmskywalker** [comment]
Done!
