### ISSUE TITLE
(Angular) Drop down doesn't show selected or available values

### ISSUE THREAD

**Issue by Amanda156** [elsa-workflows/elsa-core#4129]
Hi,

in version 3.0.0-preview.476 I have some problems with the drop down fields in the activity settings.
If you create a new workflow and add an activity which contains a drop down field, like for instance a flow switch, the drop down field is only shown correctly the first time you open the settings. If you unselect the activity and select it again, there will be no value selected at the drop down field and the list of available values is empty. A workaround is to switch to the "General" tab and go back to "Settings".  Then all values will be shown correctly. Sometimes it also happens that changes are lost, that were made while the drop down was not displayed correctly.

![image](https://github.com/elsa-workflows/elsa-core/assets/136434594/4e18375a-6b24-489a-983e-ab1a1cee77f7)

Below you can find an example where you can try this out.

1. Start the Backend
2. npm install inside the frontend project
3. npm run start inside the frontend project
4. Open the browser and enter http://localhost:4200/workflow (you have to manually enter workflow as route because the example doesn't contain a navigation menu)
5. Create a workflow with a flow switch activity
6. Configure the settings of the activity
7. Click into the workflow area, so that the activity isn't selected anymore
8. Select the activity again
9. Try to select a value at the drop down field

[angular-workflow.zip](https://github.com/elsa-workflows/elsa-core/files/11732160/angular-workflow.zip)

**Comment by truthz03** [comment]
Hi, I have the same problem with 3.0.0-preview.489.
It seems that if the "Settings" tab was selected for an activity the "Settings" tab was automatically reselected if you click on the activity again.
If you select the "General" tab before you leave the activity you have to manually click the "Settings" tab and the problem doesn't occure.
