### ISSUE TITLE
HttpEndpoint not suspending workflow if earlier HttpEndpoint was triggered

### ISSUE THREAD

**Issue by domrin123** [elsa-workflows/elsa-core#4143]
Version: Elsa RC1

**Issue:**

When a workflow is executed by an HttpEndpoint, if it is followed by another HttpEndpoint, the workflow does not suspend at that point. Instead it executes the second HttpEndpoint. 

**Example:**
[http-endpoint-issue.txt](https://github.com/elsa-workflows/elsa-core/files/11767939/http-endpoint-issue.txt)

**Possible cause:**

Looking at the source, HttpEndpoint.cs checks the input for if there is an HttpContext:

        if (!context.TryGetInput<bool>(HttpContextInputKey, out var isHttpContext))
        {
            // Create bookmarks for when we receive the expected HTTP request.
            context.CreateBookmarks(GetBookmarkPayloads(context.ExpressionExecutionContext));
            return;
        }

Is it possible that the input for the executed HttpEndpoint is also reaching the later one? In which case, would a more robust check for the targeted activity be a solution?

Thanks

**Comment by sfmskywalker** [comment]
Fixed via #4170
