### ISSUE TITLE
SetVariable throws for JSON expressions that evaluate to an array.

### ISSUE THREAD

**Issue by PeterLaComb-Availity** [elsa-workflows/elsa-core#415]
using `JSON.parse('["test"]')` in a SetVariable activity will throw an object reference not set exception because the type of expression is not set. 

private object ConvertValue(JsValue value, Type targetType) in JavascriptExpressionEvaluator does not check that targetType is not null when doing conversions.

I believe the safe thing to do here would be to return a reasonable type based on the JsValue, so I'm going to open a PR to that effect.

**Comment by sfmskywalker** [comment]
I checked the PR and it looks good to me. Thank you.
