### ISSUE TITLE
C# Expressions

### ISSUE THREAD

**Issue by sfmskywalker** [elsa-workflows/elsa-core#4163]
In addition to JavaScript and Liquid expressions, we should see if we can't add C# expressions as well.

**Comment by AlexK555** [comment]
It would be a very nice to have the same codebase for workflows and main code and avoid interrogability issues with Javascript. 
Hopefully can be doable with Roslyn. 
Hope the team can consider such possibility in future.

**Comment by sfmskywalker** [comment]
Working on it.
