### ISSUE TITLE
Deriving the outputName using CallerArgumentExpression in ActivityExecutionContext.Set<T>(...) will result in not finding output values in the JintJavaScriptEvaluator

### ISSUE THREAD

**Issue by rolandgriesser** [elsa-workflows/elsa-core#4174]
https://github.com/elsa-workflows/elsa-core/blob/a1ce26a35c3b830cef0cb738466946275cb43326/src/modules/Elsa.Workflows.Core/Models/ActivityExecutionContext.cs#L282C17-L282C20

This problem is especially visible when setting the Output using the extension method `OutputExtension.Set<T>()` e.g., as the `[CallerArgumentExpression]` will result in `output`, no matter the actual name of the output - and thus the key of the output in the `ActivityOutputRegister` won't be the original Output name, but `output` instead. As the `JintJavaScriptEvaluator` will create the output accessors using the `ActivityDescriptor.Outputs.Name` property, it will not be able to get the actual output value from the register.
As using the property name wouldn't work either if the Name is overridden using the `OutputAttribute`, the `Set` method should probably try to get the proper name from the ActivityDescriptor as well.

**Comment by sfmskywalker** [comment]
Hi @rolandgriesser , I just started looking into this and I'm having a little bit of trouble reproducing the behavior you described. Would it be possible for you to provide a setup that reproduces the issue?

What I have tried is this:

1. Created a custom activity that produces an outcome.
2. Added the custom activity to a workflow using the designer,
3. Executed the workflow using the designer.

Here's the code for the custom activity:

```csharp
public class CustomActivity : CodeActivity<string>
{
    protected override void Execute(ActivityExecutionContext context)
    {
        context.Set(Result, "Hello World!");
    }
}
```

Here's the output captured:

<img width="860" alt="image" src="https://github.com/elsa-workflows/elsa-core/assets/938393/be603181-0a55-4c1b-9849-893f377ca29b">

You raise a valid point with the Name property potentially being overridden with customized activity descriptors, which I'll give some more thought.

**Comment by sfmskywalker** [comment]
I've addressed the issue related to customizing output names. Now, the system can accurately identify outputs even when their names are altered. This applies to changes made using `[Output(Name = "Foo"]`, custom type providers, or `IActivityDescriptorModifier` implementations.

Let's delve into a practical example:

```csharp
public class CustomActivity : CodeActivity<string>
{
    [Output(Name = "CustomOutputA")] public Output<string> OutputA { get; set; } = default!;
    
    protected override void Execute(ActivityExecutionContext context)
    {
        context.Set(Result, "Hello World!");
        context.Set(OutputA, "Hello Sun!");
    }
}
```

In the above activity, there are two output properties:

1. Result
2. OutputA

The name of `OutputA` is explicitly modified to **CustomOutputA** using the `OutputAttribute`. Meanwhile, the name of `Result` is transformed to **CustomResult** via the subsequent modifier:

```csharp
public class CustomActivityModifier : IActivityDescriptorModifier
{
    public void Modify(ActivityDescriptor descriptor)
    {
        if (descriptor.TypeName != ActivityTypeNameHelper.GenerateTypeName<CustomActivity>())
            return;

        var resultPropertyDescriptor = descriptor.Outputs.First(x => x.PropertyInfo!.Name == "Result");

        resultPropertyDescriptor.Name = "CustomResult";
    }
}
```

When executing a workflow that incorporates this activity, the recorded output names will mirror the custom names, as illustrated below:

![Customized Output Names](https://github.com/elsa-workflows/elsa-core/assets/938393/411a12a7-f03e-427d-b677-386e9006d8eb)

**Comment by rolandgriesser** [comment]
Hi @sfmskywalker, thanks for addressing the issue.
Just for clarification, if anyone else is running into the same problem: I've been using the method the wrong way, instead of using `context.Set(Result, "Hello World!")`, I've been using the Extension method on the Output class: `Result.Set(context, "Hello World")`. In that case, the captured output would be `output` instead of `Result`.

**Comment by sfmskywalker** [comment]
Good to know @rolandgriesser - however, let me try and see if we can make both cases behave as expected. Both approaches should have the same result - if not it's going to be very confusing. And perhaps we should expose just one way, as THE way 🤔

**Comment by sfmskywalker** [comment]
I just tested using `Result.Set(context)`, with and without modifiers, and it all works out.
