### ISSUE TITLE
Workflow Cancellation

### ISSUE THREAD

**Issue by Cryshot** [elsa-workflows/elsa-core#4177]
Hello,
We are using Elsa 2 to construct workflows with activities that access various external resources sequentially in an asynchronous manner. As a precaution, we aim to cancel any workflow instance that exceeds a predefined time limit (e.g., if an API call takes too long).

I believe that using the built-in workflow cancellation or faulting features is not suitable in this case since they do not immediately terminate the workflow execution.

Another option is to utilize a `CancellationToken`. To provide a `CancellationToken`, we need to implement the `IHandleMessages<ExecuteWorkflowDefinitionRequest>` interface and replace its default implementation of `ExecuteWorkflowDefinitionRequestConsumer` in the dependency injection container.

However, canceling the token will also terminate the post-processing of the workflow instance, including notifications such as `WorkflowExecuted`, `WorkflowFaulted`, and `WorkflowExecutionFinished`. Consequently, the workflow instance will become 'stuck' in a running state.

Is there a way to cancel only the 'user-defined' section of the workflow without affecting the pre- and post-processing stages?

Thank you in advance!

**Comment by sfmskywalker** [comment]
I don't think there's a way to cancel only the user defined section of the workflow without affecting the pre- and post-processing stages. It might be possible to implement it, and I will certainly keep this in mind for Elsa 3.

**Comment by sfmskywalker** [comment]
Related issue: #3093
