### ISSUE TITLE
When an activity faults after a ReceiveHttpRequest activity, the returned status code should be 500, not 202

### ISSUE THREAD

**Issue by craigfowler** [elsa-workflows/elsa-core#418]
## Reproduction steps
1. Create a workflow which is based upon a received HTTP request, there's a sample below
2. Include in this workflow an activity which raises an unhandled exception
3. Invoke this workflow using an HTTP request

### Expected behaviour
Because the workflow crashed and raised an exception, the HTTP status code on the response should be 500 (internal server error).  The workflow has not progressed and is now in a faulted state.

### Actual behaviour
The HTTP response is received with a 202 Accepted status code.  There's nothing to indicate that the request failed.

## Example workflow design
_Boilerplate around the workflow design omitted for brevity:_

```csharp
builder
.StartWith<ReceiveHttpRequest>(a =>
{
    a.Path = new Uri("/crash-tastic", UriKind.Relative);
    a.Method = HttpMethod.Get.Method;
})
.Then<CrashActivity>();
```

CrashActivity is just the following:

```csharp
public class CrashActivity : Activity
{
    protected override ActivityExecutionResult OnExecute(WorkflowExecutionContext context)
    {
        throw new Exception("Sample exception to demonstrate problem");
    }
}
```

**Comment by sfmskywalker** [comment]
Fixed
