### ISSUE TITLE
V3: saveing new version of a workflow definition, reuse Created At time of previous version

### ISSUE THREAD

**Issue by Doehl** [elsa-workflows/elsa-core#4185]
When creating a new version of a workflow definition, will the created at time being set to the time of the version that the workflow definition is based on. This result in every version of a workflow definition to have the same time no matter of the date and time of the save action.

A quick look at the "DefaultWorkflowDefinitionStorePopulator.AddOrUpdateAsync" method, I can see that we only update the CreatedAt if the input value is default. As the CreatedAt value is send from the frontend on publish, is it not default, and therefore not updated.

```C#
existingDefinition.CreatedAt = workflow.WorkflowMetadata.CreatedAt == default ? _systemClock.UtcNow : workflow.WorkflowMetadata.CreatedAt;
```

All the versions on the image below, has been save on different days. 

![image](https://github.com/elsa-workflows/elsa-core/assets/1913751/35f9ef3e-8bfe-4a9d-97d1-e72c000c2838)

**Comment by sfmskywalker** [comment]
Hi @Doehl , thank you for reporting this issue! I have tried to reproduce it with the latest code base, and it would seem that the problem has disappeared. If you can still reproduce it with the latest preview version, then please feel free to reopen this issue.
