### ISSUE TITLE
V3: Invoking manually registered workflows using the IWorkflowRuntime service

### ISSUE THREAD

**Issue by glokhov** [elsa-workflows/elsa-core#4186]
I've created and registered a workflow as described [here](https://v3.elsaworkflows.io/docs/guides/invoking-workflows#using-the-i-workflow-runtime-service).
```
class DailyReport : WorkflowBase { ... }

services.AddElsa(elsa => elsa.AddWorkflow<DailyReport>());
```

If I start it using IWorkflowRuntime, I get the "Specified workflow definition and version does not exist" exception.

```
var runtime = serviceProvider.GetRequiredService<IWorkflowRuntime>();

var result = await runtime.StartWorkflowAsync("DailyReport");
```

If I run the workflow using IWorkflowRunner, it runs just fine.

```
var runner = serviceProvider.GetRequiredService<IWorkflowRunner>();

var result = await runner.RunAsync(new DailyReport());
```

**Comment by sfmskywalker** [comment]
Hi @glokhov , thanks for reporting this issue! Is there any chance you could share the full program o I can see what might be the issue?

**Comment by sfmskywalker** [comment]
Hi @glokhov , thank you for providing the full program. I see now why you are getting that particular error.
The `IWorkflowRuntime` service was designed to operate within an application host, which involves running startup services to populate the workflow registry from various sources, including workflows registered with the WorkflowRuntimeOptions.

This means that if you want to use the `IWorkflowRuntime` service inside of a regular console app that doen't use a host, you need to manually populate this registry. For example, the following program will work:

```csharp
using Elsa.Extensions;
using Elsa.Workflows.Core;
using Elsa.Workflows.Core.Activities;
using Elsa.Workflows.Core.Contracts;
using Elsa.Workflows.Runtime.Contracts;
using Elsa.Workflows.Runtime.Requests;
using Microsoft.Extensions.DependencyInjection;

var services = new ServiceCollection();
services.AddElsa(elsa => elsa.AddWorkflow<HelloWorldWorkflow>());

var serviceProvider = services.BuildServiceProvider();
var workflowRuntime = serviceProvider.GetRequiredService<IWorkflowRuntime>();

// Resolve IRegistriesPopulator from the service provider.
var populator = serviceProvider.GetRequiredService<IRegistriesPopulator>();

// Populate the registries.
await populator.PopulateAsync();

// Start the workflow.
await workflowRuntime.StartWorkflowAsync("HelloWorldWorkflow", new StartWorkflowRuntimeOptions());

public class HelloWorldWorkflow : WorkflowBase
{
    protected override void Build(IWorkflowBuilder builder)
    {
        builder.Root = new WriteLine("Hello world!");
    }
}
```
