### ISSUE TITLE
V3: Designer - Breadcrumbs disappear on publish in foreach body

### ISSUE THREAD

**Issue by Doehl** [elsa-workflows/elsa-core#4187]
In the designer when navigated to the body of a foreach loop. When clicking the publish button in the header, disappear the Breadcrumbs. So it is no longer possible to navigate out of the foreach body.

**Comment by sfmskywalker** [comment]
That sounds like a regression. What version did you see this? RC1 or in the latest preview?

**Comment by Doehl** [comment]
It was on the RC1

**Comment by Doehl** [comment]
I have found that is issue goes a lot deeper.
Because if I press publish again after the breadcrumb is hidden, will the application think that the current path is the main path of the workflow. Therefore overwrite the workflow to only being the "loop" path.

**Comment by sfmskywalker** [comment]
Yes, I think this issue is solved post-RC1. At least, I cannot reproduce it in the latest version.

**Comment by Doehl** [comment]
I can confirm that the issue has been fixed in the latest release.

**Comment by sfmskywalker** [comment]
Thanks for confirming!
