### ISSUE TITLE
V3: Disable Login does not work

### ISSUE THREAD

**Issue by schlechtOptimiziert** [elsa-workflows/elsa-core#4188]
If I add `disable-auth="true"` to my `<elsa-studio>` I get an 401 error the second I try to open the page.

The Issue was also discussed on [discord](https://discord.com/channels/814605913783795763/1123555518825386105).

The short version of the code was still to big even in .zip. I have made an [Repo](https://github.com/schlechtOptimiziert/ElsaV3Test_DisableLogin).

**Comment by sfmskywalker** [comment]
Hello @schlechtOptimiziert,

Thank you for bringing this to our attention. When you set `disable-auth="true"` for `<elsa-studio>`, it's essential to ensure that the server-side authentication is appropriately configured. If you disable login on the client side, there are a couple of approaches you can consider:

1. Implement a plugin that provides authentication for outgoing HTTP requests.
2. Modify the server configuration to accept anonymous requests, ensuring that it doesn't compromise the security of your application.
