### ISSUE TITLE
Mismatched trigger hashes generated for Bookmarks when using KafkaMessageReceived activity

### ISSUE THREAD

**Issue by dwoldo** [elsa-workflows/elsa-core#4192]
The Hash generated when receiving a Kafka message and the Hash generated when storing KafkaMessageReceived triggers are not the same when one does not provide a schema for the `KafkaMessageReceived` activity.

This is the JSON string when creating a hash for the received Kafka message:
`{"Topic":"workflow-7dff8d01b5034b8d94d7a81aab0f8adb","Group":"cg-7dff8d01b5034b8d94d7a81aab0f8adb","ConnectionString":"host.docker.internal:19092","AutoOffsetReset":1,"Headers":{},"IgnoreHeaders":true,"Schema":""}`

and this is the JSON string used to create the hash for the trigger:
`
{"Topic":"workflow-7dff8d01b5034b8d94d7a81aab0f8adb","Group":"cg-7dff8d01b5034b8d94d7a81aab0f8adb","ConnectionString":"host.docker.internal:19092","AutoOffsetReset":1,"Headers":{},"IgnoreHeaders":true,"Schema":null}`

The only difference is: `Schema` is null vs quoted empty string.

Two lines I believe are related:

https://github.com/elsa-workflows/elsa-core/blob/716ff3bba92ab0436754400e1cad0deaed065f2d/src/activities/Elsa.Activities.Kafka/Activities/KafkaMessageReceived/KafkaMessageReceived.cs#L71

and

https://github.com/elsa-workflows/elsa-core/blob/716ff3bba92ab0436754400e1cad0deaed065f2d/src/activities/Elsa.Activities.Kafka/Bookmarks/MessageReceivedBookmark.cs#L40C15-L40C15

The impact is that my workflow trigger is never found.

**Comment by sfmskywalker** [comment]
Hello @dwoldo,

Thank you for detailing the issue with the mismatched trigger hashes for Bookmarks when using the `KafkaMessageReceived` activity. If you have a potential fix, please consider submitting a Pull Request.

Thanks for your contribution!

**Comment by dwoldo** [comment]
It appears to have been resolved in #4105
