### ISSUE TITLE
Elsa 3 - edit workflow name then pressing enter opens the wrong modal

### ISSUE THREAD

**Issue by MariusVuscanNx** [elsa-workflows/elsa-core#4193]
When you alter the name of a workflow and the cursor is in the textbox, pressing [ENTER] on the keyboard will show the ‘variable editor’, which is unexpected.

**Comment by sfmskywalker** [comment]
Hi @MariusVuscanNx , thanks for reporting this issue!

Since we'll be retiring the Stencil implementation of the V3 designer in favor of the Blazor implementation, we're going to leave this issue as unresolved (unless someone wants to do it, that is fine of course).
