### ISSUE TITLE
Elsa 3 - Duplicate key violates unique constraint

### ISSUE THREAD

**Issue by MariusVuscanNx** [elsa-workflows/elsa-core#4194]
We are using a custom workflow provider. The implementation is similar to the blob provider available in Elsa code. The only difference is how it retrieves the workflows.

From time to time, we get this error of duplicate definition id. We are certain that we don't have the same definitionId/versionId in two workflows, we check this every time we get the error. Usually, the quick fix consists in changing the guid with a new one.

**Error**:
Exception data:
    Severity: ERROR
    SqlState: 23505
    MessageText: duplicate key value violates unique constraint "IX_WorkflowDefinition_DefinitionId_Version"
    Detail: Detail redacted as it may contain sensitive data. Specify 'Include Error Detail' in the connection string to include this information.
    SchemaName: Elsa
    TableName: WorkflowDefinitions
    ConstraintName: IX_WorkflowDefinition_DefinitionId_Version
    File: nbtinsert.c
    Line: 656
    Routine: _bt_check_unique
   --- End of inner exception stack trace ---

**Comment by sfmskywalker** [comment]
@MariusVuscanNx I haven't heard about this for a while now. Do you think we can close it as "can't reproduce"?

**Comment by MariusVuscanNx** [comment]
@sfmskywalker Yes!
