### ISSUE TITLE
Which is the proper branch for 2.x release?

### ISSUE THREAD

**Issue by bryanrideshark** [elsa-workflows/elsa-core#4200]
We need to have support for .NET Standard 2.0. We are going to take the route of forking, and downgrading manually; We must support .NET Framework for a few years, and have no alternatives.

Which is the best branch to take? We are starting with master, but perhaps the better solution is to use a different branch?

Any insight is appreciated! Great project, a really impressive feat.

**Comment by sfmskywalker** [comment]
The `master` branch contains the latest Elsa 2 features, so I think that’s the best branch to fork.

Thank you for the kind words and good luck with the project!

**Comment by johnwc** [comment]
I think you mean you want to target net48 and not netstandard. A few packages cannot target netstandard2.0, so you'll have to target net48. I would first just try adding net48; to all of the projects targetframeworks and see if it compiles, then work from there.
