### ISSUE TITLE
Elsa3 Custom Activity's not Publishing - bug

### ISSUE THREAD

**Issue by adolfie450** [elsa-workflows/elsa-core#4205]
hi

When I have a Custom activity I drag it into the designer, create the workflow, however it does not publish. the publish button just says "publishing" but it never takes it out of draft or create a version.  When I create a workflow with the "Built in" activity's then the publish works fine as designed. 

There is nothing in the Notification feed, all the Items are blank

**Comment by sfmskywalker** [comment]
It sounds like as if an error occurs somewhere. Could you check your browser’s console for any errors?

**Comment by adolfie450** [comment]
here is the browser output, it it seems like it doesn't save the workflow. 

![image](https://github.com/elsa-workflows/elsa-core/assets/40174198/4f7dd742-b74d-49f9-95d0-3b693663124b)



`TypeError: t.replace is not a function
    SS https://localhost:44357/_content/Elsa.Workflows.Designer/elsa-workflows-designer/p-7d146e43.js:2
    render https://localhost:44357/_content/Elsa.Workflows.Designer/elsa-workflows-designer/p-c9c6a23f.entry.js:1
    ot https://localhost:44357/_content/Elsa.Workflows.Designer/elsa-workflows-designer/p-a7a3baa1.js:2
    lt https://localhost:44357/_content/Elsa.Workflows.Designer/elsa-workflows-designer/p-a7a3baa1.js:2
    nt https://localhost:44357/_content/Elsa.Workflows.Designer/elsa-workflows-designer/p-a7a3baa1.js:2
    st https://localhost:44357/_content/Elsa.Workflows.Designer/elsa-workflows-designer/p-a7a3baa1.js:2
    nt https://localhost:44357/_content/Elsa.Workflows.Designer/elsa-workflows-designer/p-a7a3baa1.js:2
    et https://localhost:44357/_content/Elsa.Workflows.Designer/elsa-workflows-designer/p-a7a3baa1.js:2
    Vt https://localhost:44357/_content/Elsa.Workflows.Designer/elsa-workflows-designer/p-a7a3baa1.js:2
    _t https://localhost:44357/_content/Elsa.Workflows.Designer/elsa-workflows-designer/p-a7a3baa1.js:2
    raf https://localhost:44357/_content/Elsa.Workflows.Designer/elsa-workflows-designer/p-a7a3baa1.js:2
    It https://localhost:44357/_content/Elsa.Workflows.Designer/elsa-workflows-designer/p-a7a3baa1.js:2
    et https://localhost:44357/_content/Elsa.Workflows.Designer/elsa-workflows-designer/p-a7a3baa1.js:2
    ht https://localhost:44357/_content/Elsa.Workflows.Designer/elsa-workflows-designer/p-a7a3baa1.js:2
    set https://localhost:44357/_content/Elsa.Workflows.Designer/elsa-workflows-designer/p-a7a3baa1.js:2
    begin https://localhost:44357/_content/Elsa.Workflows.Designer/elsa-workflows-designer/p-46431009.entry.js:1
    onPublishClicked https://localhost:44357/_content/Elsa.Workflows.Designer/elsa-workflows-designer/p-7d146e43.js:2
    x https://localhost:44357/_content/Elsa.Workflows.Designer/elsa-workflows-designer/p-a7a3baa1.js:2
    emit https://localhost:44357/_content/Elsa.Workflows.Designer/elsa-workflows-designer/p-a7a3baa1.js:2
    onPublishClick https://localhost:44357/_content/Elsa.Workflows.Designer/elsa-workflows-designer/p-46431009.entry.js:1
    handler https://localhost:44357/_content/Elsa.Workflows.Designer/elsa-workflows-designer/p-46431009.entry.js:1
    ael https://localhost:44357/_content/Elsa.Workflows.Designer/elsa-workflows-designer/p-a7a3baa1.js:2
    N https://localhost:44357/_content/Elsa.Workflows.Designer/elsa-workflows-designer/p-a7a3baa1.js:2
    D https://localhost:44357/_content/Elsa.Workflows.Designer/elsa-workflows-designer/p-a7a3baa1.js:2
    G https://localhost:44357/_content/Elsa.Workflows.Designer/elsa-workflows-designer/p-a7a3baa1.js:2
    V https://localhost:44357/_content/Elsa.Workflows.Designer/elsa-workflows-designer/p-a7a3baa1.js:2
    G https://localhost:44357/_content/Elsa.Workflows.Designer/elsa-workflows-designer/p-a7a3baa1.js:2
    V https://localhost:44357/_content/Elsa.Workflows.Designer/elsa-workflows-designer/p-a7a3baa1.js:2
    G https://localhost:44357/_content/Elsa.Workflows.Designer/elsa-workflows-designer/p-a7a3baa1.js:2
    Z https://localhost:44357/_content/Elsa.Workflows.Designer/elsa-workflows-designer/p-a7a3baa1.js:2
    ot https://localhost:44357/_content/Elsa.Workflows.Designer/elsa-workflows-designer/p-a7a3baa1.js:2
    lt https://localhost:44357/_content/Elsa.Workflows.Designer/elsa-workflows-designer/p-a7a3baa1.js:2
    nt https://localhost:44357/_content/Elsa.Workflows.Designer/elsa-workflows-designer/p-a7a3baa1.js:2
    st https://localhost:44357/_content/Elsa.Workflows.Designer/elsa-workflows-designer/p-a7a3baa1.js:2
    nt https://localhost:44357/_content/Elsa.Workflows.Designer/elsa-workflows-designer/p-a7a3baa1.js:2
    et https://localhost:44357/_content/Elsa.Workflows.Designer/elsa-workflows-designer/p-a7a3baa1.js:2
    Vt https://localhost:44357/_content/Elsa.Workflows.Designer/elsa-workflows-designer/p-a7a3baa1.js:2
    _t https://localhost:44357/_content/Elsa.Workflows.Designer/elsa-workflows-designer/p-a7a3baa1.js:2
    raf https://localhost:44357/_content/Elsa.Workflows.Designer/elsa-workflows-designer/p-a7a3baa1.js:2
    It https://localhost:44357/_content/Elsa.Workflows.Designer/elsa-workflows-designer/p-a7a3baa1.js:2
    et https://localhost:44357/_content/Elsa.Workflows.Designer/elsa-workflows-designer/p-a7a3baa1.js:2
    ft https://localhost:44357/_content/Elsa.Workflows.Designer/elsa-workflows-designer/p-a7a3baa1.js:2
    set https://localhost:44357/_content/Elsa.Workflows.Designer/elsa-workflows-designer/p-144a434e.js:1
    a https://localhost:44357/_content/Elsa.Workflows.Designer/elsa-workflows-designer/p-144a434e.js:1
    a https://localhost:44357/_content/Elsa.Workflows.Designer/elsa-workflows-designer/p-144a434e.js:1
    set https://localhost:44357/_content/Elsa.Workflows.Designer/elsa-workflows-designer/p-144a434e.js:1
    updateNotification https://localhost:44357/_content/Elsa.Workflows.Designer/elsa-workflows-designer/p-4031f4ff.js:2
    onPublishClicked https://localhost:44357/_content/Elsa.Workflows.Designer/elsa-workflows-designer/p-7d146e43.js:2
    promise callback*DE/this.onPublishClicked https://localhost:44357/_content/Elsa.Workflows.Designer/elsa-workflows-designer/p-7d146e43.js:2
 
`

**Comment by sfmskywalker** [comment]
Are you using Rc1 by any chance? If yes, then I think this particular issue with the `t.replace` issue has been fixed in later packages (see the feedz.io feed for more up to date builds). However, it might not be the actual issue. Do you have any errors occurring in your ASP.NET Core application console output?

**Comment by adolfie450** [comment]
hi
thanks, I dont see an error popping up in the logs, but I tend to think it could be the way I have written my custom activity. 

Could you provide a simple example of a custom activity, with 2 outputs/outcomes, "pass / fail" that I can link to other activity's.

then I will compare and revert back.

**Comment by sfmskywalker** [comment]
Sure, here you go:

```csharp
using Elsa.Workflows.Core.Activities.Flowchart.Attributes;
using Elsa.Workflows.Core.Attributes;
using Elsa.Workflows.Core.Models;

namespace Elsa.WorkflowServer.Web;

[Activity("Sample", Category = "Sample", Description = "Sample activity.")]
[FlowNode("Pass", "Fail")]
public class SampleActivity : CodeActivity
{
}
```

**Comment by adolfie450** [comment]
thanks, how to you target the outcomes such as

`[Activity("Sample", Category = "Sample", Description = "Sample activity.")]
[FlowNode("Pass", "Fail")]
public class SampleActivity : CodeActivity
{
    if(2 > 1)
   {
      return Outcome["Pass"];
}
else
      return Outcome["Fail"] /// i know that outcomes are not in V3 you use Flow Nodes
}`

**Comment by sfmskywalker** [comment]
Like this:

``csharp
using Elsa.Workflows.Core.Activities.Flowchart.Attributes;
using Elsa.Workflows.Core.Attributes;
using Elsa.Workflows.Core.Models;

namespace Sample;

[Activity("Sample", Category = "Sample", Description = "Sample activity.")]
[FlowNode("Pass", "Fail")]
public class SampleActivity : CodeActivity
{
    protected override async ValueTask ExecuteAsync(ActivityExecutionContext context)
    {
        var outcome = 2 > 1 ? "Pass" : "Fail";

        await context.CompleteActivityAsync(new Outcomes(outcome));
    }
}
```

**Comment by adolfie450** [comment]
thank you

i will try this, 

I was using the Following  await context.CompleteActivityWithOutcomesAsync("SMS_Failed"); and this was causing the workflow to not publish. the origin of the bug.

**Comment by sfmskywalker** [comment]
That should have worked as well, since it's an extension method that does the same thing:

```csharp
public static ValueTask CompleteActivityWithOutcomesAsync(this ActivityExecutionContext context, params string[] outcomes) => context.CompleteActivityAsync(new Outcomes(outcomes));
```

I don't think the implementation of the activity's `ExecuteAsync` method will affect the publish routine. If it does, I'd be wildly curious to understand why.

**Comment by adolfie450** [comment]
ok so with a bit of investigating the following code works

`namespace Elsa3.Activities
{
    [Activity(
       "myNameSpace", "FormFlow", "Simple activity ")]
    [FlowNode("Pass", "Fail")]
    public class simpleActivity:CodeActivity
    {
        public Input<string> Name { get; set; }
        public Input<string> Message { get; set; }

        protected override async ValueTask ExecuteAsync(ActivityExecutionContext context)
        {
            var outcome = 2 > 1 ? "Pass" : "Fail";

            await context.CompleteActivityAsync(new Outcomes(outcome));
        }
    }

}`

but if you pull in a constructor with dependency injection it refuses to publish/save 

` [Activity(
       "myNameSpace", "FormFlow", "Simple activity ")]
    [FlowNode("Pass", "Fail")]
    public class simpleActivity:CodeActivity
    {
        public Input<string> Name { get; set; }
        public Input<string> Message { get; set; }

        public IApiService _apiService { get; set; }

        public simpleActivity(IApiService apiService)
        {
            _apiService = apiService;
        }

        protected override async ValueTask ExecuteAsync(ActivityExecutionContext context)
        {
            var outcome = 2 > 1 ? "Pass" : "Fail";

            await context.CompleteActivityAsync(new Outcomes(outcome));
        }
    }`

**Comment by adolfie450** [comment]
this seems to be related to the issue #4128 , I will mark it as closed as it works now.
We just need to update the Documentation about this, I will be happy to do it. 

Thank you

**Comment by sfmskywalker** [comment]
Indeed, activities are not currently resolved from the DI for reasons explained in the issue you referenced.

I am considering adding support for constructor injection as well as property injection (like Blazor components).
The only downside of creating activities with DI through constructor and/or property is that you would have to resolve these activities from DI at workflow-build-time when defining workflows in C#.

**Comment by adolfie450** [comment]
I propose to add a section to the Documentation, regarding this, to assist someone else who will have a similar problem, if it changes later we can modify the documentation accordingly. To avoid frustration and another bug/issue being raised about this.

**Comment by sfmskywalker** [comment]
Makes sense!
