### ISSUE TITLE
Can Elsa support PWA and ASP.net Core hosting project?

### ISSUE THREAD

**Issue by Jauhuei** [elsa-workflows/elsa-core#4210]
Hi,

I just started doing Elsa Workflow using PWA with ASP.not Core hosting.
And I want to be able to run the normal web interface at the same time.
I've successfully combined the Elsa Dashboard with the web page. But I can't trigger Elsa HttpEndPoint through browser http.
How to set it on Program.cs of Server and Client?

**Comment by dwoldo** [comment]
Hi @Jauhuei 

We've recently deployed a simple example of this. This example project in the Elsa core Samples helped us: [Elsa.Samples.HelloWorldHttp Startup.us](https://github.com/elsa-workflows/elsa-core/blob/2.12.x/src/samples/aspnet/Elsa.Samples.HelloWorldHttp/Startup.cs
)

Docs have information here as well: https://v2.elsaworkflows.io/docs/installation/server#:~:text=Add%20Package-,Startup,-The%20following%20Startup

## Basic Steps
1. Install [Elsa.Activities.Http](https://www.nuget.org/packages/Elsa.Activities.Http/2.12.0#readme-body-tab)
2. Register in Startup.cs according to the example project above
3. Add the `Receive Http Request` activity via the designer, choose GET for the verb, and specify relative URL (MUST start with a forward-slash `/`)
4. Visit via the browser the URL of your dashboard (assuming like [http://localhost:1234/{relative_url_from_designer}](http://localhost:1234/{relative_url_from_designer}))
5. Review the completed workflow execution by visiting the `Workflow Instances`  tab in the designer.

**Comment by Jauhuei** [comment]
Hi @dwoldo ,

I tried to simplify and simplify the code, remove other components, Elsa Dashboard and HttpEndPoint can work normally in ASP.NetCore hosting and PWA mode.

https://github.com/Jauhuei/MyElsaWASM

**Comment by Jauhuei** [comment]
It seems that Swagger and HttpEndPoint cannot exist at the same time?
If Swagger/UI is added, Http Get cannot be triggered through the browser.
