### ISSUE TITLE
Elsa 3 - workflow instances order when using publish event activity

### ISSUE THREAD

**Issue by MariusVuscanNx** [elsa-workflows/elsa-core#4218]
Having two workflows (first, second). The first one publishes an event using the "Publish event activity" and the second one is triggered by that event because it starts with an "Event" activity.

The execution order in the workflow instances is sometimes wrong. Meaning that the second workflow appears first.

As an observation, the execution time of both workflows is the same (same second). My assumption is that the millisecond is not taken into consideration when doing the ordering.

**Comment by sfmskywalker** [comment]
Certainly! Here's the response for the issue:

---

Hello,

I've attempted to reproduce the issue you described. When I run a workflow that publishes an event, subsequently triggering another workflow, I observe that both instances are indeed created in the same second. However, the sort order appears to be consistently correct on my end.

To help me further investigate, would you be able to reproduce this issue on your local machine using a SQLite database? If you can, please share that database with me. This will allow me to take a closer look and better understand the circumstances leading to the behavior you're experiencing.

Thank you for bringing this to our attention. Your feedback is crucial in helping us improve Elsa Workflows.
