### ISSUE TITLE
Do I must have a bookmark for a blocked activity to resume?

### ISSUE THREAD

**Issue by liuliang-wt** [elsa-workflows/elsa-core#4219]
Is there a simply way to resume a blocked workflow by providing its workflow instance id?

**Comment by sfmskywalker** [comment]
At the moment, yes you need a bookmark, but I think we should be able to support scenarios where you can resume workflows if you know the workflow instance ID.

**Comment by liuliang-wt** [comment]
I hope this can be done. Currently I have to create bookmark class and bookmark provider for my customer activity, but I don't really need to store any extra info in the bookmark, it feels quite redundant.

**Comment by sfmskywalker** [comment]
Hi @liuliang-wt 

It is now possible to resume blocking activities without creating bookmark payloads.

As an example, consider this custom activity:

```csharp
public class MyBlockingActivity : Activity
{
    protected override void Execute(ActivityExecutionContext context)
    {
        context.CreateBookmark(ResumeAsync);
    }

    private async ValueTask ResumeAsync(ActivityExecutionContext context)
    {
        await context.CompleteActivityAsync();
    }
}
```

When this activity executes, it will create a bookmark, but without a payload.
To resume workflows blocked on this activity, you can use the new `WorkflowInbox` API. For example:

```csharp
var message = new NewWorkflowInboxMessage
{
    ActivityTypeName = ActivityTypeNameHelper.GenerateTypeName<MyBlockingActivity>(),
    WorkflowInstanceId = _workflowInstanceId // This is optional - without it, all workflow instances will be resumed if they are blocked on this activity.
};

// Submit the message to the inbox.
await _workflowInbox.SubmitAsync(message, cancellationToken);
```

I hope this helps, but let me know if you need any additional information!
