### ISSUE TITLE
elsa 3 preview - editing Settings on a workflow activity doesn't change Published/Draft status

### ISSUE THREAD

**Issue by rysweet** [elsa-workflows/elsa-core#4234]
Repro:
1. Create a workflow, edit the settings on an activity, publish. 
2. change the settings on an activity, status doesn't change to draft. 
3. run workflow, new settings aren't used. 
4. drag something on the canvas, status changes to Draft
5. Publish again
6. run workflow again, new settings are used. 

        <PackageReference Include="Elsa" Version="3.0.0-preview.541" />

**Comment by sfmskywalker** [comment]
Hello Ryan,

Thank you for reporting this issue. I've tried to reproduce the problem based on the steps you provided but couldn't replicate it on my end. It's possible that the issue might have been resolved in a subsequent release.

Could you please try with the latest version of Elsa and see if the problem persists? If you can still reproduce the issue, kindly reopen this issue with any additional details that might help us investigate further.

Thanks for your understanding and cooperation!
