### ISSUE TITLE
sometimes UI gets stuck and has to hard reload

### ISSUE THREAD

**Issue by rysweet** [elsa-workflows/elsa-core#4235]
"Elsa" Version="3.0.0-preview.541"

Using Safari (Version 16.5.1 (18615.2.9.11.7) on OSX 13.4.1 (22F82)

Sometimes when editing a workflow in the designer, one pane or another gets "stuck" - it won't any longer load content.  Mostly have seen this with the Activity Settings pane, but also with the dialog that pops up when you hit "Publish", once with the Canvas, and once with the Workflow Settings pane. Once this happens most other steps won't work until the app is reloaded with shift-reload. I wish I could document a repro but it seems random so far.

**Comment by sfmskywalker** [comment]
When this happens, please take a look SThree browser console. It might reveal additional information, perhaps some JS error.
