### ISSUE TITLE
"@elsa-workflows/elsa-workflows-studio" which requires "tslint", which is deprecated

### ISSUE THREAD

**Issue by hiteshkotharinn** [elsa-workflows/elsa-core#4236]
"@elsa-workflows/elsa-workflows-studio" which requires **tslint**, which is deprecated and is not maintained anymore.

tslint also depends on "semver": "^5.3.0", which has a known vulnerability.

 @sfmskywalker @milkyware Can you please let me know when is the plan to remove **tslint** from dependency?

**Comment by sfmskywalker** [comment]
Please feel free to open a PR.

**Comment by marvingreeven** [comment]
Please see #4238
