### ISSUE TITLE
d3-color is vulnerable to ReDoS (Regular Expression Denial of Service)

### ISSUE THREAD

**Issue by hiteshkotharinn** [elsa-workflows/elsa-core#4237]
"@elsa-workflows/elsa-workflows-studio" depends on **"dagre-d3": "^0.6.4"**, which depends on **"d3": "^5.14"**, which depends on **"d3-color": "1"**. Which is vulnerable to Remote DoS: https://github.com/advisories/GHSA-36jr-mh4h-2g58

@sfmskywalker @milkyware Can you please let me know when the plan is to update the version of "d3-color"?

**Comment by sfmskywalker** [comment]
Please feel free to open a PR.
