### ISSUE TITLE
CurrentScope is incorrect

### ISSUE THREAD

**Issue by hyzx86** [elsa-workflows/elsa-core#424]
In the first iteration, a new scope will be created and pushed onto the top of the stack. CurrentScope is now a scope at the top of the stack, 
In the second iteration (perhaps in the next activity), the stack order is reversed and CurrentScope becomes the oldest Scope

My code only solved my problem, I didn't find the reason for stack inversion.
https://github.com/elsa-workflows/elsa-core/pull/423

**Comment by hyzx86** [comment]
https://github.com/elsa-workflows/elsa-core/pull/342

Perhaps it is related to this PR. In order to make the function available in other places in the code, the stack is still reversed.

**Comment by sfmskywalker** [comment]
Fixed in https://github.com/elsa-workflows/elsa-core/pull/427
