### ISSUE TITLE
Set Variable activities, sometimes set blank

### ISSUE THREAD

**Issue by rahuljain003** [elsa-workflows/elsa-core#4242]
Hii team,

I have a worker service that identified a pending task from database and dispatch workflow with setting a variable. It's execute fine if single entry into dB. But in case of bulk insert Set Variable not working. It's setting a null value into the object.
Some screens I am attaching for reference. Is anything else that I am missing . Please help me out...

![1](https://github.com/elsa-workflows/elsa-core/assets/66092221/4fc08e2f-5dfd-499c-899d-3a771e021902)
![2](https://github.com/elsa-workflows/elsa-core/assets/66092221/1903770d-1bbc-4d41-be95-ebe3153e351c)

**Comment by sfmskywalker** [comment]
I don’t see any issues, can you show the code that performs the bulk insert?

**Comment by rahuljain003** [comment]
It's only a web service that inserting data on thread basis.  I am showing a code that are fatching data from database and executing a  workflow.. Look at this 

protected override async Task ExecuteAsync(CancellationToken cancellationToken)
        {
            while (!cancellationToken.IsCancellationRequested)
            {
                try
                {
                    _logger.LogInformation("Worker running at: {time}", DateTimeOffset.Now);

                    using var scope = _serviceProvider.CreateScope();
                    // Get Service Order and dispatch relavent workflow

                    var responseDTO = await _mediator.Send(new GetNewServiceOrderQuery(), cancellationToken);

                    if (responseDTO != null && responseDTO.Data != null)
                    {
                        _logger.LogDebug("Total ServiceOrder : {count}", responseDTO.Data.Count);
                        foreach (var so in responseDTO.Data)
                        {
                            try
                            {
                                _logger.LogInformation("Started pre-steps to dispatch workflow");

                                //Check mapping already available
                                var responseMapping = await _mediator.Send(new GetServiceOrderWorkflowMappingQuery(so.ServiceOrderId), cancellationToken);
                                if (responseMapping != null && responseMapping.ResultCode == 0 && responseMapping.Data != null)
                                {
                                    _logger.LogInformation($"Workflow already exist with workflowinstanceid - {responseMapping.Data.WorkflowInstanceId!} - ");
                                    await DispatchWorkflow(scope, so, responseMapping.Data.WorkflowInstanceId!);
                                    _logger.LogInformation($"Workflow dispatched successfully with workflowinstanceid - {responseMapping.Data.WorkflowInstanceId!} - ");

                                }
                                else
                                {
                                    // Get a workflow builder. This is a transient service.
                                    var workflowRegistry = scope.ServiceProvider.GetRequiredService<IWorkflowRegistry>();

                                    // Build a workflow.
                                    var ServiceOrderWorkflow = await workflowRegistry.FindByNameAsync(so.WorkflowName!, VersionOptions.Published, cancellationToken: cancellationToken);
                                    if (ServiceOrderWorkflow != null)
                                    {
                                        // Create a workflow instance.
                                        var workflowFactory = scope.ServiceProvider.GetRequiredService<IWorkflowFactory>();
                                        var workflowInstance = await workflowFactory.InstantiateAsync(ServiceOrderWorkflow!, cancellationToken: cancellationToken);

                                        // Persist the workflow instance before dispatching.
                                        var workflowInstanceStore = scope.ServiceProvider.GetRequiredService<IWorkflowInstanceStore>();
                                        await workflowInstanceStore.SaveAsync(workflowInstance, cancellationToken: cancellationToken);

                                        _logger.LogInformation("Ended pre-steps to dispatch workflow");

                                        var MappingObj = new ServiceOrderWFMapping()
                                        {
                                            ServiceOrderId = so.ServiceOrderId,
                                            WorkflowInstanceId = workflowInstance.Id,
                                            WorkflowCorrelationId = workflowInstance.CorrelationId,
                                            WorkflowDefinitionId = ServiceOrderWorkflow!.Id
                                        };

                                        var response = await _mediator.Send(new SaveServiceOrderWFCommand(MappingObj), cancellationToken: cancellationToken);

                                        _logger.LogDebug($"SaveSOWorkFlowMappingAsync() - {MappingObj.ServiceOrderId} - Ended");

                                        if (response != null && response.Data == 0)
                                        {
                                            await DispatchWorkflow(scope, so, workflowInstance.Id);
                                            _logger.LogDebug($"UpdateServiceOrderStatusAsync() - {MappingObj.ServiceOrderId} - Ended");
                                        }
                                    }
                                    else
                                    {
                                        _logger.LogInformation($"Workflow not available for Service Order Id:  {so.ServiceOrderId}");
                                    }

                                }
                            }
                            catch (Exception ex)
                            {
                                _logger.LogError($"ServiceOrderWorkder - Service Order Id: {so.ServiceOrderId} ,  Exception occured : {ex.InnerException?.Message ?? ex.Message}");

                            }
                        }
                    }
                }
                catch (Exception ex)
                {
                    _logger.LogError($"ServiceOrderWorker->ExecuteAsync() - Exception occured : {ex.InnerException?.Message ?? ex.Message}");

                }
            }
        }

        public async Task DispatchWorkflow(IServiceScope scope, ResponseServiceOrderDetailDTO so, string workflowInstanceId)
        {
            // Get workflow dispatcher.
            _logger.LogInformation($"Started dispatch workflow for Service Order Id-{so.ServiceOrderId}");
            var workflowInstanceStore = scope.ServiceProvider.GetRequiredService<IWorkflowInstanceStore>();
            var workflowinstance = await workflowInstanceStore.FindByIdAsync(workflowInstanceId).ConfigureAwait(false);
            if (workflowinstance != null && workflowinstance!.WorkflowStatus == WorkflowStatus.Idle)
            {
                var workflowDispatcher = scope.ServiceProvider.GetRequiredService<IWorkflowInstanceDispatcher>();
                await workflowDispatcher.DispatchAsync(new ExecuteWorkflowInstanceRequest(workflowInstanceId, null, new WorkflowInput(so)));
            }
            _logger.LogInformation($"Dispatched workflow for Service Order Id-{so.ServiceOrderId}");

        }
