### ISSUE TITLE
Elsa2/3 Liquid script is hardcoded to use HtmlEncoder, which is bad for user-readable data with non-latin symbols

### ISSUE THREAD

**Issue by regan32** [elsa-workflows/elsa-core#4244]
In Sources, TextEncoder for Fluid RenderAsync is hardcoded to HtmlEncoder.Default. In this way, any non-latin character is encoded to html format. This is unworkable, when i'm tring to process user readable data to output. " | raw" is not a solution because it's also ignoring escape symbols.
https://github.com/elsa-workflows/elsa-core/blob/master/src/scripting/Elsa.Scripting.Liquid/Extensions/LiquidTemplateManagerExtensions.cs#L15
https://github.com/elsa-workflows/elsa-core/blob/master/src/scripting/Elsa.Scripting.Liquid/Services/LiquidTemplateManager.cs#L35
вторым параметром в метод RenderAsync идет TextEncoder:
https://github.com/sebastienros/fluid#encoding

It's should be an option to configure Liquid script to use another ecoder, like TextEncoder with elsa startup configuration.

**Comment by sfmskywalker** [comment]
Fixed via #4380
