### ISSUE TITLE
REST API Call

### ISSUE THREAD

**Issue by arkhokhar** [elsa-workflows/elsa-core#4248]
Hi,
I am working on Elsa 3, I am trying to call workflow using workflow-definition-id using following request through POST-MAN,
but I am unable to execute my request and getting this error
![elsa 3](https://github.com/elsa-workflows/elsa-core/assets/114415858/b18238d1-a986-4c83-9203-c52e0e56db85)

**Comment by sfmskywalker** [comment]
What version is this? RC or latest preview?

**Comment by arkhokhar** [comment]
3.0.0-rc1

**Comment by arkhokhar** [comment]
already have the updated version no more update available in vs2022

![elsa 2](https://github.com/elsa-workflows/elsa-core/assets/114415858/2887181b-f9c5-4b71-bfb3-46058fc97022)

I am also try to debug this issue using your 2 branches v3-rc1 and v3, but when i am run the following project
"Elsa.Samples.WorkflowServerAndDesigner" , it will give me this error (any configuration that's I missed here ??)


![elsa 2_1](https://github.com/elsa-workflows/elsa-core/assets/114415858/5b5795ae-5180-4bbc-97fd-fae5b8419025)

![elsa 2_2](https://github.com/elsa-workflows/elsa-core/assets/114415858/529639f7-4124-4ef1-a5ed-4e7ce3db8ae8)

**Comment by sfmskywalker** [comment]
I see. Due to an unfortunate version scheme I chose for preview, the NuGet tooling thinks RC1 is the latest, but the latest packages are on the preview feed: https://f.feedz.io/elsa-workflows/elsa-3/nuget/index.json

When you have added this feed as a source, make sure to manually select the latest version (which is 3.0.0-preview.566 at the time of this writing).

**Comment by sfmskywalker** [comment]
> I am also try to debug this issue using your 2 branches v3-rc1 and v3, but when i am run the following project
"Elsa.Samples.WorkflowServerAndDesigner" , it will give me this error (any configuration that's I missed here ??)

When you want to run from source code from the `v3` branch, make sure to build the NPM packages first in the following folders:

- ./src/designer/designer_packages/elsa-workflows-designer
- ./src/modules/Elsa.Workflows.Designer

After that, you should be able to run the Elsa.AllInOne.Web project successfully.

**Comment by arkhokhar** [comment]
Hi,
As discussed after update all packages to 3.0.0-preview.566 from https://f.feedz.io/elsa-workflows/elsa-3/nuget/index.json,
I am facing the following error.

![elsa 3_!](https://github.com/elsa-workflows/elsa-core/assets/114415858/979f5a54-382e-43ea-90f5-e32139adf5a9)
![elsa 3_2](https://github.com/elsa-workflows/elsa-core/assets/114415858/ec2bc75c-f72f-4a01-84c8-885a095269e2)

**Comment by sfmskywalker** [comment]
The error states that no JSON body was included with the request. Try sending the request with an (empty) JSON body.

**Comment by arkhokhar** [comment]
Now i am trying to create correlation Id using Correlation Activity, using the following function

1. getGuid()
2. getGuidString()

but getting this error,

errorMessage": "Workflow faulted with error: getGuid is not defined".

```

exception": {
                "type": "Jint.Runtime.JavaScriptException, Jint",
                "message": "getGuid is not defined",
                "stackTrace": "   at Jint.Engine.ScriptEvaluation(ScriptRecord scriptRecord)\r\n   at Jint.Engine.<>c__DisplayClass71_0.<Execute>b__0()\r\n   at Jint.Engine.ExecuteWithConstraints[T](Boolean strict, Func`1 callback)\r\n   at Jint.Engine.Execute(Script script)\r\n   at Jint.Engine.Evaluate(Script script)\r\n   at Jint.Engine.Evaluate(String code, String source, ParserOptions parserOptions)\r\n   at Jint.Engine.Evaluate(String code)\r\n   at Elsa.JavaScript.Services.JintJavaScriptEvaluator.ExecuteExpressionAndGetResult(Engine engine, String expression)\r\n   at Elsa.JavaScript.Services.JintJavaScriptEvaluator.EvaluateAsync(String expression, Type returnType, ExpressionExecutionContext context, Action`1 configureEngine, CancellationToken cancellationToken)\r\n   at Elsa.JavaScript.Expressions.JavaScriptExpressionHandler.EvaluateAsync(IExpression expression, Type returnType, ExpressionExecutionContext context)\r\n   at Elsa.Expressions.Services.ExpressionEvaluator.EvaluateAsync(IExpression expression, Type returnType, ExpressionExecutionContext context)\r\n   at Elsa.Extensions.ActivityExecutionContextExtensions.EvaluateInputPropertyAsync(ActivityExecutionContext context, ActivityDescriptor activityDescriptor, InputDescriptor inputDescriptor)\r\n   at Elsa.Extensions.ActivityExecutionContextExtensions.EvaluateInputPropertiesAsync(ActivityExecutionContext context)\r\n   at Elsa.Workflows.Core.Middleware.Activities.DefaultActivityInvokerMiddleware.EvaluateInputPropertiesAsync(ActivityExecutionContext context)\r\n   at Elsa.Workflows.Core.Middleware.Activities.DefaultActivityInvokerMiddleware.InvokeAsync(ActivityExecutionContext context)\r\n   at Elsa.Workflows.Core.Middleware.Activities.NotificationPublishingMiddleware.InvokeAsync(ActivityExecutionContext context)\r\n   at Elsa.Workflows.Core.Middleware.Activities.ExecutionLogMiddleware.InvokeAsync(ActivityExecutionContext context)\r\n   at Elsa.Workflows.Core.Middleware.Activities.ExceptionHandlingMiddleware.InvokeAsync(ActivityExecutionContext context)",
                "innerException": {
                    "type": "Jint.Runtime.JavaScriptException+JavaScriptErrorWrapperException, Jint",
                    "message": "getGuid is not defined",
                    "stackTrace": "   at <anonymous>:1:1"
                }
            },
```
