### ISSUE TITLE
Elsa Dashboard Page Navigation is not working

### ISSUE THREAD

**Issue by jayachandra21** [elsa-workflows/elsa-core#425]
Hi,

In Elsa Dashboard, there are more than **10,000** finished workflow instances. When I click on the "**Finished**" instances I have observed two issues:

-  Elsa dashboard shows the all "**Finished**" records in single page and it's taking time to load the page with all records.
- Page navigation is not working

![image](https://user-images.githubusercontent.com/67507118/97155257-247a8d80-1786-11eb-8fd6-aea75d3033e0.png)

![image](https://user-images.githubusercontent.com/67507118/97155218-0f9dfa00-1786-11eb-8491-6a16464d96c1.png)

**Comment by Va55ago** [comment]
I also noticed that the "History" button isn't working in my dashboard.
![image](https://user-images.githubusercontent.com/16526013/97471358-8979e300-1940-11eb-9ab2-978ad3ec8e52.png)

... If you'd prefer this this as a separate issue, I can easily create one.

**Comment by sfmskywalker** [comment]
It's fine to keep this issue here. Thanks!

**Comment by toby11** [comment]
any feedback on why the history button does not work? I have the same issue.

**Comment by sfmskywalker** [comment]
The history is a placeholder link at the moment. It will be implemented in the new Elsa V2 dashboard that is currently in progress. Perhaps we should just remove it from the menu for now to avoid confusion.

**Comment by sfmskywalker** [comment]
V2 is set to be released before the end of Q1 2021 or before, depending on the progress of the new dashboard + designer.

The elsa-designer will be replaced with a new implementation (initially done in React + Blazor, and might be re-done as a pure web component again with wrappers for it in React, Angular, Vue and Blazor). First priority is to at least have a functioning dashboard + designer that is on-part with V1, and release new features and improvements from there.

**Comment by toby11** [comment]
@sfmskywalker ok great to know - looks really promising what I have looked at so far. thanks

**Comment by toby11** [comment]
@sfmskywalker one other question in the workflow designer when adding criteria or expressions I would expect to have a data dictionary if working with custom objects (autocomplete would be good) is this something thats in the road map as well?

**Comment by sfmskywalker** [comment]
Most certainly, this is something that will be implemented as part of the Blazor implementation of the dashboard initially, and potentially in other SPA versions of the dashboard as well. I'm maintaining a list of items to be planned for [here](https://github.com/elsa-workflows/elsa-core/issues/468) (notice that the first item mentions expression editors with intellisense). It's one of the first features to implement once we got a basic dashboard up and running for Elsa 2.

**Comment by sfmskywalker** [comment]
The pagination thing has been implemented in the Elsa 2 dashboard (for workflow instances only for now - other pages are under continuous development).
