### ISSUE TITLE
Parallel ForEach activity

### ISSUE THREAD

**Issue by sfmskywalker** [elsa-workflows/elsa-core#4250]
With Elsa 3, it should now be possible to implement a true parallel foreach activity that meets the following criteria:

- Each activity in the Body port should be scheduled immediately.
- Although the activity scheduler (the work queue) processes work items sequentially, Job activities (Kind = Job) run in the background and Task activities (Kind = Task) can be configured by the user to run in the background. This effectively enables parallel activity execution, despite the fact that they are scheduled sequentially. 
- When an activity in the Body port creates a bookmark, it includes the Activity Instance ID. This information can be used to resume the activity in the appropriate iteration.

When this feature is successfully implemented, it means we have all the necessary structures in place and that we can close #1059

**Comment by sfmskywalker** [comment]
Done via https://github.com/elsa-workflows/elsa-core/pull/4306

**Comment by Dom1w** [comment]
@sfmskywalker is there a minimal working code example somewhere as a reference? As soon as I set my activities RunAsynchronously to true, they aren't executed anymore. Are there any insights? https://github.com/elsa-workflows/elsa-core/discussions/5080 and https://github.com/elsa-workflows/elsa-core/discussions/5431 seem to have the same issue.

**Comment by sfmskywalker** [comment]
I just tested with the following workflow using the current version on the main branch (which is being built into 3.3.-preview builds), and it seems to work well. Notice that the SendHttpRequest activity is configured to run asynchronously.

[parallel-loop.json](https://github.com/user-attachments/files/17714170/parallel-loop.json)
