### ISSUE TITLE
I found an exception while debugging the project

### ISSUE THREAD

**Issue by mrh520** [elsa-workflows/elsa-core#4261]
![image](https://github.com/elsa-workflows/elsa-core/assets/20501328/25e66ae3-b34c-4f80-9b36-2bada031ae22)
System.InvalidOperationException
  HResult=0x80131509
  Message=Unable to resolve service for type 'Microsoft.Extensions.Configuration.IConfiguration' while attempting to activate 'Elsa.Liquid.Handlers.ConfigureLiquidEngine'.
  Source=Microsoft.Extensions.DependencyInjection
  StackTrace:
   在 Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.CreateArgumentCallSites(Type implementationType, CallSiteChain callSiteChain, ParameterInfo[] parameters, Boolean throwIfCallSiteNotFound)
   在 Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.CreateConstructorCallSite(ResultCache lifetime, Type serviceType, Type implementationType, CallSiteChain callSiteChain)
   在 Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.TryCreateExact(ServiceDescriptor descriptor, Type serviceType, CallSiteChain callSiteChain, Int32 slot)
   在 Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.TryCreateEnumerable(Type serviceType, CallSiteChain callSiteChain)
   在 Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.CreateCallSite(Type serviceType, CallSiteChain callSiteChain)
   在 Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.GetCallSite(Type serviceType, CallSiteChain callSiteChain)
   在 Microsoft.Extensions.DependencyInjection.ServiceProvider.CreateServiceAccessor(Type serviceType)
   在 System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
   在 Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(Type serviceType, ServiceProviderEngineScope serviceProviderEngineScope)
   在 Microsoft.Extensions.DependencyInjection.ActivatorUtilities.ConstructorMatcher.CreateInstance(IServiceProvider provider)
   在 Microsoft.Extensions.DependencyInjection.ActivatorUtilities.CreateInstance(IServiceProvider provider, Type instanceType, Object[] parameters)
   在 Elsa.Mediator.Middleware.Notification.MiddlewareExtensions.<>c__DisplayClass0_0`1.<UseMiddleware>b__0(NotificationMiddlewareDelegate next) 在 D:\mrh\study\open\elsa-core\src\common\Elsa.Mediator\Middleware\Notification\MiddlewareExtensions.cs 中: 第 25 行
   在 Elsa.Mediator.Middleware.Notification.NotificationPipelineBuilder.Build() 在 D:\mrh\study\open\elsa-core\src\common\Elsa.Mediator\Middleware\Notification\NotificationPipelineBuilder.cs 中: 第 42 行
   在 Elsa.Mediator.Middleware.Notification.NotificationPipeline.Setup(Action`1 setup) 在 D:\mrh\study\open\elsa-core\src\common\Elsa.Mediator\Middleware\Notification\NotificationPipeline.cs 中: 第 24 行
   在 Elsa.Mediator.Middleware.Notification.NotificationPipeline.CreateDefaultPipeline() 在 D:\mrh\study\open\elsa-core\src\common\Elsa.Mediator\Middleware\Notification\NotificationPipeline.cs 中: 第 31 行
   在 Elsa.Mediator.Middleware.Notification.NotificationPipeline.get_Pipeline() 在 D:\mrh\study\open\elsa-core\src\common\Elsa.Mediator\Middleware\Notification\NotificationPipeline.cs 中: 第 17 行
   在 Elsa.Mediator.Middleware.Notification.NotificationPipeline.<ExecuteAsync>d__6.MoveNext() 在 D:\mrh\study\open\elsa-core\src\common\Elsa.Mediator\Middleware\Notification\NotificationPipeline.cs 中: 第 29 行
   在 Elsa.Mediator.Services.DefaultMediator.<SendAsync>d__9.MoveNext() 在 D:\mrh\study\open\elsa-core\src\common\Elsa.Mediator\Services\DefaultMediator.cs 中: 第 81 行
   在 Elsa.Extensions.MediatorExtensions.<SendAsync>d__1.MoveNext() 在 D:\mrh\study\open\elsa-core\src\common\Elsa.Mediator\Extensions\MediatorExtensions.cs 中: 第 31 行
   在 Elsa.Workflows.Core.Services.WorkflowRunner.<RunAsync>d__16.MoveNext() 在 D:\mrh\study\open\elsa-core\src\modules\Elsa.Workflows.Core\Services\WorkflowRunner.cs 中: 第 173 行
   在 Elsa.Workflows.Core.Services.WorkflowRunner.<RunAsync>d__14.MoveNext() 在 D:\mrh\study\open\elsa-core\src\modules\Elsa.Workflows.Core\Services\WorkflowRunner.cs 中: 第 104 行
   在 Elsa.Workflows.Core.Services.WorkflowRunner.<RunAsync>d__12`1.MoveNext() 在 D:\mrh\study\open\elsa-core\src\modules\Elsa.Workflows.Core\Services\WorkflowRunner.cs 中: 第 76 行
   在 Program.<<Main>$>d__0.MoveNext() 在 D:\mrh\study\open\elsa-core\src\samples\console\Elsa.Samples.ConsoleApp.OutboundHttpRequests\Program.cs 中: 第 19 行

**Comment by sfmskywalker** [comment]
Hi @mrh520 

Thanks for reporting this issue! 

I have pushed a fix via 73326bb22884004c0f1275ebec797c54d4af0da1
