### ISSUE TITLE
ActivityExecutionContext set output parameter outputName question

### ISSUE THREAD

**Issue by happtim** [elsa-workflows/elsa-core#4269]
I used the v3 branch and when practicing custom activity according to the example, I deleted the code that assigned the return value from the constructor and instead returned it from the function. As a result, the Result in the function is empty.

In the process of testing, the assignment methods are inconsistent with my expectations because the value of the outputName parameter in the sets function is obtained based on the parameter name, resulting in several possibilities: 
1. Result.
2. this.Result.
3. activity.Result.

Is there any method to make the result stable? 
For example, can we use the string after the last dot as the parameter name for the outputName parameter?

```
public class Sum : CodeActivity<int>
{
	public Sum(Variable<int> a, Variable<int> b)
	{
		A = new(a);
		B = new(b);
	}

	public Input<int> A { get; set; } = default!;
	public Input<int> B { get; set; } = default!;

	protected override void Execute(ActivityExecutionContext context)
	{
		var input1 = A.Get(context);
		var input2 = B.Get(context);
		var result = input1 + input2;
		context.SetResult(result); // incorrect
		context.Set(Result,result); // good
		context.Set(this.Result,result); //incorrect
	}
}
```

**Comment by sfmskywalker** [comment]
Hello,

Thank you for reporting this issue.

I've taken the time to investigate the problem you've described. In my tests, all three methods of setting the activity's output yielded the expected results. In other words, I was unable to reproduce the issue on my end.

It's possible that there might be specific conditions or configurations under which this issue manifests that I haven't encountered in my tests. To help us further diagnose the problem:

1. Could you provide more detailed steps or a specific workflow definition that reproduces the issue?

Your feedback is invaluable, and I appreciate your patience as we work together to resolve this. 

Thank you for your contribution to Elsa Workflows.

**Comment by happtim** [comment]
I can provide you with the test code here.
```
// Setup service container.
var services = new ServiceCollection();

// Add Elsa services.
services.AddElsa();

// Build service container.
var serviceProvider = services.BuildServiceProvider();

// Resolve a workflow runner to run the workflow.
var workflowRunner = serviceProvider.GetRequiredService<IWorkflowRunner>();
{
	// Create a workflow.
	var a = new Variable<int>();
	var b = new Variable<int>();

	var sumFunc = new Sum(a,b);

	var workflow = new Sequence
	{
		Variables = { a, b  },
		Activities =
		{
			new WriteLine("Enter first value"),
			new ReadLine(a),
			new WriteLine("Enter second value"),
			new ReadLine(b),
			sumFunc,
			new WriteLine(context => $"The sum1 get result from activity of {a.Get(context)} and {b.Get(context)} is {sumFunc.GetResult<int>(context)}"),
			new WriteLine(context => $"The sum1 get last result of {a.Get(context)} and {b.Get(context)} is {context.GetLastResult<int>()}"),

		}
	};
	
	workflowRunner.RunAsync(workflow);
}


public class Sum : CodeActivity<int>
{
	public Sum(Variable<int> a, Variable<int> b)
	{
		A = new(a);
		B = new(b);
	}

	public Input<int> A { get; set; } = default!;
	public Input<int> B { get; set; } = default!;

	protected override void Execute(ActivityExecutionContext context)
	{
		var input1 = A.Get(context);
		var input2 = B.Get(context);
		var result = input1 + input2;
		//context.Set(Result,result);
		context.SetResult(result); // incorrect
	}
}
```

The execution of the code 1+1 produces the following result:

```
Enter first value
Enter second value
The sum1 get result from activity of 1 and 1 is 0
The sum1 get last result of 1 and 1 is 1
```
