### ISSUE TITLE
ActivityExtensions GetResult method may be missing a generic method

### ISSUE THREAD

**Issue by happtim** [elsa-workflows/elsa-core#4270]
I'm using version 3 and found that the ActivityExtensions method may be missing a generic method. The other two methods for get the Result have both generic and non-generic versions.

```
    /// <summary>
    /// Gets the Result output of the specified activity.
    /// </summary>
    /// <param name="context">The context.</param>
    /// <param name="activity">The activity.</param>
    /// <returns>The output value.</returns>
    public static object? GetResult(this ExpressionExecutionContext context, IActivity activity)
    {
        return activity.GetOutput(context, ActivityOutputRegister.DefaultOutputName);
    }
```

**Comment by sfmskywalker** [comment]
Hi @happtim,

Thank you for bringing this to our attention. I've reviewed the file you mentioned, and it appears that the generic method you were looking for has been added to the `ActivityExtensions` in the meantime. You can find it [here](https://github.com/elsa-workflows/elsa-core/blob/v3/src/modules/Elsa.Workflows.Core/Extensions/ActivityExtensions.cs#L112).

Please let us know if you have any further questions or if there's anything else we can assist you with.
