### ISSUE TITLE
Resuming Suspended Workflow instances after server restart

### ISSUE THREAD

**Issue by ManjunathSaukar** [elsa-workflows/elsa-core#4271]
1. I have one workflow with two HTTP Endpoint activities.
2. I trigger the first HTTP Endpoint, which executes the response activity
3. Then the second HTTP Endpoint executes, which will create a bookmark and then suspend the workflow.
4. At this point, I stop the application, then start it again.
5. When I try to resume the workflow by triggering this second HTTP Endpoint, its not giving any response.
[sample-workflow.txt](https://github.com/elsa-workflows/elsa-core/files/12212034/sample-workflow.txt)
Request Curls : 
curl --location 'https://localhost:7202/Demo1?ID=3'

curl --location 'https://localhost:7202/Demo2?correlation=3'

Expecting a quick response

**Comment by sfmskywalker** [comment]
Hello @ManjunathSaukar,

Thank you for the detailed steps. I'm pleased to inform you that this bug has been addressed earlier today. You can find the fix in our latest preview packages.
