### ISSUE TITLE
Sequence activity uses HashSet<IActivity> as a list of activities

### ISSUE THREAD

**Issue by o2alexanderfedin** [elsa-workflows/elsa-core#4286]
That means that the order of execution is not guaranteed.
Had to create my own SequenceAct activity instead.
Mind fixing that? I don't wanna go through your HashSet-based sequence of reviews and approvals.

**Comment by sfmskywalker** [comment]
Thanks for pointing that out! I built the HashSet based Sequence hoping for a unique experience every time. 😉 I’ll look into this. Appreciate your feedback!

**Comment by sfmskywalker** [comment]
Fixed via 17a59eaa97257b044841c8fab71ace114a1df7dc
