### ISSUE TITLE
Constructors with [CallerFilePath] and [CallerLineNumber] shall never work as they are

### ISSUE THREAD

**Issue by o2alexanderfedin** [elsa-workflows/elsa-core#4287]
as the compiler will use a parameterless constructor instead.
Moreover, this.SetSource(source, line) extension method is also invalid, as it requires the lineNumber to be null to set the source:
```
   /// <summary>
   /// Sets the source file and line number where this activity was instantiated, if any.
   /// </summary>
   public static void SetSource(this IActivity activity, string? sourceFile, int? lineNumber)
   {
       if (sourceFile == null || lineNumber != null)
           return;

       var source = $"{Path.GetFileName(sourceFile)}:{lineNumber}";
       activity.SetSource(source);
   }
```

<img width="981" alt="Screenshot 2023-08-04 at 20 19 38" src="https://github.com/elsa-workflows/elsa-core/assets/77516945/b119891f-111c-4378-8e8b-76126d84c9f4">

**Comment by sfmskywalker** [comment]
Makes sense. The parameterless constructors are necessary for JSON deserialization, but now when constructing activities in code, those same constructors will be used instead of the ones taking line and source file. I’ll give it some thought.

**Comment by sfmskywalker** [comment]
I fixed it by using a custom `IJsonTypeInfoResolver` when deserializing activities from JSON, which allowed me to remove the default constructors so that the `[CallerFilePath]` and `[CallerLineNumber]` will take into effect when instantiated in workflow classes.

Thanks for having this pointed out!
