### ISSUE TITLE
When writing a httpResponse with status nocontent still has error in workflow instance about writing content.

### ISSUE THREAD

**Issue by herblinernexxbizz** [elsa-workflows/elsa-core#4296]
When writing a httpResponse with status nocontent still has error in workflow instance about writing content.

[no-content-204-running-state.txt](https://github.com/elsa-workflows/elsa-core/files/12279454/no-content-204-running-state.txt)

**Comment by sfmskywalker** [comment]
Fixed via 0b8d97c422d6c3c3a72e3267b1a6725df4e7cb5f
