### ISSUE TITLE
Integrate Swagger for API Documentation in Elsa 3

### ISSUE THREAD

**Issue by sfmskywalker** [elsa-workflows/elsa-core#4299]
**Description**:
With our ongoing development in Elsa 3, which utilizes FastEndpoints, it has become increasingly essential to provide clear and concise API documentation for our end-users and developers. To achieve this, we should integrate Swagger to automatically generate this documentation.

**Acceptance Criteria**:
1. Swagger is successfully integrated with Elsa 3.
2. All existing API endpoints in Elsa 3 are documented within Swagger.
4. A dedicated URL (e.g., `/open-api`) is available for users to view the API documentation.
5. Documentation is clear, with accurate endpoint descriptions, request/response schemas, and example values.

**Additional Notes**:
1. FastEndpoints might have specific integration details or best practices for Swagger, so it's essential to ensure compatibility.

**Comment by solutionmania** [comment]
I'm happy to have a go at this if you like?

**Comment by sfmskywalker** [comment]
That would be fantastic!
