### ISSUE TITLE
User Task Activity

### ISSUE THREAD

**Issue by sfmskywalker** [elsa-workflows/elsa-core#43]
**User Task** activity is a blocking activity (a trigger somewhere in your workflow). This means that in order for the workflow to continue, it needs to be resumed with a given action (one of the actions defined on the User Action itself). To resume such a workflow, your application will have to be able to query the workflow and the defined User Actions (associated with the User Action activity), so that your application can e.g. display these actions as buttons the user can click.

Here's a demonstration of how that works in Orchard: https://www.youtube.com/watch?v=iioKQkXUwXA

**Comment by sfmskywalker** [comment]
See [Sample12](https://github.com/elsa-workflows/elsa-core/tree/develop/samples/Sample12) for using this activity.

**Comment by denis-ivanov** [comment]
Sample12 doesn't demonstrate how to get user actions, it shows predefined list `Console.WriteLine("What action will you take? Choose one of: Accept, Reject, Needs Work");`. But in the video, I think, actions fetched from workflow dynamically.

**Comment by mzand111** [comment]
> Sample12 doesn't demonstrate how to get user actions, it shows predefined list `Console.WriteLine("What action will you take? Choose one of: Accept, Reject, Needs Work");`. But in the video, I think, actions fetched from workflow dynamically.

Take a look at "https://github.com/elsa-workflows/elsa-core/discussions/2661"
