### ISSUE TITLE
Can't access Javascript expandoObject in Javascript expression 

### ISSUE THREAD

**Issue by RingoKam** [elsa-workflows/elsa-core#430]
Hope all is well! I am having issue accessing my expandoObject in the javascript expression.

I have a custom Handler for Javascript expression below:
```C#
public async Task Handle(EvaluatingJavaScriptExpression notification, CancellationToken cancellationToken)
{
    ...get the values somehow
    var values = new Database().getValues();
    var obj = ToExpandoObject(values);
    var context = notification.Engine;
    context.SetValue("entity", obj);
    var text = context.GetValue("entity"); //debug show that the expando value is stored!
}


public ExpandoObject ToExpandoObject(IEnumerable<CnsFormOps.Requests.Model.TransformedFormValues> values)
{
    var eo = new ExpandoObject();
    var eoColl = (ICollection<KeyValuePair<string, object>>)eo;

    foreach (var kvp in values)
    {
        eoColl.Add(new KeyValuePair<string, dynamic>(kvp.FieldName, kvp.TransformedValue));
    }
    return eo;
}
```
In my javascript template expression, I have 
```javascript
JSON.stringify(Object.keys(entity).map(key => entity[key])) + " " + 
JSON.stringify(entity)
```
the result of the string is
```
[] {}
```
I used a similar method with liquid template and it worked fine and it return the expando object just fine. I am using Elsa 1.2.2.29

I am not sure why it's not working?? any pointers? as always really appreciate it!

**Comment by sfmskywalker** [comment]
I had a similar issue yesterday while troubleshooting why a given array wasn't stringified as I had expected. In my case, the issue was that the array was actually a `JArray`. So what I did was do something like 'JSON.parse(myJArr.ToString())'. 

Your situation is different, but perhaps you can try something similiar (using .NET methods to convert/serialize your ExpandoObject to JSON and then parse it using JSON.parse (and then stringify it if you need a JSON string).

**Comment by craigfowler** [comment]
Yeah.  I just ran into the exact same thing.  I also went with @sfmskywalker 's workaround.  I Newtonsoft'ed my object to a JSON string in C#-land and then stored that string in my variable.  As it happened, I actually wanted to output that JSON string anyway in a Write HTTP Response activity, but if I wanted bits of its object graph I could have `JSON.parse`'d that string in JS.

**Comment by RingoKam** [comment]
Thank you guys! I end up doing the same thing.

Is this an issue from Jint side? If so how come I can still get the object out on C# but not in the template eval?

```
public async Task Handle(EvaluatingJavaScriptExpression notification, CancellationToken cancellationToken)
{
    ...get the values somehow
    var values = new Database().getValues();
    var obj = ToExpandoObject(values);
    var context = notification.Engine;
    context.SetValue("entity", obj);
    var text = context.GetValue("entity"); //debug show that the expando value is stored!
}
```

**Comment by sfmskywalker** [comment]
Although I am not 100% sure, I do think it might be a limitation on Jint's side. To work around that, we might consider adding some helper functions to the script execution scope that help dealing with this sort of types.

**Comment by RingoKam** [comment]
Thank you closing the issue for now.
