### ISSUE TITLE
Elsa 3 DI not working for custom activities 

### ISSUE THREAD

**Issue by ricksearcy** [elsa-workflows/elsa-core#4305]
We have numerous Activities that rely on services to be injected. In Elsa 2 this worked fine, but not in Elsa 3. Consider the follwing.

public class MyActivity : CodeActivity
{
    public MyActivity(IMyService myService) 
    { 
    }
    protected override void Execute(ActivityExecutionContext context)
    {       
    }
}

Throws this error:
Each parameter in the deserialization constructor on type '......' must bind to an object property or field on deserialization. Each parameter name must match with a property or field on the object. Fields are only considered when 'JsonSerializerOptions.IncludeFields' is enabled. The match can be case-insensitive

If we add an empty constructor to get past the deserialization issues, the empty constructor always gets called on Activity execution even tho that is contrary to the .net DI discovery rules. 

Could you please provide a sample custom Activity that uses and relys on a custom service?

**Comment by MikeDLi** [comment]
Hi-

This discussion might be related to your question. 

https://github.com/elsa-workflows/elsa-core/discussions/4128#discussioncomment-6152153

Thanks

**Comment by ricksearcy** [comment]
@MikeDLi yes that looks to be the same issue. I will close.
