### ISSUE TITLE
Workflow not found after publishing via designer

### ISSUE THREAD

**Issue by alessandro-chiavegato** [elsa-workflows/elsa-core#4308]
- Elsa version 2.12
- Elsa server and dashbord hosted into .NET 7 asp.net core application.
- Application running in kubernetes pod with linux alpine OS.

Hi,
i use elsa as workflow engine in the production environment of my application. All workflows are generated via designer and their definitions persisted in SQL Server. Most workflows have an HTTPEndpoint activity as a trigger for the workflow. Sometimes, when I make an HTTP request to start these workflows, I get a 404 not found. This happens when publishing a workflow via designer (any workflow) or restarting the kubernetes pod. Republishing the workflow or restarting the kubernetes pod resolves the issue. At your disposal for further details.

**Comment by alessandro-chiavegato** [comment]
Hi,
I verified that the problem occurs in the order of receiving the events TriggersDeleted and TriggerIndexingFinished in the UpdateRouteTable class using Rebus as a message broker. 
In some situations the TriggersDeleted event arrives after the TriggerIndexingFinished event and the Http trigger informations of the workflow definition published are deleted from the RouteTable.

![image](https://github.com/elsa-workflows/elsa-core/assets/22524691/a3cf8162-5fcf-422c-8678-5754022d5439)

![image](https://github.com/elsa-workflows/elsa-core/assets/22524691/46c0e645-4119-4fc2-b78c-78d5c6fcf982)

A solution could be to add a validation in the UpdateRouteTable class, for the Handle(TriggersDeleted message) and Handle(BookmarksDeleted message) methods, such as

![image](https://github.com/elsa-workflows/elsa-core/assets/22524691/e4c32952-1caf-4559-b43d-42f462832c00)

what do you think?

**Comment by sfmskywalker** [comment]
Hi @alessandro-chiavegato , thank you for reporting this issue and proposing a solution! If the order of events is indeed not predictable, then I agree with your solution to get the actual triggers from storage to ensure the route table becomes up to date 👍🏻
