### ISSUE TITLE
How to run the sample "ElsaDashboard.Samples.BlazorServer"?

### ISSUE THREAD

**Issue by SeptSkyTime** [elsa-workflows/elsa-core#4310]
I downloaded the elsa-core sources, and try to run the sample "ElsaDashboard.Samples.BlazorServer" project, the page is blank with the url "https://localhost:6001/". I opened the page file Index.razor, there's a line "<WorkflowStudio ServerUrl="https://localhost:11000"/>". So I ran the "Elsa.Samples.Server.Host" project first, and listened on: https://localhost:11000, then ran the sample "ElsaDashboard.Samples.BlazorServer" project again, the page was still blank. Why?
I'm a newbie to elsa workflow, and very like it by its idea.
My OS is Win 10, IDE is VS2022.

**Comment by sfmskywalker** [comment]
I think that project got broken at some point. These days I’m mostly working on Elsa 3 in the v3 branch. If you’re interested in the Blazor implementation of the designer, I recommend checking out the elsa-studio repo.

**Comment by SeptSkyTime** [comment]
> I think that project got broken at some point. These days I’m mostly working on Elsa 3 in the v3 branch. If you’re interested in the Blazor implementation of the designer, I recommend checking out the elsa-studio repo.

I have run the "Elsa.Studio.Host.Server" project, but it need username and password. What's the default username and password? I found the login api url is "https://localhost:5001/elsa/api", but I didn't find the project for that api, and didn't find the ILoginApi implement source file.

**Comment by SeptSkyTime** [comment]
I commented this line "NavigationManager.NavigateTo("login", true);",  and saw the main page. Thanks a lot, very nice work!
