### ISSUE TITLE
Using AddElsaApiEndpoints() is incompatible with AddJsonOptions()

### ISSUE THREAD

**Issue by pellea** [elsa-workflows/elsa-core#4311]
Using `AddElsaApiEndpoints` breaks

```
.AddJsonOptions(options =>
    {
        options.JsonSerializerOptions.Converters.Add(new UtcDateTimeConverter());
    }
```

When `AddElsaApiEndpoints` is added, the converters are never called.

Elsa version: 2.11 in .NET6 or .NET7

**Comment by sfmskywalker** [comment]
Hello @pellea,

Elsa 2 utilizes API controllers and is dependent on Newtonsoft's serializer, so it's not compatible with System.Text.Json.

If you're deep into your Elsa implementation, you might think about transitioning to Elsa 3. This version offers more flexibility, especially regarding API endpoints and serialization settings.

If Elsa 3 isn't feasible, another approach is refactoring Elsa.Server.Api. This would involve it managing its own serialization and directly sending responses, bypassing ASP.NET's serialization. While this could be a substantial task, I'm open to reviewing such a PR if it's vital for your project.

**Comment by pellea** [comment]
Unfortunately Elsa3 was not production-ready when we started our project. So I choose to stay with Elsa 2. 
Whether we use Newtonsoft or Text.Json is not important. I switched back to Newtonsoft. 

I hope thath Elsa3 will not force application to use a specific serializer settings (or silently override user defined settings).

**Comment by sfmskywalker** [comment]
Hi @pellea,

Thank you for bringing this to our attention. In Elsa 3, we've integrated FastEndpoints to manage the exposure of API endpoints. This ensures that there won't be any conflicts with API controllers or minimal APIs. Your feedback is invaluable, and it plays a crucial role in enhancing the project. We appreciate your contribution.
