### ISSUE TITLE
Bug: Delete WorkflowInstance leaves orphaned objects

### ISSUE THREAD

**Issue by yutao815** [elsa-workflows/elsa-core#4313]
While Delete WorkflowInstance，I found two bugs:
1、ActivityExecutionRecordLog doesn't delete.
2、I use hangfire，the job doesn't remove.

**Comment by sfmskywalker** [comment]
Hi @yutao815 , thanks for reporting this issue! What version of Elsa are you using?

**Comment by yutao815** [comment]
I use the V3 version.thanks.

**Comment by sfmskywalker** [comment]
Hi @yutao815,

Thanks again for bringing this to our attention.

Regarding the first issue you mentioned about the `ActivityExecutionRecordLog` not being deleted: this has been addressed and fixed via [this pull request](https://github.com/elsa-workflows/elsa-core/pull/4324).

As for the second issue related to Hangfire jobs not being removed: I've tried to reproduce this on my end, but when I schedule a job using the Delay activity and then delete the workflow instance, the Hangfire job is also deleted as expected. If you could provide a detailed step-by-step process to reproduce this issue, it would be very helpful. If the issue persists on your end with those steps, please feel free to reopen this issue.

Thank you for your contribution to Elsa Workflows!
