### ISSUE TITLE
Workflow not changes status from 'Running' to 'Finished'

### ISSUE THREAD

**Issue by arkhokhar** [elsa-workflows/elsa-core#4319]
Hi, 
After update nuget packages to 3.0.0-preview.604, I am facing two problem, 

1. I am facing this error with database.

```
SQLite Error 1: 'table "WorkflowDefinitions" already exists'.'

``` 

![elsa_p_2](https://github.com/elsa-workflows/elsa-core/assets/114415858/70bb3dfb-f5f0-4166-8413-b28a78031c73)

2.  when i try to resume my workflow using following API

"https://localhost:7197/elsa/api/events/order/trigger"

my workflow resume, but workflow does not changes its status and also I am not getting HTTP Response.

![elsa_p_1](https://github.com/elsa-workflows/elsa-core/assets/114415858/5e8860c1-8465-4bba-bf17-0752869ac3c2)

**Comment by sfmskywalker** [comment]
For the first issue, you’ll have to delete your database (make sure to create a backup first if you don’t want to lose data, or export your workflows from the designer so you can import them later).

For the second issue, I’ll take a look soon.

**Comment by sfmskywalker** [comment]
Hi there,

Thank you for raising this issue. I've looked into the second part of the issue you mentioned.

Here are a couple of things to note:

1. When triggering the event via the REST API, it's crucial to use the "Synchronous" mode. This ensures that the `WriteHttpResponse` activity has an HTTP Context to write to.
2. I've made a small change to ensure that the Trigger Event endpoint resumes HTTP bookmarks when using the Proto.Actor runtime.

I recommend pulling the latest packages and giving it another try. If the issue persists, please provide detailed steps to reproduce. Additionally, if you could share a workflow JSON file, it would be immensely helpful for further investigation.

Thanks for your patience and collaboration!
