### ISSUE TITLE
Setup HTTP Activities under a specific URL

### ISSUE THREAD

**Issue by jkatsiotis** [elsa-workflows/elsa-core#4340]
Hi everyone,

This is something between a suggestion and a question. I am looking to add Elsa to an existing ASP.NET 7 project (which is quite large - has many areas etc). Workflows will only cover a specific section of the app and I am looking to add as little overhead as possible.

Using HTTP Activities is a great feature I want to utilize but only under a specific URL i.e. /workflows/.....

So, the way I found to skip calling the HttpEndpointMiddleware in all requests is to do the following in my Startup code.

Instead of :

`app.UseHttpActivities();`

I do:

`app.UseWhen(context => context.Request.Path.StartsWithSegments("/workflows"), appBuilder =>
{
    appBuilder.UseHttpActivities();
});`

If anyone has a cleaner approach let me know.

**Comment by sfmskywalker** [comment]
Hello @jkatsiotis,

Thank you for bringing this up! You're spot on, and I'm glad to inform you that we've already incorporated this functionality as a built-in feature. It's implemented by the HTTP Endpoint activity middleware component.

To utilize it, simply follow these steps:

In `Programs.cs`:

```csharp
services.AddElsa(elsa => elsa.AddHttpActivities(options => options.BasePath = "/workflows"));
```

Hope this helps! Let us know if you have any other questions or need further clarification.
