### ISSUE TITLE
Any plan to upgrade AutoMapper from version 9.00 to  version 10.00?

### ISSUE THREAD

**Issue by buzzlu** [elsa-workflows/elsa-core#435]
Abp. VNext had upgrade automapper from ver. 9 to ver. 10 since Abp VNext 3.1.0.

We faced a IMapper conflict error if we use Abp which version is great than 3.1.0.

Is possible to upgrade AutoMapper from 9 to 10? 

Thanks very much.

**Comment by sfmskywalker** [comment]
Done

**Comment by hyzx86** [comment]
@buzzlu 但是旧版的abp 不能用了。。😕

**Comment by buzzlu** [comment]
> @buzzlu 但是旧版的abp 不能用了。。😕
> But the old version of ABP doesn't work

You can embed an older Elsa-Core with the older Abp.

We have managed to get Abp & Elsa core be upgraded simultaneously.  It doesn't cost lot of workload.
