### ISSUE TITLE
Elsa 3 - Journal not working with Postgres

### ISSUE THREAD

**Issue by schneidersympatient** [elsa-workflows/elsa-core#4384]
Hey again,
right now I'm trying to use the Journal functionality of the Elsa 3 Dashboard (so no Studio this time).

I've created some small workflow to test, which just simply listens to an HTTP endpoint and writes to the console. The workflow executes, but no information is display in the journal, alongside with errors in the console when clicking on an activity:

![Screenshot 2023-09-01 105233](https://github.com/elsa-workflows/elsa-core/assets/140689609/cd58d03b-8cce-46ce-a0b4-1e20375b12f3)
![Screenshot 2023-09-01 105254](https://github.com/elsa-workflows/elsa-core/assets/140689609/b338f1e8-d554-4819-b3b1-431a46609326)

I've noticed that you explained in an [discussion ](https://github.com/elsa-workflows/elsa-core/discussions/3730)that `UseWorkflowRuntime` needs to be used. But it seems as the code in this discussion is outdated, or not usable with EF Core and Postgres. I.e. `UseAsyncWorkflowStateExporter` seems to not exist anymore.

I could not test it with SQLite, as the NuGet Package `Elsa.EntityFrameworkCore.Sqlite` is still stuck on RC1, and all my other packages are already using preview 682.

**Comment by schneidersympatient** [comment]
Ok, so I actually managed to make this work with Postgres, by downgrading my server dependencies to Preview 604. There all three methods you mentioned in the discussion (`UseDefaultRuntime` `UseExecutionLogRecords` and `UseAsyncWorkflowStateExplorer`) are available for Postgres.

It seems as the newest preview is either buggy for Postgres or changed the needed steps on how to activate the journal.

Nevertheless, some documentation on how to activate this feature would be great!

**Comment by sfmskywalker** [comment]
Hey @schneidersympatient 

Thank you for reporting this! We’ll look into it before the next preview release later this month.

**Comment by PKEnergy** [comment]
Hi, I have a similar problem with SqlServer. There is no WorkflowExecutionLogRecords table in the database at all (3.0.0.-preview.712). After downgrading to the version 604 + adding UseDefaultRuntime, UseExecutionLogRecords and UseAsyncWorkflowStateExplorer, the table appeared in the database and the journal works.

**Comment by PKEnergy** [comment]
Sqlite also has no journal detail.

**Comment by sfmskywalker** [comment]
Can someone share with me a repro? When I run the application I see the journal just fine.

**Comment by PKEnergy** [comment]
I would like to clarify: the log button works, but it does not show the workflow execution detail, because UseExecutionLogRecords is no longer available. UseExecutionLogRecords was removed on 2023-08-30 in commit 45d19412 (Remove WorkflowStateStore (#4374)).
With UseExecutionLogRecords:
![image](https://github.com/elsa-workflows/elsa-core/assets/59336079/c26a2e68-b7b6-4ca9-8f3e-b79b4606b14c)
Without:
![image](https://github.com/elsa-workflows/elsa-core/assets/59336079/410a930f-327a-4639-9f5c-a923c3eaf3e7)
Or how to display workflow execution details with WorkflowInstanceStore?

**Comment by PKEnergy** [comment]
Detail of the journal in ELSA 2:
![image](https://github.com/elsa-workflows/elsa-core/assets/59336079/873ce08d-a592-4bf9-b9b4-1ca55774ed09)
![image](https://github.com/elsa-workflows/elsa-core/assets/59336079/db2e8849-34c2-4889-b357-7a726c33dd5c)

**Comment by sfmskywalker** [comment]
@PKEnergy Thank you for providing those details.

> UseExecutionLogRecords is no longer available. UseExecutionLogRecords was removed on 2023-08-30 in commit https://github.com/elsa-workflows/elsa-core/commit/45d194125d46a29b114b5015f46accf4bf9dc20a (Remove WorkflowStateStore (https://github.com/elsa-workflows/elsa-core/pull/4374)).

Indeed, this has been refactored. Please make sure that Program.cs adds the Runtime feature and that it uses a persistence provider such as EF Core. For an example, please take a look at the [Elsa.WorkflowServer.Web](https://github.com/elsa-workflows/elsa-core/blob/v3/src/bundles/Elsa.WorkflowServer.Web/Program.cs#L93) bundle project.

As the Stencil implementation of the designer is being sunset, I would encourage you to start using the Blazor implementation instead:

<img width="2560" alt="image" src="https://github.com/elsa-workflows/elsa-core/assets/938393/b43ecd37-4f47-4175-aeda-d5b92b232469">

If this is not an option for you at this time, then I of course welcome a PR that updates the Stencil implementation with support for the new ActivityExecutionRecord model.

**Comment by PKEnergy** [comment]
Thank you for the informations. I switched to Blazor studio and used UseWorkflowManagement and UseWorkflowRuntime. I tried Sqlite and SqlServer and the journal works perfectly (version 3.0.0-preview.753).

**Comment by schneidersympatient** [comment]
Any update on the situation with Postgres?

**Comment by sfmskywalker** [comment]
@schneidersympatient I haven’t seen this issue with Postgres, but given your inquiry I take it you still are seeing this issue with the latest preview versions of Elsa and Elsa Studio (Blazor)?

**Comment by schneidersympatient** [comment]
@sfmskywalker  Well, either it's currently still broken, or my setup is wrong, which is also very possible.

As far as I know, we need to use `UseWorkflowRuntime` to activate the Journal, right?

For SQLite the following seems to work:
```csharp
    elsa.UseWorkflowManagement(management => management.UseEntityFrameworkCore(m => m.UseSqlite()));
    elsa.UseWorkflowRuntime(runtime =>
    {
        runtime.UseEntityFrameworkCore(ef => ef.UseSqlite());
    });
```

So for Postgres I would expect something like this:

```csharp
    elsa.UseWorkflowManagement(management => management.UseEntityFrameworkCore(m => m.UsePostgreSql("...")));
    elsa.UseWorkflowRuntime(runtime =>
    {
        runtime.UseEntityFrameworkCore(ef => **ef.UsePostgresSql("...)**); // UsePostgresSql does not exist here!
    });
```

While `UseSqlite` for WorkflowRuntime exists, `UsePostgresSql` does not. Is a different setup needed?

I've installed packages for EFCore, Postgres as well as Sqlite
```csharp
    <PackageReference Include="Elsa.EntityFrameworkCore" Version="3.0.0-preview-preview-3.0.0-740-hotfix-1.771" />
    <PackageReference Include="Elsa.EntityFrameworkCore.PostgreSql" Version="3.0.0-preview-preview-3.0.0-740-hotfix-1.771" />
    <PackageReference Include="Elsa.EntityFrameworkCore.Sqlite" Version="3.0.0-preview-preview-3.0.0-740-hotfix-1.771" />
```

**Comment by sfmskywalker** [comment]
Then I think I know. The extensions for PostgreSQL weren added later, and given that you’re using the preview hot fix package, I think it may have been added after that version. The latest version(808) should have the extension method. Let me know if you can’t find it.

**Comment by schneidersympatient** [comment]
@sfmskywalker Thanks, that did the trick!
