### ISSUE TITLE
in elsa v3 BookmarksDeleted event never not trigger

### ISSUE THREAD

**Issue by Nokecy** [elsa-workflows/elsa-core#4389]
https://github.com/elsa-workflows/elsa-core/blob/4fe7518976de313f9225eaf9b4a5cb0a66b4c36d/src/modules/Elsa.Workflows.Runtime/Services/DefaultWorkflowRuntime.cs#L350

**Comment by sfmskywalker** [comment]
Hi @Nokecy , thanks for the great catch! I pushed a fix via cbf609760ee05b771527f4e3030fa07192e21a63 👍🏻
