### ISSUE TITLE
can not set TenantId in elsa-studio-dashboard

### ISSUE THREAD

**Issue by liuliang-wt** [elsa-workflows/elsa-core#4390]
I tried this: 
<elsa-studio-dashboard culture="@requestCulture.RequestCulture.UICulture.Name" tenant="xxx"></elsa-studio-dashboard>
but it doesn't work. how do I set the tenantid?

**Comment by jumpinjackie** [comment]
On elsa 2.12:

We use a custom `ITenantAccessor` implementation that checks the tenant from request cookies.

Then we can easily "set the active tenant" on the elsa dashboard by just editing the expected cookie value to the tenant id we care about and doing a browser refresh afterwards. We get tenant-scoped listings of workflow defns because of the cookie value we set.

**Comment by liuliang-wt** [comment]
thanks alot for answering my question, can you explain abit more. In my razor page which contains ElsaDashboard, I already know the tenant, which cookie should I set to let elsa dashboard use it.

**Comment by jumpinjackie** [comment]
Our custom impl of `ITenantAccessor` looks something like this:

```
public class CustomTenantAccessor : ITenantAccessor
{
    readonly IHttpContextAccessor _hca;

    public SwiftFoxTenantAccessor(IHttpContextAccessor hca)
    {
        _hca = hca;
    }

    public Task<string?> GetTenantIdAsync(CancellationToken cancellationToken = default)
    {
        var t = _hca.HttpContext?.Request?.Cookies?["tenant_id"];
        return Task.FromResult(t);
    }
}
```

That's registered with elsa like so

```
builder.Services.AddElsa(elsa => {
   ...
   elsa.AddCustomTenantAccessor<CustomTenantAccessor>();
});
```

With this in place, requests made from the elsa dashboard will be tenanted if we have `tenant_id` set in our cookies.

You don't have to use cookies, it could be request headers or something else as long as your `ITenantAccessor` implementation knows where to read this tenant id from.

**Comment by liuliang-wt** [comment]
thank you , I tried your code and it works  :)
