### ISSUE TITLE
in elsa v3 workflowRunner.RunAsync workflowState.Input overwrite input parameter

### ISSUE THREAD

**Issue by Nokecy** [elsa-workflows/elsa-core#4391]
https://github.com/elsa-workflows/elsa-core/blob/4fe7518976de313f9225eaf9b4a5cb0a66b4c36d/src/modules/Elsa.Workflows.Core/Services/WorkflowRunner.cs#L116

**Comment by sfmskywalker** [comment]
Thanks for pointing that out! I happened to run into this issue as well a short while ago, and have pushed a fix. Please pull the latest changes and let me know if you encounter any further issues.
