### ISSUE TITLE
DistributedLock can replace DistributedLock.FileSystem？

### ISSUE THREAD

**Issue by happtim** [elsa-workflows/elsa-core#4392]
In the v3 branch, Elsa.Workflows.Runtime references DistributedLock, which depends on many other implementations such as Redis, SqlServer, FileSystem, etc. This results in a large number of compiled files. Upon reviewing the code, I discovered that currently only DistributedLock.FileSystem is being used. I replaced the package and successfully compiled. Can we consider replacing DistributedLock with DistributedLock.FileSystem?

**Comment by sfmskywalker** [comment]
Hi @happtim , yes that’s a great idea! Do you want to do a PR?

**Comment by happtim** [comment]
I'll give it a try.

**Comment by sfmskywalker** [comment]
Done via @happtim 's PR. Thanks again @happtim !
