### ISSUE TITLE
Elsa v3: Improve SendEmail error handling

### ISSUE THREAD

**Issue by rose-a** [elsa-workflows/elsa-core#4394]
Hi,

I'm trying out the Elsa v3 prerelease and I'm trying to send an E-Mail using the *SendEmail* activity, which fails on [smtpService.SendAsync](https://github.com/elsa-workflows/elsa-core/blob/7de42362621c544b8602fd1826aac652d04bb7ac/src/modules/Elsa.Email/Activities/SendEmail.cs#L121).

Since the resulting exception is just swallowed in the catch block (not logged or forwarded to the `Error` activity as an input or something) I have no indication why it fails!

Please provide a way to get hold of this exception.

**Comment by sfmskywalker** [comment]
Will do!

**Comment by sfmskywalker** [comment]
Done via 4f7341957364cb487411e82af4714963e570bc98

Thanks for the suggestion!
