### ISSUE TITLE
Not find taiwind.css 

### ISSUE THREAD

**Issue by ClementeGao** [elsa-workflows/elsa-core#4404]
Elsa version:2.9.3
when setup dashboard, the page style is error 
 when l open dev tool.it has a error: the tailwind.css not found
![image](https://github.com/elsa-workflows/elsa-core/assets/16145998/73c856c5-37ce-4285-abd6-89bbbb51e99d)

**Comment by sfmskywalker** [comment]
Do you have steps to reproduce this issue with the latest version of Elsa? Perhaps in the form of a project that you can share?

**Comment by rrustemh** [comment]
Hi @sfmskywalker ,

I'm having the same issue in with latest version of version 2. I'm following the same instructions as per the documentation to setup a server and a dashboard. The other content of the dashboard module all are being loaded correctly, tailwind.css is the only module which is not being loaded.

**Comment by ClementeGao** [comment]
<img width="955" alt="image" src="https://github.com/elsa-workflows/elsa-core/assets/16145998/31ab7402-9019-4353-ab26-d37d335b3152">
@sfmskywalker hi, 
i have problem. Why serialize the stream, 
i need download file by endpoint, but it alaway return json 
![image](https://github.com/elsa-workflows/elsa-core/assets/16145998/9404fc37-3898-4112-914b-68c929e9c459)

**Comment by sfmskywalker** [comment]
> Now it's work well , thank you

Great! Did it get fixed automatically, or did you need to do something specific?

> hi, i have problem. Why serialize the stream, i need download file by endpoint, but it alaway return json ![image](https://github.com/elsa-workflows/elsa-core/assets/16145998/9404fc37-3898-4112-914b-68c929e9c459)

It's better to create separate issues for separate topics. See you there! 😄

**Comment by ClementeGao** [comment]
@sfmskywalker    try clean solution and cache and cookie

**Comment by sfmskywalker** [comment]
Excellent, thank you.
