### ISSUE TITLE
[Question/Feature Request] Reference type variables to store large files 

### ISSUE THREAD

**Issue by regan32** [elsa-workflows/elsa-core#4408]
Hello, I have wrote activity to download/upload files and store then in variables, but the problem is very low performance. Blob has written to workflowInstance table so it serialize\deserialize 100+MB hex string at each burst and save.

I'm looking for some sort of reference/blob variable, which will store reference in workflowInstance data and allow to access blob by some sort of Custom IBlobVariableStorage realization.

**Comment by sfmskywalker** [comment]
If you're on Elsa 2, the best thing you might do is to update your activity to directly write them to some shared storage and store the URL / path / identifier in a variable, which you can then use in subsequent activities to download the stored file when you need it.

In Elsa 3, workflow variables can be configured with a **storage driver**, which controls where the value is persisted. Out of the box, there is currently only the **Workflow** and the **Memory** driver, but this system is designed to be extensible and will soon also offer a **Blob** driver that will store the contents in a configurable blob storage provider (which could be anything from local disk to cloud storage to FTP).

**Comment by regan32** [comment]
Glad to hear that, thanks!
