### ISSUE TITLE
Fix InstantEvent Activity

### ISSUE THREAD

**Issue by sfmskywalker** [elsa-workflows/elsa-core#441]
Currently, `InstantActivity` keeps on triggering the workflow, while it should only ever run the workflow once at the specified instant.

### Requirements

* `InstantActivity` triggers workflow only once.

**Comment by sfmskywalker** [comment]
Fixed in ae40d36c7279179fc83629324fb4d15c2ef52f76

**Comment by Alexplose** [comment]
Can you please fix this also in the current elsa version ?
