### ISSUE TITLE
Bug: Exceptions from WorkflowContextProviders do not result in a faulted workflow 

### ISSUE THREAD

**Issue by Nokecy** [elsa-workflows/elsa-core#4451]
when workflow context exeception ,workflow instance not Transfer to Fault state

**Comment by sfmskywalker** [comment]
Hi @Nokecy , what do you mean specifically with "workflow context exception"?

**Comment by Nokecy** [comment]
when WorkflowContextProvider   LoadAsync or  SaveAsync method exception occurred

**Comment by sfmskywalker** [comment]
Gotcha. Thanks for clarifying!

**Comment by sfmskywalker** [comment]
There was a potential for not just the workflow context provider middleware, but *any* workflow execution middleware component to throw an exception.

To fix this, I introduced a new middleware component called `ExceptionHandlingMiddleware` component that has essentially the same responsibility as the version for the activity execution pipeline, except at a higher layer.

With this middleware, if a workflow context provider throws an unhandled exception, it will be caught by this middleware component and logged as an incident and transitions the workflow into the Faulted state.

We may yet enhance this behavior by making it customizable like what was done with the incident strategy approach for activity-level exceptions, but I need to think a little bit more about that to see if it makes sense.

**Comment by sfmskywalker** [comment]
Fixed via fbdd555dd9540a3a21f7c57d23273ed989af9bea
