### ISSUE TITLE
V3:HttpEndpoint rquest error

### ISSUE THREAD

**Issue by mrh520** [elsa-workflows/elsa-core#4458]
Incorrect Content-Type: application/json

    private IFormFileCollection ReadFilesAsync(ActivityExecutionContext context, HttpRequest request)
    {
        return request.Form.Files;
    }

**Comment by sfmskywalker** [comment]
Hi @mrh520 

Thank you for reporting this issue. This should be fixed with the latest preview release, as of [build 736](https://github.com/elsa-workflows/elsa-core/actions/runs/6253506621).

If not, please feel free to reopen this issue.
