### ISSUE TITLE
Helper Method for Using Memory Store

### ISSUE THREAD

**Issue by xfoxfu** [elsa-workflows/elsa-core#4467]
I have found despite memory-based stores are injected into the DI, they are not used by default, and there seems not to be a configuration method to use the memory stores. In order to use the memory stores, I have to write

```cs
builder.Services.AddElsa(opts =>
{
    opts.UseWorkflowRuntime(x =>
    {
        x.TriggerStore = sp => sp.GetRequiredService<MemoryTriggerStore>();
        x.BookmarkStore = sp => sp.GetRequiredService<MemoryBookmarkStore>();
        x.WorkflowInboxStore = sp => sp.GetRequiredService<MemoryWorkflowInboxMessageStore>();
        x.WorkflowExecutionLogStore = sp => sp.GetRequiredService<MemoryWorkflowExecutionLogStore>();
        x.ActivityExecutionLogStore = sp => sp.GetRequiredService<MemoryActivityExecutionStore>();
    });
});
```

I wonder if a convenient method could be provided just like `UseEntityFramework`, instead of assigning these manually.

Also, defaulting to `NoopXXXStore` is quite confusing for users as me. I spent several hours to figure out why `IActivityExecutionStore` does not return any results.

**Comment by sfmskywalker** [comment]
Hi @xfoxfu ,

Thank you for your feedback! I can see your point and I agree with you- the default should be all memory stores, otherwise it's going to be confusing.

**Comment by sfmskywalker** [comment]
Done via 939c4033816758414d3d0f6057f265a9706fe3d3
