### ISSUE TITLE
Feature: Generate Event URL

### ISSUE THREAD

**Issue by sfmskywalker** [elsa-workflows/elsa-core#4475]
Like in Elsa 2, we need a way in Elsa 3 to generate a URL that triggers an event (called "signal" in V2).
Key requirements:

- Ability to generate a URL that triggers a given event name scoped to the current workflow instance.
- Ability to attach a SAS token with (configurable) expiration support to prevent external actors from invoking known public URLs.

For additional context, see #4462

**Comment by sfmskywalker** [comment]
Done via #4476

**Comment by schneidersympatient** [comment]
@sfmskywalker Quick question about this: is it (already) possible to generate URLs when using Elsa Studio?

**Comment by sfmskywalker** [comment]
It certainly is, there's a new JS function called `generateEventTriggerUrl` that accepts the name of the event.

**Comment by 7studios** [comment]
${generateEventTriggerUrl('Approve')} throws the following error - Jint.Runtime.JavaScriptException+JavaScriptErrorWrapperException, Jint: generateEventTriggerUrl is not defined
