### ISSUE TITLE
V3: add the method  or property  OnCanExecute

### ISSUE THREAD

**Issue by MartinLiL** [elsa-workflows/elsa-core#4477]
in the interface IActivity or base class Activity, the method or property  OnCanExecute is valuable (just like in the V2 version).   For example, when we create a  customized Activity ( User Task， or UI Usertask ……）
This kind of activity may be triggered many times, it will really be executed until its pre-conditions (activity's properties or workflow variables ) are right, so the OnCanExecute will be checked before the method ExecuteAsync.

**Comment by MartinLiL** [comment]
For non -trigger activities, such as an activity with a timer(loop to check the activity's properties or workflow variables ) could be a case, or other customized activities would check the pre-conditions. of course, trigger's activities are typical.

**Comment by sfmskywalker** [comment]
Done via https://github.com/elsa-workflows/elsa-core/pull/4507
