### ISSUE TITLE
Workflow Designer don't show connection/outcomes issue in modal page

### ISSUE THREAD

**Issue by jortygu** [elsa-workflows/elsa-core#448]
Hi,
  
   i have an workflow definition as below, and custom an ViewComponent that associated ```wf-designer-host```.
   when i put this ViewComponent to Modal Page,i can't see connection/outcomes as definition.
   when i put this ViewComponent to Normal Page,i can see connection/outcomes as definition.
   i find it may be related to modal  page style ```position:relative```. how i can see connection/outcomes in modal page?
+ Workflow Definition
![image](https://user-images.githubusercontent.com/43945927/97877389-11545880-1d58-11eb-92b3-d8975cf7b54b.png)
+ Modal Page
![image](https://user-images.githubusercontent.com/43945927/97876679-254b8a80-1d57-11eb-9ca9-33639da77011.png)
+ Normal Page
![image](https://user-images.githubusercontent.com/43945927/97877639-6e500e80-1d58-11eb-9541-4c85f0f8e617.png)

**Comment by sfmskywalker** [comment]
Let's see if this issue persists with the V2 designer once it's available. If you do, then please provide a repro. Closing this issue for now, but please feel free to reopen once you have said repo.
