### ISSUE TITLE
Elsa3: Switch activities cannot be persisted within MongoDB execution log

### ISSUE THREAD

**Issue by JochenSteinbrenner** [elsa-workflows/elsa-core#4482]
Good morning,
there is an issue with the "Switch" or the "Flow Switch" activity when using MongoDb persistation.
It is not possible to show the Execution log of the workflow instances (the workflow instance view shows no data).

Repro steps:
Create a workflow with a (Flow) Switch activity and run it using WorkflowRuntime with MongoDB.
(Refer to attached Workflow-Export...). Try to open workflow instance view. Ends up in exception:

```
fail: Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware[1]
      An unhandled exception has occurred while executing the request.
      System.FormatException: An error occurred while deserializing the ActivityState property of class Elsa.Workflows.Runtime.Entities.WorkflowExecutionLogRecord: An error occurred while deserializing the Condition property of class Elsa.Workflows.Core.Activities.SwitchCase: Unable to determine actual type of object to deserialize for interface type Elsa.Expressions.Contracts.IExpression.
```

Application configuration:

```
services.AddElsa(elsa =>
{
    elsa.UseMongoDb(entitySystemConfig.ConnectionString);
    elsa.UseWorkflowManagement(management =>
    {
        management.UseMongoDb();
    });
    elsa.UseWorkflowRuntime(runtime =>
    {
        runtime.UseMongoDb();
    });
..
```

[test-switch.zip](https://github.com/elsa-workflows/elsa-core/files/12723294/test-switch.zip)

Maybe other activities have the same problems when using MongoDb...
Thank you for your help!

Regards
Jochen Steinbrenner

**Comment by sfmskywalker** [comment]
Thanks @JochenSteinbrenner for the report + repro steps 👍🏻 

I was able to see the issue for myself and pushed an additional serializer to fix the error via 92dcd9991cbb51b61a15472750a4b253dfd1c229.
