### ISSUE TITLE
Bug when using ElsaWorkflowDefinitonEditor without ElsaStudio

### ISSUE THREAD

**Issue by bskfrederik** [elsa-workflows/elsa-core#4486]
We are currently using the WorkflowDefinitionEditor in a web app without using the studio component. In that scenario the editor can't display any activity because elsa-studio is not defined. By replacing
`document.getElementsByTagName('elsa-studio)[0];`
 with 
`document.getElementsByTagName('elsa-flowchart')[0];` in shapes.ts
the error seems to be fixed and the WorkflowDefintionEditor can be used as standalone component.

**Comment by sfmskywalker** [comment]
I see what you mean. Since these activity elements are children of the flowchart component anyway, your change works fine. 👍🏻
