### ISSUE TITLE
trigger a httpendpoint failed

### ISSUE THREAD

**Issue by MartinLiL** [elsa-workflows/elsa-core#4488]
I Created one workflow:  1)HttpEndpoint1  2)WriteHttpResponse1  3)HttpEndpoint2  4)   WriteHttpResponse2
The steps:
  1) https://localhost:7193/workflows/first    then run the activity  HttpEndpoint1  and WriteHttpResponse1  

Then I trigger the  HttpEndpoint2  with  https://localhost:7193/workflows/trigger?workflowinstanceId=

Can't resume the workflow, HttpEndpoint2  can't be fired.

The reason may be, that we should add one method GetActivityInstanceId  in WorkflowsMiddleware.cs

Gets the hash value in the method CreateBookmark  of ActivityExecutionContext  with  the  ActivityInstanceId

 var workflowMatches = (await _workflowRuntime.FindWorkflowsAsync(workflowsFilter, cancellationToken)).ToList();

triggerOptions = new TriggerWorkflowsOptions(correlationId, workflowInstanceId, default, input);    here the ActivityInstanceId is null

I don't know if my way is wrong or if this is an issue. thanks.

Please refer to the following JSON file.

[trigger-htt-endpoint.zip](https://github.com/elsa-workflows/elsa-core/files/12742886/trigger-htt-endpoint.zip)

**Comment by sfmskywalker** [comment]
Fixed via 01bfc15df9178000a69eb6f8362240674bdd2236
