### ISSUE TITLE
Service bus Receive Message can't be use multiple time in a workflow

### ISSUE THREAD

**Issue by jdevillard** [elsa-workflows/elsa-core#4494]
If we try to use the `Azure Service Bus Message Receive` activity as a Trigger AND during a workflow, these following lines introduce an issue :

https://github.com/elsa-workflows/elsa-core/blob/98e424faa27bec27409e1fe705f3dfe2ecef89d9/src/modules/Elsa.AzureServiceBus/Activities/MessageReceived.cs#L90C1-L96C10

indeed, the `Workflow Context` see the First `InputKey` Message and re-use it instead of creating bookmark.

**Comment by jdevillard** [comment]
as I've done more test, it seems that currently we can't use this activity more than once in a Workflow due to the `context.getInput`. I think we need to get the info from the bookmark and not from an input variable

**Comment by sfmskywalker** [comment]
Makes sense. I know you have been working on a PR, will it fix this issue by any chance?

**Comment by jdevillard** [comment]
Yes this should be fix with the #4512 PR.

The Unit Test `Receive_1_Message_Should_Block_If_One_Receive()` aims to describe the case. Where we have a workflow with 2 receive from different topic/sub and only 1 message is sent.

**Comment by sfmskywalker** [comment]
I guess we can close this one now that your PR has been merged?
