### ISSUE TITLE
"For" Activity shouldn't assume direction of Step

### ISSUE THREAD

**Issue by solutionmania** [elsa-workflows/elsa-core#4496]
The 'For' activity currently assumes the direction in which it should 'Step'. When the 'Start' is lower than the 'End' it counts up and when the 'Start' is higher than the 'End' it counts down.

In the event that you are setting the 'End' value from a variable - and that variable could be zero, I would expect the following setup to yield **no** iterations:
- Start: 1
- End: 0 (from a variable - in other circumstances, this could be 1 or more)
- Step: 1

However - the current implementation detects that Start is greater than End and iterates for both the value '1' and '0'.

I would only expect this behaviour if I were to explicitly set Step to '-1'. This would mirror common behaviour of 'for' loops in most programming languages (I appreciate this is a workflow engine, not a programming language - but I still think this would be a more useful implementation).

To achieve my goals at the moment I would have to have an 'If' before the 'For' to detect the zero case. If the 'For' activity were changed as I propose, and the current behaviour were still desirable, a simple JavaScript expression could be used to affect the sign of the Step variable.

Alternatively - we could add another boolean input parameter to enable the 'Auto-Detection' of the Step direction - when set it would continue with the current behaviour. When not set, it would behave as I describe.

I'd be happy to submit a PR with a change for this if you agree that this is the way to go.

**Comment by sfmskywalker** [comment]
You make a very strong case and I can’t but 100% agree. Thank you for setting this straight, I’ll review your PR shortly.

**Comment by sfmskywalker** [comment]
I had a quick look and I see you opted to add an option to control the behavior. But I like your suggestion to just use -1 for the Step value better, which aligns with the way it works in a real programming language.

**Comment by solutionmania** [comment]
Hello. No problem - I can amend the PR based on your feedback.

I decided to go that way because it would provide backwards-compatibility for anyone who has already built flows expecting the current behaviour (due to the default value of the parameter).

Requiring a negative step value to make it count down would effectively be a 'breaking change'. In my current implementation (in the PR) you effectively get the current behaviour by default, but can optionally enable the need to specify the direction of the 'Step'.

**Comment by sfmskywalker** [comment]
I understand and it’s the right approach, but since this is unreleased software I think we can permit a breaking change as long as we announce it. I’d like to try and keep the codebase as clean as possible before the official release and start out with as little deprecated code sections as possible. If this happened post-release, we’d have to keep it in for a very long time.

**Comment by solutionmania** [comment]
No problem - will update the PR as soon as possible (albeit it's only a tiny change - hopefully every little helps!)...

**Comment by sfmskywalker** [comment]
Thank you! And absolutely, every little bit is helpful 🙏🏻

**Comment by solutionmania** [comment]
PR has been updated. I took the liberty of adding the 'Step' parameter to the constructor alongside the existing 'Start' and 'End'. Hopefully this will ensure it's a the forefront of people's mind when they're implementing it (at least via code).

Also updated related sample project and test.

**Comment by sfmskywalker** [comment]
PR looks great. Thank you!
