### ISSUE TITLE
Elsa v3 task completion API not able to find a bookmark

### ISSUE THREAD

**Issue by AndrewNikolin** [elsa-workflows/elsa-core#4511]
Hi!
I was looking into v3, and my particular interest was the task completion which is showcased in the Onboarding sample. Unfortunately, neither the manually implemented sample (from the v3 docs), nor the one from the samples directory on the repo (Onboarding.Web and Onboarding.WorkflowServer) can properly complete the task. I've debugged a little into the framework source code, and from the looks of it seems that the hasher used to find a bookmark for a specific task instance misses to calculate the proper bookmark Id, because the input context contains only the `TaskId` and not the `ActivityId`. When I manually picked up the expected `hash` from the workflow instance and set it in the debugger (overwrote calculated hash) the task completion happened fine.

I'm fairly new to elsa (just 2-3 days in v3) and not sure I figured out the root cause correctly, so this might need another confirmation

**Comment by AndrewNikolin** [comment]
Debugged using original sources: when the workflow instance is created the hash for the run task activity is calculated using task ID, task name, activity instance Id and activity type name. But when the rest request to complete the task is executed only the task Id and type name is provided for hash calculations, which then results in a miss when querying storage

**Comment by sfmskywalker** [comment]
Hi @AndrewNikolin , thank you for reporting this bug. Your analysis is spot-on and has been fixed via c9e2b11dfe3718bbf02eac202f59fdce9f17cc74 👍🏻
