### ISSUE TITLE
Elsa V3 designer publish workflow returns 415 unsupported media type response

### ISSUE THREAD

**Issue by bskfrederik** [elsa-workflows/elsa-core#4516]
When publishing a single workflow, the backend returns a 415 repsonse.

The bug can be solved when adding a request body to the post request in WorkflowDefinitionsApi line 20. 
`const response = await httpClient.post<WorkflowDefinition>("workflow-definitions/${request.definitionId}/publish");`

**Comment by sfmskywalker** [comment]
Thanks for the fix!
