### ISSUE TITLE
Add Elsa Client Created very weird delegating handler issue where it was instantiated twice in the http delegate pipeline

### ISSUE THREAD

**Issue by shanwayne** [elsa-workflows/elsa-core#4543]
The following [Elsa Client extension method](https://github.com/elsa-workflows/elsa-core/blob/8c76360f5d6ff9246dbd901ce475ba60b3dba5b7/src/clients/Elsa.Api.Client/Extensions/DependencyInjectionExtensions.cs#L37C80-L37C101) created a scenario the ApiMessagingHandler was created twice and due to registering itself in the builder method. 

Expected:
services.AddElsaClient(options => options...);

Workaround:
Use provided builder override to prevent (duplicate?) registration of the ApiMessagingHandler.

**Comment by sfmskywalker** [comment]
Definitely a great catch @shanwayne !

**Comment by berthendrickx** [comment]
@shanwayne Could you please provide me with a code sample of this services.AddElsaClient(...) code?

**Comment by shanwayne** [comment]
@berthendrickx To workaround the issue I just provided an empty builder like such
`.AddElsaClient(builder => {  }, options => options.BaseAddress = new Uri($"{elsaURl}/elsa/api", UriKind.Absolute));`

**Comment by berthendrickx** [comment]
@shanwayne Hmm, I must be missing some other dependencies then, can't seem to get it to work.. Thank you for your quick reply though!

**Comment by shanwayne** [comment]
You might also need to register an implementation for this interface
        IHttpMessageHandlerProvider. I can provide an example later

**Comment by berthendrickx** [comment]
I will look into this, thank you again!
