### ISSUE TITLE
HashSet  type Deserialize error

### ISSUE THREAD

**Issue by Nokecy** [elsa-workflows/elsa-core#4544]
https://github.com/elsa-workflows/elsa-core/blob/8c76360f5d6ff9246dbd901ce475ba60b3dba5b7/src/modules/Elsa.Workflows.Core/Serialization/Converters/PolymorphicObjectConverter.cs#L120

Unable to cast object of type 'System.Collections.Generic.HashSet`1[System.String]' to type 'System.Collections.IList'  @sfmskywalker

**Comment by sfmskywalker** [comment]
Are you using a HashSet in a custom activity or otherwise?

**Comment by Nokecy** [comment]
[[Fork  ](https://github.com/elsa-workflows/elsa-core/blob/8c76360f5d6ff9246dbd901ce475ba60b3dba5b7/src/modules/Elsa.Workflows.Core/Activities/Fork.cs#L63)](https://github.com/elsa-workflows/elsa-core/blob/8c76360f5d6ff9246dbd901ce475ba60b3dba5b7/src/modules/Elsa.Workflows.Core/Activities/Fork.cs#L63)

**Comment by sfmskywalker** [comment]
Gotcha, thank you.

**Comment by sfmskywalker** [comment]
PR merged. Thank you for your contributions @Nokecy !
