### ISSUE TITLE
V3 Login throws Exception when Username or Password is null

### ISSUE THREAD

**Issue by polferov** [elsa-workflows/elsa-core#4598]
## Issue and how to reproduce

1. create instance of Elsa Server and Elsa Studio (I am using Blazor Server)
1. go to login
1. leave username and/or password empty
1. press login
1. be sad because Exception 

## What is happening behind the scenes?

Elsa Studio calls the Elsa server's [Login Endpoint](https://github.com/elsa-workflows/elsa-core/blob/v3/src/modules/Elsa.Identity/Endpoints/Login/Endpoint.cs).

The Endpoint receives a (Login)Request containg username and password.
There is no validation being executed to check the values for null.

The endpoint starts out by calling `.Trim()` on the input values. This results in a `NullReferenceException` and a StatusCode 500.

```csharp
    public override async Task<LoginResponse> ExecuteAsync(Request request, CancellationToken cancellationToken)
    {
        var user = await _userCredentialsValidator.ValidateAsync(request.Username.Trim(), request.Password.Trim(), cancellationToken);
        ...
```

## Solution(?)

The Endpoint is built using FastEndpoints. While I am personally not familiar with this framework, I assume that adding a validator should not be too hard.

Additionally, input validation should also be implemented on the client side, providing feedback directly in the ui.

### Proceeding-Proposal

As I am a backend engineer, I will take a look on the server side.

Also, as a backend engineer, my UIs may often be functional, though usually not very pretty.
Hence, I would appreciate if someone with more UI skills than me, could help out with this :)

<hr>

## Note

I am using following versions:

```xml
      <PackageReference Include="Elsa" Version="3.0.0-preview.727" />
      <PackageReference Include="Elsa.Identity" Version="3.0.0-preview.727" />
      <PackageReference Include="Elsa.Workflows.Api" Version="3.0.0-preview.727" />
```

and

```xml
      <PackageReference Include="Elsa.Studio" Version="3.0.0-preview.94" />
      <PackageReference Include="Elsa.Studio.Core.BlazorServer" Version="3.0.0-preview.94" />
      <PackageReference Include="Elsa.Studio.Login.BlazorServer" Version="3.0.0-preview.94" />
```

**Comment by sfmskywalker** [comment]
Closing this, since a PR has been merged for this issue. Thanks again @polferov for your contributions!
