### ISSUE TITLE
Signal_url dont work with CustomTenantAccessor

### ISSUE THREAD

**Issue by Romelman123** [elsa-workflows/elsa-core#4599]
When create a SIgnal with Signal_url and send by mail, I try to conmtinue the flow with the signal, but the server dont receive the signal, i use the same flow with tenant not set and working correctly , the problem is with the tenant is set..

**Comment by bweltin** [comment]
Are using ElsaV2 or V3?

**Comment by Romelman123** [comment]
I am using elsa V2

**Comment by bweltin** [comment]
Have you used "UseTenantSignaler()" on ElsaOptions when registering Elsa in your startup?

**Comment by Romelman123** [comment]
Hey!!, Thank you I add the UseTenantSignaler() and is work correctly , Thank you.
