### ISSUE TITLE
Workflow Designer with BPMN support

### ISSUE THREAD

**Issue by GeorgeS2019** [elsa-workflows/elsa-core#460]
I would like **feedback if there is interest to have Elsa Workflow Designer support** the [Business Process Model and Notation](https://www.omg.org/spec/BPMN/2.0.2/) (BPMN)

![image](https://user-images.githubusercontent.com/49812372/99354696-33e18800-28a7-11eb-8d6d-4042a53651bd.png)

Currently there is on-going discussion to refractor the Elsa Workflow Designer - perhaps using [the Blazor Diagram framework ( which is inspired by React Diagram).](https://github.com/elsa-workflows/elsa-core/issues/362#issuecomment-727919052)

**Comment by sfmskywalker** [comment]
I still think this is interesting to have as an option. See also #39.

**Comment by GeorgeS2019** [comment]
@sfmskywalker  I have checked existing discussions on BPMN feature request posted here.  I am curious what others think of Elsa Workflow Designer supporting BPMN :-)

**Comment by craigfowler** [comment]
Dupe of #39
