### ISSUE TITLE
Cannot modify index with CosmosDB for MongoDB

### ISSUE THREAD

**Issue by daveelbro** [elsa-workflows/elsa-core#4658]
When using MongoDB via Azure CosmosDB the a project will not start due to the following error:
`{"Errors":["The unique index cannot be modified. To change the unique index, remove the collection and re-create a new one."]}`

This behaves differently to what is in MongoDB (Atlas).

Would it be possible to check if the index already exists before creating it to overcome this issue?

Link back to discord thread:
https://discord.com/channels/814605913783795763/1175544240915365950

This would enable an "all-azure" infrastructure when developing an app with Elsa.

Kind Regards,
Dave

**Comment by sfmskywalker** [comment]
Closed via #5083
