### ISSUE TITLE
.Net 8 support

### ISSUE THREAD

**Issue by GeorgievIt92** [elsa-workflows/elsa-core#4667]
Any idea when we will have .net 8 support so we can update our projects?
Thank you.

**Comment by sfmskywalker** [comment]
Hi! Absolutely, .NET 8 support was [added around 3 days ago](bec8cbc3224c2048077bd5325612bce1526edb6f).

**Comment by GeorgievIt92** [comment]
Great, thank you.
Will elsa v2 be upgraded to .NET 8 also?

**Comment by benjaminoerskov** [comment]
@sfmskywalker @swimmesberger any idea when this will be released? This is blocking us from updating our project to .NET 8.

**Comment by swimmesberger** [comment]
@benjaminoerskov Big part of .NET 8 support is already merged in the 2.x part, I'm currently working on fixing the Github build pipeline.

**Comment by benjaminoerskov** [comment]
@swimmesberger disregard my message. I mixed up dotnet8 upgrade and Elsa v2 => v3 upgrade :)

**Comment by swimmesberger** [comment]
@sfmskywalker I guess this can be closed now with the release of [2.14.0](https://github.com/elsa-workflows/elsa-core/releases/tag/2.14.0)

**Comment by sfmskywalker** [comment]
Thanks everyone for your contributions! 🙏🏻

**Comment by Rathna314** [comment]
Hi Does Elsa 2.11.1 work with .Net 8.0

**Comment by sfmskywalker** [comment]
Hey @Rathna314 , Elsa 2.14 should indeed support .NET 8. Please give it a try and let us know if you run into issues
