### ISSUE TITLE
Getting error no such activity exists (While) when trying to use the while activity

### ISSUE THREAD

**Issue by gandresButech** [elsa-workflows/elsa-core#467]
When trying to use the while activity (either in the code directly or in the dashboard) I get the following error:

Version 1.4.5.1
![image](https://user-images.githubusercontent.com/69162175/99563499-52bf4780-2997-11eb-93e3-59f10aa3bf80.png)

**Comment by sfmskywalker** [comment]
Can you show the definition of the workflow? It looks like you might be using an activity that's not registered with DI.

**Comment by gandresButech** [comment]
`using Elsa;
using Elsa.Activities;
using Elsa.Activities.Console.Activities;
using Elsa.Activities.ControlFlow.Activities;
using Elsa.Activities.Http.Activities;
using Elsa.Expressions;
using Elsa.Scripting.Liquid;
using Elsa.Services;
using Elsa.Services.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Threading.Tasks;

namespace ElsaTest
{
    public class TestWhileWorkflow : IWorkflow
    {
        public void Build(IWorkflowBuilder builder)
        {
            builder
                .StartWith<ReceiveHttpRequest>(
                    x =>
                    {
                        x.Method = HttpMethod.Get.Method;
                        x.Path = new Uri("/hello-world-test", UriKind.Relative);
                    }
                )
                .Then<SetVariable>(
                    x =>
                    {
                        x.VariableName = "i";
                        x.ValueExpression = new LiteralExpression<int>("0");
                    })
                .Then<While>(
                    x => x.ConditionExpression = new LiteralExpression<bool>("i<10"),
                    doWhile =>
                    {
                        doWhile
                            .When(OutcomeNames.Iterate)
                            .Then<WriteLine>(x => x.TextExpression = new LiquidExpression<string>("Sending reminder"))
                            .Then<SetVariable>(
                                x =>
                                {
                                    x.VariableName = "i";
                                    x.ValueExpression = new LiteralExpression<int>("i+1");
                                })
                            .Then(doWhile);
                    })
                .Then<WriteHttpResponse>(
                    x =>
                    {
                        x.Content = new LiteralExpression("<h1>Hello World!</h1>");
                        x.ContentType = "text/html";
                        x.StatusCode = HttpStatusCode.OK;
                        x.ResponseHeaders = new LiteralExpression("X-Powered-By=Elsa Workflows");
                    }
                );
        }
    }
}`

**Comment by gandresButech** [comment]
it seems to be hung up on the while activity that is included in ElsaActivities.ControlFlow.Activities

**Comment by sfmskywalker** [comment]
Can you fix the code syntax support please? It's a bit hard to read this way. Use triple back ticks on the first line and also on the last line, like so:

```
```
```
```

**Comment by sfmskywalker** [comment]
Perfect :)

**Comment by gandresButech** [comment]
sorry, fixed

**Comment by sfmskywalker** [comment]
> it seems to be hung up on the while activity that is included in ElsaActivities.ControlFlow.Activities
You're right, the error already stated the missing activity "While". I completely misread, sorry.

I'll see if I can reproduce.

**Comment by sfmskywalker** [comment]
Can you show me the DI setup?

**Comment by gandresButech** [comment]
```
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Builder;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Identity.UI;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.HttpsPolicy;
using Microsoft.EntityFrameworkCore;
using ElsaTest.Data;
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.Hosting;
using Elsa.Activities.Email.Extensions;
using Elsa.Activities.Http.Extensions;
using Elsa.Activities.Timers.Extensions;
using Elsa.Dashboard.Extensions;
using Elsa.Persistence.EntityFrameworkCore.DbContexts;
using Elsa.Persistence.EntityFrameworkCore.Extensions;
using Elsa.Activities.Console.Extensions;
using Elsa.Activities.ControlFlow;

namespace ElsaTest
{
    public class Startup
    {
        public Startup(IConfiguration configuration)
        {
            Configuration = configuration;
        }

        public IConfiguration Configuration { get; }

        // This method gets called by the runtime. Use this method to add services to the container.
        public void ConfigureServices(IServiceCollection services)
        {
            services
                // Add services used for the workflows runtime.
                .AddElsaCore(elsa => elsa.AddEntityFrameworkStores<SqliteContext>(options => options.UseSqlite(Configuration.GetConnectionString("Sqlite"))))
                .AddHttpActivities(options => options.Bind(Configuration.GetSection("Elsa:Http")))
                .AddEmailActivities(options => options.Bind(Configuration.GetSection("Elsa:Smtp")))
                .AddTimerActivities(options => options.Bind(Configuration.GetSection("Elsa:Timers")))
                .AddConsoleActivities()
                .AddWorkflow<TestWhileWorkflow>()
                // Add services used for the workflows dashboard.
                .AddElsaDashboard();
            services.AddActivity<NewTestActivitiy>();
            services.AddSingleton(Console.Out);
            services.AddDbContext<ApplicationDbContext>(options =>
                options.UseSqlite(
                    Configuration.GetConnectionString("Sqlite")));
            services.AddDefaultIdentity<IdentityUser>(options => options.SignIn.RequireConfirmedAccount = true)
                .AddEntityFrameworkStores<ApplicationDbContext>();
            services.AddRazorPages();
        }

        // This method gets called by the runtime. Use this method to configure the HTTP request pipeline.
        public void Configure(IApplicationBuilder app, IWebHostEnvironment env)
        {
            if (env.IsDevelopment())
            {
                app.UseDeveloperExceptionPage();
                app.UseDatabaseErrorPage();
            }
            else
            {
                app.UseExceptionHandler("/Error");
                // The default HSTS value is 30 days. You may want to change this for production scenarios, see https://aka.ms/aspnetcore-hsts.
                app.UseHsts();
            }

            app.UseHttpsRedirection();
            app.UseStaticFiles();
            app.UseHttpActivities();

            app.UseRouting();

            app.UseAuthentication();
            app.UseAuthorization();

            app.UseEndpoints(endpoints =>
            {
                endpoints.MapRazorPages();
                endpoints.MapControllers();
            });
            app.UseWelcomePage();
        }
    }
}```

**Comment by sfmskywalker** [comment]
I see. You need to do `service.AddControlFlowActivities()` next to the other calls (like services.AddHttpActivities). If you do `AddElsa()` instead of `AddElsaCore`, this will be done for you.

**Comment by gandresButech** [comment]
I apologize.  This was my fault.  I had some issue upgrading the packages via nuget to v1.4.5.1.
This ended up with the ELSA package not being installed.  So I had no .AddElsa().  This is why I switched to .AddElsaCore.
I installed the updated version of ELSA package and my issue is fixed.

Thanks

**Comment by sfmskywalker** [comment]
No worries, glad it worked out!
