### ISSUE TITLE
Elsa V3 - Dapper DeleteAsync

### ISSUE THREAD

**Issue by vladc-3sd** [elsa-workflows/elsa-core#4676]
I think there is a bug in the [DeleteAsync](https://github.com/elsa-workflows/elsa-core/blob/50ac0e93719cc01df070165293001d990e9ade48/src/modules/Elsa.Dapper/Services/Store.cs#L255) method.

[Here](https://github.com/elsa-workflows/elsa-core/blob/50ac0e93719cc01df070165293001d990e9ade48/src/modules/Elsa.Dapper/Services/Store.cs#L257), when creating the query, it uses a fixed string ("rowid") as the primary key insted of the PromaryKey property.

**Comment by sfmskywalker** [comment]
Nice catch - the "rowid" field is specific to SQLite. I will update this 👍🏻

**Comment by sfmskywalker** [comment]
Fixed via 6268fe474153fd1df0f9ebdda0e9475872b6ec2c
