### ISSUE TITLE
Async/Dynamic Dropdown/Checklist Items

### ISSUE THREAD

**Issue by NrujalSharma** [elsa-workflows/elsa-core#4680]
### Description:
I am new to C# and currently working on dynamically populating the options of a dropdown field in the Event.cs activity based on data from an API call.

### Code snippet:
```c#
[Input(Description = "Group assigned to this step", UIHint = InputUIHints.Dropdown, Options = new[] { "", "Sale", "Service", "Client", "Marketing" })]
public Input<string> AssignedTo { get; set; } = default!;
```

### Desired Solution:
I want to fetch the dropdown options from an API call and update the options dynamically.

### Additional Information:
I am not sure about the best practices in C# for achieving this.

### Expected Output:
The dropdown options should be fetched from an API call and dynamically populated in the dropdown field in the Event.cs activity.

### Current Behavior:
The dropdown options are hardcoded, and I need guidance on how to make API calls and update the options dynamically.

### Additional Context:
I am open to suggestions and guidance as I am relatively new to C# development. Any help would be greatly appreciated.

**Comment by jdevillard** [comment]
Hello ,

The idea is to decorate your poperty using the OptionsProvider like this : 
```csharp
  [Input(
        Description = "The content type to use when sending the request.",
        OptionsProvider = typeof(VehiculeOptionsProvider),
        UIHint = InputUIHints.Dropdown
    )]
        public Input<string> Brand { get; set; }
    }
```

Then you implement you Provider using the `IActivityPropertyOptionsProvider`

```csharp
  public class VehiculeOptionsProvider : IActivityPropertyOptionsProvider
    {
        private readonly Random _random;

        public VehiculeOptionsProvider()
        {
            _random = new Random();
        }

        public ValueTask<IDictionary<string, object>> GetOptionsAsync(PropertyInfo property, object? context = null, CancellationToken cancellationToken = default)
        {

            var items = new List<SelectListItem>()
            {
                new ("BMW","1"  ),
                new("Tesla" ,"2" ),
                new ("Peugeot","3"  ),
                new (_random.Next(100).ToString(), "4"  )
            };


            return new(new Dictionary<string, object>() { ["items"] = items });
        }
    }
```

here instead of creating a new list you can create your `HTTP Client` and then call you custom backend API.

_NB : for now, this is called at the startup task, this feature was implemented in v2 and is currently in development for v3, some PR are waiting for approval and some (minor) code update will be necessary after the PR integration_

**Comment by NrujalSharma** [comment]
This is exactly what I wanted. Thanks @jdevillard 🥳🥳!!
