### ISSUE TITLE
Help !! elsa workflow v3 web designer 

### ISSUE THREAD

**Issue by Khalid92Sa** [elsa-workflows/elsa-core#4685]
Dears
Can anyone help ? I tried to clone to git master branch then moved to branch v3, but I got many errors related to .NET 8 SDK, 
I downloaded the .NET SDK 8 but still the issue not solved? 

https://dotnet.microsoft.com/en-us/download/visual-studio-sdks
.NET 8.0 Visual Studio 2022 SDK / x64 + x86 
also Runtime (Windows) x64 / x86

Then I moved to branch v3-740-hotfixes-1, and once I run the application [Elsa.AllInOne.Web] I got empty page

**Comment by sfmskywalker** [comment]
If you share the specific errors you are seeing, perhaps we can see what's going on.

When moving to the older hotfix-1 branch (which I do not recommend), you will have to first build the client assets. Although this part is outdated, it reminds me I still need to write a "How to build from source" section in the readme.

**Comment by sfmskywalker** [comment]
Hi @Khalid92Sa , I will close this issue for now, but please feel free to reopen it in case you still need help. In that case, it would be helpful if you could provide more details about the errors you are getting. Thank you.
