### ISSUE TITLE
tasks/{taskId}/complete endpoint returns 200, but status still is Suspended

### ISSUE THREAD

**Issue by avhovsepyan** [elsa-workflows/elsa-core#4698]
Hi there,

While implementing ELSA 3.0 we have some problem regarding Webhooks. Complete function returns 200 (Success), but workflow status still Suspended.
We also tried an example, which is described in Documentation (https://v3.elsaworkflows.io/docs/guides/external-app-integration), but the behavior is the same.

**Comment by brunozampaglione** [comment]
https://github.com/elsa-workflows/elsa-core/issues/4664

Both issues are the same.....

**Comment by avhovsepyan** [comment]
After version 3.0 release, the issue is completed
