### ISSUE TITLE
Elsa 3.0 - Persistence

### ISSUE THREAD

**Issue by NightWuYo** [elsa-workflows/elsa-core#4699]
Cannot find 3.0 version of Elsa.Persistence.EntityFramework.* packages in nuget.org

Does this mean that Elsa 3.0 does not support persistence yet?

Thanks

**Comment by Icidis** [comment]
Hi @NightWuYo ,

It seems that 3.0 has different package names

Elsa.Persistence.EntityFramework.* are now Elsa.EntityFrameworkCore.*

**Comment by NightWuYo** [comment]
Got it, thank you so much, @Icidis
