### ISSUE TITLE
Is this available on nuget?

### ISSUE THREAD

**Issue by dodyg** [elsa-workflows/elsa-core#47]
I'd like to try it out but I can't find it on nuget for 'elsa'.

**Comment by sfmskywalker** [comment]
It's available on MyGet. I just added a cool shield to the Readme file:

[![MyGet (with prereleases)](https://img.shields.io/myget/elsa/vpre/Elsa.Core.svg?label=myget)](https://www.myget.org/gallery/elsa)

Once everything is stable and feature-complete (for the v1 scope), the packages will be published to NuGet.
