### ISSUE TITLE
Elsa 3 - Blocking bug with Join activity inside Parallel For Each

### ISSUE THREAD

**Issue by b0rv3g4r4** [elsa-workflows/elsa-core#4703]
I detect in my flow a bug with the join activity inside of parallel for each (FlowChart)
With the first complete of Wait Any configured Join in any iteration its block all of the pending iterations
I tough that is clearing and closing all the pending work instead of just its iteration

![Captura de pantalla 2023-12-13 a las 17 45 21](https://github.com/elsa-workflows/elsa-core/assets/34290325/134f1eeb-e4b1-4180-b3e2-155ae6e0de1f)

![Captura de pantalla 2023-12-13 a las 17 45 17](https://github.com/elsa-workflows/elsa-core/assets/34290325/965a3682-35d5-4b5a-bfec-4f9c1b9e4291)

[bug-example.json.zip](https://github.com/elsa-workflows/elsa-core/files/13663445/bug-example.json.zip)

Maybe related with #4013 

Server version: 3.0.0-preview.894
Studio version: 3.0.0-preview.164

**Comment by sfmskywalker** [comment]
Great catch! And cheers for the repro 👍🏻
