### ISSUE TITLE
Elsa.CSharp Nuget package doesn't exist

### ISSUE THREAD

**Issue by popisms** [elsa-workflows/elsa-core#4706]
Trying to follow your documentation here: https://github.com/elsa-workflows/elsa-core/tree/eeba1f8e9b1cb5c986e6afadee4f5528438a679d#elsa-server--elsa-studio

There is no Elsa.CSharp Nuget package, including in prerelease.

**Comment by Icidis** [comment]
Hi @popisms,

The Elsa.CSharp package is still in preview and not all functions have been implemented. 

You can see a demonstration here on YouTube: [Elsa Workflows Community Meeting 43](https://www.youtube.com/watch?v=h8olktNa4ZY)

If you happy to use the preview package you can find it in the feedz.io NuGet feed shown below

https://f.feedz.io/elsa-workflows/elsa-3/nuget/index.json

**Comment by kobeliu9527** [comment]
Yes, I found it in the source code, but not on nuget. Please add it, thank you, big shot

**Comment by sfmskywalker** [comment]
The package is now also available on nuget: https://www.nuget.org/packages/Elsa.CSharp
