### ISSUE TITLE
Simple workflow with ReadLine activity freezes

### ISSUE THREAD

**Issue by francotiveron** [elsa-workflows/elsa-core#4717]
I tried a simple workflow with a Readline Activity, using the docker container.

When I start the workflow, a blue running bar appears and the workflow freezes there. I guess it is waiting something to be written somewhere, but it is not clear where to write it.

![image](https://github.com/elsa-workflows/elsa-core/assets/8280970/3031bd19-29ec-4291-8c2e-e01d0c81c4b7)

**Comment by sNakiex** [comment]
The readline activity is part of the Console activities group. It expects a line to be entered in the commandpromt of the backend.
Since there is no input, it will stay running till it received one.

**Comment by francotiveron** [comment]
The WriteLine activity is also a console activity, however it works when run in the designers and shows the output. I would expect that an input pane appears in the browser to insert the input of ReadLine. Or, at least, a message should appear saying that the ReadLine activity cannot be used when running in the studio.

**Comment by sfmskywalker** [comment]
> I would expect that an input pane appears in the browser to insert the input of ReadLine

This would be awesome :)

> Or, at least, a message should appear saying that the ReadLine activity cannot be used when running in the studio.

Adding some clarification is a good idea. One should still be able to use this activity from the designer. For example, someone might be designing a workflow for use in a console application. But, when executing such a workflow from the Studio, it would be great to somehow expose a UI that transports the input straight into the application console on the server.
