### ISSUE TITLE
Elsa Web example 1 doesn't write anything to console

### ISSUE THREAD

**Issue by francotiveron** [elsa-workflows/elsa-core#4718]
https://v3.elsaworkflows.io/docs/installation/elsa-web

![image](https://github.com/elsa-workflows/elsa-core/assets/8280970/d3d4d33b-ebd8-477c-96a1-c4df0c8cd3f0)

![image](https://github.com/elsa-workflows/elsa-core/assets/8280970/3dbd8f0f-0875-4d45-8bf3-39aebb1713c1)

**Comment by sfmskywalker** [comment]
Hey there, the WriteLine activity only writes to the .NET application console, and not to the browser's console. I do get the confusion, since both terminals are called "console" 😄
