### ISSUE TITLE
The workflow engine keeps my workflow processes on hold with its idle status.

### ISSUE THREAD

**Issue by canerarif** [elsa-workflows/elsa-core#4720]
Hello,

I am using ELSA 2.12.0 version in my project. I have a workflow process and my processes can take a long time. For example, processes that may take 2-3 days to complete. ELSA does not cause any problems for me until I start 5 workflow processes and it can run them, but when I want to run more than 5 processes, it shows its status as "Idle" as seen in the picture below and does not start the process. I want all of my processes to progress simultaneously. What should I do for it. I will be grateful if you could help me.

![22222](https://github.com/elsa-workflows/elsa-core/assets/16638931/41f1435a-2d39-483b-8a76-cb7e3f054001)

**Comment by dwoldo** [comment]
@canerarif how are you triggering these workflows, Quartz timer, HTTP, etc? The background worker library Rebus has a default max parallel lower than desired. We've set this to a higher number.

Here is quite and link to a ither issue I previously found helpful:

"Another example is the default queue worker for processing workflow execution jobs happening in the background. Elsa uses Rebus to send and process messages, so you can configure Rebus with Rebus-specific options. Example:"
 https://github.com/elsa-workflows/elsa-core/discussions/1308#:~:text=Another%20example%20is%20the%20default%20queue%20worker%20for%20processing%20workflow%20execution%20jobs%20happening%20in%20the%20background.%20Elsa%20uses%20Rebus%20to%20send%20and%20process%20messages%2C%20so%20you%20can%20configure%20Rebus%20with%20Rebus%2Dspecific%20options.%20Example%3A

I'm the reply I quoted, example code shows adjusting this. See if that helps.

**Comment by canerarif** [comment]
hi @dwoldo 
I use the signal received activity when triggering my workflow processes. Thank you very much for your answer. I tried it in my app and it was successful.
