### ISSUE TITLE
SqlServerDbConnectionProvider using Sqlite dialect

### ISSUE THREAD

**Issue by SamuelMcAravey** [elsa-workflows/elsa-core#4723]
We found this line appears to be incorrect when using the SqlServerDbConnectionProvider with Dapper:
https://github.com/elsa-workflows/elsa-core/blob/6a5835e51ac2ffc70a77011149fa9c5ceab79328/src/modules/Elsa.Dapper/Services/SqlServerDbConnectionProvider.cs#L46

The fix should be to use the SqlServerDialect instead.

**Comment by sfmskywalker** [comment]
You're right, thanks for catching & reporting this 👍🏻
