### ISSUE TITLE
Docs and samples for Dropins?

### ISSUE THREAD

**Issue by johnmcbride** [elsa-workflows/elsa-core#4724]
Is there some documentation on using the dropins for watching a directory and loading activities dynamically found? Also are there any samples showing this (Iknow there is some code in the dropsin package, but not sure if that is where I should be looking.

**Comment by sNakiex** [comment]
As far as I know the only information there currently is is a little example [here](https://github.com/elsa-workflows/elsa-core/tree/main/src/samples/drop-ins/SampleDropIn) You can also register activities trough a folder by changing the dropin configuration. You could have a look at the [initial pullrequest](https://github.com/elsa-workflows/elsa-core/pull/4471/commits/3edd2ed9b5ad1eefe569748972735eac6eec86e0) for the dropin functionality. It should make it quite easy to understand.

**Comment by sfmskywalker** [comment]
I created an issue for adding a section about DropIns here: https://github.com/elsa-workflows/elsa-documentation/issues/39
