### ISSUE TITLE
Unable to create working Elsa Studio Blazor Server application as per official documentation

### ISSUE THREAD

**Issue by francotiveron** [elsa-workflows/elsa-core#4732]
I did exactly, step by step as described in https://v3.elsaworkflows.io/docs/installation/elsa-studio-blazorserver, building the project fails with error:

```
Severity	Code	Description	Project	File	Line	Suppression State
Error	CS1739	The best overload for 'AddRemoteBackend' does not have a parameter named 'configureElsaClientBuilderOptions'	HorthFinancial.NinjaTrader.Workflows.Studio	C:\Root\Work\Horth\Work\Ninja\Code\HorthFinancial.NinjaTrader.Workflows.Studio\Program.cs	27	N/A
```

![image](https://github.com/elsa-workflows/elsa-core/assets/8280970/eaa66572-5e11-4214-aee7-980cfd9ee731)

To have something running I modified the source as follows

```
//builder.Services.AddRemoteBackend(
//    options => configuration.GetSection("Backend").Bind(options),
//    configureElsaClientBuilderOptions: elsaClient => { elsaClient.ConfigureHttpClientBuilder = httpClientBuilder => { httpClientBuilder.AddHttpMessageHandler<AuthenticatingApiHttpMessageHandler>(); }; });

builder.Services.AddRemoteBackend(options => configuration.GetSection("Backend").Bind(options));
```

With this iI am able to start the application, however, as soon I try to login:

![image](https://github.com/elsa-workflows/elsa-core/assets/8280970/4e1c0e3a-68e0-40e0-bf73-15509a2b21c9)

![image](https://github.com/elsa-workflows/elsa-core/assets/8280970/92a763ac-ebea-49f5-aeb6-40c6ab3cad5d)

**Comment by sfmskywalker** [comment]
Thanks for reporting this issue. The documentation has been updated. The key line missing is this:

```csharp
builder.Services.AddRemoteBackend(
    elsaClient => elsaClient.AuthenticationHandler = typeof(AuthenticatingApiHttpMessageHandler),
    options => configuration.GetSection("Backend").Bind(options));
```

I will close this issue as resolved, but please feel free to reopen if you're still having this issue and to continue the conversation.
