### ISSUE TITLE
Elsa 3.0.0 not working with Blazor-Server 7.0

### ISSUE THREAD

**Issue by itniels** [elsa-workflows/elsa-core#4740]
We are trying to test out Elsa 3 using blazor-server, and I cannot get it to compile due to errors with `Elsa.Api.Client` missing some references (see image).
I have followed the documentaion here: https://v3.elsaworkflows.io/docs/installation/elsa-studio-blazorserver

![image](https://github.com/elsa-workflows/elsa-core/assets/15611687/cf766676-812d-411c-8653-063e317b9c35)

## project file
```
<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net7.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Elsa.Studio" Version="3.0.0" />
    <PackageReference Include="Elsa.Studio.Core.BlazorServer" Version="3.0.0" />
    <PackageReference Include="Elsa.Studio.Login.BlazorServer" Version="3.0.0" />
  </ItemGroup>

</Project>
```

**Comment by KnibbsyMan** [comment]
I am having the same issue. I have raised it over on the Studio Project too.

https://github.com/elsa-workflows/elsa-studio/issues/103

**Comment by NightWuYo** [comment]
I got the same issue, asked in the official Discord channel as well.

**Comment by NightWuYo** [comment]
I have got the answer, you just need to install the Elsa.Api.Client nuget package.

Anyhow, the doc needs to be updated. (Or Elsa.Api.Client should be depended by other packages)

**Comment by mohdali** [comment]
There is a mismatch of depndency in the nuget package. The solution is to explicitly mention the latest version of Elsa.Api.Client in the project file.

`<PackageReference Include="Elsa.Api.Client" Version="3.0.0" />`

**Comment by itniels** [comment]
Thank you @NightWuYo and @mohdali

**Comment by sfmskywalker** [comment]
Fixed via https://github.com/elsa-workflows/elsa-studio/pull/104 - thanks @mohdali !
