### ISSUE TITLE
Please update FastEndpoints nuget package version

### ISSUE THREAD

**Issue by NightWuYo** [elsa-workflows/elsa-core#4747]
Currently, Elsa.Api.Common depends on below BETA nuget packages:
- [FastEndpoints](https://www.nuget.org/packages/FastEndpoints/) (>= 5.20.1.7-beta)
- [FastEndpoints.Security](https://www.nuget.org/packages/FastEndpoints.Security/) (>= 5.20.1.7-beta)
- [FastEndpoints.Swagger](https://www.nuget.org/packages/FastEndpoints.Swagger/) (>= 5.20.1.7-beta)

They all already have official released version already, please update the version number to 5.21.2.

**Comment by sfmskywalker** [comment]
Done via 3b48636ced046ab544da623241b445263b37e218

**Comment by NightWuYo** [comment]
Hi @sfmskywalker 
Thanks for your quick response.

One thing I'm a bit confused, I have created https://github.com/elsa-workflows/elsa-core/pull/4749 two days ago, and also has linked that pull request to this issue.
You did not merge that, but created a nother commit instead today (with exact same changes as my pull request).

Is this expected?

**Comment by sfmskywalker** [comment]
@NightWuYo I’m terribly sorry about that, I completely overlooked your PR, otherwise I would have gladly merged it in instead of doing the same work twice. I will see what I can do to right this wrong. Thanks for letting me know about it.
