### ISSUE TITLE
use Alteration ---- ScheduleActivity error 

### ISSUE THREAD

**Issue by Nokecy** [elsa-workflows/elsa-core#4752]
https://github.com/elsa-workflows/elsa-core/blob/91b59a90efc647a5a0767aa42b2f3e9a6905e389/src/modules/Elsa.Workflows.Core/Contexts/WorkflowExecutionContext.cs#L481

System.InvalidOperationException : Sequence contains more than one matching element

NodeIdLookup.Single maybe NodeIdLookup.FirstOrDefault ? @sfmskywalker

**Comment by sfmskywalker** [comment]
Maybe, but perhaps there's a bug elsewhere and there shouldn't be more than one element in the lookup. So, instead of ignoring the duplicate, let's first try to understand the reason for it. Do you have steps to reproduce this issue we might look at?

**Comment by Nokecy** [comment]
Schedule  Composite Activity ?

**Comment by sfmskywalker** [comment]
Do you have a sample project and or workflow I can use to reproduce this behavior?

**Comment by Nokecy** [comment]
https://github.com/Nokecy/ElsaConsole_Demo  @sfmskywalker

**Comment by Nokecy** [comment]
Do you have any ideas ? @sfmskywalker

**Comment by sfmskywalker** [comment]
Hi there, I’m afraid I haven’t had the time yet to look into this. I will report back any findings and ideas I might have. Thank you for your patience.

**Comment by sfmskywalker** [comment]
I could reproduce the issue with your sample project, but when I updated it to use the latest preview package version `3.2.0-preview.1626`, it worked with no issue.

When updating to the current preview, please be aware that the following two types have been renamed:

- StartWorkflowRuntimeOptions -> StartWorkflowRuntimeParams
- ResumeWorkflowRuntimeOptions -> ResumeWorkflowRuntimeParams
