### ISSUE TITLE
SqlException: Invalid column name 'Scope'

### ISSUE THREAD

**Issue by comicon1234** [elsa-workflows/elsa-core#476]
Been fiddling around with the dashboard and creating Work flows visually, I have ran in to a repeatable issue. Once I create a work flow and either save as draft or publish, I get a exception when going back in to Work Flows "SqlException: Invalid column name 'Scope'." Any idea what I am doing wrong?

**Comment by sfmskywalker** [comment]
I can't seem to reproduce this. I assume you are using the Entity Framework Core persistence provider. What SQL database server are you using? Can you try and delete your database and run the migrations again?

**Comment by sfmskywalker** [comment]
I tried it on PostgreSQL too, but it works fine there as well. I suspect your database might by out of sync. Originally, the "Scope" column was named "Scopes" (plural). If you rename the column from "Scopes" to "Scope", it should work again.

**Comment by comicon1234** [comment]
Spot on. Thanks. I had to use a older nuget version because my .net core is only at 3.0, which caused the old migration with incorrect column name. Thanks for the help
