### ISSUE TITLE
RunTask Activity Throws Cannot resolve scoped service

### ISSUE THREAD

**Issue by sfmskywalker** [elsa-workflows/elsa-core#4773]
When following the documentation on https://v3.elsaworkflows.io/docs/guides/external-app-integration the RunTask activity will throw an 'Cannot resolve scoped service 'Elsa.Workflows.Runtime.Services.BackgroundTaskDispatcher' from root provider.' exception due to a change in pull request #4753

**Comment by yspanj** [comment]
Looks like there are similar issues with the Azure Service module. Tried to get it to work in a separate project and ran into issue. Tried the same with the Alse.Samples.ASpNet.AzureServiceBusActivities but got the following exception

`
Elsa.AzureServiceBus.HostedServices.StartWorkers': Cannot consume scoped service 'Elsa.Workflows.Runtime.Contracts.ITriggerStore' 
`

**Comment by sfmskywalker** [comment]
Thanks for the additional information, much appreciated.
