### ISSUE TITLE
Type information in Designer expressions? 

### ISSUE THREAD

**Issue by dannmartens** [elsa-workflows/elsa-core#479]
Hi,

In programmatically defined workflows, we use generic typing, e.g. JavaScriptExpression<MyNamespace.MyModel>, to deserialize JSON into corresponding POCOs.

How should this type information be conveyed in Designer?

With SetVariable, JSON data for a JavaScript expression turns into a Newtonsoft.Json.Linq.JObject instance, which then causes a runtime error further down the workflow, as Newtonsoft.Json.Linq.JObject cannot be cast to our MyNamespace.MyModel.

We hacked a SetTypedVariable together, with an extra property field to set the type explicitly, together with some reflection code to get the JSON converted into the right type and that appears to do the job, but we were wondering whether this was the right thing to do.

What would be the proper Elsa way to do this, or is this a limitation of Designer?

**Comment by sfmskywalker** [comment]
I think you got it spot on. When setting a variable programmatically, the Variable object gets serialized including the type information. 

But when setting it from the designer using the `SetVariable` activity, there's currently no way to specify what type to associate with the object fields you're describing using JSON. What's missing is the ability to specify an actual type for the value, which should then also be used by the expression evaluator.

So what you did right now is a good workaround, but I'm wondering if you couldn't simply pass along the Type straight into the expression evaluator, and let it take care of parsing the JSON value into a typed object instance?

E.g.:

```csharp
// Code from SetVariable activity:
protected override async Task<ActivityExecutionResult> OnExecuteAsync(WorkflowExecutionContext workflowContext, CancellationToken cancellationToken)
{
    var value = await expressionEvaluator.EvaluateAsync(
        ValueExpression,
        Type, // Use the Type property configured on this SetVariable activity (if we were to add a Type property like you did in SetTypedVariable)
        workflowContext,
        cancellationToken
    );
    workflowContext.SetVariable(VariableName, value);
    return Done();
}
```

**Comment by sfmskywalker** [comment]
Basic work has been done to enable intellisense, but more work is required to further configure the designer / server with type information, available methods, etc.

This will be an ongoing effort, so I'm moving this issue out of the V2 milestone.

**Comment by sfmskywalker** [comment]
Type information is now largely available for activity input and output. to get type information about workflow variables, you can declare them from the Workflow Definition settings window by specifying the variable name and .NET type (assembly qualified).
