### ISSUE TITLE
Allow configuration of LogRecord storage at differents levels

### ISSUE THREAD

**Issue by jdevillard** [elsa-workflows/elsa-core#4799]
In the actual implementation, `LogRecords` are done using differents interfaces : 
- `IActivityExecutionStore` that store serialized information about activity I/O 
- `IWorkflowExecutionLogStore` that store serialize information about Workflow and ActivityContext. (maybe with redondant information regarding the `IActivityExecutionStore`

This can lead to data store that grow rapidly if you done some activity with large transformation (large input/ouput property which will be serialized).

The idea is to give the ability to the user to configure the storage strategy at different level : 
- At App Level -> store : true/false
- At Workflow Level -> store : default (inherit from App Level) / true (override) / false (override)
- At Activity Level -> store : default (inherit from Workflow Level) / true (override) / false (override)

For UI Component : 
- App Level : N/A  this is configured at Startup
- Workflow level : dropdown in the property tab of the Workflow
- Activity level : new tab for persistence information, with a list of the I/O property and a drop down list for each which allow choosing the strategy.

**Comment by jdevillard** [comment]
I think this issue can be closed ? 🧐

**Comment by sfmskywalker** [comment]
@jdevillard Yes, thank you for this awesome contribution! 🙌🏻
