### ISSUE TITLE
ELSA 3.0.3/Designer: cannot define input parameter on workflow called as activity, single-line not supported

### ISSUE THREAD

**Issue by JochenSteinbrenner** [elsa-workflows/elsa-core#4830]
Hello, I'm using `ELSA 3.0.3` in backend with
`image: elsaworkflows/elsa-studio-v3:latest`
as designer. At the moment, it is not possible to set input parameters
on workflows called as activity within the designer.

Same issue for `multi-line` inputs. I think, in backend `single-line` was changed to `singleline` but not within the designer.

ReproSteps:
I want to create a workflow with some imput parameters as single line inputs:
![image](https://github.com/elsa-workflows/elsa-core/assets/38906531/e6a373fb-586e-4cb0-80f8-830c035a9502)
![image](https://github.com/elsa-workflows/elsa-core/assets/38906531/c84f76b3-1e33-4aa9-955c-3b7064b01c23)
and allow calling it as activity:
![image](https://github.com/elsa-workflows/elsa-core/assets/38906531/7fb52199-ed49-434e-916d-ba9600236b3e)

When I call the workflow I cannot set the input parameters:
![image](https://github.com/elsa-workflows/elsa-core/assets/38906531/b77a4d7c-ccaf-457f-8df1-896f8fe97a80)

**Comment by sfmskywalker** [comment]
I think that we forgot to release the update to NuGet. I will look into it. Thanks for reporting 👍🏻

**Comment by sfmskywalker** [comment]
Should be good now with the latest packages (on NuGet - 3.0.4) and Docker images. However, your workflow's Input Definitions will have stored stale UI hints - to fix this, simply Edit an Input definition and then press save (do make sure that the desired UI Hint option is selected).

**Comment by JochenSteinbrenner** [comment]
Hello, I'am sorry, but with version 3.0.4 there is still the same behaviour.
I updated all backend Nugets to 3.0.4, the latest Elsa Studio Container was not updated.

If I create a new child workflow with to new inputs as single line and call it as activity in a new parent workflow I'm still getting this error:

![image](https://github.com/elsa-workflows/elsa-core/assets/38906531/a5b04fc9-5b61-487e-8385-57031a654bb5)

within MongoDb, the workflow is still persisted with the old `single-line` UIHint

`{
	"_id": "577afd3729bc2eaa",
	"CreatedAt": [
		638417947382524841,
		0
	],
	"Version": 2,
	"IsLatest": true,
	"IsPublished": true,
	"DefinitionId": "5a956061c3d1885",
	"Name": "Child",
	"ToolVersion": "3.0.0.0",
	"Options": {
		"UsableAsActivity": true,
		"AutoUpdateConsumingWorkflows": true
	},
	"Variables": [],
	"Inputs": [
		{
			"Type": "System.Object, System.Private.CoreLib",
			"Name": "Input1",
			"DisplayName": "Input 1",
			"Category": "Primitives",
			"UIHint": "single-line",
			"StorageDriverType": "Elsa.Workflows.Services.WorkflowStorageDriver, Elsa.Workflows.Core"
		},
		{
			"Type": "System.Object, System.Private.CoreLib",
			"Name": "Input2",
			"DisplayName": "Input 2",
			"Category": "Primitives",
			"UIHint": "single-line",
			"StorageDriverType": "Elsa.Workflows.Services.WorkflowStorageDriver, Elsa.Workflows.Core"
		}
	],
	"Outputs": [],
	"Outcomes": [],
	"CustomProperties": {},
	"MaterializerName": "Json",
	"StringData": "{\"type\":\"Elsa.Flowchart\",\"version\":1,\"id\":\"65467783766a7147\",\"nodeId\":\"Workflow1:65467783766a7147\",\"metadata\":{},\"customProperties\":{\"source\":\"FlowchartJsonConverter.cs:45\",\"notFoundConnections\":[],\"canStartWorkflow\":false,\"runAsynchronously\":false},\"activities\":[],\"connections\":[]}",
	"IsReadonly": false
}
`

Did I missed something? Thank you for your help!

**Comment by sfmskywalker** [comment]
Would it be possible to get a copy of your solution so I can investigate?

**Comment by JochenSteinbrenner** [comment]
Sorry, I must first check this with my boss tomorrow. Now, I can give you the relevant backend startup files. Maybe you can find something here. Thank you!

[Elsa.zip](https://github.com/elsa-workflows/elsa-core/files/14054593/Elsa.zip)

**Comment by JochenSteinbrenner** [comment]
Got it! I've not pulled the latest docker image of Elsa studio correctly. With the defined version. With the concrete version `elsaworkflows/elsa-studio-v3:sha-bc9d7b7 `it works! Sorry & thank you for your help!
