### ISSUE TITLE
Request to release the TransientState fix under 1.4.x version due to .NET5.0 migration challenges

### ISSUE THREAD

**Issue by jayachandra21** [elsa-workflows/elsa-core#484]
Hi,

As **TransientState** looks promising to use the variables data at runtime in workflow without persist the variables data, but we cannot migrate Elsa 1.5.0 due to change of NET 5.0.
Hence, requesting you to release the TransientState fix under 1.4.x version?

**Comment by sfmskywalker** [comment]
The issue with that is that I would now have to maintain 3 branches (Elsa 1.5, Elsa 1.4 and Elsa 2.0-preview). It's possible, but I'm afraid the additional maintenance overhead will slow down Elsa 2 development, which I would like to get up to par with Elsa 1 as soon as possible so that there is one version again that I can maintain & support.

But if someone is willing to help maintaining a 1.4.x branch, then I would be happy to assist of course.

**Comment by mohdali** [comment]
Hi @sfmskywalker,

I'm colleague of @jayachandra21 and first of all would like to thank you for the great effort you put into maintenance of Elsa workflow. It is really proving as a key element for our deliverables.

Regarding this point, our main concern is that .NET 5 is not an LTS release, while .NET 3.1 is LTS. And based on how dynamic the changes are happening to .NET nowadays, we would really prefer to wait till .NET 6 LTS is released to migrate our code. Second thing is that EF Core 5 has NET Standard 2.1 dependency, so it should be able to run on 3.1 runtime and doesn't require .NET 5 upgrade.

With the breaking change of 1.5 moving to NET 5 we will have to stick with 1.4.x branch for a while, we are happy to help maintaining the branch and pushing fixes as much as we can.

**Comment by sfmskywalker** [comment]
Hi @mohdali , that sounds wonderful, thank you. In that case, please feel free to start the 1.4.x branch and cherry-pick the things you would like to see there (such as the TransientState fix). I'll then setup a build pipeline to automatically deploy new 1.4.x packages (triggered when we tag a given commit on that branch).

**Comment by mohdali** [comment]
hi @sfmskywalker I created branch here https://github.com/mohdali/elsa-core/tree/feature/elsa-1.4

I kept it up to date with 1.5.0 release apart from the .NET 5 change.

Please let me know how to proceed further.

**Comment by mohdali** [comment]
hi @sfmskywalker, any update on this? we couldn't make a PR at the moment as the corresponding branch is not available in this repo.

**Comment by sfmskywalker** [comment]
@mohdali Sorry for the delay. I just created the `1.4.x` branch. Please go ahead and submit the PR against this branch. Thanks!

**Comment by sfmskywalker** [comment]
The 1.4.x branch was built & deployed to nuget as version `1.4.7.3`. This is an automatic CI/CD process, so anytime we push something to the 1.4.x branch & tag it with a version, it will kick off a new build & deployment to NuGet.
