### ISSUE TITLE
Remove method on the Variables class

### ISSUE THREAD

**Issue by jayachandra21** [elsa-workflows/elsa-core#485]
Hi,

Request to include a method to remove the variables on custom activities.
So that after use the workflow variables in runtime, variable data should not be persisted so it will improve the performance of a workflow instances to load.

**Comment by craigfowler** [comment]
@sfmskywalker my merged PR should close this.  I guess because it merged to a feature branch and not `master` it didn't auto-close.  I don't have project-wide close-issue permission though, so I can't do it manually.

**Comment by craigfowler** [comment]
Thanks @sfmskywalker - I am now indeed able to close tickets.

<EmperorPalpatineInfinitePower.gif> 😄
