### ISSUE TITLE
Deleted Workflow is Running in Backgroud

### ISSUE THREAD

**Issue by shijo-kg** [elsa-workflows/elsa-core#4852]
We created a workflow with timer activity with an interval of 1 minute, and somebody deleted the workflow. But still, workflow is running in every minute and unable to stop this execution. How to kill this workflow from execution? In workflow database there is no definition available of the specific workflow.
![1](https://github.com/elsa-workflows/elsa-core/assets/71206266/a3aa93e6-a3f3-4cce-8e6f-1f731a528c8f)
![2](https://github.com/elsa-workflows/elsa-core/assets/71206266/780eda8f-b888-4501-ab0e-f86c0e2cae8b)
![3](https://github.com/elsa-workflows/elsa-core/assets/71206266/b5336c79-b11a-49e0-9f75-4dbfbc88b5e3)

**Comment by sfmskywalker** [comment]
Unfortunately, I think that the only way for now, for Elsa 2, is to kill the application. We should consider this scenario for V3 as well, where we have a more thorough cancellation procedure that might be hooked into upon workflow definition deletion. 

Perhaps @raymonddenhaan, the contributor of the cancellation improvements, has some additional thoughts?

**Comment by raymonddenhaan** [comment]
Cancelling could work, but it will not in all cases. It will also only cancel the running instance, not the schedule itself.

I would propose to make an enhancement in which deletion of a workflow also implements an unpublish action. Preferably with a warning to the user if there is a instance running based on that definition.

**Comment by sfmskywalker** [comment]
This issue does not occur in Elsa 3, where it correctly handles the various deletion events to cleanup any associated triggers.
