### ISSUE TITLE
Elsa 3.0.4/Studio. Code completion not shown correctly

### ISSUE THREAD

**Issue by JochenSteinbrenner** [elsa-workflows/elsa-core#4858]
### Discussed in https://github.com/elsa-workflows/elsa-core/discussions/4840

<div type='discussions-op-text'>

<sup>Originally posted by **JochenSteinbrenner** January 26, 2024</sup>
Hello,
at the moment, the code completion within the ELSA studio of my project is not showing up any `FunctionDefinitions` (my own and Elsa internal function definitions). The `FunctionDefinitionProviders `in backend aren't called at all.
That means, the code completion comes up but does not show any methods like `get<VariableName>` etc.

I've started with Elsa 3 preview and the stencil designer. Everthing worked fine. 
At the moment, I use Elsa 3.0.4 in backend and the latest Elsa 3 studio docker container as designer.
After update to Elsa 3.0.4 and the blazor studio, the code completion does not work correctly. 
All other things seem to be good.

Is there anything special?
Anything to register within DI to get this running?
Any other ideas?

Many thanks!

regards Jochen Steinbrenner
</div>

Hello,
I have checked the behaviour within a new, plain server project built with:
https://v3.elsaworkflows.io/docs/installation/elsa-server
and a new, plain studio project build with:
https://v3.elsaworkflows.io/docs/installation/elsa-studio-blazorserver
I added only JavaScript support:
`    
    elsa.UseJavaScript(options =>
    {
        options.AllowClrAccess = true;
    });
`
[ElsaServer.zip](https://github.com/elsa-workflows/elsa-core/files/14121558/ElsaServer.zip)
[ElsaStudioBlazorServer.zip](https://github.com/elsa-workflows/elsa-core/files/14121559/ElsaStudioBlazorServer.zip)

The behaviour is the same as in my project. Code completion comes up, but does not show any functions or definitions.
Can you please investigate this? Code completion is very important for us. Many thanks! 

ReproSteps:
- Create new workflow
- Create variable (type: object, name: MyVar)
- Add SetVariable activity
- Select JavaScript for value property.
- getMyVar() not shown in code completion

**Comment by sfmskywalker** [comment]
Hi there, this is indeed a known current limitation that we have on the roadmap for completing (pun _not_ intended 😃 )

**Comment by sfmskywalker** [comment]
Here's the link to the corresponding issue: https://github.com/elsa-workflows/elsa-studio/issues/8

I will close this issue as duplicate. Thanks for reporting!
