### ISSUE TITLE
How to setup authentication using my custom identity server?

### ISSUE THREAD

**Issue by sfmskywalker** [elsa-workflows/elsa-core#4872]
I am using Elsa Server but I don't want to use the default identity provider. Instead, I want to use Auth0. Please guide me well.

**Comment by sfmskywalker** [comment]
Thank you.

**Comment by BostrongLonsec** [comment]
Unfortunately this does not seem to work with Elsa v3.

I am getting the below error when the line in startup.configure gets called:
app.UseEndpoints(epConfig => epConfig.MapWorkflowsApi());

Results in:
Inner Exception 1:
DependencyResolutionException: An exception was thrown while invoking the constructor 'Void .ctor(Elsa.Identity.Contracts.IRoleProvider, Elsa.Common.Contracts.ISystemClock, Microsoft.Extensions.Options.IOptions`1[Elsa.Identity.Options.IdentityTokenOptions])' on type 'DefaultAccessTokenIssuer'.

Inner Exception 2:
MissingConfigurationException: SigningKey is required

My add auth startup code (which is using azure ad but has worked with many other apps):

`var strAzureADAPIInstance = configStore.GetAzureAD_Instance;
var strAzureADMetadataAddress = $"{strAzureADAPIInstance}common/v2.0/.well-known/openid-configuration";
var strAzureADTenantId = configStore.GetAzureAD_TenantId;
var strAzureADAuthority = $"{strAzureADAPIInstance}{strAzureADTenantId}";
var strAzureADAPIClientId = configStore.GetAzureAD_API_ClientId;
var strAzureADIssuer = $"https://sts.windows.net/{strAzureADTenantId}/";

services.AddAuthentication(options =>
{
    options.DefaultAuthenticateScheme = JwtBearerDefaults.AuthenticationScheme;
    options.DefaultChallengeScheme = JwtBearerDefaults.AuthenticationScheme;
})
.AddJwtBearer(JwtBearerDefaults.AuthenticationScheme, jwtOptions =>
{
    jwtOptions.MetadataAddress = strAzureADMetadataAddress;
    jwtOptions.Authority = strAzureADAuthority;
    jwtOptions.Audience = strAzureADAPIClientId;
    jwtOptions.TokenValidationParameters = new TokenValidationParameters
    {
        ValidateIssuer = true,
        ValidateAudience = true,
        ValidateIssuerSigningKey = true,
        ValidAudiences = new string[] { strAzureADAPIClientId, $"api://{strAzureADAPIClientId}" },
        ValidIssuers = new string[] { strAzureADIssuer }
    };
});`


And finally, where i call AddElsa things ...
`            services.AddElsa(elsa =>
            {
                // Configure Management layer to use EF Core.
                elsa.UseWorkflowManagement(management => management.UseEntityFrameworkCore(config => config.UsePostgreSql(elsaConnectionString)));

                // Configure Runtime layer to use EF Core.
                elsa.UseWorkflowRuntime(runtime => {
                    runtime.UseEntityFrameworkCore(config => config.UsePostgreSql(elsaConnectionString));
                    //runtime.UseHangfireBackgroundActivityScheduler();
                    
                });


                // Default Identity features for authentication/authorization.
                //elsa.UseIdentity(identity =>
                //{

                //    identity.TokenOptions = options => options.SigningKey = "sxfMvrgjBvozhxPOLLggSw1W5RNk3rIs"; // This key needs to be at least 256 bits long.
                //    identity.UseAdminUserProvider();
                //});

                // Configure ASP.NET authentication/authorization.
                elsa.UseDefaultAuthentication();

                // Expose Elsa API endpoints.
                elsa.UseWorkflowsApi();`

**Comment by BostrongLonsec** [comment]
Just adding ... this error appears to be triggered by this line in the services.AddElsa call ...

// Configure ASP.NET authentication/authorization.
elsa.UseDefaultAuthentication();
