### ISSUE TITLE
Optimize WorkflowExecutionLog by Leveraging ActivityExecutionLog for ActivityState Retrieval

### ISSUE THREAD

**Issue by sfmskywalker** [elsa-workflows/elsa-core#4873]
Currently, the `WorkflowExecutionLogRecord` includes a copy of `ActivityState`, resulting in redundant data storage. This issue proposes a change to enhance data handling and storage efficiency. Instead of storing a copy of `ActivityState` directly within `WorkflowExecutionLogRecord`, the system should retrieve the `ActivityState` using the `ActivityInstanceId` from the `ActivityExecutionLog` store. The `ActivityExecutionLog` already maintains `ActivityState`, making this approach more resource-efficient and potentially improving the performance of the workflow execution logging process.

### Proposed Changes:
- Remove the storage of `ActivityState` copies in `WorkflowExecutionLogRecord`.
- Implement a mechanism to retrieve `ActivityState` from `ActivityExecutionLog` using `ActivityInstanceId`.

### Benefits:
- Reduces data redundancy and storage space usage.
- Potentially improves the performance and scalability of the logging system.
- Simplifies the data model by removing unnecessary duplication.

### Impact:
- This change requires modifications to how `WorkflowExecutionLogRecord` interacts with `ActivityState`.
- Existing data and logs need to be considered for migration or compatibility.

This enhancement seeks to optimize the logging process within Elsa Workflows, ensuring a more efficient and scalable system design.

**Comment by jdevillard** [comment]
Need to check with #4799 and latest discussion on community meeting. 

We have to ensure that filtering data that are logged in ActivityExecutionRecord doesn't impact workflow execution runtime and is fetch only for instance viewer post workflow execution. 
If not, initial work on #4799 could break the workflow or maybe I'm missing something .

**Comment by sfmskywalker** [comment]
I think it’s OK, since recorded state isn’t used functionally; it’s only used for historical data, which we still keep but using a different object; the Activity Execution Record.
