### ISSUE TITLE
MongoDB : already a serializer registered

### ISSUE THREAD

**Issue by bbenameur** [elsa-workflows/elsa-core#4885]
Hello,
There are a Bug with elsa when using mongoDb only on the integration Tests,
On the integration tests as you know the program class will be called many time using CustomWebApplicationFactory,
and on the AddElsa service registry will register the serializer 
```csharp
builder.Services.AddElsa(elsa =>
	elsa
		.UseMongoDb(orchestratorOptions.PersistanceConnectionString!)
......
``` 
With 2 or more integration test i have this error:

Message: 
MongoDB.Bson.BsonSerializationException : There is already a serializer registered for type Object.

  Arborescence des appels de procédure: 
BsonSerializerRegistry.RegisterSerializer(Type type, IBsonSerializer serializer)
BsonSerializer.RegisterSerializer(Type type, IBsonSerializer serializer)
MongoDbFeature.RegisterSerializers()
MongoDbFeature.Apply()
Module.Apply()
ModuleExtensions.AddElsa(IServiceCollection services, Action`1 configure)
ElsaExtensions.AddElsa(WebApplicationBuilder builder, IConfiguration configuration) ligne 39
Program.Main(String[] args) ligne 15

When i see the code i see that you register the serializer  on the RegisterSerializers() method

```csharp
 private static void RegisterSerializers()
 {
     BsonSerializer.RegisterSerializer(typeof(object), new PolymorphicSerializer());
     BsonSerializer.RegisterSerializer(typeof(Type), new TypeSerializer());
     BsonSerializer.RegisterSerializer(typeof(Variable), new VariableSerializer());
     BsonSerializer.RegisterSerializer(typeof(Version), new VersionSerializer());
     BsonSerializer.RegisterSerializer(typeof(JsonElement), new JsonElementSerializer());
 }
```

to fix this can you please user  BsonSerializer.TryRegisterSerializer(typeof(object), new PolymorphicSerializer());
..
Thanks

**Comment by sfmskywalker** [comment]
Closed via #4886
