### ISSUE TITLE
Disable workflow which has a start activity as Timer, which impacts other workflows to starts which has a Timer activity?

### ISSUE THREAD

**Issue by jayachandra21** [elsa-workflows/elsa-core#489]
Hi,

I have couple of workflows which has a start of activity as Timer.
So out of those workflows, one workflow got disabled.
So in this case all other workflow also stopped  triggering.
If enabled the workflow, all other workflow will start triggering.
![image](https://user-images.githubusercontent.com/67507118/101061570-a5fbe180-35b6-11eb-87f6-7c17bae16bcd.png)

**Comment by sfmskywalker** [comment]
This is fixed as of Elsa 2. If you want to provide a PR to fix this for Elsa 1, then that would be even better of course.
