### ISSUE TITLE
Payload Loss in Publish-Event and Event Activities in Event.cs

### ISSUE THREAD

**Issue by je-git-32** [elsa-workflows/elsa-core#4892]
I've noticed a problem with the Publish-Event and Event activities. The expected behavior is that you send an event with a specified payload and you receive the payload when listening to the event. However, if you send a payload, it seemingly gets lost. Upon examining the issue, I noticed in the Event.cs file on two occasions:

```c#

    /// <inheritdoc />
    protected override object GetTriggerPayload(TriggerIndexingContext context)
    {
        var eventName = EventName.Get(context.ExpressionExecutionContext);
        return new EventBookmarkPayload(eventName);
    }
```

and 

```c#
    /// <inheritdoc />
    protected override async ValueTask ExecuteAsync(ActivityExecutionContext context)
    {
        var eventName = context.Get(EventName)!;

        if (!context.IsTriggerOfWorkflow())
        {
            var options = new CreateBookmarkArgs
            {
                Payload = new EventBookmarkPayload(eventName),
                IncludeActivityInstanceId = false
            };
            context.CreateBookmark(options);
            return;
        }

        await context.CompleteActivityAsync();
    }
```

we instantiate an object of the class `EventBookmarkPayload` via the `eventName`, but when looking into the class

```c#
namespace Elsa.Workflows.Runtime.Bookmarks;

public class EventBookmarkPayload
{
    private readonly string _eventName = default!;

    public EventBookmarkPayload(string eventName)
    {
        EventName = eventName;
    }

    public string EventName
    {
        get => _eventName;
        init => _eventName = value.ToLowerInvariant();
    }
}

```

there is no visible trace of the payload that was sent by the publisher.
I am currently using the latest version (3.0.5).

**Comment by je-git-32** [comment]
In the process of transmitting supplementary data with the event name, I incorporate this data into the Input property. Subsequently, the receiving activity is expected to retrieve this input data from its execution context. However, this functionality does not seem to be operating as anticipated, suggesting the presence of a bug. Could you kindly investigate this issue?

**Comment by dehlers1000** [comment]
I have been unable to pass and receive a payload also with the publish event. It appears to be a bug. Not able to work around this issue.

**Comment by sfmskywalker** [comment]
I can confirm the issue. Looking into it.
