### ISSUE TITLE
Masstransit direct exchanges

### ISSUE THREAD

**Issue by rezabashiri** [elsa-workflows/elsa-core#495]
I'm wondering if direct exchanges could be used or not ?

It seems control over masstranssit activities are a little bit limited , i mean how to format message or change exchange names?

**Comment by sfmskywalker** [comment]
If you can do it with MassTransit, there's no reason you couldn't do it from Elsa, except of course if Elsa is currently hiding something from MassTransit that you need access to. In which case I'm sure we can open it up.
