### ISSUE TITLE
Error when opening the workflow instance view (Dapper + TSQL)

### ISSUE THREAD

**Issue by vladc-3sd** [elsa-workflows/elsa-core#4953]
I have a Microsoft SQL Database and I'm using Dapper. When opening the workflow instance view page I'm getting the following error:

An unhandled exception has occurred while executing the request.

> System.InvalidCastException: Unable to cast object of type 'System.Text.Json.Nodes.JsonArray' to type 'System.Text.Json.Nodes.JsonObject'.
>    at Elsa.Workflows.Serialization.Converters.PolymorphicObjectConverter.Read(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options)
>    at System.Text.Json.Serialization.JsonConverter`1.TryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value, Boolean& isPopulatedValue)
>    at System.Text.Json.Serialization.JsonDictionaryConverter`3.OnTryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, TDictionary& value)
>    at System.Text.Json.Serialization.JsonConverter`1.TryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value, Boolean& isPopulatedValue)
>    at System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
>    at System.Text.Json.JsonSerializer.ReadFromSpan[TValue](ReadOnlySpan`1 utf8Json, JsonTypeInfo`1 jsonTypeInfo, Nullable`1 actualByteCount)
>    at System.Text.Json.JsonSerializer.ReadFromSpan[TValue](ReadOnlySpan`1 json, JsonTypeInfo`1 jsonTypeInfo)
>    at System.Text.Json.JsonSerializer.Deserialize[TValue](String json, JsonSerializerOptions options)
>    at Elsa.Workflows.Serialization.Serializers.JsonPayloadSerializer.Deserialize[T](String payload)
>    at Elsa.Dapper.Modules.Runtime.Stores.DapperWorkflowExecutionLogStore.Map(WorkflowExecutionLogRecordRecord source)
>    at System.Linq.Enumerable.SelectListIterator`2.Fill(ReadOnlySpan`1 source, Span`1 destination, Func`2 func)
>    at System.Linq.Enumerable.SelectListIterator`2.ToList()
>    at Elsa.Dapper.Modules.Runtime.Stores.DapperWorkflowExecutionLogStore.Map(Page`1 source)
>    at Elsa.Dapper.Modules.Runtime.Stores.DapperWorkflowExecutionLogStore.FindManyAsync[TOrderBy](WorkflowExecutionLogRecordFilter filter, PageArgs pageArgs, WorkflowExecutionLogRecordOrder`1 order, CancellationToken cancellationToken)
>    at Elsa.Workflows.Api.Endpoints.WorkflowInstances.Journal.FilteredList.Get.ExecuteAsync(Request request, CancellationToken cancellationToken)
>    at FastEndpoints.Endpoint`2.ExecAsync(CancellationToken ct)
>    at FastEndpoints.Endpoint`2.ExecAsync(CancellationToken ct)
>    at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
>    at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
>    at NSwag.AspNetCore.Middlewares.SwaggerUiIndexMiddleware.Invoke(HttpContext context)
>    at NSwag.AspNetCore.Middlewares.RedirectToIndexMiddleware.Invoke(HttpContext context)
>    at NSwag.AspNetCore.Middlewares.OpenApiDocumentMiddleware.Invoke(HttpContext context)
>    at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
>    at Elsa.Http.Middleware.WorkflowsMiddleware.InvokeAsync(HttpContext httpContext)
>    at Program.<>c.<<<Main>$>b__0_4>d.MoveNext() in D:\repos\ElsaApp\ElsaApp.API\Program.cs:line 201
> --- End of stack trace from previous location ---
>    at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddlewareImpl.Invoke(HttpContext context)

This is the configuration for Elsa in Program.cs (the custom SqlServerDatabaseProvider is only needed to get the connection string from the ITSQLSettings implementation)

```c#
var elsaConfiguration = builder.Configuration.GetSection("Elsa");
builder.Services.AddElsa(elsa =>
{
    elsa
        .UseDapper(config =>
        {
            SqlMapper.ResetTypeHandlers();
            config.DbConnectionProvider = sp =>
            {
                return new SqlServerDatabaseProvider(sp.GetRequiredService<ITSQLSettings>());
            };
            config.UseMigrations(feature =>
            {
                feature
                    .AddSqlServer()
                    .WithMigrationsIn(typeof(Elsa.Dapper.Migrations.Management.Initial).Assembly);
            });
            config.Apply();
        })
        .UseWorkflowManagement(config =>
        {
            config.UseDapper();
        })
        .UseWorkflowRuntime(config =>
        {
            config.UseDapper();
        })
        .UseFluentStorageProvider(config => FluentStorage.StorageFactory.Blobs.InMemory())
        .UseWorkflowsApi(api => api.AddFastEndpointsAssembly<Program>())
        .UseIdentity(identity =>
        {
            identity.UseDapper();
        })
        .UseDefaultAuthentication()
        .UseHttp(http =>
        {
            http.ConfigureHttpOptions = options => elsaConfiguration.GetSection("Http").Bind(options);
        })
        .UseCSharp()
        .UseJavaScript(options =>
        {
            options.AllowClrAccess = true;
        })
        .UseLiquid(liquid => liquid.FluidOptions = options => options.Encoder = HtmlEncoder.Default)
        .AddSwagger()
        .AddFastEndpointsAssembly<Program>();
});
```

Am I doing something wrong?

**Comment by vladc-3sd** [comment]
I am using the last stable version of every Elsa NuGet package: 3.0.5

**Comment by sfmskywalker** [comment]
I just tried with the latest version (from source code), and I wasn't even able to create a workflow due to some bugs in the Dapper provider. I went ahead and fixed all that, after which I was able to successfully create and execute a workflow and open the instance viewer.

If you want, you can try and see if it also fixes your issue by updating your Elsa package references to version `3.1.0-dapper-provider.1131` available from the Feedz feed.

**Comment by sfmskywalker** [comment]
Great! then I will go ahead and close this issue. Thanks for having taken the time to report it!
