### ISSUE TITLE
Feature-Request: Elsa 2.0 - Separate Yessql from Elsa.Abstractions and Elsa.Core

### ISSUE THREAD

**Issue by Rafael94** [elsa-workflows/elsa-core#496]
Hello,

i would like to see Yessql removed from Elsa.Abstractions and Elsa.Core and outsourced in a separate project. I want to avoid unnecessary dependencies in my project. So every developer could use his own database library.

I can create a pull-request for this. 

# I would change the following: #

## Rename: ##
IWorkflowDefinitionManager -> IWorkflowDefinitionRepository
IWorkflowInstanceManager -> IWorkflowInstanceRepository

## New projects: ##
- Elsa.Data.InMemory
- Elsa.Data.MongoDb
- Elsa.Data.Yessql

Translated with www.DeepL.com/Translator

**Comment by sfmskywalker** [comment]
I agree. In fact, I have it on the [Elsa Ideas list](https://github.com/elsa-workflows/elsa-core/discussions/468). I linked that item to this issue.

**Comment by Rafael94** [comment]
I must have missed that point. I try to create a Pull Request during the day.

**Comment by sfmskywalker** [comment]
Fixed as of 3b35d9f.

Thanks @Rafael94 for this wonderful contribution.
