### ISSUE TITLE
Elasticsearch store does not work with workflow instances

### ISSUE THREAD

**Issue by ayalros** [elsa-workflows/elsa-core#4963]
Hi there,

While using the elastic store and the studio, loading workflow instances resultes in an error.
Maybe i'm missing something but, while debugging i found several issues creating the query:
1) the query section gets initiated with a null value resulting in a bad query. (https://github.com/elsa-workflows/elsa-core/blob/c80f80fd81cbea43d9b90256ee37c56c12294c43/src/modules/Elsa.Elasticsearch/Modules/Management/WorkflowInstanceStore.cs#L135)
2) while in the fields section the field "createdAt" is written correctly, in the order by section its beeing written not in camel case form (e,g. "CreatedAt"). (https://github.com/elsa-workflows/elsa-core/blob/c80f80fd81cbea43d9b90256ee37c56c12294c43/src/modules/Elsa.Elasticsearch/Modules/Management/WorkflowInstanceStore.cs#L105)

Reagrds,

**Comment by sfmskywalker** [comment]
Thanks for reporting the issue, and the PR! 🙏🏻
