### ISSUE TITLE
How to configure SQL Server for Elsa 3 ?

### ISSUE THREAD

**Issue by gopi-codingo** [elsa-workflows/elsa-core#4972]
I'm am setting up a .net core project to use elsa 3.0 with sql server as the storage option. But there are no materials on how to configure elsa to use sql server. It would be very helpful to know how!

**Comment by lanfaboy** [comment]
There is no UseEntityFrameworkPersistence extension method？

> 若要将 Elsa 3.0 配置为使用 SQL Server 进行持久性，需要使用相应的数据库提供程序设置 Entity Framework Core。根据提供的上下文，以下是您应该遵循的步骤：
> 
> 1. 确保已为 Elsa 3.0 和 Entity Framework Core 安装了必要的 NuGet 包，并支持 SQL Server。您至少需要以下软件包：
>    
>    * `Elsa`
>    * `Elsa.Persistence.EntityFramework.Core`
>    * `Elsa.Persistence.EntityFramework.SqlServer`
>    * `Microsoft.EntityFrameworkCore.SqlServer`
> 2. 在 OR 文件中（取决于项目设置），需要将服务配置为将 Entity Framework Core 与 SQL Server 配合使用。下面是如何执行此操作的示例：`Program.cs``Startup.cs`
> 
> ```cs
> using Elsa.Persistence.EntityFramework.Core.Extensions;
> using Microsoft.EntityFrameworkCore;
> 
> var builder = WebApplication.CreateBuilder(args);
> 
> // Configure Elsa to use Entity Framework Core with SQL Server
> builder.Services.AddElsa(elsa => elsa
>     .UseEntityFrameworkPersistence(ef => ef.UseSqlServer(builder.Configuration.GetConnectionString("YourConnectionStringName")))
>     // Add other Elsa services as needed
> );
> 
> // Build the application
> var app = builder.Build();
> 
> // ... other configurations ...
> 
> app.Run();
> ```
> 
> 请确保替换为在配置源或其他配置源中定义的连接字符串的名称。`"YourConnectionStringName"``appsettings.json`
> 
> 3. 您需要创建迁移并更新数据库，以便为 Elsa 创建必要的表。可以使用 Entity Framework Core 工具执行此操作。在包管理器控制台或终端中运行以下命令：
> 
> ```shell
> dotnet ef migrations add InitialCreate -c ElsaContext
> dotnet ef database update -c ElsaContext
> ```
> 
> 这将生成初始迁移脚本并将其应用于 SQL Server 数据库，从而为 Elsa 创建所需的架构。
> 
> 4. 确保在您的或其他配置源中正确配置了连接字符串，以指向您的 SQL Server 实例。`appsettings.json`
> 5. 如果遇到多个 DbContext 的任何问题，请确保在运行迁移或更新数据库时指定正确的上下文。
> 
> 请记住查看官方 Elsa 文档和 GitHub 存储库，了解设置过程的任何更新或更改，因为此处提供的信息基于截至知识截止日期的可用上下文。

**Comment by Anisxh** [comment]
Just pitching in here, the bot is sometimes answering using Elsa 2 examples and documentation. This is how I did it for Postgres, maybe this helps you do the same for whichever other db you need. I'm sure most of this information will become more easily available as the documentation gets built up gradually.

```
using Elsa.EntityFrameworkCore.Extensions;
using Elsa.EntityFrameworkCore.Common;
using Elsa.EntityFrameworkCore.Modules.Labels;
using Elsa.EntityFrameworkCore.Modules.Management;
using Elsa.EntityFrameworkCore.Modules.Runtime;

WebApplicationBuilder builder = WebApplication.CreateBuilder(args);
builder.Services.AddControllers();
builder.Services.AddElsa(elsa =>
{
    var dbContextOptions = new ElsaDbContextOptions();
    dbContextOptions.MigrationsAssemblyName = typeof(Program).Assembly.GetName().Name;

    elsa.UseWorkflowManagement(management => management.UseEntityFrameworkCore(ef => ef.UsePostgreSql(connectionString, dbContextOptions)));
    elsa.UseWorkflowRuntime(runtime => runtime.UseEntityFrameworkCore(ef => ef.UsePostgreSql(connectionString, dbContextOptions)));
});
```
Hope this helps
