### ISSUE TITLE
WorkflowException does not carry the innerException that would explain why it is being raised

### ISSUE THREAD

**Issue by PeterLaComb-Availity** [elsa-workflows/elsa-core#498]
In Elsa.Abstractions.Exceptions, the WorkflowException class does not have the construct that would allow the innerException to be passed in. This makes it difficult to debug within Elsa when an expression evaluation fails.

In my case, I am evaluating a Javascript expression in a unit test - when I run it by the JavascriptExpressionEvaluator, it evaluates correctly. When I run it through the context (as you would normally in an activity) it throws an exception. While it's highly likely that I have constructed my WorkflowExecutionContext incorrectly, the details of what is going wrong are obscured. Because the fix for this is straightforward, a PR will follow.

**Comment by sfmskywalker** [comment]
Fixed in 99aeac32637dd71c85fe29c3d97f720ae2b9b14f

Thanks!
