### ISSUE TITLE
How to suspend a workflow if  there is an exception thrown and then  suspend the workflow, and then reume it with or without retry(by my choice) the previous failed activity?

### ISSUE THREAD

**Issue by AngrySKL** [elsa-workflows/elsa-core#4992]
My scenario is that I have a long running worklfow with a lot of customized activities, some of the activities might throw exception when executing ( expected or unexpected ). And after the exception, I just want to suspend the workflow and then wait for the user to manually resume by clicking a "Resume" button. 

There are two kinds of suspension, one can be retried after resume and one cannot which means if the user click "Resume", if the activity caused the suspension can be retried then resume will retry the previous setp first and then going forward. If the activity can not be retried the resume will directly going forward.

I looked into the code of FaultStrategy, and maybe I can write a SuspensionStrastegy? But I don't see how to resume it...

**Comment by AngrySKL** [comment]
> To implement the behavior you're describing, you would indeed need to create a custom incident strategy that suspends the workflow instead of faulting it when an exception occurs. This strategy would be similar to the `FaultStrategy`, but instead of marking the workflow as faulted, it would suspend the workflow and potentially record some data that allows the user to resume the workflow later.
> 
> Here's a high-level approach to how you might implement this:
> 
> 1. **Create a Custom Incident Strategy**: Implement an `IIncidentStrategy` that suspends the workflow. You can store information about the suspension in the workflow instance's data or as a custom entity in your database.
> 2. **Handling Suspension**: When an activity throws an exception, your custom incident strategy would be invoked, and you would handle the suspension logic there. You might want to add a flag or some metadata to indicate whether the activity can be retried or not.
> 3. **User Interface for Resuming**: In your application, you would provide a user interface that lists suspended workflows and allows users to click a "Resume" button.
> 4. **Resuming the Workflow**: When the user clicks "Resume", you would call the appropriate method to resume the workflow. If the activity can be retried, you would need to ensure that the workflow execution context is set up to retry the activity. If not, you would resume the workflow from the next activity.
> 5. **Implementing Resume Logic**: You might need to implement custom logic in your activities to handle the resume operation. This could involve overriding the `OnResumeAsync` method in your custom activities and adding logic to determine whether to retry the previous step or move forward.
> 6. **Workflow Instance Management**: Ensure that your workflow instances are persisted correctly and that you can query for suspended workflows. You might need to interact with the workflow instance store for this.
> 7. **Testing**: Thoroughly test your custom strategy and resume logic to ensure that workflows are suspended and resumed correctly, and that retryable activities are handled as expected.
> 
> Here's a pseudo-code example of what the custom incident strategy might look like:
> 
> ```cs
> public class SuspendStrategy : IIncidentStrategy
> {
>     public void HandleIncident(ActivityExecutionContext context)
>     {
>         // Logic to suspend the workflow
>         // You might want to add custom data to the workflow instance here
>         // to indicate that it's suspended and whether it can be retried
>     }
> }
> ```
> 
> And to resume a workflow, you might have something like this:
> 
> ```cs
> public async Task ResumeWorkflow(Guid workflowInstanceId, bool retry)
> {
>     var workflowInstance = await _workflowInstanceStore.GetByIdAsync(workflowInstanceId);
>     if (workflowInstance == null)
>         throw new InvalidOperationException("Workflow instance not found.");
> 
>     // Check if the workflow instance has the custom 'suspended' data
>     // and whether the activity that caused the suspension can be retried
> 
>     if (retry)
>     {
>         // Logic to retry the activity
>     }
>     else
>     {
>         // Logic to move forward without retrying
>     }
> 
>     // Resume the workflow
>     await _workflowRunner.RunAsync(workflowInstance);
> }
> ```
> 
> Remember to register your custom incident strategy with the DI container and configure it in your workflow options.
> 
> Please note that the actual implementation will depend on the specifics of your workflow and activities, and you may need to adjust the approach based on your requirements and the behavior of the Elsa Workflow engine.

Can you show me how to retry the activity?

**Comment by sfmskywalker** [comment]
To retry a workflow instance that has not yet finished, but e.g. running with incidents (as in your case), you can use the [Alterations API](https://v3.elsaworkflows.io/docs/alterations/introduction) and specify the `ScheduleActivity` alteration. The documentation offers a sample request.
