### ISSUE TITLE
how to pass input to workflow and activity while executing the workflow

### ISSUE THREAD

**Issue by saisworld** [elsa-workflows/elsa-core#5081]
In version V3, I have a simple custom Activity, its expecting an input parameter from the workFlow or directly passed to the Activity. But when I send a httpRequest via Postman and include the body with { "taskType" : "Task"   } , Workflow instance is not able to recognize the input parameter. How to send parameters to the workflow ?

```
 public class CustomTask : CodeActivity<string>
 {
     [Input(
     Description = "The task type to that you want to.",
     UIHint = InputUIHints.DropDown,
     UIHandlers = [typeof(TaskTypeUIHandler), typeof(RefreshUIHandler)])]
     public Input<string> TaskType { get; set; }
     protected override ValueTask ExecuteAsync(ActivityExecutionContext context)
     {
         Console.WriteLine($"Hello, {context.GetWorkflowInput<TaskTypes>("TaskType")}!");
         Console.WriteLine($"Hello, {TaskType.Get(context)}!");
         var message = $"task type is :{TaskType.Get(context)}";
         context.SetResult(message);
         return base.ExecuteAsync(context);
     }

 }
```

In the Workflow, I have set the Input parameter like this - 

![image](https://github.com/elsa-workflows/elsa-core/assets/5602414/f111a33c-57af-4516-b900-8f1be20925ab)

**Comment by saisworld** [comment]
I didn't use Http Endpoint Activity, I followed the example given in this link - https://v3.elsaworkflows.io/docs/extensibility/custom-activities#create-the-application 

In the above example, there was no mention of HTTP endpoint activity, it said workflow could be triggered directly using the workflow definitionId via curl request. So, do I need to create HttpEndpoint Activity for that to work?

**Comment by saisworld** [comment]
Thank you , it worked now.

So do I need to create an Input parameter at the Workflow level  and then use that to send it to individual Activities? Or somehow it can directly map the input from the body to the starting activity input parameters?

**Comment by pramsperger** [comment]
From the designer, you can use a JavaScript expression to feed workflow input into an activity's input:
```javascript
getInput("TaskType")
```
