### ISSUE TITLE
Resume bookmark with payload

### ISSUE THREAD

**Issue by popescumadalin0** [elsa-workflows/elsa-core#5090]
Hello. I am Madalin, a beginner elsa user. Based on the discussion from Discord, I created this issue!
[The project](https://github.com/popescumadalin0/elsa-issue) with the issue.
I encountered a situation where I wanted to resume using the bookmark method, and I wanted to send a payload with the resuming.
![image](https://github.com/elsa-workflows/elsa-studio/assets/89019128/bc5d56e5-969f-4897-a9ca-4f2d052fc787)
This is my workflow. My custom activity just creates a bookmark and waits for it. At the resume step, it waits an input and sets it as the ActivityOutput.
![image](https://github.com/elsa-workflows/elsa-studio/assets/89019128/f27394d3-1041-4814-8aec-1e96164b378f)
For resuming the activity, we are using Postman to trigger a controller that sends an inbox message to the activity:
![image](https://github.com/elsa-workflows/elsa-studio/assets/89019128/2df4ba33-d143-4957-9550-11225a540398)
The input is sent to the activity using the NewWorkflowInboxMessage model:
![image](https://github.com/elsa-workflows/elsa-studio/assets/89019128/05c6fa63-1865-448f-b814-6bd1abf5558f)
In debugging, we can see that the workflow instance input is override at each resume:
![image](https://github.com/elsa-workflows/elsa-studio/assets/89019128/17aec1c4-81af-496b-b583-5b9ded82890f)
![image](https://github.com/elsa-workflows/elsa-studio/assets/89019128/a9f8e072-8d9f-49c3-9e8f-745f15a8a5d7)
![image](https://github.com/elsa-workflows/elsa-studio/assets/89019128/6301ae43-995a-46b5-a444-cf1006c9affb)
![image](https://github.com/elsa-workflows/elsa-studio/assets/89019128/6f14695a-f246-471f-9549-0354768e240d)
At this step the first activity (BookmarkActivity1) should have the result = our first payload with the property Stuff='first'
For the second activity:
![image](https://github.com/elsa-workflows/elsa-studio/assets/89019128/4c1184c7-11fe-441a-9611-3d18cfd453f8)
![image](https://github.com/elsa-workflows/elsa-studio/assets/89019128/fd05721f-a8f4-4b1f-882f-ca56f10678b2)
![image](https://github.com/elsa-workflows/elsa-studio/assets/89019128/0902447e-8256-43e8-aef8-773a632af127)
**Now you can see that the workflow input was override with the new payload.** For our second activity. 
**This is one of the problem**
The next problem is that for our previous activity the output is forgot.
![image](https://github.com/elsa-workflows/elsa-studio/assets/89019128/54b8bae4-d3bc-49e8-b546-88e0b704409f)
![image](https://github.com/elsa-workflows/elsa-studio/assets/89019128/707de5aa-05e5-411f-bd13-70be59be7aaf)
![image](https://github.com/elsa-workflows/elsa-studio/assets/89019128/99f9afc3-91c6-4b51-9988-415a777b1298)

If we are looking in our designer:
The first activity have empty result: 
![image](https://github.com/elsa-workflows/elsa-studio/assets/89019128/74ce00df-5f65-435d-81fa-756db84ad1a4)
The same for second one: 
![image](https://github.com/elsa-workflows/elsa-studio/assets/89019128/95d5f52f-6fd2-43d1-b1e7-bede7c688b7e)
And the last one has the correct result:
![image](https://github.com/elsa-workflows/elsa-studio/assets/89019128/07b8c713-9267-4f60-a4bf-49b445f5c804)
But our WriteLine activity that had to display the BookMarkActivity1 result, displayed nothing:
![image](https://github.com/elsa-workflows/elsa-studio/assets/89019128/4821a8a9-2f5c-48bb-975d-29e3bd00ee92)
**So the Result is lost.**

The workflow is in the code, in the above repository.
The postman payload:
```
{
  "workflowIdentifier": "7054e6d4451684e9-61d339ffea8114bd",
  "isSuccess": true,
  "errorMessage": "",
  "stuff": "third"
}
```

The workflow identifier is {activity instance id}-{workflow instance id}

**Comment by zer0bugz** [comment]
Bumping this, I'm seeing the same behavior with the output of resumed activities!
I'm adding some extra details as I've managed to reproduce it using a simple workflow composed of two HTTP Endpoint activities:
a1 - listening on `http://localhost/workflows/a1` 
a2 - listening on `http://localhost/workflows/a2`
Steps:
1. Calling `/a1` resumes the `a1` activity and checking the workflow instance, I see the `Output.Headers` on `a1` shows a bunch of data that was sent by the browser.
2. Calling `/a2` resumes the `a2` activity; a2 Output.Headers shows the expected data, *but when I'm checking the a1 Output.Headers these show up empty!*

I'll leave the workflow definition that I tested with here as a reference:
[resumable-activities.json](https://github.com/elsa-workflows/elsa-core/files/14672732/resumable-activities.json)

**Comment by zer0bugz** [comment]
Update: I've replaced the packages with the Elsa sourcecode from latest (rev: d11754324e3d86f2eeb81682ce2c391fd5853f75) and the output is stored as expected.
So I guess we need to wait for the 3.0.7 release - @sfmskywalker any hints on when this is going to be? xD

Attaching a relevant gif to prove that it works:
![activity-resume-with-output-persistence](https://github.com/elsa-workflows/elsa-core/assets/1118552/14d86499-f134-4fe5-96ce-4af22f606f83)

**Comment by sfmskywalker** [comment]
@zer0bugz @popescumadalin0 Would it be possible for you to try wit the latest 3.1.2 release?

**Comment by zer0bugz** [comment]
@sfmskywalker Yes! I just tested and it works fine with 3.1.2!
Thank you for this! ^_^

**Comment by popescumadalin0** [comment]
Thanks all for the implication
I'll close the issue

**Comment by sfmskywalker** [comment]
Awesome. Thanks for confirming!
