### ISSUE TITLE
Cann't find System.ComponentModel.Annotations(>= 6.0.0-preview.4.21253.7) in nuget

### ISSUE THREAD

**Issue by zk880418** [elsa-workflows/elsa-core#5098]
Elsa.Workflows.Core  dependencies on System.ComponentModel.Annotations(>= 6.0.0-preview.4.21253.7),but in [nuget](https://www.nuget.org/packages/System.ComponentModel.Annotations/) we cann't find it,the current version is 5.0.0.
So,how to fix it?

**Comment by thompson-tomo** [comment]
For me a release package of elsa should not be using preview packages of third parties and hence this dependency should be switched to a release package.

**Comment by sfmskywalker** [comment]
I think it's been removed 👍🏻
