### ISSUE TITLE
PlainTextHttpContentParser doesn't handle application/xml and text/xml or text/html content

### ISSUE THREAD

**Issue by jdevillard** [elsa-workflows/elsa-core#5115]
This parser is looking for `text/plain` content-type so it cannot handle : 

- text/html
- application/xml
- text/xml

the last two can be handle by the `XmlHttpContentParser` if target type is `string` so maybe there is not need to handle those ones in the `PlainTextHttpContentParser`.

**Comment by raymonddenhaan** [comment]
I think the text/html content-type would need its own Html parser as well.

**Comment by sfmskywalker** [comment]
@jdevillard I forget, was there a PR for this?

**Comment by jdevillard** [comment]
No sorry I missed it , and have difficulty to find the right name for the class 🤣🤣🤣🤣

**Comment by sfmskywalker** [comment]
Ah I get it. Naming is hard!! 😄

**Comment by sfmskywalker** [comment]
Thanks @jdevillard !
