### ISSUE TITLE
I config the specific implementation of IActivityExecutionMiddleware in Program.cs,but have a Exception.

### ISSUE THREAD

**Issue by coolshun** [elsa-workflows/elsa-core#5118]
I config the specific implementation of IActivityExecutionMiddleware in Program.cs,but throw a Exception.the code and Exception bellow.
`
  public class TestActivityMiddleware : IActivityExecutionMiddleware
  {
      private readonly ActivityMiddlewareDelegate _next;

      /// <summary>
      /// Constructor
      /// </summary>
      public TestActivityMiddleware(ActivityMiddlewareDelegate next)
      {
          _next = next;
      }

      /// <inheritdoc />
      public async ValueTask InvokeAsync(ActivityExecutionContext context)
      {
          Console.WriteLine($"============================Before Activity Execution: Id:{context.Id}  NodeId:{context.NodeId} Status:{context.Status} Activity.Id:{context.Activity.Id}   Activity.Name:{context.Activity.Name}");
          // Invoke next middleware.
          await _next(context);
          Console.WriteLine($"=============================After Activity Execution: Id:{context.Id}  NodeId:{context.NodeId} Status:{context.Status} Activity.Id:{context.Activity.Id}   Activity.Name:{context.Activity.Name}");
      }

  }

//Program.cs
//this throw a Exception
var builder = WebApplication.CreateBuilder(args);
builder.Services.AddScoped<IActivityExecutionMiddleware, TestActivityMiddleware>();

//Exception:
System.AggregateException:“Some services are not able to be constructed (Error while validating the service descriptor 'ServiceType: Elsa.Workflows.Contracts.IActivityExecutionMiddleware Lifetime: Scoped ImplementationType: ElsaServer.Middleware.TestActivityMiddleware': Unable to resolve service for type 'Elsa.Workflows.Pipelines.ActivityExecution.ActivityMiddlewareDelegate' while attempting to activate 'ElsaServer.Middleware.TestActivityMiddleware'.)”
`

**Comment by sfmskywalker** [comment]
Answered by bot.
