### ISSUE TITLE
An error in "Elsa.Workflows.Runtime.RunTask.cs"

### ISSUE THREAD

**Issue by joysplit** [elsa-workflows/elsa-core#5139]
When running this code：
var dispatcher = context.GetRequiredService<ITaskDispatcher>();

Will cause the following errors：
System.InvalidOperationException:“Cannot resolve scoped service 'Elsa.Workflows.Runtime.Services.BackgroundTaskDispatcher' from root provider.”

By running the example program：
![image](https://github.com/elsa-workflows/elsa-core/assets/50003056/6540cf23-57ac-4e25-880d-e48f97fa65e8)

**Comment by joysplit** [comment]
Should we solve it this way ？
![image](https://github.com/elsa-workflows/elsa-core/assets/50003056/fb17963c-e9a3-46f5-95c9-06ea370621b6)

**Comment by sfmskywalker** [comment]
Hi @joysplit , 

That's exactly right, as well as the change in commit b7074e45d245ebe3b6d25e10c8aee7c19febdc4c.

Thank you for reporting!
