### ISSUE TITLE
[Perf] JsonSerializationOption instances should be reused

### ISSUE THREAD

**Issue by sebastienros** [elsa-workflows/elsa-core#5144]
Once customized then should be made available as static instances or singleton instances in DI registered with a wrapper type. It's critical for perf as they have a lock internally.

https://github.com/elsa-workflows/elsa-core/blob/main/src/clients/Elsa.Api.Client/Extensions/JsonObjectExtensions.cs#L59-L62

**Comment by sfmskywalker** [comment]
I had no idea of the impact - thank you 😃
