### ISSUE TITLE
Elsa3.1.0 package dependency

### ISSUE THREAD

**Issue by daconglee** [elsa-workflows/elsa-core#5163]
I use PostgreSql ，why dependency MySqlConnector package. restult in not compile. 

ps:I not internet，net6.0

**Comment by Suchiman** [comment]
Duplicate of #5158

**Comment by Suchiman** [comment]
Should be resolved as of version 3.1.2 @daconglee

**Comment by sfmskywalker** [comment]
As per @Suchiman 's remark, this is now fixed. Thanks for reporting @daconglee , and many thanks @Suchiman for the fix 👍🏻
