### ISSUE TITLE
Alteration Document Error

### ISSUE THREAD

**Issue by iio888** [elsa-workflows/elsa-core#5170]
I want to know how to create an alteration plan. 
Following the documents, chapter “Alteration Plans”, I found that there is no `NewAlterationPlan` any more in Elsa 3.1.1.

**Comment by sfmskywalker** [comment]
Hi @iio888 , thanks for reaching out. We do need to update the documentation.

Until then, here's a sample JSON payload that shows the new structure:

```json
{
    "alterations": [
        {
            "type": "Migrate",
            "targetVersion": 9
        },
        {
            "type": "ScheduleActivity",
            "activityId": "ccf52939c64d66d"
        }
    ],
    "filter": {
        "workflowInstanceIds": [
            "9e10ae74f99fe60a"
        ]
    }
}
```

The new class is called [AlterationPlanParams](https://github.com/elsa-workflows/elsa-core/blob/main/src/modules/Elsa.Alterations.Core/Models/AlterationPlanParams.cs).

**Comment by iio888** [comment]
Okay. I will check it. 
Thanks for your reply!
