### ISSUE TITLE
AzureServiceBus : Elsa.AzureServiceBus.HostedServices.StartWorkers need scoped services

### ISSUE THREAD

**Issue by jdevillard** [elsa-workflows/elsa-core#5178]
Due to recent changes regarding the development of the multi-tenancy, 

the `Elsa.AzureServiceBus.HostedServices.StartWorkers` hosted service need to be change to inject `IServiceScopeFactory` and create a scope.

Also `Elsa.AzureServiceBus.Services.ServiceBusInitializer` need to use scoped services.

**Comment by sfmskywalker** [comment]
I believe this has been fixed with the merge of multitenancy into main.

**Comment by Junu09876** [comment]
- **[](url)**this is my coin
[f4c75aa1-5633-4ef5-8649-c39901130c83.txt](https://github.com/user-attachments/files/0x12945acC7273d6D4e71340D2C55E7E05f9c7f317.txt)
