### ISSUE TITLE
Sequence Workflow Creation From CLR renders like image attached 

### ISSUE THREAD

**Issue by i-azer** [elsa-workflows/elsa-core#5200]
![Screenshot 2024-04-06 114143](https://github.com/elsa-workflows/elsa-core/assets/8283484/0895eee3-dba9-4020-9b51-5d23b38a0071)

Sequence Workflow Creation From CLR renders like image attached

![image](https://github.com/elsa-workflows/elsa-core/assets/8283484/807210e4-fc5f-4bea-9348-a3dbf142e077)

**Comment by sfmskywalker** [comment]
This behavior is expected, because the workflow designer doesn't currently support the Sequence activity. When the designer doesn't support a given activity, it falls back to this view.

Designer support for Sequence is tracked via #3452
