### ISSUE TITLE
Elsa 2.0: SendEmail - several receivers, cc and bbc

### ISSUE THREAD

**Issue by Rafael94** [elsa-workflows/elsa-core#521]
The activity `SendEmail` has no `cc` or `bbc`. However, under certain circumstances this could be useful and therefore I would add it.

It could be that there are multiple recipients and this is currently not possible. You could create a new `SendMail` activity for each recipient, but then you would have to maintain the texts several times. I would have two solutions, only I don't know which one is better for the UI.

- Comma separated list
- Array of strings

**Comment by sfmskywalker** [comment]
I would go with the array, it is more convenient to use from a c# workflow point of view. The UI will be able to deal with this.

**Comment by Rafael94** [comment]
Ok, I will change it later

**Comment by sfmskywalker** [comment]
Done as of 8419424c98bcb13a9b5944633cd1146708459883
