### ISSUE TITLE
Memory Leak or miss-configuration / multipart form request / no persistence

### ISSUE THREAD

**Issue by bernhardwimmer** [elsa-workflows/elsa-core#5226]
I have troubles to set up my ELSA Workflow Server so that there is no data persistent in memory when I execute HttpRequests. What I can see (by the use of dotMemory) looks like a **mem leak**, but maybe this is somthing that could be solved via configuration.

Using ELSA 3.1.2 in a new .net6 console app, I have set up a test-workflow which receives a file from a multipart-form request. The endpoint is configured as follows:

```
new HttpEndpoint
{
    Path = new Input<string>("/document-capture"),
    SupportedMethods = new Input<ICollection<string>>(new[] { HttpMethods.Post }),
    CanStartWorkflow = true,
    Files = new Output<IFormFile[]>(files),
}
```

To avoid any data-persistence I have registered a NoopWorkflowStore as IWorkflowInstanceStore. Please tell me if this could be done easier. 

```
public class NoopWorkflowStore : IWorkflowInstanceStore
{
  ...
  public ValueTask SaveAsync(WorkflowInstance instance, CancellationToken cancellationToken = default)
  {
      return ValueTask.CompletedTask;
  }
  ...
}
```

I have started my workflow server project with dotMemory attached. Then I sent 3 requests to my test-endpoint, forced a GC and created a 1st mem-snapshot, then I repeated the procedure to create a 2nd snapshot.

This are the 2 snapshots:

![ELSA_Mem_Snapshots](https://github.com/elsa-workflows/elsa-core/assets/32705418/8b60357f-623d-461c-92cd-14467d016764)

A comparison of the 2 snapshots shows that there are many new object-arrays in memory.

![ELSA_Mem_NewObjectArrays](https://github.com/elsa-workflows/elsa-core/assets/32705418/493491fc-48bc-4878-932a-5992378633b3)

Now I picked 1 of the new object-array instances a looked at the key retention path, which shows the reference which prevents garbage collection. The info about the "TlsOverPerCoreLockedStacksArrayPool+ThreadLocalArray<Byte>" does not really help me to solve the issue:

![ELSA_Mem_NewObjectArray_KeyRetentionPath](https://github.com/elsa-workflows/elsa-core/assets/32705418/8dc9bc1e-de87-47f3-954f-417635dd8e64)

The last thing I looked at was the creation stack trace, which is really a deep one:

![ELSA_Mem_ObjectArray_CreationStackTrace](https://github.com/elsa-workflows/elsa-core/assets/32705418/6fb8c307-87a9-4a4e-af3c-856a420274f8)

It would be cool if someone can tell me if this is a real mem leak or just some miss-configuration topic, and if so, how to solve this.

**Comment by sfmskywalker** [comment]
Out of the box, Elsa will register memory store implementations for the following stores:

- IWorkflowInstanceStore
- IIWorkflowExecutionLogStore
- IActivityExecutionStore
- IWorkflowInboxMessageStore
- IBookmarkStore
- ITriggerStore

The last 3 stores contain transitory information that will be removed (bookmarks and workflow inbox messages), or at least not grow (triggers).

You already configured the `IWorkflowInstanceStore` with a NOOP implementation. Next, you would also need one for `IIWorkflowExecutionLogStore` and `IActivityExecutionStore`.

If you still see an increase of memory consumption that cannot be purged, then please do let me know.

**Comment by bernhardwimmer** [comment]
This looks really much better now.
I have added the additional empty-Implementations as follows:

```
services.AddSingleton<IWorkflowInstanceStore, NoopWorkflowStore>();
services.AddSingleton<IWorkflowExecutionLogStore, NoopWorkflowExecutionLogStore>();
services.AddSingleton<IActivityExecutionStore, NoopActivityExecutionStore>();
services.AddSingleton<IWorkflowInboxMessageStore, NoopWorkflowInboxMessageStore>();
services.AddSingleton<IBookmarkStore, NoopBookmarkStore>();
services.AddSingleton<ITriggerStore, MemoryTriggerStore>();
```

For the ITriggerStore I registered the MemoryTriggerStore, because my Noop-implementation created problems.

The workflow that I use for testing is practically empty. It takes the multipart-form and returns the size of the byte-array of the first file:

```
public class MinimumWorkflow : WorkflowBase
{
    private readonly IServiceProvider _serviceProvider;

    public MinimumWorkflow(IServiceProvider serviceProvider)
    {
        _serviceProvider = serviceProvider ?? throw new System.ArgumentNullException(nameof(serviceProvider));
    }

    protected override void Build(IWorkflowBuilder builder)
    {
        // stores the files uploaded to the HTTP endpoint
        var files = builder.WithVariable<IFormFile[]>("Document", null);

        builder.Root = new Sequence
        {
            Variables = { files },
            Activities =
            {
                new HttpEndpoint
                {
                    Path = new Input<string>("/document-capture"),
                    SupportedMethods = new Input<ICollection<string>>(new[] { HttpMethods.Post }),
                    CanStartWorkflow = true,
                    Files = new Output<IFormFile[]>(files),
                },
                new WriteHttpResponse
                {
                    Content = new Input<object?>(context =>
                    {
                        //var variable = context.GetVariable(Workflow.Activities.Bludelta.Constants.BcOcrResult);
                        var variable1 = $"Received file with {files.Get(context)[0].Length} bytes";


                        return JsonConvert.SerializeObject(variable1);
                    }),
                    StatusCode = new Input<HttpStatusCode>(HttpStatusCode.OK),
                    ContentType = new Input<string>("application/json"),

                }
            }
        };
    }
}
```

I have created 10 snapshots. Between each snapshot I send 10 requests and before each snapshot I force a GC.

![image](https://github.com/elsa-workflows/elsa-core/assets/32705418/a0975ef9-e74b-4910-a623-7a04d39a55d8)

Although the workload is exactly the same between each snapshot, the object count and .Net mem consumption a slightly differing, but I see this behaviour across all our .Net apps.

Comparing snapshots 9 and 10, I can see a view classes with object deltas. But the delta instance count is less than 10 and I sent 10 requests between the snapshots. So I assume that this is not a mem leak.

![image](https://github.com/elsa-workflows/elsa-core/assets/32705418/cfec433b-f0db-45f5-9165-1518f3f18120)

Thanks for your help and the fast response!!

**Comment by bernhardwimmer** [comment]
Sorry, one more question:
Which Interfaces would I need to override in Elsa 2.13 to remove all persistence?
For example there does not seem to be an IActivityExecutionStore in Elsa v2.

**Comment by jordanpedro** [comment]
@bernhardwimmer Hi,  can you tell where did you put those statements:

services.AddSingleton<IWorkflowInstanceStore, NoopWorkflowStore>();
services.AddSingleton<IWorkflowExecutionLogStore, NoopWorkflowExecutionLogStore>();
services.AddSingleton<IActivityExecutionStore, NoopActivityExecutionStore>();
services.AddSingleton<IWorkflowInboxMessageStore, NoopWorkflowInboxMessageStore>();
services.AddSingleton<IBookmarkStore, NoopBookmarkStore>();
services.AddSingleton<ITriggerStore, MemoryTriggerStore>();



before or after the calling of builder.Services.AddElsa () ?

**Comment by bernhardwimmer** [comment]
@jordanpedro: I have added them afterwards, so it looks like this now:

```
services
    .AddElsa(elsa =>
        {
            elsa.AddWorkflow<MinimumWorkflow>();
            elsa.UseHttp();
            elsa.UseWorkflowsApi();
        }
    );

// Elsa overrides --> remove persistence
services.AddSingleton<IWorkflowInstanceStore, NoopWorkflowStore>();
services.AddSingleton<IWorkflowExecutionLogStore, NoopWorkflowExecutionLogStore>();
services.AddSingleton<IActivityExecutionStore, NoopActivityExecutionStore>();
services.AddSingleton<IWorkflowInboxMessageStore, NoopWorkflowInboxMessageStore>();
services.AddSingleton<IBookmarkStore, NoopBookmarkStore>();
services.AddSingleton<ITriggerStore, MemoryTriggerStore>();
```
