### ISSUE TITLE
MySQL DELETE ‘WorkflowInboxMessages’ ERROR[BUG]

### ISSUE THREAD

**Issue by 493141993** [elsa-workflows/elsa-core#5227]
![20240416114112](https://github.com/elsa-workflows/elsa-core/assets/46142629/6764173f-2cdb-4900-a1e9-9be1d44e2d9f)

**Comment by 493141993** [comment]
MySql Version:8.0.11

**Comment by cr0fters** [comment]
Worth mentioning, that if you downgrade Pomelo to 7.0.0 (you'll also need to be running on .Net 7) the issue goes away. Maybe worth waiting until they patch it on the Pomelo side rather than change the implementation here?

**Comment by sfmskywalker** [comment]
This issue will be resolved automatically when we merge https://github.com/elsa-workflows/elsa-core/pull/5444. We'll close this issue once that happens.
