### ISSUE TITLE
Elsa 2.0: Centralize project properties

### ISSUE THREAD

**Issue by Rafael94** [elsa-workflows/elsa-core#523]
The projects have common properties that must be specified for each new project.

```
<LangVersion>latest</LangVersion>
<Authors>Elsa Contributors</Authors>
...
```

These can be centralized in a .prop file so that only this file needs to be customized.

**Comment by sfmskywalker** [comment]
I was thinking about that a couple of days back. Do you want to do it?

**Comment by Rafael94** [comment]
I'm already on it. :)

I do it then also with Fody and ConfigureAwait #426

**Comment by sfmskywalker** [comment]
You deserve a medal. Thanks! 😊

**Comment by Rafael94** [comment]
Can be closed. #524
