### ISSUE TITLE
Next Activity Found But Not Scheduled After Resume [Elsa 3.1.2]

### ISSUE THREAD

**Issue by iamyokai** [elsa-workflows/elsa-core#5304]
As shown in screenshot captured below, the activity "In Use" resumed and completed and the **next child activity was found but the activity not scheduled** and the workflow was stuck in Suspended. I have encountered this a few times along the way **specifically in looping scenarios**. Initially it happened within a straightforward workflow and now within While activity.

![image](https://github.com/elsa-workflows/elsa-core/assets/168507246/00d7084c-1cd6-4dc1-8851-ef12014c6838)

![image](https://github.com/elsa-workflows/elsa-core/assets/168507246/48afa8c0-82c3-412c-9470-8e15ac2f5240)

[workflow.json](https://github.com/elsa-workflows/elsa-core/files/15158230/workflow.json)

[workflow instance data.json](https://github.com/elsa-workflows/elsa-core/files/15158270/workflow.instance.data.json)

**Comment by 15859096137** [comment]
Your problem is the same as mine. I hope that after resuming the activity, it can automatically proceed. But at present, it seems to be stuck at the node where it was resumed.

https://github.com/elsa-workflows/elsa-core/issues/5281

**Comment by jdevillard** [comment]
Hello , you can unblock using a join activity just before preparing.

**Comment by iamyokai** [comment]
It seems that adding a Join activity does seems to resolve my issue.

![image](https://github.com/elsa-workflows/elsa-core/assets/168507246/4ee0794c-e501-4718-9574-3f035e247f82)

My activity is modelled after the Decision flow node activity, the outcome is either Forward or Backward depending on the configured action and result. 
- Is it intended that Join activity will always be required when **_either route converge at a later stage_**?
- In my scenario, the activity In Use actually unblock when resumed, so it seems the converge actually causes the workflow itself to block instead?
