### ISSUE TITLE
Could you please help me solve this problem as soon as possible? Thank you! 

### ISSUE THREAD

**Issue by 15859096137** [elsa-workflows/elsa-core#5305]
https://github.com/elsa-workflows/elsa-core/issues/5281#issue-2265331723

**Comment by sfmskywalker** [comment]
Hello @15859096137 ,

Thank you for reaching out and for your involvement in our community. We understand and appreciate your eagerness to resolve your issue.

However, I would like to gently remind you that creating new issues to request updates or help on existing issues can lead to some confusion and is generally not the best approach. It can fragment the discussion and make it harder for both the community and maintainers to track progress on a particular problem.

Instead, I encourage you to comment directly on the existing issue. This way, all relevant discussions are centralized, making it easier for everyone involved to follow along and contribute effectively. It also helps maintainers prioritize issues based on community feedback and engagement directly within each thread.

If you're unsure whether your comment or question might be relevant or if you feel the issue hasn’t been addressed in a timely manner, it's perfectly acceptable to ask for an update in the existing thread. Our community thrives on open communication, and your contributions are valued.

Thank you for understanding and for helping us keep our community organized and efficient!
