### ISSUE TITLE
[BUG] Default CRON causes extremely high memory usage until Out of Memory exception

### ISSUE THREAD

**Issue by rboylesDev** [elsa-workflows/elsa-core#5312]
## Description

We are using Elsa 3 with the default scheduling. Whenever we have a Timer or CRON triggered workflow, we have noticed jumps in memory usage when the workflow is triggered and then this memory is never garbage collected. We are running Elsa on Azure Container Apps with 1 GB of RAM. With a CRON that runs every 15 minutes, it runs for about two hours until the container app crashes with an out of memory exception and then is automatically restarted. We have experienced this memory leak as well locally, but with significantly more RAM, it is not causing issues unless it runs for days. 

## Steps to Reproduce
Create even a simple workflow with a Timer or CRON expression, even one that just writes to console. Allow it to run and trigger and observe memory allocations. 

## Expected Behavior
While a memory jump isn't unexpected, having GC run and release memory is expected.

## Actual Behavior
Memory appears to not be de-allocated.

## Screenshots

Here is a sample of memory usage from our container app showing the raising memory until the app crashes and restarts.
![image](https://github.com/elsa-workflows/elsa-core/assets/1521243/d6b02eb6-37b3-4be9-a71a-d79a7be71f75)

## Environment
- **Elsa Package Version**: Specify the version. If you've cloned the repo, mention if you are using the latest source code from the main branch.
- **Operating System**: Include your OS version (e.g., Windows 10, macOS Big Sur, Ubuntu 18.04).
- **Browser and Version**: If applicable, include your browser and version (e.g., Chrome 92).

## Troubleshooting Attempts
Initially we thought it might be the amount of work that the workflow is trying to do. But even a simple workflow of writing a console message or dispatching another workflow will still continue to allocate memory.

**Comment by rboylesDev** [comment]
Oh, I forgot to mention, we are using version 3.1.2 of Elsa. So I do not believe it is the same issue as the Code Activity memory leak.

**Comment by sfmskywalker** [comment]
Confirmed:

<img width="1940" alt="image" src="https://github.com/elsa-workflows/elsa-core/assets/938393/f469e834-1436-4527-8db0-0c45da633a63">


@rboylesDev thanks for reporting!

**Comment by sfmskywalker** [comment]
@rboylesDev Just to make sure: is the application using non-memory stores for all of the modules:

- Workflow Management
- Workflow Runtime

Unless you explicitly configure the persistence provider for these two, they will use the Memory provider by default - which will most certainly lead to an increase of memory consumption as new workflow instances and execution records are stored in an in-memory dictionary.

**Comment by rboylesDev** [comment]
We are using Elsa with EF Core and SQL Server. I believe these are configured correctly as it is a very simple code setup.

![image](https://github.com/elsa-workflows/elsa-core/assets/1521243/0aa46bd0-5ffc-45d5-8226-c20fa56b47e2)

**Comment by rboylesDev** [comment]
Minor update on our end. We decided to look at Quartz scheduler instead of the built-in scheduler. This had the same result of allocating ~200MB per scheduled workflow run and never seeming to release it. What is interesting is taking the same workflow and manually running it does not see the same jump in allocation.

**Comment by diegodalben** [comment]
Hi! 
I'm facing the same issue, but in my case, I'm using Hangfire for scheduling management. 
I'm using version 3.1.2.

**Comment by sfmskywalker** [comment]
Any way you can try 3.2.0? If you can still see memory increase until it runs out, it would be good to see some screenshots and ideally a (simplified) copy of your project or a reproduction.

**Comment by TimNguyenVN** [comment]
Hi @sfmskywalker, I might be mistaken, but have you checked the `RemoveScheduledTask` function? 
From the logic, it looks like when a trigger is removed, the `ScheduledTask` is canceled, but it doesn't seem to be removed from the `_scheduledTasks` dictionary. Instead, it only gets removed from the `_scheduledTaskKeys` dictionary. This could lead to the `_scheduledTasks` dictionary growing over time as tasks accumulate without being cleared.

By the way, could you explain the purpose of `_scheduledTaskKeys` and `keys` here?

![image](https://github.com/user-attachments/assets/faa7776b-2d6c-44c2-8200-5da3a4e98334)

**Comment by sfmskywalker** [comment]
@TimNguyenVN You're 100% correct - the `_scheduledTasks` dictionary doesn't get updated in this method, which may very well explain the increase in memory consumption. I will push a fix shortly.

Great catch! 👍🏻

**Comment by sfmskywalker** [comment]
Done via 123a95c07cafa40067e85b682028c9a2a60c3cfd
