### ISSUE TITLE
[BUG]How does Elsa use Sqlserver?

### ISSUE THREAD

**Issue by zqhgit001** [elsa-workflows/elsa-core#5398]
您好：
ElsaServer 默认数据库是sqlite?  如何配置成数据库为sqlserver?

**Comment by zqhgit001** [comment]
Elsa 3.0 is not Elsa.Persistence.EntityFramework.SqlServer?

**Comment by sfmskywalker** [comment]
@zqhgit001 I had to block you due to repeated spam and duplicate issues that are often incomplete or incomprehensible. If you feel this action is unfair, please contact me on Discord (@sfmskywalker) to discuss this further.
