### ISSUE TITLE
[BUG]Elsa 3.0 is not Elsa.Persistence.EntityFramework.SqlServer?

### ISSUE THREAD

**Issue by zqhgit001** [elsa-workflows/elsa-core#5400]
您好：
Elsa 3.0 is not Elsa.Persistence.EntityFramework.SqlServer?

**Comment by sfmskywalker** [comment]
@zqhgit001 I had to block you due to repeated spam and duplicate issues that are often incomplete or incomprehensible. If you feel this action is unfair, please contact me on Discord (@sfmskywalker) to discuss this further.
