### ISSUE TITLE
[BUG]Elsa.EntityFrameworkCore.SqlServer启动如何配置？

### ISSUE THREAD

**Issue by zqhgit001** [elsa-workflows/elsa-core#5401]
您好：
Elsa 3.0 如何配置Sqlserver数据库？Elsa.EntityFrameworkCore.SqlServer

**Comment by sfmskywalker** [comment]
@zqhgit001 I had to block you due to repeated spam and duplicate issues that are often incomplete or incomprehensible. If you feel this action is unfair, please contact me on Discord (@sfmskywalker) to discuss this further.
