### ISSUE TITLE
[BUG]Elsa 3.0 NuGet包，没有Elsa的SQL Server持久性提供程序？

### ISSUE THREAD

**Issue by zqhgit001** [elsa-workflows/elsa-core#5403]
您好：Elsa 3.0 NuGet包，没有Elsa的SQL Server持久性提供程序？

**Comment by sfmskywalker** [comment]
@zqhgit001 I had to block you due to repeated spam and duplicate issues that are often incomplete or incomprehensible. If you feel this action is unfair, please contact me on Discord (@sfmskywalker) to discuss this further.
