### ISSUE TITLE
How To Generate API Key

### ISSUE THREAD

**Issue by albourm** [elsa-workflows/elsa-core#5450]
I am using Workflow Elsa V3, How to generate API Key i want to call Elsa APIs.

**Comment by sfmskywalker** [comment]
Hi @albourm , thank you for your question. We have [an issue for describing the steps](https://github.com/elsa-workflows/elsa-documentation/issues/23) in the documentation repo to track this request. I will therefore close this issue as duplicate. Please keep an eye out on the other issue for any updates. In the meantime, just a few quick pointers:

1. First, configure your app to use the AdminAPI key (this is used in the documentation)

2. Create an Application using Postman. Example:

```
curl --location 'https://localhost:5001/elsa/api/identity/applications' \
--header 'Content-Type: application/json' \
--header 'Authorization: ApiKey 00000000-0000-0000-0000-000000000000' \
--data '{
    "name": "Postman",
    "roles": ["admin"]
}'
```

3. The response will include a non-encrypted version of the API key that you can use.

4. Update your application's configuration to use a configuration based or DB based Identity provider from where the Application can be retrieved. If you use Configuration, make sure to past in the response of the API call into the right section (see the [reference application for an example](https://github.com/elsa-workflows/elsa-core/blob/main/src/bundles/Elsa.Server.Web/appsettings.json#L67)) - minus the clear text API key.

**Comment by albourm** [comment]
Hi @sfmskywalker 

I would like to thank you for your support. I will try your suggestion.
Actually, I am facing one issue. I have designed the workflow using the Workflow Designer, so I have http call activities. Sometimes one of the http calls gets a bad request or something else, and then the Workflow instance gets a fault. Therefore, I want to find a way to re-trigger the workflow instance after solving the problem. For example, I want the API key to hit the Elsa APIs. But one more thing: how can I re-trigger the workflow instance using the workflow instance ID?
