### ISSUE TITLE
Slow dashboard 

### ISSUE THREAD

**Issue by Alexplose** [elsa-workflows/elsa-core#546]
I'm using the Elsa 1.4.5, and the /Elsa/workflow-definition page is really slow to display.
Is there any way to optimize or maybe change some settings ?

![image](https://user-images.githubusercontent.com/18287013/103401941-4a882980-4b4b-11eb-98b5-ac5455216d43.png)

**Comment by mohdali** [comment]
The dashboard tries to load every workflow instance with all its states, which could end up with a an expensive join operation in case of SQL Server.

We ended up writing a custom EF Core store that returns stripped down objects for the two calls used by the dashboard.
https://elsa-workflows.github.io/elsa-core/docs/extensibility-persistence

 ```
 public async Task<IEnumerable<WorkflowInstance>> ListByDefinitionAsync(
            string definitionId,
            CancellationToken cancellationToken = default)
        {
            var documents = await dbContext
                .WorkflowInstances
                .Select(w => new WorkflowInstanceEntity
                {
                    Id = w.Id,
                    DefinitionId = w.DefinitionId,
                    Status = w.Status,
                    CreatedAt = w.CreatedAt
                })
                .Where(x => x.DefinitionId == definitionId)                
                .OrderByDescending(x => x.CreatedAt)
                .AsNoTracking()
                .ToListAsync(cancellationToken);

            return Map(documents);
        }

public async Task<IEnumerable<WorkflowInstance>> ListByStatusAsync(
            string definitionId,
            WorkflowStatus status,
            CancellationToken cancellationToken = default)
        {
            var documents = await dbContext
                .WorkflowInstances
                .Select(w => new WorkflowInstanceEntity
                {
                    Id = w.Id,
                    InstanceId = w.InstanceId,
                    DefinitionId = w.DefinitionId,
                    Status = w.Status,
                    CreatedAt = w.CreatedAt,
                    StartedAt = w.StartedAt,
                    FinishedAt = w.FinishedAt,
                    FaultedAt = w.FaultedAt,
                    CorrelationId = w.CorrelationId,
                    Fault = w.Fault,
                    Version = w.Version
                })
                .Where(x => x.DefinitionId == definitionId && x.Status == status)
                .OrderByDescending(x => x.CreatedAt)
                .ToListAsync(cancellationToken);

            return Map(documents);
        }
```

The mapper code also needed to be updated because it always assumes activities are there.

```
 public class ActivityInstanceEntityCollectionConverter : IValueConverter<ICollection<ActivityInstanceEntity>, IDictionary<string, ActivityInstance>>
    {
        public IDictionary<string, ActivityInstance> Convert(ICollection<ActivityInstanceEntity> sourceMember, ResolutionContext context)
        {
            return sourceMember?.ToDictionary(x => x.ActivityId, x => context.Mapper.Map<ActivityInstance>(x));
        }
    }

    public class ActivityInstanceDictionaryConverter : IValueConverter<IDictionary<string, ActivityInstance>, ICollection<ActivityInstanceEntity>>
    {
        public ICollection<ActivityInstanceEntity> Convert(IDictionary<string, ActivityInstance> sourceMember, ResolutionContext context) =>
            sourceMember?.Select(x => context.Mapper.Map<ActivityInstanceEntity>(x.Value)).ToList();
    }
```

**Comment by Alexplose** [comment]
Thanks for your answer, also did you modify anything to get the LogEntry displayed in the dashboad when in a workflow instance details ?

**Comment by mohdali** [comment]
I think Log Entries were coming normally to the dashboard when viewing instance details.
We have not customized on that part.

**Comment by craigfowler** [comment]
This issue is about Elsa 1.4.5.  The dashboard is receiving a major rewrite in 2.0.
@sfmskywalker - do you think that Elsa 2 would continue to have this performance problem?  Is it worth keeping this issue open in your opinion (even if it's only kept open so that we test it doesn't happen in 2.0)?

**Comment by sfmskywalker** [comment]
Nope, Elsa 2 doesn't have this problem. For info, the dashboard queries the API endpoint, which returns "summary" view models of workflow definitions. Furthermore, a given workflow's execution log is now stored in a separate collection/table.

I've been testing the changes with a customer in production with great results (yes I said it; we tested in production. Fire away 🔫 😄)

We can safely close this ticket.
