### ISSUE TITLE
pgsql or mariadb support request

### ISSUE THREAD

**Issue by MiyamuraMiyako** [elsa-workflows/elsa-core#547]
As title

**Comment by Rafael94** [comment]
There is a branch for EF Core for Elsa 2.0 (https://github.com/elsa-workflows/elsa-core/tree/elsa-2.0/ef-core) probably you can use it for pgsql or mariadb.

**Comment by sfmskywalker** [comment]
Indeed, once the EF Core provider is in place, [all of these databases](https://docs.microsoft.com/en-us/ef/core/providers/?tabs=dotnet-core-cli) are supported automatically.

**Comment by MiyamuraMiyako** [comment]
@Rafael94 @sfmskywalker Thanks for reply, I understand.
