### ISSUE TITLE
The last WriteLine activity of sample25 is missing one connection

### ISSUE THREAD

**Issue by leisurelyclouds** [elsa-workflows/elsa-core#548]
https://github.com/elsa-workflows/elsa-core/blob/3717c7b9509de89e3df2c8578311a69a5d91a326/src/samples/Sample25/DataProcessingWorkflow.cs#L54

This line of code is not executed

**Comment by craigfowler** [comment]
Good spot @leisurelyclouds !  I agree, I don't think that this `WriteLine` activity would ever be executed because it's improperly connected.

As a quick-fix I'll create a PR to simply drop that line from the v1.x samples.
