### ISSUE TITLE
[CHORE] Elsa 3.0工作流节点审批用户角色权限怎么实现？

### ISSUE THREAD

**Issue by zqhgit001** [elsa-workflows/elsa-core#5492]
您好：Elsa 3.0工作流节点审批用户角色权限怎么实现？

**Comment by sfmskywalker** [comment]
@zqhgit001 I had to block you due to repeated spam and duplicate issues that are often incomplete or incomprehensible. If you feel this action is unfair, please contact me on Discord (@sfmskywalker) to discuss this further.
