### ISSUE TITLE
Elsa.Samples.DeclarativeCompositeActivitiesConsole only executes the first activity

### ISSUE THREAD

**Issue by leisurelyclouds** [elsa-workflows/elsa-core#551]
https://github.com/elsa-workflows/elsa-core/blob/feature/elsa-2.0/src/samples/console/Elsa.Samples.DeclarativeCompositeActivitiesConsole/Program.cs

**Comment by craigfowler** [comment]
@sfmskywalker whilst I don't doubt that this bug report is accurate, my knowledge of the syntax which is used in the sample is not up to scratch enough to see how to fix that one quickly.  Given it relates to a sample for the v1.x syntax, I suppose it's reasonable to assume that it's not going to get priority whilst we're on the final push towards v2.

I have a feeling that unless you are willing to address this issue yourself Sipke then probably nobody else is going to do it.  In which case the most honest thing might be to close as a **wontfix** - that is - presuming you think the issue wouldn't exist in 2.0?  What do you think?

**Comment by sfmskywalker** [comment]
Actually, the referenced sample project is part of the 2.0 branch. I'll take a look and report back here.

**Comment by sfmskywalker** [comment]
Yeah there's an issue with the example (or with Elsa 2.0 Elon forbid). I'm fixing it.

**Comment by craigfowler** [comment]
> Actually, the referenced sample project is part of the 2.0 branch
So it is.  It has become apparent that I have forgotten how to read, sorry :roll_eyes: 

Glad you're on form!

**Comment by sfmskywalker** [comment]
Fixed in 4b33418cf77bea7659b6f4305d5151e63c035482
