### ISSUE TITLE
[CHORE] Elsa 3.0 Condition = new JavaScriptExpression()

### ISSUE THREAD

**Issue by zqhgit001** [elsa-workflows/elsa-core#5517]
您好：Elsa 3.0 Condition = new JavaScriptExpression()

**Comment by fanslead** [comment]
老哥，github不是你这样用的，这个仓库的Issue都被你污染了......

**Comment by sfmskywalker** [comment]
@fanslead is right.

@zqhgit001 I had to block you due to repeated spam and duplicate issues that are often incomplete or incomprehensible. If you feel this action is unfair, please contact me on Discord (@sfmskywalker) to discuss this further.
