### ISSUE TITLE
[BUG]elsa 3.0 ”IWorkflowBuilder“未包含”StartWith“的定义

### ISSUE THREAD

**Issue by zqhgit001** [elsa-workflows/elsa-core#5528]
elsa 3.0 ”IWorkflowBuilder“未包含”StartWith“的定义

**Comment by sfmskywalker** [comment]
@zqhgit001 I had to block you due to repeated spam and duplicate issues that are often incomplete or incomprehensible. If you feel this action is unfair, please contact me on Discord (@sfmskywalker) to discuss this further.
