### ISSUE TITLE
[CHORE] 如何在Elsa 3.0中使用JavaScript表达式?

### ISSUE THREAD

**Issue by zqhgit001** [elsa-workflows/elsa-core#5538]
如何在Elsa 3.0中使用JavaScript表达式?

**Comment by sfmskywalker** [comment]
@zqhgit001 I had to block you due to repeated spam and duplicate issues that are often incomplete or incomprehensible. If you feel this action is unfair, please contact me on Discord (@sfmskywalker) to discuss this further.
