### ISSUE TITLE
[BUG]  Issues with POST and GET Execute APIs

### ISSUE THREAD

**Issue by cvijayak** [elsa-workflows/elsa-core#5553]
**POST : Execute API**
The POST `/workflow-definitions/{definitionId}/execute` endpoint in Swagger is not showing a text box for accepting the request body.

![image](https://github.com/elsa-workflows/elsa-core/assets/65659375/73a55c7c-ca0c-4215-a9b4-4114974b74da)

It looks like the highlighted line below in the Elsa core is causing the problem of not showing the request body for the POST API. It seems the same handler is used for both GET and POST requests. Therefore, if we remove GET from the configuration, we will be able to see the request body for the POST API. A different handler needs to be written for the GET API to support both verbs.

![image](https://github.com/elsa-workflows/elsa-core/assets/65659375/2f169f1e-03ce-4443-b463-871b20fb5a02)

To confirm, I changed the configuration and checked whether the POST API shows the request body. Yes, it shows properly. Please refer to the screenshot below for more details.

![image](https://github.com/elsa-workflows/elsa-core/assets/65659375/70943a4a-ee87-4cf2-9312-2ede692a4b9f)

**GET : Execute API**
Additionally, I am looking for some clarification on the GET `/workflow-definitions/{definitionId}/execute` endpoint. When I try to call the GET API as shown below, the API throws type-casting error.

`https://<HOST>/api/workflow-definitions/bddbe8462d444632/execute?correlationId=34343222&versionOptions=Latest&input={"accountId": "23242267889"}`

Please find the type-casting error in the screenshot below
![image](https://github.com/elsa-workflows/elsa-core/assets/65659375/2e01693b-efc1-41c6-9a7a-c7455a2e518a)

Please note that I am passing the 'input' as a query string parameter. As per my understanding, in the FastEndpoints framework, GET request DTO properties are automatically serialized from query string parameters by default.

So, I tried to send the 'input' in the query string like the other parameters, but it throws a type-casting error, stating that it is unable to cast the JSON object into a dictionary. This seems like a bug to me. Please confirm the same.

Highlighted line in the below screenshot throws the exception
![image](https://github.com/elsa-workflows/elsa-core/assets/65659375/e5d8626d-021d-4b5f-b0b6-adc1a7c400df)

It looks like the _JsonConverter_ defined in the model(shown in the screenshot below) is not getting invoked if we pass the 'input' through the query string.
![image](https://github.com/elsa-workflows/elsa-core/assets/65659375/e280a0ed-f407-45c4-bfff-f8961a7ff66f)

If the JsonConverter invoked properly, we will not see the casting issue.

**Comment by cvijayak** [comment]
@sfmskywalker Any updates on this?

The issue still there in 3.2 rc1

**Comment by sfmskywalker** [comment]
Hi @cvijayak , unfortunately I don’t have the bandwidth to work on this for inclusion with 3.2. However, if you want to propose a PR then maybe we could include it.

**Comment by cvijayak** [comment]
@sfmskywalker 
Sure, I will raise PR for the same
