### ISSUE TITLE
[ENH] MongoDB storage for alterations

### ISSUE THREAD

**Issue by rosca-sabina** [elsa-workflows/elsa-core#5554]
### Enhancement Overview
Elsa Workflows doesn't currently support using MongoDB as a storage provider for alteration plans and jobs out of the box.

As such, users who want to use MongoDB as persistent storage for both alterations and other functionalities (such as workflow runtime or management) have to either implement their own `IAlterationJobStore` and `IAlterationPlanStore` using MongoDB, or to use a different storage provider just for alterations.

### Proposed Enhancement
Provide MongoDB implementations for `IAlterationJobStore` and `IAlterationPlanStore`, and an extension method to allow users to configure `AlterationsFeature` to use MongoDB as storage.

### Use Cases
Users who want to use MongoDB as a storage provider for alterations would benefit from this enhancement. 

### Impact of Enhancement
This enhancement would improve user experience and productivity for users that use alterations by offering support for MongoDB storage out of the box.

**Comment by rosca-sabina** [comment]
@sfmskywalker Should this be added to the Elsa 3.2 milestone?

**Comment by sfmskywalker** [comment]
Yes, thank you.

**Comment by rosca-sabina** [comment]
Nice, closing the issue since it was resolved in PRs #5555 and #5564. Thanks!
