### ISSUE TITLE
The given key 'area' was not present in the dictionary.

### ISSUE THREAD

**Issue by mhymhygi** [elsa-workflows/elsa-core#558]
when i used "AddAuthorizeFilterConvention" like this:
`  services.AddMvc(options =>
            {
                options.Conventions.Add(new AddAuthorizeFilterConvention(""));
            }),`
the error "The given key 'area' was not present in the dictionary." I got.
then I rewrited ` if (controller.RouteValues["area"] == AreaName)` to ` if(controller.RouteValues.ContainsKey("area") && controller.RouteValues["area"]=="Elsa")` in my project.It is worked.

**Comment by sfmskywalker** [comment]
Closing, since this is no longer relevant with the advent of Elsa 2.
