### ISSUE TITLE
[BUG] FailedToConnect activity in SendHttpRequest is not executed

### ISSUE THREAD

**Issue by cschulznethaus** [elsa-workflows/elsa-core#5591]
## Description
I'm currently testing the behavior of `SendHttpRequest`, when the target is not reachable. I expected that the `FailedToConnect` would be executed, but nothing happens. I assigned a `Fault` activity to `FailedToConnect` which should terminate further execution, but after the failed HTTP Request the rest of the workflow is successfully executed.

## Steps to Reproduce

1. **Detailed Steps**: 
* Create a workflow with a `SendHttpRequest` activity that calls an endpoint that does not exists.
* Assign a Fault to the `FailedToConnect`.
* Trigger the workflow.

2. **Code Snippets**: 

Here is the example workflow I used.

``` c#
public sealed class TimeoutWorkflow : WorkflowBase
{
    protected override void Build(IWorkflowBuilder builder)
    {
        var request = builder.WithVariable<TenantOffboardingRequest>().WithMemoryStorage();

        builder.Name = "Example Timeout Workflow";
        builder.Root = new Sequence
        {            
            Activities =
            {
                new HttpEndpoint
                {
                    Path = new("/timeout"),
                    SupportedMethods = new([HttpMethods.Post]),

                    CanStartWorkflow = true
                },

                new SendHttpRequest
                {
                    Url = new(new Uri($"http://localhost:1234/url-that-does-not-exist")),
                    Method = new(HttpMethods.Post),
                    UnmatchedStatusCode = new Fault(),
                    FailedToConnect = new Fault(),
                    Timeout = new Fault(),
                    ExpectedStatusCodes =
                        {
                            new HttpStatusCodeCase
                            {
                                StatusCode = StatusCodes.Status200OK
                            }
                        },
                },

                new WriteHttpResponse
                {
                    StatusCode = new(HttpStatusCode.NoContent)
                }
            }
        };
    }
}
```

3. **Reproduction Rate**: every time

## Expected Behavior
The `Fault` activity should terminate the workflow.

## Actual Behavior
The workflow finishes successfully.

## Screenshots
![image](https://github.com/elsa-workflows/elsa-core/assets/145961133/d577cdd0-cbbb-413c-91af-3622a4dd8416)

## Environment
- **Elsa Package Version**: 3.1.3
- **Operating System**: Windows 11
- **Browser and Version**: Edge 125.0.2535.92 

## Troubleshooting Attempts

I believe the problem lies in `SendHttpRequestActivityResolver`. `GetPortsInternal` does not yield return `Timeout` and `FailedToConnect`. I replaced `SendHttpRequestActivityResolver` with an adjusted version, which solved the problem for me.

``` diff
    private IEnumerable<IActivity> GetPortsInternal(IActivity activity)
    {
        var sendHttpRequest = (SendHttpRequest)activity;
        var cases = sendHttpRequest.ExpectedStatusCodes.Where(x => x.Activity != null);

        foreach (var @case in cases)
            yield return @case.Activity!;

+        if (sendHttpRequest.Timeout != null)
+            yield return sendHttpRequest.Timeout;
+
+        if (sendHttpRequest.FailedToConnect != null)
+            yield return sendHttpRequest.FailedToConnect;
+
        if (sendHttpRequest.UnmatchedStatusCode != null)
            yield return sendHttpRequest.UnmatchedStatusCode;
    }
```

**Comment by jdevillard** [comment]
Hello, 

Thanks for this issue, I think you're right, would you like to create a PR to submit your change ?
