### ISSUE TITLE
Elsa Designer example depandency 404

### ISSUE THREAD

**Issue by lzw5399** [elsa-workflows/elsa-core#562]
Hi, dude. I want to include the workflow designer in my business system, so I copied the below example in an HTML file to have a try, but it cannot found the **elsa-workflow-designer.js** file. can you have a see?
https://elsa-workflows.github.io/elsa-core/docs/installing-elsa-designer#example

![](http://pic.codepie.fun/img/20210111133032.png)

Regards.

**Comment by sfmskywalker** [comment]
My bad - the referenced script URL `https://unpkg.com/@elsa-workflows/elsa-workflow-designer/dist/elsa-workflow-designer.js` references the latest published version, which is **2.0.0-preview6**. However that version is broken. The latest functioning version is **0.0.61**.

I have just updated the sample code to explicitly reference 0.0.61.
