### ISSUE TITLE
ReceiveHttpRequestEvent not found

### ISSUE THREAD

**Issue by lzw5399** [elsa-workflows/elsa-core#563]
I followed this docs example and tried it out, but the program compiled failed because cannot find the `ReceiveHttpRequestEvent`.
Is this class renamed or it migrates to another package?
https://elsa-workflows.github.io/elsa-core/docs/guides-document-approval

![](http://pic.codepie.fun/img/20210111163922.png)

![](http://pic.codepie.fun/img/20210111162836.png)

![](http://pic.codepie.fun/img/20210111163550.png)

Regards.

**Comment by lzw5399** [comment]
Found that is `ReceiveHttpRequest`, it's better to update the docs to avoid confusion for beginners

**Comment by sfmskywalker** [comment]
You're right. Thanks for reporting the issue!
