### ISSUE TITLE
[ENH] Add UseMySql parameter

### ISSUE THREAD

**Issue by sfmskywalker** [elsa-workflows/elsa-core#5633]
Allow MySQL to use AutoDetect & hard coded version via overload.

See https://github.com/elsa-workflows/elsa-core/commit/8a9e00d92d9fa734f97a08063a47cbf3f8318d66#commitcomment-143208006

**Comment by 4lexKislitsyn** [comment]
Hi. What do you think about adding method with `ServerVersion` parameter and use old method with autodetect?

```csharp
public static DbContextOptionsBuilder UseElsaMySql(this DbContextOptionsBuilder builder, Assembly migrationsAssembly, string connectionString, ElsaDbContextOptions? options = default, Action<MySqlDbContextOptionsBuilder>? configure = default) =>
        UseElsaMySql(builder, migrationsAssembly, connectionString, ServerVersion.AutoDetect(connectionString), options, configure);

public static DbContextOptionsBuilder UseElsaMySql(this DbContextOptionsBuilder builder, Assembly migrationsAssembly, string connectionString, ServerVersion serverVersion, ElsaDbContextOptions? options = default, Action<MySqlDbContextOptionsBuilder>? configure = default) => ...
```

If it's appropriate solution I can open PR today.

**Comment by 4lexKislitsyn** [comment]
There is already PR to reverse changes about autodetect (#5621). May be author can add overload that I suggested.

**Comment by sfmskywalker** [comment]
@4lexKislitsyn Makes sense. @raymonddenhaan do you want to update your PR, or shall we ask @4lexKislitsyn to open a new one?

**Comment by raymonddenhaan** [comment]
@4lexKislitsyn, @sfmskywalker I Updated the PR with the overload

**Comment by sfmskywalker** [comment]
Perfect, thanks @raymonddenhaan & @4lexKislitsyn  !
