### ISSUE TITLE
[BUG]Why does the If activity in Elsa 3.1.3 designer only have the Condition attribute and not the Then and Else attributes?

### ISSUE THREAD

**Issue by shxylgithub** [elsa-workflows/elsa-core#5677]
Elsa 3.1.3 designer seems to have an issue where Then and Else properties are not visible in the designer interface.
Why does the If activity in Elsa 3.1.3 designer only have the Condition attribute and not the Then and Else attributes?
![If](https://github.com/elsa-workflows/elsa-core/assets/171897414/29dc5836-fcfd-4e86-9c49-771da9d0d977)

**Comment by sfmskywalker** [comment]
Let's keep the conversation in one place: https://github.com/elsa-workflows/elsa-core/issues/5683
