### ISSUE TITLE
[CHORE] Why does the If activity in Elsa 3.1.3 designer only have the Condition attribute and not the Then and Else attributes?

### ISSUE THREAD

**Issue by shxylgithub** [elsa-workflows/elsa-core#5680]
Elsa 3.1.3 designer seems to have an issue where Then and Else properties are not visible in the designer interface.
Why does the If activity in Elsa 3.1.3 designer only have the Condition attribute and not the Then and Else attributes?
![If](https://github.com/elsa-workflows/elsa-core/assets/171897414/675ecb4d-4dd3-490b-a21a-fedfcd8830cd)

**Comment by jdevillard** [comment]
Hello, 

The IF Activity shows you 2 buttons in the Activity Display which are sub-flowchart. If you click on the `Then Button` or `Else Button ` you will go in a sub flow chart when you can implement your logic dragging/dropping new activity.

So you only need the Condition Attribute. If the result of this attribute is `true`  you will go in the Then Flowchart , if `else` you'll go in the the Else. 
And then the done connexion allow you to connect to next activities after executing the `Then/Else flowcharts`

**Comment by sfmskywalker** [comment]
@shxylgithub Let's keep the conversation in one place when we discuss a given topic: https://github.com/elsa-workflows/elsa-core/issues/5683 Thanks for understanding.
