### ISSUE TITLE
Newtonsoft.Json.JsonReaderException exception loading workflow definition page

### ISSUE THREAD

**Issue by andrzejswiatek** [elsa-workflows/elsa-core#572]
I am using Elsa 1.5.2.1284. The unhandled exception occurs during reading the workflow definition list on Elsa Dashboard.

_An exception occurred while iterating over the results of a query for context type 'Elsa.Persistence.EntityFrameworkCore.DbContexts.SqliteContext'.
      Newtonsoft.Json.JsonReaderException: Error reading JObject from JsonReader. The current JsonReader item is not an object:_

Please find workflow included:
[workflow. txt](https://github.com/elsa-workflows/elsa-core/files/5820243/workflow.txt)

and exception stack trace:
[workflow_exception.txt](https://github.com/elsa-workflows/elsa-core/files/5820252/workflow_exception.txt)

**Comment by afacanerman** [comment]
Hi, I had the same issue with my first workflow, created via the dashboard. I cleared DB manually and tried again the issue was resolved. It might be the dashboard specific error. Unfortunately couldn't re-produce again.

**Comment by craigfowler** [comment]
@andrzejswiatek are you able to reproduce at-will or is it intermittent for you too?
Glancing at the stack trace it looks like Elsa was trying to read exception/error data from a workflow instance and failed :thinking: 
I wonder if the exception & stack trace you have posted is actually _the real root cause_ or not.

@sfmskywalker - what do you think about this one?  It's 1.x and the stack trace proves that _something really did go wrong_ but I'm not sure we have enough here to repro this ourselves.

**Comment by sfmskywalker** [comment]
I have seen first-hand that there are pretty nasty issues with the serialization story in Elsa 1, for which reason it's been completely revamped (and simplified) in Elsa 2.

Although there might be other issues to be discovered in Elsa 2, I'm pretty confident this one won't return. And in the event it does rear its head, we'll chop it off clean.
