### ISSUE TITLE
[Security] d3-color is vulnerable to ReDoS (Regular Expression Denial of Service)

### ISSUE THREAD

**Issue by marvingreeven** [elsa-workflows/elsa-core#5744]
## Description
"@elsa-workflows/elsa-workflows-studio" depends on "dagre-d3": "^0.6.4", which depends on "d3": "^5.14", which depends on "d3-color": "1". Which is vulnerable to Remote DoS: https://github.com/advisories/GHSA-36jr-mh4h-2g58

dagre-d3 is not maintained anymore (https://github.com/dagrejs/dagre-d3/pull/434):
There is a fork to this project were this security issue got fixed: https://github.com/tbo47/dagre-es

Should we switch from dagre-d3 v0.6 to dagre-d3-es v7

### Version
@elsa-workflows/elsa-workflows-studio v2.14.1

### Logs
``` txt
"vulnerabilities":` {
    "@elsa-workflows/elsa-workflows-studio": {
      "name": "@elsa-workflows/elsa-workflows-studio",
      "severity": "high",
      "isDirect": true,
      "via": [
        "dagre-d3"
      ],
      "effects": [],
      "range": "*",
      "nodes": [
        "node_modules/@elsa-workflows/elsa-workflows-studio"
      ],
      "fixAvailable": false
    },
```

**Comment by sfmskywalker** [comment]
That would be good. Perhaps you want to propose a PR?

**Comment by marvingreeven** [comment]
Already created one :)
#5745

**Comment by sfmskywalker** [comment]
Ah, perfect. Thanks!
