### ISSUE TITLE
Pass complex objects from one activity to the next activity

### ISSUE THREAD

**Issue by SoftwareDesign-Solution** [elsa-workflows/elsa-core#578]
How can I pass complex objects from one activity to the next activity without expressions. Activity 1 output should be usable as input into activity 2.

**Comment by jayachandra21** [comment]
Hi,

If your trying for Custom Activities, then try with following options:

1) In Activity1, pass the your object data into a variable as below:
` Workflowcontext.SetVariable("nameofVariable", objectData);`
2) In Activity2, read the above said variable as:
`var objdata = Workflowcontext.GetVariable("nameofVariable");`

**Comment by sfmskywalker** [comment]
In Elsa 1, the only way is to use expressions or, if you are writing custom activities, to set variables from one activity and read them from another as per @jayachandra21 's example.

In Elsa 2, this feature is supported, where the output of one activity automatically flows into the next one.

**Comment by craigfowler** [comment]
It looks like this issue is either resolved or that at least _there's nothing left to be done about it_.  If you believe I have closed it in error, please re-open.
