### ISSUE TITLE
[BUG] tasks/{taskId}/complete returns 200 , but not work. Elsa Version 3.1.3

### ISSUE THREAD

**Issue by NanjingTony** [elsa-workflows/elsa-core#5785]
1. I have a workflow running with an RunTask activity , after webhook remote method is called , the state of RunTask activity is set to "Suspended"
2.  Later after the external app handled its business , and tried to call "http://localhost:49749/elsa/api/tasks/993600ea982495d/complete" to finish the activity , the api returns http status 200 OK
3.  And then I login to the web interface of Elsa to check the workflow status , found that the activity is still "Suspended" . no luck 

![image](https://github.com/user-attachments/assets/4835cd91-641a-4185-96bc-e8b7630be8ab)
![image](https://github.com/user-attachments/assets/dae57743-e27f-4b8a-a04a-ef20d5a61f6b)

My Elsa version is the latest Elsa 3.1.3:
![image](https://github.com/user-attachments/assets/167f2b1b-ec49-4eea-bbe2-9742d9c4d543)

I refer to the previous issue noting that the bug was fixed after 3.0 release , but it seems to still be there

would you please help me out of this ?? thx a lot

**Comment by Khatib-64** [comment]
It works perfectly for me!

**Comment by NanjingTony** [comment]
I'm going to close this issue now. I found the reason is that I forgot to update the version of Elsa.Api.Client from 3.0.0 to 3.1.3 .
I only upgrade the packages in Elsa.Server project , but forgot to upgrade the ones in Elsa.Studio. And that's all the reasons for this problem .
