### ISSUE TITLE
Elsa with Ninject or AutoFac

### ISSUE THREAD

**Issue by SoftwareDesign-Solution** [elsa-workflows/elsa-core#579]
How can I use Elsa with Ninject or Autofac? I have objects that are registered in Ninject or AutoFac and that I want to use in the activities.

**Comment by jerramieg** [comment]
Autofac is prob. What is use

**Comment by sfmskywalker** [comment]
The same way you use Autofac and Ninject with any other library in .NET Core. Here's [Autofac's documentation](https://autofaccn.readthedocs.io/en/latest/integration/aspnetcore.html#asp-net-core-3-0-and-generic-hosting).

Notice that the documentation describes doing `.UseServiceProviderFactory(new AutofacServiceProviderFactory())` in the `Main` method.

This allows you to simply register Elsa with `IServiceCollection` as you normally would.
I don't know about Ninject, but I imagine a similar, if not the same, approach.

**Comment by craigfowler** [comment]
It looks like this issue is either resolved or that at least _there's nothing left to be done about it_.  If you believe I have closed it in error, please re-open.
