### ISSUE TITLE
The feature 'target-typed object creation' is currently in Preview and *unsupported*.

### ISSUE THREAD

**Issue by Duan112358** [elsa-workflows/elsa-core#581]
```
// src/activities/Elsa.Activities.Http/WorkflowHttpResult.cs
namespace Elsa.Activities.Http
{
    public class WorkflowHttpResult
    {
        public static readonly WorkflowHttpResult Instance = new();
    }
}
```
case build failed in **`dotnet core 3.1`** build failed when build Dockerfile
```
15 65.30 WorkflowHttpResult.cs(5,62): error CS8652: The feature 'target-typed object creation' is currently in Preview and *unsupported*. To use Preview features, use the 'preview' language version. [/app/src/activities/Elsa.Activities.Http/Elsa.Activities.Http.csproj]
```
![image](https://user-images.githubusercontent.com/1957818/105115773-622c4f80-5b04-11eb-84ff-eae0e94d9d26.png)

**Comment by craigfowler** [comment]
Hi @Duan112358 - as of Elsa 1.5 in order to build you will need to be using the .NET 5 SDK.
Although Elsa's core still targets `netstandard2.1`, some of the elective NuGet packages also now target `net5.0`.
