### ISSUE TITLE
[BUG]Elsa.Expressions.Exceptions.TypeConversionException: Failed to deserialize {"$values":["Sequence5"],"_type":"String[]"} to System.Collections.Generic.HashSet`1[System.String]

### ISSUE THREAD

**Issue by shxylgithub** [elsa-workflows/elsa-core#5819]
System.Text.Json.JsonException: A '$values' metadata property must always be preceded by other metadata properties, such as '$id' or '$type'. Path: $.$values | LineNumber: 0 | BytePositionInLine: 11.
         at System.Text.Json.ThrowHelper.ThrowJsonException(String message)
![Uploading jsonerror.png…]()

**Comment by shxylgithub** [comment]
![SendEmail1](https://github.com/user-attachments/assets/58aa42bf-3e74-42d6-8dea-8c76999cdc1e)

**Comment by shxylgithub** [comment]
![jsonerror](https://github.com/user-attachments/assets/a4b39142-6e0c-40be-9734-f6bcd656824b)

**Comment by sfmskywalker** [comment]
Hi @shxylgithub , thanks for reporting! Do you have any steps to reproduce this?

**Comment by sfmskywalker** [comment]
I'll close this issue as resolved, but we'll reopen it in case it is still an issue and we have steps to reproduce. Thanks for your contributions @shxylgithub !

**Comment by MayorSheFF** [comment]
Hi @sfmskywalker,

I use version 3.2.3 and I run into the same issue. Could you please tell me what version has the fix? Thank you.

**Comment by MayorSheFF** [comment]
@shxylgithub,

**3.3.0-rc6 version doesn't have this issue.** Everything works well.

**Comment by sfmskywalker** [comment]
Thanks for that extra tidbit of information @MayorSheFF 👍🏻
