### ISSUE TITLE
[ENH] How to add custom UIHint in Elsa 3

### ISSUE THREAD

**Issue by quytrieu37** [elsa-workflows/elsa-core#5826]
### Enhancement Overview
Hi @sfmskywalker,

I'm trying to create a custom UIHint for my project. 
I have created a TreeUIHint component, implemented a handler, and registered the handler as follows:

TreeUIHint Component
```
public partial class TreeUIHint : StudioComponentBase
{
    [Parameter]
    public DisplayInputEditorContext EditorContext { get; set; } = default!;
}
```
```
<MudTreeView T="string" ReadOnly>
    <MudTreeViewItem Text="Getting Started">
        <MudTreeViewItem Text="Installation" />
    </MudTreeViewItem>
    <MudTreeViewItem Value='"Components"'>
        <MudTreeViewItem Text="Avatar" Value='"MudAvatar"' />
        <MudTreeViewItem Text="Button" Value='"MudButton"' />
    </MudTreeViewItem>
</MudTreeView>
```

The handler:
```
public class TreeUIHintHandler : IUIHintHandler
{
    public bool GetSupportsUIHint(string uiHint) => uiHint == "tree";
    public string UISyntax => WellKnownSyntaxNames.Literal;

    public RenderFragment DisplayInputEditor(DisplayInputEditorContext context)
    {
        return builder =>
        {
            builder.OpenComponent(0, typeof(TreeUIHint));
            builder.AddAttribute(1, nameof(TreeUIHint.EditorContext), context);
            builder.CloseComponent();
        };
    }
}
```
Register handler in `program.cs`
`builder.Services.AddUIHintHandler<TreeUIHintHandler>();`

Issue
On the server, I create an input with UIHint = "tree". 
```
[Input(
        Description = "Test string",
        UIHint = "tree"
    )]
    public Input<string> TestString { get; set; } = default!;
```

However, when I use this activity, the Input tab is blank, and there are no error logs in the console:
![image](https://github.com/user-attachments/assets/1f2cd5cd-b104-4708-a6b0-90d9df51b71e)

Is it possible to add a new UIHint in Elsa 3? If so, what steps might I be missing?
If it is not currently possible, I believe this feature is necessary and should be implemented.
Thank you so much!

**Comment by quytrieu37** [comment]
Here github repo link:
https://github.com/quytrieu37/ElsaSampleBlazorAssembly

**Comment by Suchiman** [comment]
The code looks roughly right to me but i believe you're missing a `_Imports.razor` in your `Components` directory with the following contents:
```razor
@using Microsoft.AspNetCore.Components.Web
@using Elsa.Studio.Components
@using MudBlazor
@using MudExtensions
```
i assume that without that, it just interprets the elements inside `TreeUIHint.razor` as raw html.

**Comment by quytrieu37** [comment]
Hi there, thank you for your support. That’s exactly what happened. I was able to resolve the issue on my own.
Initially, I created a `ClassLibrary`for the UIHint project, but after switching to a `RazorClassLibrary` and importing the related libraries in `_Imports.razor`, the issue was resolved.
