### ISSUE TITLE
哎，步步错，没有教程？？？

### ISSUE THREAD

**Issue by ilivecoding** [elsa-workflows/elsa-core#583]
![图片](https://user-images.githubusercontent.com/7898334/105270479-d16f7580-5bd0-11eb-9291-783e6fc5c753.png)

**Comment by ilivecoding** [comment]
PM> SET EF_CONNECTIONSTRING=Server=localhost;Database=Elsa;User=sa;Password=123;
Database=Elsa : 无法将“Database=Elsa”项识别为 cmdlet、函数、脚本文件或可运行程序的名称。请检查名称的拼写，如果包括路径，请确保路径正确，然后再试一次。
所在位置 行:1 字符: 42
+ SET EF_CONNECTIONSTRING=Server=localhost;Database=Elsa;User=sa;Passwo ...
+                                          ~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (Database=Elsa:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException
 
User=sa : 无法将“User=sa”项识别为 cmdlet、函数、脚本文件或可运行程序的名称。请检查名称的拼写，如果包括路径，请确保路径正确，然后再试一次。
所在位置 行:1 字符: 56
+ ... ET EF_CONNECTIONSTRING=Server=localhost;Database=Elsa;User=sa;Passwor ...
+                                                           ~~~~~~~
    + CategoryInfo          : ObjectNotFound: (User=sa:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException
 
Password=123 : 无法将“Password=123”项识别为 cmdlet、函数、脚本文件或可运行程序的名称。请检查名称的拼写，如果包括路径，请确保路径正确，然后再试一次。
所在位置 行:1 字符: 64
+ ... CONNECTIONSTRING=Server=localhost;Database=Elsa;User=sa;Password=123;
+                                                             ~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (Password=123:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException
 
PM>

**Comment by Duan112358** [comment]
**`SET EF_CONNECTIONSTRING="Server=localhost;Database=Elsa;User=sa;Password=123;"`** @ilivecoding

**Comment by Hi7t** [comment]
@Duan112358  不能加引号的
@ilivecoding  此命令是在cmd下执行的 并非在vs中执行 参考 https://docs.microsoft.com/en-us/ef/core/managing-schemas/migrations/providers?tabs=dotnet-core-cli 查看 cli和vs中命令的区别
并且参考 https://github.com/elsa-workflows/elsa-core/tree/master/src/persistence/Elsa.Persistence.EntityFrameworkCore 
以及 https://www.jianshu.com/p/9c74ff7da451 解决
如果是要用mysql 目前此版本可能存在bug 需要修改 Elsa.Persistence.EntityFrameworkCore项目下 MySqlContextFactory.cs中
 optionsBuilder.UseMySql(
                            new MySqlServerVersion(ServerVersion.AutoDetect(connectionString)),
                            x => x.MigrationsAssembly(migrationAssembly)
                        );
改为 
 optionsBuilder.UseMySql(connectionString, 
                new MySqlServerVersion(new Version(8, 0, 22)), // use MariaDbServerVersion for MariaDB 版本号mysql select version()
                        mySqlOptions => mySqlOptions
                            .CharSetBehavior(CharSetBehavior.NeverAppend)
                            )
demo如果运行的是MySQL也要修改.

**Comment by ilivecoding** [comment]
@Hi7t 我试试。

**Comment by iget** [comment]
dotnet tool install --global dotnet-ef
