### ISSUE TITLE
[BUG] Running workflow instances not visible in workflowinstancestore

### ISSUE THREAD

**Issue by bambitasc** [elsa-workflows/elsa-core#5832]
## Description
We use Elsa only in Code with custom workflows. So we have a own Overview over Workflows that are Completed or Running. We updated now to Elsa 3.1.3. After some rewriting everything works like before except that we only see workflow instances when they are finished. It seems that the workflow instances are only persisted when they are finished. In the sample Docker Application with Elsa Designer the running/suspended workflows are visible in the List. Also in the older Version of Elsa it gave us all the Workflow instances also the currently running ones. I tried to figure out if i'm missing a setting somewhere to make it so the workflow instance is persisted from the begining.

## Steps to Reproduce
I have made a simple console application to Reproduce this:
```
using Elsa.EntityFrameworkCore.Common;
using Elsa.EntityFrameworkCore.Extensions;
using Elsa.EntityFrameworkCore.Modules.Management;
using Elsa.EntityFrameworkCore.Modules.Runtime;
using Elsa.Extensions;
using Elsa.Workflows;
using Elsa.Workflows.Activities;
using Elsa.Workflows.Attributes;
using Elsa.Workflows.Contracts;
using Elsa.Workflows.Management.Contracts;
using Elsa.Workflows.Management.Filters;
using Elsa.Workflows.Models;
using Elsa.Workflows.Runtime.ActivationValidators;
using Microsoft.AspNetCore.Builder;
using Microsoft.EntityFrameworkCore.Diagnostics;
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.Hosting;

namespace Elsa3
{
    public class Program
    {
        static async Task Main(string[] args)
        {
            // Setup service container.
            var builder = Host.CreateApplicationBuilder();
            builder.Configuration.AddJsonFile("appsettings.json");
            var connectionString = "Server=localhost\\sqlexpress;Database=Test;Trusted_Connection=True;MultipleActiveResultSets=True;Encrypt=false";
            // Add Elsa services to the container.
            builder.Services.AddElsa(elsa =>
            {
                elsa
                .UseWorkflowRuntime(configure => configure
                                .UseEntityFrameworkCore(ef =>
                                {
                                    ef.UseSqlServer(connectionString, new ElsaDbContextOptions { SchemaName = "MyElsa" });
                                    // HACK: Ignore Warning:
                                    // The query uses a row limiting operator ('Skip'/'Take') without an 'OrderBy' operator. This may lead to unpredictable results.
                                    // If the 'Distinct' operator is used after 'OrderBy', then make sure to use the 'OrderBy' operator after 'Distinct' as the ordering would otherwise get erased.
                                    var originalOptionsBuilder = ef.DbContextOptionsBuilder;
                                    ef.DbContextOptionsBuilder = (provider, options) =>
                                    {
                                        originalOptionsBuilder(provider, options);
                                        options.ConfigureWarnings(w => w
                                            .Ignore(CoreEventId.RowLimitingOperationWithoutOrderByWarning)
                                        );
                                    };
                                })
                            )
                .UseWorkflowManagement(management => management
                                .UseEntityFrameworkCore(ef =>
                                {
                                    ef.UseSqlServer(connectionString, new ElsaDbContextOptions { SchemaName = "MyElsa" });

                                    // HACK: Ignore Warning:
                                    // The query uses a row limiting operator ('Skip'/'Take') without an 'OrderBy' operator. This may lead to unpredictable results.
                                    // If the 'Distinct' operator is used after 'OrderBy', then make sure to use the 'OrderBy' operator after 'Distinct' as the ordering would otherwise get erased.
                                    var originalOptionsBuilder = ef.DbContextOptionsBuilder;
                                    ef.DbContextOptionsBuilder = (provider, options) =>
                                    {
                                        originalOptionsBuilder(provider, options);
                                        options.ConfigureWarnings(w => w
                                            .Ignore(CoreEventId.RowLimitingOperationWithoutOrderByWarning)
                                        );
                                    };
                                })
                            )
                .UseQuartz()
                .UseScheduling(configure => configure.UseQuartzScheduler());
            });
            builder.Services.AddHostedService<WorkflowService>();
            // Build the service container.
            var app = builder.Build();
            app.Run();
        }
    }

    public class WorkflowService : IHostedService
    {
        private readonly IWorkflowRunner _workflowRunner;

        public WorkflowService(IWorkflowRunner workflowRunner)
        {
            _workflowRunner = workflowRunner;
        }
        public async Task StartAsync(CancellationToken cancellationToken)
        {
            var workflow = new SampleWorkflow();
            // Execute the workflow.
            await _workflowRunner.RunAsync(workflow);
        }

        public Task StopAsync(CancellationToken cancellationToken)
        {
            return Task.CompletedTask;
        }
    }

    public class SampleWorkflow : WorkflowBase
    {
        protected override void Build(IWorkflowBuilder builder)
        {
            builder.Name = "Sample Workflow";
            builder.WithActivationStrategyType<SingletonStrategy>();
            var currentValue = builder.WithVariable<int>();
            builder.Root = new Sequence
            {
                Activities = {
                    new WriteLine("Start Workflow"),
                    new For(1,10,1){
                        Body =new Sequence{
                            Activities={
                              new CurentRunningWorkflows{
                                CurrentValue = new Input<int>(currentValue)
                              },
                            }
                        },
                        CurrentValue = new Output<object?>(currentValue)
                    },
                    new WriteLine("End Workflow"),
                }
            };
        }
    }

    public class CurentRunningWorkflows : CodeActivity
    {
        [Input]
        public Input<int> CurrentValue { get; set; }
        protected override async ValueTask ExecuteAsync(ActivityExecutionContext context)
        {
            var workflowInstanceStore = context.GetRequiredService<IWorkflowInstanceStore>();
            var runningWorkflows = await workflowInstanceStore.FindManyAsync(new WorkflowInstanceFilter
            {
                WorkflowStatus = WorkflowStatus.Running
            });
            Console.WriteLine($"Loop Count {CurrentValue.Get(context)}. Current Running Workflow Count: {runningWorkflows.Count()}");
            foreach (var item in runningWorkflows)
            {
                Console.WriteLine($"{CurrentValue.Get(context)} Current Running Workflow: {item.Name}");
            }
        }
    }
}
```

## Expected Behavior
It should Write a 1 for runningWorkflows.Count() and the State of this Workflowinstance should be Running.

## Actual Behavior
I get 0 runningWorkflows.

## Environment
- **Elsa Package Version**: 3.13
- **Operating System**: Windows 10

## Troubleshooting Attempts
Searching for any settings on the Workflow or the EntityFramework settings to make the persistence behave otherwise.

## Additional Context
We cannot change to Dapper for example because we have to set a Schema for the DataTables.

**Comment by sfmskywalker** [comment]
The reason that there's no workflow instance in the database until after the workflow instance has finished is because the WorkflowRunner doesn't persist the workflow instance before executing it.

If you were to dispatch the workflow for execution instead, the dispatcher first creates & persists the workflow instance in the Pending state, and will be executed by a background worker.

However, you don't need to use a dispatcher in order to get your workflow instance persisted; instead you could create and persist the workflow instance manually using the `IWorkflowInstanceManager` service, and then execute it using the workflow runner.

To make this easier, maybe we should consider adding an option to the `IWorkflowRunner` API to control whether or not a workflow instance should be created upfront.

**Comment by bambitasc** [comment]
Sorry for waiting so long to answer. We tried it out like you mentioned above and it works now with showing the workflow. This is how we are doing it now. The only issue now is that we have a workflow with a cron trigger and this works just fine. But when i want to manually trigger the workflow with this method it just register the instance for being executed as soon as the cron expression is true. (This totaly makes sense to me :)) I just wondered if there is a way to start the workflow directly by ignoring the trigger? So we have a workflow that is scheduled but sometimes we need to manually start it between the scheduled time. 

`private async Task StartWorkflowAsync(string name, string jobCode)
{
	using (var scope = _serviceProvider.CreateScope())
	{
		try
		{
			var workflowDefinitionStore = scope.ServiceProvider.GetRequiredService<IWorkflowDefinitionStore>();

			var workflow = await workflowDefinitionStore.FindLastVersionAsync(new WorkflowDefinitionFilter
			{
				DefinitionIds = [name, jobCode],
			}, CancellationToken.None);

			if (workflow == null)
			{
				_logger.Warn($"Workflow '{name}' not found.");
				return;
			}

			var workflowMaterializer = scope.ServiceProvider.GetRequiredService<IWorkflowMaterializer>();
			var workflowInstanceFactory = scope.ServiceProvider.GetRequiredService<IWorkflowInstanceFactory>();
			var workflowInstanceManager = scope.ServiceProvider.GetRequiredService<IWorkflowInstanceManager>();
			var workflowHostFactory = scope.ServiceProvider.GetRequiredService<IWorkflowHostFactory>();
			var workflowRuntime = scope.ServiceProvider.GetRequiredService<IWorkflowRuntime>();

			var materializedWorkflow = await workflowMaterializer.MaterializeAsync(workflow);

			var instance = workflowInstanceFactory.CreateWorkflowInstance(new CreateWorkflowInstanceRequest
			{
				Workflow = materializedWorkflow
			});

			await workflowInstanceManager.SaveAsync(instance, CancellationToken.None);

			var workflowHost = await workflowHostFactory.CreateAsync(instance.DefinitionId, VersionOptions.Published);

			await workflowHost!.StartWorkflowAsync(new StartWorkflowHostParams()
			{
				InstanceId = instance.Id,
				CorrelationId = instance.CorrelationId
			});

			var workflowState = workflowHost.WorkflowState;

			await workflowInstanceManager.SaveAsync(workflowState, CancellationToken.None);
		}
		catch (Exception ex)
		{
			_logger.Warn(ex, $"Error executing workflow '{name}'.");
		}
	}
}`
