### ISSUE TITLE
[BUG]What caused Elsa to have a system error?

### ISSUE THREAD

**Issue by captaris** [elsa-workflows/elsa-core#5844]
![errorlog](https://github.com/user-attachments/assets/2eaf7adb-5d09-40f9-ac27-87de7b19ff40)

**Comment by sfmskywalker** [comment]
Can you add more context? What steps precede this exception, and can you provide detailed steps to reproduce and or a sample project?

**Comment by captaris** [comment]
> Can you add more context? What steps precede this exception, and can you provide detailed steps to reproduce and or a sample project?

Teacher: Hello
The steps to reproduce the error are as follows:
1. Elsa version is 3.1.3
2. The example project is: samples/aspnet/Elsa Samples.AspNet.DocumentApproval
3. When the first step is executed on the browser URL, it is successful: Jack approves URL:
https://localhost:5001/elsa/api/events/trigger?t=CfDJ8Amm1KhNgo1IjZyyiHXpQiBi1uTcdREnJre638i2_dOytsq9JzflpEbYTx1QJdLdRtesmOqY8vjGrvQ6PF1 -Xgxhe7tg5h89CnUBhudMVxnmerwYjrvnA8o0bN4LETJNy69Eew7kAKIgUP8Hr-jbjxXHrdU-HOh6SWK09l2FLCdbh9E_XgQnQkfPiSQMLb1soTtxczWGBx7yVUgVseN3HuA
4. The second step is to encounter an error when executing the URL in the browser: Lucy approves URL:
https://localhost:5001/elsa/api/events/trigger?t=CfDJ8Amm1KhNgo1IjZyyiHXpQiBVUjPu4BFx7sV9lTIYHV443npo0wY1QtnHoxTnbYRLat_sTin4nYnn1sJxb_YnDXSeCJwRAQObhWXXZd0OQQF8N1QCYweXJiq -vvs3qcNVMrK9kx7Xxy01kWvoviT08d5jr3zz-kjbj7CvWBi7ICO9cplSKgsuIRa1x7MmxiZYxY1T95REO4eOOOGsXKe5avk
5. When the first person performs approval or rejection in the browser URL, it is successful, but an error occurs when the second person performs approval or rejection in the browser

**Comment by captaris** [comment]
Teacher: Hello

The steps to reproduce the error are as follows:

1. Elsa version is 3.1.3

2. The example project is: samples/aspnet/Elsa Samples.AspNet.DocumentApproval

3. When the first step is executed on the browser URL, it is successful: Jack approves URL:

https://localhost:5001/elsa/api/events/trigger?t=CfDJ8Amm1KhNgo1IjZyyiHXpQiBi1uTcdREnJre638i2_dOytsq9JzflpEbYTx1QJdLdRtesmOqY8vjGrvQ6PF1 -Xgxhe7tg5h89CnUBhudMVxnmerwYjrvnA8o0bN4LETJNy69Eew7kAKIgUP8Hr-jbjxXHrdU-HOh6SWK09l2FLCdbh9E_XgQnQkfPiSQMLb1soTtxczWGBx7yVUgVseN3HuA

4. The second step is to encounter an error when executing the URL in the browser: Lucy approves URL:

https://localhost:5001/elsa/api/events/trigger?t=CfDJ8Amm1KhNgo1IjZyyiHXpQiBVUjPu4BFx7sV9lTIYHV443npo0wY1QtnHoxTnbYRLat_sTin4nYnn1sJxb_YnDXSeCJwRAQObhWXXZd0OQQF8N1QCYweXJiq -vvs3qcNVMrK9kx7Xxy01kWvoviT08d5jr3zz-kjbj7CvWBi7ICO9cplSKgsuIRa1x7MmxiZYxY1T95REO4eOOOGsXKe5avk

5. When the first person performs approval or rejection in the browser URL, it is successful, but an error occurs when the second person performs approval or rejection in the browser













At 2024-07-27 01:59:40, "Sipke Schoorstra" ***@***.***> wrote:

Can you add more context? What steps precede this exception, and can you provide detailed steps to reproduce and or a sample project?

**Comment by sfmskywalker** [comment]
When I run this sample project on the latest code base on the main branch, everything works out as it should. Therefore, I will close this issue as resolved. If you can still reproduce it with the latest version of the code, please let me know. Thank you for your participation!
