### ISSUE TITLE
provide Chinese Language pack?

### ISSUE THREAD

**Issue by Dysheng** [elsa-workflows/elsa-core#5854]
can this project provide other language support?

**Comment by sfmskywalker** [comment]
Hi @Dysheng 

Elsa Studio now supports localization, and we're looking for contributors to help create translations. We use [Weblate](https://hosted.weblate.org/projects/elsa-studio/) to make managing translations simple and collaborative. If you're interested in contributing Chinese translations, please sign up for a Weblate account and share your username or email address with me.

We'd greatly appreciate your help!

**Comment by sfmskywalker** [comment]
Marking this issue as a duplicate of #5346
