### ISSUE TITLE
[BUG] Joins inside loops lead to unexpected behavior

### ISSUE THREAD

**Issue by Nekrosis1** [elsa-workflows/elsa-core#5865]
## Description
When looping over an implicit or explicit join, coming from both sides multiple times, the workflow gets confused.

## Steps to Reproduce
Attached is a Workflow (LoopTestExplicit.json) that does not break, but looking at it in the Tracker reveals that the second join got executed 2x instead of the expected 4x.
Second Workflow (LoopTestImplicit.json) uses an implicit join at that spot, causing the workflow to get stuck.

In the Workflow I discovered this, even with an explicit join, the workflow gets stuck, unfortunately, I was unable to reproduce this without using custom activities and http activities.

1. **Detailed Steps**: Creating a Workflow with a loop, where inside the loop, there is a decision.
This decision should resolve to different answers over multiple loop iterations. The when resolving the decision again like the first time it resolved, something weird happens somewhere, leading to unexpected behavior when joining the two paths together again.

3. **Attachments**:
   - **Workflow JSON**:
[loopTestExplicit.json](https://github.com/user-attachments/files/16539906/loopTestExplicit.json)
[loopTestImplicit.json](https://github.com/user-attachments/files/16539907/loopTestImplicit.json)

4. **Reproduction Rate**: 100%. But severity depends on unknown factors.

5. **Video/Screenshots**: 
![JoinInLoopBug](https://github.com/user-attachments/assets/4bc24557-fa42-4697-92b7-8b34dc8cdd9b)

## Environment
- **Elsa Package Version**: 
Elsa 3.2.0-rc2.1830
Elsa Studio 3.2.0-rc.374
- **Operating System**: Win10.
- **Browser and Version**: Chrome 127.

## Log Output
Include any relevant log output or error messages that might help diagnose the issue.

## Troubleshooting Attempts
Various different combinations of joining back decisions inside loops. When routing the first execution around a join (not hitting it), sometimes it the workflow works better. This was the case in my actual Workflow, but it then gets stuck later, where I am unable to to the routing "hack".

**Comment by rimen** [comment]
We have the same issue with 3.2.

**Comment by jayachandra21** [comment]
Hello @rimen 
I am also facing an same type issue, so did you got any workaround for this issue? i have checked with Elsa 3.2.0 version
Let me know.

**Comment by sfmskywalker** [comment]
Thanks @Nekrosis1 for the detailed description and crafty test workflows! It was instrumental to uncovering the bug, which will be fixed as part of the 3.3 release. With this fix, both the implicit and explicit join workflows that you attached will run to completion.
