### ISSUE TITLE
Elsa workflow integration in AspNet Boilerplate 

### ISSUE THREAD

**Issue by wangadeketan** [elsa-workflows/elsa-core#588]
Hello,
I am trying to integrate Elsa workflow in my boilerplate project following error comes 
```
ERROR 2021-01-22 14:34:08,632 [15   ] nostics.DeveloperExceptionPageMiddleware - An unhandled exception has occurred while executing the request.
System.Reflection.ReflectionTypeLoadException: Unable to load one or more of the requested types.


Could not load type 'Microsoft.EntityFrameworkCore.Metadata.RelationalModelAnnotations' from assembly 
'Microsoft.EntityFrameworkCore.Relational, Version=3.1.9.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'.
Could not load type 'Microsoft.EntityFrameworkCore.Metadata.RelationalPropertyAnnotations' from assembly 
'Microsoft.EntityFrameworkCore.Relational, Version=3.1.9.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'.
Could not load type 'Microsoft.EntityFrameworkCore.Metadata.Internal.RelationalFullAnnotationNames' from assembly 
'Microsoft.EntityFrameworkCore.Relational, Version=3.1.9.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'.
```
.net core version :- 3.1

**Comment by sfmskywalker** [comment]
Might be due to the fact that Elsa 1.5.x uses .NET 5. 

You could try upgrading your project to .NET 5 too, or use Elsa 1.4.x, which targets .NET Core 3.1.

**Comment by carlosmorenoaguilera** [comment]
> Hello,
> I am trying to integrate Elsa workflow in my boilerplate project following error comes
> 
> ```
> ERROR 2021-01-22 14:34:08,632 [15   ] nostics.DeveloperExceptionPageMiddleware - An unhandled exception has occurred while executing the request.
> System.Reflection.ReflectionTypeLoadException: Unable to load one or more of the requested types.
> 
> 
> Could not load type 'Microsoft.EntityFrameworkCore.Metadata.RelationalModelAnnotations' from assembly 
> 'Microsoft.EntityFrameworkCore.Relational, Version=3.1.9.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'.
> Could not load type 'Microsoft.EntityFrameworkCore.Metadata.RelationalPropertyAnnotations' from assembly 
> 'Microsoft.EntityFrameworkCore.Relational, Version=3.1.9.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'.
> Could not load type 'Microsoft.EntityFrameworkCore.Metadata.Internal.RelationalFullAnnotationNames' from assembly 
> 'Microsoft.EntityFrameworkCore.Relational, Version=3.1.9.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'.
> ```
> 
> .net core version :- 3.1

hi, i downgrade everything because I'm using 3.1 too, on my (dot)csproj  i have these packages 

  ```
<PropertyGroup>
    <TargetFramework>netcoreapp3.1</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
	  <PackageReference Include="Elsa" Version="1.2.2.29" />
	  <PackageReference Include="Elsa.Persistence.EntityFrameworkCore" Version="1.2.2.29" />
	  <PackageReference Include="Microsoft.EntityFrameworkCore" Version="3.1.6" />
	  <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="3.1.6">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer.Design" Version="1.1.6" />
    <PackageReference Include="System.ServiceModel.Duplex" Version="4.4.*" />
    <PackageReference Include="System.ServiceModel.Http" Version="4.4.*" />
    <PackageReference Include="System.ServiceModel.NetTcp" Version="4.4.*" />
    <PackageReference Include="System.ServiceModel.Security" Version="4.4.*" />

  </ItemGroup>
```

and works very well, you can downgrade with nuget package manager too, current old version that i use is 1.2.x

**Comment by craigfowler** [comment]
It looks like this issue is either resolved or that at least _there's nothing left to be done about it_.  If you believe I have closed it in error, please re-open.
