### ISSUE TITLE
[BUG] Http Request activity and application/x-www-form-urlencoded

### ISSUE THREAD

**Issue by pvdbk** [elsa-workflows/elsa-core#5888]
## Description

the class `FormUrlEncodedHttpContentFactory` does not work to build a `HttpContent` from standard types

## Steps to Reproduce

In the activity "HTTP Request (flow)", use "application/x-www-form-urlencoded" as "Content Type" and an object (built with the JAVASCRIPT way) or a string as "Content".

![image](https://github.com/user-attachments/assets/06eb938a-e44d-43c4-9e15-0fcd9153f857)

Launching the resulting workflow, you get this error when "Content" is an object.

![image](https://github.com/user-attachments/assets/6c30df26-1c9d-459f-9abe-d0de032844a1)

Or this one if "Content" is a string

![image](https://github.com/user-attachments/assets/66a1e21d-cda7-4132-8a28-47a4dd5aad6b)

**Comment by pvdbk** [comment]
Here is the code of the class in question

```c#
using System.Text.Json;
using System.Text.Json.Nodes;

namespace Elsa.Http.ContentWriters;

/// <summary>
/// A content writer that writes content in the application/x-www-form-urlencoded format. 
/// </summary>
public class FormUrlEncodedHttpContentFactory : IHttpContentFactory
{
    /// <inheritdoc />
    public IEnumerable<string> SupportedContentTypes => new[] { "application/x-www-form-urlencoded" };

    /// <inheritdoc />
    public HttpContent CreateHttpContent(object content, string? contentType = null) => new FormUrlEncodedContent(GetContentAsDictionary(content));

    private static Dictionary<string, string> GetContentAsDictionary(object content) =>
        (content is string or JsonObject
            ? JsonSerializer.Deserialize<Dictionary<string, string>>(JsonSerializer.Serialize(content))
            : (Dictionary<string, string>)Convert.ChangeType(content, typeof(Dictionary<string, string>)))!;
}
```

When `content` is a `string`, it can not work : The string is serialized then deserialized as a dictionary, but the serialized result can only be deserialized as a string.

When `content` is an `ExpandoObject`, it can not work either : `Convert.ChangeType` does not accept this type.

The `JsonObject` type seems is well handled, but does not seem to be an usual activity output type.

**Comment by sfmskywalker** [comment]
@pvdbk thanks for the detailed bug report! This has now been fixed via https://github.com/elsa-workflows/elsa-core/pull/6074

**Comment by jeanbaptistedalle** [comment]
I successfully called an API with x-www-form-urlencoded, maybe I was on an environment with a wrong version
