### ISSUE TITLE
System.InvalidOperationException: The DbContext of type 'EnhancedSqlServerContext' cannot be pooled because it does not have a public constructor accepting a single parameter of type DbContextOptions or has more than one constructor.

### ISSUE THREAD

**Issue by AvtsVivek** [elsa-workflows/elsa-core#590]
I have EnhancedSqlServerContext derived from [SqlServerContext](https://github.com/elsa-workflows/elsa-core/blob/master/src/persistence/Elsa.Persistence.EntityFrameworkCore/DbContexts/SqlServerContext.cs).
The objective here is to add more entities to the context. In the EnhancedSqlServerContext, I have added a User entity. 
After I add the User entity, migration files are successfully created, and database also gets updated and a Users table also gets created. 

But when I run the app, the page does not show up. The Visual Studio 2019 Output window shows the following error.

System.InvalidOperationException: The DbContext of type 'EnhancedSqlServerContext' cannot be pooled because it does not have a public constructor accepting a single parameter of type DbContextOptions or has more than one constructor.

I am not sure the problem is with Elsa or with entity framework.

So my question is how do I add other business entities? In this case I wanted to add a User entity. 
I wanted to replicate [this User Registration example](https://sipkeschoorstra.medium.com/building-workflow-driven-net-core-applications-with-elsa-139523aa4c50) with sql server rather than with Mongo db. In that example, we can see a [user class](https://github.com/elsa-workflows/elsa-samples/tree/master/src/Elsa.Samples.UserRegistration/src/Elsa.Samples.UserRegistration.Web/Models).

For the user registration sample example uses mongo and there we can see adding a new entity is seamless. 
So having a new dbcontext for other business entities is the only option now? Deriving from existing SqlServerContext does not seem to work.

Or am I missing something simple here.

The following details to create the vs 2019 solution to replicate the problem.

1. Created an empty asp.net core 5.0 web app project.
2. Added the following packages. All latest.
     Install-Package Elsa
     Install-Package Elsa.Dashboard
     Install-Package Elsa.Persistence.EntityFrameworkCore
     Install-Package Microsoft.EntityFrameworkCore.Design
     Install-Package Microsoft.EntityFrameworkCore.Tools

The final csproj file looks like this.

    <Project Sdk="Microsoft.NET.Sdk.Web">

      <PropertyGroup>
        <TargetFramework>net5.0</TargetFramework>
      </PropertyGroup>

      <ItemGroup>
        <PackageReference Include="Elsa" Version="1.5.2.1284" />
        <PackageReference Include="Elsa.Dashboard" Version="1.5.2.1284" />
        <PackageReference Include="Elsa.Persistence.EntityFrameworkCore" Version="1.5.2.1284" />
        <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="5.0.2">
          <PrivateAssets>all</PrivateAssets>
          <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
      </ItemGroup>

    </Project>

3. I have attached the entire project folder for your reference. 

4. Finally some of the commands I used for migration and updation of db.

	Add-Migration InitialMigration -o Migrations/SqlServer -Context SqlServerContext
	Add-Migration InitialMigration -o Migrations/EnhancedSqlServer -Context EnhancedSqlServerContext
	Add-Migration InitialMigration -o Migrations/Sqlite -Context SqliteContext

	Update-Database -Context SqliteContext
	Update-Database -Context SqlServerContext
	Update-Database -Context EnhancedSqlServerContext

[Elsa.Guides.Dashboard.WebApp50.zip](https://github.com/elsa-workflows/elsa-core/files/5867602/Elsa.Guides.Dashboard.WebApp50.zip)

**Comment by sfmskywalker** [comment]
I think that this might literally be the issue: **The DbContext of type 'EnhancedSqlServerContext' cannot be pooled because it does not have a public constructor accepting a single parameter of type DbContextOptions or has more than one constructor**

Right now your `EnhancedSqlServerContext` type accepts a `DbContextOptions<SqlServerContext>` constructor argument, but what it needs is the non-generic version: `DbContextOptions`.

But that won't work because Elsa's `SqlServerContext` class too expects `DbContextOptions<SqlServerContext>`.

So what I think we should try is update Elsa's DB context types to accept a non-generic `DbContextOptions` instead of `DbContextOptions<T>`.

I'll give that a try.

**Comment by sfmskywalker** [comment]
I pushed a new release ([1.5.3](https://github.com/elsa-workflows/elsa-core/releases/tag/1.5.3)) which should allow you to update your own `EnhancedSqlServerContext` constructor to accept `DbContextOptions` instead of `DbContextOptions<SqlServerContext>`.

Let me know how it goes.

**Comment by AvtsVivek** [comment]
Thank You. Its working. So far its fine.

For the others benefit I summarize the changes I made as follows.

1. I have updated the packages to the latest version. So the csproj will now have 1.5.3.1369 instead of 1.5.2.1284. The csproj file will look as follows.

    <Project Sdk="Microsoft.NET.Sdk.Web">

      <PropertyGroup>
        <TargetFramework>net5.0</TargetFramework>
      </PropertyGroup>

      <ItemGroup>
        <PackageReference Include="Elsa" Version="1.5.3.1369" />
        <PackageReference Include="Elsa.Dashboard" Version="1.5.3.1369" />
        <PackageReference Include="Elsa.Persistence.EntityFrameworkCore" Version="1.5.3.1369" />
        <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="5.0.2">
          <PrivateAssets>all</PrivateAssets>
          <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
      </ItemGroup>

    </Project>

2. Next I updated my dbcontext to accept a non-generic DbContextOptions instead of DbContextOptions<T>

        public EnhancedSqlServerContext(DbContextOptions dbContextOptions) : base(dbContextOptions) { }

Earlier it was 

        public EnhancedSqlServerContext(DbContextOptions<SqlServerContext> dbContextOptions) : base(dbContextOptions) { }
