### ISSUE TITLE
Garbage Elsa, you haven't helped solve so many problems for so long. What else are you doing with open source?

### ISSUE THREAD

**Issue by zdydev** [elsa-workflows/elsa-core#5919]
Garbage Elsa, you haven't helped solve so many problems for so long. What else are you doing with open source?

**Comment by Thuylinh28** [comment]
yes .
Elsa 3 has a lot of problems but no support staff or any documentation.Doc tutorial is extremely sketchy and incomprehensible

**Comment by sNakiex** [comment]
The documentation can be found here: https://v3.elsaworkflows.io/
On the documentation page there is also a link to the community discord where you can ask questions e.t.c.

**Comment by XuJin186** [comment]
Just open source, not working for you
@zdydev

**Comment by XuJin186** [comment]
It can be seen that there is only one person who has the core contribution, but he is not enough.
