### ISSUE TITLE
[BUG] Elsa 3.2.0  ParallelForEach properties serialization Error  

### ISSUE THREAD

**Issue by Nokecy** [elsa-workflows/elsa-core#5939]
before

`     
   "properties": {
          "$id": "36",
          "ScheduledTagsProperty": {
            "$id": "37",
            "$values": ["4afec036-7d6c-438c-8964-bc19984b7cf1"],
            "_type": "System.Collections.Generic.List\u00601[[System.Guid, System.Private.CoreLib]], System.Private.CoreLib"
          },
          "CompletedTagsProperty": {
            "$id": "38",
            "$values": [],
            "_type": "System.Collections.Generic.List\u00601[[System.Guid, System.Private.CoreLib]], System.Private.CoreLib"
          }
        }

`
after

`
"properties": {
          "$id": "52",
          "ScheduledTagsProperty": {
            "\\\\$values": {
              "$id": "53",
              "$values": ["c7eabb1a-2fe2-4b29-ba7d-9ce710e4cc1c"],
              "_type": "Object[]"
            }
          },
          "CompletedTagsProperty": {
            "\\\\$values": { "$id": "54", "$values": [], "_type": "Object[]" }
          }
        },
`

**Comment by Nokecy** [comment]
#5841

**Comment by Nokecy** [comment]
#5922

**Comment by Nokecy** [comment]
#5819

**Comment by Nokecy** [comment]
@sfmskywalker

**Comment by sfmskywalker** [comment]
Hi @Nokecy , thanks for collecting the related issues! I'll have a look.

**Comment by IbrahimMNada** [comment]
1

**Comment by IbrahimMNada** [comment]
asdasd

**Comment by sfmskywalker** [comment]
I was able to reproduce this issue. Looking into it.

**Comment by sfmskywalker** [comment]
Fixed via 760a3e2cb5a634aee640e78e00a5c87adf6ec6e0

Thanks again @Nokecy for reporting this issue!

**Comment by Nokecy** [comment]
we can release version 3.2.1? @sfmskywalker

**Comment by sfmskywalker** [comment]
I wanted to make this part of 3.3, but given that’s still a ways off, and you probably need this fix for 3.2 stable, we can create a patch release off the 3.2.0 tagged commit. I might have some bandwidth over the weekend to do this.
