### ISSUE TITLE
Customize collection names when using MongoDB

### ISSUE THREAD

**Issue by rosca-sabina** [elsa-workflows/elsa-core#6004]
### Discussed in https://github.com/elsa-workflows/elsa-core/discussions/5977

<div type='discussions-op-text'>

<sup>Originally posted by **rosca-sabina** September 20, 2024</sup>
Hello,

When using MongoDB for workflow management and runtime storage, is there a way to set a custom collection name for the the collections created by Elsa (such as workflow_instances, workflow_definitions etc.)?

I have a scenario where multiple microservices that will use Elsa use the same MongoDB database. So I need a way to keep the Elsa collections used by each service separate, even if they're in the same database.

Thanks!</div>

**Comment by sfmskywalker** [comment]
Thanks for the PR that adds this capability!
