### ISSUE TITLE
[BUG]Multitenancy doesn't work when Entity Framework is used.

### ISSUE THREAD

**Issue by MIC-BO** [elsa-workflows/elsa-core#6029]
## Description
No tenant is applied when Multi tenancy feature is enabled and Entity Framework is used, for example: when you run Elsa.Samples.AspNet.Tenants, Elsa applies no tenant for admin user.

## Steps to Reproduce
1. Edit appsetings.json file of Elsa.Samples.AspNet.Tenants and change the SigningKey to "large-signing-key-for-signing-JWT-tokens"
2. In appsetings.json file add ids to the tenants by repeating the TenantIds, for example:
{
        "id": "19a5f2b0-75e4-45ad-b0ae-fe02d77867d0",
        "TenantId": "19a5f2b0-75e4-45ad-b0ae-fe02d77867d0",
        "Name": "DefaultTenant"
}
3. Run the Elsa.Samples.AspNet.Tenants project.
4. Using Swagger run login endpoint and add this credential: admin/password
5. Authorize Swagger by entering the token returned in the previous step.
6. Using Swagger get all Workflowdefinitions.
7. Check the queries generated by Elsa Server and you will notice that WHERE conditions tries to compare TenantId with null, instead of comparing with the tenant associated to admin account.

## Expected Behavior
DB queries must use the tenant ID associated to admin account instead of null.

## Actual Behavior
Tenants are not properly mapped to accounts due to Tenant Resolvers are not called in Entity Framework implementation.

## Environment
- **Elsa v3.3**: Problems occurs in latest master branch.
- **Windows 11**
- **Chrome 129**

## Troubleshooting Attempts
I fixed the problem by changing the CreateDbContextAsync method in file src\modules\Elsa.EntityFrameworkCore.Common\Store.cs like this:

    private async Task<string?> GetTenantIdAsync(CancellationToken cancellationToken = default)
    {
        var tenantResover = serviceProvider.GetService<ITenantResolver>();
        if (tenantResover == null)
            return null;
        var tenantId = await tenantResover.GetTenantAsync(cancellationToken);
        return tenantId?.TenantId ?? null;
    }

    public async Task<TDbContext> CreateDbContextAsync(CancellationToken cancellationToken = default)
    {
        var dbContext = await dbContextFactory.CreateDbContextAsync(cancellationToken);

        if (dbContext is ElsaDbContextBase)
        {
            var tenantId = await GetTenantIdAsync(cancellationToken);
            (dbContext as ElsaDbContextBase).TenantId = tenantId;
        }

        return dbContext;
    }

It was the less intrusive change.

**Comment by sfmskywalker** [comment]
Hi @MIC-BO , I have pushed some changes last night that should solve the issue that you reported. Please let me know if not. Thank you!

**Comment by MIC-BO** [comment]
hi Sipke ! Thanks, multi tenancy is working as expected now, you rock man !
