### ISSUE TITLE
[BUG] Activation Strategy Not Functioning as Expected

### ISSUE THREAD

**Issue by TimNguyenVN** [elsa-workflows/elsa-core#6053]
Related discussion:  
https://discord.com/channels/814605913783795763/1226493053737631764
https://discord.com/channels/814605913783795763/1298546707440861215

The Activation Strategy in workflows is no longer evaluated. This issue has already been discussed in Discord, but I am creating an issue here to ensure visibility and track progress.

Steps to Reproduce:
1. Create a workflow with two activities:
    - One activity triggered by a crontab every 5 seconds.
    - Another activity introducing a 1-minute delay.
2. Set the Activation Strategy to Singleton.
3. Publish the workflow.

Observations:
- Manual Execution: You can still initiate multiple instances by clicking the "Execute" button.
- Automatic Execution via Cron: Multiple instances are triggered and executed, which is inconsistent with the Singleton description.

![image](https://github.com/user-attachments/assets/e7c91b09-4ca8-47af-8ca6-c56c59cee1e0)
![image](https://github.com/user-attachments/assets/60f326f7-739d-4e62-b0e4-f56b17d51648)

**Comment by sfmskywalker** [comment]
Thanks @TimNguyenVN for reporting! This issue is fixed via https://github.com/elsa-workflows/elsa-core/pull/6076
