### ISSUE TITLE
[FEAT] Add Input Description Filter Class for Customizable Workflow Inputs

### ISSUE THREAD

**Issue by tramhuynhqtx** [elsa-workflows/elsa-core#6082]
### Problem Overview
Related discussion: https://discord.com/channels/814605913783795763/1301407023149092936
Currently, in the UI, the "Inputs" field appears as a dropdown. However, it's unable to set anything to display in the dropdown. I want to configure this field to show only dynamic expressions (by hiding the dropdown).

### Proposed Solution
Implement an input description filter class that enables the app to customize the "Inputs" field display, such as showing only dynamic expressions as needed.

**Comment by taihangyishui** [comment]
请参考这 ，不知道对你是否有用[elsa-samples\src\aspnet\Elsa.Samples.AspNet.CustomUIHandler](https://github.com/elsa-workflows/elsa-samples/tree/main/src/aspnet/Elsa.Samples.AspNet.CustomUIHandler)

**Comment by mathijs-dumon** [comment]
I believe this is a bug in the IPropertyUIHandlerResolver implementation

the code of the default implementation only checks the UIHint on the custom InputAttribute - so if you don't specify that hint manually no select options are generated:
![image](https://github.com/user-attachments/assets/62036b32-3a88-4c9e-ad47-681fa21871a7)

This wouldn't be a big deal on its own, but later on in the activity describer (second red box) there is a call to the private static method GetUIHint which sets the UI hint to a drop down for some property types (even if you did not manually specify this).
![image](https://github.com/user-attachments/assets/74e2f5c5-28eb-4171-9022-658e9e5f4724)

I think the PropertyUIHandlerResolver should also use this approach - changing the PropertyUIHandlerResolver code to something like this:
![image](https://github.com/user-attachments/assets/dedefa93-4275-4315-891c-e8e2b9fc77e2)

solves the problem - tested this by replacing the class with the customized version I took this screenshot from.

I should have the time next week to provide a PR with a proper fix.
