### ISSUE TITLE
[GuideLine] How to increase the CommandTimeout of RunTimeElsaDbContext

### ISSUE THREAD

**Issue by david-x-chen** [elsa-workflows/elsa-core#6088]
In recent months, the db command of inserting records to table [WorkflowExecutionLogRecords] is alwasy timeout. 

In the log, the CommandTimeout is 30s. How could we increase this CommandTimeout to more than 30s?

**Comment by sfmskywalker** [comment]
It looks like we missed providing an argument to the surface-level extension methods to help with that. To work around it, for now, is to apply the underlying calls from your Program.cs. For example, the following snippet comments out the default way of configuring the workflow runtime with EF Core and SQL Server, and instead configures the feature directly (which does expose a delegate for configuring the necessary options):

```csharp
//ef.UseSqlServer(sqlServerConnectionString, new ElsaDbContextOptions);
var migrationsAssembly = typeof(Elsa.EntityFrameworkCore.SqlServer.RuntimeDbContextFactory).Assembly;
var connectionString = sqlServerConnectionString;
ef.DbContextOptionsBuilder = (_, db) => db.UseElsaSqlServer(migrationsAssembly, connectionString, null, configure => configure.CommandTimeout(60000));
```

Let's keep this issue open as a reminder to expose the DbContextOptions configuration delegate from the commented out extension method.
