### ISSUE TITLE
[BUG]This version of MySQL doesn't yet support 'LIMIT & IN/ALL/ANY/SOME subquery'

### ISSUE THREAD

**Issue by EthanZqh** [elsa-workflows/elsa-core#6096]
The MySQL server version is community-based mysql-8.0.30-winx64 or community-based mysql-9.0.1-winx64
Limit&IN/ALL/ANY/OME subqueries are not yet supported
Solution problem: 1. Which MySQL version supports the "Limit&IN/ALL/ANY/OME subquery" query?
2. It is to modify the nested source code query, but I cannot modify the Elsa source code. I am referencing the Elsa Dll dynamic library.

![elsa-mysql-err](https://github.com/user-attachments/assets/90d0d603-7052-4e23-a477-4a3d6b579fff)

**Comment by sfmskywalker** [comment]
I tried with Docker container `mysql:9.1.0`, which works well.
If you need to support an older version of MySql, you can always generate your own EF Core migration files. Basically, copy the `Elsa.EntityFrameworkCore.MySql` project, rename the project and its classes and methods to be your own, and update the `MySqlDesignTimeDbContextFactory` class to use the version of MySQL that you want to use.

**Comment by sfmskywalker** [comment]
I just noticed you had already posted this exact same issue here: #6091
I will close that one, since this issue now contains some feedback.

Please refrain from posting the same issues multiple times. Thank you.

**Comment by sfmskywalker** [comment]
Hi @EthanZqh , you don't need to change the source code. Instead, you can add your own class library project that contains the necessary migrations.

**Comment by sfmskywalker** [comment]
See #6126
