### ISSUE TITLE
[BUG]Unable to solve the error problem of MySQL 'Limit&IN/ALL/ANY/OME subquery' by changing the MySQL version

### ISSUE THREAD

**Issue by EthanZqh** [elsa-workflows/elsa-core#6099]
MySQL Server Community mysql-8.0.30-winx64 or Community mysql-9.0.1-winx64 version
The 'Limit&IN/ALL/ANY/OME subquery' is not yet supported, so modifying the version cannot solve the existing problem, and can only be resolved by modifying the Elsa source code.
I am modifying the nested source code query, but I am unable to modify the Elsa source code. I am referencing the Elsa Dll dynamic library.
![elsa-mysql-err](https://github.com/user-attachments/assets/9e7bf919-86f0-4677-a62c-d2bdd1920dc7)

**Comment by sfmskywalker** [comment]
One way to modify Elsa's source code is to submit a PR that includes support for your version of MySQL.
Another way is to create your own module. You could copy an existing one and make changes as necessary.

**Comment by sfmskywalker** [comment]
This is related to (if not the same as) #6096
