### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by houtianxi** [elsa-workflows/elsa-core#6111]
## Description
 Compiling source code prompts an error message：
“Unable to find package WebhooksCore. No packages exist with this id in source(s): Webhooks Core Preview. PackageSourceMapping is enabled, the following source(s) were not considered: C:\Program Files\dotnet\library-packs, Elsa 3 Preview, NuGet official package source.”

How can  solve it?

**Comment by sfmskywalker** [comment]
Looks like I forgot to add the feed to the webhooks core preview package. I just pushed an update to the main branch. If you pull from that and rebuild, it should work.

**Comment by houtianxi** [comment]
Thanks.
