### ISSUE TITLE
Method Naming Error: UseMySql Should Be UseOracle in OracleProvidersExtensions Class

### ISSUE THREAD

**Issue by vdaular** [elsa-workflows/elsa-core#6113]
**Summary**
In the OracleProvidersExtensions class, Elsa.EntityFrameworkCore.Oracle module, methods are incorrectly named UseMySql instead of UseOracle. This results in misleading method names that cause errors when configuring Entity Framework Core to use Oracle as the database provider.

**Steps to Reproduce**
1. Attempt to use the UseMySql methods in OracleProvidersExtensions for configuring Oracle as the database provider.
2. Observe the method name inconsistency with the intended functionality of connecting to Oracle rather than MySQL.

**Expected Outcome**
The method names should be UseOracle to clearly indicate they are intended for configuring Oracle as the database provider.

**Actual Outcome**
The methods are named UseMySql, which suggests they are designed for MySQL, causing confusion and possibly incorrect configuration.

**Proposed Solution**
Rename all instances of UseMySql in the OracleProvidersExtensions class to UseOracle to match the intended database provider.

**Notes**
This bug may be due to a copy-paste oversight, where method names were not updated to reflect the Oracle-specific implementation. Additionally, migrations for versions prior to v3.3 are not available for Oracle, as they were restored for other providers.

**Comment by sfmskywalker** [comment]
You're absolutely right, this is a copy-paste artefact. Thanks for reporting!

**Comment by sfmskywalker** [comment]
Fixed via 8502165dcca709daab57bc1f64b890f72f4b5fc5
