### ISSUE TITLE
Collections with 20k rows and beyond slow down /Elsa/workflow-definition

### ISSUE THREAD

**Issue by Zengage** [elsa-workflows/elsa-core#612]
We had created a custom activity which reads records from another API. This is a reporting API which can give us 20k records an beyond which we pass into the out-of-box foreach Activity.
We noticed that the whole collection is stored in the Scope column in WorkflowInstances and the variables seem to get loaded and parsed when going to /Elsa/workflow-definition although variables cannot be inspected anywhere.
I have not tested enough to see at which record count it slows down performance significantly.

Is there a way to not store the variables of such size in scope or is there another way to work around this?

**Comment by sfmskywalker** [comment]
I can see how that is a problem indeed. Perhaps there's no need to store a copy of the collection in the first place. Instead, it should be up to the workflow definition to decide how the collection to iterate on is set (i.e. if it should be retrieved from a cache or not). 

The way the ForEach activity works is that after each iteration, the ForEach activity gets scheduled again so it can determine if it needs to iterate again or if it reached the end of the list. The thing to note here is that as the ForEach activity gets scheduled, its properties are set again. In your case this is relevant, as it might mean it would call out to your API before each new iteration. Which means you might want to store the list returned from the API in some cache.

I will push a change to ForEach that removes the persistence of the collection in internal activity state. Just keep in mind the above.

**Comment by sfmskywalker** [comment]
ForEach activity change: e3bb394a03bc609b749c41f7a2ed3783c9abf9ee
ForEach sample project: https://github.com/elsa-workflows/elsa-core/commit/b18dff82cd4df61ade301123adb652c8ad7b5248
