### ISSUE TITLE
How to generate Elsa EF Core migration files?

### ISSUE THREAD

**Issue by EthanZqh** [elsa-workflows/elsa-core#6121]
I copied Elsa Entity Framework Core. MySQL project, and update MySqlDesignTimeVNet Factory class to use the MySQL version I want to use. How to generate Elsa EF Core migration files?
![migrations](https://github.com/user-attachments/assets/85d84844-d64a-40eb-9c87-a0543cb96b11)

**Comment by sfmskywalker** [comment]
@EthanZqh I’ve noticed several duplicate issues being created, and I kindly ask again to consolidate your input into a single issue. This helps keep the project organized and ensures we can address your concerns effectively. Please take this opportunity to combine all relevant points into one issue. If duplicate issues continue to be submitted, I may need to take further action, including restricting access, to maintain the project’s workflow. Thank you for your understanding.
