### ISSUE TITLE
[BUG] HTTP Endpoint URL

### ISSUE THREAD

**Issue by jayachandra21** [elsa-workflows/elsa-core#6128]
## Description
**HttpEndPoint** activity referring wrong URL
![image](https://github.com/user-attachments/assets/d4957260-4d10-49df-b79b-12247aaae839)

## Steps to Reproduce

1. **Detailed Steps**: 

- Hosted the Elsa application in the IIS as below path 
https://servername/new/WorkflowApp/

- Configured the appsetting.json as below
"Http": {
    "BaseUrl":"https://servername/new/WorkflowApp/",
    "BasePath":"/api/workflows"
  }

- Http End point the path shows as the **`https://servername/api/workflows/`**  but it suppose to show path as `https://servername/new/WorkflowApp/api/workflows/ `

2. **Reproduction Rate**: 
"every time"

## Expected Behavior
It suppose to show path URL as `https://servername/new/WorkflowApp/api/workflows/ `

## Actual Behavior
It suppose to show path URL as `https://servername/new/WorkflowApp/api/workflows/ `

## Environment
- **Elsa Package Version**: 3.2.3 Elsa core and 3.2.2 Elsa Studio
- **Operating System**: Windows server 2019
- **Browser and Version**: Chrome 130 and Edge

## Troubleshooting Attempts
1. Updated the "BaseUrl":"https://servername/ and "BasePath":"/api/workflows/new/WorkflowApp"
In this case HttpEndPoint activity referring correct URL(https://servername/new/WorkflowApp/api/workflows/) but when calling this API from api tools like Postman getting the 404 error.
![image](https://github.com/user-attachments/assets/d1e6adf2-e0bd-45fa-945c-c35e0d85a015)

**Comment by sfmskywalker** [comment]
Fixed via https://github.com/elsa-workflows/elsa-core/pull/6141

Thanks for the detailed report 👍🏻

**Comment by jayachandra21** [comment]
I have verified URL trimming logic in the HTTP endpoint using the latest preview packages(Elsa 3.3.0-preview.2368 and Elsa Studio 3.3.0-preview.659).

But **HTTPEndpoint** shows the up to 1 level but now appears the full URL as described in the the steps to reproduce.

Configured the appsetting.json as below
"Http": {
"BaseUrl":"https://servername/new/WorkflowApp/",
"BasePath":"/api/workflows"
}
![image](https://github.com/user-attachments/assets/6e16288b-7170-475e-9879-4dd48fe054a1)
