### ISSUE TITLE
Dynamic Drop Down Fields for Elsa 2 Designer

### ISSUE THREAD

**Issue by sfmskywalker** [elsa-workflows/elsa-core#616]
In addition to the "static" field types such as **Text** and **List**, we need the ability for developers to provide their own source of list items at runtime.

**Comment by mohdali** [comment]
I totally agree, I think it needs to further generalized to a property editor concept. This will also pave the way for adding validation and possibly auto complete.

The current implementation in Elsa 1 is very limiting and requires static initialization of the field list, which makes it difficult to utilize services from the DI container.

**Comment by sfmskywalker** [comment]
I've started work on this and now works for the dropdown list control. The infrastructure is in place, so it's easy to also update the check-list and multi-text controls. Will work on that tomorrow.

To provide runtime list options at runtime, you need to implement these two interfaces:

`IActivityPropertyOptionsProvider` and `IRuntimeSelectListItemsProvider`.

The first one returns a settings object, which includes the provider type that provides the items.

I will probably simplify this a little bit for the user so that they would only have to implement one interface.

**Comment by sfmskywalker** [comment]
This sample activity shows how it works: https://github.com/elsa-workflows/elsa-core/blob/feature/elsa-2.0/src/samples/server/Elsa.Samples.Server.Host/Activities/VehicleActivity.cs

Note that although I implemented the interfaces on the activity, you are not required to do so if you prefer to provide items from a different class. 

Also note that I hardcoded a string array for demo purposes. In real-world scenarios, you will probably inject some service or repository to get data from e.g. an API or DB.

**Comment by jdevillard** [comment]
You rocks , will test this tomorrow !

**Comment by sfmskywalker** [comment]
This feature is now available.

**Comment by srihariraovadlani** [comment]
sfmskywalker, can you please share code snippet on how to implement the IActivityPropertyOptionsProvider and IRuntimeSelectListItemsProvider interfaces? struggling to get done from last few days. 
Thank you very much for your help.
