### ISSUE TITLE
All versions of MySQL currently do not support nested queries for 'Limit&IN/ALL/ANY/OME'

### ISSUE THREAD

**Issue by EthanZqh** [elsa-workflows/elsa-core#6179]
@sfmskywalker Teacher, I have tried the Elsa server console N times and was able to recover from this issue. This problem has been bothering me for a long time, causing me to be unable to continue moving forward. I have searched online for a lot of information on how to solve this problem, all of which were achieved by modifying nested code.
All versions of MySQL currently do not support nested queries for 'Limit&IN/ALL/ANY/OME'. Error resolution:
1. Nesting this one more layer seems to solve the problem, for example:
delete from table where uid='6'and id NOT IN (select x.id from ( select id from table where uid='6' order by id desc LIMIT 3) as x)

**Comment by r-kernberger** [comment]
Phew, I also ran into this and wasted some hours. 
It is fixed in v3.3.0-rc3 (available in nuget.org as pre-release)

I stumbled upon it when an Exception in this method occured:
Elsa.EntityFrameworkCore.Modules.Runtime.EFCoreWorkflowInboxMessageStore.DeleteManyAsync

**Comment by sfmskywalker** [comment]
@EthanZqh Happy to hear you were able to work through it 👍🏻
