### ISSUE TITLE
[BUG] Variable API throws BadRequest when type mismatch

### ISSUE THREAD

**Issue by jeanbaptistedalle** [elsa-workflows/elsa-core#6193]
## Description
Set variable to a value that doesn't match his definition will success but the instance will not be displayed correctly. 

## Steps to Reproduce
1. Create a workflow with some variables, like a variable called "Var1" of type Int32. 
2. In a javascript activity, set this variable with some value that doesn't match the type. For our business case, that could happend when the data I got from elsewhere are not as I expected.
3. Run the workflow. It will run successfully.
4. Try to display the instance, the variable API will throw a badrequest exception and the instance will not be successfully display.

## Screenshots

https://github.com/user-attachments/assets/3be4db4f-6950-4489-995d-322f600f2d67

## Expected Behavior
I'm not sure what is the good way to fix it. The variable API result seems to be correct : the type mismatch with the value. But the instance is successfull and then cannot be display. Maybe that's more when the variable is set that a failure should happend to let user see the type mismatch in the variable instance ?

**Comment by sfmskywalker** [comment]
PS. Nice catch 👍🏻

**Comment by sfmskywalker** [comment]
Fixed via https://github.com/elsa-workflows/elsa-core/pull/6207
