### ISSUE TITLE
3.3.0-rc-3 => Elsa.Retention.Options: Missing SweepInterval

### ISSUE THREAD

**Issue by r-kernberger** [elsa-workflows/elsa-core#6194]
In the class Elsa.Retention.Options.CleanupOptions of package Retention, there is missing an important setting, which has been available in prior versions of the retention module

=> SweepInterval

With this  settting it has been possible to define how often the Retention Job is running (every x days, hours, minutes).

Now with this settings missing, there is the default value of every 4 hours. Which is especially for development / testing not good.

Will this setting be available in v3.3? Has this been removed on purpose?

**Comment by jayachandra21** [comment]
Hello @r-kernberger, I have observed the same at the Elsa 3.3.0 RC3.
Also I have configured the Retention module with following and I have observed that instances are not deleted.
Even if, Sweep Interval is 4 hours, I could still see the instances are which older then the 4 hours.

```
elsa.UseRetention(retention =>
  {
      retention.ConfigureCleanupOptions = options =>
      {
          //options.SweepInterval = TimeSpan.FromHours(4);
          options.PageSize = 25;
      };
  });
```

**Comment by r-kernberger** [comment]
Did you define a delete policy like this:

`        retention.AddDeletePolicy("Löschen von abgeschlossenen NSW Import Workflows, die nichts importiert haben",
            _ => new DeleteFilter());
`

The DeleteFilter could look like this
`public class DeleteFilter : RetentionWorkflowInstanceFilter
{
    //Finished NswImportWorkflows werden beim nächsten Lauf des Löschjobs entfernt.
    //Diese erhalten den Status Cancelled, wenn keine Dateien importiert wurden.
    public DeleteFilter()
    {
        WorkflowStatus = Elsa.Workflows.WorkflowStatus.Finished;
    }
}`

**Comment by jayachandra21** [comment]
Yes, I have configured my retention policy as below. But still instances are not deleted.
` elsa.UseRetention(retention =>
 {
     retention.ConfigureCleanupOptions = options =>
     {
         options.PageSize = 25;
     };

     retention.AddDeletePolicy("Delete completed workflows", sp =>
     {
         RetentionWorkflowInstanceFilter filter = new()
         {
             WorkflowStatus = WorkflowStatus.Finished
         };
         return filter;
     });
 });`

**Comment by jayachandra21** [comment]
> Did you define a delete policy like this:
> 
> ` retention.AddDeletePolicy("Delete Workflow Instances", _ => new DeleteFilter());`
> 
> The DeleteFilter could look like this
> 
> ```cs
> public class DeleteFilter : RetentionWorkflowInstanceFilter
> {
>     //Finished Workflows
>     public DeleteFilter()
>     {
>         WorkflowStatus = Elsa.Workflows.WorkflowStatus.Finished;
>     }
> }
> ```
> 
> **Update:** I double checked it. My Instances have not been deleted despite defining a delete policy like above. Not even after 4 hours waiting.

Yes, it is the same from myside too.
 elsa.UseRetention(retention =>
 {
     retention.ConfigureCleanupOptions = options =>
     {
         options.PageSize = 25;
     };

     retention.AddDeletePolicy("Delete completed workflows", sp =>
     {
         RetentionWorkflowInstanceFilter filter = new()
         {
             WorkflowStatus = WorkflowStatus.Finished
         };
         return filter;
     });
 });

**Comment by Sverre-W** [comment]
https://github.com/elsa-workflows/elsa-core/pull/6208

**Comment by Sverre-W** [comment]
I've tested with a simple writeline workflow but seems to work as expected.

My setup:
```csharp
  elsa.UseRetention(r =>
            {
                r.SweepInterval = TimeSpan.FromSeconds(30);
                r.AddDeletePolicy("Delete all finished workflows", _ => new RetentionWorkflowInstanceFilter()
                {
                    WorkflowStatus = WorkflowStatus.Finished
                });
            });
```

Output:

```
info: Elsa.Retention.Jobs.CleanupJob[0]
      Cleaned up 1 workflow instances through Delete all finished workflows
Hello world
Hello world
Hello world
info: Elsa.Retention.Jobs.CleanupJob[0]
      Cleaned up 3 workflow instances through Delete all finished workflows

```

**Comment by sfmskywalker** [comment]
Done via #6211 
Thanks @Sverre-W !

**Comment by jayachandra21** [comment]
Hello @Sverre-W ,

Thank you very much!
I have configured the retention module with Elsa 3.0 RC4 as below.

```
elsa.UseRetention(r =>
            {
                r.SweepInterval = TimeSpan.FromMinutes(10);
                r.AddDeletePolicy("Delete all finished workflows", _ => new RetentionWorkflowInstanceFilter()
                {
                    WorkflowStatus = WorkflowStatus.Finished
                });
            });
```
I think the  Sweep Interval is considering the minute to delete the finished instances but not considered the configured as above.

Step1: Local time is 6:20 - I have 9 instances with finished state
![image](https://github.com/user-attachments/assets/d186b4ae-224c-4a72-870d-22a9c0fb1fc4)

Step2 : At 6:24 - Deleted the all above instances.
![image](https://github.com/user-attachments/assets/ea5741cb-e2db-49a1-8926-7a4de045b734)

Is it something missing in the configuration to work as expected?

**Comment by jayachandra21** [comment]
@Sverre-W @r-kernberger did you tried the scenario which I have highlighted at your side? because to ensure that Retention options is working as expected.

**Comment by jayachandra21** [comment]
Hello @Sverre-W  do you have any suggestion on my question?

**Comment by Sverre-W** [comment]
Could you tell me if you also have different length intervals in between sweepings. It might be the first  one is random, it uses the recurring tasks feature of Elsa. I'm not sure if the first scheduled instance respects the sweeping interval.

**Comment by jayachandra21** [comment]
Hello @Sverre-W, I have only one length intervals between **sweepings**.

**Comment by jayachandra21** [comment]
Hello @sfmskywalker and @Sverre-W,  I have verified the workflow instances **SweepInterval** property configuration with 5 minutes as below configuration.
   ```
 elsa.UseRetention(r =>
{
    r.SweepInterval = TimeSpan.FromMinutes(5);
    r.AddDeletePolicy("Delete all finished workflows", _ => new RetentionWorkflowInstanceFilter()
    {
        WorkflowStatus = WorkflowStatus.Finished
    });

});
```

**Testing result:**
I have observed that the workflow instances which are in **Finished** state got deleted without considering the  SweepInterval property.

I have tested the instances by running the application continuously more then an hour by configuring the SweepInterval as 5 minutes. 

I have attached the sample project for reference. Request you check if possible.

[Elsa330RC4.zip](https://github.com/user-attachments/files/18259511/Elsa330RC4.zip)

**Comment by Sverre-W** [comment]
It seems there was some misunderstanding. To clarify, the `SweepInterval` determines how often the cleanup job runs. Every time the job runs, it deletes all workflow instances that match the specified filter, which in your case includes all finished workflows.

If you want to delete workflows that have been finished for a certain period, you need to modify the filter accordingly. Here's an example:

> **Note:** This example uses the `CreatedAt` column, but you could also use the `FinishedAt` column if that better suits your requirements. The example below deletes all workflows that were started more than a day ago and have since been finished.

```csharp
retention.AddDeletePolicy("Delete completed workflows", sp =>
    {
        ISystemClock systemClock = sp.GetRequiredService<ISystemClock>();
        RetentionWorkflowInstanceFilter filter = new()
        {
            TimestampFilters = new List<TimestampFilter>(),
            WorkflowStatus = WorkflowStatus.Finished
        };

        filter.TimestampFilters.Add(
            new TimestampFilter
            {
                Column = nameof(WorkflowInstance.CreatedAt),
                Operator = TimestampFilterOperator.LessThanOrEqual,
                Timestamp = systemClock.UtcNow.Subtract(TimeSpan.FromDays(1))
            }
        );
        
        return filter;
    });
```

**Comment by jayachandra21** [comment]
Dear @Sverre-W 
Thank you very much for detailed explanation.

My point is about sweet interval,which determines the how often the cleanup job runs.

So in my case I have configured for 5minutes, it means that the cleanup job should run every 5 minutes.

But at the moment, clean up job runs every 1 minutes but not 5 minutes.

**Comment by jayachandra21** [comment]
> Dear @Sverre-W Thank you very much for detailed explanation.
> 
> My point is about sweet interval,which determines the how often the cleanup job runs.
> 
> So in my case I have configured for 5minutes, it means that the cleanup job should run every 5 minutes.
> 
> But at the moment, clean up job runs every 1 minutes but not 5 minutes.

@Sverre-W Did you get a chance to look at the Sweep Interval, which determines how often the cleanup job runs?
My observation is that the Sweep Interval does not work as configured to run the cleanup job.
I have attached a sample project for reference.
If you get a chance, please take a look into it.
