### ISSUE TITLE
Abp 5 or 6 error with ELSA packages

### ISSUE THREAD

**Issue by svonnidmeg2012** [elsa-workflows/elsa-core#620]
### Prerequisites

Zero 10.2.0
Angular
.net 5.0

#### ABP Framework

ABP Framework version: 6.2.0

#### ELSA

ELSA version: 1.5.3.1369

#### EntityFramework

EntityFramework version: 5.0.2

#### Issue

Using ELSA and configure it as:

            // Add services used for the workflows runtime.
            services
                .AddElsa(elsa => elsa.AddEntityFrameworkStores<SqliteContext>(options => 
                    options.UseSqlite(_appConfiguration.GetConnectionString("Sqlite"))))
                .AddHttpActivities(options => options.Bind(_appConfiguration.GetSection("Elsa:Http")))
                .AddEmailActivities(options => options.Bind(_appConfiguration.GetSection("Elsa:Smtp")))
                .AddTimerActivities(options => options.Bind(_appConfiguration.GetSection("Elsa:Timers")))

                // Add services used for the workflows dashboard.
                .AddElsaDashboard();

We can compile and start Swagger as well, but when access to elsa dashboard this error appear:

TypeLoadException: Could not load type 'Microsoft.EntityFrameworkCore.Metadata.RelationalEntityTypeAnnotations' from assembly 'Microsoft.EntityFrameworkCore.Relational, Version=5.0.2.0, Culture=neutral

-------------------------------------------------------------------------------------------------------
### Prerequisites

Zero 9.3.0
Angular
.net core 3.1

#### ABP Framework

ABP Framework version: 5.14

#### ELSA

ELSA version: 1.2.2.29

#### EntityFramework

EntityFramework version: 3.1.16

#### Issue

Using ELSA and configure it as:

            // Add services used for the workflows runtime.
            services
                .AddElsa(elsa => elsa.AddEntityFrameworkStores<SqliteContext>(options => 
                    options.UseSqlite(_appConfiguration.GetConnectionString("Sqlite"))))
                .AddHttpActivities(options => options.Bind(_appConfiguration.GetSection("Elsa:Http")))
                .AddEmailActivities(options => options.Bind(_appConfiguration.GetSection("Elsa:Smtp")))
                .AddTimerActivities(options => options.Bind(_appConfiguration.GetSection("Elsa:Timers")))

                // Add services used for the workflows dashboard.
                .AddElsaDashboard();

We can compile and start Swagger as well, but when access to elsa dashboard this error appear:

FileNotFoundException: Could not load file or assembly 'System.Web.Http, Version=5.2.7.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'. El sistema no puede encontrar el archivo especificado.
Unknown location

Please help!

**Comment by sfmskywalker** [comment]
Elsa 1.5 depends on .NET 5, so it is likely to cause issues when referenced from .NET Core 3.1.
Elsa 1.4 is the last version that supports .NET Core 3.1

Elsa 2.0 (in early preview) supports .NET 5.0 only, but we might look into multi-targeting if time permits.

**Comment by svonnidmeg2012** [comment]
I know the ELSA dependencies. My problem is that never works whatever version I try.

.NET 5 - ELSA 1.5.3.1369 crashes when go to dashboard
TypeLoadException: Could not load type 'Microsoft.EntityFrameworkCore.Metadata.RelationalEntityTypeAnnotations' from assembly 'Microsoft.EntityFrameworkCore.Relational, Version=5.0.2.0, Culture=neutral

.NET 3.1 - ELSA 1.2.2.29/1.4.x crashes when go to dashboard same error.

In our project we use lot of nuggets with EntityFrameworkCore relations and just hope ELSA 2.0 will be a solution for us.
