### ISSUE TITLE
Package Elsa.Persistence.EntityFrameworkCore

### ISSUE THREAD

**Issue by todayMe** [elsa-workflows/elsa-core#621]
Hello,

I tried to install the Nuget Elsa.Persistence.EntityFrameworkCore in my VS 2019 and encountered the error below:

Severity	Code	Description	Project	File	Line	Suppression State
Error	NU1202	Package Elsa.Persistence.EntityFrameworkCore 1.5.3.1369 is not compatible with netcoreapp3.1 (.NETCoreApp,Version=v3.1). Package Elsa.Persistence.EntityFrameworkCore 1.5.3.1369 supports: net5.0 (.NETCoreApp,Version=v5.0)

I am using .Net Core 3.1. It seems the package above is for Core 5.0.

Does anyone have a solution for it? 

Thanks in advance.

**Comment by svonnidmeg2012** [comment]
Downgrade to 1.4.x

**Comment by todayMe** [comment]
Thank you svonnidmeg2012. I used the latest version of 1.4 and it worked.
