### ISSUE TITLE
[BUG] WorkflowInstanceStorageDriver ReadAsync  methed  Object deserialization error

### ISSUE THREAD

**Issue by mrh520** [elsa-workflows/elsa-core#6247]
![image](https://github.com/user-attachments/assets/b0741534-d53d-4135-a708-b5f60c4f4c2e)

**Comment by sfmskywalker** [comment]
Do you have steps to reproduce the issue?

**Comment by mrh520** [comment]
Call interface elsa/api/events/trigger? t=xx times the error

error:
Unable to cast object of type 'System.Collections.Generic.Dictionary`2[System.String,System.Object]' to type 'System.Dynamic.ExpandoObject'

**Comment by mrh520** [comment]
Example code to use:

Elsa.Samples.AspNet.DocumentApproval

**Comment by sfmskywalker** [comment]
I see. Thanks!

**Comment by sfmskywalker** [comment]
Possibly related: #6245
