### ISSUE TITLE
Elsa Designer views conflict

### ISSUE THREAD

**Issue by dailyUnknown** [elsa-workflows/elsa-core#625]
Hello,

I get the warning below after running a project build:

_ViewImports.cshtml.g.cs' conflicts with the imported type 'Views__ViewImports' in 'Elsa.WorkflowDesigner.Views

Is there a way to resolve the conflict?

Thank you.

**Comment by sfmskywalker** [comment]
Hard to say without seeing the full context. What is your solution setup/structure?

**Comment by dailyUnknown** [comment]
> 
> 
> Hard to say without seeing the full context. What is your solution setup/structure?

I created a simple website with MVC Core 3.1 via VS 2019, and followed the instructions below:

https://elsa-workflows.github.io/elsa-core/docs/installing-elsa-dashboard

No errors except that warning message when doing a build. The dashboard does show up when enter \elsa\home in the browser address bar.

Thank you.

**Comment by sfmskywalker** [comment]
I see. If it's not blocking you, then I would ignore it, knowing that a completely new dashboard is being worked on. The current dashboard solution will be deprecated and not be continued.

**Comment by dailyUnknown** [comment]
Thank you.
