### ISSUE TITLE
Elsa Dashboard too wide in IE11

### ISSUE THREAD

**Issue by dailyUnknown** [elsa-workflows/elsa-core#627]
Hello,

The dashboard overflows on the right-hand side of IE11 browser. Is there a way to fix it with CSS so it would not get cut off and no horizontal scrolling at the bottom?

![DB](https://user-images.githubusercontent.com/55210044/107837750-4f99e480-6d57-11eb-8b46-f1edcdd953b4.JPG)

Thanks in advance.

**Comment by sfmskywalker** [comment]
It can probably be fixed, but due to limited bandwidth I have to make some choices. Since the Elsa 1 dashboard won't be continued, I think it makes more sense to focus on finishing the Elsa 2 dashboard such that it is good enough for Elsa 2 to be released.

**Comment by dailyUnknown** [comment]
Thank you. Hope Elsa 2 will be released soon.

**Comment by dailyUnknown** [comment]
> It can probably be fixed, but due to limited bandwidth I have to make some choices. Since the Elsa 1 dashboard won't be continued, I think it makes more sense to focus on finishing the Elsa 2 dashboard such that it is good enough for Elsa 2 to be released.

@sfmskywalker, do you know if Version 2 fully support IE11? As for Version 1, the Designer doesn't work with IE11 but it does seem to work fine with other latest browsers when I test it.

Thanks in advance.

**Comment by sfmskywalker** [comment]
Elsa 2 will initially be released with a dashboard application build with Blazor (webassembly + server hosting models will be supported) - this won't work out of the box without [adding these additional polyfills](https://github.com/Daddoon/Blazor.Polyfill). If time permits, I will see if I can add a sample project that adds this support.

Besides the Blazor implementation, I do intend to provide a vanilla MVC / Razor pages implementation as well down the line.

**Comment by dailyUnknown** [comment]
Thank you for the info.
