### ISSUE TITLE
resuming specific workflow instances

### ISSUE THREAD

**Issue by ziedunited92** [elsa-workflows/elsa-core#631]
I am building an Elsa workflow for reports , my reports have a uniform workflow . my problem is that when resuming a special workflow of a special report i want it to get the id of the workflow as a parameter to resume exactly the target workflow not all of them.

**Comment by AdelSS04** [comment]
i have the same question ...

**Comment by ziedunited92** [comment]
can you help me please @sfmskywalker

**Comment by sfmskywalker** [comment]
Of course. In Elsa 1, you can resume specific workflow instances with `IWorkflowInvoker.ResumeAsync`. See [Sample 25](https://github.com/elsa-workflows/elsa-core/blob/master/src/samples/Sample25/Program.cs#L47).
