### ISSUE TITLE
ELSA 1.4.7.4 .NET 3.1 not working

### ISSUE THREAD

**Issue by svonnidmeg2012** [elsa-workflows/elsa-core#632]
Hi ELSA team,

I'm working with .netcoreapp3.1 and trying to integrate ELSA as your guides ans samples.
Using ELSA 1.4.7.4

The ConfigureServices in Startup.cs:

```
services
    // Add services used for the workflows runtime.
    .AddElsa(elsa => elsa.AddEntityFrameworkStores<SqliteContext>(options => 
        options.UseSqlite(_appConfiguration.GetConnectionString("Sqlite"))))
    .AddHttpActivities(options => options.Bind(_appConfiguration.GetSection("Elsa:Http")))
    .AddEmailActivities(options => options.Bind(_appConfiguration.GetSection("Elsa:Smtp")))
    .AddTimerActivities(options => options.Bind(_appConfiguration.GetSection("Elsa:Timers")))

    // Add services used for the workflows dashboard.
    .AddElsaDashboard();
```

The Configure in Startup.cs:

```
app.UseStaticFiles();
app.UseHttpActivities();
app.UseRouting();
app.UseEndpoints(endpoints =>
{
    endpoints.MapControllers();
}
```

The Initialize in xxxWebHostModule:

```
        public override void Initialize()
        {
            IocManager.RegisterAssemblyByConvention(typeof(GenTimeWebHostModule).GetAssembly());
            IocManager.Register<Elsa.Dashboard.Areas.Elsa.Controllers.HomeController, Elsa.Dashboard.Areas.Elsa.Controllers.HomeController>();
        }
```

The settings:

```
{
  "ConnectionStrings": {
    "Sqlite": "Data Source=c:\\data\\elsa-dashboard.db;Cache=Shared"
  },
  "Elsa": {
    "Http": {
      "BaseUrl": "http://localhost:59862"
    },
    "Smtp": {
      "Host": "localhost",
      "Port": "2525"
    },
    "Timers": {
      "SweepInterval": "0:00:00:10"
    }
  }
}
```

The error when try to access to /elsa/home is:

System.Reflection.ReflectionTypeLoadException: Unable to load one or more of the requested types.
Could not load file or assembly 'System.Web.Http, Version=5.2.7.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'. El sistema no puede encontrar el archivo especificado.
Could not load file or assembly 'System.Web.Http, Version=5.2.7.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'. El sistema no puede encontrar el archivo especificado.
Could not load file or assembly 'System.Web.Http, Version=5.2.7.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'. El sistema no puede encontrar el archivo especificado.
Could not load file or assembly 'System.Web.Http, Version=5.2.7.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'. El sistema no puede encontrar el archivo especificado.
Could not load file or assembly 'System.Web.Http, Version=5.2.7.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'. El sistema no puede encontrar el archivo especificado.
Could not load file or assembly 'System.Web.Http, Version=5.2.7.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'. El sistema no puede encontrar el archivo especificado.
Could not load file or assembly 'System.Web.Http, Version=5.2.7.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'. El sistema no puede encontrar el archivo especificado.
Could not load file or assembly 'System.Web.Http, Version=5.2.7.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'. El sistema no puede encontrar el archivo especificado.
Could not load file or assembly 'System.Web.Http, Version=5.2.7.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'. El sistema no puede encontrar el archivo especificado.
Could not load file or assembly 'System.Web.Http, Version=5.2.7.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'. El sistema no puede encontrar el archivo especificado.
Could not load file or assembly 'System.Web.Http, Version=5.2.7.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'. El sistema no puede encontrar el archivo especificado.
Could not load file or assembly 'System.Web.Http, Version=5.2.7.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'. El sistema no puede encontrar el archivo especificado.
Could not load file or assembly 'System.Web.Http, Version=5.2.7.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'. El sistema no puede encontrar el archivo especificado.
Could not load file or assembly 'System.Web.Http, Version=5.2.7.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'. El sistema no puede encontrar el archivo especificado.
Could not load file or assembly 'System.Net.Http.Formatting, Version=5.2.7.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'. El sistema no puede encontrar el archivo especificado.
Could not load file or assembly 'System.Web.Http, Version=5.2.7.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'. El sistema no puede encontrar el archivo especificado.
Could not load file or assembly 'System.Web.Http, Version=5.2.7.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'. El sistema no puede encontrar el archivo especificado.
Could not load file or assembly 'System.Web.Http, Version=5.2.7.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'. El sistema no puede encontrar el archivo especificado.
Could not load file or assembly 'System.Web.Http, Version=5.2.7.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'. El sistema no puede encontrar el archivo especificado.
Could not load file or assembly 'System.Web.Http, Version=5.2.7.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'. El sistema no puede encontrar el archivo especificado.
Could not load file or assembly 'System.Web.Http, Version=5.2.7.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'. El sistema no puede encontrar el archivo especificado.
   at System.Reflection.RuntimeModule.GetTypes(RuntimeModule module)
   at System.Reflection.RuntimeAssembly.get_DefinedTypes()
   at Scrutor.TypeSourceSelector.<>c.<InternalFromAssemblies>b__20_0(Assembly asm)
   at System.Linq.Enumerable.SelectManySingleSelectorIterator`2.MoveNext()
   at System.Linq.Enumerable.SelectEnumerableIterator`2.MoveNext()
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at Scrutor.LifetimeSelector.Scrutor.ISelector.Populate(IServiceCollection services, RegistrationStrategy strategy)
   at Scrutor.ServiceTypeSelector.Scrutor.ISelector.Populate(IServiceCollection services, RegistrationStrategy registrationStrategy)
   at Scrutor.ImplementationTypeSelector.Scrutor.ISelector.Populate(IServiceCollection services, RegistrationStrategy registrationStrategy)
   at Scrutor.TypeSourceSelector.Populate(IServiceCollection services, RegistrationStrategy registrationStrategy)
   at Elsa.Dashboard.Extensions.ActivityDefinitionListExtensions.Discover(ActivityDefinitionList list, Action`1 selector)
   at Elsa.Dashboard.Extensions.ActivityDefinitionListExtensions.DiscoverActivities(ElsaDashboardOptions options)
   at Elsa.Dashboard.Extensions.DashboardServiceCollectionExtensions.<>c.<AddElsaDashboard>b__0_0(ElsaDashboardOptions x)
   at Microsoft.Extensions.Options.ConfigureNamedOptions`1.Configure(String name, TOptions options)
   at Microsoft.Extensions.Options.OptionsFactory`1.Create(String name)
   at Microsoft.Extensions.Options.OptionsManager`1.<>c__DisplayClass5_0.<Get>b__0()
   at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
   at System.Lazy`1.ExecutionAndPublication(LazyHelper executionAndPublication, Boolean useDefaultConstructor)
   at System.Lazy`1.CreateValue()
   at Microsoft.Extensions.Options.OptionsCache`1.GetOrAdd(String name, Func`1 createOptions)
   at Microsoft.Extensions.Options.OptionsManager`1.Get(String name)
   at Microsoft.Extensions.Options.OptionsManager`1.get_Value()
   at AspNetCore.Areas_Elsa_Views_Shared_CustomScripts.ExecuteAsync()
   at Microsoft.AspNetCore.Mvc.Razor.RazorView.RenderPageCoreAsync(IRazorPage page, ViewContext context)
   at Microsoft.AspNetCore.Mvc.Razor.RazorView.RenderPageAsync(IRazorPage page, ViewContext context, Boolean invokeViewStarts)
   at Microsoft.AspNetCore.Mvc.Razor.RazorView.RenderAsync(ViewContext context)
   at Microsoft.AspNetCore.Mvc.ViewFeatures.HtmlHelper.RenderPartialCoreAsync(String partialViewName, Object model, ViewDataDictionary viewData, TextWriter writer)
   at Microsoft.AspNetCore.Mvc.ViewFeatures.HtmlHelper.PartialAsync(String partialViewName, Object model, ViewDataDictionary viewData)
   at AspNetCore.Areas_Elsa_Views_Shared__Layout.<ExecuteAsync>b__22_1()
   at Microsoft.AspNetCore.Razor.Runtime.TagHelpers.TagHelperExecutionContext.SetOutputContentAsync()
   at AspNetCore.Areas_Elsa_Views_Shared__Layout.ExecuteAsync()
   at Microsoft.AspNetCore.Mvc.Razor.RazorView.RenderPageCoreAsync(IRazorPage page, ViewContext context)
   at Microsoft.AspNetCore.Mvc.Razor.RazorView.RenderPageAsync(IRazorPage page, ViewContext context, Boolean invokeViewStarts)
   at Microsoft.AspNetCore.Mvc.Razor.RazorView.RenderLayoutAsync(ViewContext context, ViewBufferTextWriter bodyWriter)
   at Microsoft.AspNetCore.Mvc.Razor.RazorView.RenderAsync(ViewContext context)
   at Microsoft.AspNetCore.Mvc.ViewFeatures.ViewExecutor.ExecuteAsync(ViewContext viewContext, String contentType, Nullable`1 statusCode)
   at Microsoft.AspNetCore.Mvc.ViewFeatures.ViewExecutor.ExecuteAsync(ViewContext viewContext, String contentType, Nullable`1 statusCode)
   at Microsoft.AspNetCore.Mvc.ViewFeatures.ViewExecutor.ExecuteAsync(ActionContext actionContext, IView view, ViewDataDictionary viewData, ITempDataDictionary tempData, String contentType, Nullable`1 statusCode)
   at Microsoft.AspNetCore.Mvc.ViewFeatures.ViewResultExecutor.ExecuteAsync(ActionContext context, ViewResult result)
   at Microsoft.AspNetCore.Mvc.ViewResult.ExecuteResultAsync(ActionContext context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResultFilterAsync>g__Awaited|29_0[TFilter,TFilterAsync](ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResultExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.ResultNext[TFilter,TFilterAsync](State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeResultFilters()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|24_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeFilterPipelineAsync()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Localization.RequestLocalizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at IdentityServer4.Hosting.IdentityServerMiddleware.Invoke(HttpContext context, IEndpointRouter router, IUserSession session, IEventService events)
   at IdentityServer4.Hosting.MutualTlsTokenEndpointMiddleware.Invoke(HttpContext context, IAuthenticationSchemeProvider schemes)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at IdentityServer4.Hosting.BaseUrlMiddleware.Invoke(HttpContext context)
   at Abp.AspNetZeroCore.Web.Authentication.JwtBearer.JwtTokenMiddleware.<>c__DisplayClass0_0.<<UseJwtTokenMiddleware>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Abp.AspNetZeroCore.Web.Authentication.JwtBearer.JwtTokenMiddleware.<>c__DisplayClass0_0.<<UseJwtTokenMiddleware>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Builder.Extensions.MapMiddleware.Invoke(HttpContext context)
   at Elsa.Activities.Http.Middleware.RequestHandlerMiddleware`1.InvokeAsync(HttpContext httpContext, THandler handler)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
System.IO.FileNotFoundException: Could not load file or assembly 'System.Web.Http, Version=5.2.7.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'. El sistema no puede encontrar el archivo especificado.
File name: 'System.Web.Http, Version=5.2.7.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'

System.IO.FileNotFoundException: Could not load file or assembly 'System.Web.Http, Version=5.2.7.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'. El sistema no puede encontrar el archivo especificado.
File name: 'System.Web.Http, Version=5.2.7.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'

System.IO.FileNotFoundException: Could not load file or assembly 'System.Web.Http, Version=5.2.7.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'. El sistema no puede encontrar el archivo especificado.
File name: 'System.Web.Http, Version=5.2.7.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'

System.IO.FileNotFoundException: Could not load file or assembly 'System.Web.Http, Version=5.2.7.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'. El sistema no puede encontrar el archivo especificado.
File name: 'System.Web.Http, Version=5.2.7.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'

System.IO.FileNotFoundException: Could not load file or assembly 'System.Web.Http, Version=5.2.7.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'. El sistema no puede encontrar el archivo especificado.
File name: 'System.Web.Http, Version=5.2.7.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'

System.IO.FileNotFoundException: Could not load file or assembly 'System.Web.Http, Version=5.2.7.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'. El sistema no puede encontrar el archivo especificado.
File name: 'System.Web.Http, Version=5.2.7.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'

System.IO.FileNotFoundException: Could not load file or assembly 'System.Web.Http, Version=5.2.7.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'. El sistema no puede encontrar el archivo especificado.
File name: 'System.Web.Http, Version=5.2.7.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'

System.IO.FileNotFoundException: Could not load file or assembly 'System.Web.Http, Version=5.2.7.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'. El sistema no puede encontrar el archivo especificado.
File name: 'System.Web.Http, Version=5.2.7.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'

System.IO.FileNotFoundException: Could not load file or assembly 'System.Web.Http, Version=5.2.7.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'. El sistema no puede encontrar el archivo especificado.
File name: 'System.Web.Http, Version=5.2.7.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'

System.IO.FileNotFoundException: Could not load file or assembly 'System.Web.Http, Version=5.2.7.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'. El sistema no puede encontrar el archivo especificado.
File name: 'System.Web.Http, Version=5.2.7.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'

System.IO.FileNotFoundException: Could not load file or assembly 'System.Web.Http, Version=5.2.7.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'. El sistema no puede encontrar el archivo especificado.
File name: 'System.Web.Http, Version=5.2.7.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'

System.IO.FileNotFoundException: Could not load file or assembly 'System.Web.Http, Version=5.2.7.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'. El sistema no puede encontrar el archivo especificado.
File name: 'System.Web.Http, Version=5.2.7.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'

System.IO.FileNotFoundException: Could not load file or assembly 'System.Web.Http, Version=5.2.7.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'. El sistema no puede encontrar el archivo especificado.
File name: 'System.Web.Http, Version=5.2.7.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'

System.IO.FileNotFoundException: Could not load file or assembly 'System.Web.Http, Version=5.2.7.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'. El sistema no puede encontrar el archivo especificado.
File name: 'System.Web.Http, Version=5.2.7.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'

System.IO.FileNotFoundException: Could not load file or assembly 'System.Net.Http.Formatting, Version=5.2.7.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'. El sistema no puede encontrar el archivo especificado.
File name: 'System.Net.Http.Formatting, Version=5.2.7.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'

System.IO.FileNotFoundException: Could not load file or assembly 'System.Web.Http, Version=5.2.7.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'. El sistema no puede encontrar el archivo especificado.
File name: 'System.Web.Http, Version=5.2.7.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'

System.IO.FileNotFoundException: Could not load file or assembly 'System.Web.Http, Version=5.2.7.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'. El sistema no puede encontrar el archivo especificado.
File name: 'System.Web.Http, Version=5.2.7.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'

System.IO.FileNotFoundException: Could not load file or assembly 'System.Web.Http, Version=5.2.7.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'. El sistema no puede encontrar el archivo especificado.
File name: 'System.Web.Http, Version=5.2.7.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'

System.IO.FileNotFoundException: Could not load file or assembly 'System.Web.Http, Version=5.2.7.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'. El sistema no puede encontrar el archivo especificado.
File name: 'System.Web.Http, Version=5.2.7.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'

System.IO.FileNotFoundException: Could not load file or assembly 'System.Web.Http, Version=5.2.7.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'. El sistema no puede encontrar el archivo especificado.
File name: 'System.Web.Http, Version=5.2.7.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'

System.IO.FileNotFoundException: Could not load file or assembly 'System.Web.Http, Version=5.2.7.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'. El sistema no puede encontrar el archivo especificado.
File name: 'System.Web.Http, Version=5.2.7.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'

I need a solution, please!
Thx!

**Comment by sfmskywalker** [comment]
It looks like there might be a reference made to a NuGet package that targets .NET 5 and not .NET 3.1. I'd be happy to take a look if you share your solution + projects, or at least a stripped down version of it that demonstrates the issue.

**Comment by svonnidmeg2012** [comment]
Hi,

I updated all project to .NET 5.0 (with not 3.1 dependencies) and using ELSA 1.5.3.1369

Crashes with:

TypeLoadException: Could not load type 'Microsoft.EntityFrameworkCore.Metadata.RelationalEntityTypeAnnotations' from assembly 'Microsoft.EntityFrameworkCore.Relational, Version=5.0.2.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'.
Unknown location

TypeLoadException: Could not load type 'Microsoft.EntityFrameworkCore.Metadata.RelationalModelAnnotations' from assembly 'Microsoft.EntityFrameworkCore.Relational, Version=5.0.2.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'.
Unknown location

TypeLoadException: Could not load type 'Microsoft.EntityFrameworkCore.Metadata.RelationalPropertyAnnotations' from assembly 'Microsoft.EntityFrameworkCore.Relational, Version=5.0.2.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'.
Unknown location

TypeLoadException: Could not load type 'Microsoft.EntityFrameworkCore.Metadata.RelationalFullAnnotationNames' from assembly 'Microsoft.EntityFrameworkCore.Relational, Version=5.0.2.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'.
Unknown location

ReflectionTypeLoadException: Unable to load one or more of the requested types.
Could not load type 'Microsoft.EntityFrameworkCore.Metadata.RelationalEntityTypeAnnotations' from assembly 'Microsoft.EntityFrameworkCore.Relational, Version=5.0.2.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'.
Could not load type 'Microsoft.EntityFrameworkCore.Metadata.RelationalModelAnnotations' from assembly 'Microsoft.EntityFrameworkCore.Relational, Version=5.0.2.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'.
Could not load type 'Microsoft.EntityFrameworkCore.Metadata.RelationalPropertyAnnotations' from assembly 'Microsoft.EntityFrameworkCore.Relational, Version=5.0.2.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'.
Could not load type 'Microsoft.EntityFrameworkCore.Metadata.RelationalFullAnnotationNames' from assembly 'Microsoft.EntityFrameworkCore.Relational, Version=5.0.2.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'.
System.Reflection.RuntimeModule.GetTypes(RuntimeModule module)

Loader Exceptions:
Could not load type 'Microsoft.EntityFrameworkCore.Metadata.RelationalEntityTypeAnnotations' from assembly 'Microsoft.EntityFrameworkCore.Relational, Version=5.0.2.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'.
Could not load type 'Microsoft.EntityFrameworkCore.Metadata.RelationalModelAnnotations' from assembly 'Microsoft.EntityFrameworkCore.Relational, Version=5.0.2.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'.
Could not load type 'Microsoft.EntityFrameworkCore.Metadata.RelationalPropertyAnnotations' from assembly 'Microsoft.EntityFrameworkCore.Relational, Version=5.0.2.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'.
Could not load type 'Microsoft.EntityFrameworkCore.Metadata.RelationalFullAnnotationNames' from assembly 'Microsoft.EntityFrameworkCore.Relational, Version=5.0.2.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'.

Is a clean project using ABP 6.2

```
<ItemGroup>
    <PackageReference Include="Abp.Castle.Log4Net" Version="6.2.0" />
    <PackageReference Include="AspNetCore.HealthChecks.UI" Version="5.0.0-preview1" />
    <PackageReference Include="AspNetCore.HealthChecks.UI.Client" Version="5.0.0-preview1" />
    <PackageReference Include="AspNetCore.HealthChecks.UI.InMemory.Storage" Version="5.0.0-preview1" />
    <PackageReference Include="Elsa" Version="1.5.3.1369" />
    <PackageReference Include="Elsa.Dashboard" Version="1.5.3.1369" />
    <PackageReference Include="Elsa.Persistence.EntityFrameworkCore" Version="1.5.3.1369" />
    <PackageReference Include="Microsoft.VisualStudio.Azure.Containers.Tools.Targets" Version="1.10.8" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="5.0.0">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
</ItemGroup>
```

Why can't run ELSA in any version, in any project I try!!!

**Comment by sfmskywalker** [comment]
I’m wondering if it might have to do with the auto discovery of activities when adding the dashboard services. You can test if this is the case by not registering the dashboard services and see if it starts then. 

If that’s the case, then probably the best way for now is to manually register the activities you wish to use with the dashboard.

**Comment by svonnidmeg2012** [comment]
Can I send you a simplified project in private?

**Comment by sfmskywalker** [comment]
Sure, send it to sipkeschoorstra at outlook.

**Comment by svonnidmeg2012** [comment]
Done! Waiting your response.

Thx!

**Comment by svonnidmeg2012** [comment]
Hi,

I found what really fails on ELSA project (downloaded from git). Will be so extended to explain, I hope the picture is more clear to understand what is hapening

![image_2021_02_16T18_45_57_592Z](https://user-images.githubusercontent.com/67102445/108108088-6b232900-7090-11eb-8b61-9aad532154d8.png)

The Scrutor is trying to load lots of assemblies and to much of them are deprecated or non existing in current versions.

You have a **TODO: Prevent type loads exceptions in your code**, when doing 

`!x.FullName.StartWith("Microsoft.AspNetCore") `

Seems that's the problem.

**Comment by sfmskywalker** [comment]
So, exactly what I thought then.(https://github.com/elsa-workflows/elsa-core/issues/632#issuecomment-779851181).

Which means the easiest way for now to workaround this is to register the activities you wish to see in the dashboard manually (look at the AddElsaDashboard method to find an overload that allows you to add activity types manually).

I’ll try and find an example soon and paste it in this thread if you haven’t found it already.

**Comment by sfmskywalker** [comment]
In Elsa 2 this won’t be an issue at all fortunately.

**Comment by svonnidmeg2012** [comment]
Ok... It was so great if you can paste here how to load specific types in . AddElsaDashboard() method

**Comment by sfmskywalker** [comment]
Sorry, I’m not behind a computer so it’s a bit cumbersome to find it.

**Comment by sfmskywalker** [comment]
Here's an example:

```csharp
services.AddElsaDashboard(options => options.Configure(x => x.ActivityDefinitions
    .Add<WriteLine>()
    .Add<ReadLine>()
    .Add<ReceiveHttpRequest>()
    .Add<SendHttpRequest>()
    .Add<WriteHttpResponse>()
    .Add<SetVariable>()
    .Add<ForEach>()
    .Add<While>()
    .Add<Fork>()
    .Add<Join>()
    .Add<IfElse>()
    .Add<Switch>()
    .Add<SendEmail>()
    .Add<CronEvent>()
    .Add<TimerEvent>()
    .Add<Correlate>()
    .Add<Finish>()
    .Add<Signaled>()
    .Add<Start>()
    .Add<TriggerSignal>()
    .Add<TriggerWorkflow>()
));
```

**Comment by svonnidmeg2012** [comment]
With it:

![image](https://user-images.githubusercontent.com/67102445/108121259-cbbb6180-70a2-11eb-8797-ce113e6f7f05.png)

And Workflows is:

![image](https://user-images.githubusercontent.com/67102445/108121316-e7bf0300-70a2-11eb-9911-5172967a4aa1.png)

Not working... Hope you can do it with wetransfer project I've sent.

Thanks in advance!

**Comment by sfmskywalker** [comment]
It looks like your Castle Windsor container doesn't have the controllers registered as services from the Elsa ASP.NET Area.
I don't have any experience with ABP, but perhaps all you need to do is add this call to the // MVC section: `.AddControllersAsServices()` like so:

```csharp
services.AddControllersWithViews().AddControllersAsServices();
```

If that doesn't help, perhaps try adding Elsa as an application part explicitly, like so:

```csharp
services.AddControllersWithViews()
.AddApplicationPart(typeof(Elsa.Dashboard.Areas.Elsa.Controllers.HomeController).Assembly)
.AddControllersAsServices();
```

**Comment by svonnidmeg2012** [comment]
Well... seems no error... but still with no theme and no js to can work with workflows...

Sorry my inexperience... it's so hard when don't know the tool

**Comment by sfmskywalker** [comment]
No worries, I understand.

Unfortunately I don't have the time right now to dig into ABP and Elsa integration, especially since the Elsa 1 dashboard will be discontinued in favor of the new Elsa 2 dashboard (and a future MVC modules for integration with ABP), but perhaps at least as a starting point you can try and see if at least the following project works for you:

[Elsa.Dashboard.Web.zip](https://github.com/elsa-workflows/elsa-core/files/6002064/Elsa.Dashboard.Web.zip)

To resolve the styling (and possibly script) issues you are seeing when integrating with ABP, here are a couple more things to try and look into:

1. Delete all bin and obj folders and rebuild the solution.
2. Open F12 Developer Tools and try and see what asset (CSS + script) URLs are being downloaded and returning 404 (or perhaps another non-200 status code). Copy and paste one of these URLS directly in the browser's address bar. You might get lucky and see a helpful error that might explain what's going on.

If you are still unable to figure it out, create a brand new ABP project with nothing but the Elsa configuration (so no custom modules or code). If you are still getting the same issues, send that solution over to me.

**Comment by svonnidmeg2012** [comment]
Hi Sipke,

Nothing after delete bin/obj and rebuild (I tried lot of times before too)

![image](https://user-images.githubusercontent.com/67102445/108408087-e7e70c00-7224-11eb-86b5-85fa747b8e78.png)

Just not found the js/css files of argon and Elsa.Dashboard assets

Sad...

**Comment by svonnidmeg2012** [comment]
Good/Not good news!
Now Elsa Dashboard is working fine.
Let me explain:

1. I have copied the assets folder from inside the nuget
2. I created _content/Elsa.Dashboard folders into wwwroot folder (where swagger is)
3. Pasted assets folder into wwwroot/_content/Elsa.Dashboard
4. Run the works

Ok... but I know there is not the correct way (just working for 1.4.7.4 version). 
What I need is to know why Elsa aren't doing this by itself and how to configure for it.

I hope I was clear enough in my explanation (I know that my English is not 10) and that it has been clear to you what is wrong.

If you have any solution for it, great!
If the solution is working as is while you publish de Elsa 2.0, is not the desired way, but hope 2.0 will be better at this point.

Let me know, please!

P.D. - When 2.0 will be able?

**Comment by sfmskywalker** [comment]
I'm afraid I don't know why you're seeing this issue, as I can't seem to reproduce it myself. But if it works by copying these files manually, I would just go with that. As you mentioned, Elsa 2 will be better. It has a new dashboard implementation. It won't initially be available as a separate MVC area, but instead as a standalone Blazor application.

The plan is still to release Elsa 2.0 end of March, barring any unforeseen delays.

You can get Elsa 2.0 Preview 6 today from MyGet if you would like to try it out. There's no documentation yet, but there are a lot of example projects in the "samples" folder that might help. If you want to run the dashboard, look for the sample project called [ElsaDashboard.Samples.Monolith](https://github.com/elsa-workflows/elsa-core/tree/feature/elsa-2.0/src/samples/dashboard/ElsaDashboard.Samples.Monolith). The dashboard and designer still have a lot of work to do, so keep in mind this is a very early preview and a lot of work needs to be done still.

**Comment by craigfowler** [comment]
@svonnidmeg2012 - did @sfmskywalker 's latest message help you out?  Was there anything more to this or it OK to close this issue now?
