### ISSUE TITLE
Workflow Send HTTP request issue

### ISSUE THREAD

**Issue by dailyUnknown** [elsa-workflows/elsa-core#634]
Hello,

I created a workflow based on the tutorial below:

https://elsa-workflows.github.io/elsa-core/docs/guides-dashboard

I am getting the message "No connection could be made because the target machine actively refuses". 

![Capture](https://user-images.githubusercontent.com/55210044/107990060-6ecb8880-6f88-11eb-9d16-ecff31933450.JPG)

I added "https://localhost:59862/hello-world" to the URL field of the "Send HTTP request" because there was an error stating that the activity cannot run without the url. The tutorial doesn't have an instruction about adding the url.

Please advise. I don't know what I am missing in this test case.

Thank you.

**Comment by ziedunited92** [comment]
In the tutorial the activity name is send http response but this activity dosen't exist i advice you to use write http response instead that worked for me

**Comment by sfmskywalker** [comment]
Thanks @ziedunited92 - I think you are right. @dailyUnknown are we correct in assuming that you actually wish to write an HTTP response instead of making another HTTP request?

The documentation will be revisited entirely once Elsa 2 hits the master branch. Thanks for sticking it out until then.

**Comment by dailyUnknown** [comment]
> 
> 
> In the tutorial the activity name is send http response but this activity dosen't exist i advice you to use write http response instead that worked for me

@ziedunited92, I changed it as advised but when I run it via "http://localhost:44396/hello-world" and nothing happens. Also, the workflow finished list doesn't show today's date "2/16/2021" results. See below: (only the results from yesterday are shown)

![Capture](https://user-images.githubusercontent.com/55210044/108097067-895c3b00-7036-11eb-988b-1a292ba7a706.JPG)

@sfmskywalker, I only followed exactly the tutorial: https://elsa-workflows.github.io/elsa-core/docs/guides-dashboard. I am new to this tool and still learning it.

Thank you.

**Comment by sfmskywalker** [comment]
I'm not sure what's going on. Perhaps if you send me an export of your workflow (JSON), I can have a look and see what's happening.

**Comment by craigfowler** [comment]
Hello again @dailyUnknown (as you might guess, I'm doing some issue triage this evening).  Are you able to share that exported workflow JSON or have you managed to work around this problem (IE: it's OK to close)?

**Comment by dailyUnknown** [comment]
> Hello again @dailyUnknown (as you might guess, I'm doing some issue triage this evening). Are you able to share that exported workflow JSON or have you managed to work around this problem (IE: it's OK to close)?

Thanks craigfowler for asking but I was not able to do fix those issues including the CSS problem with IE11 with version 1 so I removed it from my website. Hopefully V2 will resolve most of my issues. I will close this case. Thank you for the reminder.
