### ISSUE TITLE
Does elsa support BPMN?

### ISSUE THREAD

**Issue by zhouguoqing** [elsa-workflows/elsa-core#638]
Hi Sipke , I am a elsa-workflows's fans. It's a great workflow framework as I know.
So we want to use it as our workflow engine. Now,  I have a question as following,
Does elsa  support BPMN?

**Comment by zbogdanov** [comment]
@zhouguoqing this is a duplicate, take a look here: https://github.com/elsa-workflows/elsa-core/issues/460
