### ISSUE TITLE
To consolidate with .NET libraries, a migration from Json.NET to System.Text.Json should be investigated

### ISSUE THREAD

**Issue by craigfowler** [elsa-workflows/elsa-core#651]
_This issue began life as a discussion in #552_.  Recently, .NET has released the [System.Text.Json] package, for use as a standard JSON library.  We would like to investigate whether it is feasible to migrate from [Json.NET (aka Newtonsoft.Json)] to `System.Text.Json`.

* Which features of Json.NET does Elsa use which are not available in `System.Text.Json`?
* Are there workarounds, shims or alternative APIs available?

As yet there is no decision either way (migrate or not).  If this work gets a go-ahead then this ticket could be updated to _actually do the migration_.

[System.Text.Json]: https://www.nuget.org/packages/System.Text.Json
[Json.NET (aka Newtonsoft.Json)]: https://www.nuget.org/packages/Newtonsoft.Json/

**Comment by bryanvam** [comment]
I just started using Elsa. I was quite surprised to be forced to use Newtonsoft. I second this this request.

**Comment by Chryssie** [comment]
Would decoupling Elsa from "Newtonsoft" specifically, make the work for this more manageable? That would allow for selecting between "System.Text.Json" and "Newtonsoft" making the impact on exisiting-users

Currently, there's a lot of calls to `JsonConverter` and explicit references to "Newtonsoft" in the form of `JToken` or `JObject`. If the explicit calls to `JsonConverter` are changed to use `IContentSerializer` and the `JToken` or `JObject` usages abstracted out then it should be possible to configure in the JSON library to use in Program.cs or something. That would then eliminate the need to introduce a massive breaking change to a more controlled one.

This might also allow the serialization to be done to something other than JSON if they provide an `IContentSerializer` that serializes to and from something else like XML or a binary format.

**Comment by sfmskywalker** [comment]
Hello @Chryssie,

Thank you for your insights on this matter. I completely concur with your perspective. In our continuous efforts to improve Elsa, we've taken steps to abstract away complexities. With the release of Elsa 3, we've made significant strides in this direction, addressing the concerns raised in this issue.

Given the advancements in Elsa 3 and its alignment with the suggestions here, I propose we mark this issue as resolved. Your feedback has been invaluable, and we're excited about the improvements we've integrated based on community input.

**Comment by spantazi** [comment]
Hello. Is there any specific issue to track the migration to system.text.json? I feel that json.net is slowly being abandoned and it is still missing features that system.text.json has, like async and stream deserialization (at its high level API).
