### ISSUE TITLE
JSON Deserialization error when upgrading existing Elsa project

### ISSUE THREAD

**Issue by chris1411** [elsa-workflows/elsa-core#652]
Trying to migrate an existing application from Elsa 1.3.0.4 to the latest version, 1.5.3.1369. I'm getting the following error now when attempting to go to the workflow definition page:

```JsonSerializationException: Cannot deserialize the current JSON array (e.g. [1,2,3]) into type 'Elsa.Models.WorkflowExecutionScope' because the type requires a JSON object (e.g. {"name":"value"}) to deserialize correctly.```

I see that Elsa was changed to only support a single scope, so I'm guessing this error is because I have existing data that has an array value for scopes? Any fix for this?

**Comment by sfmskywalker** [comment]
That indeed seems to be the issue. Unless you are willing to delete existing workflow instances, the best way to fix this I think is to write a migration script that modifies the stored JSON to a version that can be loaded by 1.5 (i.e. changing the array to a flattened object).

**Comment by chris1411** [comment]
Thats what i was afraid of. Thank you.
