### ISSUE TITLE
To simplify the config, AppVeyor YML should be managed per-branch

### ISSUE THREAD

**Issue by craigfowler** [elsa-workflows/elsa-core#664]
Currently, the `appveyor.yml` file that's checked into source control (across all active long-lived branches) has the build configuration for _all of the branches_.  For example in the v2 branch the file has build configs for 1.4.x and 1.5.x as well as the 2.x code.  Which part of the yml build config is then chosen by an almost switch/case-like syntax.

To simplify the build configs, the copy of this file in each branch should only contain the build config for the code in that branch.  This is OK because when AppVeyor runs a build, it uses the `appveyor.yml` file _from the same commit as it is building_.  The extra build configs in the version of the file in each branch are actually never used anyway.

## Acceptance criteria
In this ticket, we will 'tidy up' the YML file in the v2 branch.  The master & 1.4 branches can be left as they are for now.  When Elsa 2 is finalised and merged into master, it will overwrite and 'fix itself' anyway.

_This ticket was created following a brief discussion started by @craigfowler in https://github.com/elsa-workflows/elsa-core/discussions/660_

**Comment by craigfowler** [comment]
PR https://github.com/elsa-workflows/elsa-core/pull/678 _should resolve this_ once merged.

Only things to note are:
* We can't test that the MyGet deployment works until we see a build on a v2 branch (and not a feature branch as it's on now)
* We can't test that the NuGet deployment works until we see a build from a tagged commit

On that basis, _I'd suggest leaving this issue open_ until we have seen those two scenarios working OK.  Otherwise we can't be 100% certain that the change has been completely successful.

**Comment by craigfowler** [comment]
[As of build 2.0.0-preview6.1504], I can see that MyGet deployment is working as-intended.

[As of build 2.0.0-preview6.1504]: https://ci.appveyor.com/project/sfmskywalker/elsa/builds/37955695

**Comment by craigfowler** [comment]
@sfmskywalker at your next convenience/when appropriate (no rush on my account), if you create a new v2 preview tag on the repo then we can test that the other half of this works: Publishing to full NuGet.

I saw in that build that [it detected the "publish to full NuGet" deployment step and skipped it](https://ci.appveyor.com/project/sfmskywalker/elsa/builds/37955695#L938) because it didn't meet the criteria, so I do expect it to work when it's a tagged build.

Thanks

**Comment by sfmskywalker** [comment]
As discussed, let’s push a new tag to try it (preview 7). Let’s make sure we use the same tag for the MyGet too since that feed represents the latest bits straight from the Elsa 2 branch.

**Comment by craigfowler** [comment]
I have just pushed a `preview7` tag with bumped version number, in order to check that the build completes successfully & packages are published to NuGet.

**Comment by craigfowler** [comment]
[This AppVeyor build](https://ci.appveyor.com/project/sfmskywalker/elsa/builds/37981655) shows a tagged version being promoted to a published NuGet package correctly.  [Here's an example of such a package](https://www.nuget.org/packages/Elsa.Server.Api/2.0.0-preview7.1545) which was auto-published by AppVeyor build.

Closing this issue as everything is now confirmed to be working OK.

**Comment by sfmskywalker** [comment]
Perfect 👍
