### ISSUE TITLE
To measure & encourage code quality, devs should be able to see code analysis results

### ISSUE THREAD

**Issue by craigfowler** [elsa-workflows/elsa-core#665]
This issue is to set up SonarCloud to integrate with AppVeyor CI builds which are based upon the Elsa 2 codebase.

## Acceptance criteria
* Every build/PR which is based on the v2 branch (as of this issue being done) should run a SonarCloud analysis
* Quality analysis for all projects in the solution should be reported by SonarCloud
* Test coverage analysis for all tests which are run should be reported by SonarCloud
* An initial/appropriate **quality gate** should be agreed and configured

_This issue was opened in response to this comment by @sfmskywalker in https://github.com/elsa-workflows/elsa-core/discussions/657#discussioncomment-404430_

**Comment by craigfowler** [comment]
Yikes, that's one hilariously trail of commits above.  But - _the vast majority of the commits noted in the trail above are not real_.  That is, they have been rebased and squashed out of the history, meaning that they're no longer part of the repository.

Firstly, apologies that this wasn't submitted via Pull Request.  Unfortunately each iterative attempt at getting the analysis right had to be done against "a default branch" and not via a PR.  Thankfully this only happens once and from this point on we're back to the normal/correct way of working.

The new SonarCloud project is viewable at https://sonarcloud.io/dashboard?id=elsa-workflows_elsa-core and it is based on the v2 branch.  I have set "new code" to be code added in the last 7 days.  That can be changed if desired.

## More useful summary of the commits in the v2 branch

This screenshot of a **gitk** window is probably easier to show what actually went into the **elsa-core** repository and then stayed there.
![image](https://user-images.githubusercontent.com/982047/109391444-04630280-790f-11eb-9426-7f1316c17e96.png)

### Some work went in & was reverted

This pair of commits was merged into the elsa-2 branch.

```
a1a812a1 WIP #665 - Add changes to YML in order to trigger SonarScanner
8deb1a1f WIP #665 - Beginnings of SonarCloud integration
```

These were almost-immediately reverted back out again by the following, because they broke the build.

```
8d4339f4 Revert "Merge branch 'feature/665-SonarCloud-integration' into feature/elsa-2.0"
```

### Another attempt was made

The commits which were previously reverted were subsequently cherry-picked back into the repository, along with this extra commit which fixes the prior reason that the build broke.

```
917444c8 Resolve #665 - Fix project name
```

It was noticed that build artifacts were not being packaged for MyGet correctly.  The following commit was added to move the step at which that happened because the previously-used step did not run.

```
e9d00e6b Follow-up to #665 - Put 'pack' step into after_test
```

Finally, the SonarCloud website was not showing the correct version name for each analysis.  This was fixed with the following, _which isn't shown in the gitk screenshot_.

```
76588089 Follow-up #665 - Fix version number
```

**Comment by craigfowler** [comment]
## Changes to master
Similar work to the v2 branch was also done on master.  That's the following:
![image](https://user-images.githubusercontent.com/982047/109392295-35453680-7913-11eb-8db6-c36d25c2daf2.png)

This means that master now also has SonarCloud analysis.  Although in theory we could now disable this if we want.  It only had to be added in so that I could get into the SonarCloud project in order to rename the default branch to `feature/elsa-2.0`.  Master only needed to be analysed once.

We can keep or leave the SonarCloud config here, it doesn't really matter either way to me.

**Comment by craigfowler** [comment]
I'm going to leave this open so that someone can review those commits which actually went into the project.  Whilst it's not a pull request, at least this way someone can confirm everything is good before closing this issue, and we have a forum to discuss what happened.

@sfmskywalker - the two most recent comments prior to this one will guide you through what was actually "done for real" as part of this work.  There are a load of commits mentioned in the auto-generated summary which don't exist anymore because I never merged them in.

**Comment by sfmskywalker** [comment]
Really nice work!!

No worries that this isn't done as a PR, I realize this sort of thing requires experimentation. It's all good.
I'm fine with closing this issue - we can always reopen it in case we find something we need to discuss or if there's an issue.

Thanks for doing this - the SonarCloud dashboard looks awesome.
