### ISSUE TITLE
HTTP request settings

### ISSUE THREAD

**Issue by jwillmer** [elsa-workflows/elsa-core#669]
As a power user I like to configure the following options in the HTTP request activity:

- Request Method (POST, GET, PUT, DELETE)
- URL
- Ignore SSL issues
- Response format (JSON, file, string)
- Headers (defined as a JSON object)
- Body (for POST)

**Comment by sfmskywalker** [comment]
The HTTP Request activity exists with the aforementioned settings, but work needs to be done on the designer to provide appropriate editors for each.

**Comment by sfmskywalker** [comment]
I created a ticket for this here: #693.

**Comment by sfmskywalker** [comment]
This is now available in Elsa 2.
