### ISSUE TITLE
Script Activity

### ISSUE THREAD

**Issue by jwillmer** [elsa-workflows/elsa-core#672]
As a power user I like to use JavaScript to modify my input value. 

- I like to get the input as a JSON object. 
- Create a new JSON object that I like to return
- Modify the object via basic JavaScript functionality (Math, forEach, while, for, ..)

**Comment by sfmskywalker** [comment]
In addition to having the ability to return output from the JavaScript activity, it might be interesting to also expose a way for the script to specify a set of "outcomes" other than the default "Done" outcome. This would make the activity even more powerful, where power users can use JavaScript logic to determine the next outcome dynamically.

**Comment by jwillmer** [comment]
I saw that Elsa also allows the user to specify (runtime) variables. Maybe we even can allow the script to modify them?

**Comment by sfmskywalker** [comment]
Yes, good idea. Today, the script has read-only access to workflow variables, but we should add a function to set them too.

**Comment by sfmskywalker** [comment]
Implemented as of d7d7bd4a7e1125893db350de2afd6196e9776de6

**Comment by jwillmer** [comment]
> Yes, good idea. Today, the script has read-only access to workflow variables, but we should add a function to set them too.

Is this included in your commit @sfmskywalker  ?

**Comment by sfmskywalker** [comment]
Nope, missed that one. Good catch 👍

**Comment by sfmskywalker** [comment]
Now it's included via 5e665c9119b826f5a3c6a35b15a43c52f3d45336
