### ISSUE TITLE
As a developer, to receive appropriate guidance, I would like to see a more helpful exception than an Automapper one

### ISSUE THREAD

**Issue by craigfowler** [elsa-workflows/elsa-core#683]
When a developer making use of Elsa APIs causes a problem whereby an Activity is added to a Workflow Instance more than once, they receive an exception similar to the one pictured below.

![image](https://user-images.githubusercontent.com/982047/109300058-f5f0ea00-782d-11eb-99b6-7b7b126e5769.png)

This scenario _is always an error_ and I think that there is not much choice but to throw an exception in this scenario.  The reason that this should be improved is that the exception above isn't particularly helpful to the developer who is working with Elsa.  This is because they are not themselves consuming Automapper and should not need to have to look through Elsa's internals to determine what is actually wrong.

In this case, Elsa should catch the Automapper exception and then rethrow a specific Elsa exception, which has a more helpful message.  It should tell them roughly what is wrong, conceptually how to fix it and perhaps provide some information which will help identity which Activity has caused the problem (not just a GUID identity).

## Acceptance criteria
* Find some repro steps to reliably reproduce this error
* Catch exceptions thrown in this specific scenario (or perhaps pre-emptively test for the scenario)
* When the scenario occurs, Elsa should throw a more useful exception which:
  * Explicitly states that the same activity is being added to a workflow instance more than once
  * That this is not allowed
  * Provides some useful identifying information about the offending activity and perhaps the offending workflow instance (beware of including potentially sensitive data though)
* Test that the new exception is thrown when reproducing the error scenario

**Comment by craigfowler** [comment]
## No longer relevant for Elsa 2.0
I presume that this issue (which came from a Gitter conversation) was reported against Elsa 1.x.  The reason is that in Elsa 2.0, the class `Elsa.Persistence.EntityFrameworkCore.WorkflowInstanceEntity` no longer exists.  There is no mapping between a specialized 'persistence model' object and the original `WorkflowInstance` model object.  The EF persistence layer works directly with the WorkflowInstance model.  The same is true for the MongoDb persistence provider.

I did notice that the YesSQL provider uses 'document objects' which seem conceptually equivalent though.  An example is `Elsa.Persistence.YesSql.Documents.WorkflowInstanceDocument`.  This is mapped back-and-forth to/from a workflow instance by Automapper.  That said - these do not use dictionary objects keyed by the activity ID and so I do not think that this problem will be reproducible there either.

The only places where `IDictionary<K,V>` is used and keyed by the activity ID, the `Add` methods of those dictionaries are not used, only `GetValue` and `SetValue` which can deal with duplicates (the result is overwriting the old value).  This is an acceptable outcome in those cases, as they deal with transient activity data.

I have added (via a PR) some test coverage to prove that workflows with duplicate activities may be executed and persisted OK using Elsa 2.0, using all of the currently-supported persistence providers.

**Comment by craigfowler** [comment]
This essentially means _that it is not an error_ in Elsa 2.0 for a workflow to contain activities with duplicate identifiers.  _That might not be actually desired behaviour though!_  At least in the way that this issue originally described, it no longer results in an exception though.

@sfmskywalker - might be worth further thought at a later date.  But for now the issue-as-reported is dealt with.

**Comment by sfmskywalker** [comment]
Theoretically it's of course true that a `WorkflowDefinition` can have `ActivityDefinition` objects with the same ID in its `Activities` collection. I haven't seen this happen in practice, but if it would happen, an exception would eventually be thrown as soon as the `GetByActivityId` extension method is invoked for the duplicate ID. Obviously we'd like to see issues sooner rather than later, so for those reasons it would be more correct to store the activities in a dictionary or somehow otherwise ensure we don't get duplicates. 

It's not a high-prio as far as I'm concerned, but would be a good improvement of the code base.
