### ISSUE TITLE
Footer link for 'Blog' is pointing to some edit link

### ISSUE THREAD

**Issue by DoomerDGR8** [elsa-workflows/elsa-core#691]
This footer link points to a localhost setup:

![image](https://user-images.githubusercontent.com/825078/109600669-e4158c80-7b36-11eb-8049-9501b34750ad.png)

**Comment by sfmskywalker** [comment]
Thanks for reporting. Since we are working on a new dashboard, we'll make sure it's correct there and leave the current dashboard as-is since it will be discontinued. Unless someone submits a PR, then it's fine to merge in.
