### ISSUE TITLE
Email Activity body to handle a variable with HTML

### ISSUE THREAD

**Issue by DoomerDGR8** [elsa-workflows/elsa-core#692]
I have this setup:

![image](https://user-images.githubusercontent.com/825078/109601462-59359180-7b38-11eb-9190-c91148e6eda9.png)

In the Body, `{{ Input.Payload.Justification }}` contains text decorated with HTML. I'm getting this output:

![image](https://user-images.githubusercontent.com/825078/109601822-01e3f100-7b39-11eb-80da-45a79dd81cb5.png)

How do I handle this? I want the `{{ Input.Payload.Justification }}` to be HTML

**Comment by sfmskywalker** [comment]
Try this: `{{ Input.Payload.Justification | raw }}`

See also Fluid's documentation: https://github.com/sebastienros/fluid#disabling-encoding-contextually
