### ISSUE TITLE
Activity Property Field Editors

### ISSUE THREAD

**Issue by sfmskywalker** [elsa-workflows/elsa-core#693]
To control what field editor is used by the workflow designer, the properties of an activity class need to be annotated with the `ActivityPropertyAttribute` attribute, which allows the developer to specify certain options used by the designer.

One such property of `ActivityPropertyAttribute` is `Type`, which currently can be any of the following:

- text
- boolean
- expression
- list
- select

However, the above list is inherited from Elsa 1, while the Elsa 2 designer currently has only support for one type: `"text"`.
What we should do is come up with a new set of property field types that are more intuitive to reason about. Right now, it is not clear what the difference might be between "list" and "select". The current naming scheme is too ad-hoc and inconsistent: "boolean" represents a type of data, while "select" represents a type of control.

So we have a decision to make: should the property types convey UI details, or data type details?
Keep in mind also that Elsa Core itself aims to be designer-agnostic. Although the `ActivityPropertyAttribute` exists to provide UI hints to workflow designers, it should not be tightly coupled to any specific implementation of a designer.

Personally, I feel that it is more appropriate to use "control"-like names for the property types, because it would make naming quite awkward otherwise. For example, if we were to specify the "boolean" value to a boolean property, but wish that the designer uses e.g. two radio buttons instead of a single checkbox, we would have to provide further options (i.e. UI hints). But in that case, we might as well stick to just providing UI hints, since providing "boolean" as a type explicitly would be entirely redundant to the .NET type `bool`.

One might argue that we should just stick to checkboxes for boolean values of course.
But in the case of `string` properties, the same issue arises: depending on the semantic meaning of a given activity property, it might be appropriate to display a single-line text field, or a multi-line text area.

Therefore, I propose we come up with a list of controls that we support. But perhaps they should not match HTML controls one on one, since it's entirely conceivable that there would be a WinForms and WPF based workflow designer.

With that, let's consider the following list:

- "singleline" (the default for string values)
- "multiline" (the default for string values)
- "checkbox" (the default for boolean values)
- "checklist" (for properties of type IList<T>, ICollection<T> etc.)
- "radiolist" (for properties of type string or int, but allowing the user to select from a finite set of options)
- "dropdownlist" (for properties of type string or int, but allowing the user to select from a finite set of options)

In addition to the above, each activity property can be further configured with "options" that are specific to a given type.
For example, when specifying "checklist" or "dropdownlist", the activity developer needs to provide a list of options to display.
This list can either be static or dynamic. When dynamic, the developer needs to specify a .NET type that implements a certain contract (e.g. exposes a `GetItems` method) that returns items dynamically at runtime. Taking this one step further, this item provider needs to be invoked via an API endpoint everytime the activity editor is opened in the designer, allowing the activity developer to implement more advanced scenarios.

Once the above is in place (except for the list providers), all we have to do is annotate the HTP Request Activity properties with the proper control types.

**Comment by VahidNaderi** [comment]
Is there any plan for custom editors? e.g. cascading dropdowns

**Comment by sfmskywalker** [comment]
Yes, you will be able to create custom editors without having to modify the stencil components themselves. You would have to define a new "UI hint" (e.g. "cascading-dropdown") and create your own stencil component library that provides a cascading dropdown component and implements a driver for the UI hint. This process will be documented.
