### ISSUE TITLE
HttpEndpoint Security

### ISSUE THREAD

**Issue by sfmskywalker** [elsa-workflows/elsa-core#705]
See [this discussion](https://github.com/elsa-workflows/elsa-core/issues/249#issuecomment-681849375) that sparked this issue for a little bit more background.

Currently, users can expose their workflows as HTTP endpoints via the **HttpEndpoint** activity. What is missing though, is the ability to protect this endpoint to prevent unauthorized requests.

There are a number of strategies we might want to enable, and this issue aims at collecting these, after which we might create separate issues to implement them.

- [ ] SAS tokens (Orchard Core style)
- [ ] Simply rely on ASP.NET Core security middleware (requires documentation)
- [ ] Trigger domain events (allowing the application to perform authenticating the request)

**Comment by DavidPx** [comment]
I see Asp Net security middleware as the most useful mechanism for the work I do. 

One can decorate a controller or route with an authentication attribute, why not an entire workflow or HttpReceive activity?

**Comment by dannmartens** [comment]
Is there any workaround documented to secure HTTP against the current baseline 1.5.3.1369?

Do you think it can be achieved with additional DI wiring? We want to use an API key header to protect the endpoint.

We tried to provide a SecureReceiveHttpRequest, but found we could not get the activity recognized as a specialization of ReceiveHttpRequest. Somewhere in the code base, we found hardcoded keying on nameof(ReceiveHttpRequest) which would explain that.

**Comment by sfmskywalker** [comment]
No documentation that I know of. One solution could be to create a fork and make modifications to the `TriggerRequestHandler` implementation so that you can control what workflows will match the incoming request. Alternatively, you could continue with the custom `SecureReceiveHttpRequest` implementation by copying the `TriggerRequestHandler` into your own project, make modifications as needed, and use that one instead of the original one.
