### ISSUE TITLE
Workflow instances are not persisted when they should be

### ISSUE THREAD

**Issue by craigfowler** [elsa-workflows/elsa-core#728]
As demonstrated in the code at https://github.com/craigfowler/elsa-core/commit/672e32a7caae61355e928bc4c299e3687f468d17 (the new test added in this commit), the workflow instance which is created in this test never makes it to the MongoDb persistence store.  This is despite the workflow including a `UserTask` activity which would suspend the workflow and preventing it from completing immediately.

This issue is to diagnose and fix this issue with workflow persistence.  It has been proven to affect MongoDb and also anecdotally affects Entity Framework.  **Update**: This is confirmed to affect all persistence, _not just MongoDb_.

## Acceptance criteria
* A workflow should be persisted at at least one point after it has begun executing
* Test coverage must be added to prove that this works with at least an in-memory persistence store (ideally add a MongoDb test case as well)
* The default persistence behaviour for a workflow _should be altered to be_ `WorkflowPersistenceBehavior.WorkflowBurst` (currently it is implicitly `Suspended`)

**Comment by craigfowler** [comment]
## Discussion copied from Discord
Here's a snippet of discussion from the Elsa Discord server, related to this:

@craigfowler
> I'm trying to write a test to repro #552 which relates to exceptions when loading saved workflow instances. Rather frustratingly I've fallen at the first fence because workflow instances aren't being saved to the MongoDB at all (no exceptions, they just don't show up in the db).  As far as I can tell MongoDbWorkflowInstanceStore.SaveAsync never gets executed at all, so there's no attempt to save them.
> 
> I based my test (roughly) on the sample at src/samples/persistence/Elsa.Samples.Persistence.EntityFramework/Program.cs except of course using MongoDB instead.
> 
> I've pushed the test itself up to https://github.com/craigfowler/elsa-core/blob/feature/552-mongodb-serialization/test/integration/Elsa.Core.IntegrationTests/Persistence/MongoDb/MongoDbIntegrationTests.cs
> 
> In that test file, it fails on line 33 because the retrievedInstance comes back null, when I would have expected it to be either:
> * The same object instance as instance
> * An instance of WorkflowInstance that is value-equal to instance
> 
> I actually don't know MongoDB well enough to know which of those two I would get, does it use an internal identity map to keep references to the same stored object reference-equal in C#?  Which of those two things happens isn't particularly relevant to me right now though.  You can/should ignore the assertion on line 34, that's just for my own benefit to learn what happens.
> 
> After running that test, I take a look at what's inside my local MongoDb via the CLI.  I can see the IntegrationTests db and I can see various collections including WorkflowInstances.  I can also see that execution logs have been saved, because db.WorkflowExecutionLog.find() produces plenty of results.  On the other hand db.WorkflowInstances.find() gives me a big bag of nothing.
> 
> Am I doing (or not-doing) something silly here?  Or have I accidentally managed to find a secondary bug whilst trying to fix the first?  Halp!

"Razvan" (not sure of Github alias, sorry)
> I also had a quick look and I can confirm that the issue is not related to the MongoDb provider. I created a similar `SqlServerIntegrationTests` and used `HostBuilderWithElsaSampleWorkflowAndSqlServerAttribute`. It seems like `RunWorkflowAsync()` doesn't persist a workflow instance, but I also don't know if it should.

@sfmskywalker 
> I think I know why. By default, workflow instances get only saved when they get suspended. If they complete immediately in the other hand they do not get persisted unless you change the persistence behavior of the workflow definition.

@craigfowler 
> Well, I did consider that. That's why I put an activity (the UserTask) in there which would would suspend it.

## Next steps
@sfmskywalker - what is the intended/correct behaviour here?
* Workflow instances are only persisted if they must enter a suspended state?
* Workflow instances should always be persisted?

I did notice [what looks like a configuration option here] relating to deleting completed workflows from persistence, but that doesn't seem to have any direct effect on this issue.

Once we know exactly what _should_ happen, we can get coding it to make sure that that's what _does_ happen 😄 

[what looks like a configuration option here]: https://github.com/elsa-workflows/elsa-core/blob/feature/elsa-2.0/src/core/Elsa.Core/Handlers/PersistWorkflow.cs#L71

**Comment by sfmskywalker** [comment]
@craigfowler 

> @sfmskywalker - what is the intended/correct behaviour here?
> 
> * Workflow instances should only be persisted if they must enter a suspended state?
> * Workflow instances should always be persisted?

The intended behavior depends on the configured `PersistenceBehavior` setting on the workflow:

```csharp
public enum WorkflowPersistenceBehavior
{
    /// <summary>
    /// Workflow instances are persisted only when being suspended. 
    /// </summary>
    Suspended,
    
    /// <summary>
    /// Workflow instances are persisted after the workflow completed a burst of execution.
    /// </summary>
    WorkflowBurst,
    
    /// <summary>
    /// Workflow instances are persisted after the workflow executed scheduled activities.
    /// </summary>
    WorkflowPassCompleted,

    /// <summary>
    /// Workflow instances are persisted after each activity that executed.
    /// </summary>
    ActivityExecuted
}
```

**Comment by sfmskywalker** [comment]
@craigfowler 

> Well, I did consider that. That's why I put an activity (the UserTask) in there which would would suspend it.

If the workflow doesn't get suspended while encountering a `UserTask` activity, then that's a bug.

**Comment by craigfowler** [comment]
Yep, that's what I'll be looking at tonight then 😎

**Comment by sfmskywalker** [comment]
Awesome 🌚 Thanks Craig.

**Comment by craigfowler** [comment]
FYI I've repro'd this with in-memory persistence as well, so it seems like it affects all persistence providers (as @rzvdaniel suggested might be the case).

**Comment by rzvdaniel** [comment]
Hi, all!

I just realized that a WorkflowDefinition has PersistenceBehavior defaulting to WorkflowPersistenceBehavior.Suspended. Is this intended?

I'm asking because I had issues to understand why a bare declarative workflow I created wasn't persisted. After setting PersistenceBehavior  to WorkflowPersistenceBehavior.WorkflowBurst, it worked.

Best!
Razvan

**Comment by sfmskywalker** [comment]
It was indeed intended, but in hindsight I can see how it would confuse newcomers that a workflow instance isn’t persisted for workflows that finish immediately without hitting a blocking activity.

Therefore I think we should change the default behavior to WorkfowBurst, which will cause the workflow instance to be persisted after every burst of execution.

**Comment by rzvdaniel** [comment]
Great stuff!

This may also fix this issue? :)

**Comment by sfmskywalker** [comment]
Yeah maybe, although there might still be a bug of a workflow starting with a UserTask activity indeed doesn’t get persisted. I asked @craigfowler for a repro for me to look at to make sure everything’s up to snuff.

**Comment by rzvdaniel** [comment]
Thanks, I am not aware of UserTask activity being so special. :P

I've followed your discussion, but I don't understand why the UserTask should make the workflow be persisted?

**Comment by craigfowler** [comment]
Yeah. I spotted that as I was picking through. I was so focused on the persistence that I didn't notice that the workflow runner itself was bailing and never even reaching the latter stages of the process.

Even after changing that though so that the first activity wasn't a user task, it still didn't persist 😒

What I'm expecting to find is where the runner sends a notification to the mediator, which then triggers the persistence service.

Just can't get to that point though. Will pick up again tomorrow evening.

**Comment by sfmskywalker** [comment]
That’s the thing: it shouldn’t be any more special than any other blocking activity such as Timer, HttpEndpoint etc.

The reason the workflow *should* be persisted is because anytime a blocking activity is encountered, the workflow is supposed to be persisted so that whenever the appropriate signal comes in to resume the workflow, we got a workflow to resume.

**Comment by rzvdaniel** [comment]
Got it: this is the default behaviour of blocking activities. Thanks!

**Comment by craigfowler** [comment]
W00t, I now feel like I'm making some progress with this!  In part because I've figured out what I had been doing wrong with the workflow design.  _Apologies, lots of words, but there's lots of info!_

## Workflows which immediately halt/suspend are never really started
There is a bit of [a "gotcha" in the functionality] here, which was introduced by #589.  This means that **if the workflow's first activity cannot be executed** then the workflow runner will bail out early and fail to do anything interesting.  _I presume that_ this was intended to deal with scenarios in which the workflow is intended to be started-off by an external input.  This would include receiving HTTP requests, timers, signals and the like.  Until it has actually received that specific input, the workflow shouldn't really get started, even if something tried to start it in another fashion.  I assume that code change in #589 was to prevent workflow instances from performing "false starts" and creating lots of 'zombie workflows'.  _(hehe, there's an amusing mental image)_

This does mean that you must watch out if you write a workflow _which starts with a blocking activity_ (such as the following example).  Unless you supply the appropriate inputs when calling `IWorkflowRunner.RunWorkflowAsync` (in this case an input value which matches one of the `Actions`) then your workflow instance will never really get started properly.  This is because the logic from #589 will detect it as a false-start and bail-out early.  _It will certainly never reach any point where it persists that workflow._

```csharp
builder
  .StartWith<UserTask>(/* Whatever config */)
  // Continue the workflow
```

@sfmskywalker does that sound like a reasonable assessment and are my presumptions about the intent of that logic roughly correct?  Also - is that indeed what you intended?

@rzvdaniel - this might also be the source of the confusion over how `UserTask` or `Timer` or such seemed to have special/quirky/different behaviour.  None of them do.  Really _what causes different behaviour_ is when the blocking activity is the first activity in the workflow.

_I was just unlucky when I created a simple minimal workflow for testing._  My face is certainly red now :facepalm: 

[a "gotcha" in the functionality]: https://github.com/elsa-workflows/elsa-core/blob/feature/elsa-2.0/src/core/Elsa.Core/Services/WorkflowRunner.cs#L206

## We are in better shape than it seems!
Now I have resolved the 'gotcha' above, things are actually looking better than it seems.  The bug here isn't quite as originally described.  The reasons my workflows didn't persist are:

* At first, I hadn't been putting anything into them which would suspend them (and so the default persistence behaviour meant they never persisted)
* But then when I did put something into them to suspend them, I was unlucky and started with the halting activity, which triggered the quirk noted above

Now that I have created a workflow which triggers neither of these behaviours I am seeing much better results!

## We do still seem to have a bug with `ActivityExecuted` behaviour
While I was writing test cases for the above, I figured that I may as well write test cases for _all of the persistence behaviours_!  I found that:

* Assuming the activity suspends (but not in its starting activity) then when the workflow blueprint is set to use `WorkflowPersistenceBehavior.Suspended` _it persists OK_
* When the blueprint uses `WorkflowPersistenceBehavior.WorkflowBurst` _it persists OK_
* When the blueprint uses `WorkflowPersistenceBehavior.WorkflowPassCompleted` _it persists OK_
* When the blueprint uses `WorkflowPersistenceBehavior.ActivityExecuted` **it does not persist at all**

Currently, persistence after each individual action execution _is not occurring_.  I'm going to continue looking into that in this issue.  From a really quick search around the codebase, it seems that this persistence behaviour is never used :laughing: .  @sfmskywalker  - would I be right in assuming that somewhere after an individual activity is executed, the mediator should publish a notification about it, with the usual workflow context info, and that `Elsa.Handlers.PersistWorkflow` should deal with such a notification? :wink:

**Comment by craigfowler** [comment]
Aha, [I have found where the mediator does indeed publish a notification about executing an activity].  Perhaps it's just that nobody was listening :thinking: 

[I have found where the mediator does indeed publish a notification about executing an activity]: https://github.com/elsa-workflows/elsa-core/blob/feature/elsa-2.0/src/core/Elsa.Core/Services/WorkflowRunner.cs#L350

**Comment by rzvdaniel** [comment]
Very interesting explanation, @craigfowler. 

Some of the above can easily go into documentation, like in a QA section where you answer the question "_Why my workflow instances aren't persisted_"? Same for the explanation of `WorkflowPersistenceBehavior`(s), it can be a section the **Workflow Persistence** chapter.

This ticket is revealing more details that you may have been thinking in the beginning.
