### ISSUE TITLE
Question regarding fork/join + final status

### ISSUE THREAD

**Issue by vip32** [elsa-workflows/elsa-core#729]
Am new to Elsa, see it as very interesting and usable. Especially the upcoming 2.0!

I have a workflow (Elsa v2.0) with a fork/join construct (like [DemoWorkflow](https://github.com/elsa-workflows/elsa-core/blob/1daed3c1c364111fec2a71f8292f90bde9492a75/src/samples/aspnet/Elsa.Samples.ForkJoinTimerAndSignalHttp/Workflows/DemoWorkflow.cs#L14)). Both branches in the fork wait for a signal (approve or reject). This works fine.

When i approve or reject the workflow goes to the end, however when i then retrieve the context the status is always 'Running'.  Was expecting 'Finished' here. When i remove the fork/join construct from the workflow the context has the status Finished in the end.

Am i something missing here? Putting .Finish() at the end doesn't make a difference. Any help is kindly regarded.

**Comment by sfmskywalker** [comment]
Could you provide a repro that I can look at?

**Comment by vip32** [comment]
The workflow can be found [here](https://github.com/vip32/elsa-workflow-sample/blob/06743261f5a17baec07b0aa60fa244034bd56081/Presentation.Web/Presentation.Web/Server/Workflows/DemoHttpWorkflow.cs#L13).

Simular to the [DemoWorkflow](https://github.com/elsa-workflows/elsa-core/blob/1daed3c1c364111fec2a71f8292f90bde9492a75/src/samples/aspnet/Elsa.Samples.ForkJoinTimerAndSignalHttp/Workflows/DemoWorkflow.cs#L14) from the samples. Persistent workflow context storage has been added, and the start + signals are done through my own [controller](https://github.com/vip32/elsa-workflow-sample/blob/06743261f5a17baec07b0aa60fa244034bd56081/Presentation.Web/Presentation.Web/Server/Controllers/DemoHttpWorkflowController.cs#L14).

Maybe you can see the issue... thx!

**Comment by vip32** [comment]
As a workaround i am using the following at the end of the worklow, so they will be marked Finished. Not ideal but for now i can work with this. Did i hit a bug in the new 2.0?

```.Then(context => context.WorkflowInstance.WorkflowStatus = WorkflowStatus.Finished)```

**Comment by sfmskywalker** [comment]
@vip32 Lot's of changes have been pushed since this issue was reported. Could you try and see if you are still running into this issue with the latest version?

**Comment by sfmskywalker** [comment]
I haven't noticed any issues with the Fork/Join activities of late, so I'm closing this issue. If you are still seeing the reported issue after upgrading the Elsa packages, then please reopen this ticket. Thanks.
