### ISSUE TITLE
Publish docker images

### ISSUE THREAD

**Issue by jwillmer** [elsa-workflows/elsa-core#733]
Offer a docker image so that users can quickly test the current state of Elsa.

**Comment by sfmskywalker** [comment]
Great idea 👍

**Comment by sfmskywalker** [comment]
Dockerfile + compose added here: https://github.com/elsa-workflows/elsa-core/commit/cb05f36919242bc7c096f3a24708ec981df6ef71

Will push to Docker registry.

**Comment by sfmskywalker** [comment]
I.e. update CI/CD to do this automatically.

**Comment by jwillmer** [comment]
@sfmskywalker maybe introduce multiple image tags?

- stable (latest published version)
- latest (latest master build)
- v1.0.0.0 (a tag for each version)

**Comment by craigfowler** [comment]
Agree with @jwillmer 100%

**Comment by sfmskywalker** [comment]
Sure, let’s do it.

**Comment by jwillmer** [comment]
Latest build is taken from branch `elsa-2.0` and we have a first [successful run ](https://github.com/elsa-workflows/elsa-core/actions/runs/720215365)1!!111! We have now [docker images](https://github.com/orgs/elsa-workflows/packages/container/package/elsa-core%2Felsa-dashboard) for `linux/amd64`, `linux/arm64` and `linux/arm/v7` for the dashboard 😃

**Comment by jwillmer** [comment]
@sfmskywalker I added an additional workflow for elsa-dashboard:[tag] and :stable builds in the main branch. It only triggers if the tag starts with a `v` like `v1.0.0.0`. So the next release tag should start with a `v`. I used this format because we already have a `preview7` tag that should not be triggering the workflow since it is not a stable build.

**Comment by jwillmer** [comment]
Note: When merging the elsa-2.0 branch we need to update the workflow `publish-latest-dashboard.yml` to trigger new image:latest builds on master instead of elsa-2.0.
