### ISSUE TITLE
Database growing fast

### ISSUE THREAD

**Issue by aali0906** [elsa-workflows/elsa-core#742]
I am having a problem with a fast growing db. About 200 MB each day. The main problem is that the larger the database gets the slower http requests become until they run into timeouts. An https request which usally takes less than a second suddenly takes minutes.

There are currently several hundred request each day. Every request impacts the database by at least 12kb.

**Comment by sfmskywalker** [comment]
This is indeed an issue with Elsa 1 - it stores activity execution log entries in the workflow instance. So the more workflow instances execute, the bigger the database gets.

Elsa 2 doesn't have this problem - it stores workflow execution log entries in a separate collection/table. Although the database will still grow in size as workflows execute, it won't affect the performance of the engine or the dashboard.
And even though we don't have retention settings on the backlog (I don't think at least), you can safely delete workflow execution log records as you see fit. Or move them to an archive.

I understand this doesn't help you with your current situation of course, but this is one of the problems being solved with Elsa 2.
If you don't use (or necessarily need) the designer, I highly recommend migrating to Elsa 2. If you absolutely do need the designer, then hopefully you might consider migrating sometime in April, as I expect the designer to be stable enough to be actually used for real world workflows.

**Comment by craigfowler** [comment]
I'm going to close this, as this has already been addressed in Elsa 2 and will not be in Elsa 1.x
