### ISSUE TITLE
As a developer, to support a multi-tenant app, I must be able to select entity framework context at runtime, via DI

### ISSUE THREAD

**Issue by craigfowler** [elsa-workflows/elsa-core#748]
In an application deployment, it must be possible to select an Entity Framework DB Context instance for Elsa at run-time rather than doing so upfront (during DI setup).  The particular use-case we have in mind for this is multi-tenancy.  We have an app which can connect to one of many databases per-operation (such as per HTTP request); this concept will need to be extended to Elsa.  Which database the application connects to depends upon 'injectable' services (in our case the current database ID is stored within the authenticated user's **claims**).

## Background
Some work was carried out by @craigfowler upon a closed-source app which is integrating Elsa.  This work was performed against the **Elsa 1.4.6** codebase.  This issue is essentially _to share some of that work back upstream_ into Elsa, as applicable.  Because Elsa has moved on since 1.4.x, some it may well have already been done.

## Acceptance criteria
* It must be possible to select the Entity Framework DB Context using a DI-compatible delegate
* Features such as pooling/caching, which could be troublesome in a multi-tenant environment must become elective (although it is OK to leave them enabled by default)
* Appropriate tests must be written

## Limitation of scope
This issue is not a general "make Elsa support multi-tenancy" issue.  It might help guide the conversation in a broader sense, but it is initiated by _the specific desire to share some enhancements upstream_.

**Comment by Rafael94** [comment]
Hi @craigfowler,

in the ABP framework they solved it by introducing an interface (`IConnectionStringResolver)`. This is then used in `DbContextOptionsFactory`.

Would be at least one approach.

**Comment by craigfowler** [comment]
Notable files of interest.  These two files are conceptually equivalent across the two versions of Elsa.  It is here that the (originally closed-source) enhancements were made (against the 1.4.6 version).

* [The Elsa 1.4.6 `EFCoreServiceCollectionExtensions` class](https://github.com/elsa-workflows/elsa-core/blob/1.4.6/src/persistence/Elsa.Persistence.EntityFrameworkCore/Extensions/EFCoreServiceCollectionExtensions.cs)
* [The Elsa 2.0 `ServiceCollectionExtensions` class](https://github.com/elsa-workflows/elsa-core/blob/7cfe24ba9479dd1fdc58763df0c59e644dbd0d46/src/persistence/Elsa.Persistence.EntityFramework/Elsa.Persistence.EntityFramework.Core/Extensions/ServiceCollectionExtensions.cs)

**Comment by craigfowler** [comment]
@Rafael94 Ah yes, that seems like the kind of thing I'd be going for if I were developing a very specific approach.

Actually, I have gone for a broader and less prescriptive approach in the PR I just submitted.  In Elsa 2, there is already facility to resolve contexts from an `IDbContextFactory<ElsaContext>`; that wasn't present in 1.4.6 but in Elsa 2 it's now the default.  The main thrust of the PR is actually to reinstate the functionality which allows the developer to avoid using Context Pooling.  This means that in a multi-tenant environment the developer of the consuming app might do something like this:

```csharp
serviceCollection.AddElsa(elsa => {
  elsa.UseNonPooledEntityFrameworkPersistence(builder => {
    builder.ReplaceService<IDbContextFactory<ElsaContext>, MyFunkyElsaContextFactory>();
  }, ServiceLifetime.Scoped);
});
```

In `MyFunkyElsaContextFactory` the developer has full control over how they want to create an `ElsaContext`, such as varying connection strings.  They can do whatever makes sense in the context of their own application.

It has indeed turned out that some of the work we originally did in the closed-source project has already been "done for free" in Elsa 2.0 (such as being able to use a factory instead of just a single context instance).

**Comment by kassemdarwish** [comment]
In addition to connecting to different database by changing the connection string by tenant, you might actually want to register a different implementation of a given workflow as per the requirements of the different tenants. Some of the scenarios that I think should be supported by the `AddWorkflow()` ([link](https://github.com/elsa-workflows/elsa-core/blob/master/src/core/Elsa.Core/Extensions/ElsaServiceCollectionExtensions.cs)) method are the following:

- Generic method with a factory method which resolves the instance at runtime.
- A non-generic method which allows locating the type at runtime (maybe from an assembly configured by tenant) and then instantiates the workflow implementation which implements a given interface.

What do you think?
