### ISSUE TITLE
Latency problem with TriggerSignalAsync

### ISSUE THREAD

**Issue by DNDevCode** [elsa-workflows/elsa-core#750]
Hi, 

- we use Signaled Activity as first activity of my workflow. 
- To create an instance of my workflow , we call TriggerSignalAsync("firstActivityName") of WorkflowInvoker.
- As the number of instances grows,  calling triggerSignalAsync cause latency problem. I guess that triggerSignalAsync is looking for all instances that have an activity signaled "firstActiviryName"

Is there a way to create a workflow instance based on the first reported activity? in other words, only search for workflow definitions those whose first activity of type SIGNALED matches the "first activity name" ?

Thanks

**Comment by sfmskywalker** [comment]
Yes indeed. This is fixed in Elsa 2. The behavior there is exactly what you suggested to do: get only the workflows that are starting by the **SignalReceived** (the new name for **Signaled**) that matches the _signal name_.
