### ISSUE TITLE
Elsa + Actor Model

### ISSUE THREAD

**Issue by sfmskywalker** [elsa-workflows/elsa-core#757]
This issue is sprouted from [this discussion](https://github.com/elsa-workflows/elsa-core/discussions/708#discussioncomment-476515).

Elsa 2 already solves the problem of being able to run on a multi node environment, but it has some challenges still. As I started to contemplate improvements, I remembered the discussion linked above that was started.

Long story short: Orleans would enable Elsa to be truly & massively scalable.

When done, we might consider Akka.net after for those whom prefer that platform.

**Comment by sfmskywalker** [comment]
After doing a bit more research, I'm now considering to provide an initial implementation using [Proto.Actor for .NET](https://github.com/AsynkronIT/protoactor-dotnet). It was created by one of the creators of Akka.net en seems to have taken lessons learned from both Akka.net as well as Orleans. It also looks like the repo is actively being maintained again as of last year.

**Comment by Adrian-Grimm** [comment]
@sfmskywalker where is the integration of http://proto.actor ?

**Comment by sfmskywalker** [comment]
Hi @Adrian-Grimm , you can find it in the `v3` branch form where the integration is provided via the `Elsa.ProtoActor` class library. This library provides a concrete implementation for `IWorkflowRuntime` called `ProtoActorWorkflowRuntime`.
