### ISSUE TITLE
Cannot install Elsa.Persistance.EntityframeworkCore on Dotnet Core 3.1 project

### ISSUE THREAD

**Issue by madhavabhyankar** [elsa-workflows/elsa-core#767]
I get this error - 
NU1202: Package Elsa.Persistence.EntityFrameworkCore 1.5.3.1369 is not compatible with netcoreapp3.1 (.NETCoreApp,Version=v3.1). Package Elsa.Persistence.EntityFrameworkCore 1.5.3.1369 supports: net5.0 (.NETCoreApp,Version=v5.0)

**Comment by craigfowler** [comment]
I _think_ that this is correct and by-design.

I recall there being some required tech that meant a minimum of .NET 5 is required for some parts of Elsa 1.5.

**Comment by madhavabhyankar** [comment]
NVM.  This is a non issue.
