### ISSUE TITLE
Exception when trying to create a new workflow definition

### ISSUE THREAD

**Issue by hpposch** [elsa-workflows/elsa-core#776]
Hi,
i just pulled the latest feature/elsa-2.0 branch, because i wanted to see how things are going.
Anyway when i want to create a new Workflow i can not do this because i always get this exception:

`Microsoft.AspNetCore.Components.Server.Circuits.RemoteRenderer[100]
      Unhandled exception rendering component: Failed to fetch dynamically imported module: https://localhost:11000/_content/Elsa.Designer.Bindings.Blazor/elsa-workflows.js
TypeError: Failed to fetch dynamically imported module: https://localhost:11000/_content/Elsa.Designer.Bindings.Blazor/elsa-workflows.js
      Microsoft.JSInterop.JSException: Failed to fetch dynamically imported module: https://localhost:11000/_content/Elsa.Designer.Bindings.Blazor/elsa-workflows.js
TypeError: Failed to fetch dynamically imported module: https://localhost:11000/_content/Elsa.Designer.Bindings.Blazor/elsa-workflows.js
         at Microsoft.JSInterop.JSRuntime.InvokeAsync[TValue](Int64 targetInstanceId, String identifier, Object[] args)
         at Elsa.Designer.Bindings.Blazor.WorkflowEditor.OnAfterRenderAsync(Boolean firstRender) in C:\elsa\src\designer\bindings\blazor\Elsa.Designer.Bindings.Blazor\WorkflowEditor.razor:line 20
         at Microsoft.AspNetCore.Components.RenderTree.Renderer.GetErrorHandledTask(Task taskToHandle)
fail: Microsoft.AspNetCore.Components.Server.Circuits.CircuitHost[111]
      Unhandled exception in circuit 'Gv3sykq0zciAeXTGpJPI3NdARMdWWWPHWe9kkgjVm-A'.
      Microsoft.JSInterop.JSException: Failed to fetch dynamically imported module: https://localhost:11000/_content/Elsa.Designer.Bindings.Blazor/elsa-workflows.js
TypeError: Failed to fetch dynamically imported module: https://localhost:11000/_content/Elsa.Designer.Bindings.Blazor/elsa-workflows.js
         at Microsoft.JSInterop.JSRuntime.InvokeAsync[TValue](Int64 targetInstanceId, String identifier, Object[] args)
         at Elsa.Designer.Bindings.Blazor.WorkflowEditor.OnAfterRenderAsync(Boolean firstRender) in C:\elsa\src\designer\bindings\blazor\Elsa.Designer.Bindings.Blazor\WorkflowEditor.razor:line 20
         at Microsoft.AspNetCore.Components.RenderTree.Renderer.GetErrorHandledTask(Task taskToHandle)`
         
I never come to the editor page because it always crashes before it can load.
What can i do here?

**Comment by sfmskywalker** [comment]
It looks like the necessary client assets aren’t there in the wwwroot folder of the designer bindings for Blazor. If so, you’ll need to build these assets by running a couple of NPM scripts from the designer project and the bindings project.

We will document this.

**Comment by hpposch** [comment]
This would be great, because i would like to see the behavior of the current designer so that i can try to implement it the same way..
Is there a way that you can provide these scripts for me?

**Comment by hpposch** [comment]
Just to mention, i am running the 'ElsaDashboard.Samples.Monolith' project...

**Comment by tomy2105** [comment]
This is what I did:

1. Install node.js
2. go to src\designer\elsa-workflows-studio
3. run npm ci (or npm install)
4. run npm run-script build:prod
5. If step 4 gives you some weird errors about stencil not being recognized try doing "npm install @stencil/core@latest --save-exact" and repeating step 3 and 4
6. go to src\designer\bindings\blazor\Elsa.Designer.Bindings.Blazor
7. run npm ci (or npm install)
8. run npm run-script build
9. Go to Elsa sln and build it from Visual Studio....

This worked for me (at least as far as I remember, it was last week :)).
Try and let me know if you have any problems.

**Comment by hpposch** [comment]
Thank you very much for that, this worked for me :)

**Comment by tomy2105** [comment]
If @sfmskywalker approves I could do a pull request adding these steps into root Readme.md
