### ISSUE TITLE
For clarity, users should have better UX when importing workflows

### ISSUE THREAD

**Issue by tomy2105** [elsa-workflows/elsa-core#780]
> Export doesn't seem to contain name/description of the workflow.
This is not an issue, but the rest is....

In addition, when you press import (and file picker dialog is displayed) you are taken to, empty, home screen. 
Import is done OK but the user experience is confusing.

**Comment by tomy2105** [comment]
In addition import seem to "preserve" workflow ID (as well as activites Ids I guess) , which makes it confusing.
And creates new workflow (if one with same ID doesn't exist)
Due to that, import being button on, existing, workflow is confusuing since it won't import anything into that workflow but create new one (or update existing) with same id?!?!?

**Comment by jdevillard** [comment]
> Export doesn't seem to contain name/description of the workflow.
> 
> In addition, when you press import (and file picker dialog is displayed) you are taken to, empty, home screen.
> Import is done OK but the user experience is confusing.

Hello, don't know what is you commit, but it seems to have the name, displayName and description in the export. Please note that the serializer has the following configuration : 
settings.NullValueHandling = NullValueHandling.Ignore;

so if your property is empty, you will not see this property in the JSON exported.

```json
 "$id": "1",
  "definitionId": "6333738e24d74795992ec5f84c1fcbe6",
  "versionId": "554f3016471146a49957be537cd02204",
  "name": "TestSB",
  "displayName": "TestSB",
  "description": "Description of my workflow",
  "version": 25,
  "variables": {
    "$id": "2",
    "data": {}
  },
  "customAttributes": {
    "$id": "3",
    "data": {}
  },
  "isSingleton": false,
  "persistenceBehavior": "WorkflowBurst",
  "deleteCompletedInstances": false,
  "isPublished": false,
  "isLatest": true,
```

**Comment by sfmskywalker** [comment]
Acknowledged. For your info, the dashboard + designer you are currently looking at is heavily under development. There are many lacking features and quirks and bugs abound. This is expected, but will of course be fixed and improved upon.

**Comment by sfmskywalker** [comment]
Importing workflows should now be a smooth experience. The imported workflow ID will now also be ignored to prevent the issue of overwriting a different workflow definition.
