### ISSUE TITLE
Workflow instances viewer

### ISSUE THREAD

**Issue by tomy2105** [elsa-workflows/elsa-core#784]
When I click on instance inside Workflow instances it tells me "Sorry, there's nothing at this address." 
Is this an error on my part while compiling or not implemented yet?

And although I have instance which had problems resolving JS expressions it is not visible anywhere in the list that it had errors :(.

**Comment by craigfowler** [comment]
@sfmskywalker I think you might need to help out on this one.  I've still not taken much of a look at the UI dashboard/designer components yet.  @tomy2105 is it right to assume that you are using a v2.0.0 preview?  That info might help get a good answer.  Thanks.

**Comment by tomy2105** [comment]
Yes. 2.0 preview, compiled from code....

**Comment by sfmskywalker** [comment]
Yep, this is a know missing feature. Perhaps we should start compiling a checklist of features to be implemented for 2.0. I realize that it might be confusing for folks to try out the preview bits and running up against all sorts of issues and missing features. Having a simple checklist might better communicate where we are at and what to expect.

**Comment by sfmskywalker** [comment]
This [Workflow Designer project](https://github.com/elsa-workflows/elsa-core/projects/2) is used to keep track of all the tasks to be done for the designer. I'll keep adding tasks there of things to be done, and assign the 2.0 milestone where applicable.

**Comment by tomy2105** [comment]
> 
> 
> Yep, this is a known missing feature. Perhaps we should start compiling a checklist of features to be implemented for 2.0. I realize that it might be confusing for folks to try out the preview bits and running up against all sorts of issues and missing features. Having a simple checklist might better communicate where we are at and what to expect.

Yes, please, if you could compile a list of items that are still on todo for 2.0 that would be extremely helpful.
Items like this one, and list of activities that do not function with designer yet like ForEach, Switch, etc...

**Comment by sfmskywalker** [comment]
Here it is: https://github.com/elsa-workflows/elsa-core/issues/721 - please feel free to add to the comments section anything else you find that hasn't been listed. Thanks!

**Comment by sfmskywalker** [comment]
Done:

![workflow-instance-viewer-demo](https://user-images.githubusercontent.com/938393/116420326-2c52e180-a83e-11eb-8d28-5e468bf5b4a6.gif)
