### ISSUE TITLE
For convenience, a user should be able to copy & paste activities into a workflow

### ISSUE THREAD

**Issue by craigfowler** [elsa-workflows/elsa-core#792]
In the UI workflow designer, there should be some form of mechanism allowing a 'standard copy/paste' functionality for activities.  This could work for a single activity, although if combined with a multi-selection mechanism, could copy/paste many activities together at once.

_This issue has been raised from #782, which originally described a few enhancement requests in a single issue._

**Comment by tomy2105** [comment]
I'm not sure if this is immediately visible from the task, but mentioning just to be sure.
Not only copy/paste withing one workflow should be supported but also between two different workflows.

**Comment by sfmskywalker** [comment]
This is a dupe of #393, but this one has a little bit more detail so I'm closing the other one.

**Comment by sfmskywalker** [comment]
This feature has now been implemented, but has a problem that will be fixed via #1430
