### ISSUE TITLE
To focus on an appropriate area of a workflow, users should be able to zoom in/out

### ISSUE THREAD

**Issue by craigfowler** [elsa-workflows/elsa-core#793]
In the UI workflow designer, users should be able to zoom in & out of their workflow.

_This issue has been raised from #782, which originally described a few enhancement requests in a single issue._

**Comment by tomy2105** [comment]
To be fair this was already mentioned in https://github.com/elsa-workflows/elsa-core/issues/703.
My apologies for duplicating.....

**Comment by sfmskywalker** [comment]
Good catch. I'll close this one since #703 was raised before. Thanks.

**Comment by craigfowler** [comment]
Good spot guys, I hadn't noticed the dupe!
