### ISSUE TITLE
To improve readability/usability, users should see activities & the editor background with improved contrast

### ISSUE THREAD

**Issue by craigfowler** [elsa-workflows/elsa-core#795]
It has been raised that the colour difference between activities & the editor background in the UI workflow designer is not as easy to read as it should be.  Whilst there is not a requirement for specific colours here, the styling should be revisited in order to improve readability/usability.

_This issue has been raised from #782, which originally described a few enhancement requests in a single issue._

_Also, as a personal aside from @craigfowler - please think of us poor colourblind users when doing that 😄_

**Comment by craigfowler** [comment]
Just to be fair - the state of the designer UI when this issue was raised was really an early draft of the functionality.  I don't think it was ever intended to go to production with that basic styling.

**Comment by tomy2105** [comment]
> Also, as a personal aside from @craigfowler - please think of us poor colourblind users when doing that 😄

Yes, you might use [https://snook.ca/technical/colour_contrast/colour.html#fg=FFFFFF,bg=FBFBFB](https://snook.ca/technical/colour_contrast/colour.html#fg=FFFFFF,bg=FBFBFB) to check, current result is obviously not good....

**Comment by sfmskywalker** [comment]
When this issue was reported, the background didn't have the grid tile loaded (it was 404-ing). I wonder if the contrast is good enough now that that has been fixed?

Here's a screenshot:

![image](https://user-images.githubusercontent.com/938393/116870037-106e8780-ac12-11eb-92cf-ebf3dc5f0373.png)

**Comment by tomy2105** [comment]
Not really :(.
The grid background color is almost the same as previous background color.
The white from block and gray background of the grid are simply too close contrast wise....

You should either darken the grid background more or put a "tiny" border around activity (just as you do when you hover) or select it (maybe the permanent border should be thinner and black and selected one bit thicker and blue).....

**Comment by sfmskywalker** [comment]
I like the border suggestion. What do you think of this?

![image](https://user-images.githubusercontent.com/938393/116873904-c0df8a00-ac18-11eb-93fd-13dcf98c5f06.png)

**Comment by tomy2105** [comment]
Better but I would personally make border a bit more darker, something like #ADB1A8.....

**Comment by sfmskywalker** [comment]
Interesting. To me it looks way too stark that way.
Obviously this is highly dependent on one's personal preferences, so perhaps a better idea might be to allow for a personalized stylesheet?

**Comment by sfmskywalker** [comment]
In any case, I am closing this issue since the issue of lack of contrast has been resolved (reopen if you disagree). If we want to do something with personalization, we can open a new issue.
