### ISSUE TITLE
Designer expression editor and code complete.

### ISSUE THREAD

**Issue by tomy2105** [elsa-workflows/elsa-core#803]
I see there is a code complete inside expression editor.
First question, if you see my image it seems cut off at the bottom (half of line), is this intentional or....?
Second question, could this code complete add support for named activities and their Output and children of it?

![CodeComplete](https://user-images.githubusercontent.com/7658839/112504173-d21cb780-8d8b-11eb-8b5a-abdac7af3567.png)

**Comment by craigfowler** [comment]
> if you see my image it seems cut off at the bottom (half of line), is this intentional or

I'm going to take a guess here, but I think it's just because it's a work in progress and not finished.  I think there's quite a bit of design & styling to be done once the baseline functionality is in-place.

> could this code complete add support for named activities and their Output and children of it?

Ah, now on this one there is already a discussion going on in #675 which (if I understood you correctly) might cross-over with what you're asking-for?

**Comment by tomy2105** [comment]
> > could this code complete add support for named activities and their Output and children of it?
> 
> Ah, now on this one there is already a discussion going on in #675 which (if I understood you correctly) might cross-over with what you're asking-for?

Yes, you are right, my idea of code complete containing other activities with names (the ones you can use in expressions) could be the answer to #675.

**Comment by sfmskywalker** [comment]
> First question, if you see my image it seems cut off at the bottom (half of line), is this intentional or....?

That's a visual glitch that I haven't been able to fox thus far. I even [asked for help about this on SO](https://stackoverflow.com/questions/66400588/monaco-editor-intellisense-not-full-height).

**Comment by matt4446** [comment]
Ah Monaco's suggestion window: I was looking at that with one of our UI guys yesterday. It was conflicting with `.tree` from tailwindcss for us. This is our current solution: 

```
.monaco-editor .suggest-widget div.tree {
    white-space: unset;
    padding-bottom: 0;
}
```

Which improves it:  
![image](https://user-images.githubusercontent.com/1550939/114564961-bd379380-9c68-11eb-8784-19ec63196671.png)

**Comment by sfmskywalker** [comment]
Elon Musk on a cracker, that was it! Thank you thank you 🙌🏻 🙏🏻 🎉 
It looks perfect now:

![image](https://user-images.githubusercontent.com/938393/114614408-bcbcee00-9ca4-11eb-8095-cd911c6a3c25.png)

What a save. This thing has been driving me nuts!

I owe you and your UI guys a beer.

THANK YOU 😄

**Comment by sfmskywalker** [comment]
@matt4446 If you like you can provide your answer here: https://stackoverflow.com/questions/66400588/monaco-editor-intellisense-not-full-height and I will mark it as the answer. Otherwise I will add it myself, just to make sure others find the answer as well should they run into it.
