### ISSUE TITLE
Elsa Dashboard not being loaded correctly

### ISSUE THREAD

**Issue by bigiayomide** [elsa-workflows/elsa-core#808]
just after configuring elsa and adding the dashboard and Elsa Service. when I navigate to the Elsa page seems like it is trying to load files from my server that do not exist. Please see attached screenshot. 

Service Registration
![image](https://user-images.githubusercontent.com/12390841/112619628-398c4300-8e30-11eb-86fb-f7b915aeeb16.png)

Elsa Issue. Dashboard not being loaded correctly.
![image](https://user-images.githubusercontent.com/12390841/112619729-5294f400-8e30-11eb-9422-832a0b97657f.png)

Version
Library : Elsa.DashBoard v1.5.3.1369 
Elsa v1.5.3.1369
Elsa.Persistence.FrameworkCore v1.5.3.1369

**Comment by sfmskywalker** [comment]
It looks like that maybe the build pipeline isn't building the client assets correctly.

**Comment by tomy2105** [comment]
Did you do following?
Go to src\dashboard\Elsa.Dashboard\Theme\argon-dashboard and execute:
npm install (or npm ci)
gulp build
Verify that wwwroot folder has been created in elsa-core\src\dashboard\Elsa.Dashboard.

**Comment by sfmskywalker** [comment]
The above steps are indeed necessary when building from the Elsa source code. But when referencing the packages, the assets should already be there.

**Comment by sfmskywalker** [comment]
I just tried to reproduce the issue by following the instructions [here](https://elsa-workflows.github.io/elsa-core/docs/guides-dashboard), but it worked out fine for me.

@bigiayomide can you try the following project on your local machine and let me know if you are seeing the same issue? And if so, can you share with me your solution source code so I can try it on my machine?

[WebApplication.zip](https://github.com/elsa-workflows/elsa-core/files/6211357/WebApplication.zip)

**Comment by bigiayomide** [comment]
Hi @sfmskywalker  I have figured out the issue, So It's actually on an API project and I did forget to Enable/UseStaticFiles in the Configure method. It now works fine. 

Thanks a lot

**Comment by sfmskywalker** [comment]
Ah that makes sense. Thanks for sharing what it was, this will help others in the future as well!
