### ISSUE TITLE
Publishing to Docker should be re-enabled with corrected credentials

### ISSUE THREAD

**Issue by craigfowler** [elsa-workflows/elsa-core#815]
Pull request #814 disables automated deployment to Docker, because of [a credentials error].  That error was causing build failures.

This issue is to correct the error and re-enable docker deployments (essentially reverse the changes made in that PR above).

[a credentials error]: https://ci.appveyor.com/project/sfmskywalker/elsa/builds/38438996#L6715

**Comment by sfmskywalker** [comment]
@jwillmer is handling this as part of #826 , so closing this one out.
