### ISSUE TITLE
Composite Activity are not executed when using WorkflowDefinition

### ISSUE THREAD

**Issue by jdevillard** [elsa-workflows/elsa-core#820]
I see that I cannot use a composite activity when using a Workflow Definition.

There is an sample of how to define a composite activity using WorkflowDefinition but it's not what I'm trying to achieve. I want to use a programmatic-defined composite activity.

The issue could be reproduce using a simple sample.

Here is a simple Composite Activity. 

```
 public class HelloWorldComposite : CompositeActivity
    {
        public override void Build(ICompositeActivityBuilder activity)
        {
                activity
                    .WriteLine("Hello World!")
                    .WriteLine("GoodBye World!");
        }
    }
```

if I define workflow by code like this, everything works as expected : 

```
public class HelloWorldCompositeWorkflow: IWorkflow
    {
        public void Build(IWorkflowBuilder builder) =>
            builder
            .Then<HelloWorldComposite>();

    } 
```

If I defined my workflow using a JSON (like the designer) or using directly the Workflow Definition Class : 

```
var workflowDefinition = new WorkflowDefinition
            {
                Id = "1",
                DefinitionId = "SampleWorkflow",
                Version = 1,
                IsPublished = true,
                IsLatest = true,
                PersistenceBehavior = WorkflowPersistenceBehavior.Suspended,
                Activities = new[]
                {
                    new ActivityDefinition
                    {
                        ActivityId = "activity-1",
                        Type = nameof(WriteLine),
                        Properties = new List<ActivityDefinitionProperty>()
                        {
                            ActivityDefinitionProperty.Liquid(nameof(WriteLine.Text), "Hello World")
                        }
                    }
                    , new ActivityDefinition
                    {
                        ActivityId = "activity-2",
                        Type = nameof(HelloWorldComposite),
                        Properties = new List<ActivityDefinitionProperty>()
                       
                    },
                },
                Connections = new[]
                {
                    new ConnectionDefinition()
                    {
                        SourceActivityId = "activity-1",
                        TargetActivityId = "activity-2",
                        Outcome = "Done"
                    }
                }
            };
```

The activity-2 is never executed.

This is a little bit annoying because it doesn't allow to create custom composite activity (as I do using some custom code in addition) and use it on the designer.

**Comment by sfmskywalker** [comment]
This might be a bug, because using programmed composite activities are supported since a couple of days or so as part of the work I’ve done on Telnyx activities. One of those activities is a composite and I encountered the same situation you are describing here. I fixed that as part of the Telnyx branch which was merged not too long ago.

Depending on when you last tried the above, you might want to try again (making sure to pull the latest version or update to latest packages).

If you are still seeing this issue then please do let me know and I will take a look.

**Comment by jdevillard** [comment]
Thanks I'm before telnyx PR, I'll test ASAP and let you know ! 

Thanks

**Comment by jdevillard** [comment]
I've updated to latest commit, everything seems to be ok. 

Thanks @sfmskywalker . 

(don't have already seen where the change have been made, but will take a look to be sure to understand the fix  :) )
