### ISSUE TITLE
Is it possible to programatically build ActivityProperty-ies?

### ISSUE THREAD

**Issue by tomy2105** [elsa-workflows/elsa-core#823]
The ones I've seen built in by default hardcode ActivityProperty (used to display in UI) in code.
Is it possible to programatically build (or change) ActivityProperty of and activity fields?
For example during service initialization.

**Comment by VahidNaderi** [comment]
I'm not sure if I get your issue well, but isn't it the obvious way to inherit an activity in order to make changes to it?

**Comment by tomy2105** [comment]
Thanks for the response @VahidNaderi, however my question was a little deeper :).
After you make your activity class, inheriting from `Activity` your class will have public member properties.
Some of these are displayed in designer UI for that activity.
C# attribute called `ActivityProperty` is used to control how UI will render this property in the designer.
Example taken from HTTP activity.

`

        [ActivityProperty(

            UIHint = ActivityPropertyUIHints.Dropdown,

            Hint = "The content type to send with the request.",

            Options = new[] { "text/plain", "text/html", "application/json", "application/xml", "application/x-www-form-urlencoded" }

        )]

        public string? ContentType { get; set; }

`

My question is: is there a way to build this attribute and its content programatically in the runtime, for example during program/service initialization/startup and not have it hardcoded in the code?
