### ISSUE TITLE
HTTP Endpoint/Send HTTP Request problem with "complex" Content-Type

### ISSUE THREAD

**Issue by tomy2105** [elsa-workflows/elsa-core#824]
Automatic request/response parsing won't work as expected, single string will be returned instead of an object for Body/Content, in case that request/response have content-type set to `application/json;charset=utf-8` (content-type has parts separated by `;`).

The problem seems to be the fact that whole content type is compared against the list of implemented content types. I think comparison should be done on "base" content-type (up to first `;`).

**Comment by sfmskywalker** [comment]
Thanks for [your fix](4384bdaab41722980c9e5f4f6a88fc1713d07f98)!
