### ISSUE TITLE
Feature request - Allow Activities etc to be loaded in as plugins via external class libs.

### ISSUE THREAD

**Issue by JamesNJonesIII** [elsa-workflows/elsa-core#830]
Could Elsa be coded to allow for activities and workflows to be loaded in from external libraries via say reflection in a plug in approach?

**Comment by sfmskywalker** [comment]
Sure. What changes would we need to make to Elsa in order for you to register activities from external libraries?

**Comment by craigfowler** [comment]
I think (based on @JamesNJonesIII username) that this issue has been raised as a follow-up to the chat in Discord?  Might be worth pasting some of that conversation into here for context.  It's the one about externally-loaded activities not appearing in the UI designer.

As already established though, in that particular case we are pretty confident that "it would just work" in Elsa 2.0 onwards.

If it turns out that "we get this for free" in Elsa 2, the only thing I'd suggest doing for this ticket in that case is adding some test coverage for it.  That would indicate that we've formally adopted it as a supported use-case and help us spot regressions against it.

**Comment by JamesNJonesIII** [comment]
> I think (based on @JamesNJonesIII username) that this issue has been raised as a follow-up to the chat in Discord? Might be worth pasting some of that conversation into here for context. It's the one about externally-loaded activities not appearing in the UI designer.
> 
> As already established though, in that particular case we are pretty confident that "it would just work" in Elsa 2.0 onwards.
> 
> If it turns out that "we get this for free" in Elsa 2, the only thing I'd suggest doing for this ticket in that case is adding some test coverage for it. That would indicate that we've formally adopted it as a supported use-case and help us spot regressions against it.

Sorry yes it @JamesNJonesIII and here's the discord conversation to add context:


Hi  All, I've got a question about if it's possible to load an activity from a claslib using reflection so that they can be loaded in from say a plugins folder? The code I wrote adds the activity to the IServiceCollection at startup (in web app), but when I look for the activity in the UI, it doesn't appear. If instead of doing this if I add it as a referenced project it works.

Craig Fowler — Today at 12:36
@JimbobIII which Elsa version are you using?  1.4, 1.5 or are you using a 2.0 preview?

JimbobIII — Today at 12:38
@Craig Fowler I'm using 1.5.3
[12:39]
@Craig Fowler   I can show you  sections of my code if that will help clarify?

Craig Fowler — Today at 12:46
I think I understand you.  You're loading an assembly dynamically as if it were a plugin, then using something like Assembly.GetExportedTypes() and registering each of those (which implement IActivity) with the service collection?(edited)

1

@Craig Fowler
I think I understand you.  You're loading an assembly dynamically as if it were a plugin, then using something like Assembly.GetExportedTypes() and registering each of those (which implement IActivity) with the service collection?(edited)

JimbobIII — Today at 12:49
So I have this in my web app     public static class UserServiceCollectionExtensions
    {
        public static IServiceCollection AddPluginActivities(this IServiceCollection services)
        {
            ////var pluginList = new List<Plugin>();
            var _pluginPath = $@"{AppDomain.CurrentDomain.BaseDirectory}\Plugins";
            var pluginTest = new Plugin { ModuleName = "Test.Activities", ClassName = "TestActivity", EntryPoint = "" };
            var pluginList = new List<Plugin>();
            pluginList.Add(pluginTest);


            foreach (var plugin in pluginList)
            {
                Assembly pluginLib = Assembly.LoadFile($"{_pluginPath}{plugin.ModuleName}.dll");
                var typesOfActivity = pluginLib.GetTypes().Where(w => w.FullName.EndsWith("Activity")).ToList();

                foreach (var activityType in typesOfActivity)
                {
                    Type serviceCollectionHelperType = pluginLib.GetType($"{plugin.ModuleName}.ServiceCollectionHelper");
                    //var serviceCollectionHelper = Activator.CreateInstance(pluginLib, serviceCollectionHelperType);

                    object[] myParams = new object[] { services };
                    //serviceCollectionHelper.GetMethod("AddToServiceCollection").Invoke(null, myParams);

                    MethodInfo methodInfo = serviceCollectionHelperType.GetMethod("AddToServiceCollection");

                    if (methodInfo != null)
                    {
                        object result = null;

                        object classInstance = Activator.CreateInstance(serviceCollectionHelperType, null);
                        object[] parametersArray = new object[] { services };

                        result = methodInfo.Invoke(classInstance, parametersArray);
                    }

                    var x = "";
                }
            };

            return services;

        }

JimbobIII
So I have this in my web app     public static class UserServiceCollectionExtensions     {         public static IServiceCollection AddPluginActivities(this IServiceCollection services)         {             ////var pluginList = new List<Plugin>();             var _pluginPath = $@"{AppDomain.CurrentDomain.BaseDirectory}\Plugins";             var pluginTest = new Plugin { ModuleName = "Test.Activities", ClassName = "TestActivity", EntryPoint = "" };             var pluginList = new List<Plugin>();             pluginList.Add(pluginTest);               foreach (var plugin in pluginList)             {                 Assembly pluginLib = Assembly.LoadFile($"{_pluginPath}{plugin.ModuleName}.dll");                 var typesOfActivity = pluginLib.GetTypes().Where(w => w.FullName.EndsWith("Activity")).ToList();                  foreach (var activityType in typesOfActivity)                 {                     Type serviceCollectionHelperType = pluginLib.GetType($"{plugin.ModuleName}.ServiceCollectionHelper");                     //var serviceCollectionHelper = Activator.CreateInstance(pluginLib, serviceCollectionHelperType);                      object[] myParams = new object[] { services };                     //serviceCollectionHelper.GetMethod("AddToServiceCollection").Invoke(null, myParams);                      MethodInfo methodInfo = serviceCollectionHelperType.GetMethod("AddToServiceCollection");                      if (methodInfo != null)                     {                         object result = null;                          object classInstance = Activator.CreateInstance(serviceCollectionHelperType, null);                         object[] parametersArray = new object[] { services };                          result = methodInfo.Invoke(classInstance, parametersArray);                     }                      var x = "";                 }             };              return services;          }

JimbobIII — Today at 12:49
And this in the classlib public class ServiceCollectionHelper
    {
        public void AddToServiceCollection(IServiceCollection services)
        {
            services.AddActivity<TestActivity>();
        }
    }

Craig Fowler — Today at 12:51
Huh.  That looks like it should work.  I was wondering if you'd done everything that's shown at this linked code, but you're actually executing that linked code rather than duplicating it.
https://github.com/elsa-workflows/elsa-core/blob/master/src/core/Elsa.Core/Extensions/ElsaServiceCollectionExtensions.cs#L47
GitHub
elsa-workflows/elsa-core
A .NET Standard 2.0 Workflows Library. Contribute to elsa-workflows/elsa-core development by creating an account on GitHub.

[12:53]
I'm not too familiar with the logic in the UI designer app (I mainly focus my attention on Elsa core at the moment), but I wonder if it does anything differently in order to discover activity classes (instead of just resolving an IEnumerable<IActivity> ).  Lemme go check.
[12:59]
@JimbobIII You've nailed it with your repro description.
[13:00]
I've got your root cause right here:
https://github.com/elsa-workflows/elsa-core/blob/1.5.3/src/dashboard/Elsa.Dashboard/Extensions/ActivityDefinitionListExtensions.cs#L35
GitHub
elsa-workflows/elsa-core
A .NET Standard 2.0 Workflows Library. Contribute to elsa-workflows/elsa-core development by creating an account on GitHub.

[13:03]
It relates to the discovery process which the Designer/Dashboard uses, in order to discover which activity definitions are available for showing in the UI.  That discovery process uses a third party library for reflection, named Scrutor.  The selector/predicate which Scrutor is given (line 41 of that linked code) is telling it to go look at libraries which are amongst the application's dependencies.  IE:  Libraries which are directly referenced by the app.

Exactly as you describe - if you reference it directly then your custom activity defs are found and available in the UI.  If you load as a plugin without direct reference then they're not.
[13:07]
@JimbobIII I think that would be a great issue to raise on the issue tracker, about supporting a plugin architecture for Elsa, so that activities may be loaded from external libraries without direct compile-time dependency.

We're so close to making it work; I think it genuinely would work at workflow-execution time.  I think it's probably just the designer UI where they're not showing up.  It might not make it into Elsa 2.0 (we're a bit overdue on that already so I suspect we won't want to add extra things to that milestone).  But it seems like a totally reasonable feature.

@Craig Fowler
@JimbobIII I think that would be a great issue to raise on the issue tracker, about supporting a plugin architecture for Elsa, so that activities may be loaded from external libraries without direct compile-time dependency.  We're so close to making it work; I think it genuinely would work at workflow-execution time.  I think it's probably just the designer UI where they're not showing up.  It might not make it into Elsa 2.0 (we're a bit overdue on that already so I suspect we won't want to add extra things to that milestone).  But it seems like a totally reasonable feature.

JimbobIII — Today at 13:10
Thanks for taking the time to look into that for me. And Yeah seamed really useful to be able to add activities without having to rebuild the core app.
A wild 
Nawu
 appeared.
Today at 13:14

Craig Fowler — Today at 13:14
Shucks.  I just had a skim through the code for Elsa 2.0 and I think (note, I didn't confirm it by running the app, only by reading through the code) that your problem is already fixed in Elsa 2.0

1
[13:16]
Elsa 2.0 has a totally rewritten dashboard/designer UI using a totally different set of technologies.  The backend for those has also changed.  The backend in 2.0 uses a discovery service which looks at a registry class of activity types.  That registry class is updated by the AddActivity method in service registration time.

So the root cause which means it doesn't work in 1.5 is no longer the case in 2.0.  But - the biggest thing that's "not quite ready for prime time" in 2.0 is the dashboard/designer UI, and it sounds as if that's exactly what you're wanting to use.

D'oh!
[13:18]
I think you're still welcome to raise that issue on github though, because it also brings it into the light as a "first class user requirement" which Elsa could choose to adopt.  That issue is our documentation that "we want to support loading activities by plugin".  However, I think you might get it for free in Elsa 2.
[13:19]
FYI this milestone tracks the progress toward Elsa 2.0
https://github.com/elsa-workflows/elsa-core/milestone/8

Any info about updated timescales etc goes there.
GitHub
elsa-workflows/elsa-core
A .NET Standard 2.0 Workflows Library. Contribute to elsa-workflows/elsa-core development by creating an account on GitHub.

[13:20]
... aaaand that's my lunch break over!  Back to the day job!

**Comment by craigfowler** [comment]
I have marked this issue up as "high priority" & part of Elsa 2 because there is a belief that we actually "get this for free" in Elsa 2.  In other words, there is a suspicion that the work we would have needed to do in order to enable this has already been done.

If it does already work in Elsa 2 then _are we happy to adopt this as "officially supported functionality"_ (question for @sfmskywalker  ?)?  If that's the case then the only thing which we should do is to write some test coverage for it, so that we know that we will always continue to support it and don't introduce regressions.

If it turns out that we didn't get this for free in Elsa 2 and there's significant work remaining to do in order to actually support it, then I wouldn't argue with removing it from the Elsa 2 milestone & reprioritising.

**Comment by sfmskywalker** [comment]
With Elsa 2, there's no separate activity discovery phase for the dashboard, so adding activities to DI from dynamically loaded assemblies should just work.
