### ISSUE TITLE
Populate designer drop-down list and/or multiple select list in runtime.

### ISSUE THREAD

**Issue by tomy2105** [elsa-workflows/elsa-core#831]
This is connected to my question in https://github.com/elsa-workflows/elsa-core/discussions/828.
Since the suggested way of doing it seems quite complex, here is specific problem I look for solution.

Currently my activity has, in designer, drop down list and checklist with values hardcoded in C# attributes (as the builtin activities have).

For my custom activity, I would like to be able to programmatically in the runtime set the values displayed in designer drop down and checklist (multiple select) either when activity is created (best) or during service initialization (can live with this too).

**Comment by jdevillard** [comment]
Hello, 

have you take a look at the OptionsProvider Property of the ActivityPropertyAttribute? I think it could be a good start. 


for example for a dropdown : 
```
        [ActivityProperty(UIHint = ActivityPropertyUIHints.Dropdown
               , Hint = "Test Option"
            ,OptionsProvider = typeof(TestOptionsProvider)
            )]
        public string? Test { get; set; }

```

and the OptionsProvider : 
```
    public class TestOptionsProvider : IActivityPropertyOptionsProvider
    {
        public object GetOptions(PropertyInfo property)
        {
            return new List<string>()
            {
               "value1",
               "value2",
               "value3",
            };
        }
    }
```

I think this is called once  at initialization. The OptionsProvider seems to be able to return any object, so regarding the UIHint you want to use, you can return different type of object. Even custom Object if you create custom controls in the designer.

![image](https://user-images.githubusercontent.com/3254429/113361446-4cc97200-934c-11eb-88c2-b33a1e1fbf76.png)

The next step for me is to know how to get theses values at runtime when an activity is open in the designer. (I'm interested in this because I want to fetch value through an API which will evolve quickly). But I don't know if it's possible right now with the current Interface.

**Comment by tomy2105** [comment]
Thanks for the great answer @jdevillard.
This covers the use case when list is obtained during service startup/initialization. Is there any way to make it obtainable again during runtime?

And my second question would be is there a way to have dropdown/choice value be different than what is displayed (same as html dropdown has)?

**Comment by jdevillard** [comment]
>Is there any way to make it obtainable again during runtime?

don't know yet but I also need this feature (and more using security to allow result regarding user but it'll be a work after), have to ask to @sfmskywalker.
 
> And my second question would be is there a way to have dropdown/choice value be different than what is displayed (same as html dropdown has)?

for this you have to use SelectListItem (and the latest commit of the Designer ^^)

```
    public class TestOptionsProvider : IActivityPropertyOptionsProvider
    {
        public object GetOptions(PropertyInfo property)
        {
            return new List<SelectListItem>()
            {
               new SelectListItem("1",  "value1"),
               new SelectListItem("2",  "value2"),
               new SelectListItem("3",  "value3"),
            };
        }
    }
```
This will fill the options correctly : 

![image](https://user-images.githubusercontent.com/3254429/113420374-7ffe1680-93c9-11eb-8422-0be5d260271f.png)

**Comment by sfmskywalker** [comment]
Dynamic options provided at runtime (upon opening the activity editor) is currently not supported, but it will be supported. I’m currently focusing on basic controls, but when that’s done I’m gonna be working on this issue (barring any change in priorities of course).

**Comment by tomy2105** [comment]
> for this you have to use SelectListItem (and the latest commit of the Designer ^^)
> 
> ```
>     public class TestOptionsProvider : IActivityPropertyOptionsProvider
>     {
>         public object GetOptions(PropertyInfo property)
>         {
>             return new List<SelectListItem>()
>             {
>                new SelectListItem("1",  "value1"),
>                new SelectListItem("2",  "value2"),
>                new SelectListItem("3",  "value3"),
>             };
>         }
>     }
> ```
> 
> This will fill the options correctly :
> 
> ![image](https://user-images.githubusercontent.com/3254429/113420374-7ffe1680-93c9-11eb-8422-0be5d260271f.png)

Great work! Thank you very much :)
Don't have the access to code at the moment, so I'll just ask instead of trrying...... :)
Will it work with multiple select choices (similar to what HTTP endpoint method for example)?

**Comment by sfmskywalker** [comment]
Should work exactly the same. I don't have an existing example of this at the moment, but it should work just the same for check lists and radio button lists. If not, that's an issue to be fixed.

**Comment by tomy2105** [comment]
> > for this you have to use SelectListItem (and the latest commit of the Designer ^^)
> > ```
> >     public class TestOptionsProvider : IActivityPropertyOptionsProvider
> >     {
> >         public object GetOptions(PropertyInfo property)
> >         {
> >             return new List<SelectListItem>()
> >             {
> >                new SelectListItem("1",  "value1"),
> >                new SelectListItem("2",  "value2"),
> >                new SelectListItem("3",  "value3"),
> >             };
> >         }
> >     }
> > ```
> > 
> > 
> > This will fill the options correctly :
> > ![image](https://user-images.githubusercontent.com/3254429/113420374-7ffe1680-93c9-11eb-8422-0be5d260271f.png)
> 

It seem that this does not work with multiple choice select (`ActivityPropertyUIHints.CheckList`). I get this:

![Image 1](https://user-images.githubusercontent.com/7658839/114740589-483c8a80-9d4a-11eb-8f04-1853bbe0232c.png)

**Comment by sfmskywalker** [comment]
I just pushed a fix. Well, I haven't tested it, but let me know if it works or not either way :)

**Comment by tomy2105** [comment]
The display is ok now.
However the checkboxes do not function well, after page reload the checked items are not checked anymore.
I believe the devil is in the elsa-check-list-property.tsx.
Instead of 

`
            const inputId = `${fieldId}_${index}`;

            const isSelected = values.findIndex(x => x == option) >= 0;

            const optionIsString = typeof(option) == 'string';

            const value = optionIsString ? option : option.value;

            const text = optionIsString ? option : option.text;

`

should be

`
            const inputId = `${fieldId}_${index}`;

            const optionIsString = typeof(option) == 'string';

            const value = optionIsString ? option : option.value;

            const text = optionIsString ? option : option.text;

            const isSelected = values.findIndex(x => x == value) >= 0;

`

`isSelected` must be last and compared against new `value` and not old `option`.
If you could fix that too, that would be perfect :).

**Comment by sfmskywalker** [comment]
Makes sense. I just pushed a change. Let me know.

**Comment by tomy2105** [comment]
Yup, it is displayed correctly now, thank you very much :).

**Comment by diego-034** [comment]
Hi, First of all, good job, I would like to know how the option to obtain the data of the option in a dynamic way goes, that could be used with an api

**Comment by sfmskywalker** [comment]
Populating dropdowns/multi-text/check-list controls at runtime is now supported (though not yet documented).
However, there is a simple example that demonstrates how it works: https://github.com/elsa-workflows/elsa-core/blob/feature/elsa-2.0/src/samples/server/Elsa.Samples.Server.Host/Activities/VehicleActivity.cs

Notice the two interfaces implemented by the activity: `IActivityPropertyOptionsProvider` and `IRuntimeSelectListItemsProvider`.

The first interface gives the activity a chance to provide specific property options (for the `Brand ` property).
The second interface allows for the provisioning of items to show in the designer. This method is called each time the activity editor opens.

**Comment by srihariraovadlani** [comment]
Can you please share the code snippet on usage of IActivityPropertyOptionsProvider and IRuntimeSelectListItemsProvider.

Thanks in advance!

**Comment by sfmskywalker** [comment]
Sure, here you go: https://github.com/elsa-workflows/elsa-core/blob/ed47dcd600db0ebf307c7d00a0f608fa671d6171/src/samples/server/Elsa.Samples.Server.Host/Activities/VehicleActivity.cs

**Comment by srihariraovadlani** [comment]
Thank you very much!! you saved my life :)
