### ISSUE TITLE
Problem when creating new workflow through dashboard/designer

### ISSUE THREAD

**Issue by tomy2105** [elsa-workflows/elsa-core#832]
Again, I know it is under development but this one was pretty nasty to me.

Latest Elsa compiled from code, SQLLite provider.

I have one workflow created through dashboard/designer.
1. Go back to dashboard, workflow definitions, and press create.
2. Press settings button and give it a name (don't know if this is needed).
3. Press publish (don't know if this is needed)
4.  Go back to dashboard, workflow definitions, I have several, empty, definitions with new workflow name and my old one (initial) is nowhere to be seen :(.

**Comment by proovit** [comment]
Took me a while to get the new structure, but got it now. I think ;-)

Great project.

Clicking on /workflow-definitions "create" button now throws a js error: lots of ::ERR_ABORTED 404

Working with version of 4-4, 2.0: Elsa.Samples.Server.Host / ElsaDashboard.Samples.Server
Maybe helpful, i really don't know. :-)  (I checked CORS)

GET https://localhost:54938/ElsaDashboard.Application.Server.styles.css net::ERR_ABORTED 404
create:17 GET https://localhost:54938/_content/Elsa.Designer.Bindings.Blazor/monaco-editor/min/vs/loader.js net::ERR_ABORTED 404
create:17 GET https://localhost:54938/_content/Elsa.Designer.Bindings.Blazor/monaco-editor/min/vs/loader.js net::ERR_ABORTED 404
blazor.webassembly.js:1 Debugging hotkey: Shift+Alt+D (when application has focus)
DevTools failed to load SourceMap: Could not load content for chrome-extension://dafgdjggglmmknipkhngniifhplpcldb/browser-polyfill.min.js.map: HTTP error: status code 404, net::ERR_UNKNOWN_URL_SCHEME
blazor.webassembly.js:1 blazor Loaded 10.38 MB resourcesThis application was built with linking (tree shaking) disabled. Published applications will be significantly smaller.
blazor.webassembly.js:1 GET https://localhost:54938/_content/Elsa.Designer.Bindings.Blazor/elsa-workflows.js net::ERR_ABORTED 404

**Comment by sfmskywalker** [comment]
Thanks 😄 

Yeah the dashboard is currently in flux, so there are bound to be things breaking, not to mention a lot of items ranging from small to large yet to be completed.

The current version does not have the issue you described here, so I will close this issue. Do feel free to reopen in case you are seeing the same issue still.
