### ISSUE TITLE
EF Core Schema configuration for Elsa 2

### ISSUE THREAD

**Issue by sfmskywalker** [elsa-workflows/elsa-core#836]
In Elsa 1, we have the ability to configure EF Core to create DB tables under a configurable schema name. We need that for Elsa 2 as well.

**Comment by sfmskywalker** [comment]
For Elsa 2, the default schema will be "Elsa". Work has been done to allow the use of custom DB contexts that derive from Elsa in order to override the schema name. This, however, requires the user to generate their own migrations. This is fine for most users, but we can revisit this as needed.

**Comment by mickdelaney** [comment]
We're going to start creating our own migrations using ef, as we need a custom schema name in postgres. 

i'm assuming no work has been done to parameterize migrations and avoid the the need for custom migrations ?

**Comment by sfmskywalker** [comment]
OK. 

No work was done to parameterize migrations. I looked into that a while ago, but gave up when I realized it would mean updating the migrations manually with variables for the schema, and some other pain points I don't remember.

Anyway, make sure to override the `ElsaContext.Schema` property when you generate your migrations.

**Comment by mickdelaney** [comment]
Whats your opinion on change the naming convention of the tables & columns. 
We use a snake case convention with Postgres, e.g workflow_definitions, whereas elsa uses WorkflowDefintions.
Am i likely to get in to trouble if i go down that road ? 
cheers

**Comment by sfmskywalker** [comment]
I think it would be preferable to be able to generate the table names using the same convention used by the rest of your DB.

Which you might be able to do by overriding `ElsaContext` and its `OnConfiguring` method as outlined in this [SO post](https://github.com/efcore/EFCore.NamingConventions).

I haven't looked into this at all, so there might be bears waiting for you down the road ;)

**Comment by mickdelaney** [comment]
:-) ok thanks.
