### ISSUE TITLE
can't create & run a console workflow

### ISSUE THREAD

**Issue by jiangyz7cc** [elsa-workflows/elsa-core#841]
Read from:
https://elsa-workflows.github.io/elsa-core/docs/guides-hello-world-console

Put code into my program:
```
	var workflowBuilder = services.GetRequiredService<IWorkflowBuilder>();
	...
	var invoker = services.GetService<IWorkflowInvoker>();
```

Problems:
service doesn't have the definition of GetRrequiredService(), GetService()

**Comment by jdevillard** [comment]
Hello , 

What version of Elsa are you trying to use?

**Comment by sfmskywalker** [comment]
This is Elsa 1 (IWorkflowInvoker gave it away ;)).

the problem is a missing namespace import that provides the extension method GetRequiredService.

Usually your IDE provides you with hints to import the necessary namespaces.

As a note to self: provide working examples via GitHub.

**Comment by sfmskywalker** [comment]
@jiangyz7cc The `Microsoft.Extensions.DependencyInjection` method is an extension method that lives in the `Microsoft.Extensions.DependencyInjection` namespace. To import it, add the following statement to your class file:

`using Microsoft.Extensions.DependencyInjection;`

**Comment by jiangyz7cc** [comment]
> 
> 
> @jiangyz7cc The `Microsoft.Extensions.DependencyInjection` method is an extension method that lives in the `Microsoft.Extensions.DependencyInjection` namespace. To import it, add the following statement to your class file:
> 
> `using Microsoft.Extensions.DependencyInjection;`

Thanks for reply, I made a mistake that declared services as ServiceCollection.
Add namespace: using Microsoft.Extensions.DependencyInjection;
Change services definition like this:
```
			ServiceProvider services =new ServiceCollection()
				.AddElsaCore()
				.AddConsoleActivities()
				.BuildServiceProvider();
```
then it works.
