### ISSUE TITLE
I can not save the activity Name into the database.

### ISSUE THREAD

**Issue by 1002527441** [elsa-workflows/elsa-core#848]
Dear Team, 

         Could you help me see the problem I met with Elsa(version 1.0) Dashboard.
         I am trying to fix it, but I can not find the root cause.  it will be helpful if you can give me reply or a short feedback.

In the Elsa Dashboard, I have set the Name of customized activity, which inherited "Activity" from Elsa Predefined.
![image](https://user-images.githubusercontent.com/53967483/113970298-3dc15300-9869-11eb-9659-477ba0caf210.png)

but in ActivityDefinition table in database,  the Name is NULL, it leads I can not reference Named activities in future.
![image](https://user-images.githubusercontent.com/53967483/113970341-49ad1500-9869-11eb-8ee3-71c88073c2f5.png)

**Comment by sfmskywalker** [comment]
I just tried to reproduce the issue, but the Name field is being persisted for me. The problem you describe used to be a bug that was fixed at some point, so maybe it happens under certain circumstances.

A number of questions to consider:

1. Does the problem always occur (even when you create a new workflow)?
2. What package version are you using?
3. Do you get the same issue when running the dashboard from the source code?

**Comment by 1002527441** [comment]
A number of questions to consider:

Does the problem always occur (even when you create a new workflow)?

- [ ] yes, the problem always occur.

What package version are you using?

- [ ]  I am using Elsa.core 1.0.0, and elsa.Dashboard - v1.1.0

Do you get the same issue when running the dashboard from the source code?

- [ ] yes, I always run it with source code.

Is it possible to lead this problem with different version of elsa.Dashboard?

**Comment by sfmskywalker** [comment]
>  I am using Elsa.core 1.0.0, and elsa.Dashboard - v1.1.0

Are these assembly versions or package versions? If the latter, then that might explain the issue - the current latest version of Elsa 1 is [1.5.4](https://www.nuget.org/packages/Elsa/1.5.4.1816).

> yes, I always run it with source code.

OK, then the package versions are irrelevant of course. In which case I am at a loss as to why you are seeing the issue whilst I don't 😕 

> Is it possible to lead this problem with different version of elsa.Dashboard?

There's only one version of the Elsa Dashboard for Elsa 1. Perhaps you might consider switching to Elsa 2 (feature/elsa-2.0) - it works more or less the same, but without the issue you are experiencing. There is no documentation at the moment, but there are sample projects that you might explore.

**Comment by 1002527441** [comment]
thanks for your reply. may be I need to change the right version of dashboard.
