### ISSUE TITLE
 Could not load type 'Microsoft.EntityFrameworkCore.Metadata.RelationalEntityTypeAnnotations' from assembly 'Microsoft.EntityFrameworkCore.Relational, Version=5.0.5.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'.

### ISSUE THREAD

**Issue by abdalhadikolayb** [elsa-workflows/elsa-core#852]
Error details:
An unhandled exception occurred while processing the request.
TypeLoadException: Could not load type 'Microsoft.EntityFrameworkCore.Metadata.RelationalEntityTypeAnnotations' from assembly 'Microsoft.EntityFrameworkCore.Relational, Version=5.0.5.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'.
Unknown location

TypeLoadException: Could not load type 'Microsoft.EntityFrameworkCore.Metadata.RelationalModelAnnotations' from assembly 'Microsoft.EntityFrameworkCore.Relational, Version=5.0.5.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'.
Unknown location

TypeLoadException: Could not load type 'Microsoft.EntityFrameworkCore.Metadata.RelationalPropertyAnnotations' from assembly 'Microsoft.EntityFrameworkCore.Relational, Version=5.0.5.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'.
Unknown location

TypeLoadException: Could not load type 'Microsoft.EntityFrameworkCore.Metadata.RelationalFullAnnotationNames' from assembly 'Microsoft.EntityFrameworkCore.Relational, Version=5.0.5.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'.

we use elsa version 1.5.3, with dotnet zero core 5.0.

**Comment by sfmskywalker** [comment]
Do you have steps to reproduce the above that I can follow?

**Comment by abdalhadikolayb** [comment]
I have dotnet zero project (dotnet 5), and i followed this guide: https://elsa-workflows.github.io/elsa-core/docs/guides-dashboard

**Comment by abdalhadikolayb** [comment]
The issue in (public static class ActivityDefinitionListExtensions) class in (Elsa.Dashboard\Extensions), 
At line 25: typeSourceSelector.Populate(serviceCollection, RegistrationStrategy.Replace(ReplacementBehavior.All));

**Comment by abdalhadikolayb** [comment]
Dear Sair;
Please note that the issue is in this line (shown in the screenshot).
Regards.

**Comment by sfmskywalker** [comment]
I followed the same guide just now, but it worked fine for me.
You mentioned a screenshot, but I'm not seeing it.

If you can provide me with the project source files that have this issue I could take a further look.

**Comment by sfmskywalker** [comment]
I think I understand now. This error happens with Elsa 1 when using the dashboard area and auto-registering activity types. The workaround is to manually register these activity types with the dashboard. 

But the REAL fix is to witch to Elsa 2 - which doesn't have this problem 😁
