### ISSUE TITLE
Workflow Variables set before workflow execution are not accessible in custom activity.

### ISSUE THREAD

**Issue by VeereshAngadi** [elsa-workflows/elsa-core#856]
Hi,

I have a workflow which requires input. Before executing workflow I am setting those variables but when during execution of custom activity, I am not able to access those variables. The variable count is shown as 0. I am using below code to set variables.

WorkflowDefinitionVersion workflowDefinition = await _workflowRegistry.GetWorkflowDefinitionAsync("8e090f7d235a4c9c9302f466c6464a52", VersionOptions.LatestOrPublished);
                                if (workflowDefinition != null)
                                {
                                    workflowDefinition.Variables.SetVariable("Guid", "5a7428d8-0882-4682-847f-ca884008caf2");
                                    workflowDefinition.Variables.SetVariable("Contract", contractDto);
                                    WorkflowExecutionContext workflowExecutionContext = await _workflowInvoker.StartAsync(workflowDefinition);                                    
                                }

I am using below code to try to access the variable
context.GetVariable("Guid")

I am trying to run this workflow in asp.net core web api project. I tried passing these variables in Inputs but that is also not working,

My question is that is this correct way to pass the input values to workflow or is there any other way to do that?

**Comment by sfmskywalker** [comment]
I just checked and I see why: the workflow invoker uses the specified `WorkflowDefinitionVersion` to instantiate a "runtime" workflow (of type `Workflow`) but fails to read the variables from the definition. So this is clearly a bug in Elsa 1. I will push a fix.

**Comment by sfmskywalker** [comment]
I [pushed a fix](https://github.com/elsa-workflows/elsa-core/commit/4fcfaf61f9cdf7a8ef42a94af00931bb4ae3d80a) and a new tag 1.5.4 that is being built as I write this.

**Comment by VeereshAngadi** [comment]
I updated my nuget package to 1.5.4.1816(latest) but the issue is not resolved yet. Variables In WorkflowExecutionContext is empty.

**Comment by VahidShir** [comment]
I confirm this issue (version 1.5.5.1943).

**Comment by VahidShir** [comment]
I just figured it out that as we set variable in workflowDefinition instance then we need to retrieve it from it from context too:
`context.Workflow.Definition.Variables.GetVariable("Guid");`

**Comment by sfmskywalker** [comment]
Nice find. It's actually supposed to be copied over to the workflow instance, but apparently that doesn't happen. Since this is working fine in Elsa 2 and you have found a workaround, I consider the issue fixed.

Elsa 2.0 should be released to NuGet as a stable release sometime this week.
