### ISSUE TITLE
Workflow editor connection visibility bug

### ISSUE THREAD

**Issue by MiroslavMikus** [elsa-workflows/elsa-core#860]
I have created my first custom action:
``` csharp
  [ActivityDefinition(Category = "Custom", Description = "My first activity", Outcomes = new[] {"ok", "not ok"}, DisplayName = "My test Activity")]
  public class TestActivity : Activity
  {
      [ActivityProperty(Hint = "The message to write.")]
      public WorkflowExpression<string> Message
      {
          get => GetState<WorkflowExpression<string>>();
          set => SetState(value);
      }
      protected override async Task<ActivityExecutionResult> OnExecuteAsync(WorkflowExecutionContext context, CancellationToken cancellationToken)
      {
           var result = await context.EvaluateAsync(Message, cancellationToken);         
           if (Message is null)
           {
              return Outcome("not ok");
          }            
            
          Console.WriteLine(result);
            
          return Outcome("ok");
      }
  }
```
Source code is [here](https://github.com/MiroslavMikus/Exercises/tree/main/cs.Elsa/HalloElsa)
Elsa Version : 1.5.4.1816
.Net 5.0.5
Chrome 89.0.4389.114
Gif: 
![ELSA_Editor_1 5 4 1816](https://user-images.githubusercontent.com/29312172/114534936-cd8f4480-9c4f-11eb-9859-370cb6171819.gif)
I could provide my SqlLite Db as well if necessary. The db has aproximately 7 000 completed workflow instances ~30MB.

**Comment by sfmskywalker** [comment]
I've seen this happening before, and it had something to do with the outcome name, something to do with having a space in the outcome name.

I cloned your repo and tried to reproduce the issue you captured above - which I succeeded to do.
After changing the outcome name `"not ok"` to `"not_ok"`, the problem went away.

I suspect this has something to do with space encoding, e.g. the space gets replaced with some encoded value like `%20`. I'm not sure, but the problem does not exist in Elsa 2 and will be superseding Elsa 1 soon(ish).

**Comment by craigfowler** [comment]
> but the problem does not exist in Elsa 2 and will be superseding Elsa 1 soon(ish).

@sfmskywalker that smells a little bit like **wontfix** to me.  Is that what you meant?

**Comment by sfmskywalker** [comment]
@craigfowler Indeed. You got a keen nose. 😄

**Comment by craigfowler** [comment]
Thanks.  Closing as wontfix (for 1.5.x).  Issue has already been fixed in 2.x.
