### ISSUE TITLE
Problem in designer when dragging acitvities.

### ISSUE THREAD

**Issue by tomy2105** [elsa-workflows/elsa-core#861]
Latest Elsa 2 compiled from code.

Place 4 activities in designer, one after another (for example 4 set variable activities).
Now drag second one and drop it on a + after last one.
You will end up with only first activity, all others will disappear.

**Comment by sfmskywalker** [comment]
Thanks for reporting. Will be fixed as part of the designer-rewrite that's currently going on.

**Comment by sfmskywalker** [comment]
This has been fixed:

![image](https://user-images.githubusercontent.com/938393/116874988-78c16700-ac1a-11eb-9a80-4ac50a2a4b2d.png)
