### ISSUE TITLE
Custom expression not working

### ISSUE THREAD

**Issue by wohlly** [elsa-workflows/elsa-core#868]
I am trying to make a custom expression evaluator, which was easy enough to create and add as a provider, but it is not being used by `WorkflowExpressionEvaluator` for expressions.

For example,
```C#
.Then<IfElse>(
    x => x.ConditionExpression = new WorkflowExpression<bool>("C#", "true")
);
```
is still calling the `JavaScriptExpressionEvaluator` even though the expression's `Syntax` should be "C#" and my `IExpressionEvaluator` should be mapped to "C#" in the `evaluators` dictionary.

It appears the `ConditionExpression` property returned is being typed as a `JavaScriptExpression` (and remains stuck as that type even after assignment) because of `GetState`'s `defaultValue` argument being inferred.  One possible solution is to explicitly add the field type to the `get` function in `IfElse` (and all other activities with expressions):
```C#
public WorkflowExpression<bool> ConditionExpression
{
    get => GetState<WorkflowExpression<bool>>(() => new JavaScriptExpression<bool>("true"));
    set => SetState(value);
}
```

After doing that, the correct syntax is returned and my custom expression evaluator is called.

**Comment by sfmskywalker** [comment]
That's indeed a known bug in Elsa 1. It's been fixed for Elsa 2, although v2 does not yet expose an extensibility endpoint to support custom evaluators from the designer. I believe your best bet for now would be to provide a default instance of the base type (`WorkflowExpresssion`), like so:

```csharp
public WorkflowExpression<bool> ConditionExpression
{
    get => GetState<WorkflowExpression<bool>>(() => new WorkflowExpression<bool>("JavaScript", "true"));
    set => SetState(value);
}
```

**Comment by sfmskywalker** [comment]
I'm closing this issue, as I believe the workaround suggested is the way to go with Elsa 1. Feel free to re-open if you think otherwise.
