### ISSUE TITLE
Make some more Activity methods virtual

### ISSUE THREAD

**Issue by tomy2105** [elsa-workflows/elsa-core#872]
Can Activity methods which are used to exit output and result outcomes be made virtual so that custom activity can add some processing (for example logging) to them?

I guess ones that end the calling chains:

        protected NoopResult Noop() => new();
        protected OutcomeResult Outcomes(IEnumerable<string> outcomes) => new(outcomes);
        protected OutputResult Output(object? output) => new(output);
        protected SuspendResult Suspend() => new();
        protected CombinedResult Combine(IEnumerable<IActivityExecutionResult> results) => new(results);
        protected CombinedResult Combine(params IActivityExecutionResult[] results) => new(results);
        protected FaultResult Fault(Exception exception) => new(exception);
        protected FaultResult Fault(string message) => new(message);

Or all which would be, in addition to above:

        protected OutcomeResult Done() => Outcome(OutcomeNames.Done);
        protected CombinedResult Done(object? output) => Combine(Output(output), Done());
        protected OutcomeResult Outcomes(params string[] outcomes) => Outcomes((IEnumerable<string>)outcomes);
        protected OutcomeResult Outcome(string outcome) => Outcomes(outcome);
        protected CombinedResult Outcome(string outcome, object? output) => Combine(Output(output), Outcome(outcome));

Currently don't know what schedule results one do so skipped them, but I guess same logic could apply.

**Comment by sfmskywalker** [comment]
We could make these methods virtual. But I think we can do you even one better: we could publish a domain event, e.g. `ResultExecuting`, allowing you to write event handlers to do e.g. logging.

I'll add both methods, since they both seem useful.

**Comment by sfmskywalker** [comment]
Done.

**Comment by tomy2105** [comment]
Thank you!
Very good work :)
