### ISSUE TITLE
Create/Populate Activity Outcomes at Runtime

### ISSUE THREAD

**Issue by tomy2105** [elsa-workflows/elsa-core#873]
Similar to question asked in https://github.com/elsa-workflows/elsa-core/issues/831.
Is there a way to create outputs list of the activity in the runtime, during initialization (or completely in runtime)?

**Comment by sfmskywalker** [comment]
What do you mean by "outputs list"? Do you mean some form of metadata about what output(s) an activity might provide?

**Comment by tomy2105** [comment]
Yes, that is exactly what I mean.
A dynamic way of creating `Outcomes = new[] { True, False, OutcomeNames.Done }`......
Something like `OutcomesProvider` similar as now there is `OptionsProvider` for activity properties options.

**Comment by sfmskywalker** [comment]
Ah I see. You are referring to **outcomes**, not **outputs** (I do understand the ambiguity).

Right now there's no way, except in the form of a workflow designer plugin. This is used for example for the `Fork` activity, where the user can define branches from the activity editor, and then these branches are displayed as outcomes on the designer.

What you are asking for is a way to provide a list of outcomes at runtime from the server. I think we can make that happen. But out of curiosity, what's your use case for this?

**Comment by tomy2105** [comment]
A very simplified example.
I try to develop workflow for non-programmers.
They use a web service (and I hide all the complex detail of calling it into nice activity with two parameters) which returns an int which actually has few values depending on the configuration of this 3rd party service (and configuration changes from time to time).
Web service has metadata api which allows you to fetch all current possible values of this integer with user friendly description.
So instead of forcing user to do Switch with comparison to int I want to have simple "dynamic" block which will have that many outputs as there are unique values of that int.....

**Comment by tomy2105** [comment]
> Ah I see. You are referring to **outcomes**, not **outputs** (I do understand the ambiguity).
Ah, yes......
**outputs** in code == ActivityName,Output in designer.
**outcomes** in code == activity outputs (lines with names coming out of activity :)) in designer :).

**Comment by sfmskywalker** [comment]
I see. So if you were able to dynamically control the activity's outcomes when initializing the activity registry, you can read this API metadata and provide the appropriate outcomes, right?

**Comment by tomy2105** [comment]
Yes, that is right.
