### ISSUE TITLE
Workflow Instance Inbox

### ISSUE THREAD

**Issue by sfmskywalker** [elsa-workflows/elsa-core#878]
Currently, workflow instances are executed by *dispatchers* such as Rebus, Hangfire or Orleans. And when an external trigger event occurs, such as an incoming message on some queue or a timer event, a new instruction gets sent via the dispatcher to schedule a given activity + input for execution.

Although this works (thanks to distributed locking), it could be implemented more efficiently by allowing individual workflow instance workers work off a queue called their _inbox_.

The idea here is that at each workflow instance will be processed by working through a queue of messages, where each workflow instance has its own queue (the inbox).

This is different from working off a regular queue as we are doing today. Today, the queue is _global_ for all workflow instances - the queue consumer acquires a distributed lock for a given workflow instance, and releases this lock until its done. Multiple consumer instances allow for the system to scale horizontally.

A potential issue with this is that processing a message might take too long, causing redeliveries of the same message. These messages have to be re-enqueued in order to not lose important events such as one-off timer events and webhook notifications from external systems.

This current setup potentially causes a lot of excessive IO. Having a mailbox (queue) per workflow instance solves this.
It is very similar to the actor model, and in fact Orleans would provide a great vehicle for modeling a workflow instance grain.
But to my current knowledge, Orleans is insufficient because invoking a virtual actor causes the caller to wait until the call is done (when using await). We can of course do a fire & forget call, but if the workflow execution fails, we can not easily retry it, because the message that caused the call to be made would have been marked as processed.

Orleans does have a notion of Streams that would work, but then we are back to the same issue of long-running tasks that no longer guarantee at least & at most 1 message delivery.

Another issue is that of timing: for example, it can happen that a workflow invokes some HTTP endpoint, that in turn sends a message that is to be handled by the same workflow right after it invoked the endpoint. But if this message arrives before the workflow had a chance to be persisted, the workflow engine will have handled the message **too soon**.

The following model/architecture solves all of these issues:

* Inbox per workflow instance. An inbox contains simple execution instructions: a workflow instance ID, activity type, input, time stamp and a processed flag.
* One or more workers that process individual inboxes. A distributed lock will be held on workflow instance ID, guaranteeing a single worker processing items from a workflow instance's inbox at a time.
* As new stimulus arrives, new execution instructions are posted to the inbox. They get picked up automatically by the workflow instance worker once its done processing its current stack of scheduled activities. This automatically mitigates the issue with events arriving "too soon".
* When a worker wants to process a workflow instance's inbox, it first acquires a distributed lock (e.g. `"inbox-{workflowInstanceId}"`) and then loads all unprocessed instructions from the inbox into memory. As each instruction is successfully processed, it gets marked as processed in the underlying data store.
* The workers can be instantiated in a variety of ways. One way could be in the form of an **Orleans grain** (Workflow Instance Grain). When invoked, the grain will simply acquire a worker from a pool and start processing a the workflow instance's inbox. Another form would be a **Hangfire job**. And by default, we could have an old-fashioned **BackgroundService** implementation that simply starts new threads from a threadpool.
* Besides the background processing of a workflow instance, "direct mode" processing (e.g. handling HTTP requests that ttrigger workflows) still works too of course thanks to distributed locking.
* Queue messages, timer events etc. will now simply be handled by adding instructions to the inbox.
* As items get added to an inbox, an event (via Rebus) will be triggered to signal dispatchers that work needs to be done. Because this signaling happens via a message queue, work can be picked up from any node in a cluster. And if a worker is already processing an inbox, it will automatically find the new instructions since it will repeat the loading of the inbox after it's done processing its current list that it's holding in memory.

With the above in place, I think we'd have a very clean, straightforward and predictable flow of events & processing thereof that is distributable & scalable.

Originally I assumed the above would have been available out of the box with Orleans, but it turned out to be not quite the case.

**Comment by craigfowler** [comment]
Seems sane.  The only real question I have is priority?  Also, would it be reasonable to assume that this is likely to cause an API-breaking change when it is implemented?  (perhaps not)

Also, would such a mailbox need to be persisted in any way?  This would all be starting to need to tackle many of the same problems as regular old message queueing.  If you've got messages which are likely to be enqueued for a matter of minutes or more, then it's probably worth having some sort of persistence for them.  Otherwise something as simple as a forced service restart can accidentally lose messages.

Whilst Orleans might not be suitable, might there be another message-queueing system which does the job we need?

**Comment by jwillmer** [comment]
> Also, would such a mailbox need to be persisted in any way?

hangfire supports mongo as storage so this is not a problem. I combined Hangfire (with mongo as storage) together with Masstransit and rabbitmq as pipeline. Works pretty well. It's just a question if elsa wants to invest/depend in these big services.

**Comment by sfmskywalker** [comment]
>The only real question I have is priority

I think it can be worked on after the 2.0 release as an improvement to increase throughput.

> Also, would such a mailbox need to be persisted in any way.

Yes, absolutely - this is key.

> Might there be another message-queueing system which does the job we need?

We might need a combination of systems. Ideally we get a queue per workflow instance, and a way to query unprocessed messages by priority, so that e.g. timer events get processed first. 

A nice thing about representing an Inbox with e.g. WorkflowMessage records is that we have a lot of control and let the user choose to use the same persistence store without needing a separate MQ broker. This also means the user won;t need to take on a dependency on e.g. Hangfire.

**Comment by mickdelaney** [comment]
kafka has message ordering over parititions. 
you can achieve similar semantics to actor inboxes.
we switched a lot of work loads to kafka from rabbitmq to avoid distributed locking. and although kafka is a big piece of kit, it has gotten a lot easier, and continues to, in terms of devops.

**Comment by sfmskywalker** [comment]
We now have the Actor model through the use of [Proto.Actor](https://proto.actor/).

**Comment by bxjg1987** [comment]
@sfmskywalker why not orleans?

**Comment by sfmskywalker** [comment]
We can still add Orleans if someone is interested in it. Proto.Actor is a lightweight implementation and seems easier to get setup as an Elsa module. But this doesn’t mean we can’t also have Orleans 😊
