### ISSUE TITLE
Could we get another preview version for version 2?

### ISSUE THREAD

**Issue by soerenuhrbach** [elsa-workflows/elsa-core#897]
Hey Guys,

Can we get another nuget preview version for version 2?
I would like to use it with the latest MassTransit implementation.
 
Thank you and best regards 
Sören

**Comment by soerenuhrbach** [comment]
Oh, never mind... A new version was released 5h ago.. Sorry. :)

**Comment by MrGeneric** [comment]
@soerenuhrbach Sorry, where do you see the new version?

**Comment by sfmskywalker** [comment]
Elsa 2 Preview builds can be found here: https://www.myget.org/gallery/elsa-2

**Comment by MrGeneric** [comment]
Thank you very much!
