### ISSUE TITLE
Workflow journal improvements.

### ISSUE THREAD

**Issue by tomy2105** [elsa-workflows/elsa-core#919]
I like workflow journal, very nice and helpful to see the outputs and all....

However for crazy people like me who have large objects in outputs, you need to put some limits :)....

Ideally:
1. Header with close button and two tabs should remain on top to be seen even when you are scrolled down.
2. Single activity should be limited in width and height so it doesn't look bad or takes too much space when large outputs are present.
3. Single activity if too large should have its own independent scrollbars so one can see whole output if he needs to when 2 is implemented.

![Journal](https://user-images.githubusercontent.com/7658839/116576775-27f6f900-a910-11eb-95fc-bbf5eadfc256.png)

**Comment by sfmskywalker** [comment]
I believe this has been resolved. Please feel free to reopen otherwise.
