### ISSUE TITLE
Improve support for missing activities

### ISSUE THREAD

**Issue by tomy2105** [elsa-workflows/elsa-core#926]
My problem happens when I have working elsa system but update it and remove an activity.

After update the system won't start because at startup it "detects" missing activity and ask's me if I forgot to register it.

I don't think whole system should stop functioning because of an missing activity that might be used in one of 100 workflows.

Instead system should insert "generic" activity in its place which would make workflow execution fault if this activity was executed, and not the whole system.
Same generic (saying missing activity in description) should be used in designer or when displaying either workflow journal history.

Let me know what you think? And how hard would this be to implement?

**Comment by sfmskywalker** [comment]
I agree; the system shouldn't fail to start or run because of faulty workflows.
At the very least, the workflow failing to run due to a changed workflow definition should simply not execute and a warning should be logged.

**Comment by sfmskywalker** [comment]
This is now fixed by simply ignoring workflow definitions that fail to materialize. The workflow can be fixed manually by the developer without preventing the app from starting.
