### ISSUE TITLE
Is it possible to specify designer icon for custom Activity?

### ISSUE THREAD

**Issue by tomy2105** [elsa-workflows/elsa-core#929]
How can one specify icon of an activity displayed in designer?
Sorry if I missed this somewhere :).

**Comment by sfmskywalker** [comment]
This is now documented: https://elsa-workflows.github.io/elsa-core/docs/next/extensibility/extensibility-designer-plugins

**Comment by alymomdouh** [comment]
hello in elsa v3 not work if any one have way to add icon for custom-activity
