### ISSUE TITLE
Does Workflow Instance viewer Journal needs activity inputs?

### ISSUE THREAD

**Issue by tomy2105** [elsa-workflows/elsa-core#935]
As far as I understand activity input is the output of the last activity executed before it.
Please correct me if I'm wrong :).

In Journal activity input and output is displayed.
However that means that we display same thing twice (as previous activity output and current activity input).
Which is kind of cumbersome if output/input has a lot of members.

Since output can be persisted and be used elsewhere (not just as an input) I think it should remain and the input should not be displayed (you just need to look at the output of the activity above and will see it :)).

**Comment by sfmskywalker** [comment]
> As far as I understand activity input is the output of the last activity executed before it.

You are not wrong :)

I agree with everything you said. Great idea to display output only.
