### ISSUE TITLE
Elsa 2 - UI - dialog box save and cancel buttons - tailwindcss

### ISSUE THREAD

**Issue by matt4446** [elsa-workflows/elsa-core#942]
I might have a few more tailwindcss classes turned on (or different version - latest) than the dashboard application but the two buttons have slightly different rules which make them a little inconsistent: 

![image](https://user-images.githubusercontent.com/1550939/117438497-87b15d80-af29-11eb-820b-858db59fec94.png)
The save button is a bit bigger due to mt-3 on the cancel button and the save just fills the space the cancel has created, but I don't see a reason for it being there. 
eg: cancel button minus mt-3:
![image](https://user-images.githubusercontent.com/1550939/117440861-846ba100-af2c-11eb-9bbc-9afb92e73367.png)

Or both to have mt-3 for a little more distance in the footer: 
![image](https://user-images.githubusercontent.com/1550939/117440801-7289fe00-af2c-11eb-9baf-93d0e806c083.png)

**Comment by sfmskywalker** [comment]
I’m happy to get rid of the mt-3 class.
