### ISSUE TITLE
Elsa 2 - Variable declaration in settings not saving

### ISSUE THREAD

**Issue by riatdyl** [elsa-workflows/elsa-core#943]
Hello,

When I declare a variable in the settings of the workflow, it isn't save when I reload the page.

I don't know if I do it wrong.

Here's a screenshot : 
![image](https://user-images.githubusercontent.com/43779018/117444937-67d66580-af3a-11eb-88a3-8f1e738a9783.png)

And just after reload there's nothing there.

**Comment by riatdyl** [comment]
I also have this problem when I try to enter html text, it doesn't save.

In javascript there's no problem.

This does not save :
![image](https://user-images.githubusercontent.com/43779018/117445785-6b1e2100-af3b-11eb-92ab-a3a97b9999a5.png)

This is saving :
![image](https://user-images.githubusercontent.com/43779018/117445835-7e30f100-af3b-11eb-8328-925cfc92672e.png)

**Comment by sfmskywalker** [comment]
The Settings one I was aware of, but the HTTP Activity one is new to me.

**Comment by riatdyl** [comment]
Hello, I found out that it is a display problem. The text entered in HTML is executing in the browser, but not displaying in the designer.

**Comment by sfmskywalker** [comment]
That makes sense. Indeed the HTTP Response activity needs to be updated such that it displays (part of) the Content value.

**Comment by sfmskywalker** [comment]
I can no longer reproduce any of the issues here, so closing the issue. Please feel free to reopen if you do still see them after updating to the latest version from MyGet or master.
