### ISSUE TITLE
Elsa 2 - Impossible to create a fork activity with outcomes

### ISSUE THREAD

**Issue by riatdyl** [elsa-workflows/elsa-core#944]
Hello,

I'm trying Elsa 2 and I have a problem.

In Elsa 1, the fork activity is working and makes me 2 outcomes.

In the Elsa 2 Workflow, I can place a fork activity and give it two branches. The problem is that this does nothing.

![image](https://user-images.githubusercontent.com/43779018/117139838-ff0db280-adac-11eb-86c0-c0829a6ceaab.png)
![image](https://user-images.githubusercontent.com/43779018/117139882-0634c080-adad-11eb-8d32-242d09f7a969.png)

_Originally posted by @riatdyl in https://github.com/elsa-workflows/elsa-core/discussions/934_

**Comment by sfmskywalker** [comment]
Thank you for creating an issue. This is indeed a bug that needs fixing.

**Comment by riatdyl** [comment]
Okay, I tried with the latest version of Elsa 2 and it's working.

**Comment by sfmskywalker** [comment]
Thanks for confirming!
