### ISSUE TITLE
Elsa 2 - Designer broken when moving activities

### ISSUE THREAD

**Issue by riatdyl** [elsa-workflows/elsa-core#945]
Hello,

This problem happened to me often when I tried to move activities. Sometimes half of the workflow dissapear, sometimes it's separated in two branches.

Here's an example in screenshots :

So this is the starting point :
![image](https://user-images.githubusercontent.com/43779018/117451591-fc44c600-af42-11eb-82ff-4ac3d57bf91b.png)

And I just move the "ReadLine" activity over the "If/Else", it looks like this :
![image](https://user-images.githubusercontent.com/43779018/117451719-2a2a0a80-af43-11eb-938f-49c39ef11be3.png)

For the moment it's okay, but if I move the "Readline" activity back to the starting point, the "If/Else" activity dissapear :
![image](https://user-images.githubusercontent.com/43779018/117451808-4b8af680-af43-11eb-8600-88f888c9cb42.png)

**Comment by tomy2105** [comment]
It seems to me that you are using an old version of designer :).
New ones doesn't have perpendicular line and doesn't even support moving activities at the moment as far as I know (see https://github.com/elsa-workflows/elsa-core/discussions/918).

**Comment by riatdyl** [comment]
Okay I'll try to install a newer version then :)
