### ISSUE TITLE
Elsa 2 - Cancel saves changes

### ISSUE THREAD

**Issue by riatdyl** [elsa-workflows/elsa-core#946]
Hello,

When I press the "Cancel" button, it saves the changes anyway.

Here, the "Text" field was empty and I'll press the "Cancel" button :
![image](https://user-images.githubusercontent.com/43779018/117452637-49756780-af44-11eb-9280-4b29fe2c8db7.png)

And just after pushing the "Cancel" button :
![image](https://user-images.githubusercontent.com/43779018/117452700-5d20ce00-af44-11eb-9a85-9f0220995081.png)

**Comment by riatdyl** [comment]
Sorry, it's not really saving. If I refresh or publish, the text is not saved.

**Comment by sfmskywalker** [comment]
Yes, there was an issue that caused the entered text to be stored in the component instance, which didn’t get disposed after cancelling out.

This should be fixed however, so maybe there’s a regression. Can you tell me what version of the packages you’re using?

**Comment by riatdyl** [comment]
I downloaded the entire code from the Elsa 2 branch.
