### ISSUE TITLE
Elsa 2 - Problems with Http Endpoint

### ISSUE THREAD

**Issue by doctordaddy** [elsa-workflows/elsa-core#947]
Greetings,
first of all: great project, thanks!

We are currently evaluating Elsa-2 to integrate digital workflows with Asana tasks. That is: 
1. The workflow is initiated by an HTTP POST call generated by one of our IT Assets
2. Asana tasks and subtasks are consistently created by means of Send Http Request
3. The workflow instance then waits for tasks status changes, that are notified through Asana webhook mechanism

Regarding the implementation of points 2 and 3, we are setting Http Response Activities with unique URIs, for multiple workflow instances not to interfere with each other. 

Maybe we set something wrong, however after the task creation the Http Response seems to hang listening. Our simulations of Asana webhook calls to the unique URI set for the workflow instance return HTTP ERROR 400.

Is this an open issue or is it our fault? Do you have any advice for us?

Thanks in advance

**Comment by sfmskywalker** [comment]
I tried the workflow and made a few small adjustments (like invoking https://www.google.com instead of your API endpoints to which I obviously don't have access), but the workflow should be the same in principle.

Initially it wasn't working due to an issue with the `Send HTTP Request` activity where an unhandled exception occurred. But once I fixed that, everything worked.

Here's the workflow definition I used:

[workflow-definition-Webhook-Orchestration.json.zip](https://github.com/elsa-workflows/elsa-core/files/6465624/workflow-definition-Webhook-Orchestration.json.zip)

Here's a quick screen capture:

![start-resume-http-demo](https://user-images.githubusercontent.com/938393/117963185-561d0580-b320-11eb-8610-fb414860d332.gif)

Make sure to update to the latest packages or source code of Elsa (to get the fix I pushed) and let me know if you are still having issues.

**Comment by doctordaddy** [comment]
Hi Sipke,
     thanks a lot for the support. 

By the way, is there a shortcut to get the workflow instante id embedding javascript through the designer?

Thank you in advance.
Nicola

-- 

e-mail:  ***@***.***
mobile: +39 391 4272626
skype: nicola.mezzetti

===================
This communication, that may contain confidential and/or legally privileged information, is intended solely for the use of the intended addressees. Opinions, conclusions and other information contained in this message, that do not relate to the official business of this firm, shall be considered as not given or endorsed by it. Every opinion or advice contained in this communication is subject to the terms and conditions provided by the agreement governing the engagement with such a client. If you have received this communication in error, please notify us immediately by responding to this email and then delete it from your system. Any use, disclosure, copying or distribution of the contents of this communication by a not-intended recipient or in violation of the purposes of this communication is strictly prohibited and may be unlawful.


La presente comunicazione, che potrebbe contenere informazioni riservate e/o protette da segreto professionale, è indirizzata esclusivamente ai destinatari della medesima qui indicati. Le opinioni, le conclusioni e le altre informazioni qui contenute, che non siano relative alla nostra attività caratteristica, devono essere considerate come non inviate né avvalorate da noi. Tutti i pareri e le informazioni qui contenuti sono soggetti ai termini ed alle condizioni previsti dagli accordi che regolano il nostro rapporto con il cliente. Nel caso in cui abbiate ricevuto per errore la presente comunicazione, vogliate cortesemente darcene immediata notizia, rispondendo a questo stesso indirizzo di e-mail, e poi procedere alla cancellazione di questo messaggio dal Vostro sistema. E’ strettamente proibito e potrebbe essere fonte di violazione di legge qualsiasi uso, comunicazione, copia o diffusione dei contenuti di questa comunicazione da parte di chi la abbia ricevuta per errore o in violazione degli scopi della presente.
===================

**Comment by sfmskywalker** [comment]
Not yet, but I will push an update today that will allow you to access the workflow instance ID with the following JavaScript expressions:

```javascript
workflowInstanceId
```

Example used in the **Write Line** activity's **Text** field:

```javascript
`The workflow instance ID is: ${workflowInstanceId}`
```

**Comment by doctordaddy** [comment]
Great, many thanks!

This will be great to generate webhooks specific for each workflow instance.

Kind regards,
Nicola

-- 

e-mail:  ***@***.***
mobile: +39 391 4272626
skype: nicola.mezzetti

===================
This communication, that may contain confidential and/or legally privileged information, is intended solely for the use of the intended addressees. Opinions, conclusions and other information contained in this message, that do not relate to the official business of this firm, shall be considered as not given or endorsed by it. Every opinion or advice contained in this communication is subject to the terms and conditions provided by the agreement governing the engagement with such a client. If you have received this communication in error, please notify us immediately by responding to this email and then delete it from your system. Any use, disclosure, copying or distribution of the contents of this communication by a not-intended recipient or in violation of the purposes of this communication is strictly prohibited and may be unlawful.


La presente comunicazione, che potrebbe contenere informazioni riservate e/o protette da segreto professionale, è indirizzata esclusivamente ai destinatari della medesima qui indicati. Le opinioni, le conclusioni e le altre informazioni qui contenute, che non siano relative alla nostra attività caratteristica, devono essere considerate come non inviate né avvalorate da noi. Tutti i pareri e le informazioni qui contenuti sono soggetti ai termini ed alle condizioni previsti dagli accordi che regolano il nostro rapporto con il cliente. Nel caso in cui abbiate ricevuto per errore la presente comunicazione, vogliate cortesemente darcene immediata notizia, rispondendo a questo stesso indirizzo di e-mail, e poi procedere alla cancellazione di questo messaggio dal Vostro sistema. E’ strettamente proibito e potrebbe essere fonte di violazione di legge qualsiasi uso, comunicazione, copia o diffusione dei contenuti di questa comunicazione da parte di chi la abbia ricevuta per errore o in violazione degli scopi della presente.
===================

**Comment by sfmskywalker** [comment]
You got it!

Yeah makes sense.
I just pushed an update, which means it should be available from MyGet once this [build finishes](https://ci.appveyor.com/project/sfmskywalker/elsa/builds/39147461).

I also updated [the docs](https://elsa-workflows.github.io/elsa-core/docs/next/expressions/expressions-javascript#workflowinstanceid).
