### ISSUE TITLE
Add legend on designer with keys and gestures to operate the designer

### ISSUE THREAD

**Issue by sfmskywalker** [elsa-workflows/elsa-core#954]
Background: #952

The legend might display something like the following:

* Delete connections: RIGHT-click the connection to delete.
* Connect outcomes to existing activity: Press and hold SHIFT while LEFT-clicking the outcome to connect. Release SHIFT and LEFT-click the target activity.
* Pan: click anywhere on the designer and drag mouse.
* Zoom: Use scroll-wheel on mouse.

**Comment by tomy2105** [comment]
Yes, that would be extremely helpful :).
