### ISSUE TITLE
Activity execution time logged into debug log in LogWorkflowExecution class

### ISSUE THREAD

**Issue by tomy2105** [elsa-workflows/elsa-core#956]
Maybe I am wrong about this, but wanted to make sure.

It seems to me that activity execution time logged in LogWorkflowExecution is always 0.
And I think it happens because for each time MeaditR pushes some notification new LogWorkflowExecution is created.
Hence you get different LogWorkflowExecution instances when starting a stopping watch inside it and it always logs 0.

As said, maybe I'm completely wrong here but that is what my debugger seems to indicate to me :).
So, the root question here is, how often are instances of LogWorkflowExecution created?

**Comment by sfmskywalker** [comment]
Actually, activity execution time (as in: duration) itself isn't logged anywhere; instead, the execution *timestamp* is recorded when an `WorkflowExecutionLogRecord` instance is created.

These records are created when:

1. An activity is about to execute, and:
2. When an activity finished executing.

The journal in the UI then simply takes the timestamp of the second event and subtracts the timestamp of the previous event, giving a delta:

![image](https://user-images.githubusercontent.com/938393/117672455-277d1e80-b1aa-11eb-98b3-00d0417f2e05.png)

In the above screenshot you see two records and their timestamps (although it doesn't display the milliseconds part). The difference between these timestamps in the example is `32ms`.

Perhaps I misunderstood the question, let me know If I did.

**Comment by sfmskywalker** [comment]
Ah, I see now :)

Yes that makes sense actually. Even though this is a single class, probably a new instance is created per notification type (even if using the Scoped lifetime). Then indeed the elapsed time will always be 0.

Nice catch! For now I will just remove this code - I added it at some point to troubleshoot something.
