### ISSUE TITLE
Elsa 2 - Custom activity error

### ISSUE THREAD

**Issue by riatdyl** [elsa-workflows/elsa-core#961]
Hello,

I copied/pasted the code from the documentation and I have the following error :
![image](https://user-images.githubusercontent.com/43779018/117778038-82138a80-b23d-11eb-9847-7f1a744d1524.png)

The code is from : https://elsa-workflows.github.io/elsa-core/docs/extensibility/extensibility-custom-activities#hello-world-activity

I think the problem may come from this sentence that says I have to implement the `OnExecute` method but I do not know how.
>Implement/override the OnExecute/OnExecuteAsync and if necessary the OnResume/OnResumeAsync methods.

**Comment by sfmskywalker** [comment]
My bad - it should be `ActivityExecutionContext` and not `WorkdlowExecutionContext`. Will update the code. Thanks!

**Comment by riatdyl** [comment]
Okay thanks this works but I have another error in the `Startup.cs file` :
![image](https://user-images.githubusercontent.com/43779018/117785041-7aa3af80-b244-11eb-979c-fd6928b36369.png)

This code is from : https://elsa-workflows.github.io/elsa-core/docs/extensibility/extensibility-custom-activities#registering-activities

**Comment by sfmskywalker** [comment]
> Okay thanks this works but I have another error in the `Startup.cs file` :
> ![image](https://user-images.githubusercontent.com/43779018/117785041-7aa3af80-b244-11eb-979c-fd6928b36369.png)
> 
> This code is from : https://elsa-workflows.github.io/elsa-core/docs/extensibility/extensibility-custom-activities#registering-activities

Another good catch - will update sample right away.

**Comment by sfmskywalker** [comment]
I'm seeing more issues with this page - bear with me as I fix them.

**Comment by riatdyl** [comment]
No problem. It's nice to see that you're involved in your work. Keep it up ! :p

**Comment by riatdyl** [comment]
Nice ! The first method works.

I have an other question, how can I make an assembly from an `Activities.cs` file containing every custom activities ?

It's to use it like this :
> Alternatively, you can register all activities from an assembly using the following extension method:
`services.AddElsa(elsaOptions => elsaOptions.AddActivitiesFrom<TMarkerType>()); // TMarkerType is any type in the assembly from which you want to find and register activities.`
