### ISSUE TITLE
Composite Activity and Workflow Instance viewer problems. 

### ISSUE THREAD

**Issue by tomy2105** [elsa-workflows/elsa-core#966]
I did a composite activity and I have **two problems** when going into Workflow instance viewer.

First, it displays activity name and not description in the flow displayed.

Second, as viewer loads I have an **System.NullReferenceException** (which is displayed in console and caught by debugger) as if activity tried to execute again but failed since its properties were not provided (were null).

**Comment by sfmskywalker** [comment]
The first issue is a good one to fix,

The second issue I believe is expected I believe, as the engine tries to invoke various activity property setters. But if these lambdas try to access things that don't exist in this lifecycle, exceptions will occur.

In any case, if you could share your composite activity then I can take a look to ascertain that everything is in order or if there is indeed a real issue.

**Comment by sfmskywalker** [comment]
Fixed in 999189c1dc060c342e5f1d0ae0f9b17b4095979d
