### ISSUE TITLE
Elsa 2 Designer - Cannot set JavaScript Variable

### ISSUE THREAD

**Issue by Aoshua** [elsa-workflows/elsa-core#971]
After setting up the designer as mentioned in [this example](https://elsa-workflows.github.io/elsa-core/docs/next/quickstarts/quickstarts-aspnetcore-server-dashboard-and-api-endpoints), I am not able to type text in the "Value" input of the "Set Variable" modal. Here are the console errors I see:

![Image of error](https://github.com/Aoshua/Photo_References/blob/master/Elsa%20Core/Errors/Screenshot%202021-05-11%20162010.png?raw=true)

**Comment by sfmskywalker** [comment]
I forgot to update the documentation. The Monaco lib path attribute needs to be updated. If you look at the AspNetCore Monolith Dashboard sample source code in _Host.cshtml you’ll find the correct value.

**Comment by sfmskywalker** [comment]
The correct markup for the Elsa web component in `_Host.cshtml` should be: `<elsa-studio-root server-url="@serverUrl" monaco-lib-path="_content/Elsa.Designer.Components.Web/monaco-editor/min"></elsa-studio-root>`.

**Comment by sfmskywalker** [comment]
The documentation was updated and the issue does not reproduce for me, so closing out the issue. Please feel free to reopen if you are still having issues with the script editor after updating to the latest packages from MyGet or master.
