### ISSUE TITLE
Elsa 2 - Nothing works after update

### ISSUE THREAD

**Issue by riatdyl** [elsa-workflows/elsa-core#972]
Hello,

I downloaded the latest version of Elsa 2  (10 minutes ago).

I tried to run the program in `src/samples/dashboard/aspnetcore` named `ElsaDashboard.Samples.AspNetCore.Monolith`.

Yesterday every tabs were working but today it looks like everything is broken.
If I want to open a tab, nothing is happening. If I refresh the page, there's only this displaying : 
![image](https://user-images.githubusercontent.com/43779018/117927275-44c10280-b2fa-11eb-962b-b8126d56939a.png)

I was able to import my workflow from yesterday and it appears but I can't edit the activities in it.
![image](https://user-images.githubusercontent.com/43779018/117927137-16432780-b2fa-11eb-8c7e-5316fdb3bb2a.png)

Once I tried to edit an activity, nothing works unless I refresh the page.

**Comment by sfmskywalker** [comment]
What happens if you rebuild the client assets?

**Comment by riatdyl** [comment]
I used `npm install` and `npm run build` in :
- src\designer\elsa-workflows-studio
- src\designer\bindings\aspnet\Elsa.Designer.Components.Web
- src\dashboards\blazor\ElsaDashboard.Application

And I just tried to re-download the code an re-run npm but it is still the same.

**Comment by riatdyl** [comment]
I have these errors in the browser's debugger : 
![image](https://user-images.githubusercontent.com/43779018/117951808-d178ba00-b314-11eb-9e2b-9570cf8835bd.png)

**Comment by sfmskywalker** [comment]
Interesting. So, I just downloaded the repo myself into a fresh directory, and for me everything works as expected.
To make sure you didn't miss a step, I just pushed a couple of build scripts and updated the README file with instructions.

Perhaps you can try out these steps:

1. Clone or download the latest version of the repo again (make sure you're using the `master` branch).
2. Open a Windows Terminal or PowerShell window and run `.\build-assets-and-run-dashboard-monolith.ps1` from the root directory where you downloaded the source (this is the same directory that contains the README.md file).

Building the client assets and the project might take more than a few minutes, but when done you should be able to access the dashboard at https://localhost:15265/

Alternatively (or additionally), you can try running the docker compose file if you have Docker installed using the following command: `.\build-and-run-dashboard-monolith-with-docker.ps1`

**Comment by riatdyl** [comment]
I tried to run the command but this happens : 
![image](https://user-images.githubusercontent.com/43779018/117966135-dbee8000-b323-11eb-9caa-d0dbfcffc03d.png)

A notepad is opening with text in it.

**Comment by riatdyl** [comment]
It is working this way ! I managed to import my old workflow and it's also working :)
Thank you !
