### ISSUE TITLE
[Elsa 2] - EF Core PostgreSQL Persistence - Error when running flow

### ISSUE THREAD

**Issue by tmhanus** [elsa-workflows/elsa-core#980]
Hello, 

I'm very happy to see so much progress done on Elsa 2. Looks great! 👏 👏 

I wanted to ask about the state of the EF Core PostgreSql persistence.

I'm getting an error when I'm trying to run my flows. Also I tried it on simple example flow as you can see below ( HelloWorld flow in Elsa.Samples.Persistence.EntityFramework)

`await _buildsAndStartsWorkflow.BuildAndStartWorkflowAsync<MyFlow>(cancellationToken: cancellationToken);`
```
public class MyFlow : IWorkflow
    {
        public void Build(IWorkflowBuilder builder) => builder
            .WithPersistenceBehavior(WorkflowPersistenceBehavior.WorkflowBurst)
            .WriteLine("Hello World!");
    }
```

```
services.AddElsa(x =>
            {
                x.UseEntityFrameworkPersistence(p => p.UsePostgreSql(Configuration.GetConnectionString("Elsa")),
                    autoRunMigrations: true);
                x.AddConsoleActivities();
                x.AddWorkflow<MyFlow>();
            });
```

It fails with following exception:
![image](https://user-images.githubusercontent.com/12475341/118247165-277b6800-b4a3-11eb-99a5-2cfab1f06994.png)

Callstack points here: 
![image](https://user-images.githubusercontent.com/12475341/118247350-60b3d800-b4a3-11eb-9049-67435064cfdc.png)

Also I want to **highlight** that workflow definitions are created in DB without problem. Also even when I'm getting this error above, instance is created in DB with status Idle. 

Versions used:
.nuget\packages\elsa\2.0.0-rc2.73
.nuget\packages\elsa.persistence.entityframework.core\2.0.0-rc2.73
.nuget\packages\elsa.persistence.entityframework.postgresql\2.0.0-rc2.73

Thanks for your attention and I'm looking forward to your reply.

**Comment by sfmskywalker** [comment]
Might be an issue with the `EFCore.BulkExtensions` support for Postgres.

**Comment by sfmskywalker** [comment]
It's indeed a limitation with EFCore.BulkExtensions for Postgres: https://github.com/borisdj/EFCore.BulkExtensions/issues/67.

I'll implement a workaround for the time being.

**Comment by mauordonez** [comment]
@sfmskywalker Elsa is a great project. Thanks for the hard work. I'm also experiencing the same issue described above. I'm wondering if you've got the chance to implement any workaround for this. Have you ever seen MartenDB? https://martendb.io/
 This could a good workaround.
