### ISSUE TITLE
Workflow execution and expression evaluation error

### ISSUE THREAD

**Issue by tomy2105** [elsa-workflows/elsa-core#983]
Currently if there is and JavaScript expression evaluation error, a warning is issued in console/log and workflow continues executing.

From perspective of a user using designer to design workflows this is utterly confusing (IMHO :)).
The Javascript evaluation error is not show anywhere where such a user would look (he only uses web and doesn't see console/log).

I think it would be:
1. Extremely helpful if this error could be made part of Workflow Instance Journal
2. Good to Fault workflow execution when expression evaluation error occurs and not continue execution

Can you please let me know what you think (or implement this if you agree with me :)).

BTW, can my end application somehow customize Elsa core behavior and implement any of the above without modifications to Elsa code?

**Comment by sfmskywalker** [comment]
Makes all sense to me.

**Comment by tomy2105** [comment]
Since it will, understandably, take some time for you to do this, is there a way an end application can somehow customize Elsa core behavior and implement any of the above without modifications to Elsa code?

**Comment by sfmskywalker** [comment]
Yeah I think if you replace the `IExpressionEvaluator` with your own implementation, you can just let any exceptions bubble up instead of catching & ignoring as is done now. But I'm working on this now to see if it would be enough to just rethrow and let the workflow fault because of it.

**Comment by sfmskywalker** [comment]
Yeah seems to work fine actually. I'll push and see what happens.

**Comment by sfmskywalker** [comment]
I'll close this for now, but feel free to reopen if needed.
