### ISSUE TITLE
Triger workflows with http asynchronously

### ISSUE THREAD

**Issue by badihi** [elsa-workflows/elsa-core#985]
I'm looking for a way to invoke a long-running workflow with http. So the connection closes immediately after calling the http endpoint (and maybe returns an id of the started instance), and the execution continues in background,

Is there anyway to do this in Elsa 2?

**Comment by sfmskywalker** [comment]
Yep, this feature was just merged today 🥳 .

To invoke a long-running HTTP workflow, simply supply the `x-dispatch` query string parameter or as a request header.
Sample:

```
/my-http-workflow?x-dispatch
```
