### ISSUE TITLE
Small correction in -> Guides Document Approval

### ISSUE THREAD

**Issue by atorres16** [elsa-workflows/elsa-core#986]
[Documentation](https://elsa-workflows.github.io/elsa-core/docs/next/guides/guides-document-approval) says

![image](https://user-images.githubusercontent.com/19210281/118347608-334e4500-b50a-11eb-8660-4cf67f7bbb7c.png)

I had to add the "Http" property below to appsettings.json

```json
    "Elsa": {
        "Server": {
            "BaseAddress": "http://localhost:15265"
        },
        "Smtp": {
            "Host": "localhost",
            "Port": "25",
            "DefaultSender": "noreply@acme.com"
        },
        "Http": {
            "BaseUrl": "http://localhost:15265"
        }
    }
```

Otherwise:

![image](https://user-images.githubusercontent.com/19210281/118347586-0dc13b80-b50a-11eb-910f-a07b492991bd.png)

**Comment by sfmskywalker** [comment]
Great catch. The actual issue was that we need to specify `BaseUrl` when binding against `HttpActivityOptions`. The documentation should be good now. Thanks for reporting.
