### ISSUE TITLE
myget feeds 503

### ISSUE THREAD

**Issue by Nico-VanHaaster** [elsa-workflows/elsa-core#99]
We experienced a 503 from the myget feeds for the better part of the day today. I understand this is not in your hands however I was wondering if there are any plans to migrate to Nuget for releases?

**Comment by jamesdoran** [comment]
+1 for this please, can still be pre-release

**Comment by sfmskywalker** [comment]
Sorry to hear about the MyGet troubles. There's a couple more ducks I need to get into a row, after which I'll setup the build pipeline to deploy master releases to NuGet. If all goes well this should happen around the weekend.

**Comment by sfmskywalker** [comment]
Alright, 1.0.0-rc2 has been released! 🎉 It's available on NuGet.

The develop branch remains to be deployed to MyGet, but merges to master will be automatically deployed to NuGet.

**Comment by jamesdoran** [comment]
This is big news! Great work.

**Comment by Nico-VanHaaster** [comment]
Great work! Thank you!
