### ISSUE TITLE
HTTP Endpoint request body parsing is not working

### ISSUE THREAD

**Issue by tomy2105** [elsa-workflows/elsa-core#994]
Latest elsa 2 from code.

Simple HTTP Endpoint with handling Post and Read Content checked.
Next activity checks following condition "input.Body == null".

Triggered with following Curl request (simple form post):
curl -X POST -k -H 'Content-Type: application/x-www-form-urlencoded' -i https://localhost:15265/test --data Test=TestMeNow

Condition "input.Body == null" evaluates to True.

It all worked on Friday :).

I believe the problem is in the following file in HTTPRequestMiddleware.cs:

            var commonInputModel = new HttpRequestModel(
                new Uri(request.Path.ToString(), UriKind.Relative),
                request.Method,
                request.Query.ToDictionary(x => x.Key, x => x.Value.ToString()),
                request.Headers.ToDictionary(x => x.Key, x => x.Value.ToString())
            );

            var orderedContentParsers = contentParsers.OrderByDescending(x => x.Priority).ToList();
            var simpleContentType = request.ContentType?.Split(';').First();
            var contentParser = orderedContentParsers.FirstOrDefault(x => x.SupportedContentTypes.Contains(simpleContentType, StringComparer.OrdinalIgnoreCase)) ?? orderedContentParsers.Last();

            foreach (var pendingWorkflow in pendingWorkflows)
            {
                var pendingWorkflowInstance = pendingWorkflowInstances[pendingWorkflow.WorkflowInstanceId];
                var workflowBlueprintWrapper = workflowBlueprintWrappers[pendingWorkflowInstance.DefinitionId];
                var activityWrapper = workflowBlueprintWrapper.GetActivity<HttpEndpoint>(pendingWorkflow.ActivityId!);
                var readContent = await activityWrapper!.GetPropertyValueAsync(x => x.ReadContent, cancellationToken);
                var inputModel = commonInputModel;

                if (readContent)
                {
                    var targetType = await activityWrapper.GetPropertyValueAsync(x => x.TargetType, cancellationToken);
                    inputModel = inputModel with { Body = await contentParser.ParseAsync(request, targetType, cancellationToken) };
                }

                if (useDispatch)
                    await workflowLaunchpad.DispatchPendingWorkflowAsync(pendingWorkflow, inputModel, cancellationToken);
                else
                    await workflowLaunchpad.ExecutePendingWorkflowsAsync(pendingWorkflows, commonInputModel, cancellationToken);
            }

As you can see only `inputModel` will include parsed body, `commonInputModel` won't. So if `useDispatch` is false, body will not be used.

If I change `commonInputModel` to `inputModel` in last `else`, then it works.
However, since I don't know the intention of original programmer I don't know if this simple fix is correct or not.

Can you please fix or advise if I was doing something wrong, thanks.

**Comment by sfmskywalker** [comment]
Nice catch! Yes, it is as simple as you say: we just need to pass along the right variable (`inputModel`) which contains the appropriately parsed body.

Will fix 💪🏻
