### ISSUE TITLE
The Activities dependancy injection has stopped working.

### ISSUE THREAD

**Issue by JamesNJonesIII** [elsa-workflows/elsa-core#996]
At start up I created a extension with this signature  

public static ElsaOptionsBuilder AddPluginActivities(this ElsaOptionsBuilder elsaOptions) which calls  elsaOptions.AddActivitiesFrom(pluginLib);

This was working on rc2.76. but has now stopped working.

**Comment by sfmskywalker** [comment]
Can you explain what you mean with "stopped working"?  Do you mean it no longer registers the activities from your plugin lib? As a sanity check, can you see what happens if you try `AddActivitiesFrom()` using the assembly of the application itself? Does it register your activities (create one temporarily within your application for testing) then?

**Comment by JamesNJonesIII** [comment]
Hi , By not working I mean my plugins no longer show in the designer, the point at which the user can select an activity to add. By the looks of the latest code release, it looks like we need to use an IActivityBuilder is that correct?

**Comment by sfmskywalker** [comment]
I see. That's odd, I don't think I changed anything related to registering activities, regardless of how assemblies are loaded. Is there any chance you can provide me with a repro that I can investigate?

You should not have to use `IActivityBuilder` to implement custom activities. It's a type that is used when using the Workflow Builder API, but not something you would use explicitly. In addition, it's unrelated to activity registration with Elsa.

**Comment by JamesNJonesIII** [comment]
**This is the extension for loading the plugins:**

namespace app.extensions
{
    public static class ElsaPluginExtensions
    {

        private static void GetPlugins(string path,  List<string> pluginsList)
        {
            var dir = new System.IO.DirectoryInfo(path);
            var files = dir.GetFiles("*.dll");

            foreach (var file in files)
            {
                pluginsList.Add(file.FullName);
            }

            foreach (var subDir in dir.GetDirectories())
            {
                GetPlugins(subDir.FullName, pluginsList);
            }
        }
        private static void LoadPlugins(IEnumerable<string> pluginList, ElsaOptionsBuilder elsaOptions)
        {
            var pluginBasePath = $@"{AppDomain.CurrentDomain.BaseDirectory}\Plugins\";
            foreach (var plugin in pluginList)
            {
                              
                    var location = $"{pluginBasePath}{plugin}";
                    var loadContext = new DynamicAssemblyLoader(location);

                    AssemblyName assemblyName = new AssemblyName(Path.GetFileNameWithoutExtension(location));
                    Assembly pluginLib = loadContext.LoadFromAssemblyName(assemblyName);
                    
                    elsaOptions.AddActivitiesFrom(pluginLib);                
            }
        }

        public static ElsaOptionsBuilder AddPluginActivities(this ElsaOptionsBuilder elsaOptions)
        {
            var pluginPath = $@"{AppDomain.CurrentDomain.BaseDirectory}\Plugins\";
            var pluginList = new List<string>();

            GetPlugins(pluginPath,pluginList);
            LoadPlugins(pluginList, elsaOptions);

            return elsaOptions;
        }
    }
}


**This is the assembly loader:**

using System;
using System.Reflection;
using System.Runtime.Loader;

namespace app.extensions
{

    public class DynamicAssemblyLoader : AssemblyLoadContext
    {
        private AssemblyDependencyResolver _resolver;

        public DynamicAssemblyLoader(string assemblyLocation)
        {
            _resolver = new AssemblyDependencyResolver(assemblyLocation);
        }

        protected override Assembly Load(AssemblyName assemblyName)
        {
            string assemblyPath = _resolver.ResolveAssemblyToPath(assemblyName);
            if (assemblyPath != null)
            {
                return LoadFromAssemblyPath(assemblyPath);
            }

            return null;
        }

        protected override IntPtr LoadUnmanagedDll(string unmanagedDllName)
        {
            string libraryPath = _resolver.ResolveUnmanagedDllToPath(unmanagedDllName);

            if (libraryPath != null)
            {
                return LoadUnmanagedDllFromPath(libraryPath);
            }

            return IntPtr.Zero;
        }
    }
}


**This is the activity:**
using Elsa;
using Elsa.ActivityResults;
using Elsa.Attributes;
using Elsa.Services;
using Elsa.Services.Models;
using System;

namespace Test.Activities
{
    [Activity(Category = "Test1", Description = "Test Activity", Outcomes = new[] { OutcomeNames.Done })]
    public class TestActivity : Activity
    {
        [ActivityProperty(Hint = "Enter an directory to monitor.")]
        public string MonitorDirectory { get; set; }


        protected override IActivityExecutionResult OnExecute(ActivityExecutionContext context)        
        {

            var outcomeName = "Done";
            context.SetVariable("TA1", "James");
            context.SetVariable("TA2", DateTime.Now.ToString("yyyy-MM-dd hh:mm"));
            return Outcome(outcomeName);
        }
    }
}





Here's a basic activity (nothing special here really)
 [Activity(Category = "Weightmans", Description = "Test Activity 3", Outcomes = new[] { OutcomeNames.Done })]
    public class Test3Activity : Activity
    {
        [ActivityProperty(Hint = "Enter an directory to monitor.")]
        public string MonitorDirectory { get; set; }


        protected override IActivityExecutionResult OnExecute(ActivityExecutionContext context)
        {


            var outcomeName = "Done";

            return Outcome(outcomeName);
        }
    }

**Comment by sfmskywalker** [comment]
I have to look into it more later, but the root issue seems to be that the dynamically loaded activity types' `IActivity` type is different from the one provided by the host, causing this predicate to not match:

`t.GetInterfaces().Contains(@interface)`

Where `@interface` is `typeof(IActivity)` provided by the host application, and `t` is the activity type loaded dynamically.
Even though `TestActivity` implements `IActivity` provided via a project reference to `Elsa.Core`, .NET seems to think it's a different type than `IActivity`. Must have something to do with the way the assembly is loaded.

It's more or less the issue described here it seems: https://github.com/dotnet/runtime/issues/13469

I'll circle back to this later, but perhaps this rings some bell to you as you seem to have a bit more experience with dynamically loaded assemblies than I have.

**Comment by sfmskywalker** [comment]
When I change assembly loading from:

`Assembly pluginLib = loadContext.LoadFromAssemblyName(assemblyName);`

To:

`Assembly pluginLib = Assembly.LoadFile(location);`

Then it works.

So it has something to do with the way you are loading assemblies and possibly their dependencies via the `AssemblyDependencyResolver` and your `DynamicAssemblyLoader`.

I don't see how this is an issue with Elsa itself. But if we need to change something to make it work, do let me know.

**Comment by sfmskywalker** [comment]
This may be helpful too: https://docs.microsoft.com/en-us/dotnet/core/dependency-loading/understanding-assemblyloadcontext#how-are-dependencies-shared

**Comment by JamesNJonesIII** [comment]
Thanks for that that now gets the main activity libraries loading. So I do just need to workout what libraries are need by the plugin, but are not already loaded. Hoping this is the answer: https://docs.microsoft.com/en-us/dotnet/api/system.appdomain.getassemblies?view=net-5.0


Thanks once again for the help and fast response.

**Comment by sfmskywalker** [comment]
No problem.  I'll close this issue, but let's open a separate issue in case we need to make changes.
